azure-pipelines.yml, src/Razor/src/Directory.Build.props, src/Razor/src/Microsoft.NET.Sdk.Razor/Microsoft.NET.Sdk.Razor.csproj
Adds asset publishing to dotnet-core blob feed to our builds. Based on
instructions at https://github.com/dotnet/arcade/blob/master/Documentation/DependencyFlowOnboarding.md
=> Add asset publishing

azure-pipelines.yml
The build is currently failing during publishing to the dotnet-core blob
feed. I think the reason why it's failing is that we're trying to
publish assets for multiple platforms/configurations. 
We only care about publishing windows/release.
=> Fix issue with blob publishing

src/Razor/startvs.cmd, startvs.cmd
I got this idea from @nguerrera. You should be able to run "startvs.cmd" in src/Razor (or even double click it) and get an instance of Visual Studio with the right env vars set to use the right .NET Core SDK versions.
=> Add a script for starting Visual Studio with the right environment vars

Directory.Build.props, azure-pipelines.yml, eng/Versions.props, eng/build-no-publish.cmd, eng/publish.cmd, global.json
Removes the workaround we needed to fix symbol publishing when running
on full MSBuild dotnet/arcade#1425
=> Update Arcade and remove workaround

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlMarkupParser.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/InternalSyntax/SyntaxListBuilderOfT.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/InternalSyntax/SyntaxListOfT.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/StackGuard.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/SyntaxRewriter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/SyntaxWalker.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/Legacy/HtmlDocumentTest.cs
- Added StackGuard (From Roslyn)
With this change, all of grouping logic for ParseDocument cases is now handled directly in the parser.
I am already working on completely deleting `MarkupElementRewriter` but will send that in a separate PR
=> Partially moved tag grouping logic to the parser

Directory.Build.props, eng/AfterSigning.targets
Attempts to fix a few issues with our VS build and insertion process
First, we're not currently producing Windows pdbs - which we need. I thought I had this turned on, but apparently it was not there.
Secondly, the .vsman file produced by the build doesn't follow our VS versioning scheme. Right now I have to use a hack to fix this, will follow up on a longer term solution later.
=> Attempt to fix symbols and VSIX manifest version

Directory.Build.targets, eng/AfterSigning.targets, eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/RazorDeveloperTools/RazorDeveloperTools.csproj
1. Our dev builds have a smaller build number than our official builds
because they were missing a digit. OOPS
2. The AssemblyInformationVersion was wrong. I'm not sure why this
workaround is required.
=> Fixing issues with VSIX versioning

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Extensions/DesignTimeDirectiveTargetExtension.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt
- This happens because a completion session starts when we've rendered a marker directive token (`@inject_`) without a line pragma and then we return our parse results while a completion session is active with C# content that includes a line pragma. This pull request fixes that.
- Updated tests and verified in VS d16.0stg.
AspNetCore#4810
=> Fix racey directive token auto-complete.

azure-pipelines.yml, eng/Build.props, eng/Versions.props
This change adds a set of workarounds that we need to enable publishing to
BAR from this repo.
1. Workaround the attempt to call the Execute task on every project
2. Force symbol publishing to happen by explicitly passing the option
3. Reenable BAR publishing
=> Enable BAR publishing

.gitignore, eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentDocumentClassifierPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorProjectEngine.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorProjectFileSystem.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorProjectItem.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/FileKinds.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/RazorCodeDocumentExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/RazorProjectEngine.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/RazorProjectItem.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Tools/GenerateCommand.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/Components/ComponentDocumentClassifierPassTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/DefaultRazorProjectEngineIntegrationTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/DefaultRazorProjectItemTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/CodeGenerationIntegrationTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/ComponentCodeGenerationTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/ComponentIntegrationTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/RazorBaselineIntegrationTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/RazorIntegrationTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/SuppressPrimaryMethodBodyntegrationTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/TestRazorProjectItem.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultRazorSyntaxFactsServiceTest.cs
This is a bit of a rework of how we initially set this up, but with more
forethought to how this will work in the project system. I have not yet
surfaced this through VS.
My immediate next step is to light up the component integration tests
and something like this is on the critical path to get that work since
we need a way to specify in tests that a document should be treated as
a component.
=> Flow FileKind from project items -> code document

src/Razor/src/Microsoft.AspNetCore.Razor.Tools/DiscoverCommand.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/CompilerFeatures.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs
We need to be able to wire up these features from outside of the Razor
repo. For layering reasons this can't be done in the main Razor
assembly, so it can't be done by default.
=> Provide a public entry point for Roslyn features

src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorIntermediateNodeLoweringPhase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/DataDashAttribute_ExplicitExpression/TestComponent.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/DataDashAttribute_ImplicitExpression/TestComponent.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/DataDashAttribute_ExplicitExpression/TestComponent.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/DataDashAttribute_ExplicitExpression/TestComponent.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/DataDashAttribute_ImplicitExpression/TestComponent.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/DataDashAttribute_ImplicitExpression/TestComponent.ir.txt
This was missed in the previous attempt to fix data- attributes. HTML
wasn't being translated into the correct IR.
=> Fix lowering of data- with HTML for components

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundParser.cs
- The background thread will eventually go away for Razor once we've moved to only using DocumentSnapshots. Until then, this is a simple stop gap to make identifying threads in Visual Studio easier.
Addresses aspnet/AspNetCore#6171
=> Name Razor's background parser thread.

src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common.csproj, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/Xunit/ForegroundFactDiscoverer.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/Xunit/ForegroundTestCase.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/Xunit/ForegroundTheoryDiscoverer.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/AwaitPeriodInsertionAcceptedProvisionally.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprAcceptsDCIInStatementBlock.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprAcceptsDCIInStatementBlock_1.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprAcceptsDCIInStmtBlkAfterIdentifiers.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprAcceptsDCIInStmtBlkAfterIdentifiers_1.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprAcceptsDCIInStmtBlkAfterIdentifiers_2.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprAcceptsIdentifierTypedAfterDotIfLastChangeProvisional.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAccCaseInsensitiveDCI_NewRoslynIntegration.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAccCaseInsensitiveDCI_NewRoslynIntegration_1.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAccCaseInsensitiveDCI_NewRoslynIntegration_2.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAccCaseInsensitiveDCI_NewRoslynIntegration_3.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAccCaseInsensitiveDCI_NewRoslynIntegration_4.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAcceptsDCI.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAcceptsDCIAfterIdentifiers.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAcceptsDCIAfterIdentifiers_1.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAcceptsDCIAfterIdentifiers_2.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAcceptsDCIAfterIdentifiers_3.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAcceptsDCI_1.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAcceptsDCI_2.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprRejectsAcceptableChangeIfPrevWasProvisionallyAccepted.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExpr_AcceptsParenthesisAtEnd_SingleEdit.stree.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExpr_AcceptsParenthesisAtEnd_TwoEdits.stree.txt, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorProjectHostTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Serialization/ProjectSnapshotHandleSerializationTest.cs
xUnit made a breaking change to some extensibility APIs in 2.4.1 that we
use. Since dotnet/Arcade uses this version to run, it was skipping all
of our [Foreground...] tests :(.
The changes to baselines here are expected. We added a new directive as
part of the components work, but these updates were missed because the
tests weren't being run.
- Detail 1
- Detail 2
Addresses #bugnumber (in this specific format)
=> Update xUnit and fix [Foreground(Fact|Theory)]

eng/Versions.props
We're deciding to use semver1 for the prerelease version of 3.0 since we
shipped preview1 that way. We don't want to swap to semver2 and have
preview2 show up on nuget.org with a *lower* version than we had in
preview1.
We'll go back to semver2 after 3.0 goes RTM
=> Use Semver 1 for packages

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.DesignTime.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Rules/RazorComponentWithTargetPath.xaml, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/Rules/RazorComponentWithTargetPath.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/DesignTimeBuildIntegrationTest.cs, src/Razor/test/testapps/ComponentLibrary/ComponentLibrary.csproj
This is a bug fix for the RazorComponentWithTargetPath xaml rule. We
need to have separate targets for components and views.
The other fix here is a change to the set of workarounds we're using for
components currently. We need this project capability for the correct
project host to be used when loading the project.
=> SDK updates for components tooling

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDirectiveCompletionSource.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/VisualStudioRazorParser.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioRazorParserTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/RazorDirectiveCompletionSourceTest.cs
- Prior to this parses would take the currently available syntax tree and make decisions on if a cursor location was valid to provide directive completions. In the case that you were typing the page directive and you typed `@pa` there were times when the latest code document known was the one for the `@` symbol and a parse was being processed for the `pa` inclusion. Because of this our directive completion would be asked for completions after the `pa` at which point we wouldn't find a valid owner because the syntax tree would be out of date. These changes introduce `GetLatestCodeDocumentAsync` to work around this issue.
- `GetLatestCodeDocumentAsync`uses task completion sources and the already-existing HasPendingChanges flags to ensure that a caller gets the latest code document.
- Added …
=> Wait for parse for directive completion.

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/Assert.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildWithComponentsIntegrationTest.cs, src/Razor/test/testapps/ComponentLibrary/ComponentLibrary.csproj, src/Razor/test/testapps/MvcWithComponents/Components/Counter.cshtml, src/Razor/test/testapps/MvcWithComponents/MvcWithComponents.csproj
Interim solution to allow components to share the .cshtml extension. When declared in
the project file, the SDK will prevent RazorComponent items from being included
in the RazorGenerate itemgroup.
=> Exclude RazorComponent items from RazorGenerate item group

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Configuration.targets
Leading up the release of VS 16.0p1 we added workarounds to the SDK to
make Razor fall back to the 2.1 configuration for design-time. Since
we're adding the 3.0 language support to preview2 we can remove these
workarounds. These features have been available in internal builds for
some time.
=> Remove workarounds for missing 3.0 support

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlMarkupParser.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/Legacy/HtmlTagsTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/HtmlTagsTest/ScriptTag_Incomplete.cspans.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/HtmlTagsTest/ScriptTag_Incomplete.stree.txt
This happens whenever a script tag is seen without any value for the attribute `type`.
=> Fix null ref in the parser

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/TagHelperParseTreeRewriter.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/Legacy/TagHelperParseTreeRewriterTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperParseTreeRewriterTest/HandlesNonTagHelperStartAndEndVoidTags_Correctly.cspans.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperParseTreeRewriterTest/HandlesNonTagHelperStartAndEndVoidTags_Correctly.stree.txt
This happens if you type `<input>Foo</input>`. We fail to keep track of the start tag because it is a void tag.
=> Fixed exception with non taghelper start/end void tags

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/TagHelperParseTreeRewriter.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/Legacy/TagHelperBlockRewriterTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperBlockRewriterTest/AllowsCompatibleTagStructures8.cspans.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperBlockRewriterTest/AllowsCompatibleTagStructures8.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperBlockRewriterTest/AllowsCompatibleTagStructures8.tspans.txt
Fixes https://github.com/aspnet/AspNetCore/issues/6469
This does not cause a crash. I noticed this when investigating the crashing issue.
=> Fix: Missing void end tag when targeted by TH with WithoutEndTag structure

azure-pipelines.yml, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerIntegrationTest.cs
~Just testing if this still fails.~
Looks like we needed to pass `--init` to the docker run command which spins up a PID 1 process that takes care of ending defunct processes in the container.
=> Reenable skipped test

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.DesignTime.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.props
The issue here is that the downlevel SDK (2.1/2.2) don't define the
component-related targets needed for the component design time build.
Depending on the ordering of targets, this can break all features in VS
that depend on the design-time build.
Since we want this to noop in those cases, the best fix is to make our
targets depend on a target property that will be empty in the downlevel
SDKS, but will contain our targets in the 3.0 SDK.
=> Fix DevDiv#763643

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.DesignTime.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.props
The issue here is that the downlevel SDK (2.1/2.2) don't define the
component-related targets needed for the component design time build.
Depending on the ordering of targets, this can break all features in VS
that depend on the design-time build.
Since we want this to noop in those cases, the best fix is to make our
targets depend on a target property that will be empty in the downlevel
SDKS, but will contain our targets in the 3.0 SDK.
=> Fix A VS issue

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentWhitespacePass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/CSharpCodeParser.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/FunctionsBlockMinimal_Runtime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Whitespace_BetweenElementAndFunctions/TestComponent.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/RazorDirectivesTest/BuiltInDirectiveDoesNotErorrIfNotAtStartOfLineBecauseOfWhitespace.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/RazorDirectivesTest/ExtensibleDirectiveDoesNotErorrIfNotAtStartOfLineBecauseOfWhitespace.stree.txt
Fixes https://github.com/aspnet/AspNetCore/issues/6206
Basically when we have whitespace preceding any csharp transition,
```
|    |@if (true) {
}
```
We classify this whitespace as `CSharpStatementLiteral` in runtime which is fine and is the expected behavior. We want it to be generated in the output.
Whereas for a directive,
```
|    |@functions {
}
```
it doesn't make sense for that whitespace to appear in the output. But I was incorrectly classifying it as `CSharpStatementLiteral`. This change special cases directives to correctly classify it.
Note: In design time, in both cases the whitespace will be classified as markup resulting in correct markup intellisense.
=> Correctly handle whitespace that precedes a Razor directive

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/ParserContext.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorComments_DesignTime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorComments_Runtime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorComments_Runtime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/RazorDirectivesTest/DirectiveDescriptor_FileScoped_CanBeBeneathOtherWhiteSpaceCommentsAndDirectives.stree.txt
Found this when investigating https://github.com/aspnet/AspNetCore/issues/6206.
Note: This issue has existed even in the old parser. This is not a regression.
The correct value for `StartOfLine` is `true` when the parsing starts. Before this change cases like a Razor comment at the top of file,
```
@* Some comment *@
<div></div>
```
will output a newline at the start of the document. This fixes it.
This might require us to update the `HtmlGenerationTest` baselines in Mvc. I'll check and send a PR there if necessary.
=> Set ParserContext.StartOfLine to true when parsing starts

azure-pipelines.yml
The problem is that these variables have the wrong definition when
building in the internal repo.
=> Fix .vsman authoring

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs
- The SDK tests were occasionally failing with access denied due to the test using the machines dotnet.exe (instead of the local projects dotnet.exe).
aspnet/AspNetCore#1667
=> Prioritize local dotnet when running SDK Razor tests.

eng/AfterSigning.targets, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- Prior to this, rebuilding the VSIX project would not result it in re-deploying to the experiemental hive.
- Added an AfterSigning target that ensures a VSIX is always built
=> Allow VSIX project to be built on its own.

eng/AfterSigning.targets, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- Prior to this, rebuilding the VSIX project would not result it in re-deploying to the experiemental hive.
- Added an AfterSigning target that ensures a VSIX is always built (only on windows)
Port from release/vs16.0-preview3
=> Allow VSIX project to be built on its own. (#138)

eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Microsoft.VisualStudio.Editor.Razor.csproj
- Retargeted VisualStudio.Editor.Razor to point towards Visual Studio's versions of Roslyn (it lifts).
- VSCode depends on Microsoft.CodeAnalysis.Razor.Workspaces and that entire stack depensd on publicly available bits.
=> Retarget Microsoft.CodeAnalysis.Razor.Workspaces to use public Roslyn packages.

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.DesignTime.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets
* Use _RazorComponentInclude to determine the set of files to set Generator property for
* Run RazorGenerateComponentDeclarationDesignTime instead of RazorComponentGenerate during design time builds
* Update design time targets to set Generator for content files with .razor extension.
Fixes https://github.com/aspnet/AspNetCore/issues/6859
Fixes https://github.com/aspnet/AspNetCore/issues/6860
=> Ensure updates to Razor components trigger design time build

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDirectiveCompletionSource.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorSyntaxTreePartialParser.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/VisualStudioRazorParser.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/StringTextSnapshot.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioRazorParserIntegrationTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioRazorParserTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/RazorDirectiveCompletionSourceTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/RazorSyntaxTreePartialParserTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAcceptsDCIAfterIdentifiers_CompletesSyntaxTreeRequest.cspans.txt, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TestFiles/ParserTests/DefaultVisualStudioRazorParserIntegrationTest/ImpExprProvisionallyAcceptsDCIAfterIdentifiers_CompletesSyntaxTreeRequest.stree.txt
- This change enables our parser to return a background completable task instead of waiting for the document structure notifications on the foreground thread.
- When changing the system to resolve all data on the background thread I ran into several races which triggered severe delays/timeouts/deadlocks when running through completion scenarios. To fix these issues I had to tie into our current partial parsing and snapshot tracking systems to properly complete tasks without crashing VS.
- Had to make a slight hack of returning the latest partially parsed syntax tree which maintains its original diagnostics/source document.
- There were some unrelated issues that result in a completion request aborting mid-flight, because of this changed the API to properly consume a cancellation token.
=> Update Razor parser state on background thread.

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.CodeGeneration.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest21.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest22.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerIntegrationTest.cs, src/Razor/test/testapps/MvcWithComponents/SimpleTagHelper.cs, src/Razor/test/testapps/SimpleMvc21/SimpleTagHelper.cs, src/Razor/test/testapps/SimpleMvc22/SimpleTagHelper.cs
As part of migrating the CodeGeneration targets in to the Razor.Sdk,
the SDK broke the contract that RazorReferencePaths includes the full closure
of assemblies during tag helper discovery.
This change restores the behavior to be compatible with the 2.x Razor.Design
package and adds tests to verify TagHelper discovery works in a range of projects.
Fixes https://github.com/aspnet/AspNetCore/issues/6825
=> Ensure TagHelpers from the current project are discovered for projects targeting 2.x

src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/DefaultProxyAccessor.cs, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/GuestProjectPathProvider.cs, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/ProjectSnapshotSynchronizationServiceFactory.cs, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/ProxyAccessor.cs, src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/DefaultProxyAccessorTest.cs
- Because we need to expose a LiveShare session globally to multiple services there was a situation where if the `GuestInitializationService` was instantiated after the snapshot synchronization service then we wouldn't have access to the current collaboration service via the `LiveShareSessionAccessor`. This is ok though, because in our synchronization service we're already passed the session context which we can just use directly.
- `GuestProjectPathProvider`can't actually return a null guest path if it's asked, so also removed the null coalescing on the `LiveShareSessionAccessor`'s `Session`.
- Fixed tests.
=> Fix global LiveShare session access timing issue.

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj, src/Razor/test/testapps/RestoreTestProjects/RestoreTestProjects.csproj
Fixes https://github.com/aspnet/AspNetCore-Internal/issues/1701
The `dotnet build /restore` that runs as part of running tests makes the tests flaky \ time out when network conditions are poor. This forces a restore as part of build that would download packages required for the restore to later succeed without network I/O.
=> Restore packages as part of build to avoid restore timeouts as part of running tests

eng/Versions.props
Two changes:
* Update packages to 3.0.0-preview3.$(buildnumber) per latest 3.0 plan from the PMs
* Update packages to use SemVerV2 like most other repos are doing. Preview 1 of the packages in this repo were released with SemVer v1 "3.0.0-preview-18579-0056". We didn't update to SemVer v2 like everyone else because semver v2 would have sorted as "older" than 3.0.0-preview-18579-0056. But, now that we're updating the prerelease label to "preview3", semverv2 packages should appear as newer than 3.0.0-preview-18579-0056.
=> Update package branding to use SemVer v2 and set version to 3.0.0-preview3

azure-pipelines.yml, global.json, src/Razor/Razor.Slim.sln, src/Razor/Razor.sln, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.props, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/TestCompilation.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest21.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/PublishIntegrationTest.cs, src/Razor/test/testapps/AppWithP2PReference/AppWithP2PReference.csproj, src/Razor/test/testapps/LargeProject/LargeProject.csproj, src/Razor/test/testapps/MvcWithComponents/MvcWithComponents.csproj, src/Razor/test/testapps/SimpleMvc/SimpleMvc.csproj, src/Razor/test/testapps/SimpleMvcFSharp/SimpleMvcFSharp.fsproj, src/Razor/test/testapps/SimplePages/SimplePages.csproj
Fixes https://github.com/aspnet/AspNetCore/issues/6512
* Verified compatibility with 2.2 projects with runtime compilation using `CopyRefAssembliesToPublishDirectory` flag
* Verified compatibility with 2.1 projects with precompilation
=> Use new PreserveCompilationReferences in Razor Sdk

src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/ProjectSnapshotSynchronizationService.cs, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/ProjectSnapshotSynchronizationServiceFactory.cs, src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/ProjectSnapshotSynchronizationServiceTest.cs
- Collaboration services aren't guaranteed to be invoked in a particular order. If the guest initialization service was not invoked prior to the snapshot synchronization service then the synchronization service would null ref when resolving guest paths because the `LiveShareSessionAccessor.Session` would not be set yet.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/786078
=> Fix LiveShare VS crash.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentBindLoweringPass.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/ComponentBindIntegrationTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/7384
We should also not register some of the directives that are no supported by components. But that can be a separate issue/PR.
=> Fix an assumption in ComponentBindLoweringPass that crashes VS

src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorExcerptServiceTest.cs
- Test is flakey due to https://github.com/dotnet/roslyn/issues/31548
- Tracking issue to ensure we unskip: https://github.com/aspnet/AspNetCore/issues/7713
Addresses https://github.com/aspnet/AspNetCore-Internal/issues/1456
=> Skip flakey test until Roslyn unblocks it.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/LegacySyntaxNodeExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/MarkupTagHelperEndTagSyntax.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/MarkupTagHelperStartTagSyntax.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/SyntaxTreeVerifier.cs
- Added a step to full fidelity verification that does a `LocateOwner` at every source location. If we find a `null` owner we build a snippet with a detailed response to enable us to diagnose the problem.
How the error looks when things are broken:
Addresses aspnet/AspNetCore#7718
=> Make TagHelper & Razor comments locatable at design time.

eng/scripts/CodeCheck.ps1
Workaround https://github.com/dotnet/cli/issues/10845
Apparently DOTNET_SKIP_FIRST_TIME_EXPERIENCE does not actually skip the initial welcome message output.
=> Filter non-project output from `dotnet sln list`

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentLoweringPass.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/ComponentTypingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs
https://github.com/aspnet/AspNetCore/issues/7384
In some malformed cases, when a component attribute contains more than just an expression, we were throwing an exception at place we do `.Single()`.
- Added a test for that scenario.
=> Fixed an assumption in ComponentLoweringPass

azure-pipelines.yml, global.json
Part of https://github.com/aspnet/AspNetCore-Internal/issues/1624
=> Update CI to build with VS2019 Preview 3 and require vs >= 16.0 for command line builds

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultTagHelperCompletionService.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/DefaultTagHelperCompletionServiceTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorExcerptServiceTest.cs
- Since dictionaries fill `TagHelperDescriptor`s with two ways to bind to a `TagHelper` (prefix or full match) we need to take into account their indexer name prefix when providing attribute completions.
- Added tests to ensure that bound and unbound scenarios work as expected.
This results in both `asp-all-route-data` and `asp-route-...` showing up in completion:
Prior to this only `asp-all-route-data` would show up.
#7759
=> Update TagHelper completion to understand dictionary attributes.

Directory.Build.props, Directory.Build.targets, eng/Version.Details.xml, eng/Versions.props, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/BuildVariables.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildIntegrationTestBase.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj, src/Razor/test/testapps/Directory.Build.props
* Update to latest extensions, corefx, and core-setup build
* Workaround dotnet/sdk#2976
* Update xunit to 2.4.1. (required to consume latest Microsoft.AspNetCore.Testing)
* Add workaround to resolve conflicts between SDK and dependency versions
* Remove NETStandard package version override
=> Update dependencies and workaround dotnet/sdk#2976

azure-pipelines.yml, eng/Versions.props
We're getting consistent build timeouts. Changing to a unique feed instead. Each upstream partner will need to add this to restore sources.
=> Change publish feed to workaround 'Waiting to obtain an exclusive lock on the feed.'

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/ProjectSystem/ProjectSnapshotManagerBenchmarkBase.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectWorkspaceStateGenerator.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultTagHelperResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultTagHelperResolverFactory.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TagHelperResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/OOPTagHelperResolverFactory.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DefaultDocumentSnapshotTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DefaultProjectSnapshotTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DocumentStateTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateGeneratedOutputTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorExcerptServiceTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorSpanMappingServiceTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultProjectWorkspaceStateGeneratorTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioDocumentTrackerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultProjectSnapshotManagerTest.cs
- There's nothing specific about the TagHelperResolver that needs to be bound to VS. Moving it to the workspaces assembly so it can be used by VSCode.
=> Move TagHelperResolver to CodeAnalysis.Workspaces

src/Razor/src/Directory.Build.props
[arcade](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L90) already adds 1591 to the list of NoWarn
=> Removed unnecessary NoWarn property

azure-pipelines.yml, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs
- This would cause our functional tests to time out and occasionally crash due to dotnet first run experience sentinels being locked.
aspnet/AspNetCore-Internal#1859
=> Skip first run experience locally and on azure pipelines.

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerIntegrationTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/5104
~The current mutex behavior looks like what we expect. I suspect this was failing earlier in November due to some bug which has since been fixed but we never unskipped the test.~
Modified the test to use a more reliable invalid pipe name.
=> Unskip test

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildPerformanceTest.cs
https://github.com/aspnet/AspNetCore-Internal/issues/1860
This test only ever [failed](https://dnceng.visualstudio.com/public/_build/results?buildId=103959&view=ms.vss-test-web.build-test-results-tab) once on MacOS Release but skipping for a day just in case #greenbuildfriday
=> Temporarily skip test

src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorExcerptServiceTest.cs
aspnet/AspNetCore-Internal#1876 - Porting from master
Test is flakey due to dotnet/roslyn#31548
Tracking issue to ensure we unskip: aspnet/AspNetCore#7768
=> [Port] Skip flakey tests until Roslyn unblocks it.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/CodeGeneration/DocumentWriter.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectChangeEventArgs.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/DefaultTagHelperDescriptorProvider.cs
- The `DocumentWriter` case should never be called because you need to override a lot of the internals of the RazorEngine to get to the document writer. Therefore, little harm in removing the method.
- `ProjectChangeEventArgs` used to be uised by the LiveShare extension. We've since taken ownership of those bits and no longer need to maintain those constructors.
- `DefaultTagHelperDescriptorProvider.DesignTime` didn't actually do anything. Removing since the code was truly dead and did nothing functionally.
- Made the decision to not remove a lot of the obsolete methods we have on RazorEngine because we'd be breaking people for no reason.
aspnet/AspNetCore#7146
=> Remove rarely used public obsolete public API.

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildPerformanceTest.cs
Reverts https://github.com/aspnet/AspNetCore-Tooling/commit/0598ec449702813456129996dc854b75ac64649a
Fixes https://github.com/aspnet/AspNetCore-Internal/issues/1860
Added more logging. Will re-run here for a little while to check if it fails. If not(more likely because this test only ever failed once), I'll merge it and we'll have more info the next time if it fails.
=> Re-enable skipped test

src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorProjectFileSystem.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/DefaultRazorProjectFileSystemTest.cs
Port of the fix from https://github.com/aspnet/AspNetCore-Tooling/pull/298
@rynowak. fyi I am merging this to `release/vs16.0-preview4`. Let me know if you instead prefer we create a separate `release/vs16.0-preview4-servicing` branch.
=> [Port] Correctly normalize file path from network shares (#298)

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/FilePathComparison.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDirectiveCompletionProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/RazorDynamicFileInfoProvider.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/TestProjectWorkspaceStateGenerator.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
- Added a `FilePathComparison` object since not all string methods allow a comparer.
- Updated `RazorDirectiveCompletionProvider` to also understand `.razor` files. This is an edge case scenario where users have disabled modern completion and are using Razor components (you need a reg key to disable the modern completion or MS needs to disable it).
- Tested this in VS by referencing the latest Razor SDK (preview 3) from NuGet and then replacing the Razor design time targets in VS to be the ones from the preview 3 package.
#8064
=> Enable IntelliSense for new component parameters.

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDirectiveCompletionProvider.cs
We don't want `CodeAnalysis.Razor` to load for non-cshtml completions. Referencing `FilePathComparison` makes that assembly to load. This is breaking RPS tests.
=> Don't reference FilePathComparison in RazorDirectiveCompletionProvider

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.props, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets
* Move targets for component design time generation to
Components.targets
* Provide a better error message when referencing a 2.x Razor.Design
package in a 3.0 project
* Do not produce a warning for unresolved configuration when building
2.x projects
Fixes https://github.com/aspnet/AspNetCore/issues/8899
=> Prevent build failures and warnings when building 2.x projects

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/CodeGenerationBenchmark.cs, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/SyntaxTreeGenerationBenckmark.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorProjectFileSystem.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/EmptyProjectFileSystem.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/NotFoundProjectItem.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/RazorProject.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/VirtualRazorProjectFileSystem.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Tools/CompositeRazorProjectFileSystem.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Tools/GenerateCommand.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultImportDocumentManager.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/DefaultRazorProjectFileSystemTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestRazorProject.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/VirtualRazorProjectFileSystemTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/TestRazorProjectFileSystem.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Tools.Test/CompositeRazorProjectFileSystemTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DefaultDocumentSnapshotTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Shared/TestProjectData.cs
- Obsoleted old `GetItem` API.
- Updated tests to take new API.
- Added a new test to verify the broken scenario.
#8972
=> Expand RazorProject.GetItem to take in FileKinds when getting items.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorIntermediateNodeLoweringPhase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ComponentImports/_Imports.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ComponentImports/_Imports.diagnostics.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ComponentImports/_Imports.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ComponentImports/_Imports.mappings.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentImports/_Imports.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentImports/_Imports.diagnostics.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentImports/_Imports.ir.txt
Before this we weren't generating any IR for CSharp code except add errors for them. I'm now generating IR nodes for CSharp that are not part of html attributes.
=> Fix csharp intellisense in _Imports.razor

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultProjectEngineFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorProjectHost.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultRazorProjectHost.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorProjectHostTest.cs, src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/DefaultRazorProjectHostTest.cs
This is a configuration that will be used by the SDK for Components
projects without MVC support. In this case there are no extensions. I
also made the system more tolerant in general of missing extensions and
not fail quite so hard.
=> Add support for 'Default' RazorConfiguration

azure-pipelines.yml, eng/Signing.props
Relates to: https://github.com/dotnet/arcade/issues/2443
Goal: mitigate `lock on the feed problem` and add further validations. [More details here.](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing_HowToUse.md)
Test build was here: https://dnceng.visualstudio.com/internal/_build/results?buildId=150761
Test release: https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=4484
=> Onboard with async publishing

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundParser.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/Documents/VisualStudioMacFileChangeTrackerFactoryFactory.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectBuildChangeTrigger.cs, src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj, src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Properties/_Manifest.addin.xml, src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/RazorAddin.cs
- Noticed I hadn't ported all of the VSMac fixes to the master branch. This is me pulling the remaining fixes to solve obvious blockers to the VS4Mac Razor experience.
- Note: VS4Mac doesn't work with just these set of changes. These changes simply enable VS4Mac to spin up our side of the Razor world and enable us to start parsing documents as users type. To fix the full Razor VS4Mac experience will require changes from other partner teams.
=> Port remaining VSMac blocker fixes.

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets
The newline in the warning messages causes the warning message to appear as two separate warnings in the build output:
```
Microsoft.NET.Sdk.Razor\build\netstandard2.0\Sdk.Razor.CurrentVersion.targets(805,5): warning RAZORSDK1004: One or more Razor view or page files were found, but the project is not configured to add Razor support for MVC. The MSBuild property 'AddRazorSupportForMvc' must be set to correctly
Microsoft.NET.Sdk.Razor\build\netstandard2.0\Sdk.Razor.CurrentVersion.targets(805,5): warning RAZORSDK1004:  compile Razor files that target MVC. For more information, see https://go.microsoft.com/fwlink/?linkid=868374.
```
This change fixes the warning message to appear as a single warning:
```
Microsoft.NET.Sdk.Razor\build\netstandard2.0\Sdk.Razor.CurrentVersion.targets(805,5): …
```
=> Do not split warning message across multiple lines

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Extensions/FunctionsDirectivePass.cs, src/Razor/test/RazorLanguage.Test/Extensions/FunctionsDirectivePassTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/9093
- The crash was because `ComponentLoweringPass` ran before `DirectiveRemovalPass` which means when we a tag helper exists inside a functions directive, there were duplicates.
=> Fix crash in functions block

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/SourceTextExtensions.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DefaultDocumentSnapshotTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/SourceTextExtensionsTest.cs
- In FAR scenarios with large amounts of Razor documents we generate Razor output for every document in the world and then feed that information to Roslyn to populate a set of C# buffers with Razor's generated C# documents. Prior to this we were holding onto all of the data involved in creating that generated C# document; instead we now dereference that data on the `DocumentSnapshot` to allow for GC to do its job. Also did this for excerpt generation to ensure we don't break scenarios where 1 C# reference would result in X number of Razor documents being re-generated and allocate loads of memory.
- Added lots of comments to raise some of the reasons why we clear state in certain places.
- Added tests to ensure we're clearing data in the correct places.
- Added tests to ensure that the new …
=> Dereference Razor document state information in FAR scenarios.

eng/dotnet-install.ps1, eng/dotnet-install.sh
Resolves https://github.com/aspnet/AspNetCore-Internal/issues/2392
This copies improvements from the canonical version of dotnet-install and adds retries to make installing more resilient.
=> Update dotnet-install.ps1/sh scripts and add more retries

azure-pipelines.yml
Sometime between May 1 at 9am and 12pm, Azure Dev ops changed the default value.
=> React to changes in Agent.JobName

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets
The content of `$(GetCopyToOutputDirectoryItemsDependsOn)` was being erroneously overwritten by a typo in the assignment.
The intention by the original contributor would have been to add to the existing GetCopyToOutputDirectoryItemsDependsOn property, defined in Microsoft.Common.Targets. Instead what was happening is that it was being completely overwitten with the _RazorGetCopyToOutputDirectoryItems entry, given that $(GetCopyToOutputDirectoryItems) doesn't exist as a property and must have been a typo (it exists as a task, not a property).
An effect of this bug was that the `AssignTargetPaths` target is not always executed before the `GetCopyToOutputDirectoryItems` target, which should explicitly depend on it. `AssignTargetPaths` is responsible for populating the `ContentWithTargetPath` …
=> Fixed destructive property assignment bug for GetCopyToOutputDirectoryItems task

eng/Versions.props
Part of the workaround for https://github.com/aspnet/AspNetCore-Internal/issues/2476
This also helps us consume new versions of roslyn faster via Arcade update automoation.
=> Use Microsoft.NET.Compilers.Toolset

src/Razor/src/Microsoft.NET.Sdk.Razor/GenerateStaticWebAssetsManifest.cs, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.props, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/GenerateAspNetCoreStaticAssetsManifestTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/Assert.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildIntegrationTestBase.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj, src/Razor/test/testapps/AppWithPackageAndP2PReference/AppWithPackageAndP2PReference.csproj, src/Razor/test/testapps/AppWithPackageAndP2PReference/Program.cs, src/Razor/test/testapps/PackageLibraryDirectDependency/PackageLibraryDirectDependency.csproj, src/Razor/test/testapps/PackageLibraryDirectDependency/build/PackageLibraryDirectDependency.props, src/Razor/test/testapps/PackageLibraryDirectDependency/wwwroot/css/site.css, src/Razor/test/testapps/PackageLibraryDirectDependency/wwwroot/js/pkg-direct-dep.js, src/Razor/test/testapps/PackageLibraryTransitiveDependency/PackageLibraryTransitiveDependency.csproj, src/Razor/test/testapps/PackageLibraryTransitiveDependency/build/PackageLibraryTransitiveDependency.props, src/Razor/test/testapps/PackageLibraryTransitiveDependency/wwwroot/js/pkg-transitive-dep.js, src/Razor/test/testapps/RestoreTestProjects/RestoreTestProjects.csproj
=> Support static assets in the Razor SDK

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentBindLoweringPass.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentCodeGenerationTestBase.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ChildComponent_GenericBind_TypeInference/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ChildComponent_GenericBind_TypeInference/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ChildComponent_GenericBind_TypeInference/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ChildComponent_GenericBind_TypeInference/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ChildComponent_GenericBind_TypeInference/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ChildComponent_GenericBind_TypeInference/TestComponent.mappings.txt
Unblocks https://github.com/aspnet/AspNetCore/pull/10434
Before this I was not differentiating attributes with the same name in two different elements when collecting bind and bind:parameter attributes.
=> Fix bug in bind lowering logic

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs
- The directive completion provider no longer provides completions unless an implicit expression is at the top level (not nested).
- Added tests to validate the new functionality.
This is bullet point 3 of https://github.com/aspnet/AspNetCore/issues/6364#issuecomment-495432347
@ajaybhargavb / @rynowak if you guys can think of any other constructs make sense to ignore let me know.
aspnet/AspNetCore#6364
=> Make Razor directive completion provider more strict.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DefaultRazorCompletionFactsService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItem.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemProvider.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DefaultRazorCompletionFactsServiceTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/RazorDirectiveCompletionProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/RazorDirectiveCompletionSourceTest.cs
- Completions will be coming from multiple different sources in the future and in order to build a system that works in both VSCode, VSWindows and VSMac we need the ability to toggle certain types of completions on and off easily.
- Created a `DirectiveCompletionItemProvider` this was basically a direct copy from the facts service.
- Also moved tests from the facts service over to the new directive completion item provider.
- Made `RazorCompletionItem`s `IEquatable` to ease in testing now and in the future.
This is bullet point 2 of https://github.com/aspnet/AspNetCore/issues/6364#issuecomment-495432347
aspnet/AspNetCore#6364
=> Update completion facts service to use providers.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DefaultRazorCompletionFactsService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionFactsService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItem.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemKind.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDirectiveCompletionProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDirectiveCompletionSource.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDirectiveCompletionSourceProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/VisualStudioRazorParser.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DefaultRazorCompletionFactsServiceTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioRazorParserIntegrationTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioRazorParserTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/RazorDirectiveCompletionProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/RazorDirectiveCompletionSourceProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/RazorDirectiveCompletionSourceTest.cs
- Directive attributes will need more information than just the `SyntaxTree` to make decisions on what completions to show.
- Made a "breaking" change to the `VisualStudioRazorParser`API but no one has used it yet (we're the only ones).
- Moved completion fact bits into their own namespace. We are going to have a lot of completion related bits that will be important for platforms that are trying to implement completion and don't care about the rest of the Razor.Workspaces world.
This is bullet 1 of https://github.com/aspnet/AspNetCore/issues/6364#issuecomment-495432347
aspnet/AspNetCore#6364
=> Enable completion facts service to take RazorCodeDocuments.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/AttributeCompletionDescription.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/AttributeDescriptionInfo.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeParameterCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionDescription.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItem.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemExtensions.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/DefaultVisualStudioDescriptionFactory.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSource.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSourceProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveCompletionProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveCompletionSource.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/VisualStudioDescriptionFactory.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DefaultRazorCompletionFactsServiceTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeParameterCompletionItemProviderTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/DefaultVisualStudioDescriptionFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveAttributeCompletionSourceTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveCompletionSourceTest.cs
- Updated the `RazorCompletionItem` type to no longer contain a `Documentation`/`Description` property because in completion scenarios descriptions are never readily available and don't make a lot of sense being on the completion item itself. This is also how Roslyn does completions.
- We now utilize an item bag on `RazorCompletionItem`s to hold description data. Currently there's just two type of completion descriptions (directive and attribute). Based off of the completion item kind (directive or attribute) we can extract the appropriate description. The goal of this new description type was to represent all data for a completion in an unstructured way so each platform can display it using its own capabilities.
- Added a description factory to convert description items into classified …
=> Add support for directive attribute descriptions

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/AttributeCompletionDescription.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/AttributeDescriptionInfo.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeParameterCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionDescription.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItem.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemExtensions.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemKind.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/DefaultVisualStudioDescriptionFactory.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCommitManager.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSource.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSourceProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveCompletionProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveCompletionSource.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/VisualStudioDescriptionFactory.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DefaultRazorCompletionFactsServiceTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeParameterCompletionItemProviderTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/DefaultVisualStudioDescriptionFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveAttributeCommitManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveAttributeCompletionSourceTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveCompletionSourceTest.cs
- Expanded the directive attribute completion source (the piece that hooks into VS windows) to understand the parameter portion of a directive attribute. When we think we're operating on a directive attribute parameter we now restrict the applicable completion span to just be the parameter portion.
- Added a directive attribute parameter completion provider. This provider only operates on directive attribute parametesr and tries to be smart about the parameter completions it offers.
- Expanded the commit manager to now also handle `:` commits so users can seamless go from completing a directive attribute into completing a parameter.
- Added new tests for the new parameter completion provider, completion source and commit manager.
Note: This is bullet point six of …
=> Add support for directive attribute parameter completions.

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultProjectPathProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultProjectPathProviderFactory.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultProjectPathProviderTest.cs
- VS4Mac does not have LiveShare yet so this platform agnostic piece needs to allow optional for `LiveShareProjectPathProvider`.
- Added a test to ensure `null` project path providers are allowed
aspnet/AspNetCore#9645
=> Make LiveShareProjectPathProvider optional

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSource.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveAttributeCompletionSourceTest.cs
- In the situation where a single transition was typed at the beginning of the document we'd argument out of range exception because `leftEnd` would be -1.
- Added a general restriction to document length to only support scenarios where we could possibly participate.
- Added a test to cover the situation
aspnet/AspNetCore#10708
=> Fix argument out of range exception.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSource.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveAttributeCompletionSourceTest.cs
- Made our directive attribute completion provider less greedy when determining `applicableToSpan`s. We now restrict our `applicableToSpan` to todays current flavor of directive attributes, basically only simple implicit expressions`.
- Changed our `applicableToSpan`s to no longer include the `@` symbol in order for our `applicableToSpan`s to be compatible with Roslyn's.
- Updated and added tests to account for the fixes.
- Found that VS windows modern completion APIs interact a bit strangely when multiple completion providers are at play. This ended up being a design issue in the modern VS completion end that's not easily resolvable in a short amount of time. I've notified them of the problem and they're thinking through future changes.
The design issue:
- The first provider to return an …
=> Fix C# dot commit and CSS completions.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/BoundAttributeDescriptorExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentBindLoweringPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentComplexAttributeContentPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentDiagnosticFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentEventHandlerLoweringPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentKeyLoweringPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentLoweringPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentReferenceCaptureLoweringPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentTemplateDiagnosticPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorIntermediateNodeLoweringPhase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Intermediate/ComponentAttributeIntermediateNode.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Intermediate/IntermediateNodeVisitor.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Intermediate/TagHelperDirectiveAttributeIntermediateNode.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Intermediate/TagHelperDirectiveAttributeParameterIntermediateNode.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/IntermediateNodeWriter.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentChildContentIntegrationTest.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentDiagnosticRazorIntegrationTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/10547
This is just a follow-up cleanup we wanted to do for directive attributes
- Introduced `TagHelperDirectiveAttributeIntermediateNode`
- Renamed `TagHelperAttributeParameterIntermediateNode` to `TagHelperDirectiveAttributeParamaterIntermediateNode`
- Updated references and added a test for possible corner case
=> Use an explicit intermediate node for directive attributes

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/TagHelperDescriptorExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/TagHelperDescriptorExtensions.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Test/BindTagHelperDescriptorProviderTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Test/ComponentTagHelperDescriptorProviderTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Test/EventHandlerTagHelperDescriptorProviderTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Test/KeyTagHelperDescriptorProviderTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Test/RefTagHelperDescriptorProviderTest.cs
- WTE needs a way to detect if a `TagHelperDescriptor` is a component based `TagHelper` in order to turn features like validation, completion etc. on/off. What this boils down to is providing a nice method to say that a `TagHelper` is not a directive attribute `TagHelper`.
- Updated tests to add verification points for the new `IsRazorComponentTagHelper` method.
/cc @ToddGrun this will enable what you want. We'll need to insert before you can properly use it though.
=> Add Razor component TagHelper detection.

eng/Version.Details.xml, eng/Versions.props
- align Microsoft.NETCore.App.Ref version with other core-setup dependencies
- correct `CoherentParentDependency` attribute for System.Diagnostics.DiagnosticSource
- align its version with other CoreFx dependencies
(coherency tree is now consistent again)
=> Add missing `CoherentParentDependency` attribute

src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ViewComponentTagHelperTargetExtension.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ViewComponentTagHelper_DesignTime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ViewComponentTagHelper_Runtime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/ViewComponentTagHelperTargetExtensionTest.cs
- It looks that when we first did VCTH we never put in the effort to reduce our footprint on available parameters for `ViewComponentTagHelper`s. I went ahead and added several underscores to the generated fields/parameters to reduce collisions.
- Updated tests to reflect the new codegen.
_Note: On initial investigation of this issue I must have had a bad environment because I thought that VCTH's weren't working at all. Turns out they work but can't have specifically named parameters. That's what this PR fixes._
aspnet/AspNetCore#8645
=> Allow `content`, `output` and `context` as keywords to VC params.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentBindLoweringPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentRuntimeNodeWriter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentsApi.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Intermediate/HtmlAttributeIntermediateNode.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.ComponentShim/Microsoft.AspNetCore.Components/RenderTree/RenderTreeBuilder.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToElementFallback_WithFormat_WritesAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToElementFallback_WithFormat_WritesAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToElementFallback_WritesAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToElementFallback_WritesAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToElementWithSuffix_WritesAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToElementWithSuffix_WritesAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToElement_WithStringAttribute_WritesAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToElement_WithStringAttribute_WritesAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToElement_WritesAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BindToElement_WritesAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BuiltIn_BindToInputCheckbox_WritesAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BuiltIn_BindToInputCheckbox_WritesAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BuiltIn_BindToInputText_WithFormatFromProperty_WritesAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BuiltIn_BindToInputText_WithFormatFromProperty_WritesAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BuiltIn_BindToInputText_WithFormat_WritesAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BuiltIn_BindToInputText_WithFormat_WritesAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BuiltIn_BindToInputText_WritesAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BuiltIn_BindToInputText_WritesAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BuiltIn_BindToInputWithoutType_WritesAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/BuiltIn_BindToInputWithoutType_WritesAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/DuplicateMarkupAttributes_IsAnError_BindOnInput/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/DuplicateMarkupAttributes_IsAnError_BindOnInput/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/DuplicateMarkupAttributes_IsAnError_BindValue/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/DuplicateMarkupAttributes_IsAnError_BindValue/TestComponent.mappings.txt
This is needed for https://github.com/aspnet/AspNetCore/issues/8204
We have to know whether any given event is part of a two-way binding or not, because it's important that we **only** force the DOM to be consistent with the render tree if it's part of a two-way binding. Otherwise we destroy the entire ability to do one-way binding (i.e., just an input event handler that doesn't have any corresponding output value).
=> For bind on element, also write the updated attribute name to the render tree builder

src/Razor/src/Microsoft.NET.Sdk.Razor/FindAssembliesWithReferencesTo.cs, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/ApplicationPartDiscoveryIntegrationTest.cs
Currently FindAssembliesWithReferencesTo produces a stacktrace when P2P builds fail - for instance
if the referenced project has a compiler error. This changes it to use LogErrorFromException.
In addition, there was a typo in the property that disabled the feature.
Fixes https://github.com/aspnet/AspNetCore/issues/11226
=> Use LogErrorFromException when FindAssembliesWithReferencesTo throws

src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorProjectFileSystem.cs, src/Razor/test/RazorLanguage.Test/DefaultRazorProjectFileSystemTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/11486
We were doing a case sensitive matching here while we do case insensitive matching in other places in this file. I believe this was just an oversight that was missed. I'm still digging into why this bug never came up until now. But I think this is the right fix.
=> Do case insensitive comparison in DefaultRazorProjectFileSystem.GetItem

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Extensions/EliminateMethodBodyPass.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentDeclarationIntegrationTest.cs
This fixes a regression in the new `@ref` support, where the build will
fail during the declaration pass.
The problem is that the EliminateMethodBodyPass runs really early and
wipes out the usage of `@ref` before we have a chance to see it. The
solution is to make it run really late. This makes sense because we
basically just use this pass to do cleanup.
=> Fix a bug with ref and declaration phase

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.props
This is the last cleanup from the SDK content definition move we did for static web assets from the web sdk into the razor sdk, we couldn't do it earlier because of sourcebuild (we did not have a new enough version of the web SDK here)
=> Unconditionally enable content in RCLs

Directory.Build.targets, eng/Version.Details.xml, eng/Versions.props
- see also aspnet/EntityFrameworkCore#16370 and aspnet/EntityFrameworkCore#16385 discussions
- grab latest from the '.NET Core 3 Release' channel
=> Explicitly reference Roslyn compiler toolset version that will ship in preview 7

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets
- Without this any diagnostics from Analyzers will be doubly reported. One for the declaration compilation and one for the view compilation.
i.e.
aspnet/AspNetCore#8825
=> Don't pass Analyzers to Razor declaration compilation Csc task invocation.

NuGet.config
We need all restore sources to be located in NuGet.config since internal feeds can only be restored from there. More details including next steps [here](https://github.com/dotnet/arcade/blob/master/Documentation/RestoreSourcesUpdateStatus.md)
/cc @riarenas @jcagme
=> Update NuGet.config feed list

src/Razor/test/Microsoft.CodeAnalysis.Razor.Test/BindTagHelperDescriptorProviderTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Test/ComponentTagHelperDescriptorProviderTest.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentChildContentIntegrationTest.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentCodeGenerationTestBase.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentDirectiveIntegrationTest.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentDiscoveryIntegrationTest.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentGenericTypeIntegrationTest.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentTypingTest.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ComponentWithTypeParameters/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ComponentWithTypeParameters/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ComponentWithTypeParameters/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithKey_AndOtherAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithKey_AndOtherAttributes/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithKey_AndOtherAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentWithTypeParameters/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentWithTypeParameters/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentWithTypeParameters/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithKey_AndOtherAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithKey_AndOtherAttributes/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithKey_AndOtherAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.mappings.txt, src/Razor/test/testapps/ComponentLibrary/GenericComponent.razor
- Updated existing tests to use `public` accessibility for parameters. As part of this also updated baselines.
- We now recommend that `[Parameter]`'s should be `public`. In the future this will be a requirement.
aspnet/AspNetCore#8825
=> Update tests to specify public [Parameter]

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerIntegrationTest.cs, src/Razor/test/testapps/Directory.Build.props
- Verified the fix with VS16.2-preview1 + latest CLI with modified `Nullable` entry on disk
- Updated tests.
- Note: This change will not pass the build until we have a new CLI that has an updated Roslyn that understands `Nullable`.
aspnet/AspNetCore#10218
=> React to Roslyn rename of `NullableContextOptions` to `Nullable`.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
- Prior to this we had a 50ms window in which tests can potentially fail. Basically, calling `Workspace_WorkspaceChanged` immediately enqueues an update after 50ms, if the CI is slow and it takes longer than 50ms to continue to the execution then all of these would fail.
- Added a manual reset event to ensure we can block delayed work yet still ensure that delayed work happens.
aspnet/AspNetCore-Internal#2787
=> Make WorkspaceProjectStateChangeDetector tests reliable.

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Serialization/RazorDiagnosticJsonConverter.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Serialization/TagHelperDescriptorSerializationTest.cs
I noticed this while debugging something else in VS. It looks like the
service hub is using camelCase, which wasn't covered with a diagnostic
in our tests. As a result we would fail to read the data from the OOP
host, and fall back to in-process tag helper discovery.
=> Fix serialization of SourceSpan

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerTestFixtureBase.cs
Fixes https://github.com/aspnet/AspNetCore-Internal/issues/2706
This has suddenly started being flaky again. I don't see any obvious issues with it and I can't reproduce this locally. Increasing the timeout to see if that fixes it.
=> Increase timeout in attempt to fix test flakiness

NuGet.config, eng/Version.Details.xml, eng/Versions.props
nit: last conditional `$(RestoreSources)` update was redundant
=> Move to new vside feeds and make Roslyn package coherent with Extensions version

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/BuildVariables.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildIntegrationTestBase.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/PackIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj, src/Razor/test/testapps/Directory.Build.props
- Updated `BuildVariables` to lift the `Microsoft.Net.Compilers.Toolset` package version into C# so we can pass it as a parameter to our testapps when building them.
- Flowed the `MicrosoftNetCompilersToolsetPackageVersion` to transitive testapp projects on restore. This enables `build.cmd` to properly pre-build our `testapp` projects with the latest version of Roslyn.
- Added several conditions to detect if a user is attempting to independently build a `testapp` at which point we fallback to using the SDKs Roslyn compiler toolset version.
aspnet/AspNetCore#12268
=> Enable Razor integration tests to use repos Roslyn version.

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/BuildVariables.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildIntegrationTestBase.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/PackIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj, src/Razor/test/testapps/Directory.Build.props
I added a hack to workaround limitations in how the AspNetCore-Tooling's integration tests deploy their apps with a dependency on the current SDK's Roslyn (not the one the repo consumes).
This PR unpins the integration tests Roslyn to a faulty version back to what the SDK offers. 
Ultimately we want to pin our integration tests Roslyn version to what this repo uses (i'll work on that if I find time this sprint) but for now I wanted to make sure we didn't let this staleness sit for very long.
=> Unpin Razor integration tests Roslyn version to incoherent version.

src/Razor/src/Microsoft.CodeAnalysis.Razor/ComponentTagHelperDescriptorProvider.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Test/ComponentTagHelperDescriptorProviderTest.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentCodeGenerationTestBase.cs
- Prior to this a user could have private, protected or public parameters. We now require public and plan to update analyzers to enforce good usage of public component parameters.
- Removed private `ComponentTagHelperDescriptorProvider` workaround. meta data workaround since we no longer operate on private parameters.
- Updated existing tests to not have private parameter setters. I missed these in my last pass.
- Added two new tests to validate parameters which are private or have private setters are ignored.
aspnet/AspNetCore#12291
=> Require public component parameters and remove private metadata workaround

eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/ViewComponentTagHelperDescriptorFactory.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/ViewComponentTypeVisitor.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/ViewComponentTagHelperDescriptorFactory.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/ViewComponentTypeVisitor.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ViewComponentTagHelperDescriptorFactory.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ViewComponentTypeVisitor.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/BindTagHelperDescriptorProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/ComponentTagHelperDescriptorProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/DefaultTagHelperDescriptorFactory.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/EventHandlerTagHelperDescriptorProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/RazorDeveloperTools/RazorDeveloperTools.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Microsoft.VisualStudio.LanguageServices.Razor.Test.csproj
- Updated instances of our code to no longer use reference type checks on `ISymbol`s. This was a new restriction added by Roslyn [here](https://github.com/dotnet/roslyn-analyzers/issues/2084). We also have a follow up AspNetCore issue [here](https://github.com/aspnet/AspNetCore/issues/12747) to bring these level of changes to AspNetCore.
- Had to pin `Microsoft.CodeAnalysis.Analyzers` in our VSIX projects in order to workaround version conflicts of `Microsoft.CodeAnalysis.Analyzers`. The version conflict is introduced from our dependency on `Microsoft.VisualStudio.ProjectSystem.Managed.VS`. It transitively depends on `Microsoft.CodeAnalysis.Analyzers` `2.6.3` where as our latest Roslyn bits transitively depend on `Microsoft.CodeAnlalysis.Analyzers` `2.9.4`. Tried updating to the latest, …
=> Update Roslyn dependencies to align with SDK and VS.

src/Razor/src/Microsoft.CodeAnalysis.Razor/RazorProjectEngineBuilderExtensions.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Test/RazorProjectEngineBuilderExtensionsTest.cs
- We would default to improper C# language versions when given non-numeric `LangVersion`s. For instance when given `CSharpLanguageVersion.Latest` we'd default to 7.3 which was inconsistent with how the rest of the C# world functioned in VS
- Added a test.
aspnet/AspNetCore#11139
=> Add support for non-numeric CSharpLanguageVersions.

src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/RazorExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/RazorExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/RazorExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Tools/GenerateCommand.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/RazorProjectEngineBuilderExtensions.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest.cs
- Roslyn now default to 8.0 C# so it's no longer specified in a users project file. Because of this restriction we can no longer see the projects `LangVersion` when generating Razor files. Meaning, we can't conditionally generate C# 8.0 aware code because our Razor default is not C# 8.0. Therefore, when we detect that the C# lang version hasn't been provided we don't set a C# version and instead rely on what the default configuration for the Razor project is. In practice this looks like:
- MVC1.X = C# 7.3
- MVC2.X = C# 7.3
- MVC Latest = C# 8.0
- I thought about adding a feature flags variant for `RazorCodeGenerationOptions` but decided not to since C# features are all configurable options that are based on more than just the `RazorLangVersion`.
- Added integration tests to ensure that …
=> Associate C# version with each Razor extension version.

src/Razor/src/Microsoft.NET.Sdk.Razor/AssemblyItem.cs, src/Razor/src/Microsoft.NET.Sdk.Razor/FindAssembliesWithReferencesTo.cs, src/Razor/src/Microsoft.NET.Sdk.Razor/ReferenceResolver.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/ReferenceResolverTest.cs
https://github.com/aspnet/AspNetCore/issues/12693
Building a project that references the WebSDK results in StackOverflow if any of it's dependencies have cyclical references. This was observed with a transitive dependency that referenced WPF
Project cannot be built
Regression compared to 2.x
Low. This code was written assuming references are not cyclical and now adds a guard to prevent this.
=> Prevent StackOverflows when assemblies have recursive references

clean.cmd, clean.ps1, clean.sh, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/CSharpCodeParser.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/ParserTests/CSharpSectionTest/CapturesNewlineImmediatelyFollowing.cspans.txt, src/Razor/test/RazorLanguage.Test/TestFiles/ParserTests/CSharpSectionTest/CapturesNewlineImmediatelyFollowing.stree.txt
Fixes https://github.com/aspnet/AspNetCore/issues/11859
Looks like we add a marker token at the end of @inject| to provide CSharp intellisense for the upcoming token. We fix this by only adding the marker token if there is whitespace after @inject
=> Fix @inject intellisense

src/Razor/src/Microsoft.NET.Sdk.Razor/FindAssembliesWithReferencesTo.cs, src/Razor/src/Microsoft.NET.Sdk.Razor/ReferenceAssemblyNotFoundException.cs, src/Razor/src/Microsoft.NET.Sdk.Razor/ReferenceResolver.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/ApplicationPartDiscoveryIntegrationTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/11226
@pranavkm does this look like what you expect? I'll add a test once you confirm.
=> Print warning when reference assembly is not found

azure-pipelines.yml
- Windows: use BYOC pools
- stop using removed `dotnet-external-temp` VM images
- non-Windows: `name` -> `vmImage`
- stop using queue names for hosted images; all one queue now
- correct LinuxContainer location to match current URL
- move to jobs schema; phases are barely supported and no longer documented
- phases do not support named pools and pools are needed on Windows
- switch to array syntax for top-level variables; jobs.xml doesn't support object syntax
- replace `queue` parameter with `container`, `pool`, `strategy` parameters
- remove build steps available in jobs.xml: see `enablePublishBuildArtifacts`, `enablePublishTestResults`
- remove variables that jobs.xml defaults correctly: `$(_HelixType)`, `$(_HelixBuildConfig)`
- pass `helixRepo` parameter rather than provide …
=> Use current AzDO and Arcade pools and syntax

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets
Fixes https://github.com/aspnet/AspNetCore/issues/13114
We just want to mirror what Roslyn does to set the LangVersion property here https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L6-L10.
=> Set LangVersion the same way as roslyn

.gitignore, eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateGeneratedOutputTest.cs
This uses the 3.3.0 packages that Roslyn's published for us to nuget.org (unlisted).
This way we can pin to this version ahead of the release.
Tell-mode because we've already discussed this with the QB.
/cc @agocke
=> Update Roslyn deps to 3.3.0 versions

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets
Publishing web app with trimming enabled, trims assemblies that are used only in Views, breaking the published application.
Also views aren't crossgened.
Trimming feature is broken out of the box in basic web scenarios.
Less severely, code in views does not get the benefit of crossgen.
No.
Low. 
---
Views assembly was not being passed to linker, causing anything in framework rooted only by it to be thrown out.
Views assembly was not be being crossgened.
Cause: Views assembly was added to ResolvedFileToPublish too late for linker and crossgen to see it.
Fix: Re-schedule target to run before linker and crossgen
There's a related change in https://github.com/dotnet/sdk/pull/3539, but this works with or without that and can be reviewed and approved independently. That sdk change has an …
=> Pass views assembly to linker

src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/FallbackRazorProjectHostTest.cs
- We now depend on new and signed binaries from Monodevelop.
aspnet/AspNetCore#5051
=> Unskip VS4Mac tests.

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.CodeGeneration.targets
Search and replace was overzealous and rzc can no longer be resolved correctly. This fixes the template test breaks in https://github.com/aspnet/AspNetCore/pull/13571.
=> Fix razor tool assembly path

azure-pipelines.yml, eng/common/templates/job/job.yml, eng/scripts/FinishDumpCollectionForHangingBuilds.ps1, eng/scripts/InstallProcDump.ps1, eng/scripts/StartDumpCollectionForHangingBuilds.ps1, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj
* Enables procdump to capture dumps on build hangs on Windows.
* Enables procdump to capture dumps when a child process hangs inside a test.
=> [Infrastructure] Install procdump and capture dumps on build hangs

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDefaults.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectSnapshotProjectEngineFactory.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/EphemeralProjectSnapshot.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackRazorConfiguration.cs
https://github.com/aspnet/AspNetCore/issues/13291
Working on verifying it in VS (As soon as I can build Razor on my borked machine)
=> Default to MVC 3.0 when we can't detect the Razor configuration

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets
Fixes [997705](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/997705)
Razor used to set the used C# language version in project by having a custom logic. We don't really need to set `LangVersion` manually anymore because of [this](https://github.com/agocke/roslyn/commit/17e25dca2016f0d245abc1ad22e0aa8556e14f3c) change in Roslyn.
New ASP.NET Core Razor Page application would fail at build, when running from VS.
Yes
Low: We expect Roslyn to do the [right thing](https://github.com/dotnet/roslyn/pull/38967/).
I verified this fixes the issue in VS manually.
=> Pass through the correct LangVersion to csc

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.DesignTime.targets
- The 3.0 SDK adds RazorDeclaration files to the compile list if they exist. If a user builds in VS and then does a project level operation (adding a property group or item group to their project file) a design time build will trigger for unrelated reasons and declaration files will be included as part of the C# compilation resulting in duplicate member errors. This change ensures that even if declaration files are added we then remove them to ensure we avoid those declaration additions.
- One unfortunate aspect of this change is that declarations are added to the compile list for a brief moment resulting in errors and then are instantly removed in some situations. I say "some situations" because when this happens it is highly dependent on how / when the project system decides to perform …
=> Add support for using a 3.0 SDK on VS 16.4.

src/Razor/src/Microsoft.NET.Sdk.Razor/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntrospectionTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/14017
=> Add a flag to prevent config, json files from being copied to the build output directory

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/VisaulStudioFileChangeTracker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/VisualStudioFileChangeTrackerFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/VisualStudioFileChangeTrackerFactoryFactory.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Documents/VisualStudioFileChangeTrackerTest.cs
- New async APIs were added to avoid blocking of the UI thread when possible for extensions that were interested in monitoring file changes; this PR moves our VS windows specific bits to utilize those new APIs.
- FileChange listening isn't a time dependent task so I took an approach similar to Roslyn where they have a synchronous call path to "start listening" for file change events and then in the background queue the listening asynchronously. The difficult part with this approach is properly synchronizing start/stop listening operations. To solve this we will block the UI thread IF a stop listening request is active; otherwise it will always be asynchronous. In practice this should never happen because stop listening calls are bound to files being deleted or files being opened and start …
=> Moved to async VS FileChange service APIs.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/ComponentDetectionConventions.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/ComponentTagHelperDescriptorProvider.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
- We now do aggressive detection on the type of C# class that's being edited. In order to not impact C# scenarios we only do work if C# assets are available to us. Meaning, we inspect the old document and if that document has its' semantic model available we spend cycles to determine if it's a component. In the case that we find a C# component class that wasn't previously caught we enqueue an update.
- Our IComponent detection logic has to be "fuzzy" because we don't have access to the C# compilation at the workspace change detection layer. Therefore we need to look at type names and do string comparisons vs. looking up specific types in the compilation.
- Added several tests to ensure we enqueue and that we properly detect component classes.
aspnet/AspNetCore#14646
=> Add support for partial component class editing -> refresh components.

src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/RazorGuestInitializationService.cs, src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/RazorGuestInitializationServiceTest.cs
- Prior to this LiveShare initialization would block until our ListDirectories tasks succeeded; in the case that the host project had a significant number of Razor files the acquisition operation could take a significant amount of time. This change starts tasks in the background to acquire _ViewImports dynamically.
- Added CTS flows so if the service is canceled while creating or if a user closes their LiveShare session we stop acquiring _ViewImports.
- Added tests to validate CTS flows and background acquisition of _ViewImports.
aspnet/AspNetCore#13833
=> Lazily acquire _ViewImports files in a non-blocking way.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultTagHelperCompletionService.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/DefaultTagHelperCompletionServiceTest.cs
- This removes the excess amount of directive attribute completions that show up when completing a component.
- Added a test to verify directive attributes no longer show up in element completions.
aspnet/AspNetCore#9133
=> Remove directive attribute completions from element completion list.

src/Razor/src/Microsoft.AspNetCore.Razor.Tools/Microsoft.AspNetCore.Razor.Tools.csproj, src/Razor/src/Microsoft.AspNetCore.Razor.Tools/runtimeconfig.template.json, src/Razor/src/Microsoft.NET.Sdk.Razor/Microsoft.NET.Sdk.Razor.csproj, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.CodeGeneration.targets
Based on the discussions here: https://github.com/aspnet/AspNetCore-Internal/issues/3201#issuecomment-539631557
rzc.dll targeting netcoreapp3.1 causes shared fx version conflicts when consumed as a package in the AspNetCore repo.
A fairly trivial workaround is to have it target it netcoreapp3.0 and allow it to roll-forward to the available shared fx.
This follows csc.dll's behavior, as well as solves the version conflict.
Fixes https://github.com/aspnet/AspNetCore-Internal/issues/3201
=> Retarget rzc.dll to netcoreapp3.0

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioRazorParserIntegrationTest.cs
- Prior to this it would take roughly 4-5 seconds before one could edit a Razor file correctly because if our project system wasn't yet aware of a Blazor component it wouldn't let you edit it as if it was one.
- Found that we were forcing legacy FileKind behavior despite the current FilePath when parsing Razor files that had no project system association.
- Added an integration test to ensure we can properly parse Rzor components when there is no document snapshot associated.
aspnet/AspNetCore#11816
=> Properly parse (in VS) newly added files to project.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
@KirillOsenkov found this when porting Blazor bits to VS4Mac because they handle stuff slightly differently over there.
- In Visual Studio a null-ref is thrown when we cannot find an IComponent type.
- This was missed because shockingly there's 0 end-user impact to this null reference exception. VS doesn't crash, our bits don't stop being called, Roslyn just reports the error and then continues on its merry way.
- The issue that this solves from my perspective with this throwing is that anyone debugging Visual Studio with Just My Code turned to false will encounter these exceptions in Razor < 3.0 projects.
- Added a test to verify we no longer explode.
@danroth27 / @mkArtakMSFT Do we want to go through QB mode (it's QB mode for the rest of the 16.4 release) to get this in? Read above to …
=> Fix Razor < 3.0 projects null-refing when WorkspaceChanged events fire.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentRuntimeNodeWriter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Intermediate/MarkupElementIntermediateNode.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentCodeGenerationTestBase.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/EventHandler_PreventDefault_StopPropagation/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/EventHandler_PreventDefault_StopPropagation/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/EventHandler_PreventDefault_StopPropagation/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/EventHandler_PreventDefault_StopPropagation_Minimized/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/EventHandler_PreventDefault_Duplicates/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/EventHandler_PreventDefault_StopPropagation/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/EventHandler_PreventDefault_StopPropagation/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/EventHandler_PreventDefault_StopPropagation/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/EventHandler_PreventDefault_StopPropagation_Minimized/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/EventHandler_PreventDefault_StopPropagation_Minimized/TestComponent.ir.txt
Trying to use Blazor's `@onclick:preventDefault` or `@onclick:stopPropagation` results in runtime invalid operation exception.
Customers will not be able to utilize the `preventDefault` or `stopPropagation` features (even though VS will tell them they're available) because usage of them breaks their page
No because these are a new feature. The reason why this was missed is because it involved several moving parts of which required Runtime, Tooling and SDK.
Low. We're just changing the order of how things are rendered. The rendering pipeline should have been doing this from the get-go. The only reason why it wasn't was because of an oversight.
---
- The Blazor runtime doesn't support adding attributes prior to any sort of content frames being applied. This change ensures that …
=> Fix runtime preventDefault / stopPropagation runtime InvalidOperationException.

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets
Follow up to https://github.com/dotnet/project-system/issues/5596
FastUpToDateCheck now has a way to associate inputs and outputs using the Set attribute.
This change prevents FastUpToDateCheck from rebuilding a project when a *.cshtml file is
newer than the project's dll output.
Fixes https://github.com/aspnet/AspNetCore/issues/13204
=> Associate inputs and outputs for .Views dll with a set in FastUpToDate check

eng/Versions.props
CC @mmitche @dougbu 
I'll merge this once we got the all-clear for 3.1-preview3
=> Stabilize package versions for 3.1.0

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultRemoteTextLoaderFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/PrecompiledRazorPageSuppressor.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentManager.ts, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/BackgroundDocumentProcessedPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/OmniSharpTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/OmniSharpWorkspaceTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/PrecompiledRazorPageSuppressorTest.cs
- Prior to 3.1 Razor SDK would add Razor declarations to the compile list, we now need to remove all dynamically added Razor C# documents because we control which Razor documents are generated and added to the workspace.
- Also found that when the Razor document manager initializes it was opening all documents on add even if they weren't open. Unfortunately we can't currently test the Razor document manager because it depends on VSCode runtime APIs that we've yet to mock/abstract at the unit test layer.
- Added an `OmniSharpWorkspaceTestBase` to handle workspace creation.
- Added `PrecompiledRazorPageSuppressor` tests.
=> Ensure 3.0 Razor SDKs don't add duplicate Razor document declarations/files.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultProjectSnapshotManagerTest.cs
- Only updating a project's root namespace wouldn't trigger updates because we weren't comparing the previous and current root namespaces.
- Updating a projects ProjectWorkspaceState (TagHelpers) would always result in re-computation of a Razor document even if the before and after TagHelpers were exactly the same, we now compare current and previous and do the right thing.
- Added tests
=> Fix project state improperly caching during matching RootNamespace & ProjectWorkspaceState updates.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/src/RazorDevModeHelpers.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/src/extension.ts
- Prior to this our warning dialog response was not being handled correctly.
- Stopped activating the development extension if the workspace wasn't configured. Did this because attempting to activate the Razor dev mode extension would occasionally fail due to a race between the official O# extension's Razor support and our dev variant both trying to register identical commands/functionality. This stopped activation and killed all behavior in the extension.
=> Fix VSCode Razor development configuration helpers.

.vscode/launch.json, .vscode/tasks.json
- With this change there's no reason to repeatedly run the VSCode extension. Instead you can make changes in the library and then just ctrl + r to reload the experimental instance and see the changes.
- VSCode's tasks support is limited when it comes to background commands (npm watch) because it typically will wait for a command to exit. Due to its limitations a background task must be the top level task that is called so that it's the "last" task that's in the pipeline; this way VSCode knows when to do the final launch command. In our case this means I had to add a `WatchLibraryAndCompileExtension` that in the background watched the library and then dependently compiled the extension (can't do both).
=> Change "RunExtension" to watch Razor library.

azure-pipelines.yml
Making sure the `blazor-wasm` branches are being built.
=> Enable building `blazor-wasm` branch

src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/BackgroundDocumentProcessedPublisher.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/BackgroundDocumentProcessedPublisherTest.cs
- This is to enable things like go-to-definition/rename
=> Publish C# for CSHTML files.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CSharpPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultCSharpPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedCodeContainerStore.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Program.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/UnsynchronizableContentDocumentProcessedListener.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/BackgroundDocumentProcessedPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/src/RazorDevModeHelpers.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentManager.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLogger.ts, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultCSharpPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedCodeContainerStoreTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultHostDocumentFactoryTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/UnsynchronizableContentDocumentProcessedListenerTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/BackgroundDocumentProcessedPublisherTest.cs
- Added a C# publisher that's responsible for maintaining the clients understanding of the C# document. For each C# publish it tracks the `SourceText` that was previously published and diffs the two to find the minimal text changes that are needed to update the client. Prior to this we were making a lot of assumptions about the content of the clients C# buffer; one of which was that it had content when it actually didn't.
- Changed the `UnsynchronizableContentDocumentProcessedListener` and `DefaultGeneratedCodeContainerStore` to use the `CSharpPublisher` instead of independently publishing their C# to the client.
- Updated the open document event from clients to trigger a Razor document snapshots generation to warm the data/publish the C#.
- Updated the …
=> LSP: On document open populate Razor documents C#

src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/BackgroundDocumentProcessedPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorHoverProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Hover.test.ts
- As part of the hover provider I needed to rebuild the content in order for it to properly show. This looked to be a bug in VSCode. Will reach out to them.
- Added Hover functional tests to validate the C# + HTML experiences.
- Found a race condition in the `BackgroundDocumentProcessedPublisher` where files would attempt to be removed in a racey situation which didn't actually remove them.
aspnet/AspNetCore#14329
=> Add support for HTML + C# hover/quick info.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/CodeDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/FunctionsDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Added tests for `@code` and `@functions`.
- Does not support nested HTML.
=> Add grammar support for @code and @functions directives.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/CodeDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ExplicitExpressions.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/FunctionsDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ImplicitExpressions.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Added tests to cover simple and complex explicit expression cases.
- Does not cover embedded transitions (templates)
=> Add explicit expression support to Razor grammar.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/CodeBlock.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- To allow one of `@{..}`'s primary features (HTML) I needed to add the concept of well-formed HTML to our grammar.
- Found that well formed HTML in code blocks that had expressions at the end of attribute areas (`<p @DateTime.Now>`) were not being tokenized correctly.
- Added tests
- As part of this work I also included specific `@{...}` constructs such as single line markup (`@:`) and multi-line markup (`<text>`).
=> Add Razor grammar support for code blocks @{...}.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/InjectDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ModelDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/NamespaceDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Ensured the new model directive grammar applied scopes that were compatible with the pre-existing Razor grammar.
- Add tests to validate the various forms of `@model`.
=> Add grammar support for the model directive.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/AddTagHelperDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/InjectDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ModelDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/NamespaceDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/RemoveTagHelperDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TagHelperPrefixDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Added support for `@addTagHelper`, `@removeTagHelper` and `@tagHelperPrefix`to the Razor grammar.
- Add tests to validate the various forms of the TagHelper directives.
=> Add grammar support for TagHelper directives.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/AttributeDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ImplementsDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/InheritsDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Ensured the new inherits directive grammar applied scopes that were compatible with the pre-existing Razor grammar.
- Add tests to validate the various forms of `@inherits`.
=> Add grammar support for the inherits directive.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/UsingDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Ensured the new using directive grammar applied scopes that were compatible with the pre-existing Razor grammar.
- Add tests to validate the various forms of `@using` (standard, static and alias).
=> Add grammar support for the using directive.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ImplicitExpressions.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/LayoutDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/SectionDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/UsingDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Found that for implicit expressions doing things such as `@section Foo {@DateTime.Now}` resulted in mis-coloring of the `}` suffix. This was due to our implicit expression handling not having proper exit criteria.
- Added tests to validate the new exit criteria of implicit expressions.
- Add tests to validate the various forms of `@section`.
=> Add grammar support for the section directive.

eng/Version.Details.xml, eng/Versions.props, global.json
* Use Microsoft.NETCore.App.Internal for runtime version
For stable builds, core-setup is now publishing its artifacts to a suffixed directory (e.g. 3.0.1-servicing-19510-13) instead of 3.0.1. This ensures we don't have to overwrite outputs when we rebuild stable versions. Within that directory, it publishes the same set of files with the final file names as well as suffixed file names:
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.1-servicing-19510-13/dotnet-apphost-pack-3.0.1-win-x64.msi
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.1-servicing-19510-13/dotnet-apphost-pack-3.0.1-servicing-19510-13-win-x64.msi
Downstream repos should install the runtime using the full suffixed version.
=> [release/3.0] Use Microsoft.NETCore.App.Internal for runtime version

eng/Version.Details.xml, eng/Versions.props, global.json
* Use Microsoft.NETCore.App.Internal for runtime version
For stable builds, core-setup is now publishing its artifacts to a suffixed directory (e.g. 3.0.1-servicing-19510-13) instead of 3.0.1. This ensures we don't have to overwrite outputs when we rebuild stable versions. Within that directory, it publishes the same set of files with the final file names as well as suffixed file names:
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.1-servicing-19510-13/dotnet-apphost-pack-3.0.1-win-x64.msi
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.1-servicing-19510-13/dotnet-apphost-pack-3.0.1-servicing-19510-13-win-x64.msi
Downstream repos should install the runtime using the full suffixed version.
=> [release/3.1] Use Microsoft.NETCore.App.Internal for runtime version

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/UsingStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Does not support Razor templates or more than one level embedded HTML constructs.
- Add tests to validate the various forms of `@using (...) {...}`.
=> Add grammar support for the using statement.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TryStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Does not support Razor templates or more than one level embedded HTML constructs.
- Add tests to validate the various forms of `@try {...} catch (...) { ... } finally { ... }`.
- The `catch` and `finally` constructs can not be conditionally included based off of the existence of a `try` so we have to allow these statements to exist anywhere in the documents and be colored as C#. The tricky part of allowing `catch`/`finally` to exist anywhere is that we don't want to allow situations such as `<p>Finally!</p>`. To disallow these situations the rule that's written for each tries to ensure they exist on their own line surrounded by potentially valid C# constructs (or no surroundings at all).
=> Add grammar support for the try, catch and finally statements.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/DoStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TryStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Expanded the while statement support to work as continuations of the do statement.
- Add tests to validate the various forms of `@do { ... } while (...);`.
=> Add grammar support for do-while statements.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/DoStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/LockStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TryStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@lock (...) {...}`.
- Forgot to add the open parenthesis suffix requirement to previous statements. Added those.
=> Add grammar support for lock statements.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/DoStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/LockStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/SwitchStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TryStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@switch (...) {...}`.
=> Add grammar support for switch statements.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/DoStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ForeachStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/LockStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/SwitchStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TryStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/WhileStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@foreach (...) {...}`.
- To get the `foreach` condition to properly parse I had to lift the `foreach` condition parsing from C# into our code (it's inlined there so we can't call into it via name).
=> Add grammar support for foreach statements.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/DoStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ForStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ForeachStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/LockStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/SwitchStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TryStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/WhileStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@for (...) {...}`.
- Updated some of the previous statements `begin` to match what's done in the C# grammar (added word breaks `\b`)
=> Add grammar support for for statements.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/DoStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ElsePart.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ForStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ForeachStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/IfStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/LockStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/SwitchStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TryStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/WhileStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Does not support Razor templates or more than one level embedded HTML constructs.
- Add tests to validate the various forms of `@if (...) {...}` and `else [if (...)]`.
- The `else` construct can not be conditionally included based off of the existence of an `if` so we have to allow `else` statements to exist anywhere in the documents and be colored as C#. The tricky part of allowing `else` to exist anywhere is that we don't want to allow situations such as `<p>Or else!</p>`. To disallow these situations the rule that's written for `else` tries to ensure else exists on its own line surrounded by potentially valid C# constructs (or no surroundings at all).
=> Add grammar support for the if and else statements.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCompletionItemProvider.ts
- VSCode's insiders build renamed `insert` to `inserting` and `replace` to `replacing`.
@jrieken we keep getting broken by little things like this. Is there a better way we can go about remapping `ranges` returned from executing the `vscode.executeCompletionItemProvider` command? I know eventually it'll just be overloaded on `range` but I wouldn't imagine the intermediary `range2` changes would be making it to public builds.
=> Add support for VSCode's insiders completion break.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/CodeBlock.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Basically we're now treating all statements similar to the `else` continuation for an `if`. Meaning, if we detect that a statement is being used at the beginning of a line and is followed by something logical like a parenthesis; we'll classify it as C#.
- Added tests and updated existing ones.
=> Add grammar support for nested C# statements with markup in Razor code blocks.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ImplicitExpressions.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Prior to this `abc@contoso.com` would treat `@contoso.com` as an email address.
- Added tests to validate implicit expressions properly ignore email addresses but also continue to work in situations where there are clear word boundaries.
=> Add grammar support for email addresses.

eng/Version.Details.xml
I think this is still causing CPD problems in upstack updates. While MNP this isn't technically a product dependency, it's tied to a product dependency (core-setup). Also move extensions since all those versions will line up anyway.
=> [release/3.1] Move CPD tied dependencies up above pinned

eng/Version.Details.xml
I think this is still causing CPD problems in upstack updates. While MNP this isn't technically a product dependency, it's tied to a product dependency (core-setup). Also move extensions since all those versions will line up anyway.
=> [release/3.0] Move CPD tied dependencies up above pinned

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/yarn.lock, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/yarn.lock, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/package.json, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/yarn.lock, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/package.json, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/yarn.lock, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/package.json, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/yarn.lock
Turns out the "vscode" npm package is deprecated so I followed the migration guide. Noticed that because of some component governance stuff (since the "vscode" npm pkg is no longer maintained), which this should also fix.
=> Component updates

eng/Signing.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- Included the LanguageServer core dlls as part of the VSIX install. To do this I had to expose the language server's output path via a target and then dynamically include its outputs in the VSIX output.
- Given how VSIX's are built I could not privately reference our language server to ensure that it's built when the VSIX is built. To work around this limitation I added a `_BuildLanguageServer` target that calls MSBuild directly on the language server as part of build.
- For now I'm dynamically booting the currently built language server that's deployed with the extension. I haven't given a lot of thought to what flavor of OS (x64 vs. x86) the server can run on; or if we need to ensure dotnet.exe is available.
- Found that the VS LSP client and the O# language server library that we use …
=> Start Razor Language Server when new Razor LSP editor opens.

eng/Signing.props, eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/README.md, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorEditorFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPContentTypeDefinition.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Resources.resx
- Added a new Razor LSP content type to identify our new Razor editor experience.
- Given that there are already content type associations for the .cshtml/.razor file paths I had to build a RazorEditorFactory that takes precedence over WTE's editor factories and if our feature flags are `true` to change the content type on created editors.
- Added a `README.md` to the LanguageServerClient project to indicate how to use the new Razor LSP editor (no functionality currently).
- For a feature flag I took a two pronged approach of allowing environment variables or VS' first class feature flag support. We haven't yet made the changes to Visual Studio necessary to surface our feature flag as a properly settable feature flag. Once that is done our feature flag will be toggable via the `Enable …
=> Add feature switch to use our new Razor LSP editor.

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildIntegrationTestBase.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs
Static web assets don't work properly with PublishSingleFile as they aren't excluded (like the rest of the web content is).
This fix simply adds a property and the tests necessary to make sure the assets are excluded when published.
This blocks customers trying to publish ASP.NET Core apps as single files when the app uses static web assets.
The issue was customer reported https://github.com/aspnet/AspNetCore/issues/17079
No, but we broke this really close to 3.0 RTM and used to work before.
Low. It's a one line change and we've included a test that validates the fix.
Just adds the ExcludeFromSingleFile property to the resolved static web assets to publish.
=> [Static web assets][Fixes #AspNetCore/17079] PublishSingleFile results in 404 errors for Nuget components

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntrospectionTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj, src/Razor/test/testapps/RazorTest.Introspection.targets
Fixes https://github.com/aspnet/AspNetCore/issues/17308
--------------------------------------
The tasks assembly in the RazorSDK are cross-compiled between desktop and netcoreapp. The SDK is meant to load the appropriate task dll based on the flavor of MSBuild that's executing a build. However due to a bug, the 3.1 version of the Razor SDK always ends up loading the tasks dll compiled for `net46`. We haven't had any reports of this resulting in failures, but don't fully understand the ways in this may interact or fail with user's build systems.
None. However this does not preclude MSBuild failures depending on user's build setup.
Yes. This is a regression introduced in the 3.1 SDK.
Low. Users do not directly interact with the tasks dll.
=> Load the netcoreapp3.1 compiled task when running in Core MSBuild

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs
Static web assets don't work properly with `--no-build` as they depend on AssignTargetPath which is not necessary.
I've updated when the targets get executed to avoid relying on something that will cause NoBuild to fails.
Customers can't do `dotnet publish --no-build` if they have referenced projects that contain static web assets
The issue was customer reported https://github.com/aspnet/AspNetCore/issues/17426
No
Low. It simply moves some MSBuild extensibility around and there are tests to cover the scenario
**Implementation details**
The problem was with a previous implementation that relied on embedding the manifest on the assembly.
The fix redefines when some of the targets get executed.
=> [StaticWebAssets][Fixes #AspNetCore/17426] Publish no build doesn't copy static web assets from referenced projects

src/Razor/src/Microsoft.NET.Sdk.Razor/GenerateStaticWebAssetsManifest.cs, src/Razor/src/Microsoft.NET.Sdk.Razor/ValidateStaticWebAssetsUniquePaths.cs, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/GenerateAspNetCoreStaticAssetsManifestTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/ValidateStaticWebAssetsUniquePathsTest.cs
We had a restriction in place that prevented a project from exposing static web assets under the same base path from different locations on disk.
This was done in order to avoid potential conflicting files.
It turns out that for a scenario we want to enable on Blazor webassembly we need to support exposing two folder locations from the same base path, so that we can expose the files under the wwwroot folder and the compiled dlls that get sent to the browser without having to copy files around.
Fixes https://github.com/aspnet/AspNetCore/issues/17375
It blocks us from moving Blazor wasm to use static web assets.
No
Low. We are relaxing a requirement/precondition but we still do a check to make sure that you don't have conflicting assets exposed at runtime.
**Implementation details**
We …
=> [StaticWebAssets] Updates manifest generation to allow multiple content roots under the same base path for a single project

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/ProvisionalCompletionOrchestrator.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentManager.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServerClient.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/runTest.ts, src/Razor/tslint.json
I wanted to add a tslint rule for "floating promises" because I made a silly mistake which could have been easily caught by it. There are a couple of existing places which violate this rule, I've added exceptions where I'm reasonably certain they're intended, and async/await where I figure it was just a mistake. If I'm wrong about any of those instances I'm super interested in why.
=> TSLint prevent floating promises

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Program.cs
- When I moved the LanguageServer over to the new OmniSharp library version it added the requirement to add a specific LangaugeServer logger. Given that we weren't doing that all logs from the server were being swallowed.
=> Fix language server logging.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DefaultTagHelperCompletionService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/DefaultRazorHoverInfoService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultHtmlFactsService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/HtmlFactsService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultTagHelperCompletionServiceTest.cs
- Prior to this we were doing attribute intersection checks on the entire attribute ranges of an HTML element. In reality we should only allow TagHelper completion in an attribute's prefix or name. To get this new information I had to expand on the `HtmlFactsService` to extract extra information from the attributes it introspects on.
- Added tests for the new failure cases. Testing this was primarily handled by existing tests because we had to ensure that we didn't break new scenarios by adding new restrictions when completions show up. Aka, prior tests not exploding show the quality of the change.
dotnet/AspNetCore#18431
=> Restricted TagHelper attribute completion to not show in values.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/DefaultRazorHoverInfoService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs
- Prior to this we were doing attribute intersection checks on the entire attribute ranges of an HTML element to determine if we should show an attribute hover. In reality we should only allow TagHelper attribute hovers on an attribute's name.
- Added tests for the new failure cases. Testing this was primarily handled by existing tests because we had to ensure that we didn't break new scenarios by adding new restrictions when completions show up. Aka, prior tests not exploding show the quality of the change.
aspnet/AspNetCore#18432
=> Restricted TagHelper attribute hovers to only show when over a name.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateTest.cs
- Due to how the Language Server normalizes paths there are situations when ProjectState can end up in situations where it thinks `_Imports.razor` file changes impact themselves (recursion!!). Because of this, when we remove an `_Imports.razor` file from a project the removal process ends up trying to clean up the project states understanding import -> dependent file mappings and when it tries to re-lookup itself in the dependent file mapping it no longer exists (it was removed from the document list) therefore you get a missing key exception.
- Added a test to validate the scenario.
https://github.com/dotnet/aspnetcore/issues/18487
=> Fix _Imports.razor deletion causing exceptions in language server scenarios.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DefaultTagHelperCompletionService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DirectiveAttributeTransitionCompletionItemProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/DefaultRazorHoverInfoService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProviderBase.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeParameterCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultHtmlFactsService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/HtmlFactsService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultTagHelperCompletionServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DirectiveAttributeTransitionCompletionItemProviderTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderBaseTest.cs
- The core issue was that we weren't taking into consideration an attributes "prefix" text, aka the content prior to the attribute name. This area is typically where users are typing when doing `<InputText                  @{...` because our parser thinks the attribute name is `@{` and the prefix is all the leading whitespace. We now do a two fold check
- Ensure we're overlapping the attribute name if we're checking the content of the attribute name
- Also allow typing in the prefix section when determining if we should show the `@...` completion item
- Added tests for all new API.
dotnet/AspNetCore#14334
=> Fix directive attribute @... completion item not being available on incomplete tags.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Converters/ResponseRazorConverter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Program.cs
Fixes https://github.com/dotnet/aspnetcore/issues/18370.
This is caused by https://github.com/OmniSharp/csharp-language-server-protocol/issues/202.
Basically the LSP spec (and the LSP package we're using on the TypeScript side) demand that a response contain either the `result` property or the `error` property. Currently Omnisharp isn't doing that. I'll eventually send them a PR with my suggested fix, but this will un-break us for now.
=> Ensure result property always gets serialized

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultProjectResolver.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultProjectResolverTest.cs
- For some reason VS is sending differently cased URLs to our language server for documents and projects. This ended up exposing a bug in our code where we weren't using the appropriate file comparer when resolving what project a document belonged to.
- Added a test specifically for windows to verify that casing is ignored in our project resolver.
=> Fix Visual Studio LSP client not associating documents with their proper project.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectDocumentChangeDetector.cs
- Some clients "save" files by re-creating the files on every save. VS seems to be an example of this because our existing file watcher infrastructure wasn't picking up VisualStudio file system changes. I found that by also monitoring `CreationTime` we got the proper notifications.
- Can't add tests for these because we don't test the file watchers directly (they're an external component).
=> Update FileSystemWatcher monitoring to listen for CreationTime changes.

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs
This test has around a 50% pass rate. Always find myself having to retry builds to work around this. Skipping for now until flakyness can be resolved.
dotnet/AspNetCore#18543
=> Skip Publish_CopiesStaticWebAssetsToDestinationFolder_PublishSingleFile.

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs
- This test has around a pretty high failure rate. Always find myself having to retry builds to work around this. Skipping for now until flakyness can be resolved.
dotnet/aspnetcore#18561
=> Skip Publish_NoBuild_CopiesStaticWebAssetsToDestinationFolder.

src/Razor/src/Microsoft.CodeAnalysis.Razor/ComponentTagHelperDescriptorProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/CompletionsComponents.test.ts
Fixes https://github.com/dotnet/aspnetcore/issues/14322
Not having this caused exceptions to be thrown downstream which resulted in no TagHelper Completions being available.
=>  Supply the `PropertyName` for Context TagHelper results.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/Directory.Build.props, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/RazorTemplate.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Utilized VSCode's grammar injection feature to enable Razor templates. Basically what's going on in this changeset is we describe an "injection" into the aspnetcorerazor grammar that states (`R:text.aspnetcorerazor`) if a previous Razor rule can't fulfill the current set of tokens to then allow our template rules to take precedence. This ends up also injecting itself in nested C# statements where we'd expect Razor templates.
- Arcade must have made a change restricting the VSCode grammar tests project from installing/building successfully on my box and I found that the way the SDK was being imported was breaking the way the Oniguruma library would compile itself. This didn't seem to happen on the CI but in an effort to ensure it can build everywhere I added a Directory.Build.props file …
=> Add grammar support for Razor templates (@<p>...</p>).

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/CodeBlock.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/CodeDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/FunctionsDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Utilized VSCode's grammar injection feature to enable Razor markup in functions. Basically what's going on in this changeset is we describe an "injection" into the code/functions directive and Razor code blocks grammar that states if we encounter a { inside of a Razor C# block that's not a string or comment, then tokenize the contents of the {} as typical C#. This ends up also injecting itself in nested C# statements where we'd allow nested markup.
- Updated existing tests and added a lot of new ones to cover several edge cases.
- Marked Razor code blocks with `meta.structure.razor.codeblock` so we can inject our own markup allowing grammar into the C# pieces that we call into.
dotnet/AspNetCore#14287
=> Add grammar support for Razor markup in functions.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentFactory.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServerOptionsResolver.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServiceClient.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Completions.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Completions2_1.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/CompletionsComponents.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Rename.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/TestUtil.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/tests/RazorLogger.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/tests/ReportIssueDataCollector.test.ts, src/Razor/test/testapps/MvcWithComponents/Views/Home/#FileName.cshtml, src/Razor/tsconfig.json
Fixes https://github.com/dotnet/aspnetcore/issues/14323.
vscode.Uri.parse treats anything after `#` as a uri fragment, so instead I used vscode.Uri.file then set the scheme after. `file` doesn't try to parse out the fragment, so the file is handled properly.
=> Fix # in FilePath

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- The new grammar will apply to our LSP editor Razor files.
- Had to update our grammar to specifically apply to razor/cshtml files so VS would pick up the mapping
- The grammar doesn't look to colorize the embedded languages correctly. Have reached out to the VS editor team to investigate the issue further.
- Couldn't add tests because this was more of an end-to-end scenario.
- Added a new pkdef to our extension to allow us to hand-edit pkdef's (ours are usually auto-generated) for features that do not have a code-first model (TextMate).
- Expanded the VSIX extension to build the grammar project on run to ensure we always get the latest grammar.
- Does not include "proper" colorization of Razor constructs, that's tracked at https://github.com/dotnet/aspnetcore/issues/18769 …
=> Add Razor colorization grammar to Visual Studio.

.gitignore, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentManager.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Completions2_1.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/OutOfWorkspaceCompletion.test.ts
Fixes https://github.com/dotnet/aspnetcore/issues/14304.
So what happens here is that documents get added by the file watcher, which only watches the work-space folder, so when you open a file outside of the work-space it calls in to` _getDocument`, where it throws the error bellow. Since there's no reason we shouldn't have out-of-work-space files in the document list I've modified `_getDocument` to create and insert the document if it doesn't already exist.
Since the Workspace for the functional tests is the testapps folder I did have to pollute the test directory with a cshtml file which shouldn't normally be there to write a test. I'm open to suggestions on avoiding that.
=> Out of workspace files

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorEditorFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- Had to add logic to explicitly disable the LSP editor on clients because we don't need or want a Language Server spinning up on the client side. This manifests through the use of the language client's `ClientName` feature.
- Could not add tests for these scenarios because they're all end-to-end driven.
- Found an interesting issue where our `RazorEditorFactory` was not being selected on the VS server but was on the client. Have spun off separate threads to investigate why.
dotnet/aspnetcore#17788
=> Turn Razor LSP editor on by default in VS server scenarios.

activate.sh, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpDocumentSnapshot.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpHostDocument.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/LatestProjectConfigurationProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/BackgroundDocumentProcessedPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/LatestProjectConfigurationProviderTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/14318.
- Added `activate.sh`. This was missing and I needed it to do my debugging in Linux, so I just added it here. It's an exact copy of what's in https://github.com/dotnet/aspnetcore
- OmniSharpHostDocument now throws is TargetPath doesn't meet the expected requirements.
- Normalize Document TargetPaths. We expected MSBuild to do this for us, but it's not (either correctly or wrongly.)
- Fix tests to reflect our expectations.
- Remove machine-scope of `razor.plugin.path` for local exception (It needs to stay machine-scoped in Omnisharp though). Again, needed this to debug in Linux.
=> Normalize Linux Pathing

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Microsoft.AspNetCore.Razor.LanguageServer.Common.csproj
The `NU5104` warning in this project is a constant source of failures in stable builds of this branch. We should figure out if we're doing something wrong with this reference, but for now we can just suppress the warning. Example of a failing build: https://dev.azure.com/dnceng/internal/_build/results?buildId=522096
CC @dougbu @JunTaoLuo 
@Pilchie is this alright for 3.1.3 tell mode?
> F:\workspace_work\1\s.dotnet\sdk\3.1.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X [3.1.3-servicing.20114.2, )" or update the version field in the nuspec. …
=> Suppress warnings about depending on non-stable versions of packages

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentFactory.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentFactoryTest.cs
- We hook into the `VirtualDocumentFactory` sub-system and when we're asked to create a virtual document for a Razor file we will now create a virtual Html document backed by a `htmly` content typed buffer.
- Eventually our `HtmlVirtualDocument` type will have the logic to update its underlying `ITextBuffer`. We don't expose this at the `VirtualDocument` layer to ensure that no one else can unintentionally update the backing buffer. When we want to add the logic to update the buffer we'll cast the virtual document and update it that way.
- Added a specific `TryGetVirtualHtmlDocument` to our lsp document extensions to enable the extraction of the Html buffer.
- Added tests for the new APIs
dotnet/aspnetcore#17793
/cc @ToddGrun @alexgav @jimmylewis
=> Create Virtual Html document for LSP Razor document.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentFactory.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentFactoryTest.cs
- We hook into the `VirtualDocumentFactory` sub-system and when we're asked to create a virtual document for a Razor file we will now create a virtual C# document backed by a `C#_LSP` content typed buffer.
- Eventually our `CSharpVirtualDocument` type will have the logic to update its underlying `ITextBuffer`. We don't expose this at the `VirtualDocument` layer to ensure that no one else can unintentionally update the backing buffer. When we want to add the logic to update the buffer we'll cast the virtual document and update it that way.
- This code still does not handle adding that C# buffer and its context to the C# workspace under the correct project etc. This will have to be a follow up.
- Added an `LSPDocumentExtensions` class as a way to pick out a specific C# document from our LSP …
=> Create Virtual C# document for LSP Razor document.

src/Razor/Razor.sln, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentFactory.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultFileUriProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/LSPDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorLSPTextViewConnectionListenerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/xunit.runner.json
- This changeset adds the Razor LanguageServerClient testing project as well as some tests for the VS document  manager APIs.
- Inherited the `src` LanguageServerClient's ruleset to avoid unimportant VS rules from applying to our test project.
- Added tests for https://github.com/dotnet/aspnetcore-tooling/pull/1602
dotnet/aspnetcore#17791
dotnet/aspnetcore#17748
=> Add tests for the VS LSP document manager.

src/Razor/Razor.sln, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultFileUriProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/FileUriProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentManagerBase.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextViewConnectionListener.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/TextBufferExtensions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/TrackingLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VirtualDocumentFactory.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultFileUriProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/LSPDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorLSPTextViewConnectionListenerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/xunit.runner.json
- Built out the document management infrastructure that will be responsible for understanding all LSP related documents in the VS IDE. The core purpose of this system is to
1. Understand an LSP documents lifecycle, aka know when it starts/ends
2. Allow all LSP documents to be looked up in an LSP friendly format. LSP friendly formats are via URIs.
3. Create addressable virtual documents for a top level documents. In our case our top level document is a .razor/.cshtml file and we'll be creating two virtual documents per top-level document (C#/HTML).
- I also had a sub-goal to build this system out with minimal Razor dependencies. WTE will need to have a similar system where they can turn an HTML document into a top level document with a JavaScript/CSS virtual document associated.
- Utilized …
=> Add Visual Studio LSP document tracking manager.

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/JavaScript.tmLanguage.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/csharp.tmLanguage.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/css.tmLanguage.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/html.tmLanguage.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- VS TextMate grammars can only reference other grammars that are included in the scope of the extension. Therefore we need to reship the C# and HTML grammars; however, the HTML grammar also depends on the JavaScript and CSS grammars so we need to ship those as well.
The colors aren't perfect yet, that'll be addressed in https://github.com/dotnet/aspnetcore/issues/18769. Here's what it looks like today:
dotnet/aspnetcore#17801
=> Include embedded language grammars in Razor VSIX extension.

azure-pipelines.yml
Addresses #dotnet/aspnetcore-internal#3516
duplicating fixes described in https://github.com/dotnet/extensions/pull/3016
=> Add /p:DotNetPublishUsingPipelines=value setting for Win Debug builds

src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs
- Found that cloud scenarios require that editor factories running need to support `VSConstants.LOGVIEWID.TextView_string`. Therefore, we now broadcast that we support that which allows our editor to be potentially selected.
- Upped our editor factory priority from 51 -> 52. Must have misread the XML/Web editor priorities when I initially wrote the code. Turns out 51 is what the XML/Web editors are currently at which means if reflection isn't kind enough to us there's a chance that those editors will sit in front of ours which is unintended.
Fixes dotnet/aspnetcore#19186
=> Use Razor's new editor experience in cloud scenarios.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/RazorCodeDocumentExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentContainerStore.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultHostDocumentFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/GeneratedDocumentContainerStore.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/GeneratedDocumentPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Program.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/UnsynchronizableContentDocumentProcessedListener.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/UpdateBufferRequest.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpDocumentSnapshot.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Html/HtmlProjectedDocument.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RPC/UpdateBufferRequest.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentManager.ts, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultDocumentSnapshot.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultImportDocumentSnapshot.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentSnapshot.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/GeneratedDocumentContainer.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/HostDocument.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedCodeContainerStoreTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedDocumentPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultHostDocumentFactoryTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/UnsynchronizableContentDocumentProcessedListenerTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/tests/HtmlProjectedDocument.test.ts, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DefaultDocumentSnapshotTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/GeneratedDocumentContainerTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateGeneratedOutputTest.cs, src/Razor/test/VSCode.FunctionalTest/tests/Completions.test.ts, src/Razor/test/VSCode.FunctionalTest/tests/HoverComponents.test.ts
Fixes https://github.com/dotnet/aspnetcore/issues/14286
- Refactored GeneratedCodeContainer and friends to include two output versions instead of one (CSharp and HTML)
- Added an `updateHtmlBuffer` command to update the buffer on the client
- Updated `RazorDocumentManager` and `HtmlDocument` on the client side to follow the same behavior of CSharp for updating the virtual background document
- Fixed a bug in `UnsyncronizedDocumentProcessedListener` where we were updating the background C# document with all razor content
=> Publish generated HTML in the client

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Microsoft.AspNetCore.Razor.LanguageServer.Common.csproj, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed.csproj, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/Microsoft.AspNetCore.Razor.OmniSharpPlugin.csproj
- This was a total oversight on my part. These bits were never intended to be shipped to NuGet.
Fixes dotnet/aspnetcore#19072
=> Stop shipping Razor language server bits to NuGet.org.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultProjectHierarchyInspector.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/IRemoteHierarchyService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/ProjectHierarchyInspector.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorEditorFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RemoteHierarchyService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RemoteHierarchyServiceFactory.cs
- "Unsupported projects" typically represents legacy ASP.NET projects.
- This change was slightly more tricky than anticipated. Reason being, in cloud scenarios (LiveShare) you can't always directly access the project system because it doesn't exist on the guest machine. To account for this I used the LiveShare infrastructure to create proxy services that enable a guest to query the host for project system capability fulfillments.
- Abstracted project project hierarchy inspection into a project hierarchy inspector. For now we only inspect capabilities; however, any project system asks in the future will need to flow through this path as well. In practice this class is responsible for undersetanding if it's running in a "Guest" or "Host" environment and doing the "right thing".
- Created a …
=> Disable Razor LSP editor in unsupported projects.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ILanguageServerExtensions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/BindingRedirects.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest, src/Razor/src/rzls/rzls.csproj
- Moved away from booting an OOP Razor Language Server in the new Razor LSP editor scenarios in order to remove the requirement to manage the `rzls` process lifetime and to also ensure that Razor's editor communication doesn't need to cross process boundaries.
- Now that the Razor LanguageServer Client references the language server project directly our VS extension transitively references our language server which means it no longer needs to do MSBuild magic to include the language server binaries.
- Added extension manifest and VSIXSource entries to the VS extension project to ensure that O# bits make it into our VS extension
- Added `[ProvideBindingPath]` to our `RazorPackage` definition to enable VS to load O# assemblies without them being MEF discoverable.
- Spent 10+hrs trying to …
=> Run Razor Language Server in-proc in VS.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentManagerExtensions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/TextChangeExtensions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/LSPDocumentTest.cs
- Added a custom message target for our Language Server client to handle `razor/updateCSharpBuffer` requests from the server.
- Added plumbing on the client to handle C# buffer updates and then update the text buffer that backs the C# virtual document.
- Added extension methods to make interacting with Roslyn types and our document manager easier.
- Added tests for the new API.
Fixes dotnet/aspnetcore#17835
=> Update C# buffer in VS LSP scenarios.

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- We've captured the top-level dependencies in our component governance list; however, any additional dependencies we need to add to Visual Studio (we start using one of the APIs) will require us to re-mark one of our component governance items.
=> Add OSS Component Governance comment.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocumentSynchronizer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentSynchronizer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentSynchronizerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestLSPDocumentSnapshot.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestVirtualDocumentSnapshot.cs
- The purpose of an LSP document synchronizer is to synchronize a virtual document and an LSP documents buffers. Given a `VirtualDocumentSnapshot` and an `LSPDocumentSnapshot` the synchronizer will wait until a new `VirtualDocumentSnapshot` becomes available that matches the original `LSPDocumentSnapshot`'s version number. This ensures that any requests done after synchronization will be for the "correct" document.
- By default the synchronizer has a 2s timeout in waiting for virtual documents and host documents to synchronize.
- Synchronizations are memoized, meaning if multiple synchronizations happen for the same virtual / host document combo then we will return a single task object representing the success or failure of those synchronizations.
- I made an assumption that …
=> Add LSP document synchronizer.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentSnapshot.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocumentSynchronizer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentSnapshot.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentChangeEventArgs.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentChangeKind.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentManagerExtensions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentSnapshot.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentSynchronizer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/TrackingLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VirtualDocumentSnapshot.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentSynchronizerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/LSPDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestLSPDocumentSnapshot.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestVirtualDocumentSnapshot.cs
- To enable `Change` events on the `LSPDocumentManager` I had to transition our VS model to use snapshots for our `LSPDocuments`. Overall this was a positive change anyhow and is one of my regrets of our VSCode infrastructure. Especially given that the LSP document infrastructure will most likely be shared amongst more than our team having the flexibility to understand when events happen in a snapshot based way will ensure we have the least amount of bugs.
- The snapshot model in this changeset pivots the `LSPDocumentManager`'s document retrieval mechanism to retrieve snapshot variants of each `LSPDocument` and their corresponding `VirtualDocument`. We use `LSPDocument`s inside of `LSPDocumentManager` and update those in a stateful way. Each LSP document understands when it or one of its …
=> Update LSPDocumentManager to notify on document Changes.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorSyntaxTreeExtensions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/DefaultRazorFormattingServiceTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/19609
We get a null-ref in cases of non-extensible directives like `@using` which don't have a DirectiveDescriptor attached to them.
=> Fix formatting fails in the presence of a non-extensible directive

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/17836
=> Wire up updating the LSP background html document

src/Razor/test/VSCode.FunctionalTest/tests/Rename.test.ts
This test failed a couple of times seemingly for no reason. Skipping.
[Example failure](https://dev.azure.com/dnceng/internal/_build/results?buildId=554598&view=ms.vss-test-web.build-test-results-tab&runId=17492994&resultId=100046&paneView=debug)
Updated https://github.com/dotnet/aspnetcore/issues/19296
=> Skip rename test

eng/targets/Npm.Common.targets
Add Explicit Helix Python path if that path exists for build. 
- Python 2 is EOL as of 1/1/2020; the most recent rollout removed this from Windows machines
- Certain Yarn installs require a viable python 2 or 3 on the path; this broke the build.
Works around https://github.com/dotnet/core-eng/issues/9351 until it is addressed.
=> Tell NPM to use "C:\python3.7.0\python.exe" if it's present

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundDocumentGenerator.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultDocumentDivergenceChecker.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DocumentDivergenceChecker.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultDocumentDivergenceCheckerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs
- This is a performance optimization where when we see a Razor file has changed we will not re-parse all of the related files unless we determine that the change has impacted a C# property.
- To accomplish this we look at the before and after of a document and see if the documents `@code` / `@functions` has any C# property changes. If they don't we let the `BackgroundDocumentGenerator` know that it doesn't need to re-queue parses for dependent documents. Ultimately this seemed like a heavy check to do on every change; however, a single file reparse for a closed (dependent) document results in us letting Roslyn know about the updated C# which then kicks off re-classification, errors, etc. Basically, a lottt more work then we'd ever want to have happen.
- In our divergence checks I took the …
=> Don't always re-parse dependent Blazor files on change.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectWorkspaceStateGenerator.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultProjectWorkspaceStateGeneratorTest.cs
- Not entirely sure why we were getting `ObjectDisposedException`s in VS4Mac but decided to make our code extra defensive.
- Could only write one test for `Disposed` being queued on the foreground thread prior to `Update` but it doesn't make much sense in practice because we never `Dispose` the generator. The other potential path for this issue assumes that VS4Mac's foreground thread isn't truly single threaded which we can't test because that breaks all of our test concepts. Basically, this PR is just being extra defensive to ensure we don't explode some concepts on the VS4Mac side of the world.
Fixes dotnet/aspnetcore#19813
=> WorkspaceStateGenerator - Ensure we never cancel a CTS after it's been disposed.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultDocumentServiceProviderFactory.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentServiceProviderFactory.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DynamicDocumentContainer.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorDocumentServiceProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundDocumentGenerator.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultDynamicDocumentContainer.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDynamicFileInfoProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorDynamicFileInfoProvider.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultRazorDynamicDocumentInfoProvider.cs, src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorDocumentInfoProviderTest.cs
- We have a parallel set of work in progress right now where we're moving off of Roslyn's internal types which includes the dynamic file info provider APIs. This changeset accomplishes two things.
1. Start moving towards Roslyn's internal APIs
2. Prep the dynamic file info provider APIs to be used to add CSharp virtual document's in LSP editor world to the Roslyn workspace.
- Build a `DynamicDocumentContainer` which is used to query information about our Razor documents (`DocumentSnapshot` or `CSharpVirtualDocumentSnapshot`) and use that information to notify Roslyn on how our documents should be handled in their workspace.
@tmat this is the "prep" work I was referring to.
@KirillOsenkov FYI since this changes a little bit of how our dynamic document file provider in VS4Mac functions.
=> Transition our DynamicFileInfoProvider into using DynamicDocumentContainer.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/ConfigurationChangeListener.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Diagnostics/ReportIssuePanel.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServerClient.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLogger.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/TelemetryReporter.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts
- General implementation for properly stopping and restarting the Razor Language Server (`ConfigurationChangeListener`)
- Propagation of the new trace level
- Restart message prompt on configuration change
- Telemetry for failed server stop
Addresses https://github.com/dotnet/aspnetcore/issues/14280
=> Restart Razor Language Server When Changing Trace Level

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorDynamicFileInfoProvider.cs
- When toggling between Razor LSP editor on/off we need to support turning our dynamic file info provider pieces on/off correctly for LSP documents.
- Could not add tests because of Roslyn IVT restrictions.
=> Fix LSP editor feature switch toggle bug.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs
- With how the synchronization APIs work we can't re-inspect the document snapshot's host document version without re-querying for the document (it's a snapshot). Therefore, removed the debug assert and are relying on the correctness of the synchronizer.
=> Removed debug assert in projection provider.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveData.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionResolveHandlerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/19628 and https://github.com/dotnet/aspnetcore/issues/19851
Added a CompletionResolveHandler that manually invokes the correct language server based on the given CompletionItem. We currently only call through to the CSharp language server because the Html one doesn't yet support completion resolution.
=> Support VS LSP C# completion resolution

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.tmTheme
- This makes our new Razor LSP editor bits look almost identical to the existing VS experience.
- There are several issues in regards to C# in attributes and that's tracked here: https://github.com/dotnet/aspnetcore/issues/20140
- There's no semantic colorization for tags or C# yet either so that breaks down the colorization expected for our Blazor components and TagHelpers.
- Had to name the textmate grammar with the specific name of `aspnetcorerazor.tmLanguage.tmTheme` in order to enable the VS themeing support to locate our theme.
- One big colorization difference that can't currently be supported is the background coloring of our C# bits. This is something VS' CoreEditor is willing to change on our behalf though.
New (left) vs Old (right)
FYI @danroth27 / @mkArtakMSFT 
Fixes …
=> Associated our TextMate grammar scopes with VS classifications.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedDocumentPublisherTest.cs
- I found that when interacting with the editor our document snapshot system would not always hold onto generated ouptut once all references to it were relinquished. Internally our document snapshots have a weak reference to their output meaning that data can be GCd inbetween requests.
- To handle situations where our generated documents output data was GCd I changed how our document publisher would decide to publish virtual document output. It now stores its last publish data (source text + doc version) and compares the previous publish data to what's about to be published. In the case that everything matches then there's no reason to re-publish.
- Ultimately this should result in huge performance gains in both VSCode and VS because we'll no longer be re-publishing our C#/HTML on every …
=> Don't publish identical C#/HTML data.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextDocumentCreatedListener.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorLSPTextDocumentCreatedListenerTest.cs
- LiveShare takes care of propagating all editor behaviors to the host and replicating all of our logic on the guest which ends up causing issues where our hidden buffers end up getting written to disk.
- With this change we only change the content type in remote client scenarios in order to enable TextMate grammar colorization
=> Don't spin up LSP editor world on remote clients.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/ProjectionResult.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/TrackingLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VirtualDocument.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/LSPDocumentTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/17803
- Updated the `TrackingLSPDocumentManager` and `LSPVirtualDocument` APIs to support provisional changes
- Update `CSharpVirtualDocument` to apply provisional changes and revert it whenever another change is about to happen
- TODO: Revert when the completion dialog is dismissed without needing to wait for another change. This is trickier than I thought. I'm planning to do it in a separate PR
- Added/updated tests
=> Support provisional C# completion

azure-pipelines.yml
Currently the master branch builds both debug and release configurations internally, and both try to publish. This creates a race condition by which we sometimes wind up publishing debug packages/symbols - one symptom is mismatched symbols being published to msdl, among potentially others. This isn't an issue in 3.1 as we don't try to publish from the debug configuration there. The safest way to fix the issue is just to disable windows debug builds on the internal side.
CC @NTaylorMullen @mmitche @MattGal @dougbu @JunTaoLuo 
Internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=582612
=>  Don't build windows debug internally

azure-pipelines.yml
Port of https://github.com/dotnet/aspnetcore-tooling/pull/1738
Currently the master branch builds both debug and release configurations internally, and both try to publish. This creates a race condition by which we sometimes wind up publishing debug packages/symbols - one symptom is mismatched symbols being published to msdl, among potentially others. This isn't an issue in 3.1 as we don't try to publish from the debug configuration there. The safest way to fix the issue is just to disable windows debug builds on the internal side.
I'll send mail to shiproom asking for approval
=> [release/5.0-preview3] Don't build windows debug internally

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorService.cs
After auto-completing a text tag when we press Ctrl + Z,
```razor
@{ <text></text> }
```
Without this change,
```razor
@{ <text>__placeholder__</text> }
```
With this change,
```razor
@{ <text> }
```
Suggest reviewing with [?w=1](https://github.com/dotnet/aspnetcore-tooling/pull/1739/files?w=1)
=> Fix undo on <text> tag auto-closing

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationStateSynchronizerTest.cs
The filepaths gets constructed in different ways, so they aren't a string match. Without this change a Debug.Assert fails in Debug mode, and projects will not be successfully removed from _configurationToProjectMap when unloaded in Production.
=> Normalize filepaths to ensure they match

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/InviolableEditTag.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/TrackingLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VirtualDocument.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/LSPDocumentTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/17803
- Turns out we don't even need to persist the provisional change till the next update. We just need the change there long enough for us to invoke a completion request and get the result.
- This simplifies things a lot and removes the need for any kind of hackery in the Document manager or the Virtual Document layer
- All logic for provisional completions is contained within a single method in CompletionHandler
- Reverted a bunch of code from my previous PR and updated tests
- Verified manually that this works as expected and doesn't visibly impact performance
=> Simplified provisional completion implementation

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultRemoteTextLoaderFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/FilePathNormalizer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RemoteRazorProjectFileSystem.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Common.Test/FilePathNormalizerTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentResolverTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentVersionCacheTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedCodeContainerStoreTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorProjectServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationFileChangeEventArgsTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectFileChangeDetectorTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileChangeDetectorTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RemoteRazorProjectFileSystemTest.cs
- I imagine this changeset will cause several unintended side effects. I've tried to verify our scenarios in VS and VSCode but undoubtedly I've missed a few. That's why I'm getting this in early to verify things work as expected.
- Found that we were already normalizing file paths this way for read operations. Because of that I removed the `NormalizeForRead` in favor of our new `Normalize` method to ensure all call paths are flowing through the same normalization path.
- Updated the `NormalizeForRead` tests to test the new `Normalize` path.
- Updated existing tests that passed in a path with a prefixed slash (`/path/to/file`) to use `C:/`. Surprisingly `C:/` paths work as expected cross-plat at runtime as long as we don't test trying to write any files (we don't).
- Found that our …
=> Stop platform agnosticly normalizing file paths on windows.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationStateSynchronizerTest.cs
- Found that when our project state synchronization would fail to deserialize a project configuration and then later attempt to remove it we'd hit this `Debug.Assert`. Failing to deserialize a project configuration is allowed due to us lacking control over how the file system writes those files to disk.
- Added a test to cover the scenario.
=> Fix error when removing project configuration after failed deserialization.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/CodeActions/RazorFullyQualifiedCodeActionTranslator.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCSharpLanguageMiddleware.ts
Resolves the double tab spacing when using the Fully Qualified Namespace code action within @code blocks. Further details in code comments.
Fixes dotnet/aspnetcore#19449
=> Fixed multiline FullyQualifiedNamespace Edits

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultForegroundDispatcher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentVersionCache.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentVersionCache.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/DefaultOmniSharpForegroundDispatcher.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentVersionCacheTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationStateSynchronizerTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/UnsynchronizableContentDocumentProcessedListenerTest.cs
Before this change, we were evicting documents from the cache when we untrack them even if it still exists on disk. 
This change makes it so we leave it in the cache until it gets deleted from the disk. Otherwise we can run into null-refs when resetting our project snapshot as part of updating our understanding from `project.razor.json`.
=> Make DocumentVersionCache evicting logic smarter

src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultRazorProjectHost.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/RazorProjectHostBase.cs, src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/DefaultRazorProjectHostTest.cs
- Capture project level document information for VS4Mac Blazor scenarios
- Add a few tests.
- Some how we lost this changeset in our master branch.... It was originally done [here](https://github.com/dotnet/aspnetcore-tooling/pull/1335) but maybe it never made it into master? Not entirely sure about the events that led to this mishap but here's a fix.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1086561
/cc @KirillOsenkov
=> Finish Blazor VS4Mac experience - Again

CONTRIBUTING.md
For more details, see [PR16](https://github.com/dotnet/org-policy/blob/master/doc/PR16.md).
=> Fix links to Code of Conduct

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DynamicDocumentContainer.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorDocumentServiceProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultDynamicDocumentContainer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentPublisher.cs
- These diagnostics act similar to non-Razor diagnostics meaning if you open a file which has Razor diagnostics you will now permanently be prompted with those errors until you've resolved them. This was an odd case that I didn't realize was the "norm" for C# files until trying it out in Razor.
- This changeset utilizes changes from Roslyn where we associate our dynamic C# documents with Roslyn's [RazorLanguageClient](https://github.com/dotnet/roslyn/blob/d8e8df8d8bae3df5785acaa419a9963d7e92e74a/src/VisualStudio/Core/Def/Implementation/LanguageClient/RazorLanguageClient.cs) which has a `ClientName` of "RazorCSharp". By associating our documents with that language client Roslyn wont treat those documents as closed and allow diagnostics for them to flow through the system.
Fixes …
=> Add support for C# diagnostics in LSP powered Razor files.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultFileUriProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocumentSynchronizer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/FileUriProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPDocumentSynchronizer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/TextBufferExtensions.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Infrastructure/TestTextBuffer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultFileUriProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPDocumentSynchronizerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProjectionProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestVirtualDocumentSnapshot.cs
- Prior to this we would listen to the `LSPDocumentManager`'s update events and on a virtual document changed event we would resolve active synchronization requests. Turns out that doesn't work because the act of updating our virtual document representation doesn't mean that the corresponding sub-language language server for the virtual document has seen the change. This "non-guaruntee" gets tested regularly in remote scenarios where our language server is powering a remote client. Therefore to work around this limitation I've rebuilt the synchronizer to act on `PostChanged` events of VirtualDocument's TextBuffers. The reason why this is important is that the LSP platform in Visual Studio will notify language servers of TextBuffer changes; therefore, by waiting for for "post changed" we …
=> Redesign LSP virtual document synchronization.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorOnTypeFormattingEndpoint.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/DefaultRazorFormattingServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorOnTypeFormattingEndpointTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/20619
- Handled onTypeFormatting for `*` to enable Razor comment auto-closing
- Updated cursor movement logic to also dismiss any existing completion dialogs. Without that, the completion dialog from typing the `@` remains even after we applied the edits
- Added tests
=> Support auto-closing Razor comments

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/MarkupTransitionCompletionItemProvider.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/MarkupTransitionCompletionItemProviderTest.cs
Turned out to be a relatively simple fix after the investigation revealed the root cause of all three issues to be the same.
https://github.com/dotnet/aspnetcore/issues/20590
https://github.com/dotnet/aspnetcore/issues/20590#issuecomment-610523530
https://github.com/dotnet/aspnetcore/issues/19815
The root cause for all three issues relates to the encapsulating `MarkupElementSyntax.ChildNodes`. When there is an (unrelated) closing `>` somewhere else in the document, the parser will interpret everything between the opening `<` and closing `>` as being part of the start tag. @ajaybhargavb clarified that this is by [design](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlMarkupParser.cs#L975). Due to this, the …
=> Updated Markup Transition Tag Contextual Availability Logic

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.tmTheme
- C# control flow statements like `return`  weren't getting colored. Added a listing to the `keyword.control.flow` listing.
- Other C# loop constructs such as `while` and `do` weren't getting their proper colorization so expanded the `keyword.control.loop` entries to not be specific on a per-keyword basis.
Fixes dotnet/aspnetcore#20880
=> Add colorization support for "return" & other C# loop constructs.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPEditorService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextDocumentCreatedListener.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorLSPTextDocumentCreatedListenerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/20651
_Left: Host &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Right: Guest_
- Added a temporary method to listen for guest buffer changes. Whenever we see a change that replaces `__placeholder__` with cursor position, we now manually move the cursor position on the guest as well
- This doesn't fix the undo stack on the guest. Fixing that with the current design would take a lot more time/effort and not worth it IMO
- Testing this would be a pain as this is all VS API. Plus this is all super temporary code …
=> Move cursor on the guest

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/HoverHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestDocumentManager.cs
Adds C# Razor Hover Support to Visual Studio. 
- Requires https://github.com/dotnet/roslyn/pull/43388 to be merged in and available for the `textDocument/hover` request to the C# Roslyn LSP to be accepted. Thanks @dibarbet!
- Visual Studio support for multiple hover handlers added.
- HTML hover support is currently blocked on the HTML LSP. Integration just requires removing the C# guard (https://github.com/dotnet/aspnetcore-tooling/compare/taparik/vs_hover_handler?expand=1#diff-ede37ecb91c141853c9e2b65fdc8c051R87-R91) and adding in the appropriate tests.
- Classifications (colors), bold/italics and links are missing (Roslyn is planning to add in the support later)
(Note: The extra trailing blank line can be ignored, I haven't recompiled roslyn with the latest changes which addresses that …
=> C# Hover Implementation

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DefaultTagHelperDescriptionFactory.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultTagHelperDescriptionFactoryTest.cs
Right now we end up with trailing new-lines in some cases, which make the Hover/Completion windows look weird. This PR should improve that look and feel somewhat.
Before:
After:
I think there's an argument to be made that the scenario in `TryCreateDescription_Element_MultipleAssociatedTagHelpers_ReturnsTrue` should have newlines before and after the `---` but I went with what looked right to me and kept things more compact.
Fixes https://github.com/dotnet/aspnetcore/issues/20875.
=> Only have lines if they're needed

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/21036
cc @ToddGrun
=> Added ' ' as a trigger character for HTML completion

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/HoverHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs
HTML LSP Hover Support now available. I've tested out the functionality by building and running the WTE HTML LSP locally.
Once I got the WTE HTML LSP working, actual integration changes were minimal (leveraging the C# integration).
Keeping as a draft PR until the updates are available in VS (eta Wednesday).
Fixes https://github.com/dotnet/aspnetcore/issues/20963
=> Added VS HTML Hover Support

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs
- I've disabled LSP document open genreated output publishing to work around: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1109023
- The "undo" of this workaround is tracked here: https://github.com/dotnet/aspnetcore/issues/21126
Fixes dotnet/aspnetcore#21115
=> Disable Razor doc generated output publishing on doc open.

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileChangeDetectorTest.cs
- I believe with a 1 millisecond enqueue delay the Task.Delay method can sometimes run synchronously resulting in a deadlock in the file change detector. To test this theory I've increased the delay to 50ms to avoid the special casing.
=> Attempt to fix the build.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs
- Tried figuring out why the `FileSystemWatcher_RazorFileEvent_Background_NotificationNoopToAdd_NotifiesAddedOnce` continuously failed only on the public CI's debug build. Only thing  I could come up with was XUnit's synchronization context being a little wacky. I refactored the change detector's notification dispatch piece to do all pending notification calculations on the foreground thread with a lock to ensure ordering and also to enable us to await it on the background thread.
- Take 2 at attempting a build fix. If only I could see this repro in PR builds or even locally 😢
=> Refactor RazorFileChangeDetector notification dispatch to work with XUnit synchronization context.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileChangeDetectorTest.cs
- Now that the `RazorFileChangeDetector` awaits its dispatched foreground thread I can change the way the test "waits for completion" by exposing the pending notifications and awaiting their notifications.
=> Take 3 at fixing the public CI build.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Html/HtmlPreviewPanel.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Html/HtmlTagCompletionProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Html/RazorHtmlFeature.ts
Now passing the HTML text content, instead of the raw razor content to the HTML parser.
Before:
After:
Fixes https://github.com/dotnet/aspnetcore/issues/21127
=> Fixed HTML Tag Auto-closing

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/HoverHandler.cs
The Roslyn C# and WTE HTML hover handler `textDocument/hover` endpoints are now available. VSLanguageServer support for multiple hover handlers has also been enabled. Removing the temporary silent failure.
Fixes https://github.com/dotnet/aspnetcore/issues/20962
=> Remove Hover Handler Silent Failure

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorProjectChangePublisher.cs
- Since we can't control when a might have a tmp file lying around we shouldn't be debug asserting its failure.
=> Remove Debug.Fail when tmp file still exists.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs
https://github.com/dotnet/aspnetcore/issues/20324
Without this we were losing information as part of the deserialization and the client never sees the icons set by the HTML language server.
@ToddGrun
=> Deserialize VS Client LSP types correctly to not lose information

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
Both the `CompletionItem.Detail` and `CompletionItem.Description` were being set.
Per [the definition of `CompletionItem`](https://github.com/OmniSharp/csharp-language-server-protocol/blob/master/src/Protocol/Models/CompletionItem.cs#L34-L45):
Detail is "A human-readable string with additional information about this item, like type or symbol information."
Documentation is "A human-readable string that represents a doc-comment."
Documentation is also a `StringOrMarkupContent` type vs `String` type of `Detail`. As such, `Documentation` seemed to be the better fit. I've updated to only set the `Documentation` when converting a `RazorCompletionItem` to a `Omnisharp.CompletionItem`.
Fixes https://github.com/dotnet/aspnetcore/issues/21189
=> Removed duplicate directive documentation

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs
- No reason for us to understand file deletions any quicker than every 1s.
- Saw Ryan's box having the duplicate error issue still and want to rule out that it's too slow 😄
=> Update Add/Remove Razor file batch detection to 1s

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentVersionCache.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentVersionCache.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentVersionCacheTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedDocumentPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/UnsynchronizableContentDocumentProcessedListenerTest.cs
- Technically LSP clients don't have a concept to notify the server of "deleted" documents. They only have a concept of "closed" documents. Thankfully our project snapshot manager operates in a similar fashion where a document can be removed but still be opened. Therefore, in order to bind our tracked document state (doc version + generated doc publishings) to LSP's capabilities we're only evicting old document state when they get closed. If they get removed it may be a transient state which will later be corrected and shouldn't impact the version cache because its purpose is to retrieve document versions for open/closed documents based on what the LSP client tells our server.
- Removed tests that expected deleted documents to remove corresponding state.
Fixes dotnet/aspnetcore#21302
=> Stop evicting document state on file removal.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/21154
Before:
After:
=> Fix completion commit with explicit expressions

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- This also indirectly adds support for some more auto-closing pairs. Ultimately since VS added support for `language-configuration.json` files like in VSCode we now just lift that file into the extension install directory.
- Not something you can write tests for.
Fixes dotnet/aspnetcore#21290
=> Add support for declarative Razor comments.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DefaultTagHelperDescriptionFactory.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultTagHelperDescriptionFactoryTest.cs
https://github.com/dotnet/aspnetcore/issues/21306
Basically the summaries we get probably have leading and trailing newlines, so let's trim them, using the StringBuilder for hopefully performance.
=> Trim newlines from summaries

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DefaultTagHelperCompletionService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/MarkupTransitionCompletionItemProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultTagHelperCompletionServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderTest.cs
Thanks @ajaybhargavb 
Fixes: https://github.com/dotnet/aspnetcore/issues/21066
Fixes: https://github.com/dotnet/aspnetcore/issues/21485
=> Added Colon as a Commit Character

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/HoverHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/LSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnTypeFormattingHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionResolveHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPDocumentMappingProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProjectionProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPRequestInvokerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/OnTypeFormattingHandlerTest.cs
- Renamed `RequestServerAsync` to `ReinvokeRequestOnServerAsync` to indicate that the method should be used to "re-trigger" requests and nothing else. The reason for this clarification is that this variant is technically slower then the new `CustomRequestServerAsync` because it will go through the same synchronization pipeline as all other `textDocument/didChange` requests meaning you're guarunteed for the "reinvoked" request to happen in the right order. For custom requests those can all happen in parallel and ordering isn't guarunteed because it doesn't matter (much quicker).
- Added new tests for the `CustomRequestServerAsync` method.
- Changed our projection and mapping providers to utilize the `CustomRequestServerAsync` because order doesn't need to guaranteed for custom requests. …
=> Add support for SynchronizedRequestAsync.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DefaultTagHelperCompletionService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProviderBase.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultHtmlFactsService.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderBaseTest.cs
Each of these individual Syntax nodes define the `NamePrefix` property. The property is not shared with `MarkupSyntaxNode` nor a common interface.
I didn't see a way to add an interface to the `Syntax.xml` node definitions, so I elected to take this approach.
We encounter this issue in cases like:
`<svg xml:base=""x| ></svg>`
Fixes: https://github.com/dotnet/aspnetcore/issues/21554
=> Added null NamePrefix Checks to MarkupSyntaxNode(s)

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPEditorFeatureDetector.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPRazorProjectHost.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorProjectHost.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/LSPRazorProjectHostTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/21035
- We'll now boot Razor, C# and HTML servers if we open a Razor project and have the LSP preview feature checked.
- Also handled Shutdown request that we missed in one of our servers
- Separately, there is an issue with Shutdown not being called on solution close on non-liveshare scenarios that I am following up with partner teams on
=> Pre-boot language servers if applicable

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPRazorProjectHost.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/LSPRazorProjectHostTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/21035
Looks like this is enforced in the latest VS builds.
=> Pre-boot language servers on the UI thread

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DefaultTagHelperDescriptionFactory.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultTagHelperDescriptionFactoryTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/21192.
TLDR: TryExtractSummary was giving up and returning nothing if it couldn't find a matching pair of summary tags. Since Directive attribute documentation doesn't come form doc-comments it's not in that format, and nothing was being returned. Now if it's the case that no XML is detected we'll return the whole documentation (no XML so that if its missing a summary but has return tags and/or param tags we don't show that whole mess).
=> DescriptionFactory handle Directive attributes

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPRazorProjectHost.cs
Hopefully the last change here 😄 . One of the checks inside `IsLSPEditorFeatureEnabled()` also need to be done on UI thread.
=> Switch to UI thread sooner

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/LineTrackingStringBuffer.cs
I noticed several hundred ms spent in this method from a customer profile. Primarilly, the method was doing a linear scan of all lines trying to find one that contained the requested position. I changed this to a binary search, but kept/improved the optimization around checking next/previous lines before instigating the search.
Note, there was also a bug where the old code did:
else if (absoluteIndex > _currentLine.Index && _currentLine.Index + 1 < _lines.Count)
but it should have been coparing absoluteIndex with _currentLine.Start
=> Fix perf issue in LineTrackingStringbuffer.ScanLines.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotChangeTrigger.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/EditorDocumentManagerListener.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultProjectSnapshotManagerTest.cs
- I found that our `BackgroundDocumentGenerator` was queuing up multiple changes on solution load and found that because of `ProjectSnapshotChangeTrigger` ordering it would queue up a background generated document publish while it was still being detected as "closed". This meant that when the actual already-opened file would spin up in the editor it would itself create its own C# buffer which would conflict with the background generated document resulting in ambiguous errors. This looks to be more prevalent in latest VS because MEF doesn't guaruntee ordering.
- Added a `Priority` property to `ProjectSnapshotChangeTrigger`s to control when triggers run to ensure our closed/open document state trigger could run prior to any other triggers that may or may not depend on closed/open document …
=> Fix ambiguous errors in C# documents on sln reopen with already open documents.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/CSharpCodeParser.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/CSharpLanguageCharacteristics.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/CSharpTokenizer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlLanguageCharacteristics.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlMarkupParser.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlTokenizer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/LanguageCharacteristics.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/LegacySyntaxNodeExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/ParserHelpers.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/Tokenizer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/TokenizerBackedParser.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/InternalSyntax/SyntaxFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/InternalSyntax/WhitespaceTokenCache.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/StringTextSnapshot.cs, src/Razor/test/RazorLanguage.Test/Legacy/TokenizerLookaheadTest.cs
1) Modify ParserHelpers.IsNewLine to use a switch instead of Array.IndexOf
2) Modify Tokenizer.CreateToken to take in an array of RazorDiagnostics rather than an IReadOnlyList as that was causing a ToArray call on an empty diagnostics very often (during a SyntaxFactory.Token call)
3) Modify TokenizerBackedParser.Putback to allow an IReadOnlyList as a parameter to not require creation of a reverse enumerator.
4) Cut down allocations in HtmlMarkupParser.GetParserState by:
a) Using an IReadOnlyList instead of IEnumerable to get rid of the allocations from the .any calls
b) Don't allocate while reading initial spacing
c) Inline the IsSpacingToken code so cut down on code executed and need to allocate a separate Func
5) Modify CSharpCodeParser.IsSpacingToken to now be a set of methods instead …
=> Several changes targeted to improving perf of RazorSyntaxTree.Parse

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlTokenizer.cs
Our razor typing test measured 153 CPU ms in this method. Optimized by fewer calls to CurrentCharacter, not checking '<' twice, and using a switch stmt.
=> Improve HtmlTokenizer.AtToken performance.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/LegacySyntaxNodeExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/SyntaxNodeExtensions.cs
The razor perf test shows about 70 ms CPU of WithSpanContext is in allocation. GetAnnotation similarly is showing about 60 ms in allocation (of which this only partly improves)
=> Improve Annotation and SpanContext performance.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/CSharpCodeParser.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlMarkupParser.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/TokenizerBackedParser.cs
In the razor perf typing test, Accept was showing 27 ms allocating enumerators. Additionally, modified ReadWhile to only allocate if it would return a non-empty collection (and to not use the complexity introduced by using yield enumerators)
=> Small perf improvement in TokenizerBackedParser.Accept and ReadWhile.

.github/CODEOWNERS
- This code will auto-require the correct people for the specific paths.
=> Update code owners to include Razor tooling team.

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/CSharpLanguageCharacteristics.cs
The razor typing perf test profile I'm looking at has 156 ms of CPU cycles spent in this method, mostly in Enum.ToString()
=> Improve CSharpLanguageCharacteristics.MapKeyword performance

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/CSharpCodeParser.cs
Previous optimization didn't help as much as intended.
By specifying a method group as the arguments to method like ReadWhile, an allocation was still occurring. Instead, cache the Func as a member in the class and use it instead of the method group.
=> Decrease allocations from using method groups

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextDocumentCreatedListener.cs
Fixes https://github.com/dotnet/aspnetcore/issues/21507
We'll need this workaround until partner teams figure out a consistent story for getting the host's options in remote scenarios.
=> Initialize default options on the guest

azure-pipelines.yml, eng/Build.props, src/Razor/Razor.NoVsix.sln
Turns out vsix can only be built using desktop msbuild build right now and we need to use dotnet msbuild to build the rest of the repo due to the net5.0 tfm. Splitting the build into separate steps.
=> Build Vsix separately

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs
- With latest VS insertions this should always be available.
Note: This requires a week-old VSMaster build to run the experimental instance otherwise things will explode
Fixes dotnet/aspnetcore#21468
=> Stop falling back to RequestAsync when SynchronziedRequestAsync is not available.

eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorLanguageService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/OOPTagHelperResolver.cs
This reverts commit 924ca9acf9c5a84e8fc08143c345ffe7968e9882.
Reverting this because we need to get an insertion out.
Context: https://github.com/dotnet/aspnetcore-tooling/pull/1878#discussion_r425476043
=> Revert "Update Roslyn to 3.7 (#1878)"

azure-pipelines.yml
Hopefully resolves the duplicate publishing issue. Not sure if it'll help resolve the missing symbols issue though.
=> Do not build deps when building vsix

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs
- WTE found an issue where if you dismiss completion at the right moment it's possible to deadlock our complete/cancel callbacks in our pre-existing Visual Studio Razor Parser. Basically what would happen is that Dismiss and cancel would be called simultaneously and due to how the task completion source registration/cancellation token would invoke their callbacks we'd get stuck waiting on ourselves. Turns out we don't need to have our cancellation token/task completion source management in our lock at all.
/cc @alexgav @ToddGrun
=> Fix Razor completion source deadlock.

eng/scripts/StartDumpCollectionForHangingBuilds.ps1
- allow FinishDumpCollectionForHangingBuilds.ps1 to complete w/o writing to `stderr`
nit: copy a typo fix from aspnetcore
=> Ignore error output from `Get-Process`

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/Constants.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/TerminateDebugHandler.ts
This PR fixes an issue in the Blazor debug adapter where hosted applications could not be debugged.
Now, the user can set the `hosted` property to `true` in their launch configuration. This will run the server DLL instead of running `dotnet run` as a subprocess.
Currently, this assumes that they have the solution directory open in their VS Code workspace. Having the Server or Client directories open will not work.
=> Fix debugging hosted Blazor WASM apps

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageClientMiddleLayer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefinitionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/GoToDefinitionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPRazorProjectHost.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPContentTypeDefinition.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConventions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextDocumentCreatedListener.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/TextBufferExtensions.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPRequestInvokerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefinitionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/GoToDefinitionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorLSPTextDocumentCreatedListenerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/22015
- Moved some constants and added some utility functions in `RazorLSPConventions` (Most of the file changes here are due to that)
- Added `DefinitionHandler` to do the thing. This now supports go to def on C# parts of Razor. It can,
-  go to definitions within the razor file
- between open razor files
- to external .cs files (open or closed)
- The other way around is not supported yet as that requires changes from Roslyn and is out of scope for this release
- Added tests
=> Support GoTo Definition in Razor VS LSP

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs
FlakyAttribute does not appear to work so skipping the [flaky test](https://dev.azure.com/dnceng/public/_build/results?buildId=654186&view=ms.vss-test-web.build-test-results-tab&runId=20303614&resultId=100122&paneView=debug) instead.
Another timeout in the SDK test: https://dev.azure.com/dnceng/public/_build/results?buildId=654266&view=ms.vss-test-web.build-test-results-tab&runId=20306860&resultId=100161&paneView=debug, so skipping that too
=> Skipping flaky tests

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageClientMiddleLayer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/GoToDefinitionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/HoverHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnTypeFormattingHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/OnTypeFormattingHandlerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/22106
We no longer require the main thread for most cases.
Exceptions are,
- Tracking/untracking documents
- Updating C#/HTML buffers
- Provisional completions (adding/removing provisional dot)
- Applying text edits and moving the cursor
- Logging to the VS Activity logger
Theoretically there is a slight chance that this could cause issues during completions etc but those are very unlikely and I have not seen that happen during testing. Plus we get a good performance boost from not having to switch to the main thread. So the plan is to make this change and keep watch for any threading issues in the editing experience.
=> Remove unnecessary switches to main thread

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCSharpLanguageMiddleware.ts, src/Razor/test/VSCode.FunctionalTest/yarn.lock
This seems to have been exposed in https://github.com/dotnet/aspnetcore-tooling/commit/584aafdd321c34af17171806d9aff30b71b62b4c but the actual mistake here was introduced in my codeAction PR from way back. We named that function `tryApplyingCodeActions` but if you try calling it on an edit which doesn't apply it throws rather than returning undefined as one would expect.
=> Handle missing edits

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DefaultTagHelperCompletionService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultTagHelperCompletionServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/MarkupTransitionCompletionItemProviderTest.cs
Removed to avoid issues like:
- `<button @attrib|` press `=` -> `<button @attributes="=|"`
- `@onkey|` press `:` -> `@onkeydown=":|"`
- Taghelper attribute `<form ap-anti` press ` ` -> `<form asp-antiforgery=" |"`
- Taghelper attribute `<form ap-ar` press `=` -> `<form asp-area="=|"`
As discussed here: https://github.com/dotnet/aspnetcore/issues/22150
There's nothing in the LSP spec which allows different [CompletionItem.InsertText](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.languageserver.protocol.completionitem.inserttext?view=visualstudiosdk-2019#Microsoft_VisualStudio_LanguageServer_Protocol_CompletionItem_InsertText) snippets for different commit characters. However, for the commit characters `:` and `=`, we need snippet texts of `:|` and `="|"` respectively. …
=> Removes attribute snippet support

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlSmartIndentFormatOnTypeProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormatOnTypeProviderTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlSmartIndentFormatOnTypeProviderTest.cs
- I utilized an `OnTypeFormattingProvider` specifically for newlines to handle translating tags into better formatted segments after entering a newline.
- Moved some indentation generation methods onto `FormattingContext` so they could be usable from outside of the formatting service.
- Added tests to validate HTML/TagHelper scenarios.
dotnet/aspnetcore#22119
=> Add smart indenting support for HTML + TagHelper scenarios.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs
Fix is fairly straightforward after identifying the underlying issue:
Without trimming trailling `/` from the workspace directory, the FileSystemWatcher returns with paths of the form
- "workspaceDirectory/\\Pages\\Counter.razor"
which are normalized to
- "workspaceDirectory//Pages/Counter.razor" (Invalid `//`)
This format doesn't match the directoryFilePaths we store as part of the Project Snapshot ->
- "workspaceDirectory/Pages/Counter.razor"
https://github.com/dotnet/aspnetcore-tooling/blob/488cf6e/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs#L328
Consequently files are being discarded into the MISC project and subsequently re-generated
Discovered while investigating: https://github.com/dotnet/aspnetcore/issues/21631
This issue is …
=> FileSystemWatcher Discarding Files to MISC Project

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageClientMiddleLayer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DocumentHighlightHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/GoToDefinitionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnTypeFormattingHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageClientMiddleLayerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentHighlightHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/GoToDefinitionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/OnTypeFormattingHandlerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/22257
I know this wasn't part of the plan for this release but this seemed simple enough and it looks a lot nicer with this.
=> Support C# highlights in Razor VS LSP

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultFileSystemWatcher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileSystemWatcher.cs
Previous PR was reverted due to suspected flakiness. Fears don't seem to be substantiated given repeated successful CI retries here.
Also added/consolidated the `FileSystemWatcher` across this project to use a new `DefaultFileSystemWatcher` which just trims the last `/` `\`.
Fixes: https://github.com/dotnet/aspnetcore/issues/22280
=> Trimming workspaceDirectory final directory separator

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/language-configuration.json
- Created a VS specific `langauge-configuration.json` file because the way we make smart indent work in a VS world is different from VSCode.
For HTML elements we have two aspects to smart indent behavior:
1. [Pre-existing to this PR] We have an `OnTypeFormatter` that understands newlines being entered in the document and applies indentation + extra newline edits to turn
```HTML
<strong>|</strong>
```
into
```HTML
<strong>
|
</strong>
```
2. [Done in this PR] We add a `langauge-configuration.json` to indicate if a user hits enter in the already `OnTypeFormatted` HTML that you stay in the correct location. Aka:
```HTML
<strong>
|
</strong>
```
After hitting enter
```HTML
<strong>
|
</strong>
```
Now for Razor constructs (`@{}`, `@code {}`) & C# there's two parts to the smart indent behavior …
=> Add HTML & Curly brace smart indent.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/LSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorMapToDocumentRangeParams.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RenameHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConventions.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPDocumentMappingProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentHighlightHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/RenameHandlerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/22377
Also updated LSPMappingProvider to support remapping `WorkspaceEdit`. This will also support remapping `Location[]` in the future (@TanayParikh, this is what you'll be doing for FAR).
=> Support rename from Razor files in VS LSP

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/HostEventStream.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/TelemetryReporter.ts
omnisharp-vscode is adding a new EventType for reporting errors. Updated the report error code to use the new TelemetryErrorEvents.
Addresses https://github.com/dotnet/aspnetcore/issues/21247
=> Use the TelemetryErrorEvent when reporting errors.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/FindAllReferencesHandlerTest.cs
FAR Implementation for Razor -> Razor and Razor -> C#. 
Created [this](https://github.com/dotnet/aspnetcore/issues/22436) for `IProgress<T>` support.
Fixes: https://github.com/dotnet/aspnetcore/issues/22003
=> Find all references from C# inside of a Razor file into & outside of a Razor file

src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyBindingRedirects.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- When we migrated from project references to package references for the Razor compiler dlls stopped being published as part of our VSIX insertion. Previously when using project references the VSIXSourceItem + binding redirect auto-generation was inferred.
=> Fix VSIX insertion binaries.

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
- Prior to this the feature flag was only defined in the VS repo. With these changes we override the default impl in the VS repo and expose it when our extension is available.
- Updated the preview pane channels to include every channel. This doesn't get us into the "release" channels as that's controlled by a whitelist but it does get us into every non-release channel.
- Note: How this mechanism of adding a feature flag works is that `[$RootKey$\FeatureFlags\` is the pre-requisite to identify that our extension is contributing a feature flag and then
Part of dotnet/aspnetcore#22522. The other part will involve whitelisting our feature flag for release channels and removing the VS repo feature flag.
=> Transition Razor experimental editor feature flag to extension.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs
- The language server platform is properly implementing solution close understanding for local language servers and I found that when testing their bits some pieces would explode gloriously. Turns out shutdown and exit support just wasn't fully enabled yet.
Reaction to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1127327
/cc @alexgav @ToddGrun @jimmylewis for your contained language story.
=> Add support for Shutdown/Exit target methods.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPDocumentMappingProviderTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/22677
Looks like I broke it as part of batching mapping requests change. The core issue was that I was checking if each of the Razor documents are tracked by the `LSPDocumentManager` and was discarding that file if it isn't tracked. The problem is that `LSPDocumentManger` wouldn't know about closed Razor files. As a side effect, we lose the outdated version check. But it isn't a big deal imo. On the plus side, `DefaultLSPDocumentMappingProvider` now looks cleaner.
=> Fixed broken LSP mapping for closed Razor files

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
Based on https://github.com/dotnet/aspnetcore-tooling/pull/1847 & https://github.com/dotnet/aspnetcore-tooling/pull/1852 / https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/245745
Copying over from [PR](https://github.com/dotnet/aspnetcore-tooling/pull/1852):
We need `[` and `]` to be commit characters to make extent calculations happen correctly on VS Client side. Having them as trigger characters work but it is not the correct fix.
This shouldn't affect HTML completions because the HTML language server provides CommitCharacters on individual `CompletionItem`s which overrrides what is set in AllCommitCharacters.
Fixes: https://github.com/dotnet/aspnetcore/issues/22455
Fixes: https://github.com/dotnet/aspnetcore/issues/22752
=> Fix `[ ]`, `{ }`, `!` brackets removed when committing completions

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ExtendableServerCapabilities.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRegistrationExtension.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RegistrationExtensionResult.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ExtendableServerCapabilitiesTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormatOnTypeProviderTestBase.cs
- With the onset of VS specific capabilities that do not follow the common LSP spec for extending server capabilities (they don't use the "Experimental" object) we had to build infrastructure to expand the default server capabilities that we push down to the client.
- Added an `IRegistrationExtension`  that a `IJsonRpcHandler` is expected to implement (parallels the existing `IRegistration<>` type). It exposes a new `GetRegistration` method that allows the handler to return a server capability key and value.
- Added wire-up logic to the `RazorLanguageServer` initialization flow to extract all `IRegistrationExtension`s and query all of their registration's and corresponding server capabilities to populate a new `ExtendableServerCapabilities` object.
- Added tests to verify that the new …
=> Add infrastructure for adding VS specific capabilities.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultRemoteTextLoaderFactory.cs
Essentially the same thing as our `FileNotFoundException` handling, however here we also have to fabricate the directory tree.
Fixes https://github.com/dotnet/aspnetcore/issues/22795
=> Safely handle DirectoryNotFound

src/Razor/src/Microsoft.VisualStudio.RazorExtension/language-configuration.json
- Updated our regex to only apply our HTML indentation recognition to HTML tags that are "mostly" on their own line. I say "mostly" because we'll still indent cases where two HTML tags are on the same line but we'll only indent them once.
- Given this is validating smart indent in Visual Studio I was unable to write tests for this case.
Fixes dotnet/aspnetcore#22748
=> Fix smart-indent for C# generics.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorRenameProvider.ts
I already created a release/vscode-16.7-preview3 branch, this is the merge back into master for it.
- Given that O# doesn't support "prepareRename" we have to utilize platform APIs in order to resolve the appropriate rename range.
=> Fix prepareRename to properly return a word range.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
This call is very slow and shows up in the webtools razor typing perf test. There is an existing issue logged against the feature flags implementation, but it is prioritized low and guidance is to add your own cache around calls to it if you don't neeed them to respond to changes in the value.
Fixes https://github.com/dotnet/aspnetcore/issues/21704
=> Cache result from call to IVsFeatureFlags.IsFeatureEnabled

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/Microsoft.AspNetCore.Razor.Performance.csproj, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/SourceTextDifferBenchmark.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DiffEdit.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SourceTextDiffer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/TextDiffer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedDocumentPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SourceTextDifferTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/21407
- Implemented the linear space variation of [Myer's diff algorithm](http://www.xmailserver.org/diff2.pdf). I found [this blog](https://blog.robertelder.org/diff-algorithm/) super useful to help understand the paper. This algorithm runs in linear time and is especially good for typing scenarios because, the fewer the differences in the text, the faster it runs.
- The algorithm is fully contained in `TextDiffer`. `SourceTextDiffer` implements that class and provides both character-wise and line-wise diffing functionality. I had this separation because we might likely use this for formatting in the future.
- Added tests
- Added benchmarks. Here is the benchmark results for MSN.cshtml (~3000 lines and ~350000 characters),
```
Method | …
```
=> Publish only minimal changes from the Razor language server to the client

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/22886
=> Added Directive [SPACE] Commit Character

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/CSharp/CSharpProjectedDocument.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Html/HtmlProjectedDocument.ts
https://github.com/dotnet/aspnetcore/issues/21407 exposed a bug with how we apply edits to the CSharp buffer in VSCode client.
=> Correctly apply CSharp/Html buffer edits in VSCode

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/FindAllReferencesHandlerTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/23065
Previously, for FAR queries initiated from razor, we only showed results from that razor file and other .cs files. Now showing results from all razor & .cs files.
=> C# FAR From Razor to External C# Show All Results

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultProjectSnapshotManagerAccessor.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetectorManager.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/AutoFlushingNerdbankStream.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileChangeDetectorManagerTest.cs
- The general feeling of these changesets is that we weren't disposing things properly and therefore relying on processes exit to tear down our state. To account for this we now implement `IDisposable` on several of our types to allow for them to cleanup state when the server is shutdown.
- Found that disposing the language server doesn't actually dispose of its service provider collection so I had to manually dispose of that collection to ensure all of our services `Dispose` method was invoked on server exit.
- Added `Stop` methods to the `IFileChangeDetector` APIs in an effort to follow a common pattern of start/stop and have the management class (`RazorFileChangeDetectorManager`) control when to start/stop. Otherwise we'd need to have overtly complex logic in each of the …
=> Fix Razor language server leaking memory on solution close/reopen.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorProjectChangePublisher.cs
- Found that our TagHelper/Project information harvester that serializes that info into files was reacting to every document change and serializing project.razor.json information. This seemed to be unexpected even from an implementation perspective because the tests also did not test that one variation (document changed) @ryanbrandenburg if you could confirm this last sentence I'd appreciate it 😄 .
Fixes dotnet/aspnetcore#23169
=> Stop publishing project information on every doc change.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
- TagHelper attributes would result in a null-ref exception at deserialization time because there are some Razor directives without commit characters. In the case that there were no commit characters (null) we'd create a collection with a `null` inner collection. When O#'s output handler then tried to serialize that collection it'd explode and would abort it's output publishing loop resulting in all LSP functionality ceasing.
- Added a serialization test to cover this case.
Fixes dotnet/aspnetcore#23174
=> Fix directive completion serialization.

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileChangeDetectorTest.cs
- Extending the timeout of this test to see if there's an unexpected case actually preventing this test from failing or if the CI machines are just truly dragging their feet.
=> Extend test timeout to rule-out variants of flakiness.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/Rules/RazorGenerateWithTargetPath.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs
One potential side-effect I noticed in testing was when a user typed `@|`, by subsequently pressing the `{` key, a user would expect `@{ ... }` block, however would get the `@code` / `@functions` / `@section` committed **_iff_** it was the (first) highlighted completion.
Before:
After:
Fixes: https://github.com/dotnet/aspnetcore/issues/23311
=> Commit Directive Code Blocks with `{`

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- When the aspnetcore-tooling repo had its compiler binaries migrated over to aspnetcore we had to move from project references to `<VSIXSourceItem>` inclusions. The unknown problem at the time with doing that happened to be that project references automatically get turned into VSIXSourceItem's that should be ngen'd where as manually specifying the items would not result in that.
- Could not add tests for this because ngening is validated at the integration level. Therefore, to 100% validate that this resolves our ngen issues we'll need to inspect perf logs at VS insertion time.
Fixes dotnet/aspnetcore#23314
=> Ngen Razor compiler binaries.

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.clientenabledpkg, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
- There must have been a change in the SDK that started generating/overriding the client enabled filename based off of the source.extension.vsixmanifest. Because we didn't list the custom pkgdef in the source.extension.vsixmanifest the SDK would override our manual one with an entry that only had the single `Microsoft.VisualStudio.RazorExtension.pkgdef` entry. Since our grammar pieces were listed in the custom pkgdef this resulted in Codespaces scenarios not providing TextMate colorization.
- Removed hardcoded clientenabledpkg since it's auto-generated.
Colorization portion of dotnet/aspnetcore#23482
=> Mark RazorExtension.Custom.pkgdef as client compliant.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorDropHandlerProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs
- Prior to this dragging a Razor file from the solution would result in the solution closing and prompting an error dialog:
- This does not resolve dragging a file from outside of the IDE. That's tracked in https://github.com/dotnet/aspnetcore/issues/23501. Once that's fixed we can revert this commit entirely because this fix is more of a workaroudn to temporarily enable the solution dragging scenario.
- Given this is at the scenario integration levels I didn't write tests.
Fixes dotnet/aspnetcore#23494
=> Fix drag from sln closing active solution.

src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DefaultProjectChangePublisher.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorProjectChangePublisher.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestProjectSnapshot.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/DefaultProjectChangePublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/OmniSharpTestBase.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorProjectChangePublisherTest.cs
Edit: Sorry for lack of original description, it was a busy day.
SO, we're seeing a race condition where when you open up a VS solution with a document that's pre-opened that document might not be colorized. We determined that that's because we delete the project.razor.json file when we close VS, so when we re-open and ask for Semantic's the project.razor.json probably hasn't been opened yet and even more likely doesn't have any TagHelpers/Components in it, so we don't report and Semantic Tokens, and VS doesn't know to ask for them again until an edit is made. By not deleting the project.razor.json and not publishing updates to it until the project state is loaded we greatly reduce the chance that things "aren't ready". It's not a guarantee (we've talked before about how it's hard to know …
=> Don't update project.razor.json for unprepared projects

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProgressListenerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/FindAllReferencesHandlerTest.cs
- Issue was with using [`List.Add`](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProgressListenerTest.cs#L208-L210) which isn't thread safe. Updated to using `ConcurrentBag` and repeated test run 100 times to ensure issue was resolved.
- Updated tests in FARHandler to increase resilience (defensive)
- Increased default timeout from 3.5 secs used in PROD to 30 secs for CI
- Implemented the same `ConcurrentBag` fix for the large batches tests to remove reliance on `Task.Delay` which may not work well in the CI.
Fixes: https://github.com/dotnet/aspnetcore/issues/23523
=> Updated Progress Tests for Reliability

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/SemanticTokensLegend.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/22893.
Once https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/257320 merges we'll be able to move back to the old more descriptive token types.
=> Use custom semantic token types

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/LSPDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/SimpleTextChange.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/TrackingLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/VirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/VisualStudioTextChange.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/TextChangeExtensions.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test.Common/TestDocumentManager.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultLSPDocumentManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultLSPDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/LSPDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentTest.cs
This removes mixing of Roslyn and VS Platform text change APIs in common contained language code.
=> Remove references to Roslyn TextChange type in contained language code

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionResolutionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/ExtractToCodeBehindCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/ExtractToCodeBehindCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/ExtractToCodeBehindParams.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/RazorCodeActionContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/RazorCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/RazorCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRazorCodeActionResolutionHandler.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorCodeActionResolutionParams.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorCodeActionResolutionResponse.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/CodeActions/RazorCodeActionRunner.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RPC/CodeActionResolutionRequest.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RPC/CodeActionResolutionResponse.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RPC/SerializableCreateDocument.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RPC/SerializableDeleteDocument.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RPC/SerializableRenameDocument.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RPC/SerializableTextDocumentEdit.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RPC/SerializableWorkspaceEdit.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionResolutionEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/ExtractToCodeBehindCodeActionProviderTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/ExtractToCodeBehindCodeActionResolverTest.cs
In order to support code action efficiently, this PR's main purpose is to integrate an additional dispatcher into the RZLS framework. Additionally, it contains a 'plugin' of sorts to this framework that handles extracting `@code` blocks from `.razor` files into backing C#. 
**I merged with master preemptively to double check compatibility, so please ignore diffs from that**.
This PR registers two endpoints with the RZLS. The first is the `CodeActionEndpoint`, which is a part of the O# specifications. This endpoint asks all of its registered providers (right now there is only one for ExtractToCodeBehind, but in general they are dynamically registered as `RazorCodeActionProvider` services) if they have any code actions to provide. All providers that apply return a command for …
=> Introduce Extract to Code Behind

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPRazorProjectHost.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/LSPRazorProjectHostTest.cs
Reverts the revert: https://github.com/dotnet/aspnetcore-tooling/pull/1940
Did validations on LSP Local + LSP Liveshare + Local Codespaces
Fixes: https://github.com/dotnet/aspnetcore/issues/22331
=> Bring Back Preboot Language Servers

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- The reason why this was happening was because the LSP platform would essentially do a "FirstOrDefault()" on all of our language servers when re-invoking custom messages. Because of that behavior there were occasions when the HTML CSharp language server would be selected to resolve the `razor/languageQuery` endpoint (it can't resolve that) resulting in all C#/HTML experiences failing.
Fixes dotnet/aspnetcore#23782
=> Add a Razor language server client priority to ensure rzls is prioritized for custom messages.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IMonitorProjectConfigurationFilePathHandler.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MonitorProjectConfigurationFilePathEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MonitorProjectConfigurationFilePathParams.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/MonitorProjectConfigurationFilePathParams.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MonitorProjectConfigurationFilePathEndpointTest.cs
- Added a `MonitorProjectConfigurationFilePathEndpoint` that can be called at any time to track an external directory for a project.razor.json. Therefore to account for this I've tried to account for every variation of concurrent requests flowing through it while simultaneously attempting to lock as infrequently as possible (only on dispose).
- One interesting aspect of the endpoint is that if a request comes in and tries to monitor a configuration file path that's within the workspace directory we no-op. The reason being we don't want to be doubly deserializign the `project.razor.json's` in that directory + don't want to be reparsing every file known when they change twice over.
- When a "monitor" request comes in we track the provided configuration file path for the project and when it …
=> Add ability to monitor project.razor.json's outside of workspace directory.

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/VirtualDocumentFactoryBase.cs
- Turns out this marker is understood by LiveShare in order to ensure that virtual documents are not serialized to disk.
Fixes dotnet/aspnetcore#23974
=>  Re-add ContainedLanguageMarker to virtual documents.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/ProvisionalCompletionOrchestrator.ts, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorLanguageEndpointTest.cs
- Ajay and I found that when working on the edge of Razor metacode aka `@{if (true) { } |}` our language queries would return C# as the language being operated on. The root cause of this issue is that our edge handling was a little too naive, we were restricting edge handling to only special variants of non-marker spans. That's still true after this change but we've expanded the accepted left-hand-side ownership of edge scenarios to include whitespace sensitive content (typically implicit expressions).
- Because of the new edge handling we stopped allowing the left-hand side to default to owning the edge. For the EOF case I had to special case that in our language query to ensure that at the end of the document users still get the IntelliSense they expect.
- This is an experimental …
=> Make Razor edge handling more strict.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionParams.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CreateComponentCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/ExtractToCodeBehindCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/AddUsingsCodeActionResolverTest.cs
This is the second PR in the series outlined by [PR 2195](https://github.com/dotnet/aspnetcore-tooling/pull/2195). It introduces another `CodeActionResolver`, `AddUsingsCodeActionResolver`, which adds any number of using statements to a given Razor file in a context-sensitive manner. The heuristic is as follows:
- If no `@using`, `@namespace`, or `@page` directives are present, insert the statements at the top of the file in alphabetical order
- If a `@namespace` or `@page` are present, the statements are inserted after the last line-wise in alphabetical order
- If `@using` directives are present and alphabetized with `System` directives at the top, the statements will be placed in the correct locations according to that ordering
- Otherwise it's kinda undefined; it's only geared to …
=> Implement and register AddUsingsCodeActionResolver and add tests

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/ClassifiedTextElementComparer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/ClassifiedTextRunComparer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/FindAllReferencesHandlerTest.cs
Fixes code behind leaking through:
Note; we had to accomodate ClassifiedTextElement(s) along with normal string text for the reference content.
I've updated https://github.com/dotnet/aspnetcore/issues/22512 to include reverting this change once that issue is fixed.
Fixes: https://github.com/dotnet/aspnetcore/issues/24073
=> Interim Fix for FAR Code Behind Leaking Through

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Serialization/JsonReaderExtensions.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Serialization/RazorConfigurationJsonConverter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Serialization/RazorConfigurationSerializationTest.cs
MVC 1.1 has a different razor configuration format (order of fields + language version structure). We must add support for that format.
```json
{
"ConfigurationName": "MVC-3.0",
"LanguageVersion": "3.0",
"Extensions": [
{
"ExtensionName": "MVC-3.0"
}
]
}
{
"ConfigurationName": "MVC-2.1",
"LanguageVersion": "2.1",
"Extensions": [
{
"ExtensionName": "MVC-2.1"
}
]
}
{
"ConfigurationName": "MVC-1.1",
"Extensions": [
{
"ExtensionName": "MVC-1.1"
}
],
"LanguageVersion": {
"Major": 1,
"Minor": 1
}
}
```
Fixes: https://github.com/dotnet/aspnetcore/issues/24178
Thanks @ToddGrun!
=> Razor Config Serialization MVC 1.1 Support

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MemoryCache.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MemoryCacheTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPEditorFeatureDetectorTest.cs
Using internal memory cache instead of `Microsoft.Extensions.Caching.Memory`.
Worked with @ryanbrandenburg to rework and generalize our memory cache implementation. Thanks!
Fixes: dotnet/aspnetcore#24033
=> ProjectSupportsLSP Internal Memory Cache Implementation

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/ProvisionalCompletionOrchestrator.ts, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/LSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorLanguageEndpointTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPDocumentMappingProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProjectionProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPRequestInvokerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/24261 
Also For: https://github.com/dotnet/aspnetcore/issues/24292
This PR contains,
- Removal of `SynchronizedRequestAsync` to prevent deadlocks in go to definition requests. This was necessary now because LSP platform changed the way `RequestAsync` behaves under the covers which meant that we can't use `SynchronizedRequestAsync` anymore.
- a revert of https://github.com/dotnet/aspnetcore-tooling/pull/2228 which was causing completions inside `@(|)` to not work
=> Fix 16.8 Preview 1 regressions

src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DefaultProjectChangePublisher.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/DefaultProjectChangePublisherTest.cs
- Bring over VS' publish locks to ensure file reading/writing doesn't happen concurrently.
- Moved to `File.Move` from `FileInfo.MoveTo` because Mono's implementation of `FileInfo.MoveTo` caches the file system state when the object is created (file doesn't exist) so calling `MoveTo` can result in a `FileNotFoundException` if they cache too early/late.
Fixes dotnet/aspnetcore#24251
=> Update O#'s project.razor.json TagHelper/concurrent fault tolerance (copy from our VS impl).

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorComponentSearchEngine.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorComponentSearchEngine.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorComponentSearchEngineTest.cs
This pull request implements a rudimentary component search service. The scope is fairly limited; the search only looks through the provided project and makes several assumptions (documented in code) about what it's looking for. However, our goal is to provide this service with as few false positives as possible rather than catch every case.
=> Implement naive per-project component search

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentManager.ts
Fixes https://github.com/dotnet/aspnetcore/issues/24354
- The C# buffer content was being reset because we were creating the same Razor document twice. Once because of vscode's open document API and the second time due to the workspace file watcher.
- This caused a race between our first update and the second creation.
- The fix was to not create another document if we have already created it once. I am unsure what is causing this to happen only now because our code has always been this way. @NTaylorMullen's theory is because we recently made things faster on our side causing this race to be exposed. 
- Verified the fix manually. Couldn't add tests because it involves vscode APIs but the fix is fairly simple.
=> Don't create document in VSCode if it already exists

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentManager.ts
Follow up to https://github.com/dotnet/aspnetcore-tooling/pull/2282
Need to insert into the release branch which has the previously inserted head.
=> Don't create document in VSCode if it already exists (#2282)

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorComponentSearchEngine.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RazorComponentRenameEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorRenameProvider.ts, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorComponentSearchEngineTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RazorComponentRenameEndpointTest.cs
This pull request is ugly as hell but there are a couple cases where I'm just not sure how to make it better. Have a couple ideas that I'd appreciate feedback on in addition to general review:
- Should I add an overload to `TryLocateComponentAsync` that takes a list of projects to look through to reduce the number of times we need to be on the foreground (currently we get the project list twice, once to find the origin component and once to iterate through all document paths)
- I found duplicate files naively iterating through project -> documents. Is my `HashSet` approach reasonable?
- Should I be `await`ing multiple promises to be more efficient here? Does it matter?
- Does anyone have any ideas on how to reduce boilerplate to access the `RazorCodeDocument` of a `DocumentSnapshot` from …
=> Tweak component search and implement component rename

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPRazorProjectHost.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPRequestInvokerTest.cs
We're getting ready to remove the 'C#_LSP' content type in https://github.com/dotnet/roslyn/pull/46370
This PR switches the razor LSP to look for the c# lsp server on the 'CSharp' content type instead of the 'C#_LSP' content type.
This change requires #46370 plus another liveshare PR and *should not be merged* until we are ready to do a triple insertion, but I wanted to get all PRs created and approved first.
Addresses https://github.com/dotnet/aspnetcore/issues/19184
cc @NTaylorMullen
=> Switch from 'C#_LSP' to 'CSharp' content type for C# lsp server

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LSPRazorProjectHost.cs
This takes a change from https://github.com/dotnet/aspnetcore-tooling/pull/2291 separately from the C#_LSP removal to include the DisableUserExperience attribute during pre-activation.  
Without this, the liveshare LSP server in roslyn will start providing diagnostics locally, see https://github.com/dotnet/roslyn/issues/45966
I am taking this change separately as I'm not exactly sure when C#_LSP will go in - some issues with roslyn insertions + triple insertion may delay.
Addresses https://github.com/dotnet/roslyn/issues/45966
=> Include DisableUserExperience attribute when pre-activating LSP servers

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/HoverHandler.cs
Supports the VSHover type from roslyn LSP server to include classified raw content.
I have in-progress changes that will change roslyn to return VSHover w/out markup content and instead pass the classified text in RawContent (https://github.com/dotnet/roslyn/pull/46576).  Once https://devdiv.visualstudio.com/DevDiv/_workitems/edit/918138 is resolved, we'll switch back to regular LSP.
This works if we specify either.
=> Support VSHover for colorized csharp hover

src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/DefaultLSPEditorFeatureDetector.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/MacLSPEditorFeatureDetector.cs
- Turns out the two VS4Mac issues which we had reported were already fixed in the latest master.
- Attempting to upgrade to the latest Razor tooling bits resulted in a MEF failure for our LSP editor feature detector dependency that was introduced at the CodeAnalysis.Razor.Workspaces layer. To resolve this I went ahead and added a VS4Mac specific LSP feature detector that always returns false.
- Could not add tests for this because it's more at the integration layer.
Fixes dotnet/aspnetcore#23745
Fixes dotnet/aspnetcore#23746
=> Fix VS4Mac component discovery issues through upgrade.

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj, src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/README.md
- Updated the RazorAddin project to include some dependent assemblies to ensure when running locally they can be found/loaded. In non-local built scenarios these are automatically included by the mpack.
- Added a README.md on how to debug VS4Mac.
=> Enable VS4Mac inner-loop debugging.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CodeBlockDirectiveFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContentValidationPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingResult.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingSpan.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingStructureValidationPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/IFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/IndentationContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RangeExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SourceTextExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/TextLineExtensions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnTypeFormattingHandler.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/RazorOnAutoInsertProviderTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/DefaultRazorFormattingServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingEndpointTest.cs
Part of https://github.com/dotnet/aspnetcore/issues/23419
- Implemented a new pass based design for regular and ontype formatting
- Added the ability to re-parse the document in FormattingContext
- Updated FormattingVisitor and IndentationContext to have more information about each line
- Added the core logic for C# onTypeFormatting
- Added a `FormattingContentValidatorPass` to ensure the integrity of the document before returning formatting edits
Working on:
- Adding another pass that rejects formatting edits if we format C# blocks with mixed HTML
- Tests for everything
=> Support C# onTypeFormatting in Razor LSP (Part 2)

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/TestLanguageServiceBroker.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/23191
This got unblocked by the fact that we no longer use the [`SynchronizedRequestAsync`](https://github.com/dotnet/aspnetcore-tooling/blob/4ddccd8e65312f3520f4c109c4a94ce81db37c66/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs#L49-L58)  method.
=> Remove Reflection from Default LSP Request Invoker

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CodeBlockDirectiveFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingStructureValidationPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorSyntaxTreeExtensions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CSharpStatementBlockOnTypeFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingStructureValidationPassTest.cs
Part of https://github.com/dotnet/aspnetcore/issues/23530
Opening the floodgates for more pure C# ontypeformatting
=> Enable onTypeFormatting for pure C# @{...} statement blocks

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorDocumentMappingServiceTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/24296
Investigated, discussed offline and closing out.
Essentially this stricter handling seems to be primarily needed for the `OnTypeFormatting` case, and there are some additional nuances with a stricter interpretation (ex. breaks down for `@(Da|)` case as it thinks we're in Razor instead of C#). 
Just adding in some additional tests which validate these situations.
=> Edge Handling Test Cases

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/DefaultFeedbackFileLogWriter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/DefaultFeedbackFileLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/DefaultFeedbackLogDirectoryProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLogWriter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLogger.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLoggerProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackLogDirectoryProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Feedback/FeedbackFileLoggerProviderTest.cs
- Expanded our RazorLanguageServer implementation to allow hosts to configure services.
- In VS hosted scenarios we now register a new `ILoggerProvider` that logs out to the users `%temp%/RazorVSFeedbackLogs/pid` directory. Each VS instance has its own folder but on VS boot we cross-check all pre-existing folders and cleanup any folders that no longer correspond to an active VS process. We accomplish this by querying for all `devenv` processes and then cross-checking their pid's against the folder names we've created.
- Underlying VS' `ILoggerProvider` is a FileLogWriter that accepts writes synchronously for N number of providers. Behind the scenes it synchronously writes all of its contents to disk.
- This is a pre-requisite PR for actually providing feedback information as part of a …
=> Log language server output to files (also)

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/MemoryCache.cs
This is an attempt to resolve some intermittent failures with the memory cache, likely caused by a concurrency issue between remove and add.
https://dev.azure.com/dnceng/public/_build/results?buildId=763979&view=ms.vss-test-web.build-test-results-tab&runId=23736232&resultId=100008&paneView=debug
Thanks @ryanbrandenburg!
=> Resolve flaky tests with memory cache

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/DefaultFeedbackLogDirectoryProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackLogDirectoryProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/RazorFeedbackDiagnosticFileProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj
- Added a new `RazorFeedbackDiagnosticFileProvider` that serves as the entry point for the VS "report feedback" tool. This is called whenever a user attempts to report feedback and it does the work in order to zip up all of our appropriate logs and feed them to the underlying VS feedback system.
- This isn't enough on its own we need to separately go through an approval process with the feedback team in order to get our log uploads "approved".
- Untestable given it's all file/integration driven.
Fixes dotnet/aspnetcore#24129.2
=> Zip and provide Razor logs during VS feedback flow.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServerBuilder.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/DefaultFeedbackFileLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLogger.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLoggerProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- MEF was auto-loading some additional dependencies because our FeedbackLoggerProviderFactory's signature had an ILogger impl. Changed the return type to `object` to workaround this
- Static's were resulting in some dependency injection/logging assemblies being loaded too eagerly.
- NOTE: This is a best bet at fixing a perf regression. May need to work more at it later. Couldn't reproduce easily sadly.
=> Remove loadpoints for Microsoft.Extensions.*

README.md, activate.ps1, docs/contributing/BuildFromSource.md, startvs.cmd
@ryanbrandenburg pointed out my change from `. .\activate.ps1` to `.\activate.ps1` in the build from source PR README. I've been using `.\activate.ps1` and haven't run into any particular issues, however, it's not the recommended way to source due to [scoping](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_scripts#script-scope-and-dot-sourcing). dotnet/aspnetcore enforces this dot sourcing, so I copied over the script changes here.
Also noticed startvs.cmd had changed so brought that over as well.
Thanks @ryanbrandenburg!
=> Update Scripts from ASP.NET Core

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts
We're adding a query parameter that will be set/unset if the Blazor WASM application is under debug.
This flag will determine whether or not the Mono runtime optimizes execution for debugging or performance.
The flag defaults to true for backwards-compatibility but we'll need to set it to false to disable debugging overhead and improve app performance. This change only affects apps built in Development mode.
This PR should be merged after https://github.com/dotnet/aspnetcore/pull/24972.
Addresses https://github.com/dotnet/aspnetcore/issues/24623
=>  Set noDebug flag on launch url for Blazor WASM apps

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs
- Things are faster now, when we tear down the parser whether it be due to a TagHelper refresh or the solution is tearing down it's possible that our internal parser is `null`. To protect against this I just allowed for it to be `null` and to essentially no-op in these scenarios.
Fixes https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1153369
/cc @ToddGrun
=> Fix NullReferenceException race in existing editor.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RazorComponentRenameEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RazorComponentRenameEndpointTest.cs
- We were passing in the wrong document snapshot for generating the new path.
- Added a test that validates the correct behavior.
Fixes dotnet/aspnetcore#25018
=> Fix renaming a component that exists in a different directory.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorSpanMappingService.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorSpanMappingServiceTest.cs
- To enable Roslyn to allow C# rename for closed Razor files we need to be providing `TextSpans` with appropriate mappings
- Updated tests to account for new mapping information.
Fixes dotnet/aspnetcore#25113
=> Start mapping TextSpans in our pre-existing RazorSpanMappingService.

src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyCodeBases.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
- This is required at ngen time and now that WTE has removed their Microsoft.Extensions.Primtivies codebase entry VS can't load this dependency at ngen time and I assume runtime?
=> Add Microsoft.Extensions.Primitives to extension

src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
- Without this creating the VS hive can fail because VS doesn't know how to properly re-construct it.
=> Add LanguageServer protocol assemblies to VSIX manifest.

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/TestLanguageServiceBroker.cs
- The core portion of this change is the update from ClientImplementation 16.7.33 -> 16.7.65 to ensure that our other language server dependencies were coherent with the Client.Implementation dependency. To ensure this I removed those references from Versions.props and their correpsonding referenced projects.
- Had to pin a few dependencies to ensure things could build without warning.
=> Update dependencies to be coherent with latest VS.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/AutoFlushingNerdbankStream.cs
- O# doesn't try/catch around their reading/writing flow so if our reading/writing throws it will crash VS. This is properly solved in the latest O# but for now to mitigate VS issues we're going to swallow all exceptions introduced by our stream wrapper. This may effectively corrupt the Razor scenario and leak memory but it helps mitigate the crashes until we can land the proper fix.
Fixes dotnet/aspnetcore#25116
=> Prevent VS crashes when O# fails to properly read/write to JsonRpc streams.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/AutoFlushingNerdbankStream.cs
- O# doesn't try/catch around their reading/writing flow so if our reading/writing throws it will crash VS. This is properly solved in the latest O# but for now to mitigate VS issues we're going to swallow all exceptions introduced by our stream wrapper. This may effectively corrupt the Razor scenario and leak memory but it helps mitigate the crashes until we can land the proper fix.
=> Port fix to 16.8-preview2: Prevent VS crashes when O# fails to properly read/write to JsonRpc streams.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/ComponentAccessibilityCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/ExtractToCodeBehindCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/RazorCodeActionContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LSPEditorFeatureDetector.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VSLanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/MacLSPEditorFeatureDetector.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/ComponentAccessibilityCodeActionProviderTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/ExtractToCodeBehindCodeActionProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPEditorFeatureDetectorTest.cs
- Disables `Create Component` & `Extract to CodeBehind` for liveshare host/guest + codespaces.
Fixes: https://github.com/dotnet/aspnetcore/issues/25128
Created https://github.com/dotnet/aspnetcore/issues/25333 to track revert.
=> Disable File Operation Based CodeActions in Liveshare/Codespaces

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TagHelperDescriptorCache.cs
- Given the sheer amount of TagHelperDescriptor compact crashes we've seen it looks like users are fully utilizing the cache we had in place. Given the current 1500 entries results in ~3MB of overhead I think it's fair to expand that to ~9MB to ease in larger project development. People love their TagHelpers!
- This is being done with the assumption the users hitting these cache compaction cases are in fact using larger projects; however, there is another case where they just leave VS open for significant periods of time and are navigating among loads of different solutions (less likely but possible).
=> Increase TagHelperDescriptorCache size.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
- Updated HTML & C# completion trigger characters to accurately represent C# & HTML trigger characters. This basically involved going to both the C# and HTML language servers and pulling their trigger characters.
- Updated completion handling to rewrite the completion context if we determine that we should be invoking completion but the corresponding trigger character shouldn't be passed along to the sub-language server. For instance, when we type `@` we should be asking the C# language server for completions but we don't want to be passing the `@` character as a trigger character to C#'s language server because they didn't register for that; instead we now rewrite those completion contexts to be "invoked" completions instead of "triggered" completions.
- Updated completion tests to …
=> Reconfigure HTML & C# completion triggers.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- Prior to this change we would unintentionally initialize O# on the main thread  which would pin its input handler reading loop to the main thread. Meaning it'd "while true" but only ever read data on the main thread. To workaround this we now initialize O# on a random threadpool thread. Separately I've commited a fix to O# to fix their input handling logic (configure await false).
O# fix: https://github.com/OmniSharp/csharp-language-server-protocol/pull/354/files
Fixes dotnet/aspnetcore#25738
=> Initialize O# on a threadpool thread to prevent deadlocks

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormattingPass.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestFiles/HtmlFormattingTest/FormatsMixedHtmlBlock.input.html, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestFiles/HtmlFormattingTest/FormatsMixedHtmlBlock.output.html, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestFiles/HtmlFormattingTest/FormatsRazorHtmlBlock.input.html, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestFiles/HtmlFormattingTest/FormatsRazorHtmlBlock.output.html, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestFiles/HtmlFormattingTest/FormatsSimpleHtmlTag.input.html, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestFiles/HtmlFormattingTest/FormatsSimpleHtmlTag.output.html
This change fixes a few bugs,
1. More than 3 levels of nesting causes extra indentation.
- This was because `AdjustCSharpIndentation` method touched non-csharp lines
2. Our understanding of HTML structure of the document overrides what the real HTML formatter does. This is visible with `<html>` tag formatting.
- The temporary fix for this is to special case `<html>` tag formatting on our side
3. Accessing some properties on `FormattingContext` null-refs if there is a 0 length line in the document (We just happened to not use these properties in places where this would've thrown. We go lucky so far. The fix for bug 1 exposed this)
Added tests
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1198948/
=> Fix nested html indentation and other bugs

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DirectiveAttributeTransitionCompletionItemProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SyntaxNodeExtensions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DirectiveAttributeTransitionCompletionItemProviderTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
- Disabled pre-select for the `@...` completion item to ensure that when a user types `/` that completion is dismissed (if it's pre-selected it doesn't dismiss).
- Given that `/` is another completion character completion is re-invoked upon typing `/` allowing us to recompute valid completion items. Updated the logic that provided the `@...` completion item to not allow providing completions at `<input /|`. To do this I added a general extension method that will probably be used more frequently to detect if a node contains only whitespace.
- Updated existing tests to reflect the new "pre-select" option being false.
- Added a new test to validate the scenario when a user is typing out the closing tag of an HTML element.
**Before:**
**After:**
Fixes dotnet/aspnetcore#24895
=> Prevent @ from being inserted when closing a self-closing tag.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts
Reverts dotnet/aspnetcore-tooling#2393.
We're pausing on implementing this change because:
- we discovered that the perf impact of running an app in debugging is within the accepted range when in development
- we want to land something for all editors in .NET 6/VS 16.9
=> Revert " Set noDebug flag on launch url for Blazor WASM apps"

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/ComponentAccessibilityCodeActionProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/ComponentAccessibilityCodeActionProviderTest.cs
- LSP Platform doesn't currently support previews for `WorkspaceEdit.Changes`. Transitioned to `WorkspaceEdit.DocumentChanges` to ensure we get code action previews.
Fixes: https://github.com/dotnet/aspnetcore/issues/25894
=> Support Previews for Edit Based Code Actions

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/LSPRequestInvoker.cs
This allows users of the DefaultLSPRequestInvoker to filter based on server capabilies
=> Expose the language service brokers capabilitiesTokenFilter

.gitignore, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
- Malformed FQN component was due to two separate workspace edits overwriting values. Updated to use a single workspace edit, with multiple text edits. Not sure why this issue wasn't materializing in earlier testing 🤔.
- Unit tests: Wouldn't have caught this issue as the difference occurs in how LSP platform interprets the order of edits.
Fixes: https://github.com/dotnet/aspnetcore/issues/25969
=> Fix Malformed FQN Component Code Action

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionResolutionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/IRazorCodeActionHandler.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/IRazorCodeActionResolveHandler.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/ExtendedCodeActionContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/RazorCodeActionParams.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/RazorCodeActionContext.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/ComponentAccessibilityCodeActionProviderTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/ExtractToCodeBehindCodeActionProviderTest.cs
Issue was due to some recent changes in LSP platform where they now give a `CodeActionParams.Range` which reflects the start of the line, instead of at the start of the area we want to act on. They still provide the "old"  selection range in `CodeActionParams.Context.SelectionRange`. Updated our logic to consume that instead if it's available.
Confirmed functionality in VS + VSCode & added tests.
Thanks @NTaylorMullen!
Fixes: https://github.com/dotnet/aspnetcore/issues/25964
=> Fix CTRL+. Not Invoking Code Actions

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RazorComponentRenameEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RazorComponentRenameEndpointTest.cs
- Prior to this when renaming a component it would only ever successfully rename a non-fully qualified component. Now we understand that a rename operation can occur on a fully qualified component and translate the appropriate edits. Also, we used to never translate edits onto associated fully qualified components. Now we do the needful.
- Added a test to cover the fully qualified scenario.
Fixes dotnet/aspnetcore#25021
=> Fix component rename for fully qualified components.

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultFileUriProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPDocumentManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/FileUriProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorContentTypeChangeListener.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorContentTypeChangeListenerTest.cs
- Our current way of initializing the Razor world was powered by TextBuffer content type changes. For most cases this was an accurate way to detect when documents were created/torn down; however, in the case that a user renames a document that happens to be opened to a file name that has the same content type we we weren't notified. Meaning we'd try and lookup C#/HTML documents and we'd fail to find them because we'd still think the buffer was associated with the old name.
- Updated our `RazorContentTypeChangeListener` to attach to `ITextDocument` `FileActionOccurred` events to properly track/untrack our documents.
- Found that our current way of "untracking" a buffer would result in the buffers Uri state bleeding into future renames. To address this I expanded the FileUriProvider to have …
=> Properly track/untrack doc state when files get renamed while open.

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- OmniSharp updated their package to include a fix for a VS infinite hang for peek definition & light bulb invocation. This PR just consumes the new package and removes our workaround.
=> Upgrade O# and remove workaround for hang.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultProjectSnapshotManagerTest.cs
- I found that in VisualStudio when you rename a document our system detects that a new file gets added and reacts by "opening" said document. Now the problem with this approach is that our project snapshot manager would notify consumers of a "DocumentChanged" event for a file that hadn't been notified as "added" yet. To account for this I added a notification work queue to the project snapshot manager and unwind all notifications after an initial notification has been notified.
- Added a test for this case.
Part of dotnet/aspnetcore#25045
=> Properly handle snapshot manager changes that get nested.

azure-pipelines.yml, eng/Publishing.props
- see https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Publishing.md#how-to-upgrade-from-v2-to-v3
- also remove post-build validations now done in the Validate-DotNet pipeline
nits:
- do not set post-build parameters to their defaults
- remove incorrect comments and ancient workarounds from Publishing.props
=> Use V3 publishing infrastructure

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPDocumentMappingProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/TestLanguageServiceBroker.cs
Need to update those to get them in sync with what other language server (e.g. TypeScript and Web Tools) are using. Without that, JSON deserialization doesn't work correctly. E.g. VSHover doesn't get deserialized as VSHover but as just Hover instead.
=> Updating LanguageServer.Protocol assemblies

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RazorComponentRenameEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RazorComponentRenameEndpointTest.cs
Currently `F2` anywhere on a component start tag (ex. even component parameter) will trigger the rename window. We want to only show this window when a rename is triggered for the component name itself. This requires LSP platform to support [`textDocument/prepareRename`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_prepareRename). I've created a [VSTS issue here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1222641). In the meantime, these changes ensure a rename operation on anywhere but the start of the component tag no-op.
Fixes: https://github.com/dotnet/aspnetcore/issues/26165
Issue for `textDocument/prepareRename` tracking: https://github.com/dotnet/aspnetcore/issues/26407
=> No-op Component Parameter Renames

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs
This switches Razor to html-delegation language server which supports CSS and JavaScript in HTML. I did a quick sanity test, and I'm not seeing any major blockers.
=> Enable script and style block support

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotManagerBase.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorProjectChangePublisher.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorProjectChangePublisherTest.cs
- When a solution has been opened, delay any sort of project state serialization/understanding until a Razor file has been opened. This way we aren't doing extra work for solutions/project scenarios that don't care about Razor.
- Added tests to validate the active and non-active states of the project change publisher.
Fixes dotnet/aspnetcore#26164
=> Make project state serialization lazy.

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/IntegrationTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorBaselineIntegrationTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/Legacy/ParserTestBase.cs
- Fixes the randomized test flakyness from formatting, when all tests are run together (does not repro on individual / debug)
ex.
```
CloseCurly_Method_MultiLine
Source: CodeDirectiveOnTypeFormattingTest.cs line 66
Duration: 27 ms
Message: 
Assert.Equal() Failure
↓ (pos 13)
Expected: @code {\r\n    public void Foo\r\n    {\r\n    }\r\n}\r\n
Actual:   @code {\r\n            public void Foo\r\n            {\r\n ···
↑ (pos 13)
Stack Trace: 
FormattingTestBase.RunOnTypeFormattingTestAsync(String input, String expected, String triggerCharacter, Int32 tabSize, Boolean insertSpaces, String fileKind) line 115
CodeDirectiveOnTypeFormattingTest.CloseCurly_Method_MultiLine() line 68
--- End of stack trace from previous location ---
CodeBlockDirective_WithTabSize8
Source: …
```
=> Fix IntializeTestFile Test Flakyness

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextViewConnectionListener.cs
- VS relies on there being an `IVsTextViewFilter` associated with an `ITextView` in order for "hover" support to fallback to identifier evaluation when debugging. To fix this sub-piece of the Blazor WASM debugging gap with the new LSP editor we listen for ITextView creation events and attach a dummy text view filter to enable the debugging hover support.
Fixes dotnet/aspnetcore#26196
=> Enable debugging hover support in Blazor WASM scenarios.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- When we updated O# the way logging was wired up changed. Because of this if the user didn't have verbose logging enabled they would not publish information when "Report a problem..." in Visual Studio was clicked.
- Changed how we setup logging in our language server. Instead of relying on the "ConfigureLogging" extensions that O# exposes we add the logging directly to the services collection. This way we can expand on the default logging registrations mechanisms.
Fixes dotnet/aspnetcore#26699
=> Fix VSFeedback logger writing logs.

src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Host/DefaultProjectSnapshotManagerProxy.cs
- The reason we explode is that we try to convert certain types which may be null and don't properly handle the null case. In practice this typically presents itself in Codespaces scenarios when moving from an open folder LiveShare scenario to a project loaded scenario. LiveShare launches all host/guest services at which point we notify those services that projects are being added (since we're in the midst of opening a solution) at which point the "old" project is null because it didn't exist in the open folder scenario.
Fixes dotnet/aspnetcore#26702
=> Handle `null` project handles appropriately in our LS proxy.

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundParser.cs
- Somehow calling `.Reset` still gets triggered after disposal. To prevent VS from crashing swallow any exception caused by resetting.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1177023
=> Swallow exceptions caused from resetting manual reset events.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/DefaultRazorHoverInfoService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs
- When hovering over a trailing edge of a minimized attribute there was no value right hand side to pad each attribute. Because of this our hover logic would always expect there to be only one valid attribute at the hover location; however, at edges this wasn't true.
- Added a test to account for the new scenario.
Fixes dotnet/aspnetcore#26747
=> Fix trailing edge hover queries for minimized attributes.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingLanguageServerClient.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestFiles/HtmlFormattingTest/FormatsComplexBlock.input.html, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestFiles/HtmlFormattingTest/FormatsComplexBlock.output.html
Part of https://github.com/dotnet/aspnetcore/issues/26527
Contains a bunch of cleanups and fixes the issue where formatting was behaving differently in VS vs tests. This was because we were not generating line pragmas in tests.
=> Fix formatting test infrastructure

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextViewConnectionListener.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageService`IVsLangaugeInfo.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs
- A language service in Visual Studio enables a language to fully control the end-to-end experience. This serves as a pre-requisite to the debugging work we're doing to enable Blazor WebAssembly breakpoints to properly bind in the new LSP editor. That functionality is hooked up via a language service hook.
- Setup the initial language service to be "simple" meaning it notifies everyone listening that things are not implemented so the editor falls back to default implementations. This means this language service as it exists in this changeset effectively does nothing. However, because we're going to be adding to this I've made the language service a partial class because expansions of VS language services are done via additional interfaces on the same type; making it a partial class will …
=> Add a Razor LSP language service for our buffers.

eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/ImplementInterfaceAbstractClassCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionResolutionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/RazorCodeAction.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentContainerStore.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultHostDocumentFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorConfigurationService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectFileChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLSPOptionsMonitor.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorServerReadyPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RazorComponentRenameEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/RazorSemanticTokensEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticTokensEditsDiffer.cs, src/Razor/src/rzls/Program.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionResolutionEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorComponentSearchEngineTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorConfigurationServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Microsoft.AspNetCore.Razor.LanguageServer.Test.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationStateSynchronizerTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/26476
- The fix here is to make our config parsing logic handle cases when the same option name is used in multiple sections. See test for example.
- Upgraded O# version to address the didChangeHandler not getting called issue
- All other changes here are to fix analyzer warnings in the language server
~Will send a separate PR to fully fix https://github.com/dotnet/aspnetcore/issues/26476 which will essentially be a O# version upgrade~
=> Fix VSCode config parsing in Razor language server

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Dialogs/DefaultWaitDialogContext.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Dialogs/DefaultWaitDialogFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Dialogs/WaitDialogContext.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Dialogs/WaitDialogFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Dialogs/WaitDialogResult.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.ruleset, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageService`IVsLanguageDebugInfo.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Dialogs/DefaultWaitDialogFactoryTest.cs
- Added a `IVsLanguageDebugInfo` extension to our language service. This interface will be used when attempting to set breakpoints for any file that has our language service. In our case, that's only RazorLSP files.
- Added a generic wait dialog utility for us to use when we can't possibly go async due to call paths being enforced as synchronous.
- Implemented the skeleton of `ValidateBreakpointLocation` to show how the wait dialog factory will be used. Because the API is synchronous the wait dialog is essential to ensure we can run asynchronous work but also simultaneously allow users to "stop" that async work.
- Added tests for our wait dialog wrapper.
Part of dotnet/aspnetcore#26643
=> Add initial VS debugging shims / integrations.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/GoToDefinitionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/GoToImplementationHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RenameHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/SignatureHelpHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/FindAllReferencesHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/GoToDefinitionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/GoToImplementationHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/RenameHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/SignatureHelpHandlerTest.cs
- This sounds more impressive then it really is. Basically we no longer restrict our handlers to only delegate for C#.
- Expanded some of the pre-existing handler logic to better handle "null" cases where sub-language servers can't handle requests and consequently return `null`.
- Sprinkled some more cancellation token throw if cancellation requested.
- Updated pre-existing tests for the handlers to properly expect delegation for HTML projections.
**Note:** In practice this looks to only light up go-to-def/signature help for JS/CSS. Once things are implemented on the web tools side I imagine things will just "light up"
Fixes dotnet/aspnetcore#26950
/cc @alexgav
=> Add support for FAR, def, impl, rename and signature help for HTML.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/CSharpBreakpointResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultCSharpBreakpointResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorBreakpointResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/RazorBreakpointResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Dialogs/DefaultWaitDialogFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Dialogs/WaitDialogResult.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/ITextSnapshotExtensions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageService`IVsLanguageDebugInfo.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorBreakpointResolverTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorLanguageService`IVsLanguageDebugInfoTest.cs
- This changeset enables breakpoints to be set on C# code that's not obfuscated by other Razor paradigms. For instance, implicit expressions cannot have breakpoints set on them with this changeset because `__o = DateTime.Now` is the entirety of the breakpoint but the user can only see `@DateTime.Now`.
- Had to add a C# breakpoint resolver because the breakpoint APIs provided by C# are internal only. I will do a follow up PR to Roslyn in order to properly expose the breakpoint information APIs via ExternalAccess.Razor
- Added some cleanup to the existing wait dialog factory types from the previous changeset.
- Added tests for both the Razor breakpoint resolver and the language service extension usage.
Part of dotnet/aspnetcore#26643
=> Add set/hit breakpoint support for some Razor C#.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MappingBehavior.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorMapToDocumentRangesParams.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/LSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorMapToDocumentRangesParams.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/LanguageServerMappingBehavior.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorDocumentMappingServiceTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorBreakpointResolverTest.cs
- Added a `MappingBehavior` concept to our language servers ability to map projected ranges. Currently there's only two types, `Strict` and `Inclusive`. Their meaning:
```
Inclusive mapping behavior will attempt to map overlapping or intersecting generated ranges with a provided projection range.
Behavior:
- Overlaps > 1 generated range = No mapping
- Intersects > 1 generated range = No mapping
- Overlaps 1 generated range = Will reduce the provided range down to the generated range.
- Intersects 1 generated range = Will use the generated ranges mapping
```
- Added tests to validate our `MapFromProjectedDocumentRange` API for the pre-existing "Strict" type mappings (for some reason we didn't have tests for that) and the new "Inclusive" mappings.
- Updated our `LSPDocumentMappingProvider` …
=> Add breakpoint set support for implicit expressions and TagHelper/Component attributes.

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundParser.cs
- This was the result of a high number of crashes in VS and given we're moving away from the pre-existing tech try-catching was a sufficient, low cost alternative to crashing VS.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1177023
=> Defend against disposed exceptions when waiting for parcels.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/RazorSemanticTokensEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
I noticed one instance where we weren't handling all cases for this, so we should be more careful so we don't yellow-bar anyone.
Fixes https://github.com/dotnet/aspnetcore/issues/27100.
=> Handle Razor visitor more carefully

eng/Versions.props, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/TestLanguageServiceBroker.cs
This will allow us to consume the OnTypeRename support.
=> Update VSLanguageServerClient reference to be in lockstep with WTE

Directory.Build.props, Directory.Build.targets
- dotnet/aspnetcore#18930
- also remove leftover NU5048 suppression; Arcade adds the icon for us
=> Add `[AssemblyMetadata("Serviceable", "true")]` to all assemblies

eng/Version.Details.xml, eng/Versions.props
Use the testing package from aspnetcore now that it's migrated and the package is produced from there.
=> Consume Microsoft.AspNetCore.Testing from aspnetcore

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectWorkspaceStateGenerator.cs
- Only allow a single TagHelper resolver request to process at a time in order to reduce Visual Studio memory pressure. Typically a TagHelper resolution result can be upwards of 10mb+. So if we now do multiple requests to resolve TagHelpers simultaneously it results in only a single one executing at a time so that we don't have N number of requests in flight with these 10mb payloads waiting to be processed. For larger projects this was found to occasionally contribute to over a GB worth of memory occupying VS' 4gb memory limit.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1236296
=> Reduce VS memory pressure for large projects

NuGet.config
- hopefully not needed anymore
- also switch from deprecated dotnet-core feed to dotnet-tools
=> [release/3.1] Remove Roslyn and vs-editor MyGet feeds

Directory.Build.targets
- cherry-pick 60cc307de88b from master
- dotnet/aspnetcore#18930
=> [release/3.1] Add `[AssemblyMetadata("Serviceable", "true")]` to all assemblies (#2696)

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DocumentPullDiagnosticsHandler.cs
- Remove `IProgress<T>`
- Filter out `unused using` diagnostics 
- Helps with `_Imports.razor`
- Regular unused usings aren't accurate due to the `<auto-generated>` [issue](https://github.com/dotnet/aspnetcore/issues/26815).
- Ensures we support the case when both C# and Razor clients support pull-diagnostics
=> Remove IProgress from Pull-Diagnostics

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DocumentPullDiagnosticsHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentPullDiagnosticsHandlerTest.cs
Part of: https://github.com/dotnet/aspnetcore/issues/21121
Goal of this PR is to update our return behavior to be in line with what LSP Platform expects from us;
|DiagnosticReport.Diagnostics|DiagnosticReport.ResultId|Meaning|
|---|---|---|
|`null`|`null`|document gone|
|`null`|valid|nothing changed|
|valid (non-null including empty)|valid|diagnostics changed|
Thanks @CyrusNajmabadi for clarifying this behavior!
=> Update Pull Diagnostics Return Logic

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DocumentPullDiagnosticsHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentPullDiagnosticsHandlerTest.cs
- We need to ensure the virtual and razor documents are in sync before we query roslyn for document diagnostics.
- Part of: https://github.com/dotnet/aspnetcore/issues/21121
Fixes: https://github.com/dotnet/aspnetcore/issues/27970
=> Synchronize Documents with LSP Pull Diagnostics

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorMapToDocumentEditsParams.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/TextEditKind.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/LSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnAutoInsertHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnTypeFormattingHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorMapToDocumentEditsParams.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorMapToDocumentRangesParams.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorMapToDocumentRangesResponse.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/TextEditKind.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionResolverTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/DefaultRazorFormattingServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingEndpointTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorBreakpointResolverTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/OnAutoInsertHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/OnTypeFormattingHandlerTest.cs
Part of https://github.com/dotnet/aspnetcore/issues/23753
- Handle edits from onAutoInsert response correctly but flowing it through our formatting pipeline
- Added a `TextEditKind` enum to help customize that behavior
- Added support for collapsing multiple edits into one in the formatting service
- Added/updated tests
=> Format edits from onAutoInsert response

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnAutoInsertHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/OnAutoInsertHandlerTest.cs
Part of https://github.com/dotnet/aspnetcore/issues/23753
The problem is that C# formatting doesn't work when the document looks like,
=> Workaround to support curly-brace OnAutoInsert

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/RazorSemanticTokensEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Semantic/ProvideSemanticTokensResponse.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Semantic/SemanticTokensHandler.ts, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/28130.
I noticed this because of the null-ref that `RazorSemanticTokensEndpoint` throws in this case.
The `result.Data` field from VSCode is being serialized as null (even though I made it return an empty array specifically to avoid this), which causes the Razor LSP to throw out the whole request (it thinks that the reason it's null is the DocumentVersions were out of sync).
=> Semantic null vs code

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/Constants.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/TerminateDebugHandler.ts
- Adds support for passing underlying config to JS and .NET debuggers
- Allows users to customize the hosted .NET debugger more fully
- Allows users to configure prelaunch tasks for standalone server (for example, launching a local Azure Functions app)
- Always launch .NET app using debugger to support passing custom config
- Update  clean up logic to check for standalone server launch from .NET debugger
- Update config name for app launched via .NET debugger
Fixes: https://github.com/dotnet/aspnetcore/issues/27518, https://github.com/OmniSharp/omnisharp-vscode/issues/4161, https://github.com/OmniSharp/omnisharp-vscode/issues/4108
=> Enhance support for configuring debuggers used for Blazor WASM apps

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
- When the VS language server platform's Json converters are added to our JsonRpc object we're able to see additional information as part of LSP completion requests. This additional information can help influence our sub-languages to "do the right thing".
- To add JsonConverters to our JsonRpc object I had to change the way we construct the object. Also, since we can't rely on a newer LSP protocol version quite yet I had to copy and paste their converter additions into one of our own.
- Updated two existing tests to validate that the `InvokeKind` flows properly.
/cc @allisonchou @ToddGrun 
Fixes dotnet/aspnetcore#27927
=> Delegate InvokeKind to sub-languages.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorMapToDocumentRangesResponse.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorMapToDocumentRangesResponse.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorHtmlPublishDiagnosticsInterceptor.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConventions.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentHighlightHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs
- Fixes RazorMapToDocumentRangesResponse null response support
- Previously this resulted in an exception being thrown and the message being lost
- Updated Razor LSP Conventions (added .razor and .cshtml support)
- Added Razor HTML publish diagnostics
- Note; this still needs to be flushed out (primarily filtering): https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1257401
- Tests are WIP: Will be part of https://github.com/dotnet/aspnetcore/issues/27563
Fixes: https://github.com/dotnet/aspnetcore/issues/26830
=> HTML Embedded Language Publish Diagnostics, Fix RazorMapToDocumentRangesResponse

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
- The language server platform restricts the bounding of the "applicable commit span" based on the active trigger/commit characters. Since `_` is already part of our "identifier" trigger set we don't need to specify it.
Before:
After:
Fixes dotnet/aspnetcore#28578
=> Fix underscores from being duplicated when completions committed.

NuGet.config, eng/Versions.props, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/Microsoft.AspNetCore.Razor.Performance.csproj, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/BackgroundDocumentGenerator.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpWorkspaceProjectStateChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DefaultProjectChangePublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DocumentChangedSynchronizationService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectManager.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/TagHelperRefreshTrigger.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultDocumentSnapshot.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultImportDocumentSnapshot.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentSnapshot.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Microsoft.VisualStudio.Editor.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorBreakpointResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/OOPTagHelperResolver.cs, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/Microsoft.VisualStudio.Mac.LanguageServices.Razor.csproj, src/Razor/test/Directory.Build.props, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test.csproj, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common.csproj, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DefaultDocumentSnapshotTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Microsoft.VisualStudio.LanguageServices.Razor.Test.csproj
- This is a pre-requisite to adopting Roslyn's new OOP model. Because the changes were quite noisy I'm breaking them apart from the actual code change.
- Roslyn update is to get new OOP requirements added by Razor
- ASP.NET Core update is to get the new IVT pieces from Razor.Language
- Roslyn brought in a new StreamJsonRpc version which was sufficient for our usage. Therefore removed all of our direct pinning and now only rely on the transitive dependency.
- Roslyn brought in a new Visual Studio Threading dependency. Had to update a lottt of our code to abide by the new Visual Studio threading analyzers. Also the latest dependency was sufficient so removed our pinning of it.
Part of dotnet/aspnetcore#24476
=> Update ASP.NET Core & Roslyn dependencies.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticRange.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TagHelperResolver.cs
Firstly I try to improve the message that is presented if the SemanticRange debug assert is thrown (since I still am not able to make it happen and would like to confirm my theory that it's caused by C# and Razor tokens coliding when document versions are out of sync).
Secondly I resolve a problem of StackOverflowExceptions thrown by GetTagHelpersAsync because it calls itself. It's unclear to me how this wasn't causing trouble for other people.
=> Improve messages and prevent StackOverflow

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultTagHelperServiceTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/27109.
We can't colorize portions of the tree that we don't visit, I thought I had caught everything in my previous pass but apparently things remain to be found.
Before and after in the issue.
Also fixes https://github.com/dotnet/aspnetcore/issues/27136 by semantically coloring the braces in these case.
There was no explicit reference to these items so I took advantage of the fact that no other RazorMetaCode (as far as I can find) should get Visited.
=> Fix SemanticToken Visitor

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionResolver.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/AddUsingsCodeActionResolverTest.cs
- Added `using` to the `formattingContext` to avoid undisposed warning
- Added `PageDirective` (in addition to `ComponentPageDirective`)
- This is mainly for the `mvc` case where the `ComponentPageDirective` isn't recognized
Fixes: https://github.com/dotnet/aspnetcore/issues/27453
=> Fix Add Using Code Action with @page Directive

src/Razor/test/Microsoft.AspNetCore.Razor.Test.ComponentShim/Microsoft.AspNetCore.Razor.Test.ComponentShim.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.ClassLib/Microsoft.AspNetCore.Razor.Test.MvcShim.ClassLib.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version1_X/Microsoft.AspNetCore.Razor.Test.MvcShim.Version1_X.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version2_X/Microsoft.AspNetCore.Razor.Test.MvcShim.Version2_X.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim/Microsoft.AspNetCore.Razor.Test.MvcShim.csproj
These warnings annoy my VS Error list because they're totally un-actionable in shim projects.
=> Ignore API Warnings in test shims

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorDocumentMappingServiceTest.cs
- End of document didn't have an associated classified span. We now apply the last classified span when asked to determine the language of the end of the document.
-  Further discussion in the issue https://github.com/dotnet/aspnetcore/issues/23907
[note; ignore the colorization, local issue]
Fixes: https://github.com/dotnet/aspnetcore/issues/23907
=> Fix Component End-Tag Completion At End of Document

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/CompletionListSerializationBenchmark.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/CompletionItemExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/CompletionListCache.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/CompletionListCacheTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
- We now only send completion item documentation when a completion item is resolved.
- To accomplish this we now cache our Razor completion lists between responses and hold up to 3 in memory at a time. When a completion resolve request comes in we'll cross-check the completion item with our completion list cache and if we can find it we'll resolve/calculate the documentation information for that completion item.
- Expanded our pre-existing RazorCompletionEndpointTest's to encompass the new functionality
- Added separate CompletionListCache tests.
Baseline:
|                                              Method |      Mean |     Error |    StdDev |   Op/s |     Gen 0 |     Gen 1 |    Gen 2 | Allocated |
|---------------------------------------------------- …
=> Don't send documentation in completion list responses.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/DefaultFeedbackFileLogWriter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/DefaultFeedbackFileLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLoggerProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLoggerProviderFactoryBase.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/HTMLCSharpLanguageServerFeedbackFileLoggerProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/HTMLCSharpLanguageServerFeedbackFileLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/RazorLanguageServerFeedbackFileLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DocumentPullDiagnosticsHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorHtmlPublishDiagnosticsInterceptor.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsEndpointTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentPullDiagnosticsHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorHtmlPublishDiagnosticsInterceptorTest.cs
- Logging for
- DocumentPullDiagnosticsHandler
- RazorDiagnosticsEndpoint
- RazorHtmlPublishDiagnosticsInterceptor
- Updated VS HTMLC# Language Server to support logging via feedback file logger
- Updated DefaultFeedbackFileLoggerProviderFactory.cs to share the log writer
```
09:17.710 | [DocumentPullDiagnosticsHandler] Requesting document pull diagnostics for file:///C:/Users/taparik/dev/blazorserver2/Pages/Counter.razor.g.cs with previous result Id of DocumentPullDiagnosticHandler:0.
...
09:23.837 | [DocumentPullDiagnosticsHandler] Received 1 diagnostic reports.
09:23.840 | [DocumentPullDiagnosticsHandler] Requesting processing of 12 diagnostics.
...
09:23.857 | [RazorDiagnosticsEndpoint] Received CSharp diagnostic request for file:///C:/Users/taparik/dev/blazorserver2/Pages/Counter.razo …
```
=> E2E Logging For C# Pull Based Diagnostics & HTML Interceptor

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectWorkspaceStateGenerator.cs, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/OOPTagHelperResolver.cs
- Currently this exception is treated like any other exception and results in an activity log entry. Swallow this exception to not create any noise.
=> Swallow task cancelled exceptions when resolving TagHelpers.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticRange.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/29203.
Since the SemanticTokens spec has changed to (depending on your options) allow overlapping tokens I'm modifying this so that we handle that case instead of `Debug.Assert`'ing.
=> Support overlapping Semantic tokens

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/CSharpProximityExpressionResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultCSharpProximityExpressionResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorProximityExpressionResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/RazorProximityExpressionResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/VsEnumBSTR.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageService`IVsLanguageDebugInfo.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorBreakpointResolverTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorProximityExpressionResolverTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorLanguageService`IVsLanguageDebugInfoTest.cs, src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/RazorGuestInitializationServiceTest.cs
- Added a proximity expression resolver abstraction to Razor that takes a buffer and a location then does the magic to lookup the corresponding Razor document, determine if the location is C# and pass all the information needed over to C# to resolve expressions at that location.
- Had to utilize private reflection to invoke the CSharp proximity expression resolver APIs. Need to follow up and add these APIs to Roslyn's external access Razor layer so we can utilize them.
- Expanded our `RazorLanguageServiceIVsLanguageDebugInfo` to glue together the proximity expression resolution code so that the autos window shows up.
- Autos window now shows however there's a quirk where the JavaScript type information is used for C# items. This is a separate issue that we'll need to address
- Added tests …
=> Add support Blazor WASM debugging Auto window.

.editorconfig
This is just a personal annoyance for me, I like my Error list to be empty when at all possible and these tend to be low-value fixes.
If other contributors have strong preferences feel free to object.
=> Disable If expression suggestion

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsEndpointTest.cs
- Once we determine an HTML diagnostic is within a markup attribute, we check if that markup attribute also contains C#. If it does, we disable all diagnostics within that markup attribute (and cache the results).
- ~~TODO: testing once the approach is cleared.~~
Fixes: https://github.com/dotnet/aspnetcore/issues/29079
=> Filter Diagnostics Within Attributes Containing C#

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
- Found a few misconfigurations of our initialize result.
- Missing the \` HTML trigger character
- Signature Help was entirely missing its re-trigger characters in addition to a angle bracket trigger character
- Had to purposefully not validate some trigger character pieces that were purposefully left out like the HTML `_` trigger character
- The gist of this change is that when you run our experimental instance we'll do these validation checks to ensure that all of our sub-language servers capabilities are accurately represented in our delegated HTMLC# language server.
Fixes dotnet/aspnetcore#25737
=> Add capability check verification during Debug time.

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/MemoryCacheBenchmark.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/MemoryCache.cs
- Added a benchmark to validate the performance gains
- As the amount of elements gets larger in the cache the gains get significantly higher too because of how the old "OrderBy" & "ElementAt" calls work. Aka, every ElementAt call would re-calculate the entirety of the OrderBy.
Before:
|                                          Method |     Mean |    Error |   StdDev |  Op/s |     Gen 0 |    Gen 1 | Gen 2 | Allocated |
|------------------------------------------------ |---------:|---------:|---------:|------:|----------:|---------:|------:|----------:|
| 'MemoryCache Set performance with limited size' | 17.47 ms | 0.137 ms | 0.114 ms | 57.23 | 2281.2500 | 156.2500 |     - |  13.78 MB |
After:
|                                          Method |     Mean |    Error |   StdDev |    Op/s | …
=> Fix MemoryCache Compact performance.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/RazorSemanticTokensLegend.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentPullDiagnosticsHandlerTest.cs
- Dug through the code base and there were several easy to remove "ElementAt" cases. Thankfully we didn't have any super crazy performance hitting cases but removed them nevertheless to encourage better usage in the future
- Because IEnumerable's are lazy and uncached you can get into some (O)n^2 scenarios super easily unless you force evaluation of the array you're ElementAting (ToArray).
Fixes dotnet/aspnetcore#29538
=> Remove most usages of "ElementAt".

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
- We were aggressively booting too many language clients that weren't applicable in local scenarios. For instance, one of the language clients was LiveShare's that's only ever applicable on a Liveshare guest and another was IntelliCode. Both of these should never run in Razor scenarios but our act of aggressively booting them resulted in us getting double code actions.
- Had to re-implement a lot of the language client "LoadAsync" filtering logic in order to not boot language clients that were non-applicable.
=> Fix duplicate C# CodeActions in Debug experimental VS instance

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/ITextSnapshotExtensions.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
- Removes Razor design time helpers from C#'s completion list since they will not be applicable.
- If the current identifier being targeted does not start with a double underscore, we trim out all items starting with "__" from the completion list. If the current identifier does start with a double underscore (e.g. "__ab[||]"), we only trim out common design time helpers from the completion list.
Definitely open to adding more items to the "common" design time helpers list. I mainly just used the recommended ones from the original issue.
Fixes: 
https://github.com/dotnet/aspnetcore/issues/25091
=> Remove design time helpers from C# completion list

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
- Removes `_Imports` from the completion list.
- Pretty much just a one-line change. 😄 
Fixes: 
https://github.com/dotnet/aspnetcore/issues/29562
=> Remove _Imports from completion list

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorProjectChangePublisher.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorProjectChangePublisherTest.cs
- Turns out checking if a specific file has the LSP editor available wasn't needed in this location because all we really care about is the fact of if the editor is enabled at all. Also turns out that the editor check was quite expensive in regards to perf because at solution close time every Razor file is removed from the project manager which results in a 1-1 mapping of "IsEditoravailable" checks per file which indirectly requires the need to lookup VS' hierarchy.
Fixes dotnet/aspnetcore#29861
=> Use IsLSPEditorFeatureEnabled instead of the editor variant.

NuGet.config, eng/Versions.props
The myget feeds are no longer active.
Per https://github.com/dotnet/core-eng/wiki/MyGet-Migration-New-Homes, the `rosyln` and `roslyn-tools` feeds can be replaced with the dotnet5, vssdk, vs-impl feeds.
=> Remove deprecated feeds

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProgressListener.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/LSPProgressListener.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/LSPProgressListenerHandlerBase.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProgressListenerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/FindAllReferencesHandlerTest.cs
This change shaves ~6 minutes off the test execution time. It's possible it introduces some flakiness, but that can be addressed separately (and without reintroducing this delay) if it arises.
=> Reduce the timeout for tests

src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/Xunit/ForegroundTheoryAttribute.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
These tests were not running. One test does not pass and has been skipped with a tracking issue.
=> Enable tests marked with ForegroundTheoryAttribute

eng/Versions.props, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common.csproj, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Microsoft.VisualStudio.Editor.Razor.Test.csproj
* Simplify xunit references
* Include standard utilities library Xunit.Combinatorial (from @AArnott)
📝 I use Xunit.Combinatorial for running test iterations to find flaky failures:
```
[Theory, CombinatorialData]
public void Test([CombinatorialRange(0, 100)] int iteration)
{
_ = iteration;
// rest of test goes here
}
```
=> Xunit.Combinatorial

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/CSharpProximityExpressionResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultCSharpProximityExpressionResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorProximityExpressionResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj, src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/Microsoft.CodeAnalysis.Remote.Razor.Test.csproj, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioRazorParserIntegrationTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/29883.
The basic flow here is that we use the `IRazorAsynchronousOperationListenerProviderAccessor` to create an async context which we can later resolve. Then on the DDRIT side we call [IApexAsynchronousOperationListenerProviderAccessor](https://github.com/dotnet/roslyn/blob/c9a68b6a2fed69b1a48505b401dd1bb3d09dc45a/src/Tools/ExternalAccess/Apex/IApexAsynchronousOperationListenerProviderAccessor.cs).WaitAll on the same feature name so see if it's been resolved, and wait if it hasn't.
=> Use a Brokered Service to indicate RazorLSPServerReady

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultFormattingOptionsProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/FormattingOptionsProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveData.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultFormattingOptionsProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionResolveHandlerTest.cs
- At a lower layer this changeset enables text edit remapping at completion item resolve time. We needed to lazily evaluate/remap text edits for C# overrides for multiple reasons:
1. After inserting C# override content we need to ensure the inserted content is properly formatted in the context of a Razor document
2. C# overrides can take a significant amount of time to evaluate so evaluating them after an item is selected enables us to not evaluate "all" of them.
3. Providing & remapping complex C# content in the initial completion request would require additional asynchronous calls to language servers to properly remap/format that content which could slow completion significantly.
- Added a new `DefaultFormattingOptionsProvider` that will lookup an associated LSP document and create …
=> Support remapping C# override completions in Razor documents.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionRequestContext.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionRequestContextCache.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/IsExternalInit.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionRequestContextCacheTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionResolveHandlerTest.cs
- Added a `CompletionRequestContextCache` and instead of storing host document and projected uri's along with language server kinds on completion items we now store them in the cahce to be retrieved at resolve time.
- Updated the languageserver client project to target latest C# lang version to use records!!
- Added IsExternalInit to enable this.
- Added new tests for request context cache.
- Updated existing tests to validate the new behavior.
Part of dotnet/aspnetcore#29619
=> Cache completion item -> request to minimize completion payload.

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs
The test did not reveal unwanted behavior.
Closes dotnet/aspnetcore#27135
=> Add regression test for many-line fluent calls

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/RazorLogHubTraceProvider.cs
Copy of @dibarbet's https://github.com/dotnet/roslyn/pull/51248
Should be temporary until it's handled at the source.
=> Remove default listener from loghub trace source

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs
- Ensures reference results aren't filtered out. `Exact` origin indicates the code is directly accessible.
Fixes: https://github.com/dotnet/aspnetcore/issues/29887
Thanks @AmadeusW!
=> Fix Missing References with Rich Nav

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/TagHelperDescriptorExtensions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperServiceTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/RazorDefinitionEndpointTest.cs
- Support GoToDef on components with attributes
- Support GoToDef on end/closing tags
Fixes: https://github.com/dotnet/aspnetcore/issues/29565
Fixes: https://github.com/dotnet/aspnetcore/issues/30277
=> Support GoToDef on Components with Attributes & Closing Tags

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs
Essentially reverts https://github.com/dotnet/aspnetcore-tooling/pull/2037
Caching now done at the LSP Platform layer: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1128651
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/260509
Did some basic validation in local/liveshare with new/old editors.
Fixes: https://github.com/dotnet/aspnetcore/issues/30303
=> Disable Feature Flag Caching

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/InProcLanguageServerAdapter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProjectionProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/InProcLanguageServerAdapterTest.cs
- StreamJsonRpc has significant overhead when invoking any requests. In practice I've seen timing range from 0-100ms. The purpose of this PR is to remove this overhead from common Razor language interactions (language query, range remapping, edit remapping) that will eventually go away anyways. Now I mention "will eventually go away anyways", this is in reference to a re-design that I am in the midst of writing up. For the interim, this PR actually adds some "not so great" restrictions to our design in an effort to deliver a superior user experience. Some of those are:
- We lose the RPC logging in regards to resolving LSP projections. This shouldn't be an issue once Tanay's LogHub changes have made their way in and we have separate logging.
- We're relying on things being "inproc". In a …
=> Avoid StreamJsonRpc for Razor lang calls.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsEndpointTest.cs
I was seeing `Invalid Expression )` error diagnostic for empty attributes. Examining the generated doc, it's reasonable why C# thinks there's an error, however it doesn't make sense in the Razor context (as RZ2008 already errors for empty attributes).
Razor:
```razor
<p @onabort=""></p>
```
Generated doc:
```csharp
__o = Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.ProgressEventArgs>(this, );
```
Fixes: https://github.com/dotnet/aspnetcore/issues/30480
=> Filter Invalid Expression `)` C# Diagnostic With Empty Attribute

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorBreakpointResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorProximityExpressionResolver.cs
- Added caching logic to our BP & proximity expression resolver to enable us to avoid going async as often. Ultimately this is a workaround to the platform's innability to have an async debugging API.
Fixes dotnet/aspnetcore#30223
=> Cache BPs/Proximity expressions to avoid going async.

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorBreakpointResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorProximityExpressionResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorBreakpointResolverTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorProximityExpressionResolverTest.cs
- I made a mistake and transitioned from the `VisualStudioWorkspace` -> `VisualStudioWorkspaceAccessor` prior to checking in. This hiccup results in VS hanging because the workspace accessor  attempts to lookup project information for a document which requires the UI thread (currently blocked by the debugging APIs).
- Added some test instance APIs to not conflate various tests
Fixes dotnet/aspnetcore#30778
=> Fix UI hang when setting breakpoints in Razor files.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs
- A user reported that while Razor documents were open their CPU would constantly spin. They decided to profile what was happening in VS and part of the profile indicated that Razor was constantly re-parsing on every semantic token edit poll. Found that we were aggressively generating a code document so just moved the code document calculation logic down a few steps to allow our caching layer to cache without re-parse.
Part of https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1286124
=> Lazily parse document in semantic tokens edit.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundDocumentGenerator.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedDocumentPublisherTest.cs
- When adding the logger factory to the `DefaultGeneratedDocumentPublisher` I had no way to acquire the "correct" logger at service construction time because of our previous ways of adding services (we manually constructed singletons). To combat this I modified how we construct multi-typed services (aka a singleton service that can be accessed via two different types) by using singleton factories.
- Updated tests.
Part of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1282452
=> Add more logging for update C# / HTML buffers.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorComponentSearchEngine.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorComponentSearchEngineTest.cs
- Fixed an assumption in the component search engine that didn't allow generic's to flow into proper lookups.
- Added a test to verify generic components can be looked up.
Fixes dotnet/aspnetcore#30989
=> Add support for go-to-def on generic components.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/CSharp/CSharpProjectedDocument.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Html/HtmlProjectedDocument.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RPC/ServerTextSpan.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/tests/CSharpProjectedDocument.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/tests/HtmlProjectedDocument.test.ts
- After updating C# packages in VSCode going cross languages for their `TextSpan` type no longer worked. That was due to [this change](https://github.com/dotnet/roslyn/commit/e91ccb5cff76e826b1efd9e1a598bb4dd1a13986#diff-d7c14d06408992f74fe6b90dbb05737e99a0f492227562cf25e59c0242ba00e4R46). Basically instead of rendering an "end" for TextSpan's they only render start and length and expect the other side to calculate the end. Reasonable but broke our JS impl.
Part of dotnet/aspnetcore#30834
=> Fix C# serialization break in VSCode

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProgressListener.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentPullDiagnosticsHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/TestLanguageServiceBroker.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorHtmlPublishDiagnosticsInterceptorTest.cs
Putting this up to unblock builds. Alternatives for the types made obsolete are under discussion and not yet available.
Revert Issue: https://github.com/dotnet/aspnetcore/issues/31133
=> Suppress Warnings from LSP Platform Changes

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/OpenDocumentGenerator.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Common.Test/BackgroundDocumentGeneratorTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/OpenDocumentGeneratorTest.cs
- This should significantly improve the performance of the LSP experiences. CPU will scale more drastically because instead of re-parsing every file when a document or project changes we'll only parse open documents.
- Added new `OpenDocumentGenerator` tests
Fixes dotnet/aspnetcore#31031
=> LSP: Only background parse open documents

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs
Razor tooling doesn't utilize workspace pull diagnostics as it doesn't really make sense for our use case. Consequently, we don't have a workspace pull diagnostics endpoint. This is resulting in a bunch of unnecessary exceptions being triggered. Purpose of this task is to add in a NOOP handler to mitigate the exception.
Ideally we'd have a server capability to reduce overhead of sending/receiving the request and the associated serialization/deserialization (under discussion).
Fixes: https://github.com/dotnet/aspnetcore/issues/31134
cc/ @dibarbet @veler
=> Add Workspace Diagnostics NOOP Handler

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
- The optimized completion list type offers "fast" serialization (3.7x).
- Updated our CompletionHandler construct to utilize VSCompletionList since that's what the optimized completion list takes.
Part of dotnet/aspnetcore#30232
=> Use OptimizedVSCompletionList in LSP scenarios

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
This reverts commit 88d0a07f3c058a2a5d2a97937fa3ed6bcde767bb.
- Need to revert this until we can move to an LSP platform version that has this change: https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/313368
=> Revert "Use OptimizedVSCompletionList in LSP scenarios (#3320)"

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/ITextSnapshotExtensions.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
- With how provisional completions work (they require two projections) we weren't updating the projection kind to be C# so the completion items that were returned were getting associated with the HTML server kind.
- Added a new test to validate that provisional completion works as expected in a resolveable way.
Fixes dotnet/aspnetcore#31209
=> Add provisional completion -> resolve support.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/AttributeDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/SectionDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/UsingDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Require a space after a directive name for it to be treated as a directive. This way you don't get into circumstances where a user does something like `@section.Name` and it get colored improperly. Did this for `@section`, `@using` and `@attribute`.
- Added tests.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1302527
=> Make directive TextMate more restrictive.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentOutputReferenceCapturer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentOutputReferenceCapturerTest.cs
- Added logic to capture/keep alive the latest document output. I added some logging to see how much of an impact this would have and after typing out `<strong>` you'd result in roughly 6 different Razor parses on the final version of the document because the underlying `DefaultDocumentSnapshot` state held a `WeakReference` to the underlying document output and that `WeakReference` would be collected inbetween all of the requests during that flow. With this change we now only have 1 parsed representation at the end because we keep a reference to the latest open document version's output.
- Added tests to validate the capturing/releasing behavior.
Fixes dotnet/aspnetcore#30953
=> Keep alive latest Razor document parse output.  (6 parses per-character -> 1)

.editorconfig
We use the `Skip` functionality to quarantine flaky tests.
=> Ignore `Test methods should not be skipped` Diagnostic

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorConfigurationService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorConfigurationServiceTest.cs
- @TanayParikh reported seeing the following exception when loading the Razor extension in VSCode:
```
Microsoft.AspNetCore.Razor.LanguageServer.DefaultRazorConfigurationService: Failed to sync client configuration on the server: System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRazorConfigurationService.ExtractVSOptions(JObject[] result, Boolean& insertSpaces, Int32& tabSize) in C:\Users\taparik\dev\aspnetcore-tooling\src\Razor\src\Microsoft.AspNetCore.Razor.LanguageServer\DefaultRazorConfigurationService.cs:line 135
at Microsoft.AspNetCore.Razor.LanguageServer.DefaultRazorConfigurationService.BuildOptions(JObject[] result) in C:\Users\taparik\dev\aspnetcore-tooling\src\Razor\src\Microsoft.AspNetCore.Ra …
```
=> Don't throw exception if null configuration options returned

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultRazorDynamicFileInfoProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultDynamicDocumentContainer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentPublisher.cs
- This addresses the high-hitting semantic tokens issue https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1291116/. It appears the C# server isn't processing the textDocument/didOpen request before Razor is sending a semantic tokens request to the C# server, which is resulting in a Contract failure on the C# side.
- I'm not sure this is the ideal fix but from testing it seems to resolve the problem? @NTaylorMullen please let me know if this wasn't the approach you were thinking of, or if my detailing of the issue isn't correct (this is just what I understand from the meeting yesterday but I definitely could have misunderstood something).
=> Add Razor client name to documents to mitigate race condition with C#

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/TypeAccessibilityCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
- This finishes up the additional items required to support the new code action identifiers in VSCode (wasn't able to test it properly before because of other issues). Note that PR was merged *after* the VSCode insertion was cut so there shouldn't be any issues with the new VSCode release.
- In some scenarios, I'm getting [this](https://github.com/OmniSharp/omnisharp-roslyn/issues/2132) after invoking the code action. As far as I can tell this is a O# issue.
- This is also preventing me for validating Razor add component using / fully qualify component (https://github.com/dotnet/aspnetcore/issues/31608)
=> Fix VSCode Code Actions

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DirectiveAttributeTransitionCompletionItemProvider.cs
- VisualStudio looks at a "soft selected" item and inspects its available commit characters when deciding whether or not to re-trigger completion. If you happen to type a commit character of that soft selected item VS would re-trigger completion. Pre-client refactor Visual Studio didn't differentiate language servers commit characters so when it saw the `@...` item it saw the `AllCommitCharacter` server capabilities for both our Razor and HTMLC# language servers. Because the HTMLC# language server had `@` in its all commit character list the `@...` item would re-trigger completion when you typed `@`. Post-refactor they're smarter and only look at the corresponding language server that provided the completion item, in this case Razor which does not have an `@` as a trigger character.
- …
=> Workaround VS completion soft-selection issue.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultRemoteTextLoaderFactory.cs
- Turns out there's too many things that can go wrong when trying to read dependencies from disk. Latest was a "Resource is not ready" generic IO exception that was crashing VS.
Fixes dotnet/aspnetcore#31724
=> Swallow all IO exceptions when parsing a Razor file.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionProvider.cs
This isn't working in the following case, so removing support for this code action.
Revert tracking issue: https://github.com/dotnet/aspnetcore/issues/31808
=> Remove spell check code action

NuGet.config, eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Documents/VisualStudioFileChangeTrackerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Microsoft.VisualStudio.LanguageServices.Razor.Test.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorProjectHostTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackRazorProjectHostTest.cs
- As part of dev17 a lot of interop packages have been consolidated into single binaries. To react to this we must migrate from the multitude of pre-existing interop assemblies to the new single representation (typically `Microsoft.VisualStudio.Interop`). All VS packages are in the process of updating to latest versions so there are some incoherencies that we had to react to by pinning certain dependencies.
Fixes dotnet/aspnetcore#31165
=> Update to dev17 package sources.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/src/acquireDotnetInstall.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/src/extension.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts
- Pass `arguments` to `dotnet.ensureDotnetDependencies` as list of strings
- Fallback to debugging proxy launched via middleware if extension fails
Fixes: https://github.com/dotnet/aspnetcore/issues/31757
Provides a fallback for https://github.com/dotnet/aspnetcore/issues/31653
=> Fix up Blazor WASM debugging extension

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/VirtualDocumentFactoryBase.cs
Dependency on this marker was added in https://github.com/dotnet/roslyn/pull/52609, updating comment.
=> Update comment on contained language marker to mention roslyn usages

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
- Turned out that our HmtlC# completion handler was null reffing when typing `@` in a directive attribute context because the returned completion list was empty. This in turn resulted in our delegated completion request returning `null` causing our optimized completion list wrapping to throw
- Added a test to cover the scenario
Fixes dotnet/aspnetcore#31984
=> Fix directive attribute completions.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ComponentAccessibilityCodeActionProviderTest.cs
- When typing you end up in scenarios where the document looks like: `<|` a lot. We should not be providing "Create Component from unknown tag" light bulbs in this scenario, there's no value.
- Added a test to validate that we no longer provide a light bulb.
Fixes dotnet/aspnetcore#31977
=> Don't provide "Create Component" light bulb if no tag.

NuGet.config, eng/Versions.props, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks.csproj, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Properties/launchSettings.json, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/readme.md, src/Shared/BenchmarkRunner/Program.cs
- Added the ability to debug benchmarks in-proc.
- Added the ability to run benchmarks in VS.
- Updated README.md on how to run benchmarks in VS.
- Needed to add a feed to the BenchmarkDotNet pre-release feed.
Fixes dotnet/aspnetcore#31941
=> Update Benchmarking infrastructure for net6.0

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultTagHelperCompletionService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/IsExternalInit.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/DefaultTagHelperCompletionServiceTest.cs
- The intent of this change is to improve performance so our payloads are "less"
- Prior to this we'd always provide component completions for every listed component twice over. Meaning, if you had a `<Counter>` you'd get a `Counter` completion and a `MyNamespace.Counter` completion item. Now we remove the fully qualified variants if their non-fully qualified variant is in scope.
- Added a test to validate the new completion behavior.
**Before:**
|                                              Method |      Mean |     Error |    StdDev |   Op/s |    Gen 0 |    Gen 1 |   Gen 2 | Allocated |
|---------------------------------------------------- |----------:|----------:|----------:|-------:|---------:|---------:|--------:|----------:|
| 'Component Completion List Roundtrip Serialization' | …
=> Only provide fully qualified Component completion if unimported.

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/CompletionListSerializationBenchmark.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/OptimizedCompletionList.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/OptimizedVSCompletionList.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/PlatformAgnosticCompletionCapability.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/VSCompletionList.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/VSCompletionListCapability.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/VSCompletionListTest.cs
- `CompletionList.CommitCharacters` serves as a way for completion items to not redundantly provide commit characters. Aka, all completion list commit characters serve as a default for underlying completion items.
- The LSP Platform hasn't yet inserted these changes into VS; however, our language server doesn't depend on the LSP platform directly anyhow. This changeset enables the commit character optimization of the LSP platform in a way that will automatically light up once it becomes available.
- Updated benchmarks to use new CommitCharacters on the completion list.
- Expanded our language server client capabilities to track VS' completion list capabilities that identify whether or not the CommitCharacters. This manifests as `PlatformAgnosticCompletionCapability` and …
=> Add support for CompletionList.CommitCharacters.

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/CompletionListSerializationBenchmark.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/OptimizedCompletionList.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/OptimizedVSCompletionList.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/VSCompletionList.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/VSCompletionListCapability.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/VSCompletionListTest.cs
- `CompletionList.Data` serves as a way for completion items to not redundantly provide `Data`. Aka, all completion data objects serve as a default for underlying completion items.
- The LSP Platform hasn't yet inserted these changes into VS; however, our language server doesn't depend on the LSP platform directly anyhow. This changeset enables the data bag optimization of the LSP platform in a way that will automatically light up once it becomes available.
- Updated benchmarks to use new `Data` capability on the completion list.
- Updated our `VSCompletionListCapability` to include a `Data` property.
- Added tests
**Before:**
|                                              Method |     Mean |     Error |    StdDev |  Op/s |    Gen 0 |    Gen 1 |   Gen 2 | Allocated | …
=> Add support for CompletionList.Data.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorBreakpointResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorProximityExpressionResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageService`IVsLanguageDebugInfo.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorBreakpointResolverTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorProximityExpressionResolverTest.cs
- Found that when you type near a breakpoint in Razor we would request projections from our language srever and wait for the document to be synchronized. Turns out due to VS' debugging tech being synchronous on the UI thread that was an impossible thing to do. Basically as you'd type we're try to synchronize the C# document and continually timeout during synchronization if you were typing. To address this I added a stop-gap where if the C# document is of a different host document sync version then the top level document we let the breakpoint grow on its own. This will result in some unexpected behaviors for customers as their breakpoint highlight may grow unexpectedly but replacing it will fix it or it will just inherently be fixed later when the editor re-verifies breakpoints (running). …
=> Make typing around C# breakpoints in Razor instant.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HandlerTestBase.cs
- Because projections can be requested from soooo many different pieces of the Razor sub-system (debugging being one of them) we need to initialize our logger whenever projections are attempted to be resolved. This may seem expensive but 99.9% of the time the async method will run synchronously resulting in no harm to perf.
Found because this Debug.Assert being hit:
Fixes dotnet/aspnetcore#32088
/cc @TanayParikh would you mind taking a look since this touches on the LogHub infrastructure you added.
=> Fix setting breakpoint on solution load = no logs.

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Microsoft.VisualStudio.LanguageServices.Razor.Test.csproj, src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Microsoft.VisualStudio.LiveShare.Razor.Test.csproj
- Also trimmed some more dependencies.
- Because Microsoft.VisualStudio.LanguageServerClient.Implementation hasn't been updated had to pin Shell.15 in the language server client project
- `IFeedbackDiagnosticFileProvider` got moved into the `Microsoft.Internal.VisualStudio.Shell.Framework` so removed a reference to the previous emedded packages.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1297102
=> Update VS Shell package versions to 17.0.0-preview-2-31221-277

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
- Update LSP protocol version and add support for `CompletionList.Data` wrapping in our HTMLC# completion handler.
Part of dotnet/aspnetcore#31852
Part of dotnet/aspnetcore#31883
Part of dotnet/aspnetcore#31886
/cc @ToddGrun @jimmylewis Down for another dual insertion to consume the SumType/CompletionList optimizations?
=> Add support for C#/HTML CompletionList.Data and CommitCharacters

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/DefaultRazorHoverInfoService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/RazorHoverEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/RazorHoverInfoService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/VSHover.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/DefaultLSPTagHelperTooltipFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/DefaultVSLSPTagHelperTooltipFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/LSPTagHelperTooltipFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/VSClassifiedTextElement.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/VSClassifiedTextRun.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/VSContainerElement.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/VSContainerElementStyle.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/VSImageElement.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/VSImageId.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/VSLSPTagHelperTooltipFactory.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultVSLSPTagHelperTooltipFactoryTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs
- Adds classifications for Razor TagHelper element/attribute quick info tooltips.
- Some of the logic here can be reduced once LSP VSCompletionItems support returning ContainerElements instead of just ClassifiedTextElements, tracked by https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1319274.
Before:
After:
Fixes: 
https://github.com/dotnet/aspnetcore/issues/30224
=> Add classifications for TagHelper element/attribute quick info tooltips in VS

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/IndentationContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/TextLineExtensions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
Fixes AB#1273468
(and in case that doesn't work, Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1273468/)
When reformatting we used to look at the existing formatting and base changes on that. When formatting things with tabs, that fell down because we'd see `\t\t` and think "oh, they want two spaces of indentation". This PR adds a new field so that we can think "oh, they want 8 columns of indentation" instead.
=> Fix HTML formatting when using tabs

NuGet.config, eng/Versions.props, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks.csproj, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Microsoft.AspNetCore.Razor.LanguageServer.Common.csproj, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Microsoft.VisualStudio.Editor.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/Microsoft.VisualStudio.Mac.LanguageServices.Razor.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.csproj, src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/Microsoft.CodeAnalysis.Remote.Razor.Test.csproj, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Microsoft.VisualStudio.Editor.Razor.Test.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Documents/VisualStudioFileChangeTrackerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Microsoft.VisualStudio.LanguageServices.Razor.Test.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorProjectHostTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackRazorProjectHostTest.cs, src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test.csproj
In addition to a blanket merge I:
- Update Shell packages to match latest dev17 bits.
- Comb through pre-existing "hacks" and removed ones that are no longer required.
- Re-enabled all tests.
- Trimmed unnecessary dependencies
=> Merge interop branch into vs17.0 branch

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentPublisher.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RangeExtensions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPSpanMappingService.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorLSPSpanMappingServiceTest.cs
- The Razor LSP span mapping service wasn't dealing with mapping failures correctly, which crashed rename in some scenarios.
- Also renamed `CSharpSpanMappingService` to `RazorLSPSpanMappingService` to better reflect its purpose (@NTaylorMullen this was per your suggestion in a previous convo).
When working on this issue I periodically noticed a separate issue where rename doesn't work entirely (i.e. trying to rename something and nothing happens), so I'm trying to investigate that as well and may file a separate issue in a bit.
Fixes: 
https://github.com/dotnet/aspnetcore/issues/30949
=> Fix injected service rename crash

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/cgmanifest.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/csharp-language-configuration.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/css-language-configuration.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/html-language-configuration.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/javascript-language-configuration.json
- Out-of-the box this doesn't actually enable contextual Razor commenting in Razor files. It requires changes from the platform; however, with those changes this works :)
- Added VSCode's C#, HTML, CSS and JavaScript language-configuration.json files and hooked them up in our pkgdef.
- Upated VSCode's embedded language mapping.
- Updated cgmanifest to record our newly acquired assets from VSCode.
- Found that when commenting single lines the platform (and VSCode) will look at the beginning of the line's scope association if you don't have anything selected and we weren't marking C# content as "source.cs", updated grammar accordingly.
Fixes dotnet/aspnetcore#14320
=> Add support for contextual Razor commenting.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/src/extension.ts
- Adds the config required for the new workspace trust feature in VS Code
- Returns the fall-back `inspectUri` value from the exception handler in the debugging extension
=> Add workspace trust config and always return inspectUri

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/FilePathNormalizer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs
- Normalize Uri's coming into C# Semantic token requests to prevent false-negatives.
Fixes: https://github.com/dotnet/aspnetcore/issues/32369
=> Handle spaces in C# semantic requests

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/IOnAutoInsertHandler.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRazorDiagnosticsHandler.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRazorLanguageQueryHandler.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRazorMapToDocumentEditsHandler.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRazorMapToDocumentRangesHandler.cs
- In Razor scenarios this improves perf pretty much across the board by 50%.
- The only requests that should be "serial" are document state requests like `textDocument/didChange` etc. This was just a misunderstanding of how the `[Serial]` and `[Parallel]` attributes work in O#. So let me explain a bit more. When O# processes requests it starts it takes into account the `[Serial]`/`[Parallel]` mechanic:
- `[Serial]`: Wait for the request to finish before starting the next
- `[Parallel]`: Proceed to the next request to process, no need to await it.
Because of this behavior the only types of requests that actually need to be serial are ones that mutate server state (the didChange's etc.). All others will queue behind a serial request, meaning if you get:
1. `textDocument/completion` "@"
2. …
=> Parallelize more RZLS requests.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorComponentSearchEngine.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorComponentSearchEngineTest.cs
- An assembly's name and file path can differ, so we probably don't want to check for equality between the two.
- Doesn't seem to impact performance _too_ much, in a large solution we still get results in about a second or less. Alternate solutions would either be to add a file path property to `TagHelperDescriptors` or an assembly name property to the project snapshot manager, but both of these seem to be quite a bit of work.
- GTD still doesn't work with component attributes, filed https://github.com/dotnet/aspnetcore/issues/33096 to track.
Fixes https://github.com/dotnet/aspnetcore/issues/29841
=> Fix go-to-def issue with components

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs
- We have a single "parse Razor file" mechanism in our design time infrastructure who's primary goal is to start a parse for a Razor file and if someone else asks for said parse while one is already running to not start a second parse but instead return the task from the first. To do this we cache the parse task (weakly to not result in too much static memory growth) and return it to all consumers. Prior to this change we were caching the task for the parse under a lock. Meaning we were attempting to start the Razor parsing `Task` when a parse was requested and then allow any future requestor to party on the same task. Turns out us "starting" the Razor parser task would typically run synchronously in Visual Studio scenarios. In larger apps this resulted in several threads queuing up on …
=> Don't block subsequent threads when Razor parser runs synchronously.

src/Razor/src/Microsoft.VisualStudio.RazorExtension/css-language-configuration.json
- Added `wordPattern` and `indentationRules`.
- `wordPattern` influences all sorts of features, completion being one of them so if you type `foo-bar` completion won't dismiss when you type the `-`.
- `indentationRules` influence the indentation when you enter a newline or the base indentation for your cursor when you click around the document (smart indent).
-  Played around with it a bit in the editor and everything seemed to work. Found [some issues with completion in CSS](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1335055/) but that was due to unrelated bits.
Part of dotnet/aspnetcore#33085
=> Upgrade CSS language-configuration.json

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- Turns out a lot of our language server initialization logic runs on the UI thread and that logic can take a significant amount of time; especially when restarting a language server.
Fixes dotnet/aspnetcore#33191
=> Don't active language server on UI thread.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ExtendableServerCapabilities.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServerCapability.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPDocumentMappingProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProjectionProviderTest.cs
- By adding capability checks we now wont fire off custom messages to language servers that don't support them. Meaning, if our language server is in the midst of shutting down or spinning up no messages will go to it because there wont be a server with the corresponding capbilities yet.
-  We have to use the experimental capabilities bucket here because not all platforms maintain custom capabilities. For instance in Visual Studio scenarios it will deserialize serve capabilties into what it believes is "valid" and then will re-pass said server capabilities to our client side code having lost the information of the custom. To avoid this we use the experimental bag since it's part of the official LSP spec. This approach enables us to work with any client.
Fixes dotnet/aspnetcore#33193
=> Restrict custom messages only to when server is started.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs
- Turned out the flaky test was in fact caused by me :D. When I made our document parsing mechanics not occur inside of locks / not occupy thread time for concurrent requests I inadvetantly broke the ability for our document state to accurately weak reference Razor parsed output. Because of this tests would be flaky because in some scenarios they'd expect that document versions would be cached when in fact they weren't.
Fixes dotnet/aspnetcore#33208
=> Fix DocumentState's WeakReference to Razor output.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticConverter.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticConverterTest.cs
- Compiler added support for this so we need to react.
Fixes dotnet/aspnetcore#33231
=> Add support for Razor warning severity.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/AdhocServices.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/AdhocWorkspaceServices.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AdhocWorkspaceFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultAdhocWorkspaceFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultHostWorkspaceServicesProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultProjectSnapshotManagerAccessor.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/HostWorkspaceServicesProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VSHostWorkspaceServicesProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestProjectSnapshotManager.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/RazorOnAutoInsertProviderTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingContentValidationPassTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingDiagnosticValidationPassTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestAdhocWorkspaceFactory.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestWorkspace.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultRazorEditorFactoryServiceTest.cs
- There are several locations in our stack where we construct an `AdhocWorkspace` because we don't have direct access to C#'s workspace. Primary reason behind us not having access is that our language server does not run in the same process as Roslyn. On paper constructing an `AdhocWorkspace` is easy; however; behind the scenes if you don't provide it any services it'll utilize MEF to find all the services it cares about. Turns out the default workspace impls actually depend on several services and the probing of the MEF services isn't cheap.
- To prevent us from incorrectly creating `AdhocWorkspaces` and to also enable the creation of the workspaces to re-use VS' workspaces (if available) I built out two key abstractions:
1. `AdhocWorkspaceFactory`: As the name implies, it creates an …
=> Prevent C# AdhocWorkspace from probing MEF services.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultRazorDynamicFileInfoProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LSPEditorFeatureDetector.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorProjectChangePublisher.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/MacLSPEditorFeatureDetector.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultLSPEditorFeatureDetectorTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorProjectChangePublisherTest.cs, src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/ProjectSystem/RazorDocumentInfoProviderTest.cs
- Removed the experimental editor feature flag and all the implications it imposed in our feature detector in regards to LiveShare.
- Updated tests to verify only what's still valuable.
Fixes dotnet/aspnetcore#33295
=> Turn Razor LSP editor on-by-default.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs
- WebTools is in the process of renaming HTMLX -> HTML and this Temp setting represents the HTMLX variant of the setting.
=> Respect old & new HTML setting for legacy editor.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnAutoInsertHandler.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/AutoClosingTagOnAutoInsertProviderTest.cs
- Transitioned HTML tag auto-completion into the Razor language server. Reasoning:
- Auto-completing tags is a super common behavior that typically results in our HTMLC# world resolving the language, re-invoking and then remapping.
- We were going to have to absorb a piece of this tech no matter what because the HTML language server would never auto-complete tags with bang-escapes.
- We were going to have to absorb a piece of this tech no matter what because the HTML language server does not know about TagHelper TagStructure auto-complete behaviors.
- The purpose of this change was perf motivated (roughly increases speed by 25-50%) but in turn I also enabled two new feature parity bits: bang escape auto-complete and TagHelper tag structure respects.
- Hardcoded the list of void elements …
=> Enable auto-complete of HTML elements in the RZLS.
