src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectWorkspaceStateGenerator.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/OOPTagHelperResolver.cs
src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/OOPTagHelperResolverTest.cs

We needed to account for OperationCanceled as well as TaskCanceled. This doesn't end up "fixing" anything except preventing this scenario from being noise in the logs.

Handle OperationCanceledException

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs

- C# uses '>' as a trigger character for pointer operations. This conflicts heavily with HTML's auto-closing support.
- Therefore, for perf reasons we purposefully remove the trigger character since using pointers in Razor is quite rare.

Remove `>` from C# completion triggers.

---

eng/Versions.props
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorDocumentServiceProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorSpanMappingService.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/RazorFeedbackDiagnosticFileProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorDocumentOptionsService.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorDocumentOptionsServiceTest.cs

- Responding to Roslyn changes in https://github.com/dotnet/roslyn/pull/53879 which adds a Razor options service.
- When implementing the Roslyn side, I tested out the changes in Razor and everything seemed to work. However, I can't currently test with the final upgraded packages versions because my dev17 build appears to be busted. 🤦‍♀️ so while I'm pretty confident that these changes work since I tested them before, I wasn't able to do a final test to make sure.
Fixes: 
dotnet/aspnetcore#32555

Add Razor options service in response to Roslyn changes

---

azure-pipelines.yml

- If we only run that job on main, but the commit only exists in main-vs-deps the job will never run. So run it on both for now.

Run OneLocBuild on main-vs-deps

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs

Fixes https://github.com/dotnet/aspnetcore/issues/30382
When a child component is a property of its parent component, it doesn't affect the indentation in the generated C#, but the formatter was assuming it did, leading to bad results.

Fix formatting in child components

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/OmniSharpVSCompletionContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/OmniSharpVSCompletionInvokeKind.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs
src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveCompletionSourceTest.cs

- To align with C# completion behavior we do not return Razor directive completions when an implicit expression is more than just a start of a word or on deletion.
- In the future when we've adopted the LSP embedded language re-design we wont need to special case "start of word" or on deletion because resolution of a C# completion list will end up `null` and allow us to align to when C# returns their completion items / to when we do ours.
- Added a JsonConverter to allow our Razor language server to attempt to deserialize completion contexts into VS' form. In VSCode scenarios it'll still deserialize into VS' form but the value will be different.
- Added tests.
Fixes dotnet/aspnetcore#33675

Don't return directive completions on delete & middle of word.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnAutoInsertHandler.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/OnAutoInsertHandlerTest.cs

- This ultimately means when a user types `=` they wont get quotes auto-added for them. The reason behind this is that those quotes are not "overtypeable" and it doesn't feel consistent vs. just typing quotes (they become overtypeable).
- While doing this change I also found that we were still broadcasting `>` as one of our OnAutoInsert options, corrected this while I was touching the code.
- Left the old `=` OnAutoInsert code in-tact with the intent that we can re-enable it once the platform enables dynamic overtyping for these types of scenarios
Fixes dotnet/aspnetcore#33677

Remove OnAutoInsert support for `=`.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs

- To align with HTML completion behavior we do not return Razor directive completions when an implicit expression is more than just a start of a word or on deletion.
- In the future when we've adopted the LSP embedded language re-design we wont need to special case "start of word" or on deletion because resolution of a HTML completion list will end up `null` and allow us to align to when HTML returns their completion items / to when we do ours.
- Added tests.
See [backing VSTS](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1338261) issue for end-user impact details
Fixes dotnet/aspnetcore#33676

Don't return component completions on delete & middle of word.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorSyntaxTreeExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SourceTextExtensions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsEndpointTest.cs

- In our diagnostic translation tech we now can detect rude edits via the diagnostic code starting with `ENC`. Once we detect a rude edit diagnostic we then have to enter a separate range translation path because:
1. Rude edit diagnostics have their ranges pre-mapped based off of Razor runtime #line pragma's which is entirely different code than what we see at design time.
2. Not all rude edit diagnostics can actually be mapped and we need to fallback to something understandable.
- When remapping rude edits today we handle two scenarios seamlessly (edits map directly)
1. C# statements
2. C# expressions
Other scenarios when a rude edit can occur may span multiple lines that have various Razor constructs on them (Razor comments can introduce this which I test against). In scenarios where we …

Add support for remapping rude edit diagnostics.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/AutoClosingTagOnAutoInsertProviderTest.cs

- Prior to this when you'd type out an end-tag with a `/` we'd still auto-close the end-tag. To account for this added a slash check for our without end tag completion providers.
- Found that when adjusting self-closing tags we didn't actually need snippet completion because cursor is already in an expected location. Therefore, swapped the logic to not require snippets.
- Fixed an orthogonal issue where whitespace leading a `/` would be re-added on self-closing tag addition.
- Updated and added new tests.
Fixes dotnet/aspnetcore#33770

Fix typing self-closing tag out char-by-char.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs

- Due to a [VSTS issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1348317) we have to workaround this bug:
Fixes dotnet/aspnetcore#33903

Remove `=` from HTML's trigger characters to avoid bug.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/AutoClosingTagOnAutoInsertProviderTest.cs

- Found that the Razor compiler has some really interesting [quirks](https://github.com/dotnet/aspnetcore/issues/33919) when it comes to finding the "owner" of an HTML element when within code blocks. Added some "ensurement" methods to workaround these quirks until the compiler can fix them.
- Added tests.
Fixes dotnet/aspnetcore#33901

Fix HTML tag auto-completion in code blocks.

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/css-language-configuration.json

- Enables:
- `/*` => `/*|*/` auto-complete
- `/*|*/` On Enter =>
```
/*
|
*/
```
- Block commenting highlighting
-------
Found Platform issues:
- [Brace navigation on `/*` or `*/` doesn't work.](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1348264/)
--------
- [OnEnterRule Specification](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#on-enter-rules)
Fixes dotnet/aspnetcore#33896

Add better CSS commenting support.

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.tmTheme
src/Razor/src/Microsoft.VisualStudio.RazorExtension/csharp-language-configuration.json

- Enables:
- `// ABC | DEF` On Enter =>
```C#
// ABC
// DEF
```
- `/*` => `/*|*/` auto-complete
- `/*|*/` On Enter =>
```C#
/*
* |
*/
```
- ` * |` On Enter =>
```C#
/*
*
* |
*/
```
- Block commenting highlighting
- Also fixed an unrelated issue where in the platform logs there were complaints about C#'s TextMate usage of `User Members - Parameters`, changed this to be the proper identifier.
-------
Found issues:
- Brace navigation on `/*` or `*/` doesn't work. [Issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1348264/)
- language-configuration.json Smart indent doesn't look at the "last line" it looks at the last line with content. [Issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1348266/]
- C# uses OnAutoInsert to provide `///` auto-inclusions, this can be done …

Add better C# commenting & smart indent support

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs

- Since the WebTools side has been merged and inserted, we can delete the temp HTMLX setting: https://devdiv.visualstudio.com/DevDiv/_git/WebTools/commit/9a5dafc9441392b4902fbb4b586689d2a06e4dff?refName=refs%2Fheads%2Fmain

Remove temp HTMLX in LSP editor feature detector

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/javascript-language-configuration.json
src/Razor/src/Microsoft.VisualStudio.RazorExtension/language-configuration.json

- Adding quotes to the auto-close before specifications for JS and Razor
Fixes dotnet/aspnetcore#33931

Allow C# and JS members to auto-close in HTML attributes.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/AutoClosingTagOnAutoInsertProviderTest.cs

- Ultimately this is due to [this quirk](https://github.com/dotnet/aspnetcore/issues/33919#issuecomment-870233627) of the Razor compiler
- Added tests
Fixes dotnet/aspnetcore#33930

Allow auto-closing nested HTML tags in C# blocks.

---

eng/Versions.props

- Localizations weren't showing up in latest VS builds even though the vsix's produced locally worked. We need to run the XLIFF build so that the satellite assemblies are produced in order for them to be used.

Run XLIFF on official builds

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/IRazorDiagnosticsHandler.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/OmniSharpVSDiagnostic.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/OmniSharpVSDiagnosticTag.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsResponse.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsEndpointTest.cs

- The core issue was that the O# framework ends up using custom `JsonConverters` to serialize O# specific diagnostic tags. The drawback of this is that when working with VS diagnostics they don't respect custom tag values. To combat this I shadowed the `Tags` property in a new diagnostic type called `OmniSharpVSDiagnostic`.
- Created a new `Diagnostics` namespace to start throwing all of our diagnostic logic into.
- Updated tests.
**Before:** These squiggles would show as red errors
**After:**
Fixes dotnet/aspnetcore#33790
/cc @dibarbet

Allow purple squiggles for EnC scenarios in Razor.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/OmniSharpVSDiagnostic.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/OmniSharpVSDiagnosticRank.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/OmniSharpVSDiagnosticTags.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/OmniSharpVSProjectAndContext.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPRequestInvoker.cs

- We were attempting to translate VS diagnostics into LSP bound diagnostics. The problem with this is that VSDiagnostics have many more fields than the normal LSP spec'd diagnostic type. Therefore, when we'd attempt to translate VSDiagnostics to their corresponding Razor positions we'd lose all of the VSDiagnostic data. One of the fields we lost was "Project", bringing all of the VS properties over to our O# implementation allows us to have a higher fidelity of diagnostic translation presenting things like the project for a diagnostic. To prevent future mismatches I brought over more than just the project members I brought over everything. This means that C# can build diagnostics however they want and we'll "do the right thing".
- Also found that when requesting diagnostics from C# we …

Properly serialize VS diagnostics during translation.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageService`IVsLangaugeInfo.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef

- The `Razor` name is more appropriate for extenders so before we go on-by-default the intent is to translate the Razor settings and content type over to the new "Razor" name.
- Played around with changing class & property names from `RazorLSPXYZ` to `RazorXYZ`. In the end things were just a bit too confusing with all the legacy that was pre-existing. Too many services overlapped and made it really hard to reason about what was "new" and what wasn't. Isolating this change to only be the content type / settings felt better.
Fixes dotnet/aspnetcore#33266

Change RazorLSP content type & settings to "Razor".

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts

Adds the `cascadeTerminateToConfigurations` property to the browser configuration. This causes the debugging session hosting the dev server to be stopped when the user stops the browser debugging session.
Fixes: https://github.com/dotnet/aspnetcore/issues/32393

Add cascadeTerminateToConfigurations to browser config

---

.editorconfig

I ran into this many times when working on https://github.com/dotnet/aspnetcore-tooling/pull/3808.
Before, the below example would try to generate the field `errorReporter` instead of `_errorReporter`. Now it generates the correct naming style:

Update .editorconfig naming for instance fields

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCompletionItemProvider.ts
src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/TestOmniSharpWorkspace.cs

- The `@` character is a valid Razor trigger but not a valid C#/HTML trigger. Therefore, when we see our `@` (transition) we'll translate it into a ctrl + space like invocation so all completions are queried.
- Testing this behavior is tracked separately [here](https://github.com/dotnet/aspnetcore/issues/19296).
Fixes dotnet/aspnetcore#34182

Fix typing `@` does not provide C# completion in VSCode.

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/ProjectSystem/ProjectSnapshotManagerBenchmarkBase.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectSnapshotManagerDispatcher.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSnapshotManagerDispatcher.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Shared/TestProjectSnapshotManager.cs
src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/OOPTagHelperResolverTest.cs
src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/TestProjectSnapshotManagerDispatcher.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultProjectSnapshotManagerTest.cs

#3808 caused an issue where components occasionally weren't being discovered by the LSP editor. This was because of a threading issue in the ProjectSnapshotManager (PSM) constructor. To summarize, the root of the problem was:
- In the new LSP editor, the PSM constructor was called using the special PSM thread implemented in #3808.
- The constructor fired off the PSM constructor's triggers in a [fire-and-forget](https://github.com/dotnet/aspnetcore-tooling/blob/7cb041285430431b8b2fba1a4aeeb0315e69df34/src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs#L72) fashion.
- Due to the fire-and-forget, the triggers sometimes weren't initialized until after [this line](https://github.com/dotnet/aspnetcore-tooling/blob/7cb041285430431b8b2fba1a4aeeb031 …

Fix component discovery issue

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CSharpStatementBlockOnTypeFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestLoggerFactory.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingTest.cs

I'm not adding actual logging until I know for sure it doesn't leak to users in VS, but this at least enables logging calls to go somewhere in test explorer.

Add loggers to tests for future logging goodness

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/language-configuration.json

- Many users don't know to overtype the ">" bracket which ends up being more confusing to users.
- Also fixed HTML comment auto-complete.
/cc @mikadumont

Remove auto-complete of "<" to "<|>"

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/VisualStudioRazorParser.cs

- I thought no one used this method so I removed it, but it turns out WebTools does, oops
- [This](https://github.com/dotnet/aspnetcore-tooling/blob/f81a59a1013b63d6625ba2dd950ebcda023cf491/src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs#L146) is the original method. I slightly modified it to fit with changes from the UI thread PR

Put back removed method into Razor parser

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DirectoryHelper.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectFileChangeDetector.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DirectoryHelperTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationFileChangeDetectorTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectFileChangeDetectorTest.cs

- We can encounter `PathTooLongException` when traversing deeply nested structures such as `node_modules`, to avoid this lets avoid that folder all-together.
- Also be more resilient to `PathTooLongException`. Rather than throwing we should swallow the exception then back out a level and continue the walk (though node_modules is the most likely cause, it could still happen). 
Fixes: https://github.com/dotnet/aspnetcore/issues/31237

Handle PathTooLongExceptions

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs

- Ideally these should be added in the C# language server but for the time being these are the asks from Razor language server users so we're bringing them to C# users via our HtmlC# language server for speedsakes.
- Times when we provide C# snippets:
- Empty line C# blocks (this is kind of a hack that will be usurped by C#'s impl)
- Implicit expressions
- Updated tests to reflect the updated model of providing snippets
- Our completion tests are a disaster, filed a separate issue to clean them up to get better, more coherent coverage: https://github.com/dotnet/aspnetcore/issues/34357
Fixes dotnet/aspnetcore#30774

Add support for for, foreach, if and prop C# snippets.

---

eng/Versions.props
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj
src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Microsoft.VisualStudio.LiveShare.Razor.Test.csproj

This reverts commit 7fba8c077bd1bd247504e65cf98f6a5cf4851fbf.
- Turns out that https://github.com/dotnet/aspnetcore-tooling/pull/3966 was unnecessary because the actual issue was https://github.com/dotnet/core-eng/issues/13691. Reverting.

Revert "Update threading version (#3966)"

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/ProvideSemanticTokensDeltaParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/ProvideSemanticTokensParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs

- When we make an edit we send `textDocument/didChange` to the client, causing VS to immediately trigger `textDocument\semanticTokens\edits`. The problem is, at that point C# (usually) hasn't propagated the new version and returns us the HostDocumentSyncVersion from the previous version. When the Razor and C# versions don't match we return null because otherwise we'd either cause any C# tokens to "flash" due to missing C# info or possibly mis-color if anything has moved. VSLanguageServerClient then puts us on a bit of a timer before trying again because we obviously have stuff to work out, and then by the time they've asked again everyone is caught up and we colorize.
This explains the behavior I was seeing where (other than a few initial `textDocument/semanticTokens` request) our total …

Speed up SemanticTokens by synchronizing C# virtual documents

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/ExtendedCodeActionContext.cs

- After the LSP protocol refactor we weren't properly deserializing `SelectionRange` so we weren't understanding where a light bulb request was originating from resulting in us not providing any light bulbs.
Fixes dotnet/aspnetcore#34891

Fix "add using" Razor light bulb

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/language-configuration.json

- Without these changes we were unintentionally relying on some VS bugs that incorrectly inferred indentation.
Fixes dotnet/aspnetcore#34894

Update language-configuration.json to match latest VSCode behavior.

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs

(Retargetting main-vs-deps)
- Previously if we had a project RCL.csproj, and App.csproj (with App depending on RCL) and you changed the name of a Component in RCL it would NOT update the project.razor.json of App with the new info. By getting a list of all the dependent projects and forcing an update on them we make sure that project.razor.json for App serializes and then all the correct things happen in our Error list.
This works when tested locally, but I'm warry of it being too big of a hammer since it does force file operations, which could get potentially expensive on a large project for which the root has changed. I tried a similar approach in a couple other places that did not work, but if someone has a more targeted idea I'm open.
Fixes: dotnet/aspnetcore#31282
I'll need to …

Update dependent projects with modified TagHelpers

---

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/CSharpCodeParser.cs
src/Razor/src/Microsoft.NET.Sdk.Razor/SdkRazorGenerate.cs
src/Razor/src/Microsoft.NET.Sdk.Razor/SdkRazorTagHelper.cs
src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.CodeGeneration.targets
src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets
src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets
src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest21NetFx.cs
src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildPerformanceTest.cs
src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerIntegrationTest.cs
src/Razor/test/RazorLanguage.Test/Legacy/CSharpCodeParserTest.cs
src/Razor/test/testapps/ClassLibraryMvc21/ClassLibraryMvc21.csproj
src/Razor/test/testapps/RestoreTestProjects/RestoreTestProjects.csproj
src/Razor/test/testapps/SimpleMvc21/SimpleMvc21.csproj
src/Razor/test/testapps/SimpleMvc21NetFx/Models/ErrorViewModel.cs
src/Razor/test/testapps/SimpleMvc21NetFx/Program.cs
src/Razor/test/testapps/SimpleMvc21NetFx/SimpleMvc21NetFx.csproj
src/Razor/test/testapps/SimpleMvc21NetFx/SimpleTagHelper.cs
src/Razor/test/testapps/SimpleMvc21NetFx/Views/Home/Index.cshtml
src/Razor/test/testapps/SimpleMvc21NetFx/Views/Shared/_Layout.cshtml
src/Razor/test/testapps/SimpleMvc21NetFx/Views/_ViewImports.cshtml
src/Razor/test/testapps/SimpleMvc21NetFx/Views/_ViewStart.cshtml
src/Razor/test/testapps/SimpleMvc22/SimpleMvc22.csproj

This is a port of https://github.com/dotnet/sdk/pull/19094 to 3.1 that changes the RazorSDK to use the in-box
compiler when building 2.1 apps.
2.1 shipped a Razor compiler as a package which was referenced by ASP.NET Core MVC apps by default. This package contained a 2.1 binary that required the 2.1 .NET runtime. As part of our 2.1 EOL work, we updated the 6.0 SDK to instead use the Razor compiler that is carried in the SDK. This PR ports the change to the 3.1 Razor SDK.
Our 6.0 verification confirmed that the compiler in the SDK is highly compatible with the 2.1 compiler and users should be able to upgrade without issues.
[If yes, specify the version the behavior has regressed from]
While we performed manual testing and have automated test to cover this scenario, it's possible there are …

Add support for building 2.1 Razor projects using the RazorSDK

---

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VsSolutionUpdatesProjectSnapshotChangeTrigger.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/VsSolutionUpdatesProjectSnapshotChangeTriggerTest.cs

- We weren't jumping to the dispatcher thread prior to resolving TagHelpers on build.
- Updated code to be a little more test friendly now that things are more async
- Ultimately we don't really rely on build to resolve TagHelpers anymore hence why this went unnoticed for a bit; however, there are more complex scenarios where you're absorbing TagHelpers from live nuget packages and need to force TagHelper resolution.
Fixes dotnet/aspnetcore#35126

Fix resolving TagHelpers on project build.

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/BatchableWorkItem.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/BatchingWorkQueue.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/BatchingWorkQueueTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs

- The ultimate goal of this PR is to change how we calculate TagHelpers so we don't rely as heavily on Task cancellation exceptions. Prior to this we'd detect changes to the workspace and then aggressively cancel TagHelper resolution requests as more changes came in. Turns out when loading/unloading/changing solution configurations this call path was hit extensively and caused perf regressions. Therefore this change set is meant to remove the canceled exceptions here:
- The approach I took to resolve this is to entirely change how we resolve TagHelpers. We now batch all requests for TagHelpers and then will process them one at a time. We already had this concept in other parts of Razor so I abstracted the "worker queue" logic into its own `BatchingWorkQueue` data type.
- The batching work …

Change C# Workspace TagHelper change detection to be batched.

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.tmTheme

- We were still seeing highlighting on "@" after I made some other changes, it turns out that was because TextMate was overriding our color options with HTML Server-Side Script.
Fixes part of https://github.com/dotnet/aspnetcore/issues/34770

Don't use "HTML Server-Side Script"

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPass.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingPass.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SyntaxListExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SyntaxNodeExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SyntaxTokenExtensions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs

- By using the SyntaxTree instead of a string to decide where to edit formatting we simplify the logic somewhat and set ourselves up to benefit from any future improvements that might be made to the SyntaxTree/Compiler.
Fixes: https://github.com/dotnet/aspnetcore/issues/33689
All tests pass as-is, but I wanna come back to this in a day or so (once my brain clears and I won't be testing the same stuff the tests do) and exercise things manually in case I've broken anything the tests don't cover, then add tests for that too. If anyone else wants to give that a shake I'm happy to have the help.

RazorFormattingPass

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CSSErrorCodes.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsEndpointTest.cs

- The presence of C# blocks in `<style>` elements really complicates things because of the the restrictive nature of the CSS syntax. We're flat-out ignoring some errors if a C# block is in the style element, which is not ideal but necessary until the HTML document no longer emits "~"'s.
Fixes: https://github.com/dotnet/aspnetcore/issues/33097

Handle CSS diagnostics with C#

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextViewConnectionListener.cs

It looks like [this VSTS issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1306491) no longer repros after the LSP refactor. To confirm, I put a delay at the beginning of [this method](https://github.com/dotnet/aspnetcore-tooling/blob/af9d6a1563dd9df3ad1dc917c8d8788ac1230f02/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs#L130) to ensure the TextView finishes attaching first.

Remove exception catch from RazorLSPTextViewConnectionListener

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs

While prepping for showcase I noticed the for-loop snippet was missing a `++`.

Add missing for-loop snippet part

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/RazorSemanticTokensEndpoint.cs

- Since Razor doesn't currently have the capability to parse less than the full document (while still giving correct results) the Semantic Tokens Range requests (which are an optional optimization for LSP Servers which know how to return smaller sections of documents) actually end up hurting performance since we get multiple range requests all at once, each of which is walking the whole tree (not to mention paying the cost of LSP requests and serialization).
- To avoid this behavior we need only report that our LanguageServer does not support range requests.
- This takes our performance on startup for large apps/documents from 1-2 minutes to ~35 seconds.
- I've elected to leave the existing Range infrastructure in for now because it's never been a significant maintenance burden and the …

Report no SemanticTokens range capability

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentFactory.cs

- Accidentally was not exporting the HTML virtual document factory so we were failing to synchronize with our HTML virtual document.

Fix HtmlVirtualDocumentFactory's MEF export.

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultRazorDynamicFileInfoProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorDynamicFileInfoProvider.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorDynamicFileInfoProviderTest.cs

- After investigation we found that Roslyn doesn't call into our "remove" method for our dynamic file info provider stack when projects/solutions tear down. From Roslyn's perspective this is by-design. To ensure this by-design behavior mistake doesn't get repeated I've decorated our pre-existing `RemoveDynamicFileInfoAsync` method with a nice comment indicating why we shouldn't rely on it. The true future proof fix here will be removing the remove call-path on Roslyn's front.
- Ultimately this fix encompasses hooking into our `ProjectSnapshotManager` event loop to detect cases when projects/documents/solutions get removed and tear down our internal state in response. This ensures that we no longer leak entries when solutions are closed. Specifically these entries no longer leak:
- …

Don't leak when documents / projects / solutions get removed or closed.

---

eng/Versions.props
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/JsonRpc/JsonRpcRequestScheduler.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/JsonRpc/RazorOmniSharpRequestInvoker.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/JsonRpc/JsonRpcRequestSchedulerTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/JsonRpc/RazorOmniSharpRequestInvokerTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/JsonRpc/TestLoggerFactory.cs

- We now include our own request invoker that doesn't respect content modified or concurrency options. Reasons being is that content modified in O# represents a Serial request has come in, cancel all parallel requests; we don't want this in VS because it can operate on out-of-date data. We then don't need to respect the concurrency option because by default we have unbounded concurrency :D.
- Our request invoker has the following patterns:
- Request is serial, await it before executing any additional requests
- Request is parallel, fire and forget it. Allow O# to cancel it if needed.
- Broke up request invocation & request scheduling in order to follow O#'s separation of concerns. This enables us to function semi-like the defaults in the framework while simultaneously enabling new …

Don't block serial requests on long-running parallel requests.

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/ProjectExtensions.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/SolutionExtensions.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs

- We needed to expand the scenarios under which the project.razor.json gets updated for dependent projects.
- Considered adding tests, but no tests of this class yet deal with document updates, so there's a fair bit to work through and I'll come back to that.
Fixes: https://github.com/dotnet/aspnetcore/issues/33957

Update dependent projects when razor files are added or removed

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs

Fixes https://github.com/dotnet/aspnetcore/issues/34320
I don't love this, but it is better than the current behaviour. Curious for your thoughts.
Also this took way too long to find out what was going on 😛

Don't format object, collection and array initalizers

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.tmTheme

- The problem here was that our TextMate definition was overgeneralizing `HTML Operator` to include the `<` and `>`. By giving it it's own entry we can match it to `HTML Tag Delimiter` which matches the behavior in regular HTML files.
Fixes: https://github.com/dotnet/aspnetcore/issues/35860

Correct '<' classification in Textmate

---

src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultDotNetProjectHost.cs

Fixes https://github.com/dotnet/aspnetcore/issues/35952
The `DotNetProject` class that is firing the events here is a VS Mac class, so has no idea about dispatcher threads. It does helpfully switch to the UI thread before firing these events though 😛

Switch to dispatcher thread in VS Mac

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LinkedEditingRange/LinkedEditingRangeEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/LinkedEditingRange/LinkedEditingRangeEndpointTest.cs

- Missed a case in the original PR (https://github.com/dotnet/aspnetcore-tooling/pull/4125) which caused the end boundary of the span to not be respected. For example, we should still return results to LSP if the cursor is somewhere like `<test1[||]></test1>`.
Fixes: 
https://github.com/dotnet/aspnetcore/issues/35951

Fix bug in LinkedEditingRange span calculation

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.cs

- I found that different project paths would be stored in our `ProjectInfoMap`. This cleans that up:
- This doesn't actually have any end-user impact because we do a few publishes and then things just normalize to one of the paths.

Cleanup: Normalize project file paths when absorbing project.razor.json.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorProjectChangePublisher.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorProjectChangePublisherTest.cs

- Found that after removing a document that TagHelper information for the removed document would briefly go away and then flicker back into existence. In the end this was due to how our `project.razor.json` publisher handled immediate/delayed updates.
- Had to lock around our `_pendingProjectPublishes` in order to prevent races in delayed/immediate project changes. Considered using a concurrent dictionary but they can fail to remove items and I didn't want to write the extra code that understands how to handle the failure case where a project publish fails to be removed.
- Added a test to validate this scenario.
Fixes dotnet/aspnetcore#35945

Stop resolving stale TagHelpers on document removal.

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSnapshotManagerDispatcher.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/VisualStudioFileChangeTracker.cs

@sharwell  did this work already [here](https://github.com/dotnet/aspnetcore-tooling/pull/4157). I'm just rebasing / addressing some code review comments on his behalf since he's out.
* Join asynchronously instead of blocking the dispatcher thread
* Avoid capturing unnecessary solutions in WorkspaceProjectStateChangeDetector

[Ported] Avoid capturing unnecessary solutions in WorkspaceProjectStateChangeDetector 

---

src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectBuildChangeTrigger.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacFileChangeTracker.cs
src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/ProjectBuildChangeTriggerTest.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1391658
Whitespace off recommended.
Last time I looked for all events on `DotNetProject`, but this time I searched for all event handlers and found only these two, which match was reported.
I was going to make `RunOnDispatcherAsync` do a check for the right thread, and just not use `AssertDispatcherThread` at all in the Mac project, but since most of these are sync-over-async I'm not 100% sure of the impact in doing that, so left it for now.

Switch to dispatcher thread on Mac

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LSPProjectSnapshotManagerDispatcher.cs
src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/DefaultOmniSharpProjectSnapshotManagerDispatcher.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSnapshotManagerDispatcherBase.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/VisualStudioFileChangeTrackerFactoryFactory.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioErrorReporter.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioErrorReporterFactory.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioProjectSnapshotManagerDispatcher.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioSolutionCloseChangeTrigger.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioErrorReporter.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioProjectSnapshotManagerDispatcher.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs

In an attempt to diagnose what's happening in https://github.com/dotnet/aspnetcore/issues/35787, I added some debug `WriteLine` outputs to the project snapshot manager dispatcher. Ideally these would be either (1) logs or (2) Debug.Fail, but the former doesn't apply to the Workspaces layer + not all the dispatchers support logging, and the latter will cause issues in tests.
I'm not sure how helpful these outputs would be so marking this PR as a draft for now. Any input would be appreciated.

Add error logging to PSM dispatcher

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultTagHelperCompletionService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperServiceTestBase.cs

- Turns out we were passing in the wrong information to our completion engine so it couldn't apply proper "parent tag" restrictions. TagHelpers have the ability to specify a required tag name and our completion engine wasn't capturing the proper "parent tag" name. Instead we were capturing the active tag name so when you would type `<|` we'd think the parent tag name was the empty string. After fixing which tag we were inspecting I also then found that we were blatantly passing in the wrong criteria to our matching conventions for parent tag restrictions.
- This wasn't an issue in the old editor because the old editor did not use our completion engine and instead had its own (which also had its own flaws).
- Mentioning that this issue is for "basic" completion because there's a lot more …

Add support for basic `RenderFragment` completion.

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/RazorProjectHostBase.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioSolutionCloseChangeTrigger.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorProjectHostTest.cs

Fixes https://github.com/dotnet/aspnetcore/issues/36697
A few things:
* I did see `OnAfterCloseSolution` not firing, but anecdotally it seemed like implementing `IVsSolutionEvents3` made this go away. I can provide no evidence for this though :)
* Yes the CPS stuff fires before `OnAfterOpenSolution` but that is expected. On my machine, under the debugger, however the actual dataflow event happened _afterwards_ so I didn't see any issues, but I can totally see how I would have, if I didn't get lucky
* Ultimately CPS is our "source of truth" here, since it initializes the project manager, which initializes the triggers, which is when we first get to hook up to the solution events so whilst this workaround seems a _little_ dodgy, it's not beyond reason IMO.
Happy to discuss further though if …

Mark solution as open when we receive a new project

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsEndpointTest.cs

- When users write TagHelper's or Components that override default HTML elements like `Input` the HTML stack can see that as an error because technically if a TagHelper allows body content to `Input` that is invalid in terms of a normal `input` HTML element. To account for this we suppress HTML diagnostics on TagHelper tag names.
- Added tests to validate that we suppress diagnostics on Component tag names
Fixes dotnet/aspnetcore#36569

Suppress TagHelper diagnostics on tag name.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/AutoClosingTagOnAutoInsertProviderTest.cs

- Found that we were treating TagHelper components as basic void HTML elements which auto-close as self-closing; however, there wasn't an easy way to fix this issue. Technically TagHelpers can also apply to void elements so we can't simply check "is it void and a TagHelper then do something different". Therefore I felt it was a reasonable trade to say if a user misstypes their HTML element (and avoids using our completion items) then they wont get auto-closing behavior. This in turn allows us to detect cases when a user has a more component looking HTML element like `Input` (pascal cased) and default to open/close or whatever the TagHelper specifies as its auto-closing behavior.
- Added a test to validate the new behavior.
Fixes dotnet/aspnetcore#36568

Fix auto-closing behavior of mirrored components.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Extensions/RazorLanguageKindExtensions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/LanguageServerKindExtensions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentFactory.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorHtmlPublishDiagnosticsInterceptor.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentFactoryTest.cs

- When we re-did the publish diagnostic interceptor to not load in unexpected scenarios we had to then specify a content type for when we wanted to remap diagnostics. Only problem is that we need to remap JS/HTML/CSS diagnostics too and the middlelayer that intercepts publish diagnostics requests for those sub-languages passes along their language identifier (CSS, JavaScript etc.). Therefore, we were comparing "Razor" to "cssLSPClient" which would always fail resulting in our interceptor never running
- Updated to allow remapping from JavaScript / CSS / HTML; however, this has an unintended side effect of loading Razor bits in HTML LSP scenarios. This changeset most likely isn't the final bits required to fix this isseu because it re-introduces an assembly load regression on the HTML LSP …

Fix CSS diagnostic remapping

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormatter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormattingPass.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorDocumentFormattingResponse.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorDocumentRangeFormattingParams.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/RazorOnAutoInsertProviderTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingLanguageServerClient.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs

Fixes https://github.com/dotnet/aspnetcore/issues/29645
When doing range formatting in C# the relevant lines are put into the right position as if the whole document was formatted. When doing range formatting in HTML it looks like the HTML formatter does not behave the same way. This is problematic for two reasons: Firstly, and most importantly, the Razor formatter makes assumptions about line start positions being correct, and formats based on that, which is why this bug existed, and secondly, it means that format range followed by format document would fight over where things should be.
I decided consistency between formatting methods made more sense, and consistency with C# formatting, and so range formatting now just means "format, but only change this range".

Format the whole document when doing range formatting

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/JsonRpc/RazorOmniSharpRequestInvoker.cs

- Blatant oversight here on my part. Just need to dispose our token sources :).
Fixes dotnet/aspnetcore#36787

Fix CTS leak in O# request invoker.

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/BatchingWorkQueue.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VsSolutionUpdatesProjectSnapshotChangeTrigger.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/TestProjectWorkspaceStateGenerator.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/VsSolutionUpdatesProjectSnapshotChangeTriggerTest.cs

- There are two locations in which we resolve TagHelpers:
1. WorkspaceProjectStateChangeDetector: This reacts to C# workspace and ProjectSnapshotManager changes and kicks off TagHelper resolution
2. VsSolutionUpdatesProjectSnapshotChangeTrigger: This reacts to a user building their app and us forcing TagHelper resolution because of it.
In both the above cases we need to understand when the solution is closing and cancel any active TagHelper resolution requests.
- In item 1 above we I decided to take the approach of throwing out the active work queue to cancel all in-flight work. This in turn revealed some fragilities to the pre-existing work queue so I made the work queue a little more resilient to teardown scenarios by adding some null checks / task cancellation exception understandings …

Cancel pending TagHelper resolutions on solution close.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetectorManager.cs

- Found a realllly interesting interaction with O# framework where if something imports an `IEnumerable` based service then when the outer service collection disposes it removes all entries from the imported `IEnumerable`. Because of this what would happen in our scenario is that we'd close a solution, the file change detector enumeration would be emptied and then in our file change detector manager's "Dispose" method we'd attempt to ` Stop` all active file change detectors; welllll in this situation the enumeration would be empty so `Stop` would never be called. All of those file watchers still had references to the old project snapshot manager dispatcher and would then enqueue tasks to be run on an old `ProjectSnapshotManagerDispatcher` that dispatcher would then operate in uncharted …

Fix file change dispatcher leak on solution reopen

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/CompletionSortTextHelper.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/MarkupTransitionCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItem.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperServiceTestBase.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderTest.cs

- So unintentionally this issue ended up solving 2x issues at once, I apologize for the conflated concerns!! I'll leave comments in this description detailing how/why it did two.
- When a user is trying to get attribute completions today we show HTML & attribute completion items. Both of those completion item sets get weaved amongst each other and get shown as one jointly sorted list. Now the unfortunate side effect of this is that when you have a custom component / TagHelper we spit out every possible completion item which can lead to really confusing scenarios. To fix this I took the approach of adding `SortText` to our internal `RazorCompletionItem` type to allow us to sort TagHelper completion items prior to any HTML completions.
- Now similarly when trying to get directive attribute …

Prioritize TagHelper/directive attribute completions when applicable.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPDocumentSynchronizer.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultLSPDocumentSynchronizerTest.cs

- Occasionally virtual documents get removed in the midst of trying to synchronize. I found that after deleting a Razor file we'd throw because we couldn't lookup the HTML virtual document. Updated the synchronizer to respect this scenario and added a test as well.
- Found this when investigating https://github.com/dotnet/aspnetcore-tooling/pull/4251

Allow synchronizer to handle removed documents.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DocumentPullDiagnosticsHandler.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentPullDiagnosticsHandlerTest.cs

- The platform sends one last pull diagnostic request on document close. Prior to this change we'd gracefully no-op if we couldn't find one of our documents; however, the expected behavior is to clear all diagnostics for that closed/deleted document. In the end this is a super simple change.
- Updated tests to reflect the new behavior.
- Added a CTI work item to expand our existing coverage of closed/deleted Razor documents in regards to C# diagnostics: https://github.com/aspnet/Tooling-ManualTests/issues/1503
Fixes dotnet/aspnetcore#36940

Fix C# diagnostics clearing on close/delete.

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.tmTheme

- We have proposed a more permanent fix for this against the platform, but due to resource constraints we're going to wait a bit to do that.
- This prevents "overcoloring" by removing TM themes which are known to cause problems. This degrades the startup experience to improve correctness.
Fixes: https://github.com/dotnet/aspnetcore/issues/36614

Remove TM themes to prevent overcoloring

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/ServiceHubCore/Microsoft.VisualStudio.Razor.TagHelperProvider.AssemblySearchPathsConfig.json
src/Razor/src/Microsoft.VisualStudio.RazorExtension/ServiceHubCore/Microsoft.VisualStudio.Razor.TagHelperProviderCore64.servicehub.service.json
src/Razor/src/Microsoft.VisualStudio.RazorExtension/ServiceHubCore/Microsoft.VisualStudio.Razor.TagHelperProviderCore64S.servicehub.service.json

roslynRemoteHost service was removed in https://github.com/dotnet/roslyn/pull/56426, so switch to another roslyn service.

Fix TagHelperProvider on ServiceHub Core hsot

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/razordirective-language-configuration.json
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap

- **This issue:** When multiple languages weave on the same line the beginning of the line line is used for language-configuration.json lookup. Prior to this we'd only have the ending portion of our directives be C#. This meant that the IDE would look at the beginning of hte line, find Razor's grammar and then apply its indentation rules. In Razor's case it tries to lookup HTML tags (the generic `<string>`) and increase indentation based on that.
- **The fix:** Provide a new directive language-configuration.json grammar that's not Razor and map all directives to it. Now this isn't the most ideal fix because technically what we really want is to have a Razor, HTML and C# grammar etc.; however, we currently have our Razor grammar usurping the HTML grammar which puts us in this position of …

Fix smart indent after generic inherits directive.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/SyntaxNodeExtensions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/AutoClosingTagOnAutoInsertProviderTest.cs

- **Issue:** Found another compiler quirk since we can't rely on looking up specific SyntaxTokens by position :(. Gist is that since we can't lookup token by position and have to rely on `GetOwner` we can occasionally get a node that's in front of our cursor. In the nested HTML case of `<first>|<second>` you'd get `<second>` as the owner.
- **Fix:** Gist is I added two more sections to our compiler quirks helper in our auto-closing behavior method. It's sad but works.
- Updated tests to reflect this new scenario.
Fixes dotnet/aspnetcore#36906

Fix closing HTML elements when nested and next to others.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/AutoClosingTagOnAutoInsertProviderTest.cs

- Updated our tag auto-closing behavior detection to take into account potential parents that are without end-tag when re-typing a close-angle bracket.
- Added loads of tests!
Fixes dotnet/aspnetcore#36125

Don't auto-close when end-tag already exists.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DirectoryHelper.cs

- Catches IOException which seems(?) to be out of our control. @ryanbrandenburg please let me know if this isn't the right fix.
Fixes: 
https://github.com/dotnet/aspnetcore/issues/35306
cc @NTaylorMullen, not sure if this should go into p5 - it seems like it's fairly uncommon although we've gotten two reports already.

Catch IOException in DirectoryHelper

---

src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/TagHelperDescriptorCacheTest.cs

- The actual GetHashCode problem was fixed in dotnet/aspnetcore, but I thought I'd add a test here as well, to prevent regression.
Adds a test for https://github.com/dotnet/aspnetcore/issues/29647

Add test for TagHelperDescriptorCache

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyCodeBases.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

- Platform will be providing our LSP.Protocol binary so for the interim we'll be removing our codebase for it.
/cc @matteo-prosperi

Remove LSP.Protocol code bases / inclusion in VSIX.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsEndpointTest.cs

- The CSS diagnostic system didn't recognize the C# portions of the document and was then warning about those portions of the document. It's expected that we'd get a diagnostic in this case; however, we should be filtering HTML diagnostics that map to C# literals because they can't see the C# literals properly.
- Added a test to capture this case.
Fixes dotnet/aspnetcore#36321

Fix inaccurate HTML/CSS diagnostics on C#.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextViewConnectionListener.cs

- We're seeing some high crash rates in VS due to a crash in one of our async void methods: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1405721
- Taylor suggested this might be because of the platform trying to talk to an unknown server. Nonetheless, we should avoid async void here, and instead change the `await` call to fire-and-forget.
Fixes: 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1405721

Avoid async void method in RazorLSPTextViewConnectionListener

---

azure-pipelines.yml

- We need to switch to the new 1ES servicing pools for all servicing branches. This does that for `release/3.1`.
Tracking issue: https://github.com/dotnet/core-eng/issues/14276
cc/ @ulisesh @lpatalas

Switch to 1ES servicing pools in release/3.1

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md

Added config.yml, which should allow us to do something similar to below (screenshot taken from the aspnetcore repo):

Add issue filing link to aspnetcore repo

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/BatchingWorkQueue.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/BatchingWorkQueueTest.cs

- Turns out we weren't waiting for our background workloads to actually complete before disposing our baching work queue resulting in the possibility that dispose occurs before actually processing any items.
- Ran the test over 20k times (`Combinatorial` attribute) and didn't see a failure after the fix (saw failures pre-fix).
Fixes #4398

Fix Enqueue_DisposedPreventsRestart flaky test.

---

azure-pipelines.yml

Attempting to resolve recent issues with this build step by pinning the vsce version used to a known value.

Pin vsce version used in release script

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/scripts/retrieveDebugProxy.js

- Looks like Nuget.org started enforcing that the url to download a package be lower-case.
- This exposed that we assume the request succeeded without checking to at least log the failure when we attempted to open a `.nupkg` which was actually a 0-length file.
Fixes: https://github.com/dotnet/razor-tooling/issues/5702

Handle nuget.org API change

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/AddUsingsCSharpCodeActionResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/CSharpCodeActionResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs

- Ran into the following error when testing
```
Error: Microsoft.AspNetCore.Razor.LanguageServer.JsonRpc.RazorOmniSharpRequestInvoker: Failed to handle request codeAction/resolve:302. Unhandled exception - OmniSharp.Extensions.JsonRpc.Server.JsonRpcException: Unexpected null - line 76
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.<Returning>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at …
```

Nullable in CodeActions

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LinkedEditingRange/LinkedEditingRangeEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/LinkedEditingRange/LinkedEditingRangeEndpointTest.cs

- Add logging to `LinkedEditingRangeEndpoint` that I hope will help diagnose strange behavior in Integration tests.

Add logging to LinkedEditingRangeEndpoint

---

eng/Versions.props
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj

- Given the CI failure is impossible to reproduce locally / doesn't happen consistently this is a shot in the dark. My thought is that if we can ensure that the transient StreamJsonRpc package referenes always normalize down into one version in our .NET Framework projects via pinning that ideally we shouldn't have any issues. I only ever saw LiveShare and Remote.Razor projects have this issue via binlogs so I'm starting the StreamJsonRpc pinning here.
- Was able to remove the ExternalAccess.Razor dependency from Remote.Razor because it was brought in transitively.
Fixes #4327

Attempt to fix transient StreamJsonRpc CI failure.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs

- Our Razor language server provides component/TagHelper completions at start of words and when I originally added the completion logic to request full completion lists always I didn't consider that markup languages are a lot less "kind" to that approach. Therefore, I'm reverting that specific portion of logic + the test change that went with it.
Fixes #5685

Restrict C# forced "invoke base completion" to not apply to HTML.

---

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSource.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSourceProvider.cs
src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveAttributeCompletionSourceTest.cs

- In legacy editor's directive attribute completion we used to dismiss the active completion session to take over and show our own attribute completion. Looks like when we changed our threading model we broke the UI thread expectation of dismissing that old active session. This in turn results in a flooding of directive completion sessions.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1434858

Fix directive attribute completion in legacy Razor editor

---

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSource.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSourceProvider.cs
src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveAttributeCompletionSourceTest.cs

- In legacy editor's directive attribute completion we used to dismiss the active completion session to take over and show our own attribute completion. Looks like when we changed our threading model we broke the UI thread expectation of dismissing that old active session. This in turn results in a flooding of directive completion sessions.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1434858

[Port to release/17.0.2] Fix directive attribute completion in legacy Razor editor

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef

- This allows us to remotely configure old editor usage and only presents the feature flag in main builds for internal customers.

Add feature flag for legacy Razor editor

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs

Was investigating https://github.com/dotnet/razor-tooling/issues/5693, found it was another repro of the `InputSelect` bug (https://github.com/dotnet/razor-tooling/issues/5676) which will be fixed by https://github.com/dotnet/roslyn/issues/57465 but figured we should at least have a regression test.
I temporarily added a second formatted pass [here](https://github.com/dotnet/razor-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs#L174) and verified that the test passed.

Add failing test

---

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPDocumentSynchronizer.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/LSPDocumentSynchronizer.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/LSPProjectionProvider.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultLSPDocumentSynchronizerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorBreakpointResolverTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorProximityExpressionResolverTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProjectionProviderTest.cs

- There was a race when typing too quickly our synchronization mechanism would try and reduce the work that was done to cancel pre-existing requests. So in the scenario when you were to type `<tr` what would happen is that 3 completion requests would fire:
1. Triggered completion for `<`
2. Typing completion for `t`
3. Typing completion for `r`
Now when we sped things up we were able to process requests in parallel which meant that we could handle simultaneous requests for `<`, `t` and `r` all at the same time; however, this in turn results in an interesting behavior where if we ask for completion at `r` while `<` and `t` are still active our synchronization mechanism would aggressively cancel the older requests. For completion this is catastrohpic because it would result in a 0 length …

[Port to 17.0.2] Fix HTML completion race when typing too quickly

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs

Fixes https://github.com/dotnet/razor-tooling/issues/4451
Fixes https://github.com/dotnet/razor-tooling/issues/4284
Previously when remapping edits for formatting we would bail if the start or end of the edit couldn't be mapped. For things at the start of a code block, however, the C# formatter returned an edit that our source mapping was in the middle of. Rather that dropping that edit completely, we now try to map just the last line of the edit so that we can at least fix up the indentation of the first line.
This should allow us to revert https://github.com/dotnet/razor-tooling/pull/2637, or at least remove the `IsFunctionBlock` method, but there aren't end-to-end tests of code actions that I could see, where the actual edits are verified. Logged …

Map the last line of edits

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef

- This feature flag already exists in the release/17.0.2 branch.
- This allows us to remotely configure old editor usage and only presents the feature flag in main builds for internal customers.

Port feature flag to main

---

eng/Versions.props
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultFallbackCapabilitiesFilterResolver.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultFallbackCapabilitiesFilterResolverTest.cs

This required updating the VS protocol assemblies to 17.1.2, as that was
where this method name was introduced (though it's been in the LSP spec
for a long time).

Add a capability check for textDocument/documentColor

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MonitorProjectConfigurationFilePathEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MonitorProjectConfigurationFilePathEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationStateSynchronizerTest.cs

- After digging through countless customer logs I've had a hell of a time finding out why Debug/Release project.razor.json's occasionally result in lack of component IntelliSense. This PR introduces logging to key points that will help investigate what's going on with #5757.
- We have two entry points on the Razor language server that deal with project.razor.json. These two are the `MonitorProjectConfigurationFilePathEndpoint` which is responsible for monitoring external project.razor.json locations (if you set your obj directory to something outside of the workspace) and the `ProjectConfigurationStateSynchronizer` which listens to `project.razor.json` file changes and then harvests information and pushes it to our language server project manager.
- For these two I enabled nullability + …

Add better logging around project.razor.json handling.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef

- This allows us to remotely configure old editor usage and only presents the feature flag in main builds for internal customers.

[Port to main] Add feature flag for legacy Razor editor

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/CSharpCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingPassBase.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeActionFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs

This is an alternative to https://github.com/dotnet/razor-tooling/pull/5752
It completely fixes https://github.com/dotnet/razor-tooling/issues/5747
It completely fixes https://github.com/dotnet/razor-tooling/issues/5675
Let me know what you think... it's probably not what you expect...

Allow code actions to add code above a C# block, no matter the directive

---

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPDocumentSynchronizer.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/LSPDocumentSynchronizer.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPProjectionProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/LSPProjectionProvider.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultLSPDocumentSynchronizerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorBreakpointResolverTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorProximityExpressionResolverTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProjectionProviderTest.cs

- There was a race when typing too quickly our synchronization mechanism would try and reduce the work that was done to cancel pre-existing requests. So in the scenario when you were to type `<tr` what would happen is that 3 completion requests would fire:
1. Triggered completion for `<`
2. Typing completion for `t`
3. Typing completion for `r`
Now when we sped things up we were able to process requests in parallel which meant that we could handle simultaneous requests for `<`, `t` and `r` all at the same time; however, this in turn results in an interesting behavior where if we ask for completion at `r` while `<` and `t` are still active our synchronization mechanism would aggressively cancel the older requests. For completion this is catastrohpic because it would result in a 0 length …

Fix HTML completion race when typing too quickly

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeActionFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingEndpointTest.cs

This is almost a draft, because I did most of it during Friday Social Hour on Saturday morning, but at the same time it does work so ¯\\\_(ツ)_/¯
~Includes https://github.com/dotnet/razor-tooling/pull/5753 so just review https://github.com/dotnet/razor-tooling/commit/271e4bbdea88068b0f43b906a8f9e73fa4bc4e12 and https://github.com/dotnet/razor-tooling/commit/26379f036f487c471b0c52ea8547eb1eeccb6dc5~ See note below
In theory this would allow us to get rid of our custom add using code action stuff.

Automatically add using directives from code actions etc.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs

Fixes https://github.com/dotnet/razor-tooling/issues/5731
Imagine if I hadn't done the array initializer bug first!

Don't format multi-line string literals

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs

- In the past there were various opt-outs to force the .NET Core editor in non-.NET Core scenarios. When we moved to the LSP editor we lost some of these capabilities. This changeset re-adds a similar functionality.
- Code provided by @CZEMacLeod, for context see: https://github.com/dotnet/roslyn/discussions/54068

Add project capability opt-out to use legacy Razor editor.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/VisualStudioEditorDocumentManager.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1441597
@mgoertz-msft I wasn't actually able to reproduce the issue in the work item but not calling Advise on a background thread is ultimately the right thing to do. Therefore, pushing this codechange given the comments in the associated issue

Call AdviseRunningDocTableEvents on UI thread.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MonitorProjectConfigurationFilePathEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MonitorProjectConfigurationFilePathEndpointTest.cs

- So turns out for customers who have moved their `obj` folders out of the solution directory (common for larger apps and done via the MSBuild `BaseIntermediateOutputPath` or `IntermediateOutputPath` property) and then published their app would break our ability to consume future Razor component / project system information. Turns out the `obj` folder + publish combo breaks due to a blatant bug in our `project.razor.json` change detection mechanism. Let me explain: Whenever a project has an `obj` outside of the workspace directory we need to notify the RZLS where to look for said `obj` folder so it can detect `project.razor.json` changes. We do this via a custom endpoint (`razor/monitorProjectConfigurationFilePath`) which takes in a csproj + `project.razor.json` path. So when a user would …

Fix publish from breaking Razor component discovery.

---

src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/package.json
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/yarn.lock

- Upgrade our grammar test yarn packages so they don't bring in vulnerable packages anymore.
Addresses:
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/5469395?typeId=6437374
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/5469396?typeId=6437374
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/6063418?typeId=6437374
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/6063419?typeId=6437374
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/6063420?typeId=6437374

Fix component governance issues in our grammar tests.

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.tmTheme

- Disable colorization for C# classifications because they are "bleeding" in some cases.
Temporary fix for https://github.com/dotnet/razor-tooling/issues/5614 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1426196/. Long term fix is that colors should be explicitly defined for default classifications and then this should be reverted.

Disable C# classification from TextMate

---

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/VisualStudioEditorDocumentManager.cs

This reverts commit 1f785f416ceb72b632a0568353b16c8a4fc433f9.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1447620

Revert "Call AdviseRunningDocTableEvents on UI thread. (#5783)"

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props
eng/common/sdl/packages.config
eng/common/templates/job/execute-sdl.yml
eng/common/tools.sh
global.json
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks.csproj
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Microsoft.AspNetCore.Razor.LanguageServer.Common.csproj
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyBindingRedirects.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common.csproj
src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/Microsoft.CodeAnalysis.Remote.Razor.Test.csproj
src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Microsoft.VisualStudio.Editor.Razor.Test.csproj
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Microsoft.VisualStudio.LanguageServices.Razor.Test.csproj
src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Microsoft.VisualStudio.LiveShare.Razor.Test.csproj

Changes were breaking RPS ngen (see https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/368226) and should be removed from the Preview 2 branch.

Remove compiler + arcade changes from 17.1-Preview2 branch

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs

If a SelectionRange is provided it's required that the range
should also be mapped correctly before sending off the request
for code actions. This context is used for cases where code action
ordering is ordered and the original range may not actually be
equal to the SelectionRange. Both are needed to correctly provide
the right code fixes and/or refactorings and in the right order
from Roslyn
- Map SelectionRange when available
Fixes:  #5822

Map SelectionRange for CodeActions requests

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Debugging/DefaultRazorBreakpointResolver.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorBreakpointResolverTest.cs

- Razor files generate code in a "loosely" debuggable way. For instance if you were to do the following in a cshtml file: `@DateTime.Now` it would render as:
```C#
#line 123 "C:/path/to/abc.cshtml"
__o = DateTime.Now;
#line default
```
This in turn results in a breakpoint span encompassing `|__o = DateTime.Now;|`. Problem is that if we're doing "strict" mapping Razor only maps `DateTime.Now` so mapping would fail because C# also sees the `__o` portion. Therefore in cshtml scenarios we can fall back to inclusive mapping which allows C# mappings that intersect to be acceptable mapping locations.
In Blazor this isn't an issue because `@DateTime.Now` renders as:
```C#
__o =
#line 123 "C:/path/to/abc.razor"
DateTime.Now
#line default
;
```
- To avoid mocking more of the world in our …

Allow implicit expression breakpoints for CSHTML files.

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json

- Update Blazor debugging extension to download 6.0 runtime
- Update Blazor debugging extension to use latest NuGet package
Fixes: https://github.com/dotnet/razor-tooling/issues/5780

Update runtime/package versions for Blazor debugging

---

eng/Versions.props
src/Razor/src/Directory.Build.props
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectWorkspaceStateGenerator.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/BatchingWorkQueueTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/Microsoft.CodeAnalysis.Remote.Razor.Test.csproj
src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Microsoft.VisualStudio.LiveShare.Razor.Test.csproj

- Unpinned Nerdbank.Streams since it seemed that our restore graph already encompassed coherent nerdbank versions, we were the only ones causing issues.
- Pinned Microsoft.VisualStudio.Threading to 17.0.63 (this is what core editor is pinning too) to avoid all of the various incoherent versions from transient packages floating around. This in turn upgraded some threading analyzers which I had to react to as well.
Fixes #5717

Fix CI package restore flakiness (hopefully).

---

eng/Tools.props

- Last attempt at fixing yarn looks like it brought forward another yarn issue. Hopefully this time fixes all of the component governance pain points?
Fixes
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/6199209?typeId=6437627
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/6199210?typeId=6437627
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/6199211?typeId=6437627

Upgrade yarn source build tools to 122.10

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperServiceTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/RazorDefinitionEndpointTest.cs

Fixes https://github.com/dotnet/razor-tooling/issues/5856

Support going to the definition of a property attribute directly

---

azure-pipelines.yml
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/package.json
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/infrastructure/TokenizedContentProvider.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tsconfig.json
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/yarn.lock

- We're currently pinned to 2019
- vscode-textmate@4.4.0 depended on oniguruma, which depends on node-gyp to find a version of VS to use for C++ compilation at build-time. BUT the version of node-gyp being used doesn't know about VS2022. Upgrading node-gyp causes a ton of problems. Thankfully the latest versions of vscode-textmate dropped the oniguruma dependency, so by moving to 6.0.0 we can hopefully avoid trouble.
Fixes:

Use VS2022

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/BlazorDebugProxy/README.md
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/README.dev.md
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/README.md
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/scripts/retrieveDebugProxy.js
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/src/acquireDotnetInstall.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/src/extension.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/yarn.lock
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/src/extension.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/yarn.lock
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/TerminateDebugHandler.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/CodeActions/RazorCodeActionRunner.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServerClient.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/tsconfig.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/yarn.lock
src/Razor/src/rzls/Program.cs
src/Razor/src/rzls/rzls.csproj

- Fixes Blazor WASM debugging issues (https://github.com/dotnet/aspnetcore/issues/38382)
- Upgrades yarn packages
- General refactoring
Fixes: https://github.com/dotnet/aspnetcore/issues/38382

Blazor WASM Debug Proxy Updates

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormattingPass.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingPass.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/RazorOnAutoInsertProviderTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingContentValidationPassTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingDiagnosticValidationPassTest.cs

This doesn't quite go as far as I'd like, but I thought I'd stop here in the interests of making the review not too hard, and this is definitely the "big hitters" in terms of wasted effort. This only saves about ~10% of time in formatting, which is not huge, but the indentation and formatting spans were previously being thrown out 33% of the time for each formatting operation, so its objectively wasteful. Caching the workspace would be a little bit of an additional gain, but not as much as you'd think, so I've left it off. I'd rather clean things up so that we properly dispose it properly at the same time, which would make this PR annoying
Review commit by commit and it should be pretty simple and straightforward.

Lazy load, and clean up, portions of FormattingContext

---

src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/IRemoteTagHelperProviderService.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/OOPTagHelperResolver.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteTagHelperDeltaProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteTagHelperProviderService.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/TagHelperDeltaResult.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/TagHelperResultCache.cs
src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/OOPTagHelperResolverTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/RemoteTagHelperDeltaProviderTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/TagHelperDeltaResultTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/TagHelperDescriptorTestBase.cs

- We were getting hit pretty hard in serialization & deserialization paths in our TagHelper resolution endpoints. After investigation it looks like every keystroke will kick off resolution requests every 1 second. While this may seem "too frequent" it actually enables us to provide better TagHelper detection/colorization/error states so keeping a frequent polling approach is still a goal. Therefore I designed a path to reduce the amount of data that's passed back & forth between VS & the Roslyn service hub processes. The gist is that we now have a delta result which the client & server both understand. That result has an `Added`, `Removed`, `ResultId` and `Delta` parameter. First two are self explanatory, `ResultId` represents an "id" that a client needs to keep track of (inspired by LSP) …

Make TagHelper resolution delta based

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Html/HtmlTagCompletionProvider.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/yarn.lock

- Get TextDocument from vscode-languageserver-textdocument, rather than from the deprecated version in vscode-languageserver-types
- Explicitly install vscode-languageserver-textdocument as a dependency to control its versioning
Fixes: 
A deprecation warning I noticed while working on #5767. The TextDocument from vscode-languageserver-textdocument is a drop-in replacement, and I've tested it against omnisharp-vscode and confirmed tag completion is still working.
I've also added it as a dependency in package.json so that its versioning isn't at the whim of vscode-html-languageservice's transitive dependency.

Use vscode-languageserver-textdocument

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs

- We had logic to shrink completion `TextEdit`'s  potential impact area to the current completion word; however, turns out this wasn't a great route. If a `TextEdit` does not expand past the boundaries of the current word then there's no reason to use a `TextEdit`, `InsertText` would suffice. Meaning, every time a completion item utilized `TextEdit`s we'd almost always do the wrong thing. In this case URL completion in HTML scenarios would almost always expand past the word boundary because you'd go from `~/css/parent` => `~/css` when selecting the `..` (up one folder) item. They also replaced entire spans for sub-folder logic as well.
- In testing I didn't see anything fall over from this change. If anything things work better now :), turns out there were no tests!
Fixes …

Remove TextEdit translation safety checks on completion.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPDocumentSynchronizer.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDiagnosticsTranslator.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/HTMLCSharpLanguageServerLogHubLoggerProvider.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HandlerTestBase.cs

- First problem: LoggerProvider might not have been initialized when opening a plain `.html` file.
- Second problem: In some Scenarios WebTools calls our virtual document synchronizer with an already expired CancellationToken. This can cause us to throw an exception when we try to operate on it. I've modified the code to harden us against that scenario and alerted WebTools to the scenario.
Fixes: https://github.com/dotnet/razor-tooling/issues/5924

Fix HTML scenarios

---

src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/Directory.Build.props
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/README.md
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap

- Re-generate the snapshot used for VS Code grammar tests
- [Added] Run grammar tests as a part of `cibuild` / `build --test`
Fixes:
This:
```
Snapshot Summary
› 116 snapshots failed from 1 test suite. Inspect your code changes or run `yarn test -u` to update them.
Test Suites: 1 failed, 1 total
Tests:       116 failed, 166 passed, 282 total
Snapshots:   116 failed, 166 passed, 282 total
Time:        3.529s
Ran all test suites.
```
Most of the changes were either adding missing trailing whitespace (I suspect someone manually saved the file with "Trim Trailing Whitespace" enabled) or adding `source.cs` from #3602.
I have a feeling these tests aren't being run by CI...
Addendum - turns out this was because the grammar test project included its own Directory.Build.props that didn't include …

Re-generate VS Code grammar tests

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultProjectConfigurationFilePathStore.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultProjectConfigurationFilePathStoreTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/ProjectRazorJsonPublisherTest.cs

- Issue was that when a user specifies a `BaseIntermediateOutputPath` utilizing relative directories we get a configuration file path that looks something like `C:\path\to\project\..\project.razor.json`. Once resolved the path becomes `C:\path\to\project.razor.json` which is hugely different because the "resolved" path lies outside of the workspace directory (outside of the `project` dir) which means it requires different handling from our language server. Prior to this our language server would see this relative path and then think it's within the workspace dir and then choose not to separately monitor it resulting in failure of IntelliSense.
- Updated tests.
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1456312

Fix relative `obj` folder paths from breakign Razor.

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultHtmlFactsService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs

Fixes: https://github.com/dotnet/razor-tooling/issues/4363
**Before:**
**After:**
By the way, it's a bit confusing, that functionality of `DefaultHtmlFactsService`, which is located in `Microsoft.CodeAnalysis.Razor.Workspace`, is tested in `Microsoft.AspNetCore.Razor.LanguageServer.Test`🤨

Fixed hover display on tag helpers end tag

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/CodeBlock.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap

- Syntax-highlight self-closing components
So, the one-line fix that I didn't spot until looking over my final diff is technically just
```diff
diff --git a/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml b/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml
index 7a4e6dd9d..c6b03c274 100644
--- a/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml
+++ b/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml
@@ -109,7 +109,7 @@ repository:
- include: '#balanced-open-close-tag-start'
- include: '#balanced-open-close-tag-end'
- include: '#balanced-open-close-tag-body'
-    end: (?<=(</\1>))|(/>)
+    end: …
```

Properly syntax highlight self-closing components

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingDiagnosticValidationPass.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs

Fixes https://github.com/dotnet/razor-tooling/issues/5732

Allow diagnostics to move around due to formatting

---

eng/pipelines/test-integration-job.yml

- AzDo will not allow you to have a space in the name, so we must remove them.

Fix naming

---

.github/CODEOWNERS

Capture cases like https://github.com/dotnet/razor-tooling/pull/6000.

Expanding CODEOWNERS to include BlazorWASMDebuggingExtension

---

azure-pipelines.yml
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/LICENSE.txt
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/yarn.lock

- This is mostly just a copy of https://github.com/dotnet/razor-tooling/pull/6013#pullrequestreview-864129837 to get around the fork restrictions for testing the fixes here.

Fail CI if packaging Blazor WASM Debuggin Extension fails

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6002

Indent @section blocks

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/CodeActionExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/RazorCodeAction.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/RazorCodeActionPriorityLevel.cs

- Updating our Razor representation of code actions to allow latest VS concepts so when / if sub-languages utilize them we respect it.
- This is pre-requisite work to providing our own telemetry IDs on code actions.
-  Utilized file-scoped namespaces so viewing the diff here with whitespace changes off would be best.
Part of #4899

Update Razor CodeActions to allow latest light bulb capabilities.

---

eng/Versions.props
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlineCompletion/InlineCompletionEndPoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlineCompletion/InlineCompletionRequest.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs

- Uses document options from client and passes them to C# to retrieve the razor formatted snippet text.
Tested

Pass formatting options in snippets

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj

Turns out these were necessary (esp. the addin, addin name and version)
Without these, we're getting:
```
WARNING: The add-in 'Microsoft.VisualStudio.WebTools.WebEditors,17.0' could not be updated because some of its dependencies are missing or not compatible:
missing: Microsoft.VisualStudio.Mac.RazorAddin,17.0
```

Bring back VSMac addin assembly attributes

---

eng/Versions.props
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/src/extension.ts
src/Razor/test/Directory.Build.props
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.Test.ComponentShim/Microsoft.AspNetCore.Razor.Test.ComponentShim.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version1_X/Microsoft.AspNetCore.Razor.Test.MvcShim.Version1_X.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version2_X/Microsoft.AspNetCore.Razor.Test.MvcShim.Version2_X.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim/Microsoft.AspNetCore.Razor.Test.MvcShim.csproj

- Since Razor utilizes a global.json that restricts what SDK is used this conflicts with the test runner who expects net6.0 to be available. Migrating our test projects to net6.0 resolves the ability to run tests in VS & at command line while simultaneously making everything faster :smile:.
- Also moved rzls (VSCode language server) to net6.0 because it was darn easy and didn't require much extra work!
Fixes #5904

Fix ability to run tests in VS & on command line.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionProviderHelper.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/AddUsingsCSharpCodeActionResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/TypeAccessibilityCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/CodeActionExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/RazorCodeActionFactory.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/AddUsingsCodeActionProviderFactoryTest.cs

- This changeset adds unique telemetry IDs for each of our light bulbs. It also includes changing the VSCode representation of our light bulbs for consistencies-sake.
- Made a singular "code action factory" which owns all `new RazorCodeAction(...)` creations so it can stamp telemetry IDs onto them.
- Updated the existing `AddUsingsCodeActionProviderFactory` to be a `Helper` to help distinguish a singular factory for code actions.
Final part of #4899

Add telemetry identifiers for Razor light bulbs.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsEndpoint.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultHtmlFactsService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs

- The gist of this changeset is that we should never expect an element syntax to have a `StartTag` (whether it's an HTML or TagHelper element). Reason being is that the compiler wraps incomplete tags like `</div>` in its own HTML element which means start tags are `null`.
- Added a test for this scenario and went through all of our `StartTag` access and added protections across the board.
Fixes #6096

Fix NRE at completion time on incomplete elements.

---

Directory.Build.targets
eng/Version.Details.xml
eng/Versions.props
global.json
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionProviderHelper.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorComponentSearchEngine.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RazorComponentRenameEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorComponentSearchEngineTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorDocumentMappingServiceTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RazorComponentRenameEndpointTest.cs
src/Razor/test/testapps/Directory.Build.targets

@wtgodbe pointed out that `Microsoft.AspNetCore.Testing` isn't actually a dependency here, which is causing issues with the darc subscription.

Fix Dependency Tree, Update Dependencies & Consume `TrySplitNamespace` Breaking Change

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TagHelperResolver.cs

- This changeset should not be ported to VS windows.
- The gist of what this changeset is doing is that at TagHelper resolution time, right before we return results, we call into a compiler utility method that will populate a cache in the TagHelperDescriptor. This cache is known tohave concurrency issues that result in VS4Mac crashing. Therefore to avoid this we pre-populate that cache before any concurrency scenario can happen.
Tactical fix of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1468241

Tactically fix caching compiler issue at TagHelper resolution times

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/SemanticTokensCache.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokensCacheTest.cs

- Added logging to our semantic tokens logic. It would likely be helpful to add even more logging, but since we're currently inundated with tons of range requests this would likely create unnecessary noise. Due to this, I only added logging for uncommon cases that we aren't expected to hit often.

Add logging to semantic tokens

---

.gitignore
azure-pipelines.yml
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/BlazorDebugProxy/README.md
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/scripts/retrieveDebugProxy.js
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/src/extension.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/yarn.lock

There's not too many changes overall, so feel free to look at the diff directly. If you want a more detailed breakdown:
- 56c4fba...fe2a54c are the changes that directly address #6020. Everything else is optional and can be rolled back/moved to separate PRs based on feedback.
- 504dd69 adds caching, so that local development doesn't hit the network more than is necessary.
- 504dd69...d6396da (and later on, 047a345 and d283659) is just miscellaneous code cleanup.
- 026aaa1 makes the script fail fast if any part of the download/copy operation fails. This should prevent the script from succeeding even if the download fails - something I think is desirable so that the extension isn't accidentally shipped without a proxy.
There are some more script improvements that can be made if the Node …

Retrieve BlazorDebugProxy on build

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs

- Reverts "Allow C# completion in middle of words." This reverts commit 55f03ed4387b69199c1c6b1edaef85c1f7defc62.
- Ultimately this changeset brings the C# completion experience back to 17.0-GA behavior. We initially did this changeset because there were super rare circumstances in which completion could come up incorrectly.  Turns out this ended up breaking a few other non-trivial C# cases like doc comment typing.
- Given we haven't had any feedback in 17.1 or 17.0 regarding completion in middle or start of words we'll bring things back to consistency with the core C# experience.
Fixes #6126

Restrict 24/7 typing C# completions to start of word.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/RazorSemanticTokensEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/SemanticTokensCache.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs

- @ryanbrandenburg and I discovered this bug while verifying semantic tokens yesterday:
- This is because of an error in the caching logic. After this fix, I verified we only return token-ints divisible by 5. Also changed the logic to operate on full tokens instead of individual ints based on Ryan's recommendation.
- We lack tests in this area (still in progress), but tests will be added after the C# LSP server is integrated with Razor tests.
EDIT: Probably best to view changes with whitespace turned off

Fix caching logic in semantic tokens endpoint

---

eng/pipelines/test-integration-job.yml

- Change all "Publish" steps to skip if previous steps were cancelled.
Fixes: https://github.com/dotnet/razor-tooling/issues/6138
As suggested by @sharwell.
CC @JoeRobich who maintains the Roslyn version of this.

Don't run publish steps if previous steps were cancelled

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/CompletionItemExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/OptimizedCompletionList.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/OptimizedVSCompletionList.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/VSCommitCharacter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/VSCompletionItem.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/VSCompletionList.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemExtensions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/VSCompletionListTest.cs

- The overwrite section of this won't work broadly until the relevant VS commits are fully merged. I've tested some builds of it t though and it did work.
- Start returning snippets like `<attribute>="$0"` for TagHelper/Component Attribute completion.
- We also need HTML LSP to react this for a consistent experience.
Fixes part of https://github.com/dotnet/razor-tooling/issues/4436.

Attribute snippet

---

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/MessageInterception/InterceptionMiddleLayer.cs

- Fixes a silly mistake passing the request instead of the response to the MessageInterceptor

Correctly pass the response to the request interceptor

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/mpack/addin.info

- This publishes all language server and dependent language server information to our MPack. Technically this shouljd be the last change for VS4Mac compatibility.
Fixes #6038
/cc @KirillOsenkov / @gundermanc this should be the last changeset for getting Razor compatible for VS4Mac. I haven't actually tested this bit end-to-end so we may want to sit down and see if everything is good once this gets merged.

Add Language Server binaries to MPack.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionProviderHelper.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/AddUsingsCSharpCodeActionResolver.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/AddUsingsCSharpCodeActionResolverTest.cs

This works around a bug where the edits returned by C# may not be well structured.  Proper solution is tracked by https://github.com/dotnet/razor-tooling/issues/6159 (the ability for Razor to apply arbitrary C# edits).
If anyone asks, I blame Taylor for making me write this.
Note - this hack is already present in the actual code action endpoint as well - https://github.com/dotnet/razor-tooling/commit/034f6fe9c31e0d5d9679b489a3362de765a08a02#diff-0be4ed27bb2b83f2a3854b8612e1c9b8d1779a500984a97102d074a6afec2f70R200
- Uses code action title to retrieve the appropriate using to add
- Stops calling C# to resolve as we would literally just throw away everything resolved anyway.
Fixes: 
https://github.com/dotnet/roslyn/issues/58091

Use code action title instead of resolving edits for add usings. 

---

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/TextBufferProjectService.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Editor/DefaultTextBufferProjectService.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/Editor/DefaultTextBufferProjectService.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLSPEditorFeatureDetector.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacProjectCapabilityResolver.cs
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Properties/_Manifest.addin.xml
src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/VisualStudioMacLSPEditorFeatureDetectorTest.cs

- The LSP editor feature detector is the key component in the system that decides "should we turn on the LSP editor". Therefore we have to make a VS4mac specific version of the detector because the project types are different (`DotNetProject` instead of `IVsHierarchy`) and the settings / feature flags are different.
- Added a feature switch for the VS4Mac LSP editor. This doesn't come with UI because adding UI has to be done in the VSMac platform itself + is an entirely different system (preview features). To unblock our inability to add UI / preview features the feature switch should enable us to turn on the new editor. Once we get the green light to add a preview feature we'll add the UI / understanding.
- Updated the existing `TextBufferProjectService` to understand resolving a …

Add VS4Mac LSP Editor feature detector.

---

eng/Versions.props
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/TextBufferProjectService.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Editor/DefaultTextBufferProjectService.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLSPEditorFeatureDetector.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/Editor/DefaultTextBufferProjectService.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLSPEditorFeatureDetector.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacProjectCapabilityResolver.cs
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Properties/_Manifest.addin.xml
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/VisualStudioWindowsLSPEditorFeatureDetectorTest.cs
src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/VisualStudioMacLSPEditorFeatureDetectorTest.cs

- The old `DefaultLSPEditorFeatureDetector` was bound to windows (read VS win settings, feature flags, UI Contexts, depended on LiveShare) so I moved it to the windows specific binary and renamed it to be windows specific. I plan to implement a VSMac equivalent in a follow up.
- Had to add some new project dependencies to the windows assembly because oddly the LSP.Implementation assembly that's platform agnostic has VSwindows specific transitive dependencies.
Part of #6038

Move LSP editor feature detector to windows specific assembly.

---

eng/Versions.props
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/AggregateProjectCapabilityResolver.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/ProjectCapabilityResolver.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/TextBufferProjectService.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Editor/DefaultTextBufferProjectService.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLSPEditorFeatureDetector.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsProjectCapabilityResolver.cs
src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/LiveShareProjectCapabilityResolver.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/Editor/DefaultTextBufferProjectService.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLSPEditorFeatureDetector.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacProjectCapabilityResolver.cs
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Properties/_Manifest.addin.xml
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/VisualStudioWindowsLSPEditorFeatureDetectorTest.cs
src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/VisualStudioMacLSPEditorFeatureDetectorTest.cs

- LiveShare is the only project capability resolver that actually requires documents and I didn't want to put the expectation on all capability resolution mechanisms to require documents. Therefore I added a new overload of the `HasCapability` check that only requires a project.
- In VS4Mac landscape we also don't need document file paths so this also sets us up for being able to resolve capabilities there.
Part of #6038

Add ability to resolve capabilities for projects without document.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MonitorProjectConfigurationFilePathEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeEventArgs.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.cs
src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DefaultProjectChangePublisher.cs
src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectManager.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Serialization/TagHelperDescriptorJsonConverter.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/VSLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/ProjectRazorJsonPublisher.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/FallbackRazorProjectHost.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MonitorProjectConfigurationFilePathEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationFileChangeDetectorTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestLanguageServerFeatureOptions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/MSBuildProjectManagerTest.cs

- Prior to this when VSCode + VS were open simultaneously both IDes would fight for ownership over the project.razor.json file which would break colorization, diagnostics, basically everything IntelliSense related.
- To make the language server use a new file format I expanded the existing language server feature options to include a project configuration file name.
- Updated existing references to project.razor.json in product code to use "configuration file" instead of anything specific.
- All integration tests would fail gloriously if this part of the system fell over so we get testing for free here :).
Fixes #5764

Use project.razor.vs.json in VS scenario to avoid clashes.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorProjectServiceTest.cs

- Turns out whenever we used to "realize" project state and we wanted to promote Razor documents from the MISC project to actual projects we'd always leave behind a copy of the existing Razor file in the MISC project state. This means we'd never see that file get invalidated in caches (it was never removed) and any invalid state associated with it could potentially stick around. That combined with many parts of Razor's sub-system operating on a project or document affinity could result in chaos. For instance in our components if a document affinitized component notices a document change it then invalidates its state; similarly if a project affinitized component notices a project change it invalidates its state. The problem this issue resulted in is that document affinitized components …

Migrate documents from MISC projects on config updates.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultWindowsRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/FallbackWindowsRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultDotNetProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultMacRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/FallbackMacRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/MacRazorProjectHostBase.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultWindowsRazorProjectHostTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackWindowsRazorProjectHostTest.cs
src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/ProjectSystem/DefaultMacRazorProjectHostTest.cs
src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/ProjectSystem/FallbackMacRazorProjectHostTest.cs

- Added `Windows` / `Mac` verbiage to each of our project system hooks to ensure they don't get confused with each other. I kept running into situations where i'd do Ctrl + T, search for `DefaultRazorProjectHost` and 9 times out of 10 would select the mac one when I wanted the windows one. Did it enough times where I decided to just make the verbiage change.

Update Visual Studio project system hook names (mac/win)

---

eng/pipelines/test-integration-job.yml

- This step is unnecessary since Screenshots get included in `Publish Logs`.
- Since the folder doesn't ever exist the step gives a warning, making the run yellow instead of green.

Remove Unneeded publish step

---

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultWindowsRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/FallbackWindowsRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultDotNetProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultMacRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DotNetProjectHostFactory.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/FallbackMacRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/MacRazorProjectHostBase.cs
src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/DefaultDotNetProjectHostTest.cs
src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/TestProjectConfigurationFilePathStore.cs
src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/TestVSLanguageServerFeatureOptions.cs

- Added the ability to extract the intermediate output path in VS4Mac scenarios which is in turn used to inform the language server on where project configuration files (project.razor.vs.json) exist when they're outside of the normal workspace directory.
- Updated test(s).
Part of #6038

Add support for external project config files in VS4Mac.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs

- Basically for MVC scenarios we were returning completions which were getting converted into snippets, but didn't re-constitute their CommitCharacters.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1501302

Fix Completion of Markup Attributes in MVC scenarios

---

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorUIContextManager.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsRazorUIContextManager.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacRazorUIContextManager.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs

- The classical UIContextManager requires shell APIs to operate, those don't exist in VS4Mac but more importantly UIContext's in general don't exist in VS4Mac land.
- Moved the `RazorUIContextManager` to the Editor.Razor layer and created a Windows / Mac implementation in the corresponding impl dlls.
Part of #6038

Make RazorUIContextManager no-op in Mac scenarios.

---

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Logging/RazorLogHubTraceProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/HTMLCSharpLanguageServerLogHubLoggerProviderFactory.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLoggerProviderFactoryBase.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/RazorLanguageServerLogHubLoggerProviderFactory.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/VisualStudioWindowsLogHubTraceProvider.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/Logging/VisualStudioMacLogHubTraceProvider.cs

- The LSP client LogHub tech used to be tied to windows  due to how the LogHub bits were acquired. I moved that component to have a win/mac separate impl.
- There's now a shared "RazorLogHubTraceProvider" at the core VS.Editor layer (platform agnostic VS). Hopefully we get LogHub in VS4Mac eventually!
Part of #6038

Tease LogHub dependencies apart in VS4Mac.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/AutoClosingTagOnAutoInsertProviderTest.cs

- When there were multiple TagHelpers applying to the same tag auto-closing behaviors weren't always defined because we'd allow `Unspecified` auto-closing behaviors to override values. The changeset here doesn't allow `Unspecified` TagHelpers to take ownership of auot-closing behavior.
- This was found when digging into why WebTools CTI tests weren't working correctly. I don't think their tests actually test the new editor but trying to replicate behaviors resulted in this bug.
- Added a test case.
Fixes #6217

Fix conflicting TagHelper auto-close behaviors.

---

azure-pipelines.yml
eng/CIBuild.cmd
eng/pipelines/test-integration-job.yml
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/OnEnterRulesTests.cs

- A previous commit marked our VSIX as something to be deployed to the "hive" on build, but now we need to organize the ci build in such as way that it can be actually used.
- Since we don't have the VSIX build available during the "Build" step I had to split the tests and integration tests out into their own step. I prefer this anyway since it gives a better idea of if the BUILD or the TESTS failed before looking more into specifics.
- The tests that I un-skipped should fail if the VSIX isn't being deployed properly because the changes to language-config.json haven't been inserted into VS yet.
Fixes: https://github.com/dotnet/razor-tooling/issues/6198

Fix VSIX deployment in build.cmd scenairos

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6211

Fix extra indent with CascadingTypeParameter when the type parameter is specified

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorContentTypeChangeListener.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorContentTypeChangeListenerTest.cs

- `RazorContentTypeChangeListener`: We never used the shell API
- `RazorLanguageServerClient`: Codespaces is no longer a thing so we don't need to worry about detecting it.
Part of #6038

Remove unneeded shell APIs from LanguageServerClient assembly.

---

eng/Versions.props
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Extensions/IVsTextViewExtensions.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/OutputInProcess.cs

- This allows you to capture the Output from the `Razor Language Server Client` Output pane. No current usage of it, but I confirmed that it worked so I thought I'd preserve the impl. Would be good to include in the test failure Logs once https://github.com/microsoft/vs-extension-testing/issues/112 is answered/done.
Fixes:
CC @sharwell who figured out a chain that could get us the contents even though the GUID is random.

Add output pane capture

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Serialization/CompletionListSerializationBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerTagHelperCompletionService.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LegacyTagHelperCompletionService.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Properties/AssemblyInfo.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperServiceTestBase.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/LanguageServerTagHelperCompletionServiceTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/LegacyTagHelperCompletionServiceTest.cs

- We've been updating the usage of our TagHelper completion APIs to properly pass current HTML tag & parent HTML tags. The problem is the legacy editor still passes the old information and therefore we ended up breaking t his experience in two commits:
- https://github.com/dotnet/razor-tooling/commit/658e2db05d0daa9326356ee1edc85cd3d1b970c4
- https://github.com/dotnet/razor-tooling/commit/43167a25c1ada2977630f82ab016cbf8c8eaecd9
- Instead of making the existing TagHelperCompletion work for both new and old-world I decided to fork the legacy / language server implementations so the old world would get fixed while the new world continued to reap the benefits. To do this we now have a Legacy and LanguageServer fork of the compeltion service. The legacy version has the problematic versions of …

Fix Legacy Razor editor TagHelper completion regression.

---

azure-pipelines.yml
eng/pipelines/test-integration-job.yml

- We weren't signing VSIX components leading to failures at VS insertion time. Passing the `-sign` parameter should be enough to get us back into a working state.
Fixes #6234

Sign VSIX components

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Debugging/RazorBreakpointSpanEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/DocumentUriExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/UriExtensions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Extensions/UriExtensions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/UriExtensionsTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test.csproj
src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/UriExtensionsTest.cs

- Gist of the issue is that we would sometimes double decode paths. For example, a solution with the name `file+path` would be double decoded into `file path`. This is similar to the issue Ryan fixed last year in this PR: https://github.com/dotnet/razor-tooling/pull/4136. There are two `UriExtensions` classes and only one was fixed up in the linked PR. This PR fixes the other extensions class.
- Double decoding was also occurring separately in our C# semantic tokens logic which prevented C# semantic tokens from lighting up.
- There is an edge case I found where a solution that contains both a space _and_ `+` in its name seems to fail to get any language server functionality whatsoever. This seems to be a more complicated problem but is also likely a pretty rare occurrence. Due to this, I …

Allow solutions with `+` in name to operate correctly in C#

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj

- Technically the `Microsoft.VisualStudio.LanguageServer.ContainedLanguage.dll` is also a duplicate BUT we'll want to take ownership of inserting this given we build its content.
- Context: https://github.com/xamarin/vsmac/pull/6484

Remove duplicate DLLs from Razor's mpack.

---

azure-pipelines.yml
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs

- Firstly let's set the Log creator code a bit higher up the stack.
- Secondly lets make sure to collect the data out of the "Screenshots" directory in the case of Release build Integration Test failure.
Fixes: https://github.com/dotnet/razor-tooling/issues/6252

Return Integration Test data from Release failures

---

azure-pipelines.yml
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Microsoft.VisualStudio.Razor.IntegrationTests.csproj
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/OnTypeFormattingTests.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/xunit.runner.json

- We can leverage the existing `-hang-dump` infra in dotnet test to capture dumps when we go past a certain timeframe. 4 minutes is where the HangMitigatingCancellationToken should fail, so lets use that.
Fixes: https://github.com/dotnet/razor-tooling/issues/6249
CC @sharwell

Capture hang dumps for Integration tests

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj

- It already exists in the VSMac world. Context: https://github.com/xamarin/vsmac/pull/6172#issuecomment-1097185780
Part of #6038

Remove `Microsoft.Extensions.Logging.dll` from our MPack.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/RazorDisableDropHandlerProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/RazorVisualStudioWindowsConstants.cs

- For details as to why this is VS windows specific see the comment on `RazorDisableDropHandlerProvider`:
```C#
// The intention of this class is to disable dropping random files into the Razor language service content type without throwing. Ultimately
// this class serves as a workaround to a limitation in the core editor APIs where without it you get an error dialog. This class allows us
// to silently "do nothing" when a drop occurs on one of our documents.
```
- Migrated the project item constant from the LSP constants into the VS windows specific constants file.
- Updated the name of our drop handler to indicate that it's disabling drop support specifically (for a workaround).
- There's no counterpart to this in the VS4Mac land because ultimately this drop support is only there as a …

Move drop handling workaround into VS win specific dll.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/RazorSyntaxTreeExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/TestFiles/Expected/FormatDocument.cshtml

Fixes https://github.com/dotnet/razor-tooling/issues/6110
This is one of those weird situations where the fix is too easy and makes me question everything, though it's possible formatting explicit C# statements used to not work well, and other fixes have meant that things are fine now.
Essentially what was happening was HTML formatting was removing all of the indentation, and then since C# formatting skipped them, you ended up with everything in a neat line like in the screenshot in the issue.

Format explicit C# statements

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml.cs

I broke this when making sure temp files were cleaned up, hence its all Ryan's fault.
~Tagging is still broken, must be one of my changes for RPS, but I don't know why, and I don't want to regress RPS accidentally so will have to work it out.~ It was just a bad MEF cache

Fix document opening in dev tools

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Properties/_Manifest.addin.xml
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/mpack/addin.info

- This removes the following assemblies from the manifest:
- Microsoft.Extensions.Logging.dll
- Microsoft.Extensions.Logging.Abstractions.dll
- System.IO.Pipelines.dll
- System.Reactive.dll
- System.Runtime.CompilerServices.Unsafe.dll
- System.Threading.Channels.dll
- These seemed to cause errors at runtime.
Part of #6038

Remove VS4Mac shipped dependencies from manifest.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/FoldingRangeEndpoint.cs

When a folding range is collapsed, it uses the offset character to
determine where to put the "...". We want to make sure some text is
showing to indicate what actually is being folded. Modify the range so
that it's at the end of the start line always (ignoring whitespace).

Fix folding display

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionResolveEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionResolveEndpointTest.cs

- When playing with the completion stack I felt that resolve / providing was becoming a bit unweidly and concerns were bleeding across the domain. Therefore I went ahead and split the resolve / provide endpoints apart so the logic is kept separately. This is similar to how we have code actions today as well.
- Also split tests and updated accordingly.
- Ended up needing to promote our completion list cache into a service so both endpoints could interact with the same completion list cache without relying on member state.

Split completion resolve / providing into separate endpoints.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MappingBehavior.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorDocumentMappingServiceTest.cs

- In this changeset I went ahead and experimented with a new diagnostic translation approach that I call "inferred". The general idea is that when we encounter diagnostics that aren't in mappable regions / we can't derive where they came from to then attempt to give customers a general idea on where diagnostics are coming from. This means we'll highlight larger diagnostic regions in the document to help guide customers towards problem areas instead of hiding diagnostics entirely. When playing around with this tech I found that we more often than not could show higher quality + significantly more diagnostics to customers without being too noisy.
- One thing to keep in mind, in an "ideal" world we'd know where all diagnostics came from, aka a SyntaxNode generated X generated Code which …

Add "inferred" remapping support to allow for more diagnostics.

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyBindingRedirects.cs

- In our last VS insertion I had to do manual ngen updates to ensure our binaries were ngening. I made a woopsie and added an ngen binding redirect to solve an ngen load ambiguity. This was a mistake because I also needed to add that binding redirect to our extension so at runtime the right assembly resolved. Our integration tests didn't catch this failure because WebTools also offers the same assembly so instead of barfing our world would use theirs if it couldn't find the right version and things would just work; however, once ngen'd that world expects that the correct assembly exists at the expected location.
- Fix is to add a binding redirect for MS.Extensions.Options at runtime
Fixes #6310 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1528365

Fix Razor MS.Extensions.Options load failure.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/TypeAccessibilityCodeActionProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/TypeAccessibilityCodeActionProviderTest.cs

- Found that we'd provide the FQN directive for single line directives and then upon formatting we'd bail because we can't accurately format single line directives. At first I tried digging into why we couldn't format them and turns out the C# formatter returns some really odd edits to us in terms of proper formatting. Once we build in the tech for fully formatting single line directives in the Razor context (ignore what C# tells us) this should enable us to build a good experience around this. For now disabling FQN cleans up what we provide to users.
- Added a test to validate
Fixes #6015

Restrict FQN C# code action from appearing in single line directives.

---

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/EditorDocumentManagerListener.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorTextViewConnectionListener.cs

- This is a contained fix to address a deadlock plagueing RPS tests on VS shutdown (it'd hang). See the associated issue for context.
- This is a partial revert of https://github.com/dotnet/razor-tooling/commit/cb467896550c867281e87a75c35b9313006ec77b
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1529381

Fix VS deadlock on shutdown.

---

azure-pipelines.yml

https://github.com/dotnet/razor-tooling/pull/6298 upgrades the version of Roslyn and other packages. Unfortunately the integration tests run against the latest preview, so the changes from the upgraded packages aren't in the integration machines yet. We should temporarily disable the integration tests until the next preview image is released. @ryanbrandenburg is also planning on investigating what a longer-term solution looks like.

Disable integration tests

---

Directory.Build.props

What do people think about turning this on? For many things it already seems to be on on the CI and I think generally it'd be good practice if we avoided warnings.
Fixes: My constant annoying mistakes.

Turn on warnings as errors

---

azure-pipelines.yml
eng/pipelines/test-integration-job.yml
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/README.md

- We want our integration tests to fail if we're not running against the experimental instance we've just built. It's surprisingly difficult to tell this, but we can at least ensure that the proper Extension has been deployed (to the LocalAppData directory).
- This WON'T protect us from using an OLD experimental instance, we only know that we're using AN experimental instance. This means we need to worry about:
- Dev-box pollution. This mostly shouldn't be a problem since most devs run Integration tests from VS (which seems to always deploy) or not at all.
- Test machine pollution. Basically as above but for test machines.

Vsix deploy

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DirectiveAttributeTransitionCompletionItemProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionResolveEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/MarkupTransitionCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCommitCharacter.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionContext.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItem.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionOptions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs

- The new `RazorCommitCharacter` construct allows us to specify whether or not to insert the commit character on insert. Unfortunately this PR doesn't go alllll the way and remove the hacked code to inject VS commit characters onto our O# completion items yet (that's coming).
- Updated call sites to take in the new Razor commit character construct
- Added a new `RazorCompletionOptions` record struct that can indicate when snippest are supported. In all relevant scenarios they are; however, in the legacy editor they're not so we need an option to know if we should use snippet based commit characters or non-snippet based commit characters.
Fixes #6339

Add VS "like" commit characters to Razor's completion item.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/ProvideSemanticTokensResponse.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokenTestBase.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs

- Should have been removed as part of https://github.com/dotnet/razor-tooling/pull/6298, but found some leftover references while working in the repo. Since both Razor + Roslyn have implemented semanticTokens/refresh, isFinalized is no longer necessary since C# will notify us automatically when their semantic model is finalized.

Remove leftover semantic tokens isFinalized references

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItem.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs

- We now provide the ability to indicate of a Razor completion items `InsertText` is a snippet.
- With this changeset we can remove some of our pre-existing hack logic on trying to detect minimized or unminimized attributes and instead utilize our new `IsSnippet` tech.
- In updating the RazorCompletionEndpoint to respect the new insert text format that we pass through our system I also found some mishaps in FilterText that I corrected as well. These were exposed by tests.
- Updated existing tests to respect when snippets come from completion items.
- Added new tests to validate snippets
Fixes #6341

Add "IsSnippet" understanding to Razor completion item.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/ClientCapabilitiesExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/PlatformAgnosticClientCapabilities.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Serialization/ICaptureJson.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Serialization/PlatformExtensionConverter.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Extensions/ClientCapabilitiesExtensionsTest.cs

- Prior to this I hadn't realized that we were only capturing VS items that were specifically "overloaded" in our "Platform agnostic XYZ" types. This meant that when we were trying to inspect other items on the client capability collection we'd fail to understand them because O# would see the initialize request, deserialize into their own ClientCapabilities at which point all data representing VS' would be lost. To overcome this I created a new `ICaptureJson` type that informs our platform extension converters to maintain the JToken representation of objects.
- Updated our test to be pretty exhaustive to ensure we're capturing all information.
Part of #6328

Properly capture all VS client capabilities.

---

src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLSPEditorFeatureDetector.cs

- This was preventing the LSP editor from turning itself on because there's no CPS in VS4Mac land.

Don't require CPS on VSMac.

---

src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteTagHelperDeltaProvider.cs
src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/RemoteTagHelperDeltaProviderTest.cs

- Prior to this what would happen is when folks would request TagHelpers we'd be incrementing a wholistic "result" value for every cached item. This means if you had 3 projects A, B and C we'd cache all 3 the very first time they were requested. The second time they were requested, we'd similarly say "we hit the cache but we'd then provide a different resultId (the wrong one) depending on the current wholistic "resultId". This means on the third time requesting TagHelpers it'd request A, B and C with resultId NEW at which point all woudl fail to hit the cache resulting in us not returning a delta result. This in turn would wreck serialization perf on devenv and on the service hub sides. This change ensure that we have a near 100% cache hit rate to prevent devenv and service hub from …

Re-use result IDs when calculating TagHelpers (prevent misses).

---

eng/Versions.props
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultEditorSettingsManager.cs
src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultEditorSettingsManagerTest.cs

When editor settings (use tabs, tab size) change store the updated values to Roslyn's global options.
This will allow us to remove `IRazorDocumentOptionsService` in future.
Requires https://github.com/dotnet/roslyn/pull/61054

Set Roslyn's global line formatting options

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CSharpStatementBlockOnTypeFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingTest.cs

More C# 11 goodness.
Sorry, there is no good way to review this.
In case you weren't aware, raw string literals don't include whitespace that appears at the start of each line, up until the point where the end `"""` starts, which means all of these changes don't actually change the contents of the strings*. Visual Studio also draws a vertical line so its easy to see the true content. And of course, we can use quotes in strings without needing to escape them, which is cool.
Vertical line looks like:
\* with the exception of some whitespace before and after, but that was always annoying that we had to include that to make the tests look okay.

Use raw string literals for formatting tests

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6401
This is quite the targetted fix but I don't think there is anything else we can do about here until we move completely off the "work out indentation based on generated C#" model, or get the compiler to add another source mapping at the end of a `@section` block. Might try the latter when the compiler is in this repo ¯\\\_(ツ)_/¯
Best thing is probably to advise people to put `@section` directives last :)

Use a known indentation where possible because it might be better than nothing

---

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Microsoft.VisualStudio.Editor.Razor.csproj

- We pin the version of `Microsoft.VisualStudio.LanguageServer.Protocol` used by `Microsoft.VisualStudio.Editor.Razor` to be the same as the one used by the Implementation of this class to avoid assembly load problems.
Fixes: https://github.com/dotnet/razor-tooling/issues/6408
Do we want to explicitly call out why this reference was added?

Pin Microsoft.VS.LS.Protocol to avoid assembly mismatch

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsEndpoint.cs

Noticed this while testing out Semantic Tokens perf
1. Open a reasonably large razor file. Make it bigger by copy and pasting the parts of it that won't cause an error continuously.
2. Hold down Ctrl+z so it removes all the stuff you just added.
3. Check out the Razor Language Server Client log in the Output pane. You should eventually see a null-ref pertaining to this line.
My solution then is to fix the only null-ref issue from that function by accounting for the fact that sometimes we have null owners. @NTaylorMullen I don't know much about diagnostics, but this seems to generally match what we do for the other `Is...` methods in this file.

Handle null-ref

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/RazorSemanticTokensLegend.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Semantic/RazorSemanticTokensTests.cs

- Saw a random failure that seemed to be caused by not waiting for the whole TagHelper context to load. Gonna wait for that and see if it helps.

Wait for all Classifications

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/DefaultRazorHoverInfoService.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs

- Use a cast instead of pattern matching with a `!` to make sure that if there is a problem we get useful error messages.
Responding to feedback from @davidwengier on https://github.com/dotnet/razor-tooling/pull/6414.

Cast non-nullable instances instead of using !

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/DidChangeTextDocumentParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/DidCloseTextDocumentParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/DidOpenTextDocumentParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/DidSaveTextDocumentParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IVSDidChangeTextDocumentEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IVSDidCloseTextDocumentEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IVSDidOpenTextDocumentEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IVSDidSaveTextDocumentEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IVSTextDocumentSyncHandler.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentSynchronizationEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDocumentSynchronizationEndpointTest.cs

- Move the TextDocumentSync Endpoint to VS Contracts
Fixes: https://github.com/dotnet/razor-tooling/issues/6366

Move DocumentSync to VSContracts

---

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultWindowsRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/FallbackWindowsRazorProjectHost.cs

- Turns out that my last change for single server completion broke our project system integration hooks. Gist is that in the single server completion support changeset I had to fork our language server feature options into a VSWin/VSMac equivalent; however, I didn't make the proper reaction in our project system hooks to represent that "forking" (to import the base type instead of the top-level type).

Fix VSMain integration tests.

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Serialization/CompletionListSerializationBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DirectiveAttributeTransitionCompletionItemProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DefaultRazorCompletionFactsService.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeParameterCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/MarkupTransitionCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionContext.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionFactsService.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemProvider.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSource.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveCompletionSource.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DirectiveAttributeTransitionCompletionItemProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DefaultRazorCompletionFactsServiceTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeParameterCompletionItemProviderTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/MarkupTransitionCompletionItemProviderTest.cs

- This is pre-requisite work for building centralized aggregation systems. The gist is to pre-compute as much data as possible and in the midst of prototyping the work I found that completion was a significant offender in this area.
- One hugely positive impact of this will be that we wont need to re-resolve owners for SyntaxTrees (not always cheap) at completion time.
- Updated tests and all call sites to no longer compute owners / absolute indexes and instead rely on the contexts.
Part of #6432

Don't re-resolve SyntaxNode owners for every completion handler.

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Serialization/CompletionListSerializationBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/AggregateCompletionItemResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/AggregateCompletionListProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/CompletionItemResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/CompletionListCache.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/CompletionListMerger.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/CompletionListOptimizer.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionResolveEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionItemResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionListProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionResolveEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/VSInternalCompletionItemExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/VSInternalCompletionListExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/CompletionListCacheTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/CompletionListOptimizerTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/LegacyRazorCompletionResolveEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionItemResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionResolveEndpointTest.cs

- This is the pre-requisite for allowing our completion resolve endpoint to provide both Razor & delegated (HTML/C#) completion resolution. Some of the key bits in this changeset are:
- Ability to locate originating completion lists from an item that was present from a "merged" completion list. Since we added the support to merge completion lists we needed the opposite support to `Split` completion list info back out. This way we can ask specific resolvers "can you resolve this item given it came from X originating completion list?".
- A re-envisioning of our `CompletionListCache` to better support future scenarios. Now the cache stores the originating LSP completion list and some generic "context" object. In legacy / Razor scenarios this context object is the Razor completion item list; …

Add support for multiple completion  item resolvers.

---

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/FeedbackLogging.cs

- Manually collect the MEF logs from the hive because the one collected by Feedback seems to only be for the main part of VS.
- Also fail on test initialize if we have Razor errors in the MEF cache. This makes sure we fail fast and that the error is exposed early.
Fixes: https://github.com/dotnet/razor-tooling/issues/6439

Mef logging

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedCompletionParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionListProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/RazorSyntaxTreeExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorLanguageEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestDocumentContext.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestOmnisharpLanguageServer.cs

- This changeset adds a delegated completion list provider that will invoke down into our custom message target and then into a HTML/C# language server to resolve completion items. In practice this code only really powers HTML completions because C# completion lists come back with edit ranges (not yet supported) which end up informing the client to not show C# completions.  Ultimately the code in this changeset just "invokes" C#/HTML and returns the response as-is. The response rewriting tech that exists in the completion handler is not in yet. I will bring that forward in a subsequent PR
- For many of our delegation calls we'll need to have the host document version associated with the host document. LSP has a type that represents this already, it's the `VersionedTextDocumentIdentifier`. …

Add support for requesting basic C#/HTML completions

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/TextEditResponseRewriter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/ResponseRewriterTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/TestDelegatedCompletionListProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/TextEditResponseRewriterTest.cs

- This changeset lifts the TextEdit rewriting tech that we have in the `CompletionHandler` into its own response rewriter to bring back to life C# completions so the client doesn't throw them out.
- Note that this doesn't yet bring back to life provisional C# completions. That's tracked by #6450
- Expanded testing to enable easy testing for response rewriters
- Added tests
Part of #6448

Add support for TextEdit rewriting (C# completion)

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionListProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionResponseRewriter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/TextEditResponseRewriter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/ResponseRewriterTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/TestDelegatedCompletionListProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/TextEditResponseRewriterTest.cs

- This introduces a new concept `DelegatedCompletionResponseRewriter` that allows completion lists to be "rewritten" prior to returning them from our delegation completion list provider.
- Ultimately this will be used to remove preselection, design time items and even rewrite text edit ranges for completion lists (in follow up PRs).
- Added a test to validate ordering.
Part of #6448

Add support for delegated response rewriters.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/DidChangeConfigurationParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IDidChangeConfigurationEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRazorLanguageQueryHandler.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRazorMapToDocumentEditsHandler.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRazorMapToDocumentRangesHandler.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorConfigurationEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorConfigurationEndpointTest.cs

- Move IDidChangeConfigurationHandler to VS Contracts
Fixes: https://github.com/dotnet/razor-tooling/issues/6369

Move IDidChangeConfigurationEndpoint to VS Contracts

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentColor/DocumentColorEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/DocumentColorParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IDocumentColorEndpoint.cs

- Move DocumentColorEndpoint to VS Contracts
Fixes: https://github.com/dotnet/razor-tooling/issues/6385

Move DocumentColorEndpoint to VS Contracts

---

eng/Versions.props
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj

- This is a speculative attempt to resolve some build inconsistency we've been seeing with RPC.Contracts. The idea is that the PrivateAssets setting here might be leading to a race condition.

Remove PrivateAssets

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/LinkedEditingRange/ILinkedEditingRangeEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/LinkedEditingRange/LinkedEditingRangeParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/LinePositionSpanExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LinkedEditingRange/LinkedEditingRangeEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/LinkedEditingRange/LinkedEditingRangeEndpointTest.cs

- Move `ILinkedEditingRangeHandler` to VS Contracts.
Fixes: https://github.com/dotnet/razor-tooling/issues/6379

Vs contracts linked editing range

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6191

Allow templates to stay on a single line in on type formatting

---

eng/Versions.props
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/FoldingRangeEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/RazorCodeBlockFoldingProvider.cs

- Forwards collapsed text for FoldingRange if it's provided by Roslyn or HTML
- Adds CollapsedText for our own implementations
- If no CollapsedText is found, fall back to old behavior of modifying the start to be the end of the line

Add collapsed text usage in Razor

---

azure-pipelines-integration-dartlab.yml

As part of the work to roll them out broadly, DartLab's templates were refactored to enable scenarios for more teams. Updating this pipeline to use the new agent template.
Updating DartLab pipeline to use the agent template.
Fixes:

Update DartLab pipeline to use new agent template

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DesignTimeHelperResponseRewriter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DesignTimeHelperResponseRewriterTest.cs

- This changeset includes the logic to strip C# design time helpers from the C# completion list before returning them to clients.
- The logic on "when" to remove helpers is a direct copy from the pre-existing `CompletionHandler`
- Added tests to validate the behavior
Part of #6448

Remove design time helpers from delegated completion.

---

eng/Versions.props
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Microsoft.AspNetCore.Razor.LanguageServer.Test.csproj

- We keep seeing on CI builds that VisualStudio.RpcContracts gets mismatched due to transient versioning issues. For some reason this is a flakey issue and not consistent. To workaround the flakiness I'm pinning all of our RpcContract bits.

Fix RpcContracts package flakiness.

---

azure-pipelines-integration-dartlab.yml

When branch names contain `/` the Build.SourceBranchName variable only includes the last part of the branch name. Build.SourceBranch includes the entire branch name.
Port of this Roslyn change https://github.com/dotnet/roslyn/pull/61821

Use the complete branch name in DartLab yml

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedCompletionParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionListProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/VisualStudioTextChange.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs

- This adds a new way to enable provisional completion via a single server. The route I took was to enable a `ProvisionalTextEdit` to be provided along side the delegation params that is applied then reverted before / after requesting completions.
- Expanded the `DelegatedCompletionListProvider` to detect provisional completion scenarios and then build a corresponding `TextEdit`. Ultimately this logic is identical to the existing `CompletionHandler` logic with the one exception that it doesn't actually apply the text edit (it returns it to the client to apply).
- Updated the `ProvideCompletionListAsync` message target logic to allow understanding of provisional text edits and to apply / revert them as expected. Currently the revert logic can only work for single line provisional text …

Add support for provisional completions to single server completion.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedCompletionItemResolveParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedCompletionResolutionContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionItemResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionListProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/TestDelegatedCompletionListProvider.cs

- Added a`DelegatedCompletionItemResolver` that understands how to resolve items producted from the `DelegatedCompletionListProvider`.
- Added a new `DelegatedCompletionResolutionContext` that's cached along side the delegated completion lists. This is what's used by the resolve to properly delegated item resolutions.
- Added tests for new delegated completion item resolution.
Fixes #6449

Add support for delegated completion item resolutions.

---

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/OnTypeFormattingTests.cs

This reverts commit b0300dbd51418e522462ac976c4896d8ac7d0ee5.
- Unfortunately looks like this test still fails 😢 /cc @davidwengier

Revert "Enable test" for TypeScript test.

---

src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj

- In the latest binlog failure it was complaining about our LiveShare project. Turns out my last attempt to fix this I actually had locally the LiveShare csproj edited locally but never saved. This makes more sense. Gotta fix em all!

Yet another attempt at fixing RpcContract errors.

---

eng/Versions.props
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Properties/_Manifest.addin.xml
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/mpack/addin.info

VS Mac 17.3 has breaking API changes which require its app compat
being changed to 17.3.

Update Razor addin version to 17.3

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6522

Return minimal edits from ontype formatting, and validate

---

eng/Versions.props
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPSpanMappingService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/CSharpTestLspServerHelpers.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/Extensions/ExportProviderExtensions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/RoslynTestCompositions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestRazorDocumentServiceProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokenTestBase.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/RenameHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/SignatureHelpHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorLSPSpanMappingServiceTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestLSPRequestInvoker.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestRazorLSPSpanMappingService.cs

- Un-mocks all but one rename test to use the C# LSP server. The one remaining mocked test is testing the HTML language server.
- Rename tests were a bit more complicated to move over since we had to update the test workspace to take in the correct HostServices. This is because `IEditorInlineRenameService` (which Roslyn rename utilizes) lives in the Roslyn EditorFeatures layer and is not a default workspace language service.
Part of https://github.com/dotnet/razor-tooling/issues/6263

Update rename tests to use C# LSP server

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/CSharpTestLspServerHelpers.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_CSharp_Explicit.semantic.txt
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_CodeDirectiveBodyAsync.semantic.txt
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_ComponentAttributeAsync.semantic.txt
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_DoNotColorNonTagHelpersAsync.semantic.txt
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_MultiLineCommentMidlineAsync.semantic.txt
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_NestedTextDirectives.semantic.txt
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_NestedTransitions.semantic.txt
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_UsingDirective.semantic.txt
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentHighlightHandlerTest.cs

- Previously, we weren't passing in any metadata references when creating our C# test workspace. That meant our workspace wouldn't have any of the default dlls, e.g. `System`.
- Now that we're properly passing in the metadata references, some of the existing semantic token test outputs had to be updated.
- While updating the semantic tokens tests, I went ahead and converted all the tests to use raw string literals. I also added a helper method to calculate the range so we don't need to do it manually every time. 
Part of https://github.com/dotnet/razor-tooling/issues/6263

Import metadata references to C# test workspace

---

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultFormattingOptionsProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/HTMLCSharpLanguageServerLogHubLoggerProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/CSharpTestLspServerHelpers.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultFormattingOptionsProviderTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorBreakpointResolverTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Debugging/DefaultRazorProximityExpressionResolverTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionResolveHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPDiagnosticsTranslatorTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPDocumentMappingProviderTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentHighlightHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentPullDiagnosticsHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/FindAllReferencesHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/GoToDefinitionHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/GoToImplementationHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HandlerTestBase.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/RenameHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/IsExternalInit.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test.csproj
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorHtmlPublishDiagnosticsInterceptorTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestDocumentManager.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestLSPDocumentMappingProvider.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestLoggerProvider.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestTextStructureNavigatorSelectorService.cs

- Moves the C# completion resolve tests from using Moq infrastructure to calling into a C# LSP test server
- Some of the tests were no longer relevant (each explained below), so those were removed. The C# server utilizes a cache on their side for completion items so we're only able to test realistic scenarios.
Part of https://github.com/dotnet/razor-tooling/issues/6263

Update completion resolve tests to use C# LSP server

---

.github/fabricbot.json

- We can no longer update our FabricBot configuration directly (see https://github.com/dotnet/razor-tooling/pull/6543 for details). This PR updates our configuration for 17.4 P1.

Update FabricBot configuration for 17.4 P1

---

azure-pipelines.yml
eng/restore-internal-tools.yml

-
restore-internal-tools.yml should not be under eng/common it should be under eng folder, as eng/common folder gets overwritten everytime the repo gets an arcade update
Fixes:

Update restore-internal-tools.yml path 

---

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/RazorLSPTextViewConnectionListener.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6564
I was intrigued...
Before:
After:

Use auto-indenting word wrap

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

- These are already shipped by VS.
Fixes #6405

Remove duplicate assemblies from extension install.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs

Fixes: https://github.com/dotnet/razor-tooling/issues/6134

Fixed explicit completions invocation for tag helper attributes

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef

- We're flighting "true" to all internal users in 17.3 builds; however, for 17.4 we're going to be on-by-default so we have an entire release to catch and address issues. If this ends up being a problem we can remotely  turn it off OR we can physically swap the switch.
Fixes #6421

Set default value for single sever completion to "true"

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/BreakpointSpanTests.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/FormatDocumentTests.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/TestFiles/Expected/FormatSelection.cshtml
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Classification.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Semantic/RazorSemanticTokensTests.cs

- Originally found in this Integration test CI failure: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6414782&view=results
- This ended up revealing a few issues:
1. Prior to this changeset formatting tests would wait for folding ranges to be available before attempting to format anything. In the above CI failure those checks timed out and the screenshots included also showed that no folding ranges were available. This indicates there might be a secondary issue where folding ranges ar ea little flakey. I've filed [this](https://github.com/dotnet/razor-tooling/issues/6592) to track re-enabling code folding tests and moved our existing formatting tests off of folding ranges being available to waiting for semantic classifications
2. With the introduction of …

Fix formatting tests that test markup after directive body.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WrapWithTag/WrapWithTagEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/WrapWithTag/WrapWithTagEndpointTests.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6596

Only return minimal text edits if we get back a tilde from the Html LSP server

---

NuGet.config

Fixes the CI build
FYI @epananth though it's worth noting that package source mapping wasn't enabled when you added the internal tools stuff, so not a problem that this broke, but thought you might like to know. Is it possible to add a package source mapping to the `nuget.config` file that is in `eng/common` to prevent this affecting other teams, if they adopt package source mapping?

Add package source mapping for internal tools

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultDocumentSnapshot.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultImportDocumentSnapshot.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentSnapshot.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DefaultDocumentSnapshotTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateGeneratedOutputTest.cs

- On its surface having a C#/HTML output version seems appealing; however, in practice we've never used it because the `SourceText` that stores the output already versions this information. Also, when digging through the code I found that every time we'd parse a file we'd aggressively be generating the C#/HTML docs (even when we don't need it) and simultaneously we'd also be doing massive string equals checks to try and understand versioning. This changeset removes all of that.
- Updated tests to remove the C#/HTML output checks because they no longer exist
- Made `DocumentState` nullable enabled.
Done as part of #6043 although it technically could stand on its own.

Remove C# and Html output versioning.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeDocumentReferenceHolder.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeDocumentReferenceHolderTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DefaultDocumentSnapshotTest.cs

- This changeset changes how our `DocumentSnapshot` system caches its output. Previous it relied on a secondary system to dig deep into a `DocumentSnapshot`, extract its "generate output task" and then hold onto a reference of that. In this change I expand `DocumentState` to be "code document reference aware"; meaning, if someone is referencing the generated output then the output is maintained so we don't need to re-parse / compute data. Ultimately this ends up bringing our new system back into par with our existing perf and even surpassing it in quick typing scenarios (multiple document states flowing simultaneously).
- With this changeset and some rudimentary testing I saw a 10% reduction in overall cache misses compared to what exists today while also maintaining simplicity.
- Added …

Cache generated output as long as CodeDocument is referenced.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6578

Allow minimized attribute completions anywhere in the attribute

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionListProvider.cs

- Expanded trigger characters to include a space for TagHelper completion
- Missed this originally when enabling single server completion!
Fixes #6601

Allow TagHelper completions to show up when typing space.

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/CSharpTestLspServerHelpers.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs

- Updated C# portions of our delegated completion list provider tests to utilze the real C# server and simplified the testing model.
- Maintained a lot of pre-existing tests because we don't have similar capabilities for HTML
- These tests will be more widely used upon completion of #6618 where we'll want to resolve text edits (this is a leadup).
Part of #6618

Migrate delegated completion list resolver tests to use C# server.

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs

- The original `CSharp_Operator_Triggered` test was an incorrect scenario. For instance, C# doesn't typically trigger completions off of typing `(`. Instead I migrated the test to do a `DateTime.` variant with `.` being the trigger. The only catch then was that our generated C# document did not contain `using System` so I had to update our generated code document bits to properly generate the using statement.
Part of #6618

Unskip completion list provider test.

---

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioMacDocumentInfoFactory.cs

- Not sure why we originally were changing the file extension of our generated documents to not include the Razor file extension. This aligns LSP's understanding of file paths with the dynamic file info understanding. Given how much tribal knowledge / convention is baked into the `.g.cs` ending we should probably build a factory; however, getting that factory to work across all products (VS, VSCode, VSMac) is less than simple. For now here's the quick fix.

Fix Razor's C# doc population into the workspace.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionItemResolver.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestDocumentSnapshot.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestProjectSnapshot.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingLanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorDocumentOnTypeFormattingEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorDocumentRangeFormattingEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestRazorFormattingService.cs

- Migrated our old `CompletionResolutionHandler` logic for post-processing C# completion items to our new single server completion system.
- One current gap is that the old system used to lookup active formatting options on the client to understand if snippets should be formatted with/without tabs etc. For now I'm using defaults but in a follow up PR i'll light up the real formatting options acquisition logic.
- As part of this PR there were several pieces of code that could be re-used so I refactored them out. The `TestRazorFormattingService` is a prime example (especially now that completion resolve depends on it).
- Did a few updates to the API so it was clear what type of formatting service you'd be getting (aka should it be HTML enabled?).
- Added a test that validates that we get …

Add support for remapping TextEdits & AdditionalTextEdits at resolve time.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionItemResolver.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultFormattingOptionsProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/FormattingOptionsProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultFormattingOptionsProviderTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionResolveHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestFormattingOptionsProvider.cs

- This is the final part to #6618 to enable completion resolve to acquire formatting options for complex text edits so it can properly format text edits
- We now expose a new endpoint on the client under `razor/formatting/options` that will return the most recent understanding of formatting options
- To make this possible updated the `FormattingOptionsProvider` API to take a `Uri` instead of a document snapshot.
- Updated tests accordingly
Final part of #6618

Add support for acquiring formatting options from client.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/LanguageServerConstants.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionItemResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultFormattingOptionsProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/FormattingOptionsProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestDocumentSnapshot.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestProjectSnapshot.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingLanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorDocumentOnTypeFormattingEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorDocumentRangeFormattingEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestRazorFormattingService.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultFormattingOptionsProviderTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionResolveHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestFormattingOptionsProvider.cs

- Prior to this C# snippets were wrapped/unwrapped at the endpoint layer. This means anyone trying to format a snippet would need to manually wrap/unwrap their own snippets. The logic fit well into the existing formatting service so I migrated the logic there.
- Another aspect of this that's a little disconnected is that when applying formatted snippet edits I found that edits wouldn't get "minimialized" prior to collapsing which would result in unminified edits returning to the client. At completion time (what I will eventually be doing as part of #6618) this was highly troublesome because completion is sensitive to the "end of the edit" area. Meaning if you complete `await` and the await has a complex text edit that gets formatted the `t` in `await` needs to be the absolute last thing …

Fix `FormatSnippetAsync` to properly format C# snippets.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/ExtractToCodeBehindCodeActionParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionResolver.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionResolverTest.cs

In extract to code behind, there are cases where the setup is not fully ready for the compiler to accurately generate a namespace. Luckily they provide a public extension point to get the namespace for a document, which handles fallback behavior and failure. Use that in the action provider to determine if a namespace is accurately available. If it is, fill the action params with that namespace and use for generating the code rather than recalculating it again. 
Fixes #4441

Fix Extract To Code Behind Produces "__GeneratedComponent" Namespace

---

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/BreakpointSpanTests.cs

- 17.3-P1 has shipped and is widely available.
Fixes #6280

Unskip SetBreakpoint_FirstCharacter_InvalidLine.

---

src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/MacRazorProjectHostBase.cs

- Turns out project system interactions on mac still use windows style paths. Meaning, if we query MSBuild for information like the `obj` directory we'll get the path back with `\`. These paths then explode when passed to normal .NET APIs. This fix translates all MSBuild / local file system interactions to utilize `/` on Macs.
- Unfortunately due to the MonoDevelop APIs these sections can't be properly tested without extensive re-work. This was already the precedent so #yolo

Fix project.razor.json generation on Mac.

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

- Turns out these are required for ngen: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/413012
This reverts commit 47badc17ac8f5e98cd45c71e496345e6d4333a4e.

Revert "Remove duplicate assemblies from extension install. (#6508)"

---

eng/MPack.targets
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Properties/_Manifest.addin.xml

- Update TextMate information for VSMac.
- Added new MSBuild goop to copy VSWin's TextMate pieces into VSMac's addin.
- As part of this I had to update our mpack generator to respect a sub-folder indicator.

Add TextMate information to VSMac Addin.

---

.github/fabricbot.json

- Updates FabricBot for 17.4 P2.
- Also makes FabricBot slightly smarter so instead of moving everything to the "To-do" project column when added to a milestone, the column is chosen based on who the issue is assigned to.
- Also closes PR tagger generated issues automatically since the PR tagger is now working.

Update FabricBot for 17.4 P2

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/mpack/addin.info

This should allow using the TextMate extension point.

Mac: Add Addin dependency on TextEditor

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj

Follow-up to https://github.com/dotnet/razor-tooling/pull/6663.

Actually add MonoDevelop.TextEditor dependency

---

Directory.Build.props

- Arcade by default does the right thing supposedly for projects & publishing symbols. We were holistically swapping debug types / setting if we should publish windows pdbs. Arcade now supports all of this by default so this is an attempt at resolving #6239 in hopes that arcade does the right thing.

Publish symbols with default arcade settings.

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj

- Turns out on the CI creating an mpack was only including the Razor grammar and not our sub-grammars. That in-turn lead to our mpack lacking C#, HTML, CSS, JavaScript etc. grammars. This changeset goes from including grammars in the Addin output (doesn't have any impact) to directly including the grammars in the MPack file.

Fix VSMack embedded grammars inclusion on CI

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionListProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionListProvierTest.cs

- When typing out Razor directives we previously had a check that straight up outruled any deletion based interaction at completion time. This resulted in funky behavior when folks would accidentally mis-type a directive -> delete -> try to fix. That funky behavior would be an empty completion liset (see below for before gif).
- This fix makes our completion engine respect the `TriggerForIncompleteCompletions` even if it's on delete. This aligns with what C# does and because HTML doesn't currently offer incomplete completions doesn't really impact component completions; although if they ever end up going down that path we'll work as expected.
- Added a test for this scenario.
- This doesn't entirely fix the below associated issue, just one aspect of it. It's still possible for a …

Fix directive completions on deletion for incomplete sessions.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/AggregateCompletionListProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/AggregateCompletionListProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs

- Removed all error handling logic from our aggregate completion list provider. The motivator behind this change is that we want to properly "fail" in the case that completion explodes so we can capture that information in LogHub logs, telemetry and anything else sub-systems use those exceptions for. Effectively we don't want to hide issues.
- A side effect of not swallowing exceptions means if C#/HTML throws then we also wont provide Razor completions. This is desirable because it'll mean that we're at the very least not providing super partial information to the user. i.e. imagine only getting a list of Razor directives in your completion list after typing `@`. That list probably isn't very valuable and portrays unreliability.
/cc @mikadumont & @ryzngard this may negatively impact our …

Don't swallow exceptions during completion.

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultRazorDynamicFileInfoProvider.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorDynamicFileInfoProviderTest.cs

- Turns out that after one would rename a component there was a race that could occur where that component would be ejected from the C# compilation until close/reopen. This race was introduced in several different ways over the past year; however, it's primarily due to us trying not to leak memory on solution close. When we originally fixed https://github.com/dotnet/razor-tooling/issues/4703 we aggressively also added "document removed" mechanics to our cleanup mechanisms. We later then introduced the "solution is closing" path which accomplishes the same thing. Turns out that because we had a document remove mechanic built in what would happen is a user would rename a document which would enqueue a "document removed" on our project snapshot manager dispatcher thread while simultaneously …

Fix component IntelliSense after rename.

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs

When delegating to C#/HTML hover was using the rename method name....
</shame>

Fix the method name for HoverAsync

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionResolveEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionItemResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionListProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItem.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemKind.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources.resx
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.cs.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.de.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.es.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.fr.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.it.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.ja.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.ko.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.pl.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.pt-BR.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.ru.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.tr.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.zh-Hans.xlf
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/xlf/Resources.zh-Hant.xlf
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveCompletionSource.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/LegacyRazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionListProvierTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs
src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveCompletionSourceTest.cs

Most of https://github.com/dotnet/razor-tooling/issues/4547
Multi-line directives (e.g. `@code`) require additional tweaking to correctly determine ident size and type (spaces or tabs). Maybe I will implement them later, but not sure. Single-line directives are used a lot more frequently, so this PR will cover most use cases anyway

Single line directive snippets

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/ProjectRazorJsonPublisher.cs

Serializing the project.razor.json is failing for me on an M1 Mac, specifically the temp file is being created, but then I'm getting a file not found error when it tries to get renamed (moved) to the real file name. I don't know for sure what is going on, but it could be https://github.com/dotnet/runtime/issues/35122 so going to see if this works any better.

Try alternate file moving code for ARM macx

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/RazorLanguageServerCustomMessageTargets.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedTypes.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/IDelegatedParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/RazorHoverEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/RazorDefinitionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestClient.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestProjectSnapshotManagerAccessor.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestResponseRouterReturn.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6652
Unfortunately due to a lot of build issues, I couldn't make the tests actually use the real custom message target, but maybe one day.
I inched the rename and hover endpoints a bit further too, so might want to review commit-by-commit. Each commit has a _little_ more info about what it is too.

Single server go to definition

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Properties/_Manifest.addin.xml

- Includes Razor Language Configuration file in the MPack with the requisite authoring required for VS Mac.
- Compliments this: https://github.com/xamarin/vsmac/pull/8621/files

Include Language Configuration in VS Mac addin.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs

Found while debugging.
Fortunately in release this has no negative effect, other than an extra call to the custom message target before we return null, but during debugging its annoying with the constant assert popups.

Don't try to delegate to Razor

---

src/Razor/src/rzls/rzls.csproj

Adds arm64 RIDs for each of the supported platforms.
-
Fixes: https://github.com/dotnet/razor-tooling/issues/6406

Add arm64 RIDs to Razor LanguageServer project.

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/RazorDefinitionEndpointTest.cs

Noticed today while working. Not only did this not work, my tests were validating the wrong Uri 🤦‍♂️
C# was unaffected (at runtime) because Roslyn calls us for mapping anyway. Sad we can't (easily) test this with the real Html and TypeScript language servers.

Fixed Go to Definition for TypeScript

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs

(Hopefully) Fixes one of the exceptions in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1593766
Would love to know what the code looked like, that hit this, but alas, this is mostly just an educated guess at what could possibly be null in this method. The compiler is not nullable annotated in this area.

Fix null ref exception

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1596109
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1593766
When typing fast, its possible for Roslyn to not be up to date with the state of the world, and so can send us edits that are out-of-bounds when we try to go apply them during formatting. This is a very quick fix to not error in those situations. The real fix will be https://github.com/dotnet/razor-tooling/issues/6650 which I'll pick up soon.

Don't NFW when we get a bad edit from C#

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/cgmanifest.json

This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …

Add `$schema` to `cgmanifest.json`

---

src/Razor/src/rzls/rzls.csproj

- The win10 change was to try and address CG issues that have been resolved separately from the change.

Don't target win10

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectWorkspaceStateGenerator.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1601533
Unfortunately this isn't testable on our end, because it relies on a race in .NET where the semaphore is disposed after the check for disposal. Given there was no user impact, this is just RPS noise, I'm totally okay with this :)

Don't update anything if we've been disposed

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionProviderHelper.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/AddUsingsCSharpCodeActionResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/WorkspaceEditExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/AddUsingsCSharpCodeActionResolverTest.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6784
Originally our add using code would try to parse out the text edit, and manually add the using from that. That was problematic for fragmented edits, so it was changed to just process the title of the code action. That was problematic because sometimes usings aren't as simple as they appear.
This fixes all of that, and is in fact part of https://github.com/dotnet/razor-tooling/issues/6159 and actually uses the patent that we filed, which is not a bad thing. We had all of the interesting code as part of on type formatting anyway, this mainly just moves things around.

Allow any add using to work

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/RazorLanguageServerCustomMessageTargets.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedTypes.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentHighlighting/DocumentHighlightEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/DefinitionParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/DocumentHighlightParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/ITextDocumentPositionParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/ImplementationParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/OnAutoInsertParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RenameParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/SignatureHelpParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/VSHoverParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/RazorHoverEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Implementation/ImplementationEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SignatureHelp/SignatureHelpEndpoint.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/OnAutoInsertTests.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6650
Fairly straightforward implementation, though I did need to access the original request, and the project, when handling the delegated parameters, and I had to add an opt-out of delegating (returning null from CreateDelegatedParams), and the OnAutoInsert parameters didn't inherit from TextDocumentPositionParams, but fulfils the same contract, so all-in-all there is a little churn.

Single Server OnAutoInsert

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs

Fixes: https://github.com/dotnet/razor-tooling/issues/6724
**New fixed behaviour:**

Fixed snippet behaviour in the middle of an attribute

---

build.cmd
eng/restore-internal-tools.yml

Fixes #6790
This fixes an issue that was introduced with #6545 where `build.cmd` would no longer pass the `-restore` and `-build` arguments by default. Previously, `build.cmd` also passed `-pack`, but that appears to be failing, so I've chosen to leave that out for now.

Fix build.cmd to always pass -restore and -build

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/src/extension.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/ProvisionalCompletionOrchestrator.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServerClient.ts

(See last commit only)
Passes in a document selector to client options so that Razor documents can be recognized. I believe this was previously done within the language server itself, but was taken out of the server logic within the past year as we did more refactoring.

[VSCode] Pass in document selector so Razor documents can be recognized

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/yarn.lock
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/src/extension.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/yarn.lock
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/CodeActions/CodeActionsHandler.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Diagnostics/ReportIssuePanel.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorFormattingFeature.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorHoverProvider.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServerClient.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorServerReadyHandler.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Semantic/SemanticTokensHandler.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/vscodeAdapter.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/yarn.lock
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/package.json
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/yarn.lock
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/package.json
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/yarn.lock
src/Razor/test/VSCode.FunctionalTest/package.json
src/Razor/test/VSCode.FunctionalTest/yarn.lock

Our VSCode type versions, especially our LSP client versions, are out of date. This PR updates them and fixes the fallout from the upgrades.

[VSCode] Upgrade type versions + fix breaking changes

---

src/Razor/Razor.sln
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

Adds source generator and its dependencies to VSIX.
Roslyn change: https://github.com/dotnet/roslyn/pull/63912

Add source generator to VSIX

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs

Follow up to #6834 because I'm a fusspot. I _love_ using raw string literals, for readability, so figured it makes sense to make things even more readable.
Entirely non-functional whitespace changes (even if the GitHub diff algorithm doesn't agree 😛)
(well.. there is one non-whitespace change.. still non functional though.. see if you can spot it!)

I have opinions about style

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyCodeBases.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

- Remove old references to some packages for VS Extensions parts.

CLaSP: VS Extensions

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentColor/DocumentColorEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentHighlighting/DocumentHighlightEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/FoldingRangeEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorDocumentFormattingEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorDocumentOnTypeFormattingEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorDocumentRangeFormattingEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/RazorHoverEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LinkedEditingRange/LinkedEditingRangeEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/RazorSemanticTokensEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguage.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServerClient.ts
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorDocumentOnTypeFormattingEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorDocumentRangeFormattingEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/LinkedEditingRange/LinkedEditingRangeEndpointTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs

- We were seeing issues with double registrations of handlers, which resulted in issues such as double hover.
- Previously, I debugged through the client code and had _thought_ this was a bug on the VS Code client side. However, after discussing with Dirk + debugging through some more, this actually seems to be a probable bug in O#.
- Essentially, O# [registers the handlers it recognizes](https://github.com/OmniSharp/csharp-language-server-protocol/blob/e0cc2012b63757ebf779bf4e86e8835e400b034f/src/Server/LanguageServerHelpers.cs#L147). However, since Razor also registers handlers, this results in some handlers being registered twice.
- This is likely not an issue in VS since it doesn't look like the VS client supports direct registration requests via `client/registerCapability`. Instead, …

[VS Code] Remove double handler registrations

---

eng/Versions.props

Same as https://github.com/dotnet/razor-tooling/pull/6880 but targeted towards main since the LSP client merged a breaking change today.

[VSCode] Update VS LSP protocol version (main)

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentPresentation/TextDocumentTextPresentationEndpointTests.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentPresentation/TextDocumentUriPresentationEndpointTests.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/WrapWithTag/WrapWithTagEndpointTests.cs

- Move TextDocument and WrapWithTag tests to CLaSP.

CLaSP: TextDocument and WrapWithTag tests

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/AddUsingsCSharpCodeActionResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/TypeAccessibilityCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionResolutionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/LegacyRazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/LinkedEditingRange/LinkedEditingRangeEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileChangeDetectorManagerTest.cs

- Move CodeAction, Completion, and LinkedEditRange tests to CLaSP.

CLaSP: CodeAction, Completion, and LinkedEditRange tests

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/RazorLanguageServerCustomMessageTargets.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedTypes.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Debugging/ValidateBreakpointRangeEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentHighlighting/DocumentHighlightEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IValidateBreakpointRangeEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/ValidateBreakpointRangeParamsBridge.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/RazorHoverEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Implementation/ImplementationEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SignatureHelp/SignatureHelpEndpoint.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Debugging/ValidateBreakpointRangeEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6825
Fairly boring really... though it turns out that the initial breakpoint placement still uses the old COM stuff, so I can't delete any code like I was hoping to :(
We could make that COM stuff call through to LSP, but eventually the debugger will do that for us, so unless there are known issues with it, I don't think we gain anything (and we potentially introduce perf issues as the LSP call to Roslyn would have to block the UI thread)

Add endpoint to handle breakpoint validation requests, and forward them to Roslyn

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs

- This line used to exist but disappeared in the CLaSP merge. It's needed for VSCode since we don't explicitly pass in a HostServicesProvider in that scenario.

Add back host services

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServerCapability.cs

Fixes breakpoint placement, plus presumably lots of other things, after the CLaSP merge.
Seems like when changing the `RazorLanguageServer` we lost the registration of our experimental capabilities.
https://github.com/dotnet/razor-tooling/commit/3cbeebf4b8e31c1f3a0d6de932bcc4a3f94ad111#diff-71cce0492ca142b27d35547a8056029bdfd5bd92720d32d9265193dbaefb98e0L116
Decided to also change it to be a bit more "standard" and DI (though I would have _loved_ if I could have just put `[Export(typeof(IRegistrationExtension))]` on it 😛) since previously it was a record that was only accessed statically, which just seemed odd.

Register our experimental language server capabilities

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorLanguageQueryParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorMapToDocumentEditsParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorMapToDocumentEditsResponse.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorMapToDocumentRangesParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorMapToDocumentRangesResponse.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageQueryResponse.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServerWrapper.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorMapToDocumentEditsParams.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorMapToDocumentRangesParams.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorMapToDocumentRangesResponse.cs

- @ryanbrandenburg and I were pair debugging through some serialization issues in VSCode and noticed a few issues:
- (1) Some endpoints were not being registered to the language server.
- (2) The naming of some properties sent over the wire to the VSCode side had incorrect naming (e.g. `Position` instead of `position`).
- (1) is a pretty simple fix. To address (2), we added a `CamelCasePropertyNamesContractResolver` to our JSON serializer. As a secondary measure, we thought it would also be good to label our custom requests and responses with the `DataContract` attribute (which is how the VS LSP client does things today).

Fix serialization naming

---

azure-pipelines.yml

As a part of https://github.com/dotnet/arcade/issues/10123, we are moving all docker containers to the "latest" tagging schema

Update docker containers to latest tag

---

.github/fabricbot.json

- Updates FabricBot for 17.5 P1.
- Since we no longer have columns for each individual in our project board, we can remove a significant portion of our logic.

Update FabricBot for 17.5 P1

---

.editorconfig
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultBraceSmartIndenterFactory.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/RazorLSPTextViewConnectionListener.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs

Noticed the other day, when I tweaked my VS code style settings to investigate a bug, there were lots of errors in razor. This change adds a few things to our editorconfig file so that we're not at the mercy of different people's different VS settings. It also gives us a base to start changing as we make decisions.
This is presumably not exhaustive, it's just the changes the editorconfig editor wanted to make, but cleaned up.
Oh and I removed some double semi-colons because I'm sneaky :)

Baseline editorconfig

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs

- Now that we no longer depend on O#, we can remove the workaround to stop double registering features. The bulk of this removal was actually included as part #6951, this is just the remaining cleanup.
Fixes https://github.com/dotnet/razor-tooling/issues/6871

[VSCode] Remove O# double registration workaround

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentPresentation/TextDocumentUriPresentationEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentPresentation/TextDocumentUriPresentationEndpointTests.cs

Use DocumentResolver instead of DocumentContextFactory to find dropped components

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorLanguageServerBenchmarkBase.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentPresentation/AbstractTextDocumentPresentationEndpointBase.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentSynchronization/RazorDidSaveTextDocumentEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorRequestContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRazorLogger.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LoggerAdapter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LspLogger.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServerWrapper.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorRequestContextFactory.cs
src/Razor/src/rzls/Program.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/Logging/LoggerExtensions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/TestBase.cs

- Clean up some of the Logging in Razor so that we're not passing two logging objects around (especially since they both lead to the same place).
- The current state of our logging seems to be that for VS we log to LogHub and in rzls scenarios we use window/log. Does this track with everyone's expectations?
Fixes: https://github.com/dotnet/razor-tooling/issues/6843

Clean up Logging

---

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs

- In the official build our assembly version will not be the fake "42.42.42.42". IIRC that was just me being extra paranoid though and the AppDataLocal check should b e enough.

Don't rely on assembly version

---

eng/Versions.props
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorLanguageServerTest.cs

- There was a breaking change in CLaSP in order to fix https://github.com/dotnet/roslyn/pull/64583. Now that Roslyn has merged that fix we must react.
- Thankfully it's very simple, we just need to stop referencing the ExitHandler since it's gone now. CLaSP now auto-registers that method itself (exit has special handling properties since it's the only method that can be run after shutdown).

Take new CLaSP version

---

azure-pipelines-richnav.yml

- cibuild.cmd includes tests, so let's not use that for RichNav, where we don't want tests.
- This should save us ~5 minutes per RichNav build
Fixes: https://github.com/dotnet/razor-tooling/issues/6984

Don't run tests on RichNav

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/DefaultLSPTagHelperTooltipFactory.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/DefaultVSLSPTagHelperTooltipFactory.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/TagHelperTooltipFactoryBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultVSLSPTagHelperTooltipFactoryTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/HoverTests.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6047
Adds support for `<c>`, and uses named groups in the regex instead of hard-coding array indexes, and stops capturing groups we don't need, stores the regexes statically, and uses raw string literals because they're objectively good.

Classify <c> tags the same as <code> tags, and clean up regex usage a little

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerTagHelperCompletionService.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/LanguageServerTagHelperCompletionServiceTest.cs

Fixes https://github.com/dotnet/razor-tooling/issues/6824
This is also the proper fix for https://github.com/dotnet/razor-tooling/issues/6583 IMO
The story is, previously we would inconsistently show tag helper completion for some HTML elements, namely we wouldn't show `form` but would show `script`. https://github.com/dotnet/razor-tooling/pull/6823 fixed that by making things consistent, and show now we always show `form` and `script`. Unfortunately that was not actually correct, as we would show the `script` tag helper completion, but then upon completing that item, the tag wouldn't be classified as a tag helper. This fixes that, and only shows a tag helper in completion if the attribute rules it has, if any, are also satisfied. This means we now don't show `form` or `script`, as tag …

Don't show tag helper completions if the attribute rules aren't satisfied

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/RazorDefinitionEndpointTest.cs

I thought we already had coverage for this, but after the tests got ported to be readable, it was clear we didn't, so adding it just in case.

More Go to Definition attribute tests

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Completion/RazorCompletionItemProvider.ts

- See gif in original issue. We need to handle Razor comments specially so we don't accidentally commit an item when typing the comment syntax.
Fixes #4566

[VSCode] Completion commit fix for Razor comments

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRazorIntermediateNodeLoweringPhase.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/IRazorDocumentClassifierPhase.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/CSharpCodeParser.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RazorCodeDocumentExtensions.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RazorCodeGenerationOptions.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RazorCodeGenerationOptionsBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RazorProjectEngine.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RazorSourceDocument.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RazorSourceDocumentProperties.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/SourceLocation.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/ComponentTagHelperDescriptorProvider.cs
src/Compiler/test/Microsoft.AspNetCore.Razor.Test.MvcShim/Microsoft.AspNetCore.Razor.Hosting/RazorCompiledItem.cs
src/Compiler/test/Microsoft.AspNetCore.Razor.Test.MvcShim/Microsoft.AspNetCore.Razor.Hosting/RazorCompiledItemAttribute.cs

There is not much to it. Found a few spelling mistakes in the public API xmldocs while working with the Razor compiler.
I fixed a few comments as well since I was already in the document.

Fix spelling mistakes

---

eng/Versions.props

Another day, another CG alert.
Fixes https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-razor-tooling/alert/7359307?typeId=6437374

Update Microsoft.CodeAnalysis.Testing dependency

---

src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithRouteTemplate_DesignTime.codegen.cs
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithRouteTemplate_DesignTime.mappings.txt
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithoutModel_DesignTime.codegen.cs
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithoutModel_DesignTime.mappings.txt
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPages_DesignTime.codegen.cs
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPages_DesignTime.mappings.txt
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithRouteTemplate_DesignTime.codegen.cs
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithRouteTemplate_DesignTime.mappings.txt
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithoutModel_DesignTime.codegen.cs
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithoutModel_DesignTime.mappings.txt
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPages_DesignTime.codegen.cs
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPages_DesignTime.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/CodeGeneration/DefaultCodeRenderingContext.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Extensions/DesignTimeDirectiveTargetExtension.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ChildComponent_WithPageDirective/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ChildComponent_WithPageDirective/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Component_WithUsingDirectives/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Component_WithUsingDirectives/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Legacy_3_1_TrailingWhiteSpace_WithDirective/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Legacy_3_1_TrailingWhiteSpace_WithDirective/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Regression_772/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Regression_772/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Regression_773/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Regression_773/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/TrailingWhiteSpace_WithDirective/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/TrailingWhiteSpace_WithDirective/TestComponent.mappings.txt

Fixes https://github.com/dotnet/razor-compiler/issues/352
I've hacked this in. There are things todo:
1. Is this the right way to detect whether a Razor document is a Razor Page or Blazor page?
2. I was surprised when I ran the unit tests and nothing failed. It appears the razor compiler unit tests aren't in the solution file? If they're somewhere in the repo then I still need to update them.

Add route string syntax to Razor pages and Blazor

---

src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor.CoreComponents/Microsoft.CodeAnalysis.Remote.Razor.CoreComponents.csproj

Fixes #7026
The XML doc comment files for our binaries are unnecessarily copied to our VSIX's ServiceHubCore folder, but they're just unnecessary bytes and noise for that scenario.

Remove XML doc comment files from VSIX ServiceHubCore folder

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/yarn.lock
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/yarn.lock
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/.npmrc
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/package.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/yarn.lock
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/package.json
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/yarn.lock
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/package.json
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/yarn.lock
src/Razor/test/VSCode.FunctionalTest/package.json
src/Razor/test/VSCode.FunctionalTest/yarn.lock

Closes https://github.com/dotnet/razor-tooling/security/dependabot/49
Closes https://github.com/dotnet/razor-tooling/security/dependabot/48
Closes https://github.com/dotnet/razor-tooling/security/dependabot/47
Closes https://github.com/dotnet/razor-tooling/security/dependabot/46
Closes https://github.com/dotnet/razor-tooling/security/dependabot/45
Closes https://github.com/dotnet/razor-tooling/security/dependabot/44

Update minimatch to 3.0.5

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

- Noticed that these dll's failed to load in VSMain. It's unclear to my why the error wasn't shown to us before that though.

Clean up bad Analyzer references

---

azure-pipelines.yml

- The pool used for `Publish to Build Asset Registry` was somehow changed from under us, resulting in our official builds failing. This PR pulls `Publish to Build Asset Registry` into a separate step which allows us to specify the pool. This is similar to what [Roslyn does today](https://github.com/dotnet/roslyn/blob/eb5712232bf1d68a4f34214af32a16a6d4dda52e/azure-pipelines-official.yml#L316) (and is why they're not running into the same issue). Note, Roslyn includes `Publish to Build Asset Registry` as one of their build steps, but due to the different way Razor infra is set up, it was much easier to make it a separate stage.
- An alternate solution would be to track down whoever controls the default pool (maybe arcade?) and ask them for help, but pulling the pool into a separate step …

Publish to Build Asset Registry using specific pool

---

azure-pipelines.yml
eng/scripts/StartDumpCollectionForHangingBuilds.ps1

Fixes #6297 
Currently, the scheduled job to run ProcDump on hanging processes runs after 25 minutes. However, the build and tests are taking upwards of ~35 minutes now that we've added the compiler and re-enabled integration tests. So, it _always_ ends up capturing a dump when tests are running.
Since our CI is set to time out at 120 minutes, I'm increasing the ProcDump timeout to 60 minutes. I've also made a couple of other tweaks to the dump collection scripts to improve the reporting slightly.

Increase wake time for ProcDump CI task

---

src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/ExportedTagHelperResolverFactory.cs
src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpTelemetryReporter.cs

- After pulling in changes from main into the feature branch, VSCode started throwing an exception that an `ITelemetryMonitor` couldn't be found. This workaround solution creates a dummy class so the exception is no longer thrown. Since we aren't currently actively tracking telemetry for VSCode, imo it's not necessary for now to have a working telemetry monitor.

[VSCode] Fix telemetry monitor exception

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TagHelperResolver.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorServiceBase.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorServiceFactoryBase.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorServices.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteTagHelperProviderService.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteTagHelperProviderServiceFactory.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteTagHelperResolver.cs

- Basically ServiceHub demands that instances of `IServiceHubServiceFactory` always have a parameterless constructor, so when we added a parameter it decided our factory was invalid. Not sure why this didn't show up in the integration tests, possibly when it failed to find the Experimental instances ServiceHub provider it used the one from VS?
- I tried to do this in the least destructive way to the Telemetry work, but I couldn't figure out how to get the TelemetryReporter where it was needed so I left the calls themselves in and we can fix `TelemetryReporter` acquisition in a later PR.

Make TelemetryReporter optional for TagHelperResolver

---

eng/Versions.props
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingLanguageServerClient.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Microsoft.AspNetCore.Razor.LanguageServer.Test.csproj

In preparation for doing HTML code actions, I figured it would be a good idea to update our Web Tools dependency that we use for testing, and add a test for On Type formatting, since the new version now supports it.
I've no idea if this will actually enable us to test HTML code actions of course, because Web Tools delegates to separate LSP servers for each language, but I figured this can't hurt anyway, and gave me something to do on the couch for a couple of nights.

Update Web Tools dependency and create OnType formatting test

---

.github/fabricbot.json

- It doesn't look like FabricBot is compatible with the new project format. Given this, I've removed the logic where adding an issue to a milestone automatically adds it to a project.
- edit: reverted this bit <s>In the process, I also renamed several of the tooling milestones to be tooling specific, e.g. `17.5 P2` -> `17.5 P2 - Tooling` so we don't have tooling issues confused with compiler issues. (Not part of this PR, but just thought I'd mention it.)</s>

Update FabricBot after project changes

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyCodeBases.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

Those are already shipped in VS
https://dev.azure.com/devdiv/DevDiv/_git/VS?path=%2Fsrc%2FSetupPackages%2FDeployableDotNetDependencies%2FDeployableDotNetDependencies.csproj&version=GBmain&_a=contents

Remvoe duplicate BCL assemblies from vsix

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/DelegatedCodeActionParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentColor/DelegatedDocumentColorParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentColor/DocumentColorEndpoint.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs

Noticed this while working on stuff, thought I'd do it as a separate commit in the interests of speed, and possible future servicing needs.
Looks like in https://github.com/dotnet/razor/pull/7006 the delegated code actions and delegated color params types were introduced, and signatures of the custom message target were updated, but the endpoints were missed. I looked at the sync code briefly and its not really clear to me how these endpoints actually work now, because it seems like they would always be out of sync (because `HostDocumentVersion` would be `0`), but latest main of VS does seem to work 🤷‍♂️
I don't _want_ to write an analyzer to check that all custom message target calls use the right parameters.. but I kinda can't think of any easier way to validate this in future. Would …

Pass host document version through to our custom message targets

---

eng/pipelines/test-integration-job.yml

- I noticed that we weren't finding the logs that were claimed to be published in [this error case](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6896885&view=logs&j=3e5619a1-2b1c-5cb0-1de5-24acacb5486e&t=7a357653-97cc-5c20-88c7-956a28e2bfb1&l=18). So I'm seeing if we can A) start collecting those B) can figure out what caused the failure. The failure seems intermittent, so we may need to check  this in before we're able to verify that it catches the data we want.

Integration publish data

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.cs

Fixes: #6795 by un-skipping test now that the version of Roslyn that Razor uses has been updated by #7012

Re-enable test Handle_SingleServer_CSharpBraceMatching

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Components/ComponentGenericTypePass.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/ParserHelpers.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperDescriptor.cs

This fixes some issues that ReSharper complained about in the `Microsoft.AspNetCore.Razor.Language` project:
- The `&&` operator has higher precedence than `??`, so the following two lines didn't behave as intended:
- `if (attribute.BoundAttribute?.IsGenericTypedProperty() ?? false && attribute.TypeName != null)`
- `if (childContent.BoundAttribute?.IsGenericTypedProperty() ?? false && childContent.TypeName != null)`
- Removed two redundant `;`
I also took the opportunity to do some minor cleanup in the impacted files:
- Replaced `.Where(...).FirstOrDefault()` with `.FirstOrDefault(...)`
- Adjusted a NRT annotation
- Fixed some typos

Fix operator precedence and cleanup

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionProviderTest.cs

- While debugging, I ran into https://github.com/dotnet/razor/issues/7901
- This changes `Debug.Fail` to logging so the language server doesn't crash:

[VSCode] Change `Debug.Fail` to logging to mitigate crash

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyCodeBases.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

- Basically without these some WebTools scenarios break because in RPS due to loading weirdness.
- Wanted to get this moving, but I don't have the area knowledge here that @genlu does, so @genlu please confirm that this is the correct fix and that this won't conflict with anything else.
Fixes: Issues WebTools has when we don't provide these for O#.Ext.JsonRpc.

Revert 'Remvoe duplicate BCL assemblies from vsix'

---

.editorconfig
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/BaseDelegatedCodeActionResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/CSharpCodeActionResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionResolutionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Html/HtmlCodeActionResolver.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/AddUsingsCodeActionProviderFactoryTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/AddUsingsCodeActionResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/AddUsingsCSharpCodeActionResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/TypeAccessibilityCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionResolutionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ComponentAccessibilityCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/CreateComponentCodeActionResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorTranslateDiagnosticsEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentPresentation/TextDocumentUriPresentationEndpointTests.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CSharpCodeActionsTests.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Text.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/ShellInProcess.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/RazorCodeActionsTests.cs

Fixes https://github.com/dotnet/razor/issues/7926
Well not really, because one of the suggestions turned out to not be possible, but I null annotated all of the code actions tests, and added new integration tests, to make up for it :)

Clean up code actions

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TagHelperResolver.cs

@AllenD-MSFT noticed a property name coming through telemetry of `razor.razor.bindtaghelperdescriptorprovider.elapsedtime`. Turns out we prefixed the property name when creating the data, and then [prefixed it again](https://github.com/dotnet/razor/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.Common/Telemetry/TelemetryReporter.cs#L50) when reporting.

Remove duplicate "razor." on property name

---

src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor.CoreComponents/Microsoft.CodeAnalysis.Remote.Razor.CoreComponents.csproj

Following files should not be included in `ServiceHubCore` inthe razor vsix

Exclude non-shipping files from vsix

---

src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/src/ViewComponentTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/src/ViewComponentTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/src/ViewComponentTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/ITagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/BindTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/ComponentTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/DefaultTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/EventHandlerTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/KeyTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/RefTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/SplatTagHelperDescriptorProvider.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TagHelperResolver.cs

PR https://github.com/dotnet/razor/pull/7001 added a `Name` property to `ITagHelperDescriptorProvider`.
Unfortunately, for some legacy razor projects (MVC Extensions 2.x and 1.x) the assembly versions from NuGet are hard coded, meaning changes need to be backwards compatible. With this change, the razor tool in the SDK starts throwing `MethodNotFoundException` for the legacy projects because the hard coded nuget versions don't implement the new `Name` property. 
We can think through how we want to handle this in the future, and I think there is scope to make changes, but for now we're blocked inserting into the SDK by this.  As a temporary remediation, I've removed the `Name` property, and am just using the runtime type instead.

Remove Name from interface, use runtime type instead

---

NuGet.config
eng/Signing.props
src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyCodeBases.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

- We're currently including these assemblies just because WebTools have a dependency on them, but WebTools is getting ready to take that on themselves, so I prepared this PR to remove them from our vsix.
- We MUST insert this in coordination with WebTools, probably as part of a joint VS insertion PR.
Fixes: https://github.com/dotnet/razor/issues/6903
CC @jimmylewis

Remove unused assemblies

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/DoStatement.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ForStatement.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ForeachStatement.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/IfStatement.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/LockStatement.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/SwitchStatement.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TryStatement.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/UsingStatement.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/WhileStatement.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap

Fixes #4581
I've done this as lots of commits to hopefully make things easier to review, since all test results are in the one single snapshot results file.
First commit adds more tests and updates the snapshot to illustrate the bad thing.
Second commit sets up the textmate system I'm going to use, which sadly involves duplicating a bunch of rules.
Subsequent commits then fix one type of statement at a time, including the test snapshot results change, so you can see that things are actually fixed.
Final commit is compiling the json file from the yaml, and can be ignored.

Fix classification of C#-looking text in Html tags

---

NuGet.config
eng/Signing.props
src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyCodeBases.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

Reverts #7925 until WebTools ships their own copies of the removed dlls. This unblocks our insertion.

Revert "Merge pull request #7925 from ryanbrandenburg/OSharpNoShip"

---

eng/Versions.props

The packages are only for transport and the "5" can be confusing when looking at the SDK input version numbers.

Remove pre-release version iteration

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Extensions/DesignTimeDirectiveTargetExtension.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ChildComponent_WithPageDirective/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ChildComponent_WithPageDirective/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Component_WithUsingDirectives/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Component_WithUsingDirectives/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Legacy_3_1_TrailingWhiteSpace_WithDirective/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Legacy_3_1_TrailingWhiteSpace_WithDirective/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Regression_772/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Regression_772/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Regression_773/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Regression_773/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/TrailingWhiteSpace_WithDirective/TestComponent.codegen.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/TrailingWhiteSpace_WithDirective/TestComponent.mappings.txt
src/Compiler/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.Compiler.csproj

https://github.com/dotnet/razor/pull/6997 added string syntaxes to Razor pages and component page routes. This PR changes the string syntax for components to `Route,Component` so the same integration can be used for both.

Change Razor component route syntax to use option

---

azure-pipelines.yml

- similar to #6907 but stick w/ `ubuntu-18.04-cross` (versus `centos-7` in main)
- was `ubuntu-14.05-cross-blah` but that's _really_ old and doesn't have a simpler tag

[release/3.1] Use simpler Docker tags

---

eng/Versions.props

- Was seeing errors similar to https://github.com/dotnet/roslyn/issues/63318 when building within VS. Upgrading the compiler toolset version seemed to have fixed it.

Update compiler toolset version

---

src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor.CoreComponents/Microsoft.CodeAnalysis.Remote.Razor.CoreComponents.csproj

This fixes a typo in `Microsoft.CodeAnalysis.Remote.Razor.CoreComponents.csproj` that caused the `.dll`, `.exe`, `.deps.json`, and `.runtimeConfig.json` to be included in the Razor VSIX's `ServiceHubCore` folder. In addition, I've updated this project to target `net6.0`. There's no reason it needs to target `netcoreapp3.1`. The only reason this project exists is to define an output group target that our VSIX's build can access to pull in the assets needed for the `ServiceHubCore` folder. 
**Before:**
**After:**

Exclude Razor.CoreComponents.* files from VSIX

---

eng/config/PublishData.json

- Separate from this PR, I created a `release/dev17.5` branch to match Roslyn's branching strategy. This will make it easier in the future if we need to take a fix for servicing or QB approval.
- This PR updates our GitHub -> VS branch mapping targets after the 17.5 P2 snap.

[Infra] Update PublishData.json for 17.5 P3

---

azure-pipelines.yml

- I previously hardcoded a commitId in our insertion PR logic which I meant to remove after testing but forgot. This has resulted in our insertion PRs being generated with the wrong prefixes. Thanks to @dibarbet for the catch!

[Infra] Fix VS insertion logic

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Properties/_Manifest.addin.xml
src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/mpack/addin.info

Turns out VS Mac already ships this itself, so we don't need to.
https://github.com/xamarin/vsmac/blob/main/main/src/core/MonoDevelop.Core/MonoDevelop.Core.addin.xml#L4

Don't include Microsoft.Extensions.ObjectPool.dll in our mpack

---

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj

Follow-up to https://github.com/dotnet/razor/pull/8009.
If Razor's LSP server was a separate process like WebTools, we would leave the duplicate files in there and resolve this issue using symlinks. But that's not the case here.

Truly exclude Microsoft.Extensions.ObjectPool.dll from mpack

---

azure-pipelines.yml
eng/Build.props
eng/pipelines/test-integration-job.yml
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/README.md

This is _somewhat_ a guess, but I think this might solve the symbol issue, plus it just makes sense.
Currently we build all of Razor.sln, then the RazorExtension.csproj even though its part of the solution. This change means we just build the solution, and call it a day.
Will do a validation build once the RPS issue has been fixed, so I can be sure it will work, but looking at build artifacts, the VSIX contents are identical.

Try doing one build instead of two

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorPullDiagnosticResponse.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorPullDiagnosticsEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorTranslateDiagnosticsEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorTranslateDiagnosticsService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorTranslateDiagnosticsEndpointTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DiagnosticTests.cs

Fixes #8023
Nerd sniped myself. Looks like Web Tools changed to pull diagnostics for Html so we need to respond in kind.
Includes https://github.com/dotnet/razor/pull/8018 so just review [the last commit](https://github.com/dotnet/razor/pull/8024/commits/0f44ec5f70f1c241fab32609ce159d8a4d530aa6?w=1) (with whitespace off). @ryanbrandenburg if you think this is okay, and see this message before you merge your PR, feel free to just approve and merge this instead :)

Switch Html to pull diagnostics

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorPullDiagnosticsEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorTranslateDiagnosticsEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorTranslateDiagnosticsService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorTranslateDiagnosticsEndpointTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DiagnosticTests.cs

- Start running pull diagnostics through translate.
- Break diagnostics translate out into a service to keep the multi-location use clean
- Create an Integration test which covers the diagnostics scenario that was missed.
- Remove SingleServerDiagnostics flag (if people feel strongly or there's some policy I'm unaware of this can be left in).
Fixes: Reversion of https://github.com/dotnet/razor/pull/7986.

Diagnostic translate flag

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs

- This moves contained LS initialization out of the initialize handler for HTMLCSharp to avoid some UIThread dangers. It's also a good pre-emptive fix since HTMLCSharp is on the way out.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1391983
CC @gundermanc

UI thread handling outside of initialize request

---

azure-pipelines.yml
eng/AfterSigning.targets
eng/AfterSolutionBuild.targets

- Previously disabled source build in the VS Code feature branch (via https://github.com/dotnet/razor/pull/8049) since I couldn't determine how to prevent it from building `rzls.csproj`. After talking to Fred, this should hopefully be the solution.

[VS Code] Re-enable source build in VS Code feature branch

---

README_compiler.md
docs/ProjectsAndLayering.md

- Mostly I just am annoyed by the warnings that show in VSCode, but I'm told that clean header usage helps screen-readers

Fix md file warnings

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRazorIntermediateNodeLoweringPhase.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/CSharpCodeParser.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/HtmlMarkupParser.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/MarkupChunkGenerator.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/StatementChunkGenerator.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/TagHelperBlockRewriter.cs

Contributes to https://github.com/dotnet/razor/issues/7893. MarkupChunkGenerator is a stateless marker entity, and shows up 16 million times in the trace in the linked bug.

Use a singleton for MarkupChunkGenerator

---

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DiagnosticTests.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/FindAllReferencesTests.cs

- This is purely to unblock CI and get a green build for our VS Code bits. Planning on reverting before the feature branch is inserted into main.

[VS Code] Skip flaky integration tests

---

src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj

The latest build has the source gen as the only DLL missing symbols, and I think letting it be marked as a shipping should fix that. And it does ship in the VSIX after all.
Hopefully this can't break anything else 🤷‍♂️

Mark source gen as shipping

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/ProjectSystem/ProjectSnapshotManagerBenchmarkBase.StaticProjectSnapshotProjectEngineFactory.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/ProjectSystem/ProjectSnapshotManagerBenchmarkBase.StaticTagHelperResolver.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/ProjectSystem/ProjectSnapshotManagerBenchmarkBase.TestErrorReporter.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/ProjectSystem/ProjectSnapshotManagerBenchmarkBase.TestProjectSnapshotManagerDispatcher.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/ProjectSystem/ProjectSnapshotManagerBenchmarkBase.cs

This change cleans up `ProjectSnapshotManagerBenchmarkBase` a bit, which is the base class of several of the tooling benchmarks. While cleaning this up, I was surprised to find a bug where several documents with initialized with a file path as the text, rather than the actual file text. This results in some benchmarks, notably `BackgroundCodeGenerationBenchmark`, being completely invalid.

Fix benchmarks to produce correct documents

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DiagnosticTests.cs

... and when there is no doctype.
I _think_ this might fix the integration test failures we're seeing in CI.

Fix diagnostics when only C# diagnostics exists

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRazorProjectFileSystem.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RazorProject.cs

Fixes #6965.
In the CI, the path happens to be `C:document1.razor`, so it doesn't contain `/`, failing the original assert. This PR handles that case.
`Debug.Assert` hangs the CI build (seems .NET Framework [shows modal dialog](https://github.com/xunit/xunit/issues/382) instead of failing), so I replaced this one with exception. It would be better to configure this globally like [in Roslyn](https://github.com/dotnet/roslyn/blob/55259597ad41ac41e0d1888fa52a92e73318b57e/eng/config/test/Desktop/app.config#L9), I guess.

Handle project files in root directory

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml
src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml.cs

In preparing for a meeting with the compiler folks, I thought this might be a useful addition (and helps illustrate some quirks).
Looks like this (above the treeview):

Show position owner info in Syntax Visualizer

---

docs/contributing/BuildFromSource.md

Noticed some outdated text in the docs files from when the files existed in the dotnet/razor-tooling repo I think.

correct docs file

---

eng/Versions.props

A servicing fix is needed in 17.4 branch.
And it is blocked by the CG warning.
So cherrypick this https://github.com/dotnet/razor/pull/7022 to 17.4 branch

Fix the CG in 17.4 branch

---

azure-pipelines.yml
eng/Versions.props
eng/config/PublishData.json
eng/pipelines/insert.yml

- We need to insert into 17.4 (see https://github.com/dotnet/razor/pull/8097). However, as part of https://github.com/dotnet/razor/pull/7944 to automate VS insertions, I updated the drop folder to point to a different location. We should cherry-pick this change (+ related changes) back to 17.4 so we can insert.
cc @Cosifne

Cherry-pick VS insertion automation to release/17.4

---

azure-pipelines.yml
docs/contributing/BuildFromSource.md
src/Razor/src/Microsoft.VisualStudio.RazorExtension.Dependencies/AssemblyCodeBases.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension.Dependencies/Microsoft.VisualStudio.RazorExtension.Dependencies.csproj
startvs.cmd
startvs.ps1

Razor tooling deploys Roslyn dependencies to allow integration tests and VS hive debugging to function against VS preview builds. However, on local dev boxes, where VS IntPreview should be used for dogfooding, this can result in hard-to-diagnose problems when some Roslyn dependencies are loaded from the Razor tooling deployment and others are loaded from the VS install.
This change only deploys Roslyn dependencies if the `IncludeRoslynDeps` MSBuild property is set to true. This is needed for running integration tests in CI, so the job has been updated to set that property.

Conditionally deploy Roslyn dependencies

---

azure-pipelines.yml

- The 17.4 branch should be pointing to the 17.4-specific PublishData.json.
cc @Cosifne

[17.4] Update PublishData.json path

---

build.cmd
clean.cmd
restore.cmd

This is a follow up to #8099 to remove the BOM from out batch files to allow them to run properly.

Remove BOM from batch files

---

docs/InsertingRazorIntoOmniSharp.md

- The instructions for inserting Razor into O# are located somewhere fairly obscure, so I thought it'd be helpful to link directly to the instructions from our repo.

Add link to instructions on inserting Razor into O#

---

src/Razor/src/Microsoft.AspNetCore.Razor.Common/ListExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DebuggerDisplay.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ClientNotifierServiceBase.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/CompletionListCache.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionItemResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionListProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DesignTimeHelperResponseRewriter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/TextEditResponseRewriter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionListProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionResolveEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/VSInternalCompletionListExtensions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/CompletionListCacheTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/LegacyRazorCompletionResolveEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionResolveEndpointTest.cs

This is a series of tweaks in completion to improve performance at an algorithmic level. This won't make much difference in the grand scheme of completion, since most of the time spent bringing up a completion list is currently within Roslyn. However, there is some low-hanging fruit that can be easily addressed:
* `CompletionListCache` now uses a circular buffer rather than a `List<T>`. Previously, it called `List<T>.RemoveAt(0)` when something would be evicted from the cache, which results in all remaining items in the array being copied. This change avoids the copy entirely.
* Lookup for completion trigger characters was O(n) because it was calling `Contains(...)` on string arrays. This has been updated to use `ImmutableHashSet<string>` for O(1) lookup.
* Filtering design-time helpers …

Reduce allocations and O(n) lookup in completion

---

Directory.Build.props
build.cmd
src/Razor/src/Directory.Build.props
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj

Let me know if this is controversial, in particular @ryanbrandenburg, but our "warnings as errors" policy really annoys me in the IDE, because it interupts me about inane things when I'm just trying to get my hacky code changes in. I think by coding and debugging, so often don't have fully-formed thoughts, and having unused variables, or uncalled private members, is not uncommon for me.
I do, however, understand the desire for a clean codebase, and I have the same desire, so having this on in CI makes sense. This does mean you could get a local build pass, which fails in CI, so perhaps that will annoy people more than I get annoyed by having to comment out unused locals, I don't know, but I'm open to all feedback.

Warnings as errors only in CI

---

azure-pipelines-richnav.yml
azure-pipelines.yml
eng/Versions.props
eng/config/PublishData.json
eng/pipelines/insert.yml

Long story short:
Razor miss the insertion due in 17.4 P3, so right now, everything in release/17.4 branch after https://github.com/dotnet/razor/commit/61cc048d36a3fc9246d2f04625988b19a18ab8f0 is not in VS.
Now there is a servicing fix need to come to 17.4.
And QB would not be happy to accept so many change one time,
So we need to create a new branch based on https://github.com/dotnet/razor/commit/61cc048d36a3fc9246d2f04625988b19a18ab8f0 , use this as the 17.4 branch, then ship things from there.
This PR, cherry-picking the infra change listed here https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/445017
I believe it would include
https://github.com/dotnet/razor/pull/6910
https://github.com/dotnet/razor/pull/6912
https://github.com/dotnet/razor/pull/8097 …

Cherry-pick all the infra changes to 17.4.x branch

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/CreateComponentCodeActionResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/CreateComponentCodeActionResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs

- VS Code expects returned file paths to be prefixed with `/`. We aren't doing this in code actions or rename, and instead we [remove](https://github.com/dotnet/razor/blob/b2d15be01c8b9615b819fb8cffed4ccd02cdff2f/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/FilePathNormalizer.cs#L37) any leading `/` in `FilePathNormalizer` on Windows machines. This has resulted in broken code actions and rename. Unfortunately, we can't alter the logic in `FilePathNormalizer` as doing so would break other parts of the world. As an alternative, I've hacked a fix specifically in our rename/code actions logic.
- Manually verified these changes work in both VS and VS Code.

[VS Code] Fix code action and rename file paths

---

azure-pipelines.yml

- We weren't producing the proper build #s on Linux and Mac builds. We also don't need to sign those builds since (1) the Windows build already signs, and (2) the only unique component of the Linux/Mac builds are the produced language servers, which are "signed" through a separate pipeline.

[VS Code] Fix version numbers

---

src/Compiler/Directory.Build.props

Exclude analyzers from source-build to eliminate prebuilts

---

src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.cs.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.de.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.es.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.fr.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.it.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.ja.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.ko.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.pl.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.pt-BR.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.ru.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.tr.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.zh-Hans.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.zh-Hant.xlf

Reverts dotnet/razor#8120
QB asked me if https://github.com/dotnet/razor/pull/8120 is necessary for https://github.com/dotnet/razor/pull/8119 and if not QB doesn't really like to include this in the payload.
So revert.
Kind tag @davidwengier for checking

Revert "Cherrypick the LOC changes"

---

eng/CIBuild.cmd
eng/common/CIBuild.cmd
eng/common/dotnet-install.cmd
eng/common/init-tools-native.cmd

This change removes the BOM added by #8099 from `.cmd` files in the `eng` and `eng/common` folders. These scripts have continued to work, since the first line of each starts with `@echo off`. However, an error gets printed to the console for the first line before the scripts continue on.

Remove BOM from .cmd files in eng folder

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensBenchmark.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensScrollingBenchmark.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/ProjectSystem/ProjectSnapshotSerializationBenchmark.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Serialization/CompletionListSerializationBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Serialization/ProjectSnapshotHandle.cs

Fixes #8073
There were a handful of tooling micro benchmarks that failed when run. This change fixes each of them.
* `ProjectSnapshotSerializationBenchmark`: Tried to serialize a `ProjectSnapshot` and then deserialize it as a `ProjectSnapshotHandle`. Since `ProjectSnapshot` isn't actually an object that can be serialized, I assume that the original intent was to serialize a `ProjectSnapshotHandle`.
* `RazorSemanticTokensBenchmark` and `RazorSemanticTokenScrollingBenchmark`: Both of these benchmarks add a `TestRazorSemanticTokensInfoService` into the language server's service collection. However, the language server would add a `DefaultRazorSemanticTokensInfoService` afterward, causing the benchmarks to fail. The fix is to use `TryAddSingleton` in the language server to avoid allowing two …

Fix broken tooling micro benchmarks

---

src/Compiler/.editorconfig

I noticed these while making changes in the Compiler area.
- Since src/Compiler/.editorconfig declares itself as root they don't get any of the settings from the base .editorconfig such as
- Don't separate import directives by group. This matches that the files seem to generally use (and also my preference).
- Using directives go outside of the namespace.

Compiler .editorconfig

---

.gitattributes

This change was originally added to PR #8099 in [commit](https://github.com/dotnet/razor/commit/7c7cce2b663c6f86e2b46bda608a6f53637c1ea4#diff-618cd5b83d62060ba3d027e314a21ceaf75d36067ff820db126642944145393e) by @333fred, but subsequently got accidently removed with his first force push.
See [comment](https://github.com/dotnet/razor/pull/8099#issuecomment-1376904265).
This PR adds that same encoding back into the `.gitattributes` file.
**N.B.** I've not seen this attribute `encoding` in the official [git documentation](https://git-scm.com/docs/gitattributes), but assume @333fred knows what he's doing :smiley:.

Add UTF-8 encoding to `.gitattributes`

---

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DiagnosticTests.cs

- These are skipped in main and seem to be failing here too, so lets un-block things.

Skip Diagnostic tests for now

---

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Classification.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Semantic/TestFiles/RazorSemanticTokensTests/GenericTypeParameters_Work.txt

- So in VSMain we fixed a TextMate issue causing additional colors to show up in the results, but now that that's available in VSMain (but not VSPreview) our Integration tests are failing due to an additional classification span.

Account for Syntax colors

---

eng/config/PublishData.json

Add 17.6 P1 in PublishData.json after snap.
Razor 17.6 branch would still point to VS main, after this Fri. it should be changed to the release branch.
Let me know if there are other config file need to be changed.
@davidwengier  @allisonchou

Update PublishData.json after 17.6 P1 snap

---

eng/Versions.props
global.json

- This matches Roslyn's behavior: https://github.com/dotnet/roslyn/blob/fde6782ee30efa6f408b64085ba6ebdeb36dace1/global.json#L4
- It also addresses some user concerns of Razor releasing VS Code updates using pre-release versions of .NET SDK (see https://github.com/dotnet/razor/issues/6241)

[Infra] Disallow pre-release SDK versions

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1710347
FYI @phil-allen-msft @Cosifne this is for 17.6 P1, M2 mode.

Don't throw away C# diagnostics if Web Tools returns null

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json

It's been a while since we've published a new version (currently 1.1.0 is the most recent). Incrementing the version because of the addition of #7929, then will walk through publishing on resolution of this PR.
My understanding of the publishing process is from the guide written by @captainsafia [here](https://github.com/dotnet/razor/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/README.dev.md#publishing-the-extension). Please correct me if this process is no longer correct.

Upgrade BlazorWasmDebugging to 1.1.3

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Components/ComponentsApi.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/ComponentDetectionConventions.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/ComponentTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/DefaultTagHelperDescriptorFactory.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/SymbolExtensions.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/TagHelperTypes.cs

The general pattern for tag helper lookup is to use `compilation.GetTypeByMetadataName()` and then compare if a given type is equal. Generally, this is fine, but for some operations the source generator calls into these methods many times per compilation. Looking at traces this became a significant performance bottleneck. 
This PR replaces that logic by instead comparing the full names of the types which is significantly faster. I don't *think* this changes the lookup rules if a user has defined their own copy of the attribute, as `GetTypeByMetadataName` checks the declaring compilation first anyway.
This is honestly one of the changes I'm _least_ happy with, although we tell people to use the approach in source generators, so I think its sound. I also looked if it would be possible to …

Lookup some types by name

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorCodeActionsBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/DelegatedCodeActionParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/RazorCodeActionContext.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IVSCodeActionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/VSCodeActionParams.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/TypeAccessibilityCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Html/DefaultHtmlCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ComponentAccessibilityCodeActionProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionProviderTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs

We're losing data between our endpoint and middleware (custom message target) because the platform converters aren't used for writing.
Poiinting this to release/dev17.6 on the assumption web tools wants it for M2.  @ToddGrun @jimmylewis let me know if P2 is okay.

Use a custom CodeActionParams to prevent NRE in Web Tools

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TextDifferencing/TextDiffer.IntArray.cs

Encountered an IndexOutOfRange Exception here, when formatting a large .razor file.
The debugger showed that the pages array had 3 entries, the expression `index % PageSize` evaluated to some high values like 23300 % 20480.
I think this should be an integer division instead of a modulo operation.

fix-text-differ

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs

Follow up to #8207
That PR fixes the issue, this PR makes us resiliant to downstream servers throwing exceptions getting code actions in general (and adds ConfigureAwait calls because there were a few missing)

Don't kill all code actions when a delegated server misbehaves

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json

It looks like the .vsix artifact for publishing isn't created unless this changes. Includes fix for dotnet/aspnetcore#46429
FYI @thaystg

Release BlazorWasmDebugging 1.1.4

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs

﻿Here are some Tests demonstrating razor formatting issues.
﻿
This PR contains one ~~two~~ change sets.
* The first has all the Tests that fail.
* ~~The second fixes one of these test.~~
~~I tried to fix the other two as well but wasn't able to. Also I'm not sure if my approach in fixing the first one is aligned to how things should be done.~~
~~**Please check if my assumption about supposed formatting is actually correct.**~~
~~If you can give me some guidance I'm willing to fix the other two tests as well.~~
Issues tracked in:
#8227 
#8228 
#8229

[Tests] Nested formatting issues

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/OutputWindowLogger.cs

- It was silly of me to make this an exception just because we weren't using scopes at the time, especially given that apparently we already had a pattern to do this without the underlying stores having to understand (NoOps).

Don't NotImplemented in OutputwindowLogger

---

Directory.Build.props

Allows linux machines to build the complete solution, without errors about WPF frameworks being missing.

Turn on windows targeting

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Diagnostics/ReportIssuePanel.ts

- The GitHub link in the "Report a Razor issue" command automatically re-directs to the Razor repo, but Phil brought up a good point that we should probably explicitly change this to "razor" (from "razor-tooling").

[VS Code] Update Razor repo link

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DirectoryHelper.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MonitorProjectConfigurationFilePathEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationFileChangeDetectorTest.cs

When recursively digging through directories to find project configuration files (i.e. `project.razor.json`), we didn't handle any `UnauthorizedAccessExceptions` that might be thrown. So, if some sub-directory fails due to permissions access, the entire search would fail, even if a configuration file had already been found.
Beyond the bug fix (which is small), I did a bit of clean up.

Handle UnauthorizedAccessExceptions in DirectoryHelper

---

.editorconfig
src/Compiler/.editorconfig
src/Compiler/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorBaselineIntegrationTestBase.cs

Follow up on #8099.
- Fixes EditorConfig settings.
- Emits baselines in UTF-8 with BOM.
Tested locally with Visual Studio.

Fix UTF-8 BOM settings

---

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Classification.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Semantic/TestFiles/RazorSemanticTokensTests/GenericTypeParameters_Work.txt

- Seen when running locally, the TextMate colorization was missing from the baseline file.

Fix TextMate missing item

---

src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport.csproj
src/Compiler/tools/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal.csproj
src/Compiler/tools/Microsoft.CodeAnalysis.Razor.Tooling.Internal/Microsoft.CodeAnalysis.Razor.Tooling.Internal.csproj
src/Razor/src/rzls/rzls.csproj

- This should hopefully fix our failing internal builds due to duplicate darc publishing.

Fix darc publishing

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/.npmrc
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/.npmrc

This was introduced by yarn when I updated various packages, and because I refuse to acknowledge the existence of the JavaScript ecosystem, I blindly committed it assuming it was correct. What this actually did was ensure that on every build, npm would auth to the package registry, which means my build broke when a PAT expired. This is objectively stupid.

Don't set always-auth

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/TerminateDebugHandler.ts

We cannot use startsWith because if we use it we will kill the process when we close a login window.
When we stop the debugging session we receive 2 event names:
- `Debug Blazor Web Assembly in Browser: https://localhost:7291`
- `Debug Blazor Web Assembly in Browser`
So I think it's okay to keep without the startsWith as it was done before this commit: https://github.com/dotnet/razor/pull/5885 
Fixes: https://github.com/aspnet/AspNetCore-ManualTests/issues/1834

Avoid killing the process when a login window is closed.

---

eng/Versions.props
src/Compiler/Directory.Packages.props
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentFilePathIntegrationTest.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj
src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/Microsoft.AspNetCore.Razor.OmniSharpPlugin.csproj
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj
src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Microsoft.VisualStudio.Editor.Razor.csproj
src/Razor/src/Microsoft.VisualStudio.RazorExtension.Dependencies/Microsoft.VisualStudio.RazorExtension.Dependencies.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common.csproj
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.csproj

We had multiple sets of roslyn references, differing between the compiler and the tooling. This consolidates those versions and updates the compiler references to be inline with the tooling.

Consolidate roslyn versions

---

eng/Versions.props
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/CSharpTestLspServerHelpers.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestRazorDocumentServiceProvider.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/CSharpDiagnosticsEndToEndTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.cs

Follow up to https://github.com/dotnet/roslyn/pull/66748 being available, needed to write proper tests for https://github.com/dotnet/razor/issues/8204 (and have a sane dev experience)
Figured I'd put this up separately so there is less in flight on my machine. Not the worlds most earth shattering tests :)

Add functional test for C# diagnostics

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperBinder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TagHelperBinderTest.cs

Partially reverts https://github.com/dotnet/razor/pull/8135
Unfortunately, it isn't valid to short circuit in all cases. It's possible for a descriptor to have multiple registration keys. We also can't just add it when we create the hash set, because it could be created by a different provider. 
We could probably track which sets a descriptor has been added to, so as to not try and add it multiple times, but I'm not convinced it would be all that much faster (we can benchmark this in another PR if we're interested).

Don't try and de-dup tag helper descriptors

---

src/Compiler/Directory.Packages.props
src/Compiler/tools/Microsoft.AspNetCore.Razor.SourceGenerator.Tooling.Internal/Microsoft.AspNetCore.Razor.SourceGenerator.Tooling.Internal.csproj

This change links all of the files from `Microsoft.AspNetCore.Razor.Utilities.Shared` into `Microsoft.AspNetCore.Razor.SourceGenerator.Tooling.Internal`, now that `Utilities.Shared` is referenced by `Microsoft.AspNetCore.Razor.Language`. Otherwise, `SourceGenerators.Tooling.Internal` will fail to build if anything from `Utilities.Shared` is actually used.
@333fred: I noticed that `Microsoft.AspNetCore.Razor.SourceGenerator.Tooling.Internal` does not directly reference `System.Collections.Immutable`, so it's transitively referencing it through its reference to `Microsoft.CodeAnalysis.CSharp`. Would it make sense to add a direct reference in `SourceGenerator.Tooling.Internal` to ensure that it builds with the same version as `Microsoft.AspNetCore.Razor.Language`?

Update SourceGenerator.Tooling.Internal with Utilities.Shared

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs

To celebrate finally being able to build on my machine, I took a break from firefighting to write some code.
Fixes https://github.com/dotnet/razor/issues/8227
Fixes https://github.com/dotnet/razor/issues/8229
I cannot explain why this doesn't fix the third skipped test, but I wanted to timebox the work so I did.
Thanks @LunicLynx for creating the tests for these, made it much easier

Fix formatting of lines that start with component attributes

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLSPOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLSPOptionsMonitor.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServerWrapper.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/ClientSettingsManager.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorLSPOptionsMonitorTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestRazorLSPOptionsMonitor.cs
src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/ClientSettingsManagerTest.cs

When Razor LSP Server starts, provide the advanced settings available in the ClientSettingsManager

Load Advanced Settings On Server Start

---

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Logging/IOutputWindowLogger.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/OutputWindowLogger.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs

Fixes https://github.com/dotnet/razor/issues/8261
Unfortunately the LSP client packages bring in windows only packages as transitive dependencies, so its hard to notice when adding these things, that we're breaking VS Mac. Hopefully that will be fixed soon on the platform side.
Thanks to @sandyarmstrong for doing the work to find the offending class here.

Move OutputWindowLogger to a VS Windows only project

---

docs/contributing/ASPNetCore-Debugging.md
docs/contributing/BuildFromSource.md
docs/contributing/Roslyn-Debugging.md

Fixes #5996.
- Replaced references to `razor-tooling` with `razor`.
- Updated "Debugging with experimental Roslyn bits" to what actually worked for me.

Update contributing docs

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Folding/FoldingRangeHandler.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Folding/SerializableFoldingRangeResponse.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts

- Implements folding range support in VS Code now that it's supported as a built-in command.
After:
Fixes https://github.com/dotnet/razor/issues/6811

[VS Code] Implement folding range support

---

docs/contributing/Roslyn-Debugging.md

A few steps were missing in the doc guide for locally debugging razor/roslyn together. This PR adds the missing steps.
Also adding steps to troubleshoot when bits get into a bad state
Fixes: https://github.com/dotnet/razor/issues/8305

Update documentation for razor/roslyn debugging

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/DefaultVSLSPTagHelperTooltipFactory.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultVSLSPTagHelperTooltipFactoryTest.cs

Fixes #6998
The actual behavior:
The expected behavior:
The fix:
The changes in this PR helps to add a line of padding in between summaries.
It somehow seems like it is adding two new lines. So I need to figure our why this is happening.
Fixes: #6998

Fix hover when it should separate multiple summaries

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Folding/FoldingRangeHandler.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Formatting/FormattingHandler.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Formatting/RazorFormatOnTypeProvider.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageServiceClient.ts
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts

- This PR fixes several formatting bugs:
- https://github.com/dotnet/razor/issues/8175: If the user had onTypeFormatting enabled, VS Code would try to send us a request that we didn't support. This change adds an empty handler for the time being so we stop throwing the exception.
- https://github.com/OmniSharp/omnisharp-vscode/issues/5561: This is due a bug presumably on VS Code's side where
they'll sometimes send us an end position that exceeds the length of the document. I've filed a bug on them (https://github.com/microsoft/vscode/issues/175298) and have implemented a workaround for the time being.
- (Possibly) https://github.com/dotnet/razor/issues/7038: Wasn't able to directly repro this one, but improved error handling that could potentially resolve the …

[VS Code] Fix various formatting issues

---

src/Shared/Directory.Build.props
src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.csproj

ISSUE:  
In order for consumption of Microsoft.VisualStudio.LanguageServer.ContainedLanguage to work, the upstream Microsoft.AspNetCore.Razor.Utilities.Shared needs to be available.
FIX:
Using the build properties that are used heavily in the src\Razor directories, apply to src\Shared.
VALIDATION:
Validated that in local build, the package is produced in the Debug\NonShipping directory and the package contains the correct binary in three different TFMs.

Have *.Razor.Utilities.Shared package created

---

eng/config/PublishData.json

I checked the [OneNote](https://microsoft.sharepoint.com/teams/managedlanguages/_layouts/OneNote.aspx?id=%2Fteams%2Fmanagedlanguages%2Ffiles%2FTeam%20Notebook%2FRoslyn%20Team%20Notebook%20-%20New&wd=target%28Infrastructure.one%7C0E3C75FE-0827-41BF-9696-F5CD7105BC9A%2FSnapping%20Razor%20-%20LoaT%7C9C7582B1-F81D-44B0-9DB7-1078696B9A53%2F%29) for this step and it looks like we update PublishData but not Versions.props here. I think the only update needed is the PR title for informational purposes.
Does this change look right @allisonchou?

Update versions to 17.6.P3

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormattingPass.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingLanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingTest.cs

This was a lot more complicated than I thought, so after chatting with @ryzngard this is taking the easy way out, since the hard way would require big changes to formatting.
With this change the actual formatting service doesn't check the on type formatting setting, just the LSP endpoints do, with this PR specifically adding that check to the auto insert endpoint. This means the setting will also turn off XML doc comment completion, but I think thats a reasonable compromise for now. It also means the setting has no effect if Single Server is turned off, but we have no reason to think anyone has done that anyway.
There is a comment explaining that, and a bit more, in the code.
Closes https://github.com/dotnet/razor/issues/4336
@phil-allen-msft I think we should take this for M2

Allow formatting service to ignore the OnTypeFormatting option

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/SyntaxNode.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorTranslateDiagnosticsService.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorTranslateDiagnosticsEndpointTest.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1758057
Also should fix these faults:
https://prism.vsdata.io/failure/?query=fe%3Arazor%2Ffault&eventType=fault&failureType=hits&failureHash=9cfb44d6-ba55-60ab-9c03-17719a6d8c93
https://prism.vsdata.io/failure/?query=fe%3Arazor%2Ffault&eventType=fault&failureType=hits&failureHash=8ac6d32c-f098-a26d-a312-0abff8ff630c
https://prism.vsdata.io/failure/?query=fe%3Arazor%2Ffault&eventType=fault&failureType=hits&failureHash=53fd5f93-6e27-d7e7-85f7-b598754ccb70
https://prism.vsdata.io/failure/?query=fe%3Arazor%2Ffault&eventType=fault&failureType=hits&failureHash=eae8ed55-d35c-e440-a6d5-cd7094f88ab6

Null annotate FirstAncestorOrSelf

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1753830
The "Strict" version of this method already has this check, not sure why it was left off the Inclusive version.

Validate range before trying to map

---

src/Compiler/Directory.Build.props

It was pointing to `razor-compiler`. It's an informative property for NuGet listings.

Fix `RepositoryUrl` MSBuild property

---

azure-pipelines.yml
eng/pipelines/test-integration-job.yml
src/Razor/src/Microsoft.VisualStudio.RazorExtension.Dependencies/AssemblyCodeBases.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension.Dependencies/Microsoft.VisualStudio.RazorExtension.Dependencies.csproj
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CSharpCodeActionsTests.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/GoToDefinitionTests.cs

Fixes #8378 if I'm very very very very very very lucky

Re-enable integration tests

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentPresentation/TextDocumentUriPresentationEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentPresentation/TextDocumentUriPresentationEndpointTests.cs

- Drag & drop a .razor file with a code-behind file (.razor.cs) creates anchor tags for both files instead of a component tag. This provides a fix for this issue.
- Add a file like below with a code-behind file:
```cs
using BlazorApp6.Data;
using Microsoft.AspNetCore.Components;
using System;
using System.Threading.Tasks;
namespace BlazorApp6.Data
{
public class FetchDataBase : ComponentBase
{
[Inject] WeatherForecastService ForecastService { get; set; }
protected WeatherForecast[]? forecasts;
protected override async Task OnInitializedAsync()
{
forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
}
}
}
```
By commenting out the C# code block in its corresponding razor file below;
```razor
@inherits FetchDataBase
@page "/fetchdata" …
```

Fix drag/drop

---

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/ClientSettingsManager.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Options/OptionsStorage.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Options/AdvancedOptionPage.cs

The OptionsStorage is exported as part of the MEF composition but is defined in Microsoft.VisualStudio.RazorExtension project. This causes Microsoft.VisualStudio.RazorExtension.dll to be loaded in typing scenarios, though it really shouldn't be. To address that, this change moves the OptionsStorage type into LanguageServerClient.
This should address part of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1752820.

Move OptionsStorage down to avoid image load

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension.Dependencies/AssemblyCodeBases.cs

Pulled from #8349
Removal of upper bound will remove most of the maintenance burden.
Shrinking to a single line makes it must easier to identify which assemblies are missing in future.

Simplify assembly code bases

---

eng/Versions.props

- @dibarbet hit an issue where some Razor package versions were out of sync with O#-roslyn versions, causing integration tests to fail. See https://github.com/OmniSharp/omnisharp-roslyn/pull/2518
- Added a comment to `Versions.props` to ensure we don't hit this again

Add comment to keep package versions in sync with O#-roslyn

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionResolver.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionResolverTest.cs

- `#endregion` was being attached to the closing brace of generated class upon parsing the c# and we were losing that information when creating our `ClassDeclarationSyntax`. The change adds a check to see if the closing brace contains a directive and update our created `ClassDeclarationSyntax` before proceeding
- Add unit test to ensure we correctly extract code with directives
- Small change to fix the code contents of other unit tests since we end up accidentally cutting off the end "}"
Fixes: #8294
Before: 
After:

Check Closing Brace for Directives During ExtractToCodeBehind

---

eng/Publishing.props
src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport.csproj
src/Compiler/tools/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal.csproj
src/Compiler/tools/Microsoft.CodeAnalysis.Razor.Tooling.Internal/Microsoft.CodeAnalysis.Razor.Tooling.Internal.csproj
src/Razor/src/rzls/rzls.csproj

This avoids an issue where the source build intermediate, built on Linux, didn't have the nupkgs in it because they were only packaged on Windows. Instead of restrictig packaging to only Windows, only push nupkgs on Windows, or in source-build situations. This is a little simpler, and has the added advantage that a developer can work on Linux or Mac and produce the nupkgs for testing or dev work.

Use an alternate approach to publishing nupkgs only on Windows

---

eng/Versions.props
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LoggerAdapter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LspLogger.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLSPOptionsMonitor.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLogger.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLoggerProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/OutputWindowLogger.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyBindingRedirects.cs
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Logging/TestOutputLogger.cs

Update binding redirects for Microsoft.Extensions.* dependencies (Primitives etc.)

Update binding redirects for Microsoft.Extensions.* dependencies

---

azure-pipelines.yml
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs

Pulled out of #8133 in case we want to take this for servicing.
|  | Method | Job | RunStrategy|FileType |Mean|Error|StdDev|Op/s|Gen 0|Gen 1|Gen 2|Allocated |
|-------|------------|--------------|---------|------|----------|---------|--------|-------------|--------|---|---|------|
|Before| Lightbulbs| Job-GKMZJP|Default| Small| 378.0 us| 2.41 us| 1.88 us|2,645.85	|19.5313| -|-|	 40 KB |
|After	 |Lightbulbs	 |Job-GKMZJP	  |   Default|Small	|   137.5 us|  1.65 us	|  1.38 us	|7,270.60	|5.8594|-|-|12 KB |
|Before	 |Lightbulbs	  |InProcess	  |Throughput|  Small	|    380.1 us|	  1.27 us	|  1.13 us	|2,630.64	|19.5313|-|-|40 KB |
|After	 |Lightbulbs	 | InProcess	  |Throughput|   Small	|   138.1 us|	  1.87 us	|  2.00 us	|7,239.20	|5.8594|-|-|12 KB |
|Before	 |Lightbulbs	 |Job-GKMZJP	  |   Default| …

[17.5] Cache classified spans and tag helper spans

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs

Reverts dotnet/razor#8437
Necessary changes are already in release/17.6, and this also fails the compile because there are now duplicate instances of methods.

Revert "Merge release/dev17.5 to release/dev17.6"

---

src/Razor/src/rzls/rzls.csproj

- Only publish platform agnostic language server on Windows
- This condition previously existed but was removed in https://github.com/dotnet/razor/pull/8426. We actually still need it since the produced package (e.g. `RazorLanguageServer-PlatformAgnostic-7.0.0-preview.23167.1.zip`) doesn't follow the `*.nupkg` pattern specified in the linked PR.

[Infra] Fix darc duplicate publishing

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/FilePathNormalizer.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormatter.cs

Fixes https://github.com/dotnet/razor/issues/8465
Fixes https://github.com/dotnet/razor/issues/6182
I don't know why we were normalizing a path we got from LSP before sending an LSP request, but seems wrong to me. Also removed a bit of dead code that did the wrong thing too.

Don't normalize URIs that we send to language servers

---

eng/Versions.props
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LoggerAdapter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LspLogger.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLSPOptionsMonitor.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLogger.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLoggerProvider.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/OutputWindowLogger.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyBindingRedirects.cs
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Logging/TestOutputLogger.cs

This reverts commit bf5d35e3f29e93f166006e7d1156108d5d502e39, reversing changes made to c12b6f32ca0b61a9693030eff2da665325acb75e.
- #8422 ended up causing NGEN issues in RPS - see https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/459358
- Validated that reverting PR fixes issue: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/459630
cc @maryamariyan

Revert "Merge pull request #8422 from dotnet/binding-redirect"

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/BoundAttributeDescriptorComparer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/BoundAttributeParameterDescriptorComparer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/ComparerUtilities.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperDescriptorComparer.cs

There was a recent regression in `TagHelperDescriptorComparer` due to several collection properties in the Default* tag helper classes being changed to be backed by immutable collections. There was already a fast path for `Dictionary<TKey, TValue>` to avoid boxing struct-based enumerators and a similar path is now needed for `ImmutableDictionary<TKey, TValue>`.
In addition, a fast path for arrays has been added to avoid calling unnecessarily through `IReadOnlyList<T>`.
The `TagHelperSerializationBenchmark` shows a decent improvement with this change:
``` ini
BenchmarkDotNet=v0.13.2.2052-nightly, OS=Windows 11 (10.0.25314.1010)
Intel Core i7-8700 CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=8.0.100-preview.1.23115.2
[Host]     : .NET 7.0.4 (7.0.423.11508), X64 …
```

Add more runtime checks to ComparerUtilities

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorComponentSearchEngine.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ComponentAccessibilityCodeActionProviderTest.cs

Fixes #4450
Strips type params using DefaultRazorComponentSeachEngine.RemoveGenericContent on the rename code action.

Strip generic type params from rename codeaction

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionResolveEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRegistrationExtension.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionResolveEndpointTest.cs

The code got regressed alongside some of the CLaSP code changes.
Client capabilities was not being initialized for `RazorCompletionResolveEndpoint.cs` anymore therefore the intellisense was showing up as default plain rather than being markdown showing full type name and colored
Fixes #8488

Brings back `GetRegistration` for `RazorCompletionResolveEndpoint`

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorConfigurationService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLSPOptions.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Editor/ClientSettings.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/IClientSettingsManager.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Options/OptionsStorage.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Options/AdvancedOptionPage.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/VSPackage.resx
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.cs.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.de.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.es.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.fr.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.it.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ja.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ko.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.pl.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.pt-BR.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ru.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.tr.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.zh-Hans.xlf
src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.zh-Hant.xlf
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorConfigurationServiceTest.cs
src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/ClientSettingsManagerTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/OnAutoInsertTests.cs

Part of https://github.com/dotnet/razor/issues/6212 and fixes #8499 
We already have all of the code for the option itself, we just were only reading it from VS Code's html settings area. This adds the setting to our Advanced settings page in VS, and reads it from there.

Expose the existing AutoClosingTags option in VS

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentColor/DocumentColorEndpoint.cs

Workaround for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1743689
I can see from the dump that there is a color adornment tagger in web tools that has a stale filename making requests, so figured there is no reason for us to report faults unnecessarily.

Workaround web tools color adornment tagger bug

---

src/Compiler/Microsoft.CodeAnalysis.Razor/src/SymbolExtensions.cs

Check the type simple name first, to avoid allocating a lot of strings via `ToDisplayString()`
In the cold benchmark we see a drop of about 6MB
```
Previous:
|           Method |     Mean |   Error |  StdDev |      Gen0 |      Gen1 | Allocated |
|----------------- |---------:|--------:|--------:|----------:|----------:|----------:|
| Cold_Compilation | 254.5 ms | 4.80 ms | 4.25 ms | 3000.0000 | 1000.0000 |  95.29 MB |
After:
|           Method |     Mean |   Error |  StdDev |      Gen0 |      Gen1 | Allocated |
|----------------- |---------:|--------:|--------:|----------:|----------:|----------:|
| Cold_Compilation | 251.6 ms | 2.77 ms | 2.31 ms | 3000.0000 | 1000.0000 |  89.25 MB |
```
We also see a drop of a 100kb or so on the hot benchmarks, but they already allocated very little.

Avoid allocating when comparing type names

---

azure-pipelines.yml

This breaks up the YAML file such that our Restore, Build, Unit Tests and Integration Tests are now different steps. This makes it much easier for us to tell at a glance:
1. What part of our pipeline failed. 
2. How long are the different parts of our pipeline taking. 
It also means in the future we can get much better metrics via code to answer questions like 
> Which step in our build is failing the most frequently? 
Example of the new display

Break up the YAML file into fine grain steps

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/AllowedChildTagDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/AllowedChildTagDescriptorComparer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/BoundAttributeDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/BoundAttributeDescriptorComparer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/BoundAttributeParameterDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/BoundAttributeParameterDescriptorComparer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeParameterDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeParameterDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRequiredAttributeDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRequiredAttributeDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultTagHelperDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultTagHelperDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/MetadataCollection.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RequiredAttributeDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RequiredAttributeDescriptorComparer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Resources.resx
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperDescriptorComparer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperDiagnostics.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagMatchingRuleDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagMatchingRuleDescriptorComparer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/MetadataCollectionTests.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Remote/RemoteTagHelperDeltaProviderBenchmark.cs
src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ListExtensions.cs
src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PooledObjects/PooledList`1.cs
src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ThreadSafeFlagOperations.cs

This is the first of several changes coming for tag helper descriptors to reduce their memory footprint. In this particular change. I've made tweaks to the memory used by the tag helper descriptors themselves. Future changes will promote sharing objects between tag helper descriptors, stop using a builder pattern for construction, and shrink the serialization payloads of tag helper descriptors.
Here is a summary of the changes:
1. Each object that makes up a tag helper descriptor has a field for storing diagnostics. This is a lot of wasted space since the majority of the objects never have diagnostics and those fields end up holding empty arrays. So, I've added a `ConditionalWeakTable` to store any diagnostics, similar to how green nodes work.
2. I've collapsed loads of boolean fields …

Improve memory used by tag helper descriptors

---

azure-pipelines.yml
eng/cibuild.sh

This PR is best read commit by commit. 
Summary of changes: 
1. Normalize `CIBuild.cmd` and `cibuild.sh` to have same semantics.
2. Remove the `{{ if ... }}` in our Unix builds and use a variable instead as we do in Windows
3. ~~Break up into Restore, Build and Test steps~~

Clean up the YML for our Unix based builds

---

.config/dotnet-tools.json
NuGet.config
eng/AfterSigning.targets

The code for producing the zip of our servers was different per platform:
- Windows: use PowerShell
- Mac: use pwsh 
- Linux: sudo to install then use pwsh
This change unifies everything on `dotnet pwsh` and restores it as a global tool. That makes our zip consistent across platforms and removes the need for a `sudo` call in a build file.

Use powershell global tool

---

azure-pipelines.yml

The last remaining warning in our build, that we control, was about missing TRX files 
This happens because when `enablePublishTestResults: true` is passed to the `jobs.yml` template it will default to looking for TRX results in every job that it creates. The problem is that only integration tests produce TRX files though. Unit tests only produce XML files. The end result is that our Unix jobs were not producing TRX files yet `jobs.xml` produced code to look for them. 
The way the `jobs.yml` template works means every job created will get the parameters passed into the template. There is no way to say "disable TRX in this job". 
To fix this I just had to put our Windows and Unix jobs into different `jobs.yml` template expansions. The one for Unix disables TRX lookup by specifying it's …

Remove TRX warning on Unix builds

---

src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/src/ViewComponentTagHelperDescriptorFactory.cs
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/src/ViewComponentTagHelperDescriptorFactory.cs
src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/src/ViewComponentTagHelperDescriptorFactory.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/BoundAttributeDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultAllowedChildTagDescriptorBuilder.Policy.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultAllowedChildTagDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeDescriptor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeDescriptorBuilder.Policy.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeParameterDescriptorBuilder.Policy.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeParameterDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRequiredAttributeDescriptorBuilder.Policy.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRequiredAttributeDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultTagHelperDescriptorBuilder.Policy.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultTagHelperDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultTagMatchingRuleDescriptorBuilder.Policy.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultTagMatchingRuleDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RazorDiagnosticCollection.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperDescriptorBuilder.PooledBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperPooledObjectPolicy.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/BindTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/ComponentTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/DefaultTagHelperDescriptorFactory.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/EventHandlerTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/KeyTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/RefTagHelperDescriptorProvider.cs
src/Compiler/Microsoft.CodeAnalysis.Razor/src/SplatTagHelperDescriptorProvider.cs
src/Compiler/shared/TagHelperDescriptorJsonConverter.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Serialization/TagHelperDescriptorJsonConverter.cs

This PR introduces object pools for each sort of builder that is used to produce `TagHelperDescriptors`. The primary change related to this is returning the fields of each to a default state of each builder before they are returned to the pool. The rest of the change is primarily updating all of the places in the compiler and tooling that used to call `TagHelperDescriptorBuilder.Create(...)` to now call `TagHelperDescriptorBuilder.GetInstance(...)` and `TagHelperDescriptorBuilder.ReleaseInstance(...)`. Over time, this should improve allocations at design-time by ensuring that we don't _always_ create new builders for every descriptor.

Pool tag helper builders

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/CodeActionExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ConfigurableLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/CSharpCodeActionEndToEndTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionProviderTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs

Something for our dogfooding.
This adds a flag to Preview Features in VS that allows any code action to be displayed, and at least attempted to be applied. Its a good way to find things we can add to our allow list for little to no cost. eg, just from a quick play it looks like "Convert to interpolated string" might be a good candidate. Looks like this:
You can tell if the code action will work, by the preview. eg, this will work:
And this one won't (its trying to offer to change the whole RenderBody method to an expression I think???)
Sometimes it can apply, but the results are pretty funny:
Thats why its a feature flag, and internal only, and off by default. Sorry community 😝 Don't worry, I have a pretty good idea how to make these work, just need some time :)

Add feature flag to show all C# code actions

---

src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport.csproj
src/Compiler/tools/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal.csproj
src/Compiler/tools/Microsoft.CodeAnalysis.Razor.Tooling.Internal/Microsoft.CodeAnalysis.Razor.Tooling.Internal.csproj

Related: https://github.com/dotnet/sdk/pull/31508, https://github.com/dotnet/sdk/pull/31510

Transport `Razor.Utilities.Shared` and its dependencies

---

src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace.csproj

Follow up to the previous PR.
Depending solely on nupkgs doesn't work when tooling projects reference the compliler, because it is published differently. This works around the issue by baking in the compiler DLLs. Since everything is built in this repo, it seems to me like a safe option, because even if there is a breaking compiler change, it can't be done without this project being built too.
FYI @jjonescz. I don't think this will break when the compiler moves to a single DLL, but thought I'd better keep you in the loop :)

Package compiler dependencies in the package

---

src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace.csproj

This package must be referenced because Roslyn doesn't include it.

Reference MS.Ext.ObjectPool package in ExternalAccess.RoslynWorkspace

---

src/Razor/src/rzls/rzls.csproj

In rzls, the package references, Microsoft.Extensions.Logging and Microsoft.Extensions.Configuration, were defined with PrivateAssets="true". (According to git blame, this was done as part of an attempt to fix spurious build issues.) However, it seems that this also means that the libs in these packages are not included in published output, which is critical for rzls.exe to run.

Remove package refs with PrivateAssets="true"

---

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPDocumentSynchronizer.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/LSPDocumentSynchronizer.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs

Temporary workaround for https://github.com/dotnet/razor/issues/8209 for prefix completions.
@DustinCampbell @davidwengier I've been unable to make any additional progress on this document synchronization issue for completion. It still appears that we only end up receiving file version updates after timeout is reached on synchronization, LSP logs seem to show nothing unusual. I'd love either of your insight.
In the meantime, falsely claiming that we are synchronized if we've seen a version > required is a temporary workaround that fixes prefix completions but not postfix completions, and is gated only on the resolve endpoint.

Prefix completion workaround

---

src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport.csproj
src/Compiler/tools/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal.csproj
src/Compiler/tools/Microsoft.CodeAnalysis.Razor.Tooling.Internal/Microsoft.CodeAnalysis.Razor.Tooling.Internal.csproj

Cherry-pick of https://github.com/dotnet/razor/pull/8542 to fix broken flow into SDK: ~https://github.com/dotnet/sdk/pull/31822#issuecomment-1514264257~ https://github.com/dotnet/sdk/pull/31823

[17.6] Transport `Razor.Utilities.Shared` and its dependencies

---

src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/PublicAPI.Unshipped.txt
src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/RazorWorkspaceListener.cs
src/Razor/test/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace.Test/RazorWorkspaceListenerTest.cs

This means we're not holding only project references, and avoids a race condition where document changes after the debounce won't be seen.

Only capture project id, and get the latest project from the workspace

---

src/Razor/test/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace.Test/RazorWorkspaceListenerTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/OnTypeFormattingTests.cs

These tests seem flaky in CI, and failed after 5 iterations on my laptop. Changing to concurrent dictionary seems to fix things.

Fix flaky tests

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorDiagnosticsBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ConfigurableLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsPublisher.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsPublisherTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs

Add `SupportsDelegatedDiagnostics` language server option and request for diagnostics only if it is true.
Related: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1806769

Add LanguageServerOption For Diagnostics

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorDiagnosticsBenchmark.cs

This PR adds benchmarks to compare perf for when there are zero, one or 1000 C# diagnostics in a razor document.
**Note:** The benchmarks are faking a call to roslyn to get the C# diagnostic.
```
// * Summary *
BenchmarkDotNet=v0.13.2.2052-nightly, OS=Windows 10 (10.0.18363.2274/1909/November2019Update/19H2)
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET SDK=8.0.100-preview.2.23157.25
[Host]     : .NET 8.0.0 (8.0.23.12803), X64 RyuJIT AVX2
Job-UVKTRU : .NET 7.0.4 (7.0.423.11508), X64 RyuJIT AVX2
Job-NLOVLU : .NET Framework 4.8 (4.8.4510.0), X64 RyuJIT VectorSize=256
PowerPlanMode=00000000-0000-0000-0000-000000000000
|      Method |        Job |            Toolchain |    N | FileType |           Mean |        Error |       StdDev |         Median | …
```

Adds more diagnostics benchmarks

---

src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace.csproj
src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/PublicAPI.Unshipped.txt
src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/RazorWorkspaceListener.cs
src/Razor/test/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace.Test/RazorWorkspaceListenerTest.cs

When I originally wrote this, I was smart enough to not generate the json file if there are no razor documents in a project, but it turns out for a reasonable sized project there are a _lot_ of workspace events flying around. This PR tweaks things so that we can just ignore any event for a project, until we get confirmation that it actually has a razor document in it.

Don't create task schedulers until we know we'll need one

---

eng/Versions.props
src/Compiler/Directory.Packages.props
src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace.csproj
src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.csproj

Fixes: https://github.com/dotnet/razor/issues/8656
This is a backport of source-build patch: https://github.com/dotnet/installer/pull/16260
Razor source-generator was including SBRP package for `Microsoft.Extensions.ObjectPool` which resulted in `Microsoft.Extensions.ObjectPool.dll` being a reference assembly. This was introduced with the following `razor` change: https://github.com/dotnet/razor/pull/8542
Package version property was incorrect - source-build could not override with live version of `Microsoft.Extensions.ObjectPool` package.
This PR does not address other instances of similarly named packages using `MicrosoftExtensionsPackageVersion` property.

Fix Microsoft.Extensions.ObjectPool package version

---

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/CSharpTestLspServerHelpers.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/DefinitionEndpointDelegationTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorTranslateDiagnosticsEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/TestRazorSourceDocument.cs

Extracted out of other work I'm doing. A fair bit of our test infra didn't support .razor files, which was surprising.

Allow testing razor files, not just cshtml files

---

src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/RazorWorkspaceListener.cs
src/Razor/test/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace.Test/RazorWorkspaceListenerTest.cs

Found this on my machine. Seems like a good change. I guess I missed committing it last time 🤷‍♂️
Unlikely to be hit in real life anywhere, so I don't think its too important :)

Don't create a task scheduler if the project doesn't exist

---

src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest

Roslyn has special logic to replace the razor SDK generator with the one from the VSIX. However we get the list of assemblies to replace from the VSIX, and we weren't listing the dependencies as analyzers. 
In the main process these assemblies are present by virtue of the tooling being loaded. In the OOP scenario, we only load the ones listed from the main process, and so they never get loaded.

Include the missing deps as analyzer references

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeParameterDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRequiredAttributeDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultTagHelperDescriptorBuilder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/MetadataCollection.Enumerator.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/MetadataCollection.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/MetadataCollectionTests.cs

This change corrects the nullability annotations for `MetadataCollection`, since it there are cases where tag helper metadata can have null values. In addition, I've added a struct-based enumerator, which will be used in future work to avoid allocations when iterating metadata.

Small improvements to MetadataCollection

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorDiagnosticsBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ConfigurableLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/OpenDocumentGenerator.cs
src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedDocumentPublisherTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/OpenDocumentGeneratorTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs

Right now we monitor for .razor files being open and closed, and we stop generating and pushing code for closed documents. Sometimes this is problematic because we end up sending didChange notifications based on our understanding of things (document is going from empty to not), but the receiving end, if it holds documents open, will see document content being duplicated.

Allow for clients that always want to generate code all the time

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LoggerAdapter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServerWrapper.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorRequestContextFactory.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs

Fixes #8704
Makes our loghub logs look like this:
Each activity is essentially an LSP request, with log messages scoped within them. The "Activity" column on the left should have the LSP message as its value, but that doesn't seem to happen for local dev, so best I can do is hope this works when we get a feedback item. It also doesn't happen for Roslyn when doing local dev, but does in feedback items, so I'm hopeful 😬

Make our logs a bit nicer

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json
src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/CodeDirective.ts
src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap

Fixes https://github.com/dotnet/razor/issues/8681
As usual for TextMate changes, review commit by commit will make things easier.
First commit is some new tests to ensure good coverage, and repro the bug.
Second commit is the snapshot changes for the new tests.
Third commit fixes the bug in the grammar.
Fourth commit is the update to the snapshot, which clearly indicates the fix.

Fix TextMate classification of variables starting with `code`

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CSharpStatementBlockOnTypeFormattingTest.cs

- Some code actions in VS Code would fail if the edit involved adding a line at the end of the file. This was due to a bug with source text boundaries.
- Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1821816

Fix end of document formatting

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultClientNotifierService.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/TelemetryReporter.cs

To help see if we can track down the cause of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1825424
Haven't had any hits on this today, from a quick run through a few things, so I don't think this will be annoying.
**If you see this pop up, please debug and see why 😀**

Add a debug assert for faults at debug time

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Versions.props

Related to https://github.com/dotnet/razor/issues/8293
For .NET source-build, repos must target NetCurrent (.NET 8.0) and/or NetStandard.  This initial changes for https://github.com/dotnet/razor/issues/8293 added .NET 8.0 on top of the existing tfms.  This PR conditions source-build to only target net8.0 in order to eliminate prebuilts.

During source build, target net8.0 only

---

Directory.Build.props
eng/SourceBuildPrebuiltBaseline.xml
eng/Versions.props

Because Razor flows into multiple SDK major version branches, the TFM logic for source-build needs to be updated so that only the "current" TFM for the SDK is targeted in order to prevent prebuilts.
This is in response to https://github.com/dotnet/razor/pull/8779/files#r1213897264.

Refactor SB TFM logic to account for multiple branch dependents

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/CodeGeneration/CodeWriter.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/CodeGeneration/CSharpCodeWriterTest.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentWithConstrainedTypeParameters/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentWithConstrainedTypeParameters_WithSemicolon/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentWithTypeParameterArray/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentWithTypeParameterValueTuple/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentWithTypeParameters/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentWithTypeParameters_WithSemicolon/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithCssScope/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithKey_WithChildContent/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithRef_WithChildContent/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ProducesEnhancedLinePragmaWhenNecessary/TestComponent.mappings.txt
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/WhiteSpace_WithPreserveWhitespace/TestComponent.mappings.txt

The CodeWriter counts line breaks as it writes to an underlying StringBuilder. However, it would count incorrectly if passed a start index and length representing a portion of a string. Essentially, it would count past the end of the string portion to the real end of the string. So, any line breaks appearing _after_ startIndex + count would be counted, even though those line breaks weren't be written to the StringBuilder.
Note: I verified that the updated compiler test base lines are now accurate with regard to the line numbers that changed. It seems that we never found this issue because the tooling layer relies the absolute index of source mappings, and not the line and line character index values. However, I found it while converting this method to use `ReadOnlySpan<char>` (coming in a …

Fix issue in CodeWriter when counting line breaks

---

azure-pipelines.yml

This has been discussed a few times, thought i'd have a crack at it.
@jaredpar PTAL
Fixes https://github.com/dotnet/razor/issues/8809

Don't run integration tests on official builds

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/TagHelperParseTreeRewriter.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperBinder.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/TagHelperParseTreeRewriterTest.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/TagHelperRewritingTestBase.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TagHelperBinderTest.cs

GCPauseWatson reports high GC pressure caused by frequent dictionary resizes in this code:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1824275
We attempt to reduce these by giving the dictionary a reasonable size to start with.
-
Fixes:
- Preallocate a dictionary large enough for all the likely additions we'll make.

Prevent large number of dictionary resizes

---

.vscode/settings.json
azure-pipelines-integration-dartlab.yml
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/ConditionalSkipIdeFactAttribute.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DiagnosticTests.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/FlakyFactAttribute.cs

Add an attribute that will run tests if the RAZOR_RUN_FLAKY_TESTS is set, otherwise they will be skipped.

Add flaky test attribute

---

eng/Versions.props

- Upgrades Microsoft.VisualStudio.Telemetry (to fix transitive dependency to an older `System.Private.Uri`): `Microsoft.VisualStudio.Telemetry` > `System.Diagnostics.Tracing` > `runtime.any.System.Runtime` > `System.Private.Uri`
- Upgrades Microsoft.AspNetCore.App to 7.0.5
FYI usage in 
https://github.com/dotnet/razor/blob/ae0352cb437483915fa7e06ffa19449153246c89/src/Compiler/Directory.Packages.props#L7
Addresses https://github.com/dotnet/announcements/issues/250

Updates package version dependencies, fixing interoperability issues

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensBenchmark.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensRangeEndpointBenchmark.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensScrollingBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/RazorSemanticTokensLegend.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/SemanticTokensRangeEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/IRazorSemanticTokenInfoService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/RazorSemanticTokensInfoService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/RazorSemanticTokenInfoServiceTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokenTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestRazorSemanticTokensLegend.cs

Fixes https://github.com/dotnet/razor/issues/8791

Don't use statics for semantic tokens legend

---

src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/TestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/ThrowingTraceListener.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractIntegrationTest.cs

This change sets `DefaultTraceListener.AssertUiEnabled` to false during test runs to avoid displaying assert dialogs, which can hang CI machines. To ensure that we continue seeing assertions fail during debug tests (just without UI) a new `ThrowingTraceListener` has been added.

Don't show assert dialog UI during test runs

---

Directory.Build.props
Razor.Slim.slnf
Razor.sln
src/Compiler/Microsoft.Net.Compilers.Razor.Toolset/Microsoft.Net.Compilers.Razor.Toolset.csproj
src/Compiler/Microsoft.Net.Compilers.Razor.Toolset/build/Microsoft.Net.Compilers.Razor.Toolset.targets
src/Compiler/Microsoft.Net.Compilers.Razor.Toolset/buildMultiTargeting/Microsoft.Net.Compilers.Razor.Toolset.targets

Similar to the Microsoft.Net.Compilers.Toolset package that we use in roslyn, this nuget package will override the generators used by a project, replacing them with the specific versions from this package. The purpose of this package is to allow shipping hotfixes to customers directly in a simple manner, without having to ask them to manually do a bunch of msbuild magic or replacing existing dlls. It may be helpful to reference the targets that add the razor generators to the compilation in the first place when reviewing: https://github.com/dotnet/sdk/blob/main/src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.SourceGenerators.targets#L15.

Add Microsoft.Net.Compilers.Razor.Toolset

---

eng/Version.Details.xml
eng/Versions.props

Contributes to: https://github.com/dotnet/source-build/issues/3224
This dependency is needed for source-build PVP flow, which was enabled for `razor` with https://github.com/dotnet/installer/pull/16495
Fix for ttps://github.com/dotnet/source-build/issues/3224 will enable `razor` to consume live `runtime` and `aspnetcore` packages, during product source-build.

Add System.Collections.Immutable package dependency

---

src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport.csproj
src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj
src/Compiler/Microsoft.Net.Compilers.Razor.Toolset/Microsoft.Net.Compilers.Razor.Toolset.csproj

Fixes errors in https://github.com/dotnet/sdk/pull/33125.

Transport EA.RazorCompiler DLL

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRazorTagHelperContextDiscoveryPhase.cs
src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PooledObjects/PooledArrayBuilder`1.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1826609

[Perfathon] Stop resizing a list

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/CodeActionExtensions.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/CSharpCodeActionEndToEndTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CSharpCodeActionsTests.cs

Fixes https://github.com/dotnet/razor/issues/8578
TL;DR: I added 4 tests per line of code, and I expect everyone of you to do the same from now on! 😛
This isn't _perfect_ because cursor position after the code action can be questionable, and there is no way for us to trigger a rename of the introduced local after the code action executes, but neither of those things are possible to make any better with the current LSP spec and client implementations, so here we are. I basically just played around with this in VS with all of the possibilities I could think of, and couldn't break it, so I figure its better than not having the code action available.
Looks like this:

Allow the Introduce local code action to run in code blocks

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/RazorSemanticTokenInfoServiceTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/RazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_MultiLineCommentWithBlankLines.semantic.txt
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/RazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_MultiLineCommentWithBlankLines_LF.semantic.txt
src/Razor/test/testapps/ComponentApp/Components/Pages/SemanticTokens_LargeMultiLineComment.razor

Fixes #6756
Fixes #8176
The compiler team fixed the perf of `GetContent()` in https://github.com/dotnet/razor/pull/8032 but we were still being pretty naive in our usage here, and the use of `Environment.NewLine` was just wrong.
Results show no harm without a large comment, but a big saving in allocations when there is a large comment.
Old:
|                        Method | WithMultiLineComment |     Mean |    Error |   StdDev |   Median |      Min |       Max |   Gen0 |   Gen1 | Allocated |
|------------------------------ |--------------------- |---------:|---------:|---------:|---------:|---------:|----------:|-------:|-------:|----------:|
| RazorSemanticTokensRangeAsync |                False | 53.43 us | 1.057 us | 2.428 us | 53.54 us | 48.58 us |  60.56 us | 0.6104 |      - |   3.75 …

Fix perf of multiline semantic tokens, and LF handling of same

---

src/Razor/src/rzls/rzls.csproj

This is a follow up PR to https://github.com/dotnet/razor/pull/8806
The rslz project picks up the older version of System.Private.Uri. Using this fix to adds direct reference to System.Private.Uri.
This makes sure the restore steps would no longer pick up the older version (4.3.0) of System.Private.Uri.

Fixes interoperability issue for System.Private.Uri

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/DisposableAction.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/TokenizerBackedParser.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundParser.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs

This is a small change that removes some unnecessary heap allocations.

Change DisposableAction to ref struct

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/ClassifiedSpanVisitor.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/ItemCollection.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/RazorSyntaxTreeExtensions.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperSpanVisitor.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Serialization/TagHelperDeltaResult.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDocumentMappingServiceTest.cs
src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ImmutableArrayExtensions.cs
src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PooledObjects/PooledArrayBuilder`1.cs

As I work on the legacy editor shim, I'm trying to pull bits of clean up and minor improvements into separate PRs.
* Renamed `ImmutableArray<T>.Builder.SetCapacityIfNeeded(...)` extension method to `SetCapacityIfLarger` to match other similar extension methods.
* Add `ItemCollection.TryGetValue<TKey, TValue>(...)` method to clean up calling code.
* Add `ImmutableArray<T>.Builder.DrainToImmutable()` extension method.
* Return `ImmutableArray<T>` from `RazorSyntaxTreeExtensions.GetClassifiedSpans()` and `RazorSyntaxTreeExtensions.GetTagHelperSpans()`.
* Add `ImmutableArray<T>.SelectAsArray(...)` extension method.

Return ImmutableArray<T> in legacy RazorSyntaxTreeExtensions

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/RazorLanguageServerCustomMessageTargets.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedTypes.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SpellCheck/DocumentSpellCheckEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SpellCheck/WorkspaceSpellCheckEndpoint.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SpellCheck/DocumentSpellCheckEndpointTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/WrapWithTagTests.cs

Add spell checking endpoints

---

build.cmd
src/Razor/src/rzls/rzls.csproj

This addresses some feedback from #8762
﻿

Clean up from previous PR

---

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorCodeActionsBenchmark.cs
src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensRangeEndpointBenchmark.cs
src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.OmniSharp/Project/OmniSharpTelemetryReporter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/DelegatedCodeActionParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/DocumentPullDiagnosticsEndpoint.cs
src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/ITelemetryReporter.cs
src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/NoOpTelemetryReporter.cs
src/Razor/src/Microsoft.VisualStudio.Editor.Razor/TelemetryReporter.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/CSharpCodeActionEndToEndTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs

Includes correlationId, a Guid we generate for the sub LSP call to correlate between the calls from Razor Code Action LSP request and C# or Html LSP.
Here's a PR adding a similar telemetry added earlier for Diagnostics in Preview 2: https://github.com/dotnet/razor/pull/8789

Adds Telemetry for CodeAction

---

eng/Versions.props

When building a .NET core app we implicitly pull down references for the runtime. e.g. `Microsoft.NetCore.App.Runtime.linux-arm` when building for Linux. At the moment our builds are pulling down 7.0.5 but CG is asking to be 7.0.7.
So this PR updates MicrosoftAspNetCoreAppVersion to 7.0.7.
Here is a recent [Component Governance - Compliance (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_componentGovernance/205182?_a=alerts&typeId=13385733&alerts-view-option=active) report: [Pipelines - Run 20230624.1 (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7971461&view=results) taken from merged PR [#8863](https://github.com/dotnet/razor/pull/8863).
The report shows the `Microsoft.NETCore.App.Runtime.win-arm64` items are …

Fixes Microsoft.NETCore.App.Runtime Component Governance issues

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRazorTagHelperContextDiscoveryPhase.cs
src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTagHelperTests.cs
src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorTagHelperTests/GlobalPrefixedDirective/Views_Home_Index.html
src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorTagHelperTests/UrlResolutionTagHelper/Views_Home_Index.html

Fixes errors reported in https://github.com/dotnet/aspnetcore/pull/49034#issuecomment-1608571858.
Fixes https://github.com/dotnet/razor/issues/8884 (a regression introduced by https://github.com/dotnet/razor/pull/8857).

Handle `global::` in `@addTagHelper`

---

SpellingExclusions.dic
eng/Versions.props
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/CSharpTestLspServer.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/CSharpTestLspServerHelpers.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/LanguageServerTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/CSharpCodeActionEndToEndTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentHighlighting/DocumentHighlightEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/HoverInfoServiceTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokenTestBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SpellCheck/DocumentSpellCheckEndpointTest.cs
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj
src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/RazorTestResources.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Serialization/TagHelperDescriptorSerializationTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/TagHelperDescriptorCacheTest.cs
src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/Serialization/TagHelperResolutionResultSerializationTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionResolveHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentHighlightHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/RenameHandlerTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/SignatureHelpHandlerTest.cs

I was intending this to be a little cleanup PR after the Roslyn bump, so use the Roslyn `AssertEx.EqualOrDiff` method, which is an easier to discover signature than `new XUnitVerifier().EqualOrDiff` (which also introduces a whole package reference, and creates a new object, just to call an extension method that is part of a different package we were already referencing 🤷‍♂️). It ended up being a little more. Sorry!
* Removed XUnitVerifier
* Added reference to MS.CA.Test.Utilities
* This broke tooling tests that used our test LSP, because that DLL contains analyzers that have an infinite loop
* Excluded that DLL from our analyzers to fix that issue
* Added "Blazor" to our dictionary because it annoyed me
* Renamed `TestResources` to `RazorTestResources` because the name clashed with a …

Remove XUnitVerifier and use the roslyn utilities that the compiler references

---

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackRazorConfiguration.cs

Fixes https://github.com/dotnet/razor/issues/8572
I don't know _why_ the fallback configuration is being used, so logged https://github.com/dotnet/razor/issues/8905 to investigate that further. This mitigates the problem though.

Make the latest configuration actually be somewhat recent

---

eng/Versions.props
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultWindowsRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/FallbackWindowsRazorProjectHost.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/IUnconfiguredProjectCommonServices.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/UnconfiguredProjectCommonServices.cs
src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultWindowsRazorProjectHostTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackWindowsRazorProjectHostTest.cs
src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/TestProjectSystemServices.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Commands.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Text.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/ProjectTests.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/RazorProjectConstants.cs

This is the first part of https://github.com/dotnet/razor/issues/8879
I'm hoping to do the changes in managable (to review) chunks, but with the holidays in the US and potential conflicts from other PRs, that might not be possible.
What this does is change our CPS code from only getting updates about a single TFM in a mutli-target project, to getting updates for all of them. There is nothing that takes advantage of this _yet_, but without this the rest wouldn't be possible. There is also some extra stuff here to remove state from the `WindowsRazorProjectHostBase` class because it contianed a bunch of state about the last project we got updates for, and its documents, and obviously that doesn't work in a mutli-target world. No state will make it easier to make more change in future anyway. …

Subscribe to all target frameworks in the project file

---

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Completion/RazorCompletionItemProvider.ts

we don't support commands in our markdown documentation for completion, so just remove it entirely
Tested in a cshtml and .razor file:
* CSharp completion
* HTML completion (links to MDN still work)
* Razor completion

Remove unsupported feature

---

eng/config/PublishData.json

Takes 17.8 P1 PRs out of draft mode. This enables more checks to run by default.

[Infra] Publish 17.8 P1 VS PRs 

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/CSharpIdentifier.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Components/ComponentDesignTimeNodeWriter.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/CSharpLanguageCharacteristics.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/CSharpTokenizer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/HtmlTokenizer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/ImplicitExpressionEditHandler.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/ParserHelpers.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/SourceLocationTracker.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/Tokenizer.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Microsoft.AspNetCore.Razor.Language.csproj
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/SyntaxNodeExtensions.cs
src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/StringTextSnapshot.cs

The language level currently doesn't have a reference to MS.CA.CSharp, which makes many things quite difficult, and resulted in a number of copy/pastes of utility functions from roslyn over to razor. This is the start of addressing that, adding a reference to MS.CA.CSharp and eliminating some of the simpler helpers that were copy/pasted. Contributes to https://github.com/dotnet/razor/issues/8445.

Add reference to Microsoft.CodeAnalysis.CSharp

---

src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageConfigurationTest.cs

Tried to have a go at fixing https://github.com/dotnet/razor/issues/8916 but my regex-foo is weak. Thought I'd put up this test harness if anyone wants to have a crack.

Create tests for onEnterRules in language configuration json

---

.github/fabricbot.json

- Sets 'Next' milestone on merged PRs to main, which Tigers at the end of each sprint can then switch to the correct milestone. This is aligned with how Roslyn does things today.

[Infra] Set 'Next' milestone on merged PRs to main

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/CSharpTokenizer.cs

As noted in https://github.com/dotnet/razor/pull/8914, these can be static fields.

Mark lambdas as static

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs

Fixes https://github.com/dotnet/razor/issues/8915
Another layer to the house of cards :(

Single line explicit expressions don't affect indentation so aren't "significant"

---

src/Compiler/Directory.Build.props

These were duplicated at the repo root, so I removed them. Note that this will make the Compilers layer langversion be preview now, not latest, which I assume we are fine with.

Remove a couple of duplicate props

---

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/SolutionExplorerInProcess.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/ProjectTests.cs
src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/RazorProjectConstants.cs

After writing a message in teams that we didn't have tests for opening existing projects, I realised that there wasn't a reason we couldn't. That also made me realise we could use the same trick (closing and opening a solution) to work around CPS limitations for switching to multi-targeting while a project is open.

Add a couple of basic project operation tests

---

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/ChildSyntaxList.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/SyntaxKind.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/SyntaxNode.cs
src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Syntax/FindTokenTests.cs
src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PooledObjects/PooledArrayBuilder`1.cs

This implements `SyntaxNode.FindToken`, as was discussed a couple of months ago. The basic semantics of the method are very similar to Roslyn's implementation, but with one significant difference: no attempt is made to ignore any trivia other than whitespace. To recap, this means the rules for `FindToken` are:
1. Find the SyntaxToken that covers the position requested.
2. Scan backwards until a non-whitespace token is encountered. If it's a newline, goto 3. Otherwise, return the token.
3. Scan forwards until a non-whitespace, non-newline token is encountered. Return this token.
There's an additional complication here as well that Roslyn does not have to deal with: because SyntaxToken is a reference type and inherits SyntaxNode, it is possible to call FindToken on that token. If that token …

Add `FindToken` to `SyntaxNode`

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs

Text edit on the file being renamed gets lost.
To fix this we first apply text edits and then
apply file rename as the last thing to do.
To do:
Contributes to: #8541

Rename bugfix - When component is in the same file

---

azure-pipelines.yml

Enabling **BinSkim** scan over build artifacts in CI based on company requirements.
We are required to run SDL tools on official builds and implement automated bug filling for the tools output. Currently we are running SDL checks over the source code in the nightly builds, inline in the builds for some of the product repos and in the .NET staging pipeline, but to be compliant we need to also run BinSkim over the produced artifacts.
This PRs is enabling **BinSkim** checks in the `Run SDL tool job` of [razor-ci-official](https://dev.azure.com/dnceng/internal/_build?definitionId=262&_a=summary).
More information is in the [Automate BinSkim runs over official builds issue](https://github.com/dotnet/arcade-services/issues/2647)

Enable Binskim scan in CI builds

---

src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor/.editorconfig
src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor/InternalAPI.Shipped.txt
src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor/InternalAPI.Unshipped.txt
src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor.csproj
src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor/PublicAPI.Shipped.txt
src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor/PublicAPI.Unshipped.txt

Adding API analyzers to avoid future breaking changes that affect the legacy editor.
Related to #8810

Add API analyzers to ExternalAccess.LegacyEditor

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/GenerateMethodCodeActionParams.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/CodeBlockService.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/GenerateMethodCodeActionProvider.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/GenerateMethodCodeActionResolver.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/RazorCodeActionFactory.cs
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/SR.resx
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.cs.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.de.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.es.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.fr.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.it.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.ja.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.ko.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.pl.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.pt-BR.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.ru.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.tr.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.zh-Hans.xlf
src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.zh-Hant.xlf
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestDocumentContextFactory.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestDocumentSnapshot.cs
src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.cs

Related: #4381 
- 1st commit:
- Uses information from project.razor.json to add fully qualified type parameters to the generate event handler code action. Note that this also takes care of user defined events and event args.
- Update tests to reflect the new parameters. 
- 2nd commit:
- Provide a lightbulb to generate the async version of the generate event handler since blazor supports async event callbacks.
- Add some more test scenarios that test generating the async version.
VS:
VSCode:

Generate EventHandler CodeAction: Add Async Version and Fully Qualified Type Params

---

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DirectoryHelper.cs

Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1813770/
Adding the missing `IOException` catch for `DirectoryHelper.GetDirectory` similar to how `DirectoryHelper.GetFiles` already has it.
Related to PR dotnet/razor#8219

Handles `IOException` for `DirectoryHelper.GetDirectories`

---

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs

It came up at triage today, that a user found a lot of task cancelled exceptions in the output window, and perhaps because of that detail, didn't include much info about the actual issue they were running into. Either way, these serve no useful purpose.

Don't log task cancellations to the output window
