azure-pipelines.yml
We need more than the default.
=> Capture VSIX and MPack build artifacts

azure-pipelines.yml
We need the trailing ; on the URL, but that's not very friendly for YAML.
=> Simplify manifest publising

eng/AfterSigning.targets
=> Fix manifest generation

eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorDocumentServiceProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/RazorDynamicFileInfoProvider.cs
This will require a coordinated VS insertion.
=> React to breaking changes from dotnet/roslyn#31397

Directory.Build.props
The bug in dotnet/Arcade has be fixt
=> Remove SourceLink workaround

restore.cmd, restore.sh
Proposing we add these. It's part of my workflow to do a restore before
opening VS because I always disable package restore inside VS.
Any objections?
=> Add dedicated scripts for restore

src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
Fixes https://github.com/aspnet/AspNetCore/issues/5103 https://github.com/aspnet/AspNetCore/issues/5094
=> Update vsixmanifest for dev16

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlMarkupParser.cs
We used to parse things like 
```
<text    /    
>
```
as a single tag. Fixing this.
=> Minor text tag fix

azure-pipelines.yml
These disappeared at some point :(
=> Add back nuget packages as artifacts

global.json, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest21.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest22.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerTestFixture.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildServerTestFixtureBase.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/LegacyBuildServerTestFixture.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildIntegrationTestBase.cs, src/Razor/test/testapps/AppWithP2PReference/AppWithP2PReference.csproj, src/Razor/test/testapps/LargeProject/LargeProject.csproj, src/Razor/test/testapps/MvcWithComponents/MvcWithComponents.csproj, src/Razor/test/testapps/SimpleMvc/SimpleMvc.csproj, src/Razor/test/testapps/SimpleMvc22/Models/ErrorViewModel.cs, src/Razor/test/testapps/SimpleMvc22/Program.cs, src/Razor/test/testapps/SimpleMvc22/SimpleMvc22.csproj, src/Razor/test/testapps/SimpleMvc22/Views/Home/About.cshtml, src/Razor/test/testapps/SimpleMvc22/Views/Home/Index.cshtml, src/Razor/test/testapps/SimpleMvc22/Views/Shared/_Layout.cshtml, src/Razor/test/testapps/SimpleMvc22/Views/Shared/_ValidationScriptsPartial.cshtml, src/Razor/test/testapps/SimpleMvc22/Views/_ViewImports.cshtml, src/Razor/test/testapps/SimpleMvc22/Views/_ViewStart.cshtml, src/Razor/test/testapps/SimpleMvcFSharp/SimpleMvcFSharp.fsproj, src/Razor/test/testapps/SimplePages/SimplePages.csproj
Fixes https://github.com/aspnet/AspNetCore/issues/5101
=> Add a test using 2.2 project with current Sdk

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/HtmlMarkupParser.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/Legacy/MarkupElementGroupingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/HtmlTagsTest/VoidElementFollowedByOtherTag.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/MarkupElementGroupingTest/Handles_SpecialCasesVoidTags_WithNoEndTags.cspans.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/MarkupElementGroupingTest/Handles_SpecialCasesVoidTags_WithNoEndTags.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperBlockRewriterTest/AllowsCompatibleTagStructures4.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperBlockRewriterTest/CanHandleWithoutEndTagTagStructure3.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperBlockRewriterTest/CanHandleWithoutEndTagTagStructure4.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperBlockRewriterTest/CanHandleWithoutEndTagTagStructure5.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperBlockRewriterTest/TagHelperParseTreeRewriter_AllowsInvalidHtml4.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperBlockRewriterTest/UnderstandsMinimizedAttributes_PartialTags8.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperBlockRewriterTest/UnderstandsMinimizedAttributes_PartialTags8.tspans.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperParseTreeRewriterTest/UnderstandsAllowedChildren10.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperParseTreeRewriterTest/UnderstandsAllowedChildren11.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperParseTreeRewriterTest/UnderstandsAllowedChildren14.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperParseTreeRewriterTest/UnderstandsAllowedChildren6.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperParseTreeRewriterTest/UnderstandsNestedVoidSelfClosingRequiredParent1.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperParseTreeRewriterTest/UnderstandsNestedVoidSelfClosingRequiredParent2.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperParseTreeRewriterTest/UnderstandsNestedVoidSelfClosingRequiredParent3.stree.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/ParserTests/TagHelperParseTreeRewriterTest/UnderstandsNestedVoidSelfClosingRequiredParent5.stree.txt
Fixes https://github.com/aspnet/AspNetCore/issues/6183
=> Fix void tags grouping logic

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/RazorDeveloperTools/RazorDeveloperTools.csproj
These things are .vsix or .mpack and don't make sense as packages.
=> Unmake .nupkgs for tooling

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets, src/Razor/test/testapps/ComponentLibrary/ComponentLibrary.csproj, src/Razor/test/testapps/MvcWithComponents/MvcWithComponents.csproj
Workaround for https://github.com/aspnet/AspNetCore/issues/6500
=> Use a property to allow specifying component globbing pattern

src/Razor/src/Microsoft.AspNetCore.Razor.Language/RazorProject.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/RazorProjectFileSystem.cs
Addresses aspnet/AspNetCore#4876
=> Remove obsolete RazorProject ViewEngine based create method.

azure-pipelines.yml
Enable publishing to bar
Use jobs yaml pipeline schema
Validated with internal build - https://dev.azure.com/dnceng/internal/_build/results?buildId=73376
FYI @rynowak @natemcmaster @mmitche
=> Publish to bar, use updated yaml templates schema

eng/configure-toolset.ps1, eng/configure-toolset.sh
=> Force repo-local install of dotnet

global.json
Updates to the version we are using in aspnet/Extensions
=> Update dotnet SDK

azure-pipelines.yml
This should help with aspnet/AspNetCore-Internal#1575 while we wait for a more complete fix.
=> Increase timeout to allow BAR to publish

eng/Versions.props
=> Update package branding to 3.0.0-preview4

src/Razor/test/Microsoft.AspNetCore.Razor.Test.ComponentShim/Microsoft.AspNetCore.Components/EventCallbackFactory.cs
Yes, this is really supposed to be string. Yes. Really.
=> Fix a bad copy-paste

.github/CODEOWNERS
=> Add CODEOWNERS starting point

src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorProjectFileSystem.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/DefaultRazorProjectFileSystemTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/8185
=> Correctly normalize file path from network shares

activate.ps1
This is a copy paste from AspNetCore
=> Added activate.ps1 to set DOTNET_ROOT to Path

eng/Version.Details.xml, eng/Versions.props
- add `CoherentParentDependency` attributes then run `darc update-subscriptions ...`
=> Update to coherent dependencies using private `darc` build

src/Razor/tools/RazorSyntaxGenerator/Model/AbstractNode.cs, src/Razor/tools/RazorSyntaxGenerator/Model/Comment.cs, src/Razor/tools/RazorSyntaxGenerator/Model/Field.cs, src/Razor/tools/RazorSyntaxGenerator/Model/Kind.cs, src/Razor/tools/RazorSyntaxGenerator/Model/Node.cs, src/Razor/tools/RazorSyntaxGenerator/Model/PredefinedNode.cs, src/Razor/tools/RazorSyntaxGenerator/Model/Tree.cs, src/Razor/tools/RazorSyntaxGenerator/Model/TreeType.cs, src/Razor/tools/RazorSyntaxGenerator/README.md
Follow up to https://github.com/aspnet/AspNetCore-Tooling/pull/313.
I somehow messed up when adding things to git and I forgot a folder full of types in the previous PR 😄
=> Added missed files to RazorSyntaxGenerator

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest.cs
mitigates aspnet/AspNetCore-Internal#1931
=> skip flaky razor build integration test

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorDirectiveCompletionProvider.cs
Follow up to https://github.com/aspnet/AspNetCore-Tooling/pull/335
=> Missed change

eng/Version.Details.xml, eng/Versions.props
- previous update was incoherent and not caught until we reached aspnet/AspNetCore
- upgrades core-setup and Extensions dependencies but downgrades CoreFx to achieve coherency
=> Manually update dependencies from CoreFx, core-setup and Extensions

eng/Version.Details.xml, eng/Versions.props
=> Manually (and coherently) update dependencies from core-setup and Extensions

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/SourceTextExtensions.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DefaultDocumentSnapshotTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/8635
- Manually verified FAR works again in VS
=> Flow relative path when creating RSD in DocumentState

eng/Version.Details.xml
=> Fix core-setup URI

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIncrementalismTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntrospectionTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildIntegrationTestBase.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/ProjectDirectory.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/PublishIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj, src/Razor/test/testapps/AppWithP2PReference/AppWithP2PReference.csproj, src/Razor/test/testapps/ClassLibrary/ClassLibrary.csproj, src/Razor/test/testapps/ClassLibrary2/ClassLibrary2.csproj, src/Razor/test/testapps/ComponentApp/ComponentApp.csproj, src/Razor/test/testapps/ComponentLibrary/ComponentLibrary.csproj, src/Razor/test/testapps/Directory.Build.props, src/Razor/test/testapps/LargeProject/LargeProject.csproj, src/Razor/test/testapps/MvcWithComponents/MvcWithComponents.csproj, src/Razor/test/testapps/RestoreTestProjects/RestoreTestProjects.csproj, src/Razor/test/testapps/SimpleMvc/SimpleMvc.csproj, src/Razor/test/testapps/SimpleMvcFSharp/SimpleMvcFSharp.fsproj, src/Razor/test/testapps/SimplePages/SimplePages.csproj
More work to fix https://github.com/aspnet/AspNetCore-Internal/issues/1997
=> Do not restore as part of test

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/Assert.cs
Fixes https://github.com/aspnet/AspNetCore-Internal/issues/2050
=> Allow some warnings

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentDiagnosticFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorIntermediateNodeLoweringPhase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Legacy/TagHelperParseTreeRewriter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Syntax/MarkupEndTagSyntax.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/Components/ComponentMarkupBlockPassTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/ComponentDiagnosticRazorIntegrationTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/6217
=> Bring back errors for missing tags in component documents

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets
Fixes https://github.com/aspnet/AspNetCore/issues/8181
=> Add .razor files to UpToDateCheckInput

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest21.cs
* Fix invalid parameter used in error message
* Re-organize test code
=> Fixup invalid configuration error message

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateTest.cs
- Added a test to verify the new behavior.
aspnet/AspNetCore#8849
=> Fix Import reseting on ProjectState when host project changes.

src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ModelDirective.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/ModelDirectiveTest.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/BasicComponent_DesignTime.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/BasicComponent_DesignTime.ir.txt, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/BasicComponent_DesignTime.mappings.txt
Fixes https://github.com/aspnet/AspNetCore/issues/8193
Skip running ModelDirective pass for component documents
=> Fixed a spooky issue

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentDiagnosticFactory.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/ComponentDiagnosticRazorIntegrationTest.cs
This was just a badly written diagnostic format string
=> Fixes: #5640 FormatException from diagnostic

src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/IntegrationTests/ComponentCodeGenerationTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/AsyncEventHandler_OnElement_ActionEventArgs_Lambda/TestComponent.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/AsyncEventHandler_OnElement_ActionEventArgs_Lambda/TestComponent.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/AsyncEventHandler_OnElement_ActionEventArgs_Lambda/TestComponent.mappings.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/AsyncEventHandler_OnElement_Action_Lambda/TestComponent.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/AsyncEventHandler_OnElement_Action_Lambda/TestComponent.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/AsyncEventHandler_OnElement_Action_Lambda/TestComponent.mappings.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/AsyncEventHandler_OnElement_ActionEventArgs_Lambda/TestComponent.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/AsyncEventHandler_OnElement_ActionEventArgs_Lambda/TestComponent.ir.txt, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/AsyncEventHandler_OnElement_Action_Lambda/TestComponent.codegen.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Language.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/AsyncEventHandler_OnElement_Action_Lambda/TestComponent.ir.txt
Fixes https://github.com/aspnet/AspNetCore/issues/8826
=> Correct code gen tests

azure-pipelines.yml
- aspnet/AspNetCore-Internal#2231
- use internal pools for all internal builds
nit: remove unused YAML variable
=> Support internal pull requests

azure-pipelines.yml
Part of https://github.com/aspnet/AspNetCore-Internal/issues/2033
=> Update to use VS2019 Enterprise build images

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/BackgroundDocumentGenerator.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs
- Also updated the tests to reflect the mishap.
aspnet/AspNetCore#9905
=> Updated BackgroundDocumentGenerator to properly parse related docs.

azure-pipelines.yml
- This contains the azure-pipelines.yml fixes.
=> Merge release/vs16.1-preview4

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.DesignTime.targets
Specify a list of file extensions that VS will monitor for file changes to reload the app.
Includes .razor and .cshtml files.
=> Specify UpToDateReloadFileTypes

src/Razor/src/Microsoft.NET.Sdk.Razor/GetDefaultStaticWebAssetsBasePath.cs, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/GetDefaultStaticWebAssetsBasePathTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs, src/Razor/test/testapps/AppWithPackageAndP2PReference/AppWithPackageAndP2PReference.csproj, src/Razor/test/testapps/ClassLibrary/wwwroot/js/project-transitive-dep.js, src/Razor/test/testapps/ClassLibrary2/wwwroot/css/site.css, src/Razor/test/testapps/ClassLibrary2/wwwroot/js/project-direct-dep.js
Brings in content from referenced projects
=> Support for content from project references

eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorServiceBase.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Microsoft.VisualStudio.Editor.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/RazorProjectHostBase.cs, src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/RazorProjectExtension.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/Xunit/ForegroundTestCase.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Microsoft.VisualStudio.Editor.Razor.Test.csproj
Fixes https://github.com/aspnet/AspNetCore/issues/8312
Currently blocked on https://github.com/dotnet/roslyn/pull/34860
=> Upgrade StreamJsonRpc version to 2.xxx

src/Razor/test/testapps/RestoreTestProjects/RestoreTestProjects.csproj
There seems to be some flakyness here. Trying to avoid restore for the projects at runtime to see if that helps
=> [Flaky tests] Restore package projects at build time

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentDiagnosticFactory.cs
=> Fix error spacing.

eng/Version.Details.xml, eng/Versions.props, global.json
Part of aspnet/AspNetCore#9720, similar to https://github.com/aspnet/Extensions/pull/1828.
=> React to changes in Microsoft.NETCore.App

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/ApplicationPartDiscoveryIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/Assert.cs
Fixes https://github.com/aspnet/AspNetCore/issues/11315
=> Ensure ApplicationPart attributes are added during incremental builds

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentsApi.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.ComponentShim/Microsoft.AspNetCore.Components.netstandard2.0.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentDirectiveIntegrationTest.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ComponentImports/_Imports.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ComponentImports/_Imports.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/ComponentImports/_Imports.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentImports/_Imports.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/ComponentImports/_Imports.ir.txt
This will be coordinated with the equivalent change in the runtime repo.
=> Move [Layout]

src/Razor/src/Microsoft.CodeAnalysis.Razor/ComponentTagHelperDescriptorProvider.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Test/ComponentTagHelperDescriptorProviderTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/5653
I also verified it manually in VS.
=> Support [Parameter] attribute on base class of overridden properties

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentDesignTimeNodeWriter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentRuntimeNodeWriter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentsApi.cs, src/Razor/src/Microsoft.AspNetCore.Razor.Language/Intermediate/ReferenceCaptureIntermediateNode.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/RefTagHelperDescriptorProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.ComponentShim/Microsoft.AspNetCore.Components.netstandard2.0.Manual.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.ComponentShim/Microsoft.AspNetCore.Components.netstandard2.0.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentCodeGenerationTestBase.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentDeclarationIntegrationTest.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_SuppressField/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_SuppressField/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_SuppressField/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.mappings.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef_SuppressField/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef_SuppressField/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Element_WithRef_SuppressField/TestComponent.mappings.txt
=> React to ElementReference change

eng/MPack.targets, src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj
This helps a lot with debugging and exceptions stacktraces
https://github.com/aspnet/AspNetCore/issues/11808
=> Add .pdb files to .mpack

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/BackgroundDocumentGenerator.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs
- This reduces the noise when a user renames a .razor file in VS.
- Added tests to validate that we properly swallow FileNotFoundExceptions.
During the fix of this I found:
1. It doesn't crash VS
2. It's unavoidable because our project manager can't guarantee that an underlying file won't disappear before processing it.
3. In VS' case renaming a Razor file doesn't result in the project system detecting its removal until after we've attempted to parse the deleted file.
4. This exception is reported to the activity log as an error.
I took the approach of fixing 4 because this is a pretty common case that can't always be avoided. I wish I could mitigate it by dequeuing background parsing work; however, we aren't notified that it's actually gone until we've already thrown an exception. …
=> Don't let background FileNotFoundExceptions land in ActivityLog.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultTagHelperCompletionService.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/DefaultTagHelperCompletionServiceTest.cs
Part of https://github.com/aspnet/AspNetCore/issues/9860
This came up when discussing scenarios with the WTE team. They use our element completion logic so fix turned out to be here.
=> Make element completions case sensitive

azure-pipelines.yml
=> Use Arcade post-build stage template

eng/Versions.props
This is blocked until we branch for preview8
=> Update branding to 5.0.0-alpha1

eng/Versions.props
https://github.com/aspnet/AspNetCore-Internal/issues/2876
=> Update branding to preview 9

src/Razor/src/Microsoft.AspNetCore.Razor.Tools/GenerateCommand.cs, src/Razor/src/Microsoft.NET.Sdk.Razor/DotnetToolTask.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildWithComponentsIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/RazorGenerateIntegrationTest.cs, src/Razor/test/testapps/ComponentApp/Components/Pages/Index.razor
https://github.com/aspnet/AspNetCore/issues/12661
=> Don't fail the build on warnings

src/Razor/src/Microsoft.AspNetCore.Razor.Language/Components/ComponentMarkupBlockPass.cs, src/Razor/test/RazorLanguage.Test/Components/ComponentMarkupBlockPassTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/12667
Follow up to https://github.com/aspnet/AspNetCore/pull/12996
=> Don't coalesce <option> tag in ComponentMarkupBlockPass

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets
* Removes the need for a custom property when resolving referenced static web assets.
=> Remove the need for a custom property when resolving static web assets from referenced projects

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.DesignTime.targets
Fixes https://github.com/aspnet/AspNetCore/issues/12840
=> Add tooling support for TypeScript files to RazorSDK

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets
Original PR https://github.com/aspnet/AspNetCore-Tooling/pull/978
=>  Set LangVersion the same way as roslyn

global.json, src/Razor/src/Microsoft.NET.Sdk.Razor/Microsoft.NET.Sdk.Razor.csproj, src/Razor/src/Microsoft.NET.Sdk.Razor/Microsoft.NET.Sdk.Razor.nuspec
aspnet/AspNetCore-Internal#2979
=> Update SDK to preview 8

eng/Versions.props
=> [release/3.0] Rebrand to rc1

Directory.Build.props, src/Razor/src/RazorDeveloperTools/RazorDeveloperTools.csproj
- problem noticed while investigating aspnet/AspNetCore-Internal#3030
=> Correct `sourcelink` validation errors

azure-pipelines.yml
Working around breaking changes in preview9 SDK
=> Pin SDK to preview8

azure-pipelines.yml
Addresses https://github.com/aspnet/AspNetCore-Internal/issues/3066
=> Pin SDK to preview8 (#1068)

NuGet.config, azure-pipelines.yml
Addresses https://github.com/aspnet/AspNetCore-Internal/issues/3066
=> Johluo/backport 16.2

eng/Versions.props
Addresses https://github.com/aspnet/AspNetCore-Internal/issues/3066
=> Move to new vside feeds

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIncrementalismTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildIntegrationTestBase.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/PackIntegrationTest.cs, src/Razor/test/testapps/Directory.Build.props
https://github.com/aspnet/AspNetCore/issues/12494
=> Restore test projects prior to running SDK tests

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj
* Fixes missing metadata key for procdump.
=> [Infrastructure] Fix assembly metadata key

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs
* Extends our ability to capture dumps to include potential child processes spawn from processes we directly start in tests.
* This is necessary as "dotnet msbuild" spawns child dotnet processes and wait for them to finish, which is the root cause of the hangs.
=> Capture process dumps for child dotnet processes

Directory.Build.targets, azure-pipelines.yml, eng/AfterSigning.targets, eng/Publishing.props, eng/targets/Packaging.targets
- Publishing the Razor.VSCode NPM package for O#.
- Publishing the various Razor LanguageServers that are used by O#.
=> Publish all things Razor.VSCode

src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Microsoft.NET.Sdk.Razor.Component.targets
Fixes https://github.com/aspnet/AspNetCore/issues/12322.
That's how I interpreted the issue at least, let me know if I'm way off base or you've got better idea for names/locations.
=> RazorSDK shouldn't overwrite ErrorLog

src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/MultipleChildContentMatchingComponentName/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/MultipleChildContentMatchingComponentName/TestComponent.ir.txt, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/MultipleChildContentMatchingComponentName/TestComponent.codegen.cs, src/Razor/test/RazorLanguage.Test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/MultipleChildContentMatchingComponentName/TestComponent.ir.txt
=> Update baselines to unbreak tests

src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/tests/ReportIssueCreator.test.ts, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs
- Detail 1
- Detail 2
Addresses #bugnumber (in this specific format)
=> Flake some tests

azure-pipelines.yml
- problem should be specific to our 'master' branch
=> Disable signing validation temporarily

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCompletionItemProvider.ts
- Looks like VSCode misbehaves in re-execution of completion scenarios. They've been [experimenting](https://github.com/microsoft/vscode/issues/10266) with new completion range APIs and it seems that it translates O#'s non-new range based completion request into a new type of range completion request (`range2`).
- We now fallback to using a `range2` property on completion items if it exists and properly re-map.
https://github.com/aspnet/AspNetCore-ManualTests/issues/52
@jrieken I imagine this is not intended is it?
=> Fix Razor VSCode C# completions at beginning of the line.

.vscode/launch.json, .vscode/tasks.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/src/extension.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDefinitionProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentFactory.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test/RazorPageDocumentClassifierPassTest.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test/LegacySectionTargetExtensionTest.cs, src/Razor/test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test/RazorPageDocumentClassifierPassTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/GoToDefinition.test.ts, src/Razor/tslint.json
- Detail 1
- Detail 2
Addresses #bugnumber (in this specific format)
=> Go to definition

eng/Version.Details.xml, eng/Versions.props
Fixes 4.6.0 versions coming from extensions.
=> Update depenedencies from extensions

src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultRazorProjectHost.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/RazorProjectHostBase.cs, src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/DefaultRazorProjectHostTest.cs
- Capture project level document information for VS4Mac Blazor scenarios.
- Add a few tests
/cc @KirillOsenkov
=> Finish Blazor VS4Mac experience - add document info

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorMapToDocumentRangeParams.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorLanguageEndpointTest.cs
=> Add MapToDocumentRange tests.

eng/targets/Npm.Common.targets
- Makes it so `dotnet build` actually rebuilds npmproj's
=> Fix npmproj incrementalism

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCompletionItemProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorConventions.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDefinitionProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDocumentFactory.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorImplementationProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorLanguageFeatureBase.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorRenameFeature.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorRenameProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Rename.test.ts, src/Razor/test/testapps/MvcWithComponents/Test.cs, src/Razor/test/testapps/MvcWithComponents/Views/Shared/NavMenu.razor, src/Razor/tslint.json
=> Rename support in VS Code and other fixes

azure-pipelines.yml, eng/Versions.props
Update branding & add trigger for internal release/3 branches
@JunTaoLuo @mmitche PTAL
=> Update branding to 3.1.1

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/CodeDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/FunctionsDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ImplicitExpressions.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Started adding infrastructure pieces for interoperating with more specific pieces of C#.
- Added several implicit expression tests
- Does not include nested HTML or `@<p>...</p>` templates.
=> Add support for implicit expressions.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/InjectDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@inject`.
=> Add grammar support for the inject directive.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/InjectDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/NamespaceDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@namespace`.
=> Add grammar support for the namespace directive.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/AddTagHelperDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/InjectDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ModelDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/NamespaceDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/PageDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/RemoveTagHelperDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TagHelperPrefixDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@page`
=> Add grammar support for @page.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/AttributeDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@attribute`.
=> Add grammar support for the attribute directive.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/AttributeDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ImplementsDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@implements`.
=> Add grammar support for the implements directive.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCodeLens.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCodeLensProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/CodeLens.test.ts
CodeLens 😍 
Working on adding tests
=> CodeLens in Razor files

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/LayoutDirective.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@layout`.
=> Add grammar support for the layout directive.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCSharpLanguageMiddleware.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCodeLensProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDefinitionProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorImplementationProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/extension.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/CodeLens.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Completions.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Completions2_1.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/FindReference.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/GoToDefinition.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/GoToImplementation.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Hover.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/HtmlTyping.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Rename.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/SignatureHelp.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/TestUtil.ts
Also addressed feedback from #1424
=> Make integration tests slow but reliable

azure-pipelines.yml
=> Enable CI on internal branches

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/language-configuration.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/RazorComment.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
https://github.com/aspnet/AspNetCore/issues/14287
=> Textmate grammar support for Razor Comments

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/DoStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/GrammarTests.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/LockStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/SwitchStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/TryStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/WhileStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Add tests to validate the various forms of `@while (...) {...}`.
=> Add grammar support for while statements.

src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/TestUtil.ts
Some small spelling and capitalization stuff so that linters don't complain.
=> Minor cleanup

global.json
See https://github.com/aspnet/AspNetCore/pull/17633
=> Change minimum VS requirement

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/syntaxes/aspnetcorerazor.tmLanguage.yml, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/ForeachStatement.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/tests/__snapshots__/GrammarTests.test.ts.snap
- Added tests to validate the new await foreach syntax.
- Updated snapshots for tests.
=> Add grammar support for await foreach.

CONTRIBUTING.md, Directory.Build.props, README.md, azure-pipelines.yml, eng/scripts/CodeCheck.ps1, src/Razor/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/EmptyTextLoaderTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/GeneratedDocumentTextLoaderTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/ApplicationPartDiscoveryIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntrospectionTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/PublishIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/ReferenceResolverTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioRazorParserIntegrationTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs, src/Razor/test/RazorLanguage.Test/Components/ComponentMarkupBlockPassTest.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentCodeGenerationTestBase.cs, src/Razor/test/RazorLanguage.Test/IntegrationTests/ComponentDeclarationIntegrationTest.cs
=> Update links for repo moves/renames

src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectDocumentChangeDetector.cs
- The file watcher rename event fires when renaming from a non-Razor file -> Razor file and from a Razor File -> non-Razor file. Therefore we need to add the logic to detect these scenarios and conditionally fire the add/remove events.
- Could not add tests for this updated scenario because it involves creating file system watchers which we don't want to do at test time.
=> Fix Razor file and generated file detection in O# plugin.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultRemoteTextLoaderFactory.cs
- When a file is renamed in VSCode it first closes said file and then re-opens it under the new name. The problem is there's a race when a file is renamed where VSCode will publish a "closed" event for a file that no longer exists on disk. Since all .razor files impact each other when the renamed variant gets re-opened if we haven't processed the file system delete event for the originally closed file yet we'll re-parse all impacted files, of which include the closed non-existent file. To workaround this by design limitation we now detect file not found exceptions when reading from disk and swallow those exceptions accordingly.
- Could not add tests for this case because it involves reading from disk, something we don't want to do in our tests.
I'd suggest reviewing this with the ?w=1 …
=> Fix race where RazorLanguageServer could crash on .razor file rename.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultHtmlFactsService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/package.json, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/HoverComponents.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/TestUtil.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/yarn.lock
Fixes https://github.com/dotnet/aspnetcore/issues/18433.
- Hovering over Directive attributes didn't work because we were using Name instead of FullName (`onclick` instead of `@onclick`).
- Re-ordered the package.json to be alphabetical because that will happen if we use any automation to edit it anyway.
- Added a test for the Directive attribute case.
- Fixed Functional test hang due to miscount of TestApp Projects (a new one was added). Ideally we would get rid of that count entirely, but I don't know of another way to ensure that all our projects are loaded before handing off to the individual tests.
=> Directive attribute hovers fix

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProviderBase.cs
=> Fix poli check violation.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCompletionItemProvider.ts
Yup, it happened again. Probably shouldn't be supporting insiders as much as we have BUT for one of the demos we're doing in the upcoming week may require insiders so figured i'd fix.
=> Fix VSCode Insiders completion.

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultTagHelperServiceTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs
Missed this before merging https://github.com/dotnet/aspnetcore-tooling/pull/1525.
=> Add tests for HoverInfo directive attributes

azure-pipelines.yml
- agents should start much faster
=> [master] Switch to Windows Server queues

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorEditorFactory.cs
- Found that testing through LiveShare scenarios sped up experimentation without the need for full VS server support yet still operated the same. Because of this I added placeholders in our EditorFactory initialization logic so they can easily be changed to ease development
- Could not add tests for these scenarios because they're all end-to-end driven.
dotnet/AspNetCore#17714
=> Prep Razor LSP editor to eventually be on by default in LiveShare scenarios.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json
Fixes https://github.com/dotnet/aspnetcore/issues/14326.
Thankfully we only have three configs so far.
=> Machine scope path config

eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/ViewComponentTagHelperDescriptorFactory.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/ViewComponentTypeVisitor.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/ViewComponentTagHelperDescriptorFactory.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/ViewComponentTypeVisitor.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ViewComponentTagHelperDescriptorFactory.cs, src/Razor/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/ViewComponentTypeVisitor.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/BindTagHelperDescriptorProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/ComponentTagHelperDescriptorProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/DefaultTagHelperDescriptorFactory.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor/EventHandlerTagHelperDescriptorProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj
Fixes https://github.com/dotnet/aspnetcore/issues/18838
=> Upgrade roslyn deps to 3.4.0

.vscode/launch.json, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/index.ts
- In VSCode only (F5) you are now prompted with a test file filter that will be applied to the entire list of functional tests.
- This does not impact command line runs.
dotnet/aspnetcore#17045
=> Added ability to run single VSCode functional test.

src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/Completions1_0.test.ts, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.FunctionalTest/tests/TestUtil.ts, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/BuildIntegrationTest11.cs, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/Microsoft.NET.Sdk.Razor.Test.csproj, src/Razor/test/testapps/RestoreTestProjects/RestoreTestProjects.csproj, src/Razor/test/testapps/SimpleMvc11/Program.cs, src/Razor/test/testapps/SimpleMvc11/SimpleMvc11.csproj, src/Razor/test/testapps/SimpleMvc11/Views/Home/Index.cshtml, src/Razor/test/testapps/SimpleMvc11/Views/Shared/_Layout.cshtml, src/Razor/test/testapps/SimpleMvc11/Views/_ViewImports.cshtml, src/Razor/test/testapps/SimpleMvc11/Views/_ViewStart.cshtml, src/Razor/test/testapps/SimpleMvc11NetFx/Program.cs, src/Razor/test/testapps/SimpleMvc11NetFx/SimpleMvc11NetFx.csproj, src/Razor/test/testapps/SimpleMvc11NetFx/Views/Home/Index.cshtml, src/Razor/test/testapps/SimpleMvc11NetFx/Views/Shared/_Layout.cshtml, src/Razor/test/testapps/SimpleMvc11NetFx/Views/_ViewImports.cshtml, src/Razor/test/testapps/SimpleMvc11NetFx/Views/_ViewStart.cshtml
Fixes https://github.com/aspnet/AspNetCore/issues/13943
=> Added back 1.x tests

azure-pipelines.yml
- agents should start much faster
=> [release/3.1] Switch to Windows Server queues

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCompletionItemProvider.ts
Looks like I failed to do this for the insiders fix.
=> Merge back the LSP Preview 1 branch into master

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentVersionCache.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCodeLensProvider.ts, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentVersionCacheTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/18343 
Fixes https://github.com/dotnet/aspnetcore/issues/19172
=> Fix bugs when renaming Razor files in VSCode

src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs
=> Add support for VS' LSP Razor editor preview panel.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCompletionItemProvider.ts
Fixes https://github.com/dotnet/aspnetcore/issues/18641
Before:
After:
I don't know why this fixes it. Any ideas @NTaylorMullen @ryanbrandenburg?
=> Fix HTML completion documentation

src/Razor/test/VSCode.FunctionalTest/tests/CodeLens.test.ts
Updated https://github.com/dotnet/aspnetcore/issues/19296 to include this test
=> Skip CodeLens test that's flaky on the CI.

eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Microsoft.VisualStudio.Editor.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj
- This addresses alerts from Component Governance.
=> Pin System.Private.Uri package version

azure-pipelines.yml
- dotnet/aspnetcore-internal#3540
=> [master] Update hosted and BYOC agents used in our builds

azure-pipelines.yml
- dotnet/aspnetcore-internal#3540
=> [release/5.0-preview2] Update hosted and BYOC agents used in our builds

azure-pipelines.yml
This is currently failing.
Filed https://github.com/dotnet/aspnetcore/issues/19937 to track the work to re-enable this.
=> Disable VSCode functional tests on the CI

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
Fixes https://github.com/dotnet/aspnetcore/issues/19913
This fixes it. Working on tests.
Review with [?w=1](https://github.com/dotnet/aspnetcore-tooling/pull/1694/files?w=1) to make things easier.
=> Fix race condition when publishing to HTML and CSharp buffers

src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1085512
=> Don't wait for IntelliSense in our RazorEditorFactory

azure-pipelines.yml
- dotnet/aspnetcore-internal#3540
=> [release/3.1] Update hosted and BYOC agents used in our builds

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorService.cs
=> Fix policheck violation

eng/Version.Details.xml, eng/Versions.props
As part of the ingestion process for new extensions packages from dotnet/runtime https://github.com/dotnet/aspnetcore/issues/19254
=> Ingest new packages from dotnet/runtime

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnTypeFormattingHandler.cs
Need to to invoke html comment auto completion,
```html
```
=> Added "-" as a trigger character for onTypeFormatting

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorProjectServiceTest.cs
- There's an inherent race between us initializing the project/document world and us updating our project world when there are pre-existing `project.razor.json` files on disk. Because of this we need to eagerly update our projects and create or remove documents from projects to match what's stated in the `project.razor.json`. To do this I added the creation/removal steps to the `UpdateProjectDocuments` method.
- Added tests to verify the add/remove paths for updating a project.
=> Fix late project updates.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultDocumentResolver.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentResolverTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/20684
Thanks @NTaylorMullen!
=> Added MISC Proj Check When Trying to Resolve Document

eng/Versions.props
- The VS bits have recently added several APIs. Given we're targeting VS master builds I'm proactively updating to ensure we have access to all APIs
=> Update VS Language Server client version.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/DefaultTagHelperDescriptionFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperDescriptionFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/DefaultRazorHoverInfoService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultTagHelperDescriptionFactoryTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/19804.
=> Only use markdown when it's supported

src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
Fixes https://github.com/dotnet/aspnetcore/issues/21101
Manually verified that this works correctly on a client instance of VS.
=> Mark Razor VSIX as cloud compliant

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileChangeDetectorTest.cs
- I found that when you save a file in VS it renames the file to a .tmp file, writes out your current file to a temp directory under a different name and then renames the new temp file to the "correct" file name. Because of this our file change detector would see all of these changes and notify the world for each (remove, and then re-add). Turns out this is a pretty common pattern for .NET runtime methods so to react to this I decided to batch our file change notifications.
- Because of VS' strategy in saving files our system would see the removal of the file, clear what it thought it had sent down to the client for C# content, and then re-send down a fresh batch of C# content to the client as an "insert". This meant you'd get double the C# in your buffer because you'd re-insert the …
=> Fix C# diagnostics on every Razor statement after save in cloud scenarios.

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/MSN.cshtml
Addresses:
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1111066
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1111067
- https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1111068
=> Fix PoliCheck failures.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs
Follow up to https://github.com/dotnet/aspnetcore-tooling/pull/1833#discussion_r416190433
=> Minor optimization

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs
* Improves the reliability of the affected tests with retries
* Pack and restore fail/hang in some occasions. The retries minimize
the chances of these happening.
* For pack, we retry a few times but we ultimately continue as we've
seen the package gets generated when pack hangs and looks correct.
If that were not to be the case in the future, the test will fail.
=> [Fixes #17233 #18543 #18707 #18561][Static web assets] Improve test reliability

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/MSN.cshtml
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1115919
=> Fix more policheck failures in MSN.cshtml

README.md
Build status badges similar to what dotnet/roslyn has: https://github.com/dotnet/roslyn#welcome-to-the-net-compiler-platform-roslyn
View DIFF as preview: https://github.com/dotnet/aspnetcore-tooling/pull/1875/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
=> Added Build Status Badges to README

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSource.cs
- Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1122435
=> Fix PoliCheck issues.

NuGet.config, eng/Version.Details.xml, eng/Versions.props
- Merges internal -> public
- Removes internal feeds from nuget.config
- Updates branding
=> Update branding to 3.1.5

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
Fixes dotnet/aspnetcore#20324
With this, completion icons show up correctly in both host and the guest.
We need this until [this external bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1110173) is fixed.
=> Temporary fix for Razor completion icons

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/DefaultRazorFormattingServiceTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/21714
Example in issue description
=> Don't format outside the selected range

eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorLanguageService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/OOPTagHelperResolver.cs
Fixes https://github.com/dotnet/aspnetcore/issues/21253 and https://github.com/dotnet/aspnetcore/issues/21470.
=> Update Roslyn to 3.7

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs
- This is a revert of https://github.com/dotnet/aspnetcore-tooling/pull/1817
Fixes dotnet/aspnetcore#21126
=> Re-enable C# generation on document open.

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.clientenabledpkg, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
Fixes https://github.com/dotnet/aspnetcore/issues/21101
My original PR to do this was only partially correct. It only worked for experimental instances.
=> Mark Razor pkgdefs as cloud compliant

eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorLanguageService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/OOPTagHelperResolver.cs
The previous attempt here had a problem with serialization. I've run through a couple scenarios by hand with this one and they were fine.
=> Roslyn update serialization

eng/MPack.targets
There is already a dash in MPackVersion.
=> Remove the extra dash in .mpack name.

eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorLanguageService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/OOPTagHelperResolver.cs
This reverts commit 6e7220bbaf8a4086b7cc188847660d3b059536f7 for the Omnisharp insertion.
This is targeting the release branch.
=> Revert "Roslyn update serialization (#1911)"

.github/CODEOWNERS
=> Add Noah to code owners to get auto-added to PRs

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts
Addresses https://github.com/dotnet/aspnetcore/issues/21716
=> Add support for 'attach' requests to Blazor debugger

src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/PrecompiledRazorPageSuppressor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/PrecompiledRazorPageSuppressorTest.cs
- Added test to verify the fix.
Fixes https://github.com/OmniSharp/omnisharp-vscode/issues/3798
=> Fix bug where files that end in "g.cshtml.cs" would get ambiguous errors.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
Fixes https://github.com/dotnet/aspnetcore/issues/22043
The underlying issue with the ordering was fixed and we no longer need this.
=> Removed unnecessary SemaphoreSlims

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/SignatureHelpHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/SignatureHelpHandlerTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/21974
=> Razor Signature Help Implementation

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/GoToImplementationHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/GoToImplementationHandlerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/22254
This works but produces incorrect results. Looks to be a Roslyn issue. Filed https://github.com/dotnet/roslyn/issues/44846 to track it.
=> Support Go to implementation in VS LSP

azure-pipelines.yml
- dotnet/aspnetcore#22368
nit: Remove extra `$(_PublishArgs)` variable
=> Do not publish except in official builds

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/AttributeSnippetFormatOnTypeProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/Rules/RazorGenerateWithTargetPath.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/AttributeSnippetFormatOnTypeProviderTest.cs
Putting up draft PR to confirm this is what was intended by our discussion. If so, will add the appropriate tests.
Fixes: https://github.com/dotnet/aspnetcore/issues/21857
=> Attribute Snippet OnTypeFormatter

src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorDocumentExcerptServiceTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/23060
Working appropriately locally. Running this through the CI a few times to identify flakiness.
=> Reintroduce Razor Excerpt Tests

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentExcerptServiceBase.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ExcerptModeInternal.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ExcerptResultInternal.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpDocumentExcerptService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpSpanMappingService.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorDocumentExcerptServiceTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Shared/DocumentExcerptServiceTestBase.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpDocumentExcerptServiceTests.cs
Didn't write tests as part of the initial implementation, due to [previously blocked](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorExcerptServiceTest.cs) flaky tests in the RazorExcerptService  test suite.
Fixes: https://github.com/dotnet/aspnetcore/issues/23061
=> C# Excerpt Service Test Suite

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/UriExtensions.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/UriExtensionsTest.cs
Targeted fix for https://github.com/dotnet/aspnetcore/issues/23336
Getting a quick fix out to unblock working on DDRIT tests.
Will keep the original issue open to investigate if this doesn't break cross-plat
=> Quick fix for path with spaces bug

src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPProgressListenerTest.cs
https://dev.azure.com/dnceng/internal/_build/results?buildId=711503&view=ms.vss-test-web.build-test-results-tab&runId=22053168&resultId=100145&paneView=debug
=> Skip MultipleProgressNotificationReported Test

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/MSN.cshtml
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1149814
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1149815
=> Fix PoliCheck violations

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackRazorConfiguration.cs
Edit: [Here is some context](https://github.com/dotnet/aspnetcore/pull/23385#discussion_r446344856) for future us
=> Add support for LangVersion 5.0

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DocumentHighlightHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/HoverHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentHighlightHandlerTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/23552
=> HTML Document Highlights

docs/contributing/RoslynDebugging.md
Thanks @NTaylorMullen for the guide, just writing up the process for future reference.
Directory structure inspired by [roslyn](https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md).
=> Added Roslyn Debugging Steps

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- Shutdown failures can happen for a variety of reasons. The two addressed in this PR are:
1. There's currently a race in the LSP platform where shutdown/re-activate can happen concurrently. This means we could be re-activating our `RazorLanguageServerClient` without ever having handled the shutdown request.
2. The `JsonRpc` object that the language server platform uses to communicate with our language server times out. This most prominently happens in "attached" debugging scenarios where things take a longer then expected.
- For both of these cases it's possible that we need to forcefully shutdown our "previous" language server prior to starting a new one to avoid leaking.
- Expanded our `RazorLanguageServer` implementation to actually wrap the typical O# language server. This way we can …
=> Shutdown our language server properly on LSP platform shutdown failures.

NuGet.config, eng/Version.Details.xml, eng/Versions.props
=> Update branding to 3.1.7

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/README.md, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
Fixes https://github.com/dotnet/aspnetcore/issues/23550.
=> Allow Log-level customization

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
Fixes https://github.com/dotnet/aspnetcore/issues/23908.
=> Handle @{ completion case in VS

src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/DefaultProjectChangePublisher.cs
- Found that in Linux when you'd boot a Razor application larger project.razor.json files would typically take longer to serialize and would serialize in batches. Meaning our language server would see these changes and immediately attempt to deserialize them. The problem with this is that when we moved to a JsonReader model for serialization/deserialization it was possible that a project.razor.json could be broken up into invalid JSON resulting in some of our reader tech infinite looping. In the case that the end of the document would contain a partial string or a partial array we'd have a `do while (token != EndArray)` which would never exit. This infinite loop would occupy O#'s schedule processing loop meaning any message sent to it would be cancelled/ignored.
- Updated our O# …
=> Ensure we don't partially serialize project.razor.json in VSCode.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/MemoryCache.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/24385 
Will kick off an insertion on merge.
=> Fix Razor language server assembly shouldn't be loaded by default in VS

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorProjectChangePublisher.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorProjectChangePublisherTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/24209
=> Don't serialize project.razor.json until ready

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/FindAllReferencesHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/Rules/RazorConfiguration.cs
Addresses: https://github.com/dotnet/aspnetcore/issues/24423
Discussion: https://github.com/dotnet/aspnetcore/issues/24423#issuecomment-668995044
Essentially just moves the filtering logic ahead of the bypass logic for non-generated files.
=> Fix FAR Reference Code behind Filtering

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/24064.
=> Include keywords in completion results

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RazorComponentRenameEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorDefinitionProvider.ts
Addresses https://github.com/dotnet/aspnetcore/issues/17044
=> Implement go to definition for components

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/24741.
=> Only return C# keywords on '@' for now

global.json
Updated to match https://github.com/dotnet/aspnetcore/blame/master/global.json#L3
=> Upgrade dotnet sdk versions to rc.1

README.md, docs/contributing/BuildFromSource.md
Added to help simplify onboarding for new (community) contributors.
Adapted from: https://github.com/dotnet/aspnetcore/blob/3de55dfd2152d85b958c3f2f5e37fedf360f4753/docs/BuildFromSource.md
=> Added BuildFromSource Instructions

NuGet.config, eng/Version.Details.xml, eng/Versions.props, global.json
=> Update branding to 3.1.8

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundParser.cs
- Now that TagHelper resolution can be almost instantaneous there are more chances for our underlying parser tech to fall over due to race conditions. This was causing issues when initially opening up a project and queuing some of the first parses. Basically what I observed is that TagHelpers would be resolved simultaneously with enqueuing a new change sometimes resulting in our manualResetEventSlim.Reset() throwing an object disposed exception and crashing VS.
Fixes dotnet/aspnetcore#24856
=> Make BackgroundParser more threadsafe.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContentValidationPass.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1172685
=> Fix PoliCheck issue for "nuked"

eng/Version.Details.xml
=> Unpin System.Runtime.CompilerServices.Unsafe

src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs
https://github.com/dotnet/aspnetcore/issues/18543
The Quarantine attribute doesn't seem to be available
=> Skip flaky test

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/AddUsingsCodeActionResolverTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/25019
**Before:**
**After:**
=> Fix Add Using Added to Wrong Line

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Serialization/ExtendableClientCapabilitiesJsonConverter.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Serialization/ExtendableClientCapabilitiesJsonConverterTest.cs
- Part of: https://github.com/dotnet/aspnetcore/issues/23985
- Support for extendable client capabilities + testing. 
- Validated in VS + VSCode
=> Razor ExtendableClientCapabilities Support

eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/DefaultFeedbackFileLogWriter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/DefaultFeedbackFileLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/DefaultFeedbackLogDirectoryProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLogWriter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLogger.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLoggerProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackFileLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/FeedbackLogDirectoryProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/RazorFeedbackDiagnosticFileProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/Feedback/FeedbackFileLoggerProviderTest.cs
- Found out that the underlying issue to the RPS regression was ngen related and must be addressed at the VS PR level.
=> Re-enable VSFeedback integration

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentExcerptServiceBase.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TextSpanExtensions.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorDocumentExcerptServiceTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpDocumentExcerptServiceTests.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/25327
Before:
After:
=> Fix FAR Leading Whitespace in Results

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/MemoryCache.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/MemoryCacheTest.cs
- Prior to this when there was a high amount of concurrency around setting items on our memory cache we'd occasionally explode when attempting to concurrently compact items in the `MemoryCache`. This was because accessing members of the currently being compacted memory cache would throw.
- Granted we started seeing a significant amount of users hit this "compaction" case I'm considering increasing the size of the `TagHelperDescriptorCache`. Will do in a follow up though to not associate with this changeset.
- Added a test that reproduces the issue when I undo my change.
Fixes dotnet/aspnetcore#25358
=> Make MemoryCache thread safe during compact.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RazorComponentRenameEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RazorComponentRenameEndpointTest.cs
- Utilized the same LanguageServerFeature options service to understand if the IDE supports file manipulations. This typically results in a "false" call when operating in a Codespaces or LiveShare environment.
- Added a test to ensure we don't try and rename anything when file manipulations are disabled.
Fixes dotnet/aspnetcore#25504
=> Disable component rename in LiveShare & Codespaces.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/23908.
=> Do not preselect

eng/Versions.props
Fixes https://github.com/dotnet/aspnetcore/issues/25538.
=> O# upgrade for VSCode

global.json
Upgrade to https://github.com/dotnet/aspnetcore/blob/master/global.json#L3
=> Upgrade .net SDK to 5.0.100-rc.1.20379.10

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormattingPass.cs
* Razor block formatting and other bug fixes
* feedback
Follow up to https://github.com/dotnet/aspnetcore-tooling/pull/2484
=> Port: Fix nested html indentation and other bugs (#2484)

global.json
Reverts dotnet/aspnetcore-tooling#2479
=> Revert "Upgrade .net SDK to 5.0.100-rc.1.20379.10"

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/MSN.cshtml
- Copy & pasted the master branch version of MSN.cshtml over to release/3.1.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1212315
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1212316
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1212317
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1212318
=> Fix PoliCheck errors in release/3.1 branch.

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/BlazorDebugConfigurationProvider.ts, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/BlazorDebug/TerminateDebugHandler.ts
- Add support for passing through logging configured to hosted apps
- Don't terminate children of dev server process in extension
- Polish up process clean-up code
Fixes: https://github.com/OmniSharp/omnisharp-vscode/issues/4056, https://github.com/OmniSharp/omnisharp-vscode/issues/4070
=> Add more logging support and update clean-up logic for blazorwasm

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/TypeAccessibilityCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultFileUriProvider.cs
Fixes: Provides valid temp file for buffer without associated file
Fixes: Temp fix for invalid projected range
Fixes: https://github.com/dotnet/aspnetcore/issues/25105
Fixes: https://github.com/dotnet/aspnetcore/issues/26283
=> VS 16.8 Preview 4 Patch Fixes

azure-pipelines.yml, global.json
- ~Reverts the dotnet sdk upgrade from `rc.1.20452.10` to `preview.7.20366.6`~
- ~https://github.com/dotnet/aspnetcore-tooling/commit/33f2b33bc382d9d276ffaae9765deb8bb97740d5~
- @dougbu any concerns with doing this downgrade? 
Fixes: https://github.com/dotnet/aspnetcore/issues/26408
Error message with `rc.1`:
```
C:\aspnetcore-tooling\src\Razor\test\Microsoft.AspNetCore.Razor.Test.MvcShim\Microsoft.AspNetCor
e.Razor.Test.MvcShim.csproj : error : Version 5.0.100-rc.1.20452.10 of the .NET Core SDK requires at least version 16.8.0 of
MSBuild. The current available version of MSBuild is 16.7.0.37604. Change the .NET Core SDK specified in global.json to an
older version that requires the MSBuild version currently available.
C:\aspnetcore-tooling\src\Razor\test\Microsoft.CodeAnalysis.Razor.Works …
```
=> Update Build Pools

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/RazorSemanticTokensLegend.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SyntaxNodeExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/24483 and the first part of https://github.com/dotnet/aspnetcore/issues/24774.
Handle more tokens Semantically.
=> Semantic tokenization of HTML elements

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/26553 and https://github.com/dotnet/aspnetcore/issues/26563.
=> Don't handle color using statements yet

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs
This reverts commit 5281b4cd130a2b7243167c4b1216a0d0af3688cb.
Temporarily disabling this to unblock insertion
=> Revert "Enable script and style block support (#2579)"

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/ImplementInterfaceAbstractClassCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/TypeAccessibilityCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/TypeAccessibilityCodeActionProviderTest.cs
This builds off of @ajaybhargavb's mixed formatting https://github.com/dotnet/aspnetcore-tooling/pull/2585. Thanks @ajaybhargavb!
Testing: Covered from prior PR.
Fixes: https://github.com/dotnet/aspnetcore/issues/26399
=> Multi-Part Edit & Type Identifier Code Actions

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/TypeAccessibilityCodeActionProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/TypeAccessibilityCodeActionProviderTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/26653
=> Fix Diagnostic Span Out Of Range

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs
This reverts commit 49658068598733e1c65989a52519c32864037765.
=> Revert "Revert "Enable script and style block support (#2579)" (#2588)"

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultFallbackCapabilitiesFilterResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
Update LanguageServerClient packages to latest
=> Update LanguageServerClient packages to latest

eng/Versions.props, global.json
Will update the SDK version tomorrow
=> Update branding to 3.1.10

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorLanguageServerCustomMessageTargetTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/26860
Thanks @NTaylorMullen!
=> Fix Code Action MEF Issue

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/CSharpCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/ImplementInterfaceAbstractClassCodeActionProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionProviderTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionResolverTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/ImplementInterfaceAbstractClassCodeActionProviderTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/26715
Revert PR: https://github.com/dotnet/aspnetcore/issues/26867
=> Disable C# Code Actions in @functions blocks

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/MessageInterception/DefaultInterceptorManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/MessageInterception/IInterceptMethodMetadata.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/MessageInterception/InterceptMethodAttribute.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/MessageInterception/InterceptionMiddleLayer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/MessageInterception/InterceptionResult.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/MessageInterception/InterceptorManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/MessageInterception/MessageInterceptor.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/MessageInterception/DefaultInterceptionManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/MessageInterception/InterceptionMiddleLayerTest.cs
- Add support for extensible message interception handlers
- Add a default middle layer implementation that plugs into message interception.
=> Message interception

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/RazorSemanticTokensLegend.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/27181.
Responding to https://github.com/dotnet/roslyn/commit/24210551987101191a151304f1806264281f5c99#.
=> Include Record in Razor Legend

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultClientNotifierService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultClientNotifierServiceTest.cs
I failed to register `DefaultClientNotifierService` as an `IOnLanguageServerStarted`.
=> Fix the ClientNotifier

docs/contributing/BuildFromSource.md
Python needed for grammar tests (oniguruma).
=> Update Build from Source Instructions

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnAutoInsertHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/OnAutoInsertHandlerTest.cs
Blocked on: https://github.com/dotnet/roslyn/pull/48468
Fixes: https://github.com/dotnet/aspnetcore/issues/27511
Thanks @dibarbet!
=> Support C# OnAutoInsert

NuGet.config, eng/Versions.props
also
- switch from deprecated dotnet-core feed to dotnet-tools
- remove the down-level dotnet5 feeds
=> [master] Remove Roslyn and vs-editor MyGet feeds

eng/Versions.props, global.json
=> Update branding to 3.1.11

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DocumentPullDiagnosticsHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentPullDiagnosticsHandlerTest.cs
- Some of this will have to move around on account of https://github.com/dotnet/aspnetcore/issues/27563. However I haven't prioritized that work as this is all still pretty hot and I don't believe the VSCode/HTML LS implementations are available yet.
Part of https://github.com/dotnet/aspnetcore/issues/21121
=> Document Diagnostic Tests

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DocumentPullDiagnosticsHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentPullDiagnosticsHandlerTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/24590
=> Always allow error Diagnostics

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/razorLanguageService64S.servicehub.service.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
~*Note:* Still validating that this actually fixes the root issue.~ Validated!
- This is required for Roslyn to A/B t est various service hub skews.
Part of dotnet/aspnetcore#24476
=> Add support for ServerGC ServiceHub skew.

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultFallbackCapabilitiesFilterResolver.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnAutoInsertHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnTypeRenameHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/OnTypeRenameHandlerTest.cs
- HTML onTypeRename Support
Fixes: https://github.com/dotnet/aspnetcore/issues/27508
=> HTML onTypeRename Support

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultLSPEditorFeatureDetector.cs
This is (suspected to be) causing an issue in the Codespaces environment where the first file isn't appropriately classified as being LSP and consequently we get a non-LSP experience for it. No strong repro for this unfortunately.
Thanks @NTaylorMullen!
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1255364
Fixes: https://github.com/dotnet/aspnetcore/issues/28484
=> Remove ProjectSupportsRazorLSP Cache

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/ISemanticTokensLegendHandler.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/LegacySemanticTokensOptions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/ProvideSemanticTokensResponse.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/RazorSemanticTokensLegend.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/SemanticTokensDocumentProviderOptions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/SemanticTokensLegendParams.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/RazorSemanticTokensEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/RazorSemanticTokensLegendEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/RazorSemanticTokenInfoService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticRange.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticTokensEditsDiffer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
Turning on nullable in the SemanticTokens realm because I'm pretty sure it would have saved me from making a very silly null-ref mistake.
=> Code cleanup

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Serialization/TagHelperDescriptorJsonConverter.cs
- Found that in user dumps that when their `TagHelperDescriptor`s contained diagnostics that those diagnostics would each pin their backing JSON payload due to this lambda capture.
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1258678
Inclusive size for 13 diagnostics (in Bytes)
**Before:**  3,004,444
**After:** 1,676
=> Fix memory pinning when user has a diagnostic.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/RazorSemanticTokensLegend.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/28708.
=> Handle complex HTML comments

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Serialization/StringCache.cs
Following up on https://github.com/dotnet/aspnetcore-tooling/pull/2816#pullrequestreview-561205139.
=> PR feedback on StringCache

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/OptimizedCompletionList.cs
|                                              Method |      Mean |     Error |    StdDev |   Op/s |     Gen 0 |     Gen 1 |    Gen 2 | Allocated |
|---------------------------------------------------- |----------:|----------:|----------:|-------:|----------:|----------:|---------:|----------:|
| 'Component Completion List Roundtrip Serialization' | 32.623 ms | 0.6457 ms | 1.1139 ms |  30.65 | 2125.0000 | 1125.0000 | 187.5000 |  13.66 MB |
|           'Component Completion List Serialization' |  8.734 ms | 0.1084 ms | 0.1014 ms | 114.50 |  312.5000 |  234.3750 | 234.3750 |   2.42 MB |
|                                              Method |      Mean |     Error |    StdDev |   Op/s |     Gen 0 |     Gen 1 |    Gen 2 | Allocated |
|---------------------------------------------------- …
=> Cache commit characters raw json when serializing completion lists.

.github/CODEOWNERS
- This will ensure Allison is automatically included in GitHub Razor PRs
=> Add Allison to CodeOwners list

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/RazorProjectHostBase.cs
- This enables Blazor component completions to function properly with Razor class libraries.
- The resolved project.razor.json directory didn't exist for Razor class libraries. This occurred because:
1. Razor class libraries base intermediate path is not absolute. Meaning instead of C:/project/obj it returns /obj.
2. Our `new DirectoryInfo(...).Parent` call above is forgiving so if the path passed to it isn't absolute (Razor class library scenario) it utilizes Directory.GetCurrentDirectory where
in this case would be the C:/Windows/System path
Because of the above two issues the joinedPath ends up looking like "C:\WINDOWS\system32\obj\Debug\netstandard2.0\" which doesn't actually exist. The end-user effect of this
quirk means that you don't get any component completions for Razor class …
=> Properly resolve Razor class library intermediate output paths for project.razor.json.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/HTMLCSharpLanguageServerFeedbackFileLoggerProvider.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DocumentPullDiagnosticsHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorHtmlPublishDiagnosticsInterceptorTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/29073
=> E2E Diagnostics Logging 2, Followups & Stability

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionResolveHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionResolveHandlerTest.cs
- WebTools just added lots of performance improvements in this area that we need to consume to better improve our completion experience.
/cc @ToddGrun
=> Add support for HTML resolve handling.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_IncompleteTag.semantic.txt
Fixes: https://github.com/dotnet/aspnetcore/issues/29476.
=> Fix Null-Ref on nodes

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_DirectiveAttributesParametersAsync.semantic.txt, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_DirectivesAsync.semantic.txt, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_DoNotColorNonTagHelpersAsync.semantic.txt
Fixes: https://github.com/dotnet/aspnetcore/issues/29471.
=> TagHelper attribute values colorize correctly

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperServiceTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_MinimizedDirectiveAttributeParameters.semantic.txt
Fixes: https://github.com/dotnet/aspnetcore/issues/27912
Before:
After:
=> Fix unknown HTML Semantic colorization

.githooks/pre-commit, build.ps1
Made this as similar as possible to https://github.com/dotnet/aspnetcore/pull/27712. Should help with small formatting problems in PRs.
=> Git hooks format

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentSynchronizationEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticRange.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionResolverTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorConfigurationServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingContentValidationPassTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingDiagnosticValidationPassTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsPublisherTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Serialization/RazorExtensionSerializationTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorContentTypeChangeListenerTest.cs
Noticed one of these and just did fix-all to make it go away.
=> Fix unsused usings

eng/Versions.props
- Validated earlier: https://github.com/dotnet/aspnetcore-tooling/pull/2796
- Requires Roslyn to also upgrade for us to be able to re-validate.
=> Upgrade LS Client Implementation for Tag Support

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsEndpointTest.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/29692
=> Fix Diagnostics in Markup/TagHelper Attribute with C#

src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/WorkItemAttribute.cs
Allows linking tests to issues.
=> Add WorkItemAttribute utility

.github/CODEOWNERS
- @sharwell this would mean you're auto-included on all PR reviews. If this is something you're not interested in to avoid the noise let me know
=> Add @sharwell to codeowners

src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/RazorGuestInitializationServiceTest.cs
=> Fix flaky test CreateServiceAsync_SessionDispose_CancelsListRootsToken

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs
Fixes: https://github.com/dotnet/aspnetcore/issues/27913
=> Update project on DocumentRemoved

Directory.Build.props, eng/Versions.props
* Microsoft.CodeAnalysis.Analyzers 3.3.2
* Microsoft.CodeAnalysis.NetAnalyzers 5.0.3
* Microsoft.CodeAnalysis.BannedApiAnalyzers 3.3.2
=> Update to the latest code analysis packages

eng/config/globalconfigs/ApiShim.globalconfig, eng/config/globalconfigs/Common.globalconfig, eng/config/globalconfigs/NonShipping.globalconfig, eng/config/globalconfigs/Shipping.globalconfig, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundDocumentGenerator.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Microsoft.VisualStudio.Editor.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Microsoft.VisualStudio.LanguageServerClient.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/Microsoft.VisualStudio.Mac.LanguageServices.Razor.csproj, src/Razor/src/rzls/rzls.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.ComponentShim/Microsoft.AspNetCore.Razor.Test.ComponentShim.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.ClassLib/Microsoft.AspNetCore.Razor.Test.MvcShim.ClassLib.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version1_X/Microsoft.AspNetCore.Razor.Test.MvcShim.Version1_X.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version2_X/Microsoft.AspNetCore.Razor.Test.MvcShim.Version2_X.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim/Microsoft.AspNetCore.Razor.Test.MvcShim.csproj, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/Microsoft.VisualStudio.Editor.Razor.Test.Common.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test.Common/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test.Common.csproj
=> Update shipping designations

Directory.Build.props, eng/Versions.props, eng/config/globalconfigs/ApiShim.globalconfig, eng/config/globalconfigs/Common.globalconfig, eng/config/globalconfigs/NonShipping.globalconfig, eng/config/globalconfigs/Shipping.globalconfig, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/ProjectSystem/BackgroundCodeGenerationBenchmark.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/VisaulStudioFileChangeTracker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultRazorProjectHost.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/FallbackRazorProjectHost.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/RazorProjectHostBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedDocumentPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingLanguageServerClient.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationStateSynchronizerTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorProjectHostTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackRazorProjectHostTest.cs
=> Install Roslyn.Diagnostics.Analyzers

NuGet.config, eng/Version.Details.xml, eng/Versions.props, global.json
=> Update branding to 3.1.13

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPass.cs
Update CSharpFormattingPass to have a different order from HtmlFormattingPass.
=> Ensure the order of IFormattingPass is deterministic

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/DefaultLogHubLogWriter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLogWriter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLogger.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
```csharp
_logger.LogInformation("This is information");
_logger.LogWarning("This is a warning");
try
{
throw new Exception("SOME EXCEPTION");
}
catch (Exception e)
{
_logger.LogError(e, "This is a error");
}
```
Part of: https://github.com/dotnet/aspnetcore/issues/29269
=> Support Log Hub Error Levels

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnAutoInsertHandler.cs
- I plan to utilize the snippet tech in completion edit translation which will require this wrapping/unwrapping capabilities.
Part of dotnet/aspnetcore#29619
=> Refactor text edit snippet wrapping to the language server.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SourceTextExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/TextLineExtensions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
=> Preserve blank lines during formatting

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
Feedback for: https://github.com/dotnet/aspnetcore-tooling/pull/3132
Part of dotnet/aspnetcore#29619
=> React to pull request feedback for https://github.com/dotnet/aspnetcore-tooling/pull/3132

NuGet.config
- remove remaining way user NuGet.config can infect builds
=> [master] Clear disabled package sources

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/LegacyHTMLCSharpLanguageServerFeedbackFileLoggerProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/DefaultLogHubLogWriter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/HTMLCSharpLanguageServerLogHubLoggerProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLogWriter.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLogger.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLoggerProviderFactory.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLoggerProviderFactoryBase.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/RazorLogHubTraceProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorHtmlPublishDiagnosticsInterceptor.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorHtmlPublishDiagnosticsInterceptorTest.cs
Creating a separate PR as I'm only pushing approved code to #3116 to keep things more manageable.
=> LogHub Feedback

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/HTMLErrorCodes.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorSyntaxTreeExtensions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsEndpointTest.cs
Addresses invalid warning seen in https://github.com/dotnet/aspnetcore/issues/30358.
Part of: https://github.com/dotnet/aspnetcore/issues/28654
=> Ignore Invalid Nested warning when in component

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/HTMLErrorCodes.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorSyntaxTreeExtensions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsEndpointTest.cs
Part of: https://github.com/dotnet/aspnetcore/issues/28654
=> Remove duplicate missing closing bracket diagnostic

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/LanguageServer/RazorLanguageServerBenchmarkBase.cs, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Performance/LanguageServer/RazorSemanticTokensBenchmark.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticTokensEditsDiffer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokenTestBase.cs, src/Razor/test/testapps/ComponentApp/Components/Pages/Append.extra, src/Razor/test/testapps/ComponentApp/Components/Pages/SemanticTokens.razor
Part of https://github.com/dotnet/aspnetcore/issues/30247.
With this fix:
|                             Method |     Mean |    Error |   StdDev |  Op/s |    Gen 0 |    Gen 1 |   Gen 2 | Allocated |
|----------------------------------- |---------:|---------:|---------:|------:|---------:|---------:|--------:|----------:|
| 'Razor Semantic Tokens Formatting' | 21.08 ms | 0.416 ms | 0.597 ms | 47.43 | 968.7500 | 531.2500 | 93.7500 |   6.13 MB |
Without fix:
|                             Method |     Mean |    Error |   StdDev |  Op/s |      Gen 0 |    Gen 1 | Gen 2 | Allocated |
|----------------------------------- |---------:|---------:|---------:|------:|-----------:|---------:|------:|----------:|
| 'Razor Semantic Tokens Formatting' | 70.38 ms | 0.723 ms | 0.641 ms | 14.21 | 60285.7143 | …
=> Fix extra SemanticTokens allocations

NuGet.config
- remove remaining way user NuGet.config can infect builds
=> [release/3.1] Clear disabled package sources

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundDocumentGenerator.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs
- Discovered a race that where interactions with document parsing / open document detection could race in unexpected ways. Basically what would happen is that once a document was opened we'd be notified and then go and "suppress" the background document in Visual Studio; however, if a previous request was still active / being parsed we'd run into situations where the suppressed document would then have content populated after-the-fact resulting in ambiguity errors.
- Added a test to validate the race condition is fixed.
Fixes AB#1283341
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1283329
=> Fix background parsing race.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLogWriter.cs
Just to match the latest guidance, not noticing any changes in behavior.
=> Add jsonRpc TraceSource

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorContentTypeChangeListener.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorContentTypeChangeListenerTest.cs
- Prior to this we would always untrack -> track despite the new content type. Added checks to ensure that we validate the new content type we're moving "to". However, during this process I found that the `textDocument.TextBuffer` wasn't updated to the renamed content type so we need to re-calculate the content type to ensure we don't re-track the document.
- Added tests.
Fixes dotnet/aspnetcore#31375
=> Add support for .razor => non.razor extension.

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/TestLanguageServiceBroker.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Microsoft.VisualStudio.LanguageServices.Razor.Test.csproj, src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Microsoft.VisualStudio.LiveShare.Razor.Test.csproj
=> Version Upgrades

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPDocumentSynchronizer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/DefaultLSPDocumentSynchronizerTest.cs
- This hang was specifically introduced due to synchronizations being kicked off in quick succession/within the same callstack. To address this we now dispatch synchronization "success" calls asynchronously.
- As part of this I also found that when a document is closing down we don't invalidate all active requests which means if a user is typing in quick succession and we're waiting for synchronization events its possible that we hang the IDE> Given the simplicity of the fix I also batched that in this changeset.
- Added tests.
Fixes dotnet/aspnetcore#31462
=> Fix document synchronization VS hang.

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/OnAutoInsertHandlerTest.cs
=> Minor Test Cleanup

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextViewConnectionListener.cs
This is #3397, which was somehow merged/closed automatically.
=> Add exception checking in TextViewConnectionListener

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextViewConnectionListener.cs
=> Merge release/vs16.10-preview2 into main

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_MultiLineCommentAsync.semantic.txt, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_MultiLineCommentMidlineAsync.semantic.txt
Fixes https://github.com/dotnet/aspnetcore/issues/27447.
=> Fix multiline Razor comments

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.tmTheme, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_CSharp_Nested_HTML.semantic.txt, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_NestedIfDirectives.semantic.txt, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_NestedTextDirectives.semantic.txt, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_Razor_NestedTransitions.semantic.txt
Fixes https://github.com/dotnet/aspnetcore/issues/29595 and https://github.com/dotnet/aspnetcore/issues/30555
Before: 
After:
=> Semantic colorization edge cases

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
- Also add reactive propery arch for json.
Fixes dotnet/aspnetcore#31600
=> Update VSSDK Build Tools

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
Part of dotnet/aspnetcore#30232
=> Utilize OptimizedVSCompletionList for HTMLC#

eng/config/globalconfigs/ApiShim.globalconfig, eng/config/globalconfigs/Common.globalconfig, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/ProjectSystem/ProjectSnapshotManagerBenchmarkBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultProjectResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/BackgroundDocumentProcessedPublisher.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultTagHelperResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentExcerptServiceBase.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/EditorDocumentManagerBase.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/VisualStudioTextChange.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorUIContextManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextViewConnectionListener.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RemoteHierarchyService.cs, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Host/DefaultProjectSnapshotManagerProxy.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/RazorProjectHostBase.cs, src/Razor/src/rzls/Program.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Common.Test/BackgroundDocumentGeneratorTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/IntermediateNodeVerifier.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/Legacy/SyntaxNodeVerifier.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/SyntaxTreeVerifier.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/TestCompilation.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.ClassLib/Microsoft.AspNetCore.Razor.Test.MvcShim.ClassLib.csproj, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Serialization/RazorConfigurationSerializationTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/TestTextBuffer.cs, src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/DefaultRazorProjectHostTest.cs
General cleanup and silencing noisy Analyzer suggestions.
=> Lint cleanup

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
I am adding value for our customers!
=> Achieving weekly KPIs and knocking monthly OKRs out of the park

.github/CODEOWNERS
=> Removed @TanayParikh from CodeOwners 👋 

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/OptimizedCompletionList.cs
=> Fix null ref when serializing non-VS completion list.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingTest.cs.cs
Fixes https://github.com/dotnet/aspnetcore/issues/19445
I haven't actually _run_ this yet (gotta install node??) so I might have missed something really obvious.. but hey the tests pass ¯\\\_(ツ)_/¯
=> Fix formatting of C# code blocks

eng/Versions.props
- Had to update StreamJsonRpc and the LSP platform bits along side it.
=> Update Shell to `17.0.0-preview-2-31228-438`

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/MSN.cshtml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1325272
=> Remove static content.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/DefaultRazorSemanticTokenInfoServiceTest/GetSemanticTokens_HTMLIncludesBang.semantic.txt
- This was simply miscategorized.
Fixes: https://github.com/dotnet/aspnetcore/issues/32821
=> HTML Bangs as RazorTransitions

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs
CC @NTaylorMullen.
Notifying us about this is great, giving us 50+ Debug.Assert dialog boxes is not.
=> Don't Debug.Assert repeatedly

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/IUIThreadOperationExecutorExtensions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageService`IVsLanguageDebugInfo.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDiagnosticsEndpointTest.cs
- Move the Dialog calls into an extension method.
Fixes: The feedback that I missed on the other PR.
=> Move dialog to extension

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPTextViewConnectionListener.cs
- Today we polyfill the `workspace/didChangeConfiguration` request in VS however in scenarios where our Razor language server isn't running this throws an exception. That being said the exception is instantly caught and discarded but this fix at least stops the exception from throwing initially.
Fixes dotnet/aspnetcore#33262
=> Protect workspace/didChangeConfiguration from RZLS being down.

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/RazorFeedbackDiagnosticFileProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/RazorLogHubTraceProvider.cs
- There were some breaking changes that can unexpectedly bite us on renames of Task -> TaskListItem in some scenarios.
=> Update our VSShell package versions.

eng/Versions.props, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj
=> Fix old reference to MS.VS.Validation.

azure-pipelines.yml
- Following [the arcade docs for OneLocBuild](https://github.com/dotnet/arcade/blob/main/Documentation/OneLocBuild.md#onboarding-to-onelocbuild-using-arcade).
Part of https://github.com/dotnet/aspnetcore/issues/33084.
=> Continue loc onboarding for Razor tolling

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/RazorFeedbackDiagnosticFileProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/RazorLogHubTraceProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj
This exposed an underlying Microsoft.VisualStudio.Validation assembly load issue that I don't currently have time to dig into. To unblock the build reverting all those bits
=> Revert VS.Shell update

azure-pipelines.yml
=> Fix missing Loc builds

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingBlockKind.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContentValidationPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingDiagnosticValidationPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingResult.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingSpan.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingSpanKind.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormatter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/IFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/IndentationContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorDocumentRangeFormattingParams.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorDocumentRangeFormattingResponse.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/StringExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/NullableAttributes.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedDocumentPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingLanguageServerClient.cs
Thought I'd at least make a start, and it was surprisingly straightforward.
=> Null annotate formatting code

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.tmTheme
- Remove TextMate coloration for `HTML  Server-Side Script`.
Fixes: https://github.com/dotnet/aspnetcore/issues/33567
=> Don't TextMate razor directives

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/27102
=> Fix end span clean up if the start span cleanup added a newline

.gitattributes, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VS.LSClientRazor.Resources.resx, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/ViewCodeCommandHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.cs.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.de.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.es.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.fr.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.it.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.ja.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.ko.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.pl.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.pt-BR.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.ru.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.tr.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.zh-Hans.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.zh-Hant.xlf, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/ViewCodeCommandHandlerTests.cs
Fixes https://github.com/dotnet/aspnetcore/issues/33794
I know I need tests, I just hate mocks so I need to pluck up the courage overnight to create some.
=> Add View Code command from a razor file

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingSpan.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/29837
Well this was easy.
For fun I changed the `2` to a `3` and a bunch of other tests broke so I have some confidence that the coverage here is okay.
=> Track Component nesting in code blocks too

eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorDocumentServiceProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorSpanMappingService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Feedback/RazorFeedbackDiagnosticFileProvider.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorDocumentOptionsService.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorDocumentOptionsServiceTest.cs
- This is essentially https://github.com/dotnet/aspnetcore-tooling/pull/3768, which was reverted due to RPS issues on the Roslyn side.
- Fixed the RPS issues in https://github.com/dotnet/roslyn/pull/54857, so we should be good to go now. Tested and confirmed things work.
Fixes: 
https://github.com/dotnet/aspnetcore/issues/32555
=> Add back in Razor options service after Roslyn RPS fixes

eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj, src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Microsoft.VisualStudio.LiveShare.Razor.Test.csproj
- We seem to have run into some versions conflicts after a Roslyn package version was deleted, trying to resolve by pinning versions.
=> Update threading version

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/VS.LSClientRazor.Resources.resx, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.cs.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.de.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.es.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.fr.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.it.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.ja.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.ko.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.pl.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.pt-BR.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.ru.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.tr.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.zh-Hans.xlf, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/xlf/VS.LSClientRazor.Resources.zh-Hant.xlf
- Responding to LSP client breaking changes (addition of new activation failure APIs)
TODO - complete test insertion
=> Implement new LSP client activation failure APIs

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/OmniSharpVSDiagnostic.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/OmniSharpVSDiagnosticProjectInformation.cs
- We didn't properly serialize the project information for a diagnostic, now we do!
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1360736
=> Fix error squiggles showing up for Razor diagnostics

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingPass.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/34961
Intended to work on https://github.com/dotnet/aspnetcore/issues/32419
Found nothing wrong, decided to format using statements anyway.
I think I logged that issue based on an assumption of razor syntax that doesn't hold true.
=> Format using directives

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CSharpStatementBlockOnTypeFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/35001 (still working on a test, will update)
Fixes https://github.com/dotnet/aspnetcore/issues/34965
=> Fix regression in code block formatting

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorProjectChangePublisher.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/DefaultRazorProjectChangePublisherTest.cs
- When a project gets updated TagHelpers we used to put it on a delay of 3s before publishing any information for it. I changed that logic to fast-path TagHelper resolution (no delay) if we detect that potential TagHelper changes have happened.
- Added and updated tests.
Fixes dotnet/aspnetcore#35129
=> Improve TagHelper resolution speeds 2x

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VsSolutionUpdatesProjectSnapshotChangeTrigger.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/VsSolutionUpdatesProjectSnapshotChangeTriggerTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1364660
I couldn't repro the hang (I suspect luck might be part of it?) but it certainly was quicker with this change. My preview 4 build is pretty crappy though, so anything is possible :)
=> Ensure initialize switches to main thread before getting service

eng/targets/Npm.Common.targets
Please Mr Node, just leave me alone :(
(this variable was already used for build, but restore kept erroring and annoying me)
=> Allow my restores to happen

src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/RazorProjectHostBase.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1390411
Another one.
I search (thoroughly!) this time and couldn't find any other event handlers that were asserting so hopefully this is it.
=> Switch to dispatcher thread in VS Mac

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs
Fixes https://github.com/dotnet/aspnetcore/issues/34319
=> Expand on type formatting range to encompass clean up operations made earlier in the file

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs
- Overall this was a blatant oversight. Our background diagnostic publisher utilizes async void methods because of its reliance on timers; however, turns out this can throw (this is a separate issue).
- Found that Razor diagnostics from the compiler can occasionally explode with null ref exceptions when getting their diagnostic data. That's tracked here: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1405849
Fixes dotnet/aspnetcore#36774
=> Protect VS from crashing when diagnostic publisher throws.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorServerReadyPublisher.cs
- Went through the code to verify that we were try-catching around all relevant locations in our async
=> Try-catch around all async void locations

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSnapshotManagerDispatcherBase.cs
- Made the `ProjectSnapshotManagerDispatcher` teardown its inner thread when disposed. Because the dispatcher itself is now disposable the when an outer service collections tears down (language server shutting down or VS close) then our dispatcher will also have its thread killed.
Fixes dotnet/aspnetcore#36788
=> Teardown dispatcher threads on solution close.

docs/contributing/ASPNetCore-Debugging.md, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs
- Requires changes from https://github.com/dotnet/aspnetcore/pull/36907 to propagate
=> Add Support for SupportLocalizedComponentNames

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
- This will require a good amount of VS changes but that's all staged here: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/353104?_a=files
Fixes dotnet/aspnetcore#36554
=> Ngen O# assemblies and their dependencies

src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor.CoreComponents/Microsoft.CodeAnalysis.Remote.Razor.CoreComponents.csproj
@NTaylorMullen Could you help validate this change and make sure I didn't miss anything? Thanks!
=> Remove common dependencies between Razor and Roslyn

NOTICE.txt
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1391337
=> Add third party notices file.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs
- The platform changed how the text structure navigator APIs behave at the edges of words. Because of this we need to re-calculate how we capture word spans. For instance when we'd ask for the wordspan at `p|\r\n` we'd get `\r\n` without this change set resulting in no snippets.
Fixes #4599
=> Fix C# snippets being included in completion.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs
=> Update var name

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DefaultRazorFormattingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveOnTypeFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs
Fixes https://github.com/dotnet/razor-tooling/issues/5698
=> Don't send back edits if no changes were made

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
- This fixes the dreaded "Disco Colors". Basically what happens is that when provisional completion fires it makes two edits to the backing C# document (to manually add a `.` which is otherwise interpreted as HTML). These modifications at programmatic speed seems to cause the document to get out of sync, as evidenced by colors being in the wrong position and by Debug.Asserts about the length of the C# backing document.
- This can be reproduced by typing `@FirstName.N` inside a razor Document with C# under that point.
- We don't want to leave Provisional Completion removed but we estimate that having to type `@DateTime.N` until we figure out a more permanent fix will be minimally invasive, as opposed the very confusing color changes when you're just typing.
Edit: I lucked into the actual …
=> Fix Provisional completions in error cases

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/UnformattedRemappingCSharpCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentVersionCache.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentVersionCache.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/PositionExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultDocumentResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DocumentResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentSynchronizationEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLS.Resources.resx, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.cs.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.de.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.es.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.fr.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.it.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.ja.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.ko.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.pl.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.pt-BR.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.ru.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.tr.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.zh-Hans.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/xlf/RazorLS.Resources.zh-Hant.xlf, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshot.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs
- We noticed some Argument Null exceptions being thrown from the "Get DocumentSnapshot and Version safely". Considered extracting them into a helper method, but there's not a great class I could attach it to, unless we created a static helper and passed in a bunch of extra objects.
Fixes part of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1435565
=> More Nullable

azure-pipelines.yml
Copying @wtgodbe's commit here: https://github.com/dotnet/razor-tooling/pull/5765
=> Move off of expiring machine pools

src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version1_X/Microsoft.AspNetCore.Mvc.Razor/RazorInjectAttribute.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version1_X/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewContextAttribute.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version1_X/Microsoft.AspNetCore.Mvc/ViewComponentAttribute.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version2_X/Microsoft.AspNetCore.Mvc.Razor/RazorInjectAttribute.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version2_X/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewContextAttribute.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim.Version2_X/Microsoft.AspNetCore.Mvc/ViewComponentAttribute.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim/Microsoft.AspNetCore.Mvc.Razor/RazorInjectAttribute.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewContextAttribute.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.MvcShim/Microsoft.AspNetCore.Mvc/ViewComponentAttribute.cs
- Got annoyed with the warnings from not having these attributes.
=> Set AttributeUsage

.github/ISSUE_TEMPLATE/config.yml, CONTRIBUTING.md, docs/contributing/ASPNetCore-Debugging.md, docs/contributing/BuildFromSource.md, docs/contributing/Roslyn-Debugging.md
Updates tooling docs to reflect the new compiler repo.
=> Update tooling docs

src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/package.json, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/yarn.lock
Addresses:
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/6063426?typeId=6437374
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/5469399?typeId=6437374
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/5469400?typeId=6437374
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/6063424?typeId=6437374
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/6063425?typeId=6437374
=> Fix Razor.VSCode.Test component governance issues.

eng/Tools.props
Addresses:
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/3714283?typeId=6437627
- https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-razor-tooling/alert/2939605?typeId=6437627
=> Update yarn.msbuild to latest version

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormattingPass.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
Fixes https://github.com/dotnet/razor-tooling/issues/5749
=> Fix render fragment formatting in C# blocks

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/VisualStudioEditorDocumentManager.cs
- Originally when this work was done I attempted to call the advise in the ctor; however, that in practice didn't work out so well. Therefore, given that the editor document manager is always "started" / requested elsewhere we can lazily advise the running document table when already on the UI thread.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1441597
=> Call AdviseRunningDocTableEvents on UI thread take 2.

azure-pipelines.yml
Part of dotnet/aspnetcore-internal#3950
=> [release/3.1] Move off of expiring machine pools

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json
Bumping version to patch release with the following fixes:
- 1bfaa81dc7d108163838bbc60d2428782db02586
- 5a1ce433f343fcbec43394fccf7f53b345e27a20
- 08353b0c928adbf660541a5a7a0ad391202bd32f
=> Update BlazorWasmDebuggingExtension version for release

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ComponentAccessibilityCodeActionProviderTest.cs
I am very excited as this is my first ever PR to a public repo. It fixes some minor issue, but anyway I feel proud of myself 😊
Fixes: 
https://github.com/dotnet/razor-tooling/issues/5888
=> Fixed tests locale issues

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/yarn.lock, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/yarn.lock, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/yarn.lock
- Ran restore.cmd and this is the latest yarn.lock values. To prevent suppressing these changes everytime I figured we should just check this in.
=> Update yarn.lock files.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
Not the best solution from my poin of view, but it works
Fixes: https://github.com/dotnet/razor-tooling/issues/5827
Before:
After:
=> Fixed initializer completions

.editorconfig, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/ActivityLogRazorLogger.cs
Fixes #5939
Would love someone to validate this on their machine, because VS was being weird, but this worked for me.
=> Pump up the volume

eng/targets/Npm.Common.targets
We did this ASP.NET Core and should do it here too: https://github.com/dotnet/aspnetcore/pull/37834
=> Always use frozen lockfiles

azure-pipelines.yml
=> Use official AZDO pools for non-public builds.

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/DefaultLSPDocumentMappingProvider.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/DefaultLSPDocumentMappingProviderTest.cs
This is https://github.com/dotnet/razor-tooling/pull/6034 but without the more controversial bits.. this is just a good idea :)
=> Don't clobber deserialized types

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs
- Basically the way things are right now can result in Razor requesting a span from Roslyn with a Start-point that is after the End-point because we're comparing them against the host project (.razor file) instead of the Generated project. This makes Roslyn throw and the whole request fail. 
- Stripping this out of https://github.com/dotnet/razor-tooling/pull/6022/files since it fixes a break rather than a perf issue.
- I wasn't able to come up with a unit test that tests this (and because of the nature of our mocks even if I did it would be fairly artificial). Further, because of the semi-randomness of the generated backing file even if I were able to create an Integration test that tests this it may stop testing it without us knowing in the future. We DO have a repro case for the full …
=> Don't produce backward ranges

eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Serialization/PlatformExtensionConverter.cs, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Microsoft.AspNetCore.Razor.LanguageServer.Test.csproj
This fixes the build for me. Would appreciate someone else verifying (and obviously let's see if CI breaks)
=> Fix main build

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/DefaultRazorSemanticTokensInfoService.cs
- Don't produce backward ranges
=> Merge release/17.2.0-preview1 into main

eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultRazorDynamicFileInfoProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentExcerptServiceBase.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DynamicDocumentContainer.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorDocumentExcerptService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorDocumentServiceProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultDynamicDocumentContainer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpDocumentExcerptService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentPublisher.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/RazorDocumentExcerptServiceTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpDocumentExcerptServiceTests.cs
=> Update to new IRazorExcerptServiceimplementation interface

src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/MessageInterception/InterceptionMiddleLayer.cs
This is needed e.g. for workspace/symbols, where the response may
contain a virtual document and need to be remapped to the user document.
Needed for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1317962
=> Allow MessageInterceptors to intercept request responses

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
Fixes https://github.com/dotnet/razor-tooling/issues/6092
=> Format array initializers

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
Fixes https://github.com/dotnet/razor-tooling/issues/6090
=> Fix formatting in the presence of HTML comments

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/OnTypeFormattingTests.cs
=> Skip test until we have a real version number

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
Fixes https://github.com/dotnet/razor-tooling/issues/6175
=> Don't format Razor comment bodies

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/IndentationContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ILoggerExtensions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs
Just some formatting test helper changes that make diagnosing failures easier.
=> Help with writing and debugging formatting tests

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/GoToDefinitionTests.cs
Maybe this will work ¯\\\_(ツ)_/¯
=> Enable test

eng/pipelines/test-integration-job.yml
- Failed to update the VSMain integration pipeline when we switched test output type.
=> Collect test files

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj
- Occasionally when building we'd encounter the following error:
The odd thing is this error is inconsistent and happens only on occasion so I'm shotting in the dark here a little bit. We've encountered similar things in the past so I've gone forward and pinned the versions I've seen this error complain about.
=> Try and fix incoherent package version error during build.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/BackgroundDocumentGenerator.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentVersionCache.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LanguageServerErrorReporter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/OpenDocumentGenerator.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorServerReadyPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpWorkspaceProjectStateChangeDetector.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin/MSBuildProjectManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ErrorReporter.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/JoinableTaskContextExtensions.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSnapshotManagerDispatcher.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectChangeEventArgs.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioRazorParser.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/EditorDocumentManagerListener.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/RazorCodeDocumentProvidingSnapshotChangeTrigger.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorTextViewConnectionListener.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/VisualStudioRazorParser.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/ProjectRazorJsonPublisher.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ActivityLogRazorLogger.cs, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/ProjectSnapshotSynchronizationService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultWorkspaceSemanticTokensRefreshPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultWorkspaceSemanticTokensRefreshTriggerTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.OmniSharpPlugin.Test/MSBuildProjectManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultTextBufferCodeDocumentProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultProjectSnapshotManagerTest.cs
- No `async void`.
- Nullable for the stuff we touch.
Fixes: https://github.com/dotnet/razor-tooling/issues/5991
=> Resolve Threading issues

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/OutputInProcess.cs
- We were seeing tests where the logs failed to collect, so after asking @sharwell I made some improvements to our call patterns here.
=> Threading and Service Feedback

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/CompletionHandlerTest.cs
- When C# turned on `TextEdit` support for completion items it broke our provisional completion handling. Turns out though that we had a pretty massive gap in how we determined something was a provisional completion and then captured the "correct projection" for that provisional completion. For instance when you type `@DateTime.` what happens is the `.` is understood as HTML so we detect that and inject a fake `.` into the C# buffer and THEN ask for completions (a provisional completion). Problem is that the original projection for the `.` was HTML so if that was represented by line 0 character 10 we needed to also update our projection handling to say actually the projection was line 93 character 15 (to represent the location after the injected `.` in the C# buffer). This way when we …
=> Fix provisional completion + C# text edits.

eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/DefaultRazorHoverInfoService.cs
- The 17.3.15 version is the one VS will be shipping with.
=> Update to 17.3.15 LSP protocol version

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/FormatDocumentTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/TestFiles/Expected/BadlyFormattedCounter.razor, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/TestFiles/Expected/FormatAndUndo.cshtml, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/TestFiles/Input/BadlyFormattedCounter.razor, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/TestFiles/Input/FormatAndUndo.cshtml
Fixes https://github.com/dotnet/razor-tooling/issues/6418
=> Remove bad test

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Debugging/RazorBreakpointSpanEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Debugging/RazorProximityExpressionsEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorDocumentMappingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentPresentation/AbstractTextDocumentPresentationEndpointBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlineCompletion/InlineCompletionEndPoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WrapWithTag/WrapWithTagEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorDocumentMappingServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentPresentation/TextDocumentTextPresentationEndpointTests.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentPresentation/TextDocumentUriPresentationEndpointTests.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Extensions/ClientCapabilitiesExtensionsTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/WrapWithTag/WrapWithTagEndpointTests.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultEditorSettingsManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
Fixes https://github.com/dotnet/razor-tooling/issues/6412
=> Allow wrap with div to make better choices

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.Razor.TagHelperProvider.servicehub.service.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.Razor.TagHelperProvider64.servicehub.service.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.Razor.TagHelperProvider64S.servicehub.service.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/ServiceHubCore/Microsoft.VisualStudio.Razor.TagHelperProviderCore64.servicehub.service.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/ServiceHubCore/Microsoft.VisualStudio.Razor.TagHelperProviderCore64S.servicehub.service.json
- Asked to change the name
/cc @genlu Here's our reaction to the announcement. Nothing works because it's not inserted yet + I'm not sure if it'll even work until Roslyn reacts. Thought I'd ping you either way
=> Migrate to changed ServiceHub host names.

azure-pipelines.yml
Adds SDL validation to the official build.
=> Add SDL validation

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingPass.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingTest.cs
Fixes https://github.com/dotnet/razor-tooling/issues/6485
=> Format close brace of code directives

azure-pipelines-compliance.yml, eng/TSAConfig.gdntsa
- This mostly copies Roslyn's approach here: https://github.com/dotnet/roslyn/pull/61905
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1531320
=> Add compliance pipeline for running APIScan.

azure-pipelines-compliance.yml
The build step needed a few tweaks to work with the razor-tooling repo. 
Test Run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6330052&view=results (microsoft)
=> Update compliance build step

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/RazorCodeDocumentProvidingSnapshotChangeTrigger.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1553401
Fixes AB#1553401
=> Allow for CPS to call DocumentAdded twice

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/OnAutoInsertHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/LogHubLogger.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1559814
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1559845
TL;DR its all Ryan's fault 😛
https://github.com/dotnet/razor-tooling/pull/6495/files#diff-d784699410203c26bebd37db140abfab8a7ec6801e53ede6a16c1298c77dea28R90
=> Fix log message for OnAutoInsert

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
Fixes https://github.com/dotnet/razor-tooling/issues/6548
I'm sure there are more edge cases to find too...
=> More initializer edge case pain

NuGet.config
Fixes https://github.com/dotnet/razor-tooling/issues/6563 (?)
=> Map packages to their sources

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/.npmrc, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/.npmrc, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/.npmrc, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/.npmrc, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/.npmrc, src/Razor/test/VSCode.FunctionalTest/.npmrc
- Porting from [this PR that was done on the wrong repo](https://dev.azure.com/dnceng/internal/_git/dotnet-razor-tooling/pullrequest/23705?_a=files). I tried to maintain branch / naming etc. but wasn't able to maintain author info. Seems like Azdo threw away the details maybe?
=> Remediating Azure Artifacts Configuration Issues.

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultRazorDynamicFileInfoProvider.cs
- Mac & windows boxes represent file paths differently `/` versus `\`. Sadly at the portion where our system intersects with project systems (CPS or VSMac's custom) file paths need to fall back to a platform equivalent so that files can properly be looked up. This changeset adds a platform check in order to special case this scenario. Didn't feel great about this path but I don't have a better way without making external-to-razor project system specific changes on both VSWin and VSMac.
=> Fix VSMac file paths for LSP editor.

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1576608
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1579252
=> Address PoliCheck issues :D

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/RazorCodeDocumentProvidingSnapshotChangeTrigger.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SourceMappingAdornment.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1580007
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1579500
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1579508
=> Various accessibility fixes for Syntax Visualizer

azure-pipelines.yml
=> Extend timeout to 2 hours for Windows builds.

src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1579937
=> Use the same colour for treeview item selection, whether focused or not

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/FoldingRangeEndpoint.cs
I could never repro the folding range exceptions on my machine, _except_ operation cancelled exceptions, which we'd just mindlessly retry over and over, which is a bit silly.
=> Be a good citizen

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/ISemanticTokensRefreshEndpoint.cs
Fixes https://github.com/dotnet/razor-tooling/issues/6685
=> Listen for the right LSP method

eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/ProjectSnapshotSynchronizationService.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test.Common/Xunit/ForegroundTestCase.cs
Addressing some component governance alerts.
A few alerts are not being addressed because they only impact test code.
=> Fix component governance issues for release/3.1 branch

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerToolWindow.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizerMenu.vsct, src/Razor/src/Microsoft.VisualStudio.RazorExtension/VSThemeDictionary.xaml, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.cs.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.de.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.es.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.fr.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.it.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.ja.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.ko.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.pl.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.pt-BR.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.ru.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.tr.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.zh-Hans.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.zh-Hant.xlf
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1580626
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1579938
Fixes color issues for buttons/tree control by using VS themes. It also now supports dark mode!
=> Theme the syntax visualizer

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.BlazorWasmDebuggingExtension/yarn.lock, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/package.json, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Test/yarn.lock, src/Razor/test/VSCode.FunctionalTest/package.json, src/Razor/test/VSCode.FunctionalTest/yarn.lock
I _think_ this...
Fixes https://github.com/dotnet/razor-tooling/security/dependabot/40
Fixes https://github.com/dotnet/razor-tooling/security/dependabot/39
Fixes https://github.com/dotnet/razor-tooling/security/dependabot/27
Fixes https://github.com/dotnet/razor-tooling/security/dependabot/20
Fixes https://github.com/dotnet/razor-tooling/security/dependabot/18
Fixes https://github.com/dotnet/razor-tooling/security/dependabot/17
Fixes https://github.com/dotnet/razor-tooling/security/dependabot/11
Fixes https://github.com/dotnet/razor-tooling/security/dependabot/10
Fixes https://github.com/dotnet/razor-tooling/security/dependabot/8
Fixes https://github.com/dotnet/razor-tooling/security/dependabot/7
=> Bump lots of dependencies

eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/RazorHoverEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/GoToImplementationHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/CSharpTestLspServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/GoToImplementationHandlerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/HoverHandlerTest.cs
- Take the new version of VS.LS.Protocol. It includes some perf improvements and simplifications of classes like hover.
- Need to take the reaction from Roslyn too in order to get the build to work.
=> Protocol version bump

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/RazorLanguageServerCustomMessageTargets.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentHighlighting/DocumentHighlightEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/DocumentHighlightParamsBridge.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IDocumentHighlightEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentHighlighting/DocumentHighlightEndpointTest.cs
Fixes https://github.com/dotnet/razor-tooling/issues/6653
Through the power of reuse, this took maybe two hours to write (made slightly more complicated by the fact that we didn't have a Razor endpoint for it at all), and two hours to debug and work out the IProgress bit, but its a pretty good sign that this design is straight forward, so much like the Swedish flag, that's a big plus.
=> Do single server document highlighting

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/RazorLanguageServerCustomMessageTargets.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/SignatureHelpParamsBridge.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SignatureHelp/SignatureHelpEndpoint.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerCustomMessageTarget.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SignatureHelp/SignatureHelpEndpointTest.cs
=> Do single server signature help

src/Razor/src/rzls/rzls.csproj
Move from win-\* to win10-\*. Add linux-musl-\* RIDs.
=> Update Razor Language Server RIDs

eng/Versions.props
- We think this should solve some problems in our internal builds.
=> Update VS.BuildTools version

eng/Versions.props, src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks.csproj, src/Razor/src/rzls/rzls.csproj
=> Use system.private.uri

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/AdhocLanguageServices.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/AdhocServices.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/AdhocWorkspaceServices.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultProjectEngineFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultRemoteTextLoaderFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Extensions/JsonConverterCollectionExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Extensions/RazorCodeDocumentExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/HostDocumentComparer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/ProjectEngineFactories.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/ProjectEngineFactory_1_0.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/ProjectEngineFactory_1_1.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/ProjectEngineFactory_2_0.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/ProjectEngineFactory_2_1.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/ProjectEngineFactory_3_0.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/ProjectEngineFactory_Unsupported.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/Properties/AssemblyInfo.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/RemoteTextLoaderFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/UnsupportedCSharpLoweringPhase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/UnsupportedRazorConfiguration.cs
@ryanbrandenburg this was already changed from last week, I just hadn't committed and pushed, but if you want me to not merge it I'm fine with it :)
=> Null annotate MS.AspNetCore.Razor.LanguageServer.Common

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/package.json, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode.Extension/src/extension.ts
Finally started a feature branch since the code was starting to get messy - expect an influx of PRs in the next few days 😄
This PR accomplishes first step of allowing the Razor extension to actually launch.
=> [VSCode] Be able to launch VSCode extension

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs
=> Remove restriction for completion while inside an HTML start tag

.github/fabricbot.json
Updates FabricBot configuration for 17.4 P3.
Changes:
- Updates to correct milestone and project
- Removed Taylor and added Dustin+Arun
=> Update FabricBot for 17.4 P3

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
This ought to fix the failures from the newly added assembly.
=> Add MS.AspNetCore.Razor.Common to VSIX and MPack

eng/Versions.props
- This update should let us run Integration tests locally.
=> Update Integration tests

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs
=> Use `TestFileMarkupParser` and raw strings in `TagHelperCompletionProviderTest`

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/FormattingTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestRazorFormattingService.cs
Fixes https://github.com/dotnet/razor-tooling/issues/6411
This fix was surprising :D
=> Fix HTML tag formatting

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionProviderTest.cs
Fixes https://github.com/dotnet/razor-tooling/issues/5699
=> Don't offer completions for implicit expressions

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/DefaultRazorHoverInfoServiceTest.cs
Can't let @DoctorKrolic have all the fun 😁
=> Use test markup for hover tests

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormatter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorDocumentFormattingEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorDocumentOnTypeFormattingEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorDocumentRangeFormattingEndpoint.cs
- Move Formatting to CLaSP Framework
=> CLaSP: Formatting

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Implementation/ImplementationEndpoint.cs
- Move Implementation to use CLaSP Framework.
=> CLaSP: Implementation

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionResolutionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs
=> CLaSP: Move CodeActions to CLaSP

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentColor/DocumentColorEndpoint.cs
- Move DocumentColor to CLaSP Framework
=> CLaSP: Document Color

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionResolveEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionResolveEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IVSCompletionResolveEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IOnInitialized.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlineCompletion/InlineCompletionEndPoint.cs
=> CLaSP: Completion

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentHighlighting/DocumentHighlightEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IDocumentHighlightEndpoint.cs
- Move DocumentHighlights to CLaSP.
=> CLaSP: DocumentHighlight

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/FoldingRangeEndpoint.cs
- Move Folding to CLaSP Framework
=> CLaSP: Folding

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/ISignatureHelpEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SignatureHelp/SignatureHelpEndpoint.cs
- Move SignatureHelp to ClaSP Framework.
=> CLaSP: SignatureHelp

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IMonitorProjectConfigurationFilePathHandler.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MonitorProjectConfigurationFilePathEndpoint.cs
- Move MonitorProjectConfiguration to CLaSP Framework
=> CLaSP: monitor project configuration

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LinkedEditingRange/LinkedEditingRangeEndpoint.cs
- Move LinkedEditingRange to CLaSP Framework.
=> CLaSP: LinkedEditing

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
- Move renaming to CLaSP Framework.
=> CLaSP: Rename

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WrapWithTag/WrapWithTagEndpoint.cs
- Move WrapWithTag to CLaSP Framework
=> CLaSP: Wrap with tag

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Debugging/RazorBreakpointSpanEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Debugging/RazorProximityExpressionsEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/Debugging/IRazorProximityExpressionsEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IRazorBreakpointSpanEndpoint.cs
- Move breakpoint endpoints to CLaSP Framework.
=> CLaSP: Breakpoints

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IDefinitionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/ISignatureHelpEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/SignatureHelpParamsBridge.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SignatureHelp/SignatureHelpEndpoint.cs
- Move Definition and SignatureHelp to CLaSP Framework.
=> CLaSP: Definition and SignatureHelp

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AbstractRazorDelegatingEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorInitializedEndpoint.cs
- Move Diagnostics to CLaSP framework.
=> CLaSP: Diagnostics

NOTICE.txt, NuGet.config, eng/Signing.props, src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj, src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Properties/_Manifest.addin.xml, src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/mpack/addin.info
- Fix some signing and assembly load issues.
=> CLaSP: Signing

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorCSharpSemanticTokensInterceptor.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/WorkspaceConfigurationChangedListener.cs
- Move the VS Client on to CLaSP.
=> CLaSP: VS Client

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServerWrapper.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultWorkspaceSemanticTokensRefreshPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/DefaultRazorSemanticTokenInfoServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokenTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokensRefreshEndpointTest.cs
- Move Semantic Tokens tests to CLaSP
=> CLaSP: Semantic Tokens tests

azure-pipelines-richnav.yml, azure-pipelines.yml
- Move to the new build images.
Fixes: https://github.com/dotnet/razor-tooling/issues/6905
=> Update build images

azure-pipelines.yml
- Update ubuntu images to use more recent version.
Fixes: https://github.com/dotnet/razor-tooling/issues/6911
=> Update Ubuntu image

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/RazorDefinitionEndpointDelegationTest.cs
- In the CLaSP move I somehow accidentally deleted this file. Bringing it back here. Sorry @davidwengier!
=> Add back definition test

azure-pipelines.yml, eng/common/templates/job/execute-sdl.yml, eng/common/templates/job/onelocbuild.yml, eng/common/templates/jobs/jobs.yml, eng/common/templates/post-build/channels/generic-internal-channel.yml, eng/common/templates/post-build/channels/generic-public-channel.yml, eng/common/templates/post-build/darc-gather-drop.yml, eng/common/templates/post-build/post-build.yml, eng/common/templates/post-build/promote-build.yml, eng/common/templates/post-build/setup-maestro-vars.yml, src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs
- includes a fake Arcade update matching recent release/3.x changes
=> [release/3.1] Switch to consolidated Windows build images and Ubuntu 20.04

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Completion/RazorCompletionItemProvider.ts
- Cleans up some unnecessary code
- Fixes commit character issue #4371
- Eventually we probably want to add actual tests to verify we don't break this again in the future, however we don't test our providers in-depth today so this will probably have to be a follow-up work item (likely can be encompassed in https://github.com/dotnet/razor-tooling/issues/4593).
Fixes https://github.com/dotnet/razor-tooling/issues/4371
=> [VSCode] Fix C#/HTML completion commit issue + clean up

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/RazorDefinitionEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/RazorDefinitionEndpointTest.cs
Fixes: https://github.com/dotnet/razor-tooling/issues/6775
The simplest fix I've ever made - just a method name change 🙂
=> Go to def on edge

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/RazorDefinitionEndpointDelegationTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/RazorDefinitionEndpointTest.cs
- Extracted common logic into helper methods
- Used fancy raw strings
- Used test markup
=> Improve "Go to definition" tests

eng/Versions.props, global.json, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsEndpointTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/MarkupTransitionCompletionItemProviderTest.cs
Fixes https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-razor-tooling/alert/2967366?typeId=6437627
Only took me a week to find the magic numbers to use 🤦‍♂️
=> Fix CG alert coming from compiler test projects

docs/ProjectsAndLayering.md
This is not incredibly detailed, but I wanted to try and at least tease out which projects make up the various layers for Razor.
=> Add document that lists various projects and layers along with TFMs

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/RazorCodeActionsTests.cs
- Noticed this was disabled. Turned it on and it worked... 👻.
=> Enable CodeAction test

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectWorkspaceStateGenerator.cs
Another attempt at fixing https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1601533 after https://github.com/dotnet/razor-tooling/pull/6777 apparently didn't work.
Exception stack looks like this:
First highlighted row is our method, of course. Second highlighted row, I have it on good authority, means something is trying to take a `lock` on a null reference. From looking at [the source](https://referencesource.microsoft.com/#q=SemaphoreSlim) of SemaphoreSlim, I could see this happening if we disposed while inside its `Release` method, so release in our dispose should prevent that.
Any alternate suggestions are more than welcome :D
Also I went looking to see how Roslyn deals with disposing SemaphoreSlim's, and apparently it doesn't 😂
=> Belt and braces around our semaphore disposal

eng/Versions.props
Fixes https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-razor-tooling/alert/7406915?typeId=6437374
=> Bump Microsoft.Build.Framework

azure-pipelines.yml
No idea if this will work, but it probably can't hurt
=> Try to maybe fix OneLoc

azure-pipelines-integration-dartlab.yml
=> Fix Integration tests

src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/RazorDynamicDocumentInfoProvider.cs
Fixes https://github.com/dotnet/razor-tooling/issues/6725 and is the Razor part of fiing https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1643651
Requires https://github.com/dotnet/roslyn/pull/64884 so not expecting this to build, yet.
=> Update document services, not just text loader

docs/contributing/BuildFromSource.md
=> Add missing `.\` to startvs.cmd in docs

src/Compiler/Directory.Build.props, src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport.csproj, src/Compiler/tools/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal.csproj, src/Compiler/tools/Microsoft.AspNetCore.Razor.SourceGenerator.Tooling.Internal/Microsoft.AspNetCore.Razor.SourceGenerator.Tooling.Internal.csproj, src/Compiler/tools/Microsoft.AspNetCore.Razor.Symbols.Transport/Microsoft.AspNetCore.Razor.Symbols.Transport.csproj
Ensure we don't ship transitive analyzers, and all transport packages are packed.
=> Fix transport dependencies

azure-pipelines.yml, eng/Versions.props, eng/config/PublishData.json, eng/pipelines/insert.yml
- Automates Razor insertions on official CI builds via the Roslyn insertion tool.
- Successful test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2049414&view=logs&s=d00c89cd-5e0a-588d-122b-bf62b983d932
- Generated test insertion: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/437069
Fixes:
https://github.com/dotnet/razor/issues/7874
=> [Infra] Automate Razor insertions

src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/DefaultMacRazorProjectHost.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/ProjectSystem/MacRazorProjectHostBase.cs, src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/ProjectSystem/DefaultMacRazorProjectHostTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1544050 and maybe even https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1315748/ if I get lucky?
=> Fix Blazor Maui projects on VS Mac

src/Razor/src/Microsoft.VisualStudio.Mac.RazorAddin/Microsoft.VisualStudio.Mac.RazorAddin.csproj
=> Fix PDB paths

src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/src/RazorExtensionsDiagnosticFactory.cs, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/src/RazorPageDocumentClassifierPass.cs, src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentDeclarationIntegrationTest.cs, src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/CSharpCodeParserTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultRazorIndentationFactsServiceTest.cs
- This isn't related to anything other than that analyzer warnings annoy me.
=> Unused variables

.editorconfig, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/TypeAccessibilityCodeActionProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorTranslateDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/SourceTextExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingPass.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDiagnosticsPublisher.cs, src/Razor/src/Microsoft.AspNetCore.Razor.OmniSharpPlugin.StrongNamed/OmniSharpWorkspaceProjectStateChangeDetector.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/MarkupTransitionCompletionItemProvider.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorTextViewConnectionListener.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/CompletionHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/RazorHtmlCSharpLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioRazorParserIntegrationTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultWorkspaceEditorSettingsTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/MessageInterception/InterceptionMiddleLayerTest.cs
Fixes nothing, but I'm in a mood.
=> Clean up experimental formatting rules, and fix warnings

eng/Version.Details.xml, eng/Versions.props
Updates the razor compiler dependencies to include the final fixes that were missed for 17.4
=> Update razor-compiler version

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Common/DefaultLanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorPullDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlCSharp/InitializeHandler.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs
Cherry-pick of #7986 into 17.5 P2.
=> [Cherry-pick into 17.5 P2] Have a separate feature flag for single server diagnostics, that defaults to off

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
=> Inline temporary variables

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/FindAllReferencesTests.cs
Failed in https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7110578 and https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7110352 and https://dev.azure.com/dnceng/internal/_build/results?buildId=2069323
Will be unskipped in #8036
=> Skipping flaky tests

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DiagnosticTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/GoToDefinitionTests.cs
Trying to get integration tests green again
=> Skip another test

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/FindAllReferencesTests.cs
Unskip one of the tests in #8036 by making sure we order the results
=> Unskip FindAllReferences_ComponentAttribute_FromRazor

.github/fabricbot.json
As per Teams convo, I felt 7 days was a little aggressive.
@allisonchou let me know if I missed anything, I'm just guessing here :)
=> Don't close NMI issues until 14 days has passed

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
Follow up from https://github.com/dotnet/razor/pull/8075 after hearing more info, and having a little less panic in my life.
=> Fix comment based on better understanding

azure-pipelines.yml
- Merging this into the `release/17.4` branch as a follow up from https://github.com/dotnet/razor/pull/8100 since I incorrectly handled some parts of the merge conflict resolution after cherry-picking.
=> Fix `release/17.4` VS insertion step

azure-pipelines.yml
=> Use publishData from 17.4.x

src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.cs.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.de.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.es.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.fr.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.it.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.ja.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.ko.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.pl.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.pt-BR.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.ru.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.tr.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.zh-Hans.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Resources/xlf/SR.zh-Hant.xlf
Cherrypick this change https://github.com/dotnet/razor/pull/6835 to 17.4.x branch
Depends on QB if this could also be checked in
=> Cherrypick the LOC changes

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/JavaScript.tmLanguage.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/css.tmLanguage.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/html.tmLanguage.json, src/Razor/src/Microsoft.VisualStudio.RazorExtension/cgmanifest.json, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/embeddedGrammars/JavaScript.tmLanguage.json, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/embeddedGrammars/css.tmLanguage.json, src/Razor/test/Microsoft.AspNetCore.Razor.VSCode.Grammar.Test/embeddedGrammars/html.tmLanguage.json
Trying to see if this fixed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1619464 but I don't think it does, but may as well commit it.
Purely mechanical, I just ran `eng/scripts/UpdateTextMate.ps` (which I might make a weekly GitHub Actions job for?)
=> Update grammar files

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/WorkspacePullDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/IWorkspacePullDiagnosticsEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
Fixes #8143
Confirmed in the debugger that we get these requests.
=> Handle workspace diagnostics messages

azure-pipelines.yml, eng/AfterSigning.targets, eng/Publishing.props, src/Razor/src/Microsoft.AspNetCore.Razor.Common/Microsoft.AspNetCore.Razor.Common.csproj, src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/Microsoft.AspNetCore.Razor.VSCode.npmproj, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Microsoft.VisualStudio.Editor.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/Microsoft.VisualStudio.Mac.LanguageServices.Razor.csproj
- Fixes darc failures. As a result of now officially building Linux/Mac, we started publishing duplicates of certain assets. This PR restricts publishing of those assets to Windows only and makes it so that the only asset Linux/Mac publishes is the Razor language server.
=> [VS Code] Fix darc failures

.github/workflow/update-textmate.yml
No idea if this works, not sure if I can test it before merging :)
=> Create a GitHub Actions script to update TextMate weekly

src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.tmTheme
Fixes #8182
Copied entirely from the Web Tools javascript tmTheme :)
Proof:
=> Update JavaScript classification

azure-pipelines.yml
Sample run
https://dev.azure.com/dnceng/internal/_build/results?buildId=2101361&view=results
=> Switch to scout queue

src/Razor/src/rzls/rzls.csproj
- Publishes platform agnostic language server for OSes we don't explicitly support.
cc @dibarbet
=> Publish platform agnostic language server

eng/config/PublishData.json
=> Change the target branch

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/CSharpCodeActionEndToEndTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.cs
Did this to make #8204 easier, thought I may as well commit now.
=> Create end-to-end test for C# code actions

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Resources/FormattingTest.razor, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Resources/FormattingTest_Expected.razor, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/TestResources.cs
This is a follow-up test for #8215
=> Add large file formatting test to validate `TextDiffer.IntArray` fix

eng/Versions.props, src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension.Dependencies/AssemblyCodeBases.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension.Dependencies/Microsoft.VisualStudio.RazorExtension.Dependencies.csproj
Whats the worst that could happen? 😁
=> Bump Roslyn to latest in VS main

eng/Versions.props
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1747142
FYI @matteo-prosperi
=> Update LSP protocol DLL version

eng/SetupVSHive.ps1
I want this yesterday, so next best thing is to get it tomorrow.
=> Output VS info for integration test runs

src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/IntegrationTests/CodeGenerationIntegrationTest.cs, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ModelExpressionTagHelper_Runtime.ir.txt, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithoutModel_Runtime.ir.txt, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPages_Runtime.ir.txt, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Sections_Runtime.ir.txt, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ViewComponentTagHelper_Runtime.ir.txt, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/IntegrationTests/CodeGenerationIntegrationTest.cs, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ModelExpressionTagHelper_Runtime.codegen.cs, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ModelExpressionTagHelper_Runtime.ir.txt, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithoutModel_Runtime.codegen.cs, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPagesWithoutModel_Runtime.ir.txt, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPages_Runtime.codegen.cs, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/RazorPages_Runtime.ir.txt, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Sections_Runtime.codegen.cs, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/Sections_Runtime.ir.txt, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ViewComponentTagHelper_Runtime.codegen.cs, src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/ViewComponentTagHelper_Runtime.ir.txt
Noticed some disabled tests which seem to work fine. So, I enabled them and updated their baselines.
=> Re-enable some legacy extension tests

azure-pipelines.yml
=> Disable integration tests in 17.6

azure-pipelines.yml
=> Fix yaml syntax error

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
Fixes another VS Mac thing that I completely stuffed up.
=> Remove the silly thing

eng/config/PublishData.json
Insert release/dev17.6 branch to VS rel/d17.6 since we have inserted our stuff to main and VS is snapping on their side today.
=> Insert release/dev17.6 to VS rel/d17.6

src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.csproj
- We're publishing duplicate blobs, which is breaking darc. We should only be publishing blobs on Windows.
=> Fix darc publishing issues

Directory.Build.props
=> Disable targeting Windows for source-build (#8376)

azure-pipelines-richnav.yml, azure-pipelines.yml
No idea what I'm doing as ever, but outlook gave me a reminder about an email from Matt Galbraith and it doesn't seem like anyone did anything about it, so you get me instead :)
=> Use automatic pool selection controlled by arcade

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Options/OptionsStorage.cs
=> Add event for when an option is changed

eng/config/PublishData.json
- Makes it so required checks run by default and will speed up the insertion process
=> [Infra] Take insertion PRs to main out of draft mode

docs/contributing/Roslyn-Debugging.md
Updating the troubleshooting guide in the docs
=> Updating the troubleshooting guide in the docs

azure-pipelines.yml, eng/Versions.props
- Updates Roslyn to 4.6.0-3.23164.6
- Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1747142/?triage=true
=> Update Roslyn to 4.6.0-3.23164.6

eng/Versions.props
@phil-allen-msft spotted that this wasn't updated
=> Bump version to 17.6

azure-pipelines.yml
Fixes https://github.com/dotnet/razor/issues/8457
=> Re-enable integration tests

eng/config/PublishData.json
=> Snap 17.6 P3

azure-pipelines.yml
Build artifacts were supplanted by pipeline artifacts quite some time ago. Moving to pipeline artifacts
=> Use pipeline artifacts

src/Razor/src/rzls/Program.cs
Just a little quality of life improvement for local debugging of rzls
=> RZLS local debug tweaks

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ConfigurableLanguageServerFeatureOptions.cs, src/Razor/src/rzls/Program.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ConfigurableLanguageServerFeatureOptionsTest.cs
This should allow us to do some very fancy integration tests in the long term, and makes my life a little easier in the short term :)
=> Allow configuring the language server via the command line

eng/config/PublishData.json
=> Update PublishData.json after M2

docs/ProjectsAndLayering.md, docs/overview.svg
=> Update layering doc

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsPublisher.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsPublisherTest.cs
Part of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1782912/
- Publishes/tracks csharp diagnostics alongside razor diagnostics 
- Update/add tests to RazorDiagnosticsPublisherTests
=> Publish CSharp Diagnostics

eng/config/PublishData.json
- Thanks @adamint for the catch!
=> Fix 17.6 branching

src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Microsoft.AspNetCore.Razor.ProjectEngineHost.csproj, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/SR.resx, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.cs.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.de.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.es.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.fr.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.it.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.ja.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.ko.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.pl.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.pt-BR.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.ru.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.tr.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.zh-Hans.xlf, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Resources/xlf/SR.zh-Hant.xlf
This PR just adds an empty resx file to the new `ProjectEngineHost` project in a similar fashion as other tooling projects.
=> Add resx for string resources to MS.ANC.Razor.ProjectEngineHost

eng/Versions.props
Match up with what will be built in source-build.
Includes https://github.com/dotnet/cssparser/compare/d6d86bcd8c162b1ae22ef00955ff748d028dd0ee...0d59611784841735a7778a67aa6e9d8d000c861f
=> Update CSS parser version

eng/Versions.props, eng/config/PublishData.json
=> Update configs for snap

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/SyntaxNodeExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/RazorCodeBlockFoldingProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/RazorFileUsingsFoldingSyntaxWalker.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingPass.cs
Removes a redundant partial keyword & converts IsUsingDirective to extension function
=> Small folding cleanup

src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
Backport of https://github.com/dotnet/razor/pull/8682 to 17.6
=> Include the missing deps as analyzer references

NOTICE.txt, eng/Versions.props, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
Updates OmniSharp package version and makes explicit reference to the desired System.Reactive version.
Once more validation is complete will merge this PR.
=> Updates OmniSharp package version

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1822441
There is more that could/should be done here, but I think the dispatcher thread is already on Dustin's hit list, so I did the bare minimum :)
=> Fix threading in Rename

azure-pipelines.yml, eng/Version.Details.xml, eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/RazorSemanticTokensLegend.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Microsoft.AspNetCore.Razor.LanguageServer.Test.csproj, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Mef/ExportProviderCache.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlCSharp/TestLanguageServiceBroker.cs
- Using Darc Tool and also getting inspiration from PR https://github.com/dotnet/razor/pull/8670 to update the roslyn bits and other packages that we use.
Fixes https://github.com/dotnet/razor/issues/8652
/cc @jjonescz
=> Update Roslyn bits

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/RazorSemanticTokensLegend.cs
Fixes a brief lack of programming knowledge.
=> Goofed because I'm a goofball

eng/Versions.props
Hopefully fixes CG warnings on our official build
=> Bump analyzer testing

src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Assumed.cs, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/SR.resx, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.cs.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.de.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.es.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.fr.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.it.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.ja.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.ko.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.pl.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.pt-BR.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.ru.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.tr.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.zh-Hans.xlf, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.zh-Hant.xlf
Noticed a spelling mistake with the Assumed helpers. Fixed that up.
=> Fix spelling mistake

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/8827
=> Format typeparam directive

src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Completion/RazorCompletionItemProvider.ts
=> Cherry Pick #8913

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/EndpointContracts/RazorRequestContext.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorRequestContextFactory.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/TelemetryReporter.cs
=> Add some useful info at debug time

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
Wait after initializing our language server, and make a couple of text edits, then wait a bit more, to give all of our external dependencies a chance to spin up properly, and get data flowing around the system.
=> Thinking outside the box!

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/GenerateMethodCodeActionResolver.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.cs
cherry pick https://github.com/dotnet/razor/pull/9030 to 17.8 branch
=> Port #9030 to release/dev17.8

src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/IncrementalValueProviderExtensions.cs, src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs
Fixes https://github.com/dotnet/razor/issues/8999
=> Remove unused hashCode from lambda comparer

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultRazorLanguageServerCustomMessageTarget.cs
Noticed this today in the output window logging. When we introduced the changes to modify POCOs in place, we missed a couple of places where we process requests in parallel, hence race condition.
I'm not 100% sure if this regressed when we added the `WithUri` calls, or with my changes to document synchronization in the most recent PR (its doc sync that fails). Given that our folding range integration tests didn't fail, I don't think this has any much user impact.
=> Fix race where we're modifying a TextDocumentIdentifier before we use it

src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml.cs
Figured I may as well do this now that the APIs are available.
=> Support opening multiple virtual documents in the Syntax Visualizer

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Components/ComponentMarkupEncodingPass.cs, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorComponentTests.cs, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/Doctype_CSharp/Views_Home_Index.html, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/Doctype_CSharp_View/Views_Home_Index.html, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/Doctype_HtmlComment/Views_Home_Index.html, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/Doctype_HtmlComment_View/Views_Home_Index.html, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/Doctype_Newline/Views_Home_Index.html, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/Doctype_Newline_View/Views_Home_Index.html, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/Doctype_NoNewline/Views_Home_Index.html, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/Doctype_NoNewline_View/Views_Home_Index.html, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/Doctype_RazorComment/Views_Home_Index.html, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/Doctype_RazorComment_View/Views_Home_Index.html
Fixes https://github.com/dotnet/razor/issues/8545.
=> Fix angle bracket encoding in Razor components

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/RazorSemanticTokensLegend.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/RazorSemanticTokensInfoService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/RazorSemanticTokensLegendTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/RazorSemanticTokensRefreshEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestRazorSemanticTokensLegend.cs
Fixes https://github.com/dotnet/razor/issues/8889
Was waiting for the Roslyn bump.
=> Stop hard coding Roslyn token modifiers, and add test

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs
Fixes https://github.com/dotnet/razor/issues/9160
=> Fix completion in self closing tags inside C#

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/8606
=> Fix formatting of `@bind` attributes

eng/config/PublishData.json
=> Update configs for razor snap

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/ProjectSystem/ProjectSnapshotManagerBenchmarkBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultProjectSnapshotManagerAccessor.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManagerFactory.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test.Common/TestProjectSnapshotManager.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeDocumentReferenceHolderTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Common/BackgroundDocumentGeneratorTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentVersionCacheTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedDocumentPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorProjectServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultWorkspaceSemanticTokensRefreshTriggerTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsPublisherTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/OpenDocumentGeneratorTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SnapshotResolverTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Shared/TestProjectSnapshotManager.cs, src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/OOPTagHelperResolverTest.TestProjectSnapshotManager.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultProjectWorkspaceStateGeneratorTest.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioDocumentTrackerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentFactoryTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/ProjectRazorJsonPublisherTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultProjectSnapshotManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorDynamicFileInfoProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultWindowsRazorProjectHostTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackWindowsRazorProjectHostTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/VsSolutionUpdatesProjectSnapshotChangeTriggerTest.cs, src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/ProjectSnapshotSynchronizationServiceTest.cs, src/Razor/test/Microsoft.VisualStudio.Mac.LanguageServices.Razor.Test/ProjectSystem/RazorDocumentInfoProviderTest.cs
=> Cherry-Pick 9165

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentHighlighting/DocumentHighlightEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/RazorCodeDocumentExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DocumentHighlightTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess.cs
Fixes https://github.com/dotnet/razor/issues/9212
=> Don't assume the response was C#

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticConverter.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticConverterTest.cs
Fixes https://github.com/dotnet/razor/issues/9213
=> Fix off-by-one error in Razor diagnostics

eng/config/PublishData.json
=> Update configs after vs 17.8 p2 snap

src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteTagHelperDeltaProvider.cs
I noticed this method in a completion performance trace I was looking at and saw Dustin made an O(n^2) => O(n) improvement in this code that likely addressed the performance issue I was seeing (PR: https://github.com/dotnet/razor/pull/9086). However, while admiring his awesome fix, I did notice that it could be slightly optimized and get close to a 50% reduction in most cases by observing the fact that we most likely don't need to call TagHelperData.Compute twice.
Benchmark results look promising:
```
|                                        Method |        Job |            Toolchain | ReduceComputeCalls |         Mean |       Error |      StdDev |       Median |          Min |         Max | Allocated |
|---------------------------------------------- |----------- |--------------------- …
```
=> Further perf improvement to GetTagHelpersDelta

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WrapWithTag/WrapWithTagEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/WrapWithTag/WrapWithTagEndpointTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/WrapWithTagTests.cs
Fixes https://github.com/dotnet/razor/issues/9209
=> Wrap implicit expressions, even though they're C# code

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultRazorDynamicFileInfoProvider.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1878509
=> Allow project key to not be found, in case the project isn't C#

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/HoverInfoService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/HoverInfoServiceTest.cs
Fixes https://github.com/dotnet/razor/issues/9136
=> Correctly find parents in hover

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
Creating the PR so once we make a decision we'd go ahead with this change
cc: @phil-allen-msft @ToddGrun @davidwengier
=> Disable feature flag by default for precise ranges

eng/Versions.props
Starts producing packages with version 8 instead of 7.
=> Bump version to 8

eng/Versions.props
=> Revert "Bump version to 8"

eng/Version.Details.xml, eng/Versions.props
Link to last update: https://github.com/dotnet/razor/pull/9110
=> Update Roslyn to 4.8.0-2.23469.5

eng/Versions.props
I think this is forgotten in main.
Right now we can directly change this in release/dev17.8
=> Update vsix version to 17.8 p3

eng/config/PublishData.json
I don't know how but my brain desynced from my fingers in #9347
=> Fix VS branch name

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentSymbol/DocumentSymbolEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectContexts/ProjectContextsEndpoint.cs
=> Enable navbar

src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/FilePathNormalizer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/FilePathNormalizerTest.cs
This fixes a problem introduce late into the file path normalization pull request.
=> Fix pattern matching to avoid IndexOutOfRangeException

azure-pipelines-conditional-integration.yml
=> Update azure-pipelines-conditional-integration.yml for Azure Pipelines

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/FindAllReferencesTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/GoToDefinitionTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/OnTypeFormattingTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/ProjectTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/RenameTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/SynchronizationTests.cs
This will allow them to be run in the [integration ci](https://dev.azure.com/dnceng-public/public/_build?definitionId=269&_a=summary) that runs flakey tests
=> Change ide facts to be conditional skip

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/BaseDelegatedCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/UnformattedRemappingCSharpCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Html/DefaultHtmlCodeActionResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/CodeActionExtensions.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/CodeActionResolveParams.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/RazorResolveCodeActionParams.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/CodeActions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionResolverTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionResolutionEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Html/DefaultHtmlCodeActionResolverTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorCustomMessageTargetTest.cs
Fixes checkbox in https://github.com/dotnet/razor/issues/8983 and TODO comment in code
=> Make sure we carry ProjectContext through to code action resolve

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentContextFactory.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentContextFactoryTest.cs
Noticed this in PRISM, and works towards one of the goals of https://github.com/dotnet/razor/issues/8983 of removing the link between project file path and document file paths.
=> Don't bother looking up every project if we know where it comes from

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/Completion.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs
=> Do not add snippets on deletion as reason for completion

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultRazorDynamicFileInfoProvider.cs
Doing this in preparation for https://github.com/dotnet/razor/issues/9459
Follow up to https://github.com/dotnet/razor/pull/9245 and https://github.com/dotnet/roslyn/pull/69828 now that the right Roslyn version has flowed through to us
=> Nullable enable our dynamic file info provider

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/9484
=> Fix formatting when implicit expression is present

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/SpellCheck/DocumentSpellCheckEndpoint.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SpellCheck/DocumentSpellCheckEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/9485
=> Don't spell check any attributes

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotManagerBase.cs
=> Remove unused methods

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Telemetry/TelemetryReporter.cs
While looking at #9502, I noticed that I introduced a significant telemetry bug in #9465. Fixing that issue.
=> Fix type check in IsComplexValue

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentContextFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/OpenDocumentGenerator.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/SnapshotResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackHostProject.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackProjectManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/UpdateProjectAction.cs, src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/OOPTagHelperResolverTest.cs
This is a grab bag bunch of changes from things I found investigating https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1908306 using the patented method of deleting the `obj` folder and restarting VS over and over again.
Will comment on the couple of interesting points.
=> Various cold start fixes

src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Serialization/CompletionListSerializationBenchmark.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionListProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RazorSyntaxNodeExtensions.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSource.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveCompletionSource.cs
Move all completion scenarios over to FindToken.
=> Remove LocateOwner from completion scenarios

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentContextFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/OpenDocumentGenerator.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/SnapshotResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackHostProject.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackProjectManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotManager.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/UpdateProjectAction.cs, src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/OOPTagHelperResolverTest.cs
Port of https://github.com/dotnet/razor/pull/9509 for inclusion in M2 mode
FYI @phil-allen-msft
=> Port cold start fixes to 17.9 P1

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Telemetry/TelemetryReporter.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Shared/TestTelemetryReporter.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TelemetryReporterTests.cs
Add some testing to our telemetry logic to help avoid regressions.
=> Add telemetry tests

src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/TelemetryScope.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Telemetry/TelemetryReporter.cs
- Pulls in #9545 and #9507 for release/dev17.9
Fixes:
=> Cherry-pick in telemetry changes for 17.9

azure-pipelines-integration-dartlab.yml
Same as https://github.com/dotnet/roslyn/pull/70867
Use dnceng side connection
=> Use dnceng end point to run darc lab test

src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/ChecksumTests.cs, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Utilities/Checksum.Builder.cs
Cherry-picks #9575 into release/dev17.9
=> Cherrypick "Fix issue with Checksum and long strings" to 17.9

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorProjectInfoPublisher.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorProjectInfoPublisherTest.cs
Cherry-pick of just the fix from https://github.com/dotnet/razor/pull/9614 to hopefully make it into 17.9 P2 in M2 mode
FYI @phil-allen-msft
=> Publish on document change if the config file doesn't exist

eng/config/PublishData.json
=> Update publishdata for 17.9 P2

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/SyntaxListBuilder.cs
Fixes https://github.com/dotnet/razor/issues/9718
=> Change Count when resizing the array

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/GenerateMethodCodeActionProvider.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.NetFx.cs
Fixes https://github.com/dotnet/razor/issues/9729
=> Don't offer to generate a method for a directive attribute that isn't an event callback

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/OpenDocumentGenerator.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultRazorDynamicFileInfoProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundDocumentGenerator.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/EditorDocumentManagerListener.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Documents/EditorDocumentManagerListenerTest.cs
Fixes https://github.com/dotnet/razor/issues/9185
=> Make project removal more efficient

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedTypes.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionListProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorSyntaxFacts.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/Completion.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.NetFx.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TestDocumentMappingService.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs
=> Do not offer snippets when typing inside a start or end tag

eng/Versions.props, src/Compiler/Microsoft.AspNetCore.Razor.Language/test/CodeGeneration/DesignTimeNodeWriterTest.cs, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTestsBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorProjectServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DirectoryHelperTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MonitorProjectConfigurationFilePathEndpointTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDocumentMappingServiceTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorLanguageServerTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Microsoft.AspNetCore.Razor.Test.Common.Tooling.csproj, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultProjectPathProviderTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/MessageInterception/DefaultInterceptionManagerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.Test/MessageInterception/InterceptionMiddleLayerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorContentTypeChangeListenerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/RazorProjectInfoPublisherTest.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CodeFoldingTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Classification.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/SolutionExplorerInProcess.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Microsoft.VisualStudio.Razor.IntegrationTests.csproj, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Semantic/RazorSemanticTokensTests.cs, src/Razor/test/OSSkipConditionFactAttribute.cs, src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/CompilationFailedException.cs, src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs, src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Microsoft.AspNetCore.Razor.Test.Common.csproj
Did this to try to resolve an issue with another PR, thought I may as well put it up.
=> Update Xunit and unify versioning a bit

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/RazorSemanticTokensInfoService.cs
Merged the PR from the couch thinking I'd actioned this feedback. Turned out I'd made the changes on my other machine but hadn't committed 🤦‍♂️
=> Missed PR feedback from Semantic Tokens PR

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Completion.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/RazorProjectSystemInProcess.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/NonRazorSdkTests.cs
Fixes https://github.com/dotnet/razor/issues/9665
Test run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8855843&view=results
=> Integration test for non-Razor SDK usage

eng/config/PublishData.json
I'm an idiot and forgot to snap Razor as well yesterday. 
-
Fixes:
=> Update configs for 17.10 snap

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MapCode/MapCodeEndpoint.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MapCode/Protocol/MapperMethods.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MapCode/Protocol/VSInternalMapCodeMapping.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MapCode/Protocol/VSInternalMapCodeParams.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/MapCode.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MapCode/MapCodeTest.cs
Razor equivalent of https://github.com/dotnet/roslyn/pull/71415 
cc @genlu @zkat
=> Update to latest mapcode contract

eng/config/PublishData.json
=> Update PublishData.json after VS 17.10 snap

eng/restore-internal-tools.yml
See https://github.com/dotnet/arcade/pull/14314
=> Move to non-deprecated NuGetAuthenticate@1 task

azure-pipelines.yml, src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/Serialization/SerializerValidationTest.cs
Skip tests failing for features/fuse
=> Skip tests that fail for features/fuse

eng/Versions.props
Looks like 17.10 P1 branch is not updated.
=> Update version for P1

src/Compiler/Microsoft.AspNetCore.Razor.Language/src/CodeGeneration/CodeWriterExtensions.cs, src/Compiler/Microsoft.AspNetCore.Razor.Language/test/CodeGeneration/DesignTimeNodeWriterTest.cs
* Ensure we include the line count and end char index in remapped spans
* Make the source span in tests have non-default values to ensure they get mapped too
=> Port #9863 to main

eng/config/PublishData.json
Will merge this by end of the day
=> Prepare 17.10 snap

src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostInlayHintResolveEndpoint.cs
=> Fix MEF error

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/HoverService.cs
Fixes latest batch of integration test MEF failures. Caused by two PRs merging at the same time.
=> Fix hover service export

src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/Legacy/TagHelperParseTreeRewriterTest.cs
To match changes already made: https://github.com/dotnet/razor/pull/9933#discussion_r1489279120.
=> Simplify test code

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/ClientSettingsManager.cs, src/Razor/src/Microsoft.VisualStudio.Editor.Razor/IClientSettingsManager.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Options/OptionsStorage.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Snippets/SnippetService.cs, src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/ClientSettingsManagerTest.cs
=> Async hook up change in options (#9809)

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/MEFComponentTests.cs
This fixes the integration tests
=> Move MEF error detection to a test, and add some known current exceptions

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs
Second attempt at fixing https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1923333
Seems the 5-try-with-delay thing didn't work, so lets just go ahead and set ourselves up for success. We're getting the path from MSBuild/CPS etc. so we're unlikely to fill up the users hard drive with random empty folders - or at least if we are, so is everyone else :)
=> Create the path, instead of waiting for it to be created

featurflag.ps1
Did you know if you make an error in powershell it won't run? It's also a good way to add more contribution commits
=> Fix error in powershell

azure-pipelines-compliance.yml, azure-pipelines-conditional-integration.yml, azure-pipelines-integration-dartlab.yml, azure-pipelines-richnav.yml, azure-pipelines.yml
Like https://github.com/dotnet/roslyn/pull/72302.
=> Disable CodeQL in unofficial builds

eng/Versions.props
Like https://github.com/dotnet/razor/pull/10003 but better. I forgot to change the target branch previously🤦 Not sure why GitHub still displayed the diff though since the change was already in main...
=> [17.9] Bump roslyn-sdk

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/MEFComponentTests.cs
Fixes https://github.com/dotnet/razor/issues/9971 een though @phil-allen-msft really fixed the issue
=> Remove LiveShare from allow list

src/Razor/src/rzls/rzls.csproj
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1986633/?view=edit
See https://learn.microsoft.com/en-us/dotnet/core/versions/selection#values for definition of roll forward values
=> Enable roll forward on latest major version

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/HoverService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlayHints/InlayHintService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentMapping/AbstractRazorDocumentMappingService.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/MEFComponentTests.cs
Told you I'd break MEF 😛
The failures are just fallout from all of the cohosting moves and removals, they don't impact users.
=> Fix MEF integration test failures

eng/BannedSymbols.MEFv1.txt, eng/BannedSymbols.MEFv2.txt, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj
Fixes https://github.com/dotnet/razor/pull/10098#discussion_r1525203503
=> Ban the appropriate MEF in the approprate project

azure-pipelines-official.yml, azure-pipelines.yml
=> Update EOL versions

src/Razor/src/Microsoft.VisualStudio.RazorExtension/UnifiedSettings/razor.registration.json
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1995012
From reading the docs on a few things, it seems the use of the attribute is still in flux, and the team will notify partners when we should migrate, so going to leave that for now.
=> Fix typo in settings

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/MemoryLoggerProvider.Buffer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/MemoryLoggerProvider.Logger.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/MemoryLoggerProvider.cs
In memory logger will be viewable in dumps and log all levels. This will help with diagnosing feedback issues
=> Add an in memory logger

src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DynamicFiles/BackgroundDocumentGenerator.cs
There is a fair amount of lock contention in `BackgroundDocumentGenerator` that contributes to a hang on 17.10p2. The issue is caused by my recent changes to `FallbackProjectManager` to perform `IProjectSnapshotManager` updates on the dispatcher. While this change improves correctness it changes the interaction with Roslyn's dynamic file info implementation enough that it is causing problems.
The particular issue that this should address deadlocks due to `BackgroundDocumentGenerator._suppressedDocuments`.
1. `BackgroundDocumentGenerator.Suppressed(...)`: This adds or removes a file path from `_suppressedDocuments`. However, it also holds the lock while calling into `RazorDynamicFileInfoProvider.SuppressDocument(...)`.
https://github.com/dotnet/razor/blob/0294056d5b40faada727e267ec6e44150d1 …
=> Remove lock in BackgroundDocumentGenerator

eng/Versions.props, eng/config/PublishData.json
=> Update config for 17.10 P3 snap

eng/pipelines/insert.yml
Update path to OneOffInsertion.ps1
=> Infra: Update path to OneOfInsertion.ps1

eng/config/PublishData.json
=> Update publishdata after vs snap

eng/targets/GenerateServiceHubConfigurationFiles.targets, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Directory.Build.targets
Removes .NET Framework service hub descriptors etc.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1999684
=> Publish only .NET service files

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeDocumentReferenceHolderTest.cs
Tests within `CodeDocumentReferenceHolderTest` tend to fail on Linux intermittently. I suspect that the flakiness is due to the reliance on GC behavior. This change tightens that up a bit to see we can reduce the flakiness.
=> Clean up and improve CodeDocumentReferenceHolderTest

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs
Fixes #10238
Bad things can happen if a project is added while a document is opened, so we shouldn't allow it. Likewise, other RazorProjectService operations shouldn't run at the same time. This is achieved with an `AsyncSemaphore`, which is not re-entrant. So, it's important that the RazorProjectService operations do not rely on other RazorProjectService operations directly.
=> Ensure that RazorProjectService operations happen serially

azure-pipelines-official.yml, azure-pipelines.yml
- Removes `if`s that are always true or false in public/internal pipelines.
- Follow up on https://github.com/dotnet/razor/pull/10038.
- Full main CI run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=635947&view=results
- Official CI run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2425936&view=results
=> Simplify pipelines

azure-pipelines-official.yml
Official build run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2431316&view=results
=> Replace deprecated CI images

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/RazorCohostDynamicRegistrationService.cs
Fix (or at least reduce) the regression in https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/544293?discussionId=6353934
Alternative for https://github.com/dotnet/razor/pull/10266
Val build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2433044&view=results
Test insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/544800
=> Fix RPS image load regression

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/AbstractSyntaxNodeFoldingProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/RazorCodeBlockFoldingProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/SectionDirectiveFoldingProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RazorSyntaxTreeExtensions.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Folding/FoldingEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/10261
=> Create folding ranges for `@section` blocks

Directory.Packages.props, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/DefaultLSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/LSPRequestInvoker.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/MessageInterception/InterceptionMiddleLayer.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/DefaultRazorLanguageClientMiddleLayer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/DefaultLSPRequestInvokerTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/TestLSPRequestInvoker.cs
Switch to the new APIs; this is the first part of longer term changes to switch to System.Text.Json
=> Switch to the new LSP protocol APIs

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentContextFactory.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/SnapshotResolver.cs
Fixing random bad log messages I saw today while scouring logs
=> Fix log messages

eng/pipelines/test-integration-job.yml
This brings in the hang detection from our PR integration tests, to dart lab, and makes the test logs etc. always upload, which at least gets us something to start investigating from.
Test run is here: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9455188&view=results
=> Integration test improvements

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WorkspaceSemanticTokensRefreshNotifier.cs
Fixes a PRISM fault I can't find the link for right now
=> Don't get capabilities before they're available

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/RazorActivityLog.cs
Integration tests all failed with a MEF composition error
=> Add missing attribute

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentSynchronization/DocumentDidChangeEndpoint.cs
Seems like we're hitting the error condition here, and so our integration tests are firing telemetry for it. Would be better to debug fail so we get a failed test and know what the scenario is.
=> Add log message and assert to identify PRISM bug

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_Diagnostics.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_SemanticTokens.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_UpdateCSharpBuffer.cs
=> Logger isn't nullable

eng/Versions.props, eng/config/PublishData.json
=> Update configs for 17.11 P1

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/RazorCSharpStatementFoldingProvider.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Folding/FoldingEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/10324
=> Fold C# statement blocks

eng/config/PublishData.json
=> Update 17.11 config after VS snap

src/Razor/Directory.Build.props
Fixes https://github.com/dotnet/razor/issues/10309
=> Don't put Razor.Diagnostics.Analyzers in the VSIX

eng/Version.Details.xml, eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
Funny story.
When I did my previous PR, I had to bump Roslyn but thought I'd leave CLaSP alone to simplify the PR, and not confuse this. So this PR is bumping CLaSP to match and dealing with all of the breaking changes.
There were 2 😁
=> Bump CLaSP

eng/targets/ReplaceServiceHubAssetsInVsixManifest.targets
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2056346
I made a mistake when I originally authored this, but we didn't notice because we were shipping .NET Framework services so there were files at the specified location too. Now that we've removed those, this started to cause exceptions.
=> Fix asset manifest generation

Directory.Packages.props, eng/Version.Details.xml, eng/Versions.props, src/Razor/src/.editorconfig, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/CSharpTestLspServer.cs
Fixes nothing but some self-inflicted wounds :)
=> Bump Roslyn and respond to System.Text.Json changes

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentSynchronizer.SynchronizationRequest.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentSynchronizer.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/HtmlDocumentSynchronizerTest.cs
Fixes some issues found while working on folding ranges support. When closing a razor file, it still thought it had completed work, so reopening would not regenerate, leaving an empty buffer. Also some issues around retrying if generation failed, either for exceptional reasons on boring ones, and a double-dispose issue the fix for that introduced.
=> Fix some bugs with the html document synchronizer

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget.cs
I meant to remove this when I cleaned up the rest of the old cohosting stuff, but missed it.
=> Remote unused export

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CSharpCodeActionsTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DiagnosticTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DocumentHighlightTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/FormatDocumentTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/HoverTests.cs
QoL change for investigating some integration test failures. I didn't search in other test projects, just useful for me to investigate fuse related failures.
=> Change some string comparisons to EqualOrDiff

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticConverter.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorTranslateDiagnosticsService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Extensions/TextDocumentExtensions.cs
Fixes an issue reported by Vlad where Html/Js diagnostics were not showing. Will explain in comments
=> Tweak diagnostics reporting to make things more consistent and reliable

eng/config/PublishData.json
=> Target release/dev17.11 to rel/d17.11

Directory.Packages.props, src/Compiler/perf/Microsoft.AspNetCore.Razor.Microbenchmarks.Generator/Microsoft.AspNetCore.Razor.Microbenchmarks.Generator.csproj
fix [this ](https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-razor/alert/7988630?typeId=6437374) issue
=> Set System.Security.Cryptography.Xml version

src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTagHelperTests.cs, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorTagHelperTests/EscapedIdentifierInRazorBlock/Views_Home_Index.html
Noticed while working on an issue.
The test did not import the tag helper correctly, so it wasn't very useful, I think.
cc @333fred
=> Fix a tag helper test

azure-pipelines-compliance.yml
Test run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9752413&view=results
=> Fix APIScan authentication

src/Compiler/shared/JsonReaderExtensions.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/IntraTextAdornmentTagger.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SourceMappingAdornmentTagger.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SourceMappingAdornmentTaggerProvider.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SourceMappingTagger.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerToolWindow.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizerMenu.vsct, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.cs.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.de.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.es.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.fr.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.it.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.ja.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.ko.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.pl.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.pt-BR.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.ru.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.tr.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.zh-Hans.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.zh-Hant.xlf
Add tag helper visualization for All, In Scope and Reference tag helpers
=> Add tag helper vizualization to the syntax viewer

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/TextEditResponseRewriter.cs
Partially complete https://github.com/dotnet/razor/issues/8829
=> Handle InsertReplaceEdit for completion

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/GoToDefinitionTests.cs
Since we were talking in the working group meeting, thought I'd give it a go and see if it passes
=> Unskip bound attribute test

eng/Versions.props, src/Compiler/Directory.Packages.props, src/Compiler/perf/Microbenchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks.Compiler.csproj
Analogous to https://github.com/dotnet/razor/pull/10464
=> Update version of system.security.cryptography.xml in use in 17.10

Directory.Build.targets, src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/StreamExtensions.NetCore.cs, src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/StreamExtensionTests.NetCore.cs
Thanks for making this super easy @DustinCampbell 🥳
=> Move StreamExtensions to netcore only

src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/AsyncBatchingWorkQueue`2.cs
This pull request cherry-picks b8f14d39bffd11f65b4fc140a69d5413b7c53d8d to `release/dev17.11`
=> Port AsyncBatchingWorkQueue fix to release/dev17.11

eng/Versions.props, eng/config/PublishData.json
=> Snap Razor 17.2P1

src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
Fixes something. Possibly breaks other things :)
=> Allow anyone to opt in to FUSE

eng/config/PublishData.json
=> Insert release/dev17.12 to VS rel/d17.12

eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor.csproj, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Microsoft.VisualStudio.LiveShare.Razor.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension.Dependencies/Microsoft.VisualStudio.RazorExtension.Dependencies.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Microsoft.VisualStudio.Razor.IntegrationTests.csproj
Address CG alerts by upgrading a few packages.
=> Address CG Alerts

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/RazorProjectSystemInProcess.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/SolutionExplorerInProcess.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/RenameTests.cs
Honestly, I'm only 99% confident the test run will pass with this, but I'm going to bed so figured I may as well create the PR anyway 😁
=> Unskip and fix rename integration tests

eng/Versions.props, eng/config/PublishData.json
=> Update configs for 17.12p3 snap

eng/Versions.props, eng/config/PublishData.json
=> Update configs for 17.13p1 snap

azure-pipelines-official.yml
Add policheck to official pipelines
=> Add policheck to official pipeline

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CSharpCodeActionsTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/HtmlCodeActionsTests.cs
Fixes current integration test failures
=> Fix code actions integration tests

eng/Versions.props, eng/config/PublishData.json
=> update configs for 17.13p2 snap

azure-pipelines-official.yml, azure-pipelines.yml
Official build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2575398&view=results
=> Update to macOS-14

Directory.Packages.props
Updates VSTelemetryAPI version to 17.13.16
=> Update VSTelemetryAPI version

Directory.Packages.props
=> Cherry-Pick 11181

docs/Compiler Breaking Changes - DotNet 8.md, docs/Compiler Breaking Changes - DotNet 9.md
=> fix codefix that wasn't closed

docs/Compiler Breaking Changes - DotNet 8.md, docs/Compiler Breaking Changes - DotNet 9.md
Add the required learn metadata to publish these articles on learn.
See dotnet/AspNetCore.Docs#34063
=> Add metadata

docs/Compiler Breaking Changes - DotNet 8.md, docs/Compiler Breaking Changes - DotNet 9.md
The previous PR used the wrong date format.
=> Yes, learn uses the US date format.

docs/Compiler Breaking Changes - DotNet 8.md, docs/Compiler Breaking Changes - DotNet 9.md
=> Only one format works for dates.

eng/config/PublishData.json
To be merged after VS snaps today.
=> Update config data for 17.13P2 snap of VS

src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Formatting/FormattingTestCase.cs, src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Formatting/FormattingTestContext.cs
I'm sure this was on my todo list somewhere, it just didn't get todone.
=> Actually use FUSE for FUSE tests

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/FindAllReferencesTests.cs
Update integration test base lines to match the FAR behavior introduced with #11279
=> Fix FAR integration tests

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingTestBase.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/OnTypeFormattingTest.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/FormattingTestBase.cs, src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Formatting/FormattingTheoryDiscoverer.cs, src/Shared/Microsoft.AspNetCore.Razor.Test.Common/IntegrationTestAttributes.cs
Just to establish a baseline.
The "flip line ending" tests all fail, so I've skipped them because I'm not intending to go down that rabbit hole right now.
=> Run on type formatting tests on FUSE

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentPullDiagnosticsEndpoint.cs
The VS LSP client fixed this in https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/591457
=> Remove TODO

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Models/GenerateMethodCodeActionParams.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/GenerateMethodCodeActionProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/GenerateMethodCodeActionResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/RazorCodeActionFactory.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.NetFx.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostCodeActionsEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/9065
=> Offer generate handler for `@bind-XX:after` and `:set`

.github/workflow/backport.yml
=> Add backport github action

eng/config/PublishData.json
I goofed, this should be main until VS snaps on Friday
=> Fix 17.13 insertion branch

eng/config/PublishData.json
=> Update PublishData.json after 17.13 snap

Directory.Packages.props
=> Update package versions

eng/Versions.props, eng/config/PublishData.json
=> Update configs for 17.14 p2

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/TestFiles/Expected/FormatOnPaste.cshtml
Either I used some git commands wrong, or some whitespace got mucked up by something
=> Fix test again

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioLanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
=> Fuse on by default

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioLanguageServerFeatureOptions.cs, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
Targeting to main, cherry picked from https://github.com/dotnet/razor/pull/11416
=> [Main branch] fuse on by default

src/Razor/src/Microsoft.VisualStudio.RazorExtension/VSPackage.resx, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.cs.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.de.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.es.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.fr.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.it.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ja.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ko.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.pl.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.pt-BR.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ru.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.tr.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.zh-Hans.xlf, src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.zh-Hant.xlf
=> Fix typo in setting description

eng/config/PublishData.json
=> Update PublishData.json after vs snap

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CodeFoldingTests.cs
Hopefully this fixes most of our test runs.
=> Update folding range integration test

Directory.Packages.props
=> Update Telemetry package

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LiveShare/IRemoteHierarchyService.cs
Fixes another failure in https://github.com/dotnet/sdk/pull/46633
=> Fix another IDE0040 violation

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/LinePositionSpanExtensions.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.CSharpDocumentGenerator.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.LineInfo.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/11506
Fixes https://github.com/dotnet/razor/issues/11521
=> Fix formatting of multi-line expressions in Html attributes

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteServiceInvoker.cs
Backport of https://github.com/dotnet/razor/pull/11430 to 17.13
=> Fix issue where RemoteServiceInvoker never initializes (17.13)

src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteServiceInvoker.cs
Backport of https://github.com/dotnet/razor/pull/11430 to 17.13
=> Fix issue where RemoteServiceInvoker never initializes (17.12)

Directory.Build.props, src/Analyzers/Directory.Build.props, src/Razor/src/Directory.Build.props, src/Shared/Directory.Build.props
Fixes:
#11546
Following https://github.com/dotnet/roslyn/pull/64581, remove conversion to Windows PDB
=> Remove conversion to Windows PDB

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/AbstractFilePathService.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/FilePathServiceTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=11076433&view=ms.vss-test-web.build-test-results-tab&runId=122938041&resultId=100121&paneView=debug
=> Fix file path service, and integration tests

src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Microsoft.CodeAnalysis.Razor.Compiler.csproj, src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
With other recent changes, we don't produce PDBs for every binary we want to ship.  We are missing 2.
Fixes:
Produce more symbols
=> Produce more symbols

src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorCohostingOptions.cs, src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorSourceGenerator.cs, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Initialization/RemoteLanguageServerFeatureOptions.cs
Attempt 2. Move the option to a dedicated class.
=> Fix jitting when sg enabled

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/DocumentPullDiagnosticsEndpointTest.cs
Missed feedback from a previous PR that was set to auto-complete :)
=> Remove unnecessary assert

Directory.Packages.props, eng/Version.Details.xml, eng/Versions.props, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/ProjectExtensions.cs, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteProjectSnapshot.cs, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteFilePathService.cs
Part of https://github.com/dotnet/razor/issues/10693
Clean up from a previous PR that was waiting for a Roslyn insertion
=> Simply cohosting generated document Uri code

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs
It surprised me we didn't have one of these, considering how often we break it :)
=> Add override completion integration test

src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionItemResolver.cs, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionResolveEndpoint.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/AggregateCompletionItemResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/CompletionItemResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/CompletionListCache.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/CompletionListMerger.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/ICompletionResolveContext.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/DelegatedTypes.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.NetFx.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionItemResolverTest.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionResolveEndpointTest.cs, src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/CompletionListCacheTest.cs
Starting to look at cohosting completion resolve and noticed some things that annoyed me :)
=> Minor clean up of some completion code

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/FindReferencesWindowInProcess.cs
https://devdiv.visualstudio.com/DevDiv/_git/VSEditor/pullrequest/618447 renamed a field
=> Fix find all references integration tests

azure-pipelines-official.yml
Disable recurring build in 17.6
See https://learn.microsoft.com/en-us/visualstudio/productinfo/vs-servicing#long-term-servicing-channel-ltsc-support
=> Disable recurring build in 17.6

azure-pipelines-official.yml, eng/TSAConfig.gdntsa
=> Update TSA Settings 17.10

azure-pipelines-official.yml, eng/TSAConfig.gdntsa
=> Update TSA settings 17.13

azure-pipelines-official.yml, eng/TSAConfig.gdntsa
=> Update TSA settings 17.12

azure-pipelines-official.yml, eng/TSAConfig.gdntsa
=> Update TSA settings 17.8

eng/config/PublishData.json
=> Publish Microsoft.VisualStudioCode.RazorExtension

src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/StressTests/StressTests.cs
Phil's suggestion, copilot wrote most of the code, I watched the .NET Showcase in the background :)
=> Add a stress test for renaming a component attribute

eng/Version.Details.xml, eng/Versions.props
dotnet/dotnet PR: https://github.com/dotnet/dotnet/pull/155/files
Updating:
- Microsoft.IO.Redist to 6.1.3
- System.Threading.Tasks.Extensions to 4.6.3
@ericstj @ViktorHofer @akoeplinger
=> Update maintenance-packages versions

start-code.cmd
Shamelessly stolen from dotnet/aspire
=> Add start-code.cmd

src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/LspDynamicFileProvider.LspTextChangesTextLoader.cs
depends on https://github.com/dotnet/razor/pull/11732
=> Cherry Pick 11727 into release/vscode

Directory.Packages.props, NOTICE.txt, NuGet.config, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Test.csproj
Fixes https://github.com/dotnet/razor/issues/11743
=> Remove unused reference

Directory.Build.targets, eng/Version.Details.xml, eng/Versions.props, global.json
We no longer need these old dependencies.
=> Remove outdated entries from Version.Details.xml/props

src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Microsoft.VisualStudioCode.RazorExtension.csproj
This bit me on a clean machine for an undisclosed amount of time.
=> Copy ObjectPool.dll to output folder

src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Microsoft.VisualStudioCode.RazorExtension.csproj
Cherry Picking #11766 to insert into dotnet/vscode-csharp
=> Cherry Pick 11766

src/Analyzers/Razor.Diagnostics.Analyzers.Test/IRemoteJsonServiceParameterAnalyzerTests.cs, src/Analyzers/Razor.Diagnostics.Analyzers/DiagnosticIds.cs, src/Analyzers/Razor.Diagnostics.Analyzers/GlobalSuppressions.cs, src/Analyzers/Razor.Diagnostics.Analyzers/IRemoteJsonServiceParameterAnalyzer.cs, src/Analyzers/Razor.Diagnostics.Analyzers/Resources.resx, src/Analyzers/Razor.Diagnostics.Analyzers/WellKnownTypeNames.cs, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.cs.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.de.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.es.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.fr.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.it.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.ja.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.ko.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.pl.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.pt-BR.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.ru.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.tr.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.zh-Hans.xlf, src/Analyzers/Razor.Diagnostics.Analyzers/xlf/Resources.zh-Hant.xlf
There is a test for this, but an analyzer is a better dev experience.
Copilot wrote most of this.
=> Analyzer to ensure correct parameter usage in Json services

src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Completion/RemoteCompletionService.cs
Fixes the "Assert" that Phil was seeing
=> Fix C# completion resolve in VS

src/Compiler/Microsoft.AspNetCore.Razor.Language/test/RazorCodeDocumentExtensionsTest.cs, src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/RazorCodeDocumentExtensions.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Models/ExtractToComponentCodeActionParams.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/ExtractToComponentCodeActionProvider.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/ExtractToComponentCodeActionResolver.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToComponentCodeActionResolverTest.NetFx.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/ExtractToComponentTests.cs, src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/StressTests/RCLStressTests.cs
Fixes https://github.com/dotnet/razor/issues/11478
Did this a while ago, then the issue was assigned and I didn't want to step on anyone's toes, but then someone decided those toes weren't necessary anymore so here we are.
=> Include namespace in extracted component

src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/DefaultRazorIntermediateNodeLoweringPhase.cs
This was recently changed to take in a params array which is great, except for performance on net framework as this causes an array allocation for each caller.
I'm seeing about 0.7% of all allocation in the razor scrolling and typing speedometer test as allocations to create these params arrays.
=> Change DefaultRazorIntermediateNodeLoweringPhase.MergeTokenLists to not take in a params array

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/AddUsingsCodeActionResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/AddUsingsHelper.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2493866
I was going to look into why we sometimes get relative Uris from the client or something, and then I looked at the code and thought "we could just not do this".
=> Simply the code that generates edits to insert using directives

eng/targets/Services.props, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WrapWithTag/WrapWithTagEndpoint.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/RazorLSPConstants.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteWrapWithTagService.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RazorServices.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Utilities/WrapWithTagHelper.cs, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/WrapWithTag/RemoteWrapWithTagService.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostWrapWithTagEndpoint.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/RazorLSPTextViewConnectionListener.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostWrapWithTagEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/11993
Copilot [did the boring work](https://github.com/dotnet/razor/pull/11994), I just did a bit of clean up and testing. Left its commit history intact to preserve credit :)
=> Port wrap with tag to cohosting

Directory.Packages.props, eng/Version.Details.xml, eng/Versions.props, src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor.csproj, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/SyntaxListExtensions.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/FormattingContext.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Discovery/ProjectStateChangeDetector.TestAccessor.cs, src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Discovery/ProjectStateChangeDetector.cs, src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/RazorWorkspaceListenerBase.cs, src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/DynamicFileProviderFactory.cs, src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/LspDynamicFileProvider.cs, src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/RazorInitializer.cs, src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/TelemetryReporterWrapper.cs, src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/VSCodeTelemetryReporter.cs, src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Workspaces/WorkspaceTestBase.cs
Fixes https://github.com/dotnet/razor/issues/12009
Needs a Roslyn bump before this will compile. Roslyn PR: https://github.com/dotnet/roslyn/pull/79254
=> Allow our VS Code extension to report telemetry (through Roslyn)

Razor.Slim.slnf, src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionItemResolver.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/DelegatedCompletionHelper.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/VSInternalCompletionListExtensions.cs, src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Completion/RemoteCompletionService.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.NetFx.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentCompletionEndpointTest.cs
Fixes https://github.com/dotnet/vscode-csharp/issues/8486
Fixes https://github.com/dotnet/razor/issues/12099
=> Fix VS Code cohosting completion when Razor and C# are valid

src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/SourceTextExtensions.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/CSharpFormattingPass.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/CSharpOnTypeFormattingPass.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/HtmlFormattingPassBase.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/HtmlFormattingPass.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/RazorFormattingPass.cs, src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/12120
=> Fix range formatting in the presence of K&R braces

src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokensTest.cs
Not sure how I missed this one
=> Update a test missed in https://github.com/dotnet/razor/pull/12149/

src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorSourceGenerator.cs, src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/StringExtensions.cs, src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostFoldingRangeEndpointTest.cs, src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/FileUtilities.cs
Part of fixing https://github.com/dotnet/razor/issues/10437 along with https://github.com/dotnet/roslyn/pull/80068
=> Allow for weird Uris as file paths

src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorCohostingOptions.cs, src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
=> Revert "Revert "Default the cohosting option in the generator to on.""

.github/workflows/copilot-setup-steps.yml
Shamelessly stolen from roslyn, hopefully this means copilot will be able to build its own work
=> Create copilot setup file
