- eng/Versions.props
- src/Compiler/Directory.Packages.props
- src/Compiler/perf/Microsoft.AspNetCore.Razor.Microbenchmarks.Generator/Program.cs
- Noticed two separate versions of BenchmarkDotNet being used not sure if it's really needed to be different.
Traced down when we originally ended up with both versions on this file, it started here: https://github.com/dotnet/razor/commit/108a63cffcd5deadbd045bf0f1f92061bb0c85b2
I think both can be consolidated into one.
> Updates/Consolidates the two BDN versions to latest

- src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj
Previously, I had made a change to the ContainedLanguage project to marrk the Utilities.Shared package ref as PrivateAssets="All". However, this is problematics for Web Tools unit tests, which will fail if Utilities.Shared isn't present when exercising ContainedLanguage. To address this, I'm removing PrivateAssets="All" and allowing the project reference to flow through as a dependency of ContainedLanguage. It's not ideal, but this is better than adding a direct dependency on Utilities.Shared to Web Tools' unit tests.
> Don't mark Utilities.Shared package ref as PrivateAssets="All"

- src/Shared/Directory.Build.props
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/.editorconfig
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/HashAlgorithmOperations.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.csproj
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PublicAPI/PublicAPI.Shipped.txt
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PublicAPI/PublicAPI.Unshipped.txt
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/readme.md
Our Utilities.Shared library is intended to only contain internal APIs for use across both Razor compiler and tooling. This change brings in the public API analyzers to ensure that we don't unintentionally add public APIs to Utilities.Shared.
> Add API analyzers to Utilities.Shared

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/language-configuration.json
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageConfigurationTest.cs
The fix updates the regex in `language-configuration.json`
- Allows a lambda containing "=>" in an attribute
- Makes sure the line does not contain self closing tag
Fixes #8916
> Fixes indentation issue caused by regex in onEnterRules

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
Every little bit of speed up helps, but lets see if this goes too far and re-introduces flakiness.
> Reduce the delay in integration test warmup

- src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.OmniSharp/Project/OmniSharpProjectKey.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentVersionCache.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectChangeEventArgs.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectConfigurationFilePathChangedEventArgs.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectKey.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/WorkspaceProjectStateChangeDetector.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioDocumentTracker.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/EditorDocumentManagerListener.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/RazorCodeDocumentProvidingSnapshotChangeTrigger.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/DefaultProjectConfigurationFilePathStore.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorProjectServiceTest.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Documents/EditorDocumentManagerBaseTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
I should have done this from the start, but didn't due to an extreme lack of confidence (which will now be validated via your PR comments 😛)
> Change ProjectKey to a struct

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentVersionCache.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentVersionCache.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormatter.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentContextFactoryTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentVersionCacheTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/TestRazorFormattingService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/GeneratedDocumentSynchronizerTest.cs
Takes document version tracking off the dispatcher thread requirement and uses a locking mechanism instead.
> Remove dispatcher from DocumentVersionCache

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/GenerateMethodCodeActionResolver.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.cs
- Removes `async` keyword from method generation when executing 'Generate Async Method' code action to align with C# behavior and update tests
- Ensure the same namespace that is computed in [GenerateMethodCodeActionResolver](https://github.com/dotnet/razor/blob/4c74690c1a2506db4a94af6aa8f3fe1979da81e2/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/GenerateMethodCodeActionResolver.cs#L75) is used for the code behind file content in tests.
> Remove Async Keyword For Generate Async Method Code Action

- eng/Versions.props
- Upgrading to .NET 7.0.9 release to take in security fixes for CVE-2023-33127 and CVE-2023-33170 showing up in our pipeline report here [Pipelines - Run 20230726.1 logs (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8149094&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=4bb9ee66-d15b-54bf-dea1-47f4e6298783)
release notes [here](https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.9/7.0.9.md?WT.mc_id=dotnet-35129-website#notable-changes)
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1802880
@jjonescz
> Fixes interoperability issues from CVE-2023-33127 and CVE-2023-33170

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorDiagnosticsBenchmark.cs
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks.csproj
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/RazorCodeDocumentExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/DocumentPullDiagnosticsEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorTranslateDiagnosticsService.cs
- Adds `Moq` to the benchmark project
- Mocks `LanguageServerFeatureOptions`, `IRazorDocumentMappingService`, and `ILoggerFactory`
- Moves up `CallOnMe()` to keep the range value fixed, regardless of the `FileType` size
- Move validation check into `CleanupAsync`
- Make Benchmark method more compact
- Adds `ShortRun` job to the Diagnostic benchmark, with that we can run the benchmarks faster locally with smaller IterationCount and WarmupCount to help compare different cases faster:
(Reports below using latest commit  [0fde405](https://github.com/dotnet/razor/pull/9016/commits/0fde405d82e36c6420e2b12fb30349b627300161)  with mocked language server and `IRazorDocumentMappingService`)
```
|      Method |    N |       Mean |      Error |   StdDev |     Median | …
```
> Improvements to `RazorDiagnosticsBenchmark` class

- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/SyntaxNode.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Syntax/FindTokenTests.cs
Fixes https://github.com/dotnet/razor/issues/9040.
> Handle the special case where the start of a razor document is whitespace

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/DefinitionEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
Small refactoring I noticed to reduce a few unnecessary closure allocations
> Avoid using `Ancestors().FirstOrDefault()`

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingVisitor.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/ClassifiedSpan.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultRazorSyntaxFactsService.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultRazorSyntaxFactsServiceTest.cs
There are a few simple IDE scenarios that are using GetEditHandler that do no need to do so. This removes them in preparation for turning off calculations entirely.
> Remove unnecessary IDE references to GetEditHandler

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServerWrapper.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLifeCycleManager.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ILspServerActivationTracker.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/LspServerActivationTracker.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Debugging/RazorLanguageService`IVsLanguageDebugInfo.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Debugging/RazorLanguageService`IVsLanguageDebugInfoTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1391983/
Without our language server, we are basically dead in the water, and whilst the code we have now tries to be a good citizen and pre-emptively create our dependent language servers when our server is activated, so that they can hopefully switch to the UI thread and do what they need, if they need, the presence of this bug after previous attempted fixes in https://github.com/dotnet/razor/pull/8027 would imply that it doesn't work. My personal opinion is that it is also not our job or responsibility to be initializing other language servers, and trying to marshall them around.
Further, the two instances where we need this are not what I would call core functionality, so a small window of time where they are unavailable …
> Don't respond to UI thread bound COM entry points if our LSP server isn't active

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorLanguageServerBenchmarkBase.cs
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensBenchmark.cs
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensRangeEndpointBenchmark.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/RangeExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/RazorSemanticTokensInfoService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticRange.cs
This reverts commit 837dc71a2e30a894384ce3d80fa1a8e6603862a4.
-
Fixes:
Developers using debug noted that if they had specific sorts of content, the assert was firing, as that meant the two collections were not merging identically as before.  Undo.
> Revert "Improve Perf for Semantic Tokens (#8968)"

- eng/Versions.props
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CapabilitiesManager.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorRequestExecutionQueue.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/CSharpDiagnosticsEndToEndTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorLanguageServerTest.cs
Fixes https://github.com/dotnet/razor/issues/9064
Proof it works:
> Honour the locale name sent through via the parameters to the Initialize LSP method

- eng/Version.Details.xml
- eng/Versions.props
Sourcelink dependency isn't needed anymore. Arcade uses sourcelink tooling that is included in .NET SDK 8.0 preview 6.
> Remove sourcelink dependency

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs
This fixes the issue with semantic tokens being out-of-whack in multi-targeting projects, and probably a bunch more issues as yet unnoticed too.
The code changes I'm currently working on will remove the hack (or formalize it 😁)
> Don't send multiple buffer updates for the same C# generated document

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentVersionCache.cs
In my previous PR I incorrectly translated the [old code](https://github.com/dotnet/razor/blob/3fee1cdbdb9df0087107e40003cf3a6b8bf7da0d/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentVersionCache.cs#L143) to allow for documents to be in multiple projects, and accidentally left us with a gap in our DocumentVersionCache. I had a `return;` statement where there should have been a `break;` statement.
Obviously this huge change has taken me most of the day to track down 🤦‍♂️
This doesn't seem to manifest any issues to the user currently, but does result in errors in the output log when switching tabs between open Razor documents, for example. When things become actually multi-document, then it starts to cause real problems, especially with somewhat flaky project context …
> Fix issue with document version cache missing some snapshots

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
> Remove a boxed enumerator allocated during TryMapToHostDocumentPosition

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultDocumentVersionCache.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/FoldingRangeEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/DefaultRazorProjectService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultDocumentVersionCacheTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorProjectServiceTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1867769 hopefully
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1868418/ probably
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1868479 optimistically
Fixes #9131
Fixes #9125
This is a bit of a strange one, but while investigating the above issue I saw some definite quirks around project handling and folding range handling in VS Code. All of it I suspect is my fault, and most of it I've been able to fix by just pulling a few choice commits out of the dynamic document uri work I'm already doing.
The first commit is something I have done in my other branch, and fixes an issue in multi-targeting in VS. I saw the same issue today when debugging though, where the misc project and real project in our …
> Fix various folding range, and general VS Code issues

- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/TelemetryReporter.cs
Removes the `TelemetryComplexProperty` wrapper to allow numeric type to show as-is
- The value of [dotnet.razor.eventscope.ellapsedms](https://github.com/dotnet/razor/blob/main/src/Razor/src/Microsoft.VisualStudio.Editor.Razor/TelemetryReporter.cs#L286) is coming through as string but we want them to be numeric.
- As per documentation it seems like the processor `TelemetryComplexProperty` will convert what it's wrapping to the JSON string.
This fix simply removes the `TelemrtyComplexProperty` wrapper around `propertyValue` which is an object type.
Another interesting observation seems to be that we are reporting this values under `Properties` but typically numeric values are expected to be found under `Measures`.
/cc @ToddGrun @ryzngard
> Removes the TelemetryComplexProperty wrapper to allow numeric type

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/FoldingRangeEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LspLogger.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/SemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs
- src/Razor/src/rzls/Program.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultGeneratedDocumentPublisherTest.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/ProjectTests.cs
Second attempt at fixing various issues: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1867769, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1868418, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1868479, #9131, #9125 and https://github.com/dotnet/razor/issues/9060
Also fixes https://github.com/dotnet/razor/issues/9138
Turns out my previous fix, which I pulled out of my other PR, didn't quite go far enough and specifically failed for documents that were restored to their open state in VS Code/VS and for documents that were seen to be in the "Misc Files" project before appearing in a real project.
> Ensure we don't send duplicate changes when unique filenames aren't used

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/RangeExtensions.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/RazorSemanticTokenInfoServiceTest.cs
Fixes the following exception, reported in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1868418 (though I couldn't repro it 🤷‍♂️)
```
[Error - 4:03:22 PM] System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Range end line 50 matches or exceeds SourceText boundary 50.')
at Microsoft.AspNetCore.Razor.LanguageServer.Extensions.RangeExtensions.AsRazorTextSpan(Range range, SourceText sourceText) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/RangeExtensions.cs:line 172
at Microsoft.AspNetCore.Razor.LanguageServer.Semantic.TagHelperSemanticRangeVisitor.VisitAllNodes(RazorCodeDocument razorCodeDocument, Range range, RazorSemanticTokensLegend razorSemanticTokensLegend, Boolean colorCodeBackground) in …
```
> Allow range to extend past the end of the last line, per LSP spec

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Common/CustomMessageNames.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ConfigurableLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsPublisher.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsPublisherTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs
Server side of https://github.com/dotnet/vscode-csharp/pull/6209
Found an issue in the logs where 2 seconds after a .razor document close, we try to update diagnostics for the document, which then tries to remap the ranges for those diagnostics, but we've just closed the file, the so it fails. This was actually quite wasteful, as the remapping has to happen on the server anyway, so its better to just do it after the results have come back. Additionally, it meant that VS Code diagnostics weren't going through our translation service, which excludes some diagnostics and fixes ranges on others, so the experience would have been generally worse than in VS.
Also renamed a couple of things to make a bit more sense, so the changes are slightly bigger than they first seem.
> Remap and translate diagnostics on the server

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Tooltip/BoundAttributeDescriptionInfo.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Tooltip/BoundAttributeDescriptionInfoTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1872609
This change defends against invalid assumptions about the inputs of `BoundAttributeDescriptionInfo.ResolveTagHelperTypeName(...)`. This method is a bit of a hack that tries to retrieve the parent tag helper's type name from the display string of a bound attribute. It assumes that _every_ `BoundAttributeDescriptor.DisplayName` has the same form of `<return-type> <type-name>.<property-name>`, which isn't always the case:
https://github.com/dotnet/razor/blob/6949e3a5f99d0978a6a6d07a4e4072a11a84ce3a/src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultBoundAttributeDescriptorBuilder.cs#L159-L190
To avoid exceptions being thrown when trying to call `string.Substring(...)` when the assumptions fail, I've rewritten the …
> Rework BoundAttributeDescriptionInfo to avoid failures due to unexpected inputs

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDocumentMappingServiceTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1753830
All of the other mapping methods had checks for `IsRangeWithinDocument` except this one.
Root cause here is probably duplicated C# code, fixed by other recent PRs, but even if there is still a case of that in the wild, the mapping service being defensive against bad data is not a bad thing IMO.
> Defend against bad input in the Inferred mapping

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/HoverEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/HoverInfoServiceTest.cs
Fixes https://github.com/dotnet/razor/issues/9170
Fixes https://github.com/dotnet/razor/issues/8490
Looks like this:
> Fix hover when Roslyn gives us a range that can't be mapped

- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Components/ScopeStack.cs
Extracting common refactoring needed for
- https://github.com/dotnet/razor/pull/9117
- https://github.com/dotnet/razor/pull/9153
See https://github.com/dotnet/razor/pull/9153#discussion_r1303325497.
CC: @chsienki @333fred
> Refactor `ScopeStack`

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DesignTimeHelperResponseRewriter.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorTranslateDiagnosticsService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/RazorSyntaxTreeExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/SyntaxNodeExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorSyntaxFacts.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorTranslateDiagnosticsEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/FindNodeTests.cs
- Update code actions and completion
- Update diagnostics to get off LocateOwner
> Remove more LocateOwner usage

- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/ComponentResources.resx
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Components/ComponentDiagnosticFactory.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Components/ComponentMetadata.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Components/ComponentRenderModeDirective.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Components/ComponentRenderModeLoweringPass.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DocumentationDescriptor.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DocumentationId.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentCodeGenerationTestBase.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentRenderModeAttributeIntegrationTests.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentRenderModeDirectiveIntegrationTests.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/src/ComponentTagHelperDescriptorProvider.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/src/RenderModeTagHelperDescriptorProvider.cs
Make it an error to specify a rendermode for a component that has explicltly declared one.
Cleans up the remaining prototype comments.
> Rendermode errors

- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.ir.txt
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.ir.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/CSharpCodeParser.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/FindTokenIntegrationTest.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.ir.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_DesignTime.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/CodeGenerationIntegrationTest/IncompleteDirectives_Runtime.ir.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/FindTokenIntegrationTest/EmptyDirective.cshtml
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/CSharpSectionTest/CapturesNewlineImmediatelyFollowing.stree.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/RazorDirectivesTest/Directives_CanUseReservedWord_Class.stree.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/RazorDirectivesTest/Directives_CanUseReservedWord_Namespace.stree.txt
Fixes https://github.com/dotnet/razor/issues/9177. The parser was violating an invariant that nodes cannot be terminal nodes, and must always have at least one token child. This is likely not the only variant of this problem, but is a very common one, as typing in the editor will often result in incomplete directives some of the time. We now add a missing token in such cases to avoid violating the invariant.
> Ensure that directive nodes always have at least one token child

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorDiagnosticsBenchmark.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ConfigurableLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.Mac.LanguageServices.Razor/VisualStudioMacLanguageServerFeatureOptions.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ConfigurableLanguageServerFeatureOptionsTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.Common/TestLanguageServerFeatureOptions.cs
OmniSharp was the only thing that didn't set it to false.
> Remove SupportsDelegatedCodeActions option

- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/VsSolutionUpdatesProjectSnapshotChangeTriggerTest.cs
SolutionClosing_CancelsActiveWork was failing because the test dispatcher does not work correctly even with RunOnDispatcherThread async. It would cause the test to try to complete before change notifications required to mutate state.
The fix is to use a dispatcher that just always reports it is on the correct thread. This can be removed in the future when a better fix around change notifications comes in so we can remove thread asserts.
> Fix SolutionClosing_CancelsActiveWork

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultGeneratedDocumentPublisher.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/UpdateBufferRequest.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocument.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/UpdateCSharpBuffer.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/UpdateHtmlBuffer.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/GeneratedVirtualDocument.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocument.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/HtmlVirtualDocumentFactory.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/UpdateBufferRequest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentFactoryTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/HtmlVirtualDocumentFactoryTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/TestDocumentManager.cs
Fixes https://github.com/dotnet/razor/issues/9148
This also should prevent users from noticing, and the system from getting into a bad state, some of the time.
> Fire telemetry if language server and client get out of sync

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionProviderHelper.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeActionFormattingTest.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CSharpCodeActionsTests.cs
Fixes https://github.com/dotnet/razor/issues/9210
Also fixes #8409 because I was surprised it was skipped, and assume it was because of a Roslyn incompatibility. We'll see :)
> Don't add a semicolon to using statements when we insert them

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/ProvideSemanticTokensResponse.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/RazorSemanticTokensInfoService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/SemanticTokens.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorCustomMessageTarget.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/RazorSemanticTokenInfoServiceTest.cs
Fixes https://github.com/dotnet/razor/issues/9229
Part of me was really hoping the above issue was an actual bug, as it could have been a cause of some odd behaviour, but after digging in it turns out its just our logging making things look bad. What is actually happening is that everything is working just fine: While typing we get requests for semantic tokens for various versions, and when a request comes in (happens to be completion in this case) for a higher version, the old requests are cancelled because they are obviously no longer valid. For semantic tokens this was logging 3 warning messages and making things look bad.
After reviewing logs and debugging etc. its actually all fine, and we cancel those requests, but future ones come in, we update buffers fine, and wait appropriately …
> Improve logging of semantic tokens responses, so things don't look broken

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormattingPass.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LinkedEditingRange/LinkedEditingRangeEndpoint.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/TestFiles/Expected/FormatSelection.cshtml
Also in linked ranges, because no fixes were needed (at least according to tests?)
> Remove LocateOwner in formatting

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Debugging/RazorBreakpointSpanEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Debugging/RazorBreakpointSpanEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/9208
Not sure if this was a recent compiler change, or this never worked, but .razor files are generated with the `__o =` stuff, not just .cshtml files, so we need to use inclusive mapping all the time.
> Use inclusive mapping for breakpoints

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultClientNotifierService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorConfigurationEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
Fixes https://github.com/dotnet/razor/issues/9224 by honouring the `razor.format.enable` setting
> Request options from the client when the server starts

- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/8964
Couldn't repro this one, so added a test to verify continued non-reproing. The issue is pretty light on context so it could be we have some edge case where these constructs don't work, in which case this will be helpful to ensure we don't fix one thing and break another.
> Add test to validate existing behaviour

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingPass.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/RazorFormattingTest.cs
While investigating https://github.com/dotnet/razor/issues/7038#issuecomment-1411578609 I noticed the open brace of the section moving, and could repro that bit at least, so this is a partial fix for the bugs seen in that video.
> Be opinionated about the formatting of section blocks

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormatter.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/CodeDirectiveFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/7058
> Don't break the close brace of implicit array initializers

- src/Compiler/tools/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal.csproj
Prerequisite for #8400.
SDK counterpart: https://github.com/dotnet/sdk/pull/35273
(I have also verified this will work with renamed compiler DLLs: https://github.com/dotnet/sdk/pull/34928)
VS insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/496985
> Transport v1 and v2 of MVC extensions

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionResolver.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionResolverTest.cs
Fixes https://github.com/dotnet/razor/issues/8750
The main fix here is to not use NormalizeWhitespace, but the formatter instead, as the former clobbers too much of the users code. Commit-at-a-time is probably the way to go, to see how the test output changes (or doesn't 😛)
> Keep whitespace in extract to code behind

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/SourceSpanExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingService.cs
Fixes 61% of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1883434
The compiler will happily create diagnostics with a source span that is undefined (AbsoluteIndex of -1):
https://github.com/dotnet/razor/blob/main/src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/src/RazorExtensionsDiagnosticFactory.cs#L26
Also snuck in a removal of one-allocation-per-diagnostic just because I'm in the mood.
> Don't crash if there are diagnostics without spans

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorDocumentMappingBenchmark.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ArrayExtensions.cs
Last one before I go :)
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1886121 which is the first non-compiler stack when searching PRISM for "Razor" 😁
The benchmark results look pretty good, but are actually probably worse than real world, as the benchmark code has the number of locations being mapped increases with the size of the file. In the real world, I expect large files will get a huge speed boost in normal scenarios, which just map one or two positions. I could write another benchmark that just maps one location, but that feels unnecssary.
|       Method |        Job |            Toolchain | Blocks |          Mean |        Error |       StdDev |        Median |           Min |           Max | Allocated |
|------------- |----------- |--------------------- |------- …
> Use a binary search when trying to find source mappings

- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.AllTagHelpers.cs
- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs
- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/StaticCompilationTagHelperFeature.cs
I was looking at a trace the other week and noticed that the source generator was a significant source of `TagHelperDescriptor[]` allocations and copying. This pull request fixes a bunch of low-hanging fruit in this area.
* Don't allocate a new `List<TagHelperDescriptor>` for every reference on a compilation. Instead, pass int the same list.
* Don't create a new array and copy two `List<TagHelperDescriptor>` into it. Instead, create an object that implements `IReadOnlyList<TagHelperDescriptor>` and wraps the two lists.
* Start with a list with a larger capacity when collecting the tag helpers in compilation references.
* Avoid boxing an `ImmutableArray<TagHelperDescriptor>.Empty` to an `ICollection<TagHelperDescriptor>`.
> Reduce allocations and array copies in the Razor source generator

- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/ProjectContexts.cs
Editor fixed the Nav Bar. Yay!
David had a bug. Boo!
Before:
After:
> Fix empty parentheses in nav bar

- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/IncrementalValueProviderExtensions.cs
- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.RazorProviders.cs
- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.cs
- src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
- Don't do tag helper discovery when suppressed
- Don't calculate options when suppressed 
- Update logging to correctly show if we ran or not
- Update tests to check we're not performing any work
- Refactor out the suppression checks
> Fix suppression

- eng/Version.Details.xml
- eng/Versions.props
Pre-requisite for PR https://github.com/dotnet/razor/pull/9304#issuecomment-1732094147
Will need version `4.8.0-3.23471.2` or higher to have the `roslyn/semanticTokenRanges` LSP endpoint available to request for semantic tokens using precise ranges.
> Update Roslyn to `4.8.0-3.23471.2`

- eng/Versions.props
Fixes this error while restoring Razor.sln:
> Upgrade Shell package version

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerTagHelperCompletionService.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/LanguageServerTagHelperCompletionServiceTest.cs
Fixes https://github.com/dotnet/razor/issues/9338
Had to update a couple of existing tests as they were passing, but for the wrong reasons.
> Show non-html element completions even if their attribute rules aren't satisfied

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting/HtmlFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/9337
If only there was some kind of base class that represented everything common about an attribute 🤦‍♂️
> Fix formatting of minimized tag helper attributes

- eng/config/PublishData.json
VS has snapped 17.8 so we need to insert here instead
> Insert Razor 17.8 into VS 17.8

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionListProvider.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/TestDelegatedCompletionListProvider.cs
Fixes https://github.com/dotnet/razor/issues/9211
When typing quickly, completion requests get dropped because we try to wait for the correct version of the generated C#, which is correct, but because we return Razor completion items, and because the client doesn't re-request completion during typing, we end up with "broken completion", by just never showing anything from Html or C#.
Before:
After:
> Mark list as incomplete if delegated server couldn't respond

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/HoverInfoService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperServiceTestBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/HoverInfoServiceTest.cs
Fixes https://github.com/dotnet/razor/issues/9397
The parent calculation for attributes was wrong, but without tag helper rules, the calculation had no effect, so the bug didn't show up anywhere.
> Fix parent tag calculation for attribute hovers

- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/Completion.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs
Fixes #9409
1. Fix so space is no longer a commit character for completions. This can lead to very poor typing experience.
2. Disable snippets for csharp while we look into issues with it breaking all csharp completion
> Fix some snippets

- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Snippets/SnippetInfo.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/Completion.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1899533 and the override completion part of https://github.com/dotnet/razor/issues/9409
We were incorrectly thinking everything was a snippet, and setting its `InsertText` to the snippet context, which would then be null. This not only prevented us calling delegated servers for completion resolve, which caused the override completion part of https://github.com/dotnet/razor/issues/9409, but also meant that the client fell back to using the `LabelText` to commit the completion item. This means the Html servers retrigger functionality was broken, since it was just retriggering on the same content over and over.
> Don't assume everything is a snippet

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/UriExtensions.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/UriExtensionsTest.cs
- Fixes noisy errors generated when viewing git diff of cshtml/razor files on VS code.
This is a hacky workaround. Would be good to follow this up with a proper fix.
- The language server project was returning a wrong file path for URIs with git scheme
- e.g. this could happen when opening git diff on VS code
- With this hacky fix, we make up a fake git folder to provide for these file paths
- This makes sure the returned file path for the left hand side of the git diff view, would not collide with existing file paths (original file path for the right hand side)
Fixes #9365
> Reduce noisy errors when viewing git diff on VS code

- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/Completion.cs
Take 2 on https://github.com/dotnet/razor/pull/9380 now that completion doesn't return null when the delegated server does.
> Return an incomplete list if the delegated server doesn't respond

- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X/src/ViewComponentTagHelperDescriptorProvider.cs
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X/src/ViewComponentTagHelperDescriptorProvider.cs
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/src/ViewComponentTagHelperDescriptorProvider.cs
- src/Compiler/Microsoft.AspNetCore.Mvc.Razor.Extensions/src/ViewComponentTypeVisitor.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/ITagHelperDescriptorProvider.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/PublicAPI.Shipped.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/PublicAPI.Unshipped.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperCollector.Cache.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperCollector.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/src/BindTagHelperDescriptorProvider.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/src/ComponentTagHelperDescriptorProvider.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/src/DefaultTagHelperDescriptorProvider.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/src/EventHandlerTagHelperDescriptorProvider.cs
Fixes #8336
Fixes #8609
Roslyn shares the same assembly symbol instances across compilations when they refer to the same underlying assembly. Using this information, we can cache `TagHelperDescriptors` per assembly using a `ConditionalWeakTable` when computing tag helpers for compilation references, which saves tons of allocation and CPU-bound work. during tag helper and component discovery.
I've introduced an abstract base type, `TagHelperCollector`, to perform the general algorithm of collecting tag helpers from a target symbol, or a compilation and its references. Next, I updated each `ITagHelperDescriptorProvider` that produces tag helpers from a compilation's references to use a `TagHelperCollector` descendant to perform the work.
> Cache tag helpers per assembly reference

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorDocumentMappingServiceTest.cs
Fixes https://prism.vsdata.io/failure/?query=c%3A*LinePositionSpan*%20fe%3A*razor*&eventType=fault&failureType=hits&failureHash=0aca18a1-1f14-3647-5fc8-d18f8edea02f&showFG=false
This code used to use VS protocol types, which did no validation, which means we were returning bad data to other services/components, and letting them deal with it. By switching to Roslyn data types, which do validate, the bad data has surfaced to us, so this not only prevents us throwing exceptions, but also prevents us returning bad mappings.
~No tests yet, because I can't repro it, and the one CAB we have so far can't be loaded on my machine, so a repro is still pending. Putting this up because its the end of my day, and to make sure our tests all pass.~
Found a repro, and wrote a very crappy test.
> Don't map to ranges that are invalid

- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/SemanticTokens.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1841559 while we wait for the real fix, either https://github.com/dotnet/razor/issues/9197 or The Great Merge™
> Don't report that we're synchronized if the line count is wrong

- src/Compiler/Microsoft.CodeAnalysis.Razor/src/BindTagHelperDescriptorProvider.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/test/BindTagHelperDescriptorProviderTest.cs
The change to cache tag helpers per assembly led to a bug introduced in the BindTagHelperDescriptorProvider. It *should* visit the compilation's assembly and all of its references. However, while refactoring, I had passed in a different target symbol which ended up overriding the compilation search.
I'll be adding a unit test before this PR goes in. This bug wasn't caught by out tests. Instead, it was caught by the ASP.NET Blazor tests, so we need coverage here.
> BindTagHelperDescriptorProvider should search the compilation

- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentAddListener.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1901166
No testing, no cabs, just intuition. Dispose calls everything that is registered and waits for it to complete. Silly mistake on my part when I originally wrote this.
> Don't dispose inside a lock, when disposing calls a method that tries to take a lock

- docs/InsertingRazorIntoVSCodeCSharp.md
Updates VS Code insertion docs to include instructions on how to update VS Code telemetry bits.
> Update VS Code insertion instructions to include DevKit telemetry

- docs/InsertingRazorIntoVSCodeCSharp.md
Based on [this conversation](https://github.com/dotnet/razor/pull/9465#discussion_r1370821267), it's likely safer to always update rzls and our Razor telemetry dll together. This PR updates the insertion instruction docs to reflect this.
> [Documentation] Require always updating both rzls and telemetry dlls in VS Code

- docs/InsertingRazorIntoVSCodeCSharp.md
Updates docs to reflect [this change](https://github.com/dotnet/vscode-csharp/pull/6600) (will wait to merge this PR until that PR is in)
> [Documentation] Start inserting platform agnostic language server + telemetry

- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Telemetry/TelemetryReporter.cs
This will make it easier for us to write TN. Looking at all the values available in https://learn.microsoft.com/en-us/dotnet/api/system.typecode?view=net-7.0 it seems they should all just be directly written except for `TypeCode.Object`
> Only use complex types for TypeCode.Object

- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/HtmlMarkupParser.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/SyntaxNavigator.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/SyntaxNode.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/SyntaxToken.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Language/SyntaxTreeVerifier.cs
Port over SyntaxNavigator from Roslyn. I've also rewritten FindToken to utilize this, instead of the hand-built system I did previously. In lieu of specific tests, I've instead added a hook to the common `SyntaxValidator` type, that collects all `SyntaxTokens` in a tree and validates the new APIs on them to ensure that we get correct results.
> Port SyntaxNavigator from Roslyn

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackHostProject.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackProjectManager.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BackgroundDocumentGenerator.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/FallbackProjectManagerTest.cs
Fixes a regression from https://github.com/dotnet/razor/pull/9486
> Don't generate code for closed files that are part of fallback projects

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionListProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/HoverInfoService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/MarkupTransitionCompletionItemProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionFactsService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultHtmlFactsService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/HtmlFactsService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/CompletionListProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DirectiveAttributeTransitionCompletionItemProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionListProvierTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TagHelperFactsServiceTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderBaseTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeParameterCompletionItemProviderTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/MarkupTransitionCompletionItemProviderTest.cs
This required adjusting some implementation logic that would have been broken by https://github.com/dotnet/razor/pull/9455, but weren't caught by the tests directly on the main completion provider. We should consider moving these tests to more functional-style implementation, where we test the whole provider pipeline, to avoid potential future bugs here.
With this PR, we've removed all LocateOwner product usages outside the legacy tooling! A followup PR will mark `LocateOwner` as `Obsolete` and suppress the specific areas that it's allowed to be used.
> Remove LocateOwner from Razor Tooling Tests

- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/DefaultRazorIntermediateNodeLoweringPhase.cs
- src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorComponentTests.cs
Previously, the warning `RZ10012: Found markup element with unexpected name 'NonExistingComponent'. If this is intended to be a component, add a @using directive for its namespace.` was reported only for `MarkupElementSyntax` nodes which is fine for elements like `<X />`. But elements like `<X @key="null" />` are rewritten into `MarkupTagHelperElementSyntax` nodes because there are tag helpers registered for things like `@key`, `@ref`, etc. So this PR adds the reporting also to tag helper elements if they match by attribute (components have also tag helpers which match by tag name - and we obviously don't want to report this warning for them).
Fixes https://github.com/dotnet/razor/issues/9381.
> Warn for unrecognized components with attribute tag helpers

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/TelemetryScope.cs
When reducing allocations in our telemetry, I inadvertently created one array to be too small, resulting in our correlation ID being overwritten for telemetry with three properties.
Many thanks to @maryamariyan for spotting this bug!
> Fix telemetry (again!)

- eng/config/PublishData.json
VS has snapped 17.9 so we need to insert here instead.
> Insert Razor 17.9 into VS 17.9

- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/LegacySyntaxNodeExtensions.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/BraceSmartIndenter.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorIndentationFacts.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/RazorSyntaxTreePartialParser.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/BraceSmartIndenterTest.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/BraceSmartIndenterTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultRazorIndentationFactsServiceTest.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/LegacyCoreContentType.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Language/SyntaxTreeVerifier.cs
There are no more product usages in the LSP codepaths, so we are marking this obsolete in preparation for disabling SpanEditHandlers in non-legacy scenarios.
> Mark LocateOwner obsolete

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/FilePathNormalizer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/FilePathNormalizerTest.cs
Fixes https://github.com/dotnet/razor/issues/9527
The way we handle paths wasn't fixing two slashes in a row to be one slash, which isn't fundamentally a problem, but Roslyn does, and it meant that we were not correctly matching Razor projects to Roslyn projects. We now match Roslyns path normalization logic: https://github.com/dotnet/roslyn/blob/main/src/Compilers/Core/Portable/FileSystem/PathUtilities.cs#L146
> Deduplicate slashes during path normalization

- src/Compiler/Microsoft.CodeAnalysis.Razor/src/BindTagHelperDescriptorProvider.cs
Started seeing this null-ref when opening Razor.sln in 17.9. The fix is simple enough, and I verified that this is a regression introduced by #9410.
@davidwengier: I _think_ this bug is exposed in 17.9 because of your changes to make Razor run on projects that don't reference the Razor SDK. Essentially, the problem is that we're performing tag helper discovery when loading Razor.sln and there are tag helpers found due to our various Shim projects. However, some of those tag helpers didn't conform to expected shapes, so null got into the system and this PR fixes that. However, I'm curious to know if it is expected that Razor should perform tag helper discovery on Razor.sln. That seems unnecessarily costly when there aren't any .razor files present. Thoughts?
> Don't add null tag helpers to results in BindTagHelperDescriptorProvider

- Razor.Slim.slnf
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Legacy/ClassifiedSpanInternal.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.LegacyEditor/RazorWrapperFactory.CodeDocumentWrapper.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorDocumentMappingService.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Language/Legacy/ClassifiedSpan/ClassifiedSpanWriter.cs
This property is calculated through use of SpanEditHandlers, so it needs to go. As part of this, I had to update the tooling `RazorDocumentMappingService` to not rely on this property. Luckily, once I understood what the original code was looking for, there was an obvious, more straightforward way to get that information.
@dotnet/razor-compiler and @dotnet/razor-tooling for review.
> Obsolete ClassifiedSpanInternal.AcceptedCharacters

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshot.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/EditorDocumentManagerListener.cs
We now have support for fallback projects, which is great, but we don't know how many people actually _use_ the files in these projects.
> Fire telemetry when a document is opened that is tracked by a fallback project

- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Telemetry/TelemetryReporter.cs
Noticed this in my other PR, where I was manually reporting a fault and passing in a message, but the message was never used.
With this change it should show up in PRISM and in a CAB if we collect it.
> Use message in the fault description

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultRazorDynamicFileInfoProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackProjectManager.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/FallbackProjectManagerTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Shared/TestProjectData.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultRazorDynamicFileInfoProviderTest.cs
Porting https://github.com/dotnet/razor/pull/9582 to main, in case that one doesn't merge, and because there will be conflicts anyway.
Also took the liberty of removing the unnecessary HashSet.
Only https://github.com/dotnet/razor/pull/9589/commits/70179b3cab6826b266afb053e72c3c374ec6aa03 has not been reviewed in the other PR.
> Port FallbackProjectManager fix to main

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/RazorCodeActionsTests.cs
Reported on Discord by @AdmiralSnyder. Looks like VS sorts code actions alphabetically, which means in the German locale, Html's "Remove <tag>" code action is first:
This is also trivially problematic in English just by having a namespace that makes things appear in an unexpected location:
This PR means we group Razor code actions before Html code actions, which partially solves the issue:
Following up with the editor team to see if there is a better solution. Maybe we should create more groups too, so our "Extract to component" code action is always after our "fully qualify" code actions?
> Group code actions so Razor shows first

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DefaultProjectWorkspaceStateGenerator.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/OOPTagHelperResolver.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultProjectWorkspaceStateGeneratorTest.cs
As discussed at various times, here is some telemetry to _maybe_ help us track down tag helper issues.
I'm no telemetry expert here, but my hope is with these queries we'll be able to find things like:
* Occurances of tag helper discovery never finishing (i've seen this on my machine, but maybe nowhere else?)
* Where tag helper discovery results in us losing tag helper information
* Sessions that never get a non-zero number of tag helpers
* How often we're trying to discover tag helpers in general (with/without any changes)
Please keep that in mind when reviewing. I don't know how to write the Kusto queries for those, I'm just assuming that I, or someone smarter than I, will be able to work it out later :)
Also removing some old telemetry which I don't think we've ever used, and looking …
> Tag Helper Discovery Telemetry

- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/IncrementalValueProviderExtensions.cs
- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators/RazorSourceGenerator.RazorProviders.cs
- src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
Before:
```
warning CS8785: Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentNullException' with message 'Value cannot be null. (Parameter 'languageVersion')'.
... more errors due to missing razor files
```
After:
```
error RZ3600: Invalid value '{0}'' for RazorLangVersion. Valid values include 'Latest' or a valid version in range 1.0 to 8.0.
```
> Fix reporting of incorrect `RazorLangVersion`

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/RangeExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContentValidationPass.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingDiagnosticValidationPass.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/SR.resx
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.cs.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.de.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.es.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.fr.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.it.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.ja.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.ko.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.pl.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.pt-BR.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.ru.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.tr.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.zh-Hans.xlf
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Resources/xlf/SR.zh-Hant.xlf
Fixes: https://github.com/dotnet/razor/issues/9616
Logs look like this:
```
A format operation is being abandoned because it would introduce or remove one of more diagnostics.
Diagnostics before:
Diagnostics after:
/path/to/document.razor(1,2): Error RZ1003: A space or line break was encountered after the "@" character.  Only valid identifiers, keywords, comments, "(" and "{" are valid at the start of a code block and they must occur immediately following "@" with no space in between.
```
and
```
A format operation is being abandoned because it would add or delete non-whitespace content.
Edit at (2, 0)-(3, 0) deletes the non-whitespace content 'public class Foo { }
'.
```
or mabye
```
A format operation is being abandoned because it would add or delete non-whitespace content.
Edit at (2, …
```
> Log when formatting operations are being abandoned

- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Intermediate/ReferenceCaptureIntermediateNode.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentCodeGenerationTestBase.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Component_WithRef_Nullable_Generic/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/GenericComponent_WithComponentRef_TypeInference_CreatesDiagnostic/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithRef_Nullable_Generic/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/GenericComponent_WithComponentRef_TypeInference_CreatesDiagnostic/TestComponent.codegen.cs
Fixes https://github.com/dotnet/razor/issues/9625.
> Add `global::` prefix to `System.Action`

- eng/config/PublishData.json
We need to insert these release branch builds into main until VS snaps on Friday.
I'll try and update docs to more clearly indicate this step so that it's easier to get right in future.
> Ship release/dev17.9 to VS main until VS snap

- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Telemetry/VSTelemetryReporter.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Editor_NetFx/TestTelemetryReporter.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TelemetryReporterTests.cs
0) If TelemetryReporter.ReportFault were called with an RemoteInvocationException that had no InnerException, we would: 1) Pass it to HandleException
2) HandleException would see it is an RIE, pass it to ReportRemoteInvocationException. 3) ReportRemoteInvocationException would see it has no InnerException, and call HandleFault (return to step 0)
RESULT: Stack overflow.  By having ReportRemoteInvocationException effectively ask the quesiton: Does the ReportFault above me on the stack already have the Deserialized ErrorData?, it can break the stack overflow.
-
Fixes:
> Fix stack overflow handling RemoteInvocationException

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs
Fixes the only stack from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1925926 that occurs in 17.9
When I converted semantic tokens to use value types, I either blindly converted this bit of code without thinking, or I was lazy and used the `LinePositionSpan` comparison method as a helper method, but either way it was silly as `LinePositionSpan` will throw on bad data. This would have previously been VS LSP types which didn't throw.
> Move data validity check to happen before the call that would throw if the data wasn't valid

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs
Fixes https://github.com/dotnet/razor/issues/9687
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1923333
Managed to repro this, just a timing thing.
> Retry if the intermediate output path doesn't exist

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionListProvider.cs
Fixes #6504 by just using keywords, which suit our directive completion better
While #6505 is still open, it's not something we can handle in our codebase. I removed the comment.
> Use keyword instead of struct

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/LegacyRazorCompletionEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/LegacyRazorCompletionEndpointTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1930835
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1930839
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1809204
Looks like this was missed in https://github.com/dotnet/razor/pull/9532
Hopefully none of the other code changes in that PR are important 🤦‍♂️ We should really do single server completion in VS Code so we can delete all of this code, as clearly our tests for it are not up to the task. And/or more integration tests in VS Code I guess
> Adjust owner in legacy completion, just like in non-legacy completion

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/HoverInfoService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperServiceTestBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/HoverInfoServiceTest.cs
Fixes https://github.com/dotnet/razor/issues/9713
> Don't show hover info for <Text> components when they're not components

- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/IStartTagSyntaxNode.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/MarkupStartTagSyntax.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/Syntax/MarkupTagHelperStartTagSyntax.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/TagHelperMatchingConventions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionProviderHelper.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/TypeAccessibilityCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/AddUsingsCodeActionParams.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/AddUsingsCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/RazorCodeActionFactory.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/AddUsingsCodeActionProviderFactoryTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ComponentAccessibilityCodeActionProviderTest.cs
Fixes https://github.com/dotnet/razor/issues/7658 by providing a better user experience.
Unfortunately we can't be smart and offer to only fix the casing without some more smarts/APIs from the compiler. But I figure this is better than nothing.
Before:
Before when there is also an `@bind` attribute:
After:
The add using code action is also smarter. Full capabilties:
> Offer to fully qualify component name even if case doesn't match

- eng/Versions.props
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/IClientSettingsManager.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Options/OptionsStorage.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Options/README.md
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Options/SettingsNames.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs
- src/Razor/src/RazorDeployment/RazorDeployment.csproj
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Microsoft.AspNetCore.Razor.Test.Common.Tooling.csproj
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/ClientSettingsManagerTest.cs
Finalizes AB#1786418 
Unified settins has been in for a while, but we needed to consume the 17.9 preview packages to be able to subscribe to the change events. This adds that, updates the structures we use to help keep it easy to follow, and adds a readme for people adding new options.
> Refresh settings when unified settings change

- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Options/OptionsStorage.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/OutputWindowLoggerProvider.cs
The two logging PRs worked fine in isolation, but wouldn't you know it when they're both merged in, we ended up with a MEF circular dependency. This fixes that.
> Fix MEF cycle

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/OutputInProcess.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/LogIntegrationTestAttribute.cs
Seems like we can't expect types to be in the MEF composition if they're not in the installed VS version. I guess the test harness bits run in a separate environment to the hive used for the tests? Anyway.
This should hopefully allow our main integration tests to start passing again, and once the actual IRazorLoggerFactory bits are inserted into VS main we can hopefully revert this. Of course, that requires getting our CI unblocked, but thats a problem for another day :)
> Don't use IRazorLoggerFactory from integration tests.... YET!

- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Logging/RazorLogHubTraceProvider.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Telemetry/VSTelemetryReporter.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/RazorLogHubLogger.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/RazorLogHubLoggerProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/VisualStudioWindowsLogHubTraceProvider.cs
Hopefully fixes an issue seen in integration tests, and by @alexgav. I was never able to repro it, but I could see it being possible if there is a race between the trace source being initialized, and an error that wants to be reported.
> Don't get the trace source until we need to use it

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ConfigurableLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Workspaces/TestLanguageServerFeatureOptions.cs
If nothing else, this cleans up the logs when trying to work out why your cohost endpoint isn't working :)
> Add feature flag to disable the Razor LSP, leaving only cohosting

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/DidChangeHandler.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/DidOpenHandler.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/OpenDocumentGenerator.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/UpdateCSharpBuffer.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/UpdateHtmlBuffer.cs
In theory this means the end of document sync issues forever!
In practice there is one fire-and-forget async method call here, from a sync context, so edge cases will still creep in. But all of this code should be deleted eventually anyway :D
> Move C# and Html document generation (ie, compilation) to the Cohost side of the world

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/MultiTargetProjectTests.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/NonRazorSdkTests.cs
Sort of fixes https://github.com/dotnet/razor/issues/9368 (but really i think its just not necessary)
Integration test run is green: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8856230&view=results
> Move integration tests to .NET 8

- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/OpenDocumentGenerator.cs
Noticed this in the integration tests logs. Might be the cause of disco colors in them?
> Don't generate documents for cohosting if we're not cohosting

- eng/Versions.props
- src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/TestFiles/RazorSourceGeneratorComponentTests/ScriptTag/Views_Home_Index.html
Seems better if our tests are executed against the latest runtime version.
> Update ASP.NET Core runtime used in tests to v8 GA

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Cohost/CohostDocumentContextFactory.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Cohost/CohostDocumentSnapshot.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Cohost/CohostProjectSnapshot.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Cohost/DocumentSnapshotFactory.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Cohost/ProjectSnapshotFactory.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentVersionCache.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IDocumentVersionCache.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostDocumentColorEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostSemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/RazorCohostRequestContextExtensions.cs
This PR is the very first baby step towards using the Roslyn project system in cohosting.
What it does:
* Creates document and project snapshots from Roslyn document and project snapshots for document color and semantic tokens requests
* Provides a point for @chsienki and co to put their calls to the source generator to get the generated code (in `CohostDocumentSnapshot.GetGeneratedOutput`) and host outputs (various places in `CohostProjectSnapshot`)
What it doesn't do:
* Anything good for performance. This is blindly discovering tag helpers whenever a project snapshot changes, rather that trying to carry them forward
* The source generator will do that work
* Remove any of the old systems, meaning everything is running in parallel with …
> Use Roslyn project info in cohost endpoints

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentVersionCache.DocumentEntry.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentVersionCache.TestAccessor.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentVersionCache.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DefaultProjectSnapshotManager.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentVersionCacheTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/LanguageServerTestBase.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ReadWriterLocker.cs
While investigating `ProjectSnapshotManagerDispatcher`, I encountered an issue with `DocumentVersionCache` where it would never exit an upgradeable read lock. This pull request fixes that issue and makes several other changes.
1. `DocumentVersionCache` no longer exposes internal data structures for unit tests. Instead, it provides a `TestAccessor` to avoid allowing unfettered access to a dictionary that should only be accessed within a lock.
2. Tests now use a real dispatcher to modify `ProjectSnapshotManager`, which exposes the issue fixed in this PR.
3. Asserts have been added to verify that methods are called with the correct lock being held.
4. Structs are no longer passed around to indicate the lock state. These were a little broken anyway because they are mutable structs that track …
> Fix and clean up `DocumentVersionCache`

- eng/Versions.props
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/DocumentPullDiagnosticsEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/DocumentPullDiagnosticsEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticConverterTest.cs
Add telemetry for time-to-first diagnostic
By adding this Diagnostic kind to our set of capabilities, the VS Win system lights up to gather the time to first diagnostic event, so we can track changes in that duration. 
Adds a unittest for the endpoint.
> Add telemetry for time-to-first diagnostic

- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/OpenDocumentGenerator.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1939874
FYI @333fred 
After talking to @DustinCampbell this morning I decided to slightly change tact with cohosting, and not worry about having it be able to co-exist with the current language server. That means this RPS regression is easy to fix just by disconnecting the cohost OpenDocumentGenerator from that system. Yes, that means co-hosting is now slightly worse, but if we move away from co-existence, then it matters a lot less, as we no longer expect it to fully work, it just needs to work enough to let us all get our work done. This PR doesn't change that.
In reality what this change does is that if cohosting is on, and the old server is off, then semantic tokens won't be correct for files that were already open when you …
> Don't register cohost types with the Razor project system

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/FoldingRangeEndpoint.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CodeFoldingTests.cs
Fixes #9708
Prior to this, HTML and C# could have different folded text. This normalizes us to "..." in all cases
> Fix folding text for html

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Cohost/CohostDocumentSnapshot.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MapCode/MapCodeEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/IDocumentSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ImportDocumentSnapshot.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingContentValidationPassTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingDiagnosticValidationPassTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingTestBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MapCode/MapCodeTest.cs
There are a few methods in the document/project snapshot system that are problematic and unnecessary in co-hosting. To make their removal from that system easier, I'm going to try to clean some things up around their use, and this is the first PR in that step, by cleaning up the `GetProjectEngine()` method a little bit.
The method is still there, because its used by TagHelperResolvers, but those won't be used in co-hosting so they're not a problem. A future PR will (presumably) split `IProjectSnapshot` up in some way, and so the method itself won't strictly be removed, but rather just not exposed to anything in co-hosting.
I did an integration test run from the midway point of this PR to ensure formatting still works, and it's green: …
> Don't use project engines directly in the language server

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Cohost/CohostDocumentSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/IDocumentSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ImportDocumentSnapshot.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingTestBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/TestDocumentSnapshot.cs
This was going to be part of a larger PR but that is proving to be extremely annoying to do, so I'm pulling this out while I have it.
The `GetImports` method was only used in one place, and was just indirection to call another method on the same class, so this PR just flattens that and simplifies the interface. This just gives us a lower surface area for cohosting.
> Remove IDocumentSnapshot.GetImports

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultWindowsRazorProjectHost.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/FallbackWindowsRazorProjectHost.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioProjectSnapshotManagerAccessor.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultWindowsRazorProjectHostTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackWindowsRazorProjectHostTest.cs
This change avoids passing a Roslyn workspace into `WindowRazorProjectHostBase`. This was only used to retrieve the `ProjectSnapshotManager`. However, `IProjectSnapshotManagerAccessor` exists for that purpose.
Note that I've had to call `JTF.Run(...)` in the VS implementation of `IProjectSnapshotManagerAccessor.Instance` to avoid the snapshot manager being created and initializing project snapshot change triggers on a non-dispatcher thread. I made this change after calling `AssertDispatcherThread()` in `IProjectSnapshotManagerAccessor` and finding that it was indeed being initialized from a different thread (the UI thread) by `CSharpVirtualDocumentFactory`. Because `WindowsRazorProjectHostBase` had a comment about only creating the snapshot manager on the dispatcher thread, I decided to …
> Don't use Workspace in WindowsRazorProjectHostBase

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServerWrapper.cs
Set our exception strategy such that exceptions our server creates are serialized to the client, and if a client we communicate with throws an exception we get it embedded as an inner exception.
> Use ISerializable exception strategy

- .editorconfig
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Cohost/CohostDocumentContextFactory.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/DefaultFileChangeTrackerFactory.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Documents/EditorDocumentManagerListener.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostDocumentColorEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostSemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorCustomMessageTarget.cs
This change enables a couple of the Roslyn analyzers for MEF and fixes the violations. In particular, an error will now be reported for anything exported with MEFv2 that does not also have the `[Shared]` attribute. Like Roslyn, I don't believe Razor has any scenarios where MEF exports aren't intended to be singletons.
> Enable MEF diagnostics and fix issues

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensBenchmark.cs
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensScrollingBenchmark.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Common/Capabilities.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Common/VSInternalServerCapabilitiesExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentColor/DocumentColorEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentColor/DocumentColorService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentColor/IDocumentColorService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/SemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/IRazorSemanticTokenInfoService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/RazorSemanticTokensInfoService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostDocumentColorEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostSemanticTokensRangeEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokensTest.cs
After a chat with @davidwengier I wanted to propose this design for moving forward with CoHosting. This makes it so the services themselves aren't ICapabilitiesProviders, and instead we have that code separate but still centralized. 
It still keeps the endpoints as `ICapabilitiesProvider`
> Move capabilities to a central place

- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioDocumentTracker.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioDocumentTrackerFactory.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DefaultVisualStudioDocumentTrackerFactoryFactory.cs
- src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/ProjectSnapshotSynchronizationService.cs
- src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/ProjectSnapshotSynchronizationServiceFactory.cs
- src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Host/DefaultProjectSnapshotManagerProxy.cs
- src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Host/DefaultProjectSnapshotManagerProxyFactory.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/OpenDocumentGeneratorTest.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultRazorDocumentManagerTest.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultVisualStudioDocumentTrackerTest.cs
- src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/ProjectSnapshotSynchronizationServiceTest.cs
This change avoids requesting `IProjectSnapshotManager` from the Roslyn workspace in a few more places.
Note that there's a lot of effort in the Live Share code to access the `ProjectSnapshotManager` on the main thread rather than the dispatcher thread. I have a sneaking suspicion that was actually incorrect and this might have been missed back when the `ProjectSnapshotManagerDispatcher` was introduced. Since this is Live Share, it's kind of off the beaten path.
> Use `IProjectSnapshotManagerAccessor` rather than requesting `IProjectSnapshotManager` as a Roslyn language service

- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/CSharpTestLspServer.cs
With all of the churn in the Roslyn versions, due to CLaSP breaking changes, I completely missed that my fix to avoid reflection went in, and Ankita fixed the nested code actions bug too.
> Follow up to Roslyn bump

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/DefaultLSPTagHelperTooltipFactory.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DefaultLSPTagHelperTooltipFactoryTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/HoverInfoServiceTest.cs
Make the tooltip show the full tagHelperTypeName instead of the reduced name in LSP factory. This method is used in both hover service and code completion service.
Fixes #9638
- To make the TryCreateTooltip method in DefaultLSPTagHelperTooltipFactory return the tag helper’s full type name with its namespace, I added the namespace to the descriptionBuilder variable. (see picture below for visualization)
-  I also changed the corresponding unit tests in DefaultLSPTagHelperTooltipFactoryTest.cs and HoverInfoServiceTest.cs to test for the now desired behavior with the full namespace shown in tag helper with the type name in bold. 
- This change only affects the VS code user experience and does not affect that of Visual Studio.
- This fixes GitHub issue #9638 where hovering on a razor element …
> tooltip fix for hover and code completion on VS code 

- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveAttributeCompletionSource.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Completion/RazorDirectiveCompletionSource.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Completion/RazorDirectiveCompletionSourceTest.cs
We want to continue using LocateOwner for legacy code as the logic in FindInnermostNode isn't finding the correct node here.
-Switch back to LocateOwner which finds the correct tree node for the legacy code. That allows us to create RazorCompletionContext that provides completion items for the directives. 
Fixes:
AzDO filed issue - Razor directives are missing from completion list in Razor Pages when legacy editor is enabled.
> Restoring usage of LocateOwner in legacy-only completion scenarios

- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/CodeGeneration/CodeWriterExtensions.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/CodeGeneration/DesignTimeNodeWriterTest.cs
Ensure we include the line count and end char index in remapped spans
Fixes https://github.com/dotnet/razor/issues/9827
> Ensure we include the line count and end char index in remapped spans

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/IProjectSnapshotExtensions.cs
There are 2 project snapshot types that are allowed to be non-async.
Will be cleaned up properly in https://github.com/dotnet/razor/issues/9878 (hopefully)
> Fix false assert from legacy editor

- global.json
- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport.csproj
Contributes to: https://github.com/dotnet/source-build/issues/3170
Backport of changes in https://github.com/dotnet/installer/pull/18478
Each .NET repo needs to specify all used SDKs in `global.json` file. This change adds the missing SDK.
> Add missing SDK dependency to global.json

- eng/Version.Details.xml
- eng/Versions.props
The changes in this pull request aim to [improve the UX and guideance around the SourceBuild metadata](https://github.com/dotnet/source-build/issues/3373) by placing the metadata on explicit source-build intermediates.
The changes include:
- Removing existing SourceBuild metadata from all non-intermediate dependencies.
- Defining new explicit intermediate dependencies and adding SourceBuild metadata to those dependencies.
Related to https://github.com/dotnet/source-build/issues/3373 and https://github.com/dotnet/source-build/issues/4073
> Move SB metadata to intermediates

- eng/AfterSolutionBuild.targets
- src/Razor/src/Microsoft.VisualStudio.DevKit.Razor/Microsoft.VisualStudio.DevKit.Razor.csproj
- src/Razor/src/rzls/rzls.csproj
- Removed `RuntimeIdentifiers` and self contained packaging related content in csproj
- Set SelfContained to false
Unsure if something else needs to be added,
Also unsure of how best to test the end to end on the extension side.
Related PRs:
- [Allow rzls to launch using standard dotnet (Redo) by maryamariyan · Pull Request #6844 · dotnet/vscode-csharp (github.com)](https://github.com/dotnet/vscode-csharp/pull/6844)
- https://github.com/dotnet/vscode-csharp/pull/5855
> Remove script for building self-contained package

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedTypes.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Common/CustomMessageNames.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Common/VSInternalServerCapabilitiesExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/RazorCodeDocumentExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlayHints/IInlayHintService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlayHints/InlayHintEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlayHints/InlayHintResolveEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlayHints/InlayHintService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlayHints/RazorInlayHintWrapper.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/RazorSemanticTokensInfoService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostDocumentColorEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostInlayHintEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostInlayHintResolveEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/InlayHints.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/InlayHints/InlayHintEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokensTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.TestLanguageServer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/CSharpTestLspServer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/CSharpTestLspServerHelpers.cs
Adds inlay hint support for Razor in VS and VS Code, cohosting and regular.
Goes with https://github.com/dotnet/vscode-csharp/pull/6857 for the VS Code side.
> Add textDocument/inlayHints support

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Common/VSInternalServerCapabilitiesExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Debugging/ValidateBreakpointRangeEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Debugging/ValidateBreakpointRangeEndpointTest.cs
Noticed while looking at https://github.com/dotnet/razor/issues/9846, that when placing a breakpoint on one of the expressions in:
```
<button class="btn btn-primary" @onclick="IncrementCount" disabled="@(currentCount > 3)">Click me</button>
```
The breakpoint got placed correctly, but any edit would then remove it. This fixes that. Seems in [my previous PR](https://github.com/dotnet/razor/pull/9236) when I said "use inclusive mapping everywhere" I missed a spot :)
This ~might also~ doens't fix #9846 itself ~, but I can't be sure as I seem to be unable to build and run Blazor apps at the moment :)~ :(
> Use inclusive mapping for breakpoint validation

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/GeneratedDocumentPublisher.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/MonitorProjectConfigurationFilePathEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultWindowsRazorProjectHost.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/FallbackWindowsRazorProjectHost.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/GeneratedDocumentPublisherTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MonitorProjectConfigurationFilePathEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultWindowsRazorProjectHostTest.cs
Fixes https://github.com/dotnet/razor/issues/9900
When publishing a project, the IntermediateOutputPath get changed to Release during the publish, then back to Debug again at the end. There were two problems with this:
1. We were seeing the change to Release as a new project, and ended up thinking it was multi-targeted
* The changes to our CPS bits fix this, by uninitializing the old project when the intermediate output path changes. Thanks @phil-allen-msft for the headstart commit on this one.
* The changes to the `MonitorProjectConfigurationFilePathEndpoint` make the uninitialize in VS also result in the removal of the project in the language server
2. When changing back to Debug, the VS side of things thought this was a new project (because of the above change), but the language server …
> Don't break the world when a project is published

- .github/policies/resourceManagement.yml
https://github.com/dotnet/razor/pull/9895 had an issue slip through in the migration from FabricBot. The 'merged' action is no longer supported; and there previously wasn't a way to filter to only merged PRs. There's now an `isMerged` condition that can be used.
@JohannesLampel for review.
Please note that all PRs that have been merged since https://github.com/dotnet/razor/pull/9895 have not been automatically updated with the 'Next' milestone as desired.
> Fix the GitHub automation for tracking the milestone on merged PRs

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.TestAccessor.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeDocumentReferenceHolderTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultWindowsRazorProjectHostTest.cs
Fixes #9812 and #9906
ISSUE:
Because we are are keying off of the intermediate object path instead of the csproj file path, the intermediate object path may have ".." in it from normal MSBuiild properties, but that means the same logical string has two different representations.
FIX:
Normalize the path.  There's an adjoining and similiar change in Roslyn to likewise make.  (Will link).  There is alternative fix to pursue where Razor instead does the  normalization.
TESTING:
Unittests pulled from manul testing with ".." in BaseIntermediateOutputPath and ArtifactsPath
> Fixes Razor when ".." is in the intermediate object path

- Razor.Slim.slnf
- eng/AfterSolutionBuild.targets
- src/Razor/src/Microsoft.VisualStudio.DevKit.Razor/Microsoft.VisualStudio.DevKit.Razor.csproj
- src/Razor/src/rzls/rzls.csproj
Before this change, every transitive dependency of these projects were getting rebuilt for each specified RID in addition to the RIDless builds.
This is part of the VMR work (we'll follow this up by reducing the RIDs we build for in each leg in the VMR build).
> Don't rebuild when doing rid-specific publishing, just publish

- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/Telemetry/TelemetryReporter.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TelemetryReporterTests.cs
Skips fault reporting when the inner-most exception is `OperationCanceledException`.
Resolves: [WorkItem#1774918](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1774918/)
> Skip reporting fault when the inner-most exception is OperationCanceledException

- eng/SourceBuildPrebuiltBaseline.xml
- eng/Version.Details.xml
- eng/Versions.props
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyBindingRedirects.cs
It turns out that our System.Immutable.Collections package version was already bumped to 8.0.0 with the Roslyn update. This PR bumps our pinned version of System.Immutable.Collections to match, and also bumps Microsoft.Extensions.ObjectPool.
> Bump immutable collections and objectpool packages to 8.0.0

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks.csproj
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Program.cs
The tooling benchmarks were still using `net7.0` as a target and also compiling with `net7.0`. This change ensures that benchmarks only run and compile on `net8.0` and `net4.2`.
> Update tooling benchmark targets

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.json
This pull request fixes #9882, where Textmate did not support the newly added directives: rendermode, preservewhitespace, and typeparam. The TextMate grammar for Razor is located in the dotnet/vscode-csharp repository, and a separate pull request (dotnet/vscode-csharp#6887) has been submitted with the fix and tests.
The Razor tmLanguage.json file was copied from the vscode-csharp repository to reflect the latest changes, including the addition of grammar support for rendermode, preservewhitespace, and typeparam.
The lack of coloring for the new directives using TextMate.
> Copied aspnetcorerazor.tmLanguage.json from dotnet/vscode-csharp

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/TagHelperCompletionBenchmark.cs
This is a simple change to add a benchmark specifically for TagHelper completion. The results on my machine look like so:
``` ini
BenchmarkDotNet=v0.13.5.2136-nightly, OS=Windows 11 (10.0.26058.1000)
Intel Core i7-8700 CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=8.0.101
[Host]     : .NET 8.0.1 (8.0.123.58001), X64 RyuJIT AVX2
Job-LANPFL : .NET 8.0.1 (8.0.123.58001), X64 RyuJIT AVX2
Job-XNVIXV : .NET Framework 4.8.1 (4.8.9181.0), X64 RyuJIT VectorSize=256
PowerPlanMode=00000000-0000-0000-0000-000000000000  
```
|                  Method |        Job |            Toolchain |     Mean |   Error |  StdDev |   Median |      Min |      Max |    Gen0 |    Gen1 | Allocated |
|------------------------ |----------- |--------------------- …
> Add TagHelperCompletionBenchmark

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/IProjectSnapshotExtensions.cs
Since we are comparing project snapshot type name with full type name string, we should use FullName instead of just Name
Fixes:
I was hitting this assert after re-opening a project (with a Razor page previously open, legacy editor enabled)
Not sure if it was causing any intermittent tag helper discovery issues or just the noisy assert.
> We need to use full type name in the check

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionFactsService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionListProvierTest.cs
The issue here was that FindInnerMostNode returns empty MarkupLiteral node (containing only a marker) and AdjustSyntaxNodeForWordBoundary wasn't working for zero-length tokens in originalNode. Changing the code to allow it seems to fix things.
-Allow adjustment of the originalNode including cases when it contains zero-length tokens only. That fixes the case where cursor is at the very end of the file, e.g. in the image below "functions" was missing
Fixes:
https://developercommunity.visualstudio.com/t/Razor-directive-completions-missing-at-t/10585436
https://github.com/dotnet/razor/issues/9955
> Fix directive completion at EOF (last line of file)

- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Microsoft.AspNetCore.Razor.Test.Common.Tooling.csproj
Awhile back, I'd made Common.Tooling compile to a different assembly name that Roslyn's Razor EA assembly provided IVT to. Awhile back, we updated to a newer Roslyn that fixed the IVT, so this hack can be removed.
> Remove name hack from Razor.Test.Common.Tooling

- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/PublicAPI.Unshipped.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RazorConfiguration.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/src/RazorProjectEngine.cs
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Resources/project.razor.json
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ConfigurableLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Serialization/Json/ObjectReaders.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Serialization/Json/ObjectWriters.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Serialization/Json/SerializationFormat.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Serialization/MessagePack/Formatters/RazorConfigurationFormatter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackRazorConfiguration.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSystemRazorConfiguration.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultWindowsRazorProjectHost.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioWindowsLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
- src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/Serialization/ProjectSnapshotHandleSerializationTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Workspaces/TestLanguageServerFeatureOptions.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Serialization/RazorConfigurationSerializationTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/OOPTagHelperResolverTest.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/DefaultProjectSnapshotProjectEngineFactoryTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultWindowsRazorProjectHostTest.cs
Adds a feature flag and console flag in rzls for "fuse" as a feature. 
Commits are separated by addition of the flag in tooling, and pushing that through to `RazorConfiguration`
> Add feature flag for fuse

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/CSharpCodeParserTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/CSharpCodeParser.cs
@ToddGrun noticed a call to `String.Split(...)` showing up in a Speedometer. The fix was trivial enough, so I went ahead and applied it. While in the code, I made a few other tweaks that I hope will be useful.
> Remove String.Split(...) in CSharpCodeParser

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpFormattingPassBase.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/CSharpOnTypeFormattingPass.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/CodeDirectiveOnTypeFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/9969
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1978110
> Don't add a newline after a component attribute

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer.Protocol/DelegatedTypes.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MapCode/MapCodeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Endpoints/MapCode.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MapCode/MapCodeTest.cs
Telemetry for mapCode - CorrelationId, duration
ISSUE:
When the mapCode method is called, it receives a correlationId; it should log that, so that we can stitch together which LSP servers did which work.
FIX:
Record in telemetry the correlationID and duration.
> Telemetry for mapCode - CorrelationId, duration

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectWorkspaceStateGenerator.cs
ISSUE:
There are cases (caught in debugger) where a cancelled tag helper discovery/update call reports success to the telemetry system.  We should report cancelled if cancelled.
FIX:
Check for cancellation.
> Cancelled tag helper discovery should report cancelled

- eng/Versions.props
Fixes a "critical" CG alert (NuGet.Packaging 6.3.3). Similar to https://github.com/dotnet/roslyn/pull/72242.
> Bump roslyn-sdk

- eng/Versions.props
Backport of #9996 so we get rid of the CG alerts also in release/dev17.9 and release/dev17.10 branches. I won't actually insert this one alone into VS, so there's no need for special M2/QB approvals, I believe.
> [17.9] Bump roslyn-sdk

- Razor.Slim.slnf
- eng/AfterSolutionBuild.targets
- src/Razor/src/Microsoft.VisualStudio.DevKit.Razor/Microsoft.VisualStudio.DevKit.Razor.csproj
- src/Razor/src/rzls/rzls.csproj
This reverts commit e77dc86683ef07a9dd2ba4270003bda3b3886a5b which was causing arm64 mac images to incorrectly try to use the x64 runtime. Fixes [AB1977917](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1977817)
> Revert "Don't rebuild when doing rid-specific publishing, just publish (#9925)"

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LspProjectSnapshotManagerAccessor.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/IProjectSnapshotManagerAccessor.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackProjectManager.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioProjectSnapshotManagerAccessor.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorComponentSearchEngineTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestProjectSnapshotManagerAccessor.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentFactoryTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackProjectManagerTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1947624/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1978114/
_Might_ fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1979185/
Recently, I made a change to `VisualStudioProjectSnapshotManagerAccessor.Instance` to use `JTF.Run(...)` as a last resort to ensure that the project snapshot manager is created on the dispatcher (commit 528f1e950190545b7dda2b20bd129975c71d4c2f). This is necessary because the project snapshot manager initializes change triggers when it is created, and change triggers can do significant work during initialization that should only run on the dispatcher. However, this has been problematic because it results in `JTF.Run(...)` occurring on thread pool threads, which can contribute …
> Avoid force-creating the project snapshot manager off the dispatcher

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LspProjectSnapshotManagerAccessor.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/IProjectSnapshotManagerAccessor.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackProjectManager.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/CSharpVirtualDocumentFactory.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioProjectSnapshotManagerAccessor.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorComponentSearchEngineTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestProjectSnapshotManagerAccessor.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServerClient.Razor.Test/CSharpVirtualDocumentFactoryTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackProjectManagerTest.cs
This cherry-picks the changes from #10024 to the `release/dev17.10`, since there's interest in these changes for 17.10p2.
> [release/dev17.10] Avoid force-creating the project snapshot manager off the dispatcher

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorConfigurationService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingPass.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLSPOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Settings/ClientSettings.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Options/OptionsStorage.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Options/SettingsNames.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Options/AdvancedOptionPage.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/UnifiedSettings/razor.registration.json
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/VSPackage.resx
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.cs.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.de.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.es.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.fr.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.it.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ja.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ko.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.pl.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.pt-BR.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ru.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.tr.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.zh-Hans.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.zh-Hant.xlf
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorConfigurationServiceTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/RazorFormattingTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/TestRazorFormattingService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorLSPOptionsMonitorTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/LanguageServerTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/Settings/ClientSettingsManagerTest.cs
Fixes: Being nerdsniped by `u/featheredsnake` on Reddit: https://www.reddit.com/r/Blazor/comments/1b47odh/am_i_the_only_one_bothered_that_code_brackets/
VS Code option: https://github.com/dotnet/vscode-csharp/pull/6939
> Add formatting option to force open brace onto the next line after a `@code` or `@functions` block

- Razor.Slim.slnf
- eng/AfterSolutionBuild.targets
- eng/SourceBuild.props
- src/Razor/src/Microsoft.VisualStudio.DevKit.Razor/Microsoft.VisualStudio.DevKit.Razor.csproj
- src/Razor/src/rzls/rzls.csproj
Reapply #9925 but only do it in VMR builds. Additionally, only build the vertical's RID in a vertical build as we won't be able to restore the other apphost packs anyway.
> In VMR builds only build the target RID and don't rebuild

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/FallbackProjectManager.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1980614/
There are scenarios on 17.10p2 where my recent changes to make `FallbackProjectManager` use the dispatcher for project snapshot manager changes can cause a dead lock. The problem occurs when dynamic file info is updated on the dispatcher thread. Roslyn will then call `GetDynamicFileInfoAsync(...)` on the dispatcher thread and block on the result. `GetDynamicFileInfoAsync(...)` calls into `FallbackProjectManager.DynamicFileAddedAsync(...)`, which attempts to make changes to the project snapshot manager using the dispatcher. However, because the dispatcher thread is blocked, it can never make progress to newly queued task and hangs.
This is a small change to `FallbackProjectManager` to apply the project snapshot manager …
> [release/dev17.10] Fix hang on solution close

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSnapshotManagerDispatcher.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/WorkspaceProjectStateChangeDetector.cs
This is a pretty simple change but should reduce deadlocks and improve the performance of running operations on the dispatcher. Essentially, if the current execution path is already running on the dispatcher, new operations can be run inline without starting a task.
In addition, I'm cleaned up and rationalized the `RunAsync(...)` methods a bit.
> Dispatcher should run actions inline if possible

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensBenchmark.cs
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensRangeEndpointBenchmark.cs
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorSemanticTokensScrollingBenchmark.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/RazorCodeDocumentExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlayHints/InlayHintService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/SemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/ICSharpSemanticTokensProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/IRazorSemanticTokenInfoService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/LSPCSharpSemanticTokensProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/RazorSemanticTokensInfoService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticTokensVisitor.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/InlayHints/InlayHintEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokensTest.cs
In order to work in cohosting, and hence OOP, its a lot easier with a couple of relatively simple changes to the semantic tokens service:
1. Use MS.CA.Text types instead of LSP protocol types
2. Extract C# tokens requests to a separate service
This PR does both of those things, and also:
1. Move telemetry reporting out of the service, up into the endpoint
This is targeting the "regress cohosting" branch because it turns out this new design is impossible in cohosting right now 🤦‍♂️
> Update semantic tokens service to better support The Future™

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Microsoft.CodeAnalysis.Razor.Compiler.csproj
This was missed when we unified the dlls and causes failures when using .NET 9p2 in VS.
> Add razorencconfig to Microsoft.CodeAnalysis.Razor.Compiler

- src/Razor/src/Microsoft.VisualStudio.DevKit.Razor/Microsoft.VisualStudio.DevKit.Razor.csproj
- src/Razor/src/rzls/rzls.csproj
Fix razor failures in https://github.com/dotnet/installer/pull/18916
- Explicitly set SelfContained to `false` to address warnings about how the default behavior with RuntimeIdentifier changed in the .NET 8 SDK
- Never append the RID to the output path, even in the build (which now was having it appended because we are specifying a RuntimeIdentifier.
> Fix unified build failures in dependency flow

- .github/policies/resourceManagement.yml
https://github.com/dotnet/razor/pull/9895 was missing the task that removes the untriaged label from issues that get closed or added to a milestone. This restores that automation in the Policy Service configuration.
/cc @phil-allen-msft @JohannesLampel
> Restore automation task to remove the untriaged label

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs
- Another case where we need to fixup owner returned by FindInnermostNode (that replaced previously used LocateOnwer) in RazorCompletionContext
- We were already fixing up cases for start/end element name, but we weren't for attributes
- Previously LocateOwner always gave us MarkupTextLiteral that was a child of the MarkupTagHelperAttribute, but now we get MarkupTagHelperAttribute itself from FindInnermostNode, so we need to add it to the list of exclusions where we don't need to get a parent of the owner
- Similar to what was done in #9455
- 
Fixes:
https://github.com/dotnet/razor/issues/9728
> Fixing TagHelper attribute name completion at attribute name end

- azure-pipelines-official.yml
Backport of https://github.com/dotnet/razor/pull/10038. When merged, should flow automatically also into release/dev17.10.
- Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2401125&view=results
- VS insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/535529
> [17.9] Add official pipeline using 1ES template

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/DisposableAction`1.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/TokenizerBackedParser.cs
This closure allocation was showing up as 0.4% of allocations in devenv in the Completion speedometer test.
﻿*** prior allocations from completion speedometer test ***
> Add DisposableAction that takes in an arg to prevent a closure allocation

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Cohost/CohostProjectSnapshot.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/FilePathNormalizer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/FilePathNormalizingComparer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/FilePathNormalizerTest.cs
Port of https://github.com/dotnet/razor/pull/10050 to a new branch, which is at the point of https://github.com/dotnet/vscode-csharp/commit/bda22d3a7c0accdca813bc32f3afbd3ca35a5850, which is the current version of Razor bits in the `release` branch of the C# extension
@phil-allen-msft
> Port case-sensitivity fixes from main

- azure-pipelines-official.yml
Turns out it is hard to do an insertion without being able to build. This is a cherry-pick of https://github.com/dotnet/razor/pull/10073 into the vscode insertion branch
> Add official pipeline using 1ES template to vscode insertion branch

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/DefaultWindowsRazorProjectHost.cs
Actually, allow the IDE to turn on the ForceRuntimeCodeGeneration flag.
> Ensure we assign 'force runtime code generation' to the correct param

- src/Razor/Directory.Build.props
Before and after dependencies of the nupkg
> Mark analyzers as private assets

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Models/SemanticTokenTypes.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/GetSemanticTokens_Razor_ComponentAttributeAsync.semantic.txt
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/TestFiles/GetSemanticTokens_Razor_ComponentAttribute_DoesntGetABackground.semantic.txt
This pull request solves issue #9376 which highlights the inconsistent capitalization of the string value for the `RazorComponentAttribute` in the `RazorSemanticTokenTypes.cs`. 
These changes will not affect the semantic token recognition in Visual Studio, as an additional case check has been added to the VSlanguageServerClient repo to account for the transition (see [RP](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient/pullrequest/502662)). However, to reflect the capitalization change in VS Code, we will need to [insert Razor into the VS Code C# Extension](https://github.com/dotnet/razor/blob/main/docs/InsertingRazorIntoVSCodeCSharp.md) and update the `package.json` file in the vscode-csharp repo ([this line](https://github.com/dotnet/vscode-csharp/blob/b8ca3132427020cc …
> Fix the capitalizationof razorComponentAttribute

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlayHints/InlayHintService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/InlayHints/InlayHintEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/CSharpTestLspServer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/CSharpTestLspServerHelpers.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/LanguageServerTestBase.cs
Fixes https://github.com/dotnet/razor/issues/10088
> Don't show inlay hints for component attributes

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
1. The Compiler should not be listed as a MEF component.
2. An old assembly was still listed: `Microsoft.AspNetCore.Razor.LanguageSupport`. This was renamed long ago to `Microsoft.AspNetCore.Razor.Utilities.Shared`
> Fix a couple of mistakes in the Razor VSIX manifest

- docs/InsertingRazorIntoVSCodeCSharp.md
- src/Razor/src/Microsoft.VisualStudio.DevKit.Razor/Microsoft.VisualStudio.DevKit.Razor.csproj
- src/Razor/src/rzls/rzls.csproj
@dibarbet removed these packages from the extension in https://github.com/dotnet/vscode-csharp/pull/6983 so I figure there is no point building them
(also, guaranteed I would forget to manually delete them before doing an insertion, and would get build errors 😛)
> Don't build the x86 RID of VS Code bits

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorLanguageServerBenchmarkBase.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.LoggerFactoryWrapper.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Logging/AbstractRazorLoggerFactory.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Logging/RazorLogHubLoggerProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/VisualStudioRazorLoggerFactory.cs
- src/Razor/src/rzls/LoggerFactory.cs
- src/Razor/src/rzls/Program.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Logging/TestOutputLoggerFactory.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/ToolingTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.Editor.Razor.Test/TelemetryReporterTests.cs
Part of #10127
`RazorLoggerFactory` is exported as a MEF part. This change removes that MEF export and exports it from the VS Layer.
> Remove logging MEF export from Workspaces

- src/Razor/src/rzls/rzls.csproj
With this setting, the runtime config will require 8.0.1 to be set. This can cause issues for those without the latest patch installed. Fixes https://github.com/dotnet/razor/issues/10130 
Now the runsettings look like 
```json
{
"runtimeOptions": {
"tfm": "net8.0",
"rollForward": "LatestMajor",
"framework": {
"name": "Microsoft.NETCore.App",
"version": "8.0.0"
},
"configProperties": {
"System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
}
}
}
```
> Disable latest runtime patch

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/IOutOfProcSemanticTokensService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteSemanticTokensService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Constants.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/SemanticTokens/RemoteCSharpSemanticTokensProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/SemanticTokens/RemoteSemanticTokensService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostSemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/OutOfProcSemanticTokensService.cs
One of the items in https://github.com/dotnet/razor/issues/10103
Rather than move telemetry down into the service, I decided to leave it in the endpoint, and C# specific service, so we can track separate telemetry from existing LSP, to make it easier to report on. In theory this is unnecessary because we already would know the status of A/B flights in the telemetry data, but that doesn't allow for manually switching the flag. If people feel strongly about not using different properties, I'm fine to change. Perhaps all of our telemetry should automatically log cohosting and fuse status as properties?
> Bring telemetry back for semantic tokens in cohosting

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/LSPCSharpSemanticTokensProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/IOutOfProcSemanticTokensService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteSemanticTokensService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/SemanticTokens/AbstractRazorSemanticTokensInfoService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/SemanticTokens/ICSharpSemanticTokensProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Constants.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/SemanticTokens/RemoteCSharpSemanticTokensProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/SemanticTokens/RemoteSemanticTokensService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostSemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLSPConstants.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/OutOfProcSemanticTokensService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokensTest.cs
Turns out the code path is the same for OOP, whether precise ranges is on or not :)
One of the items in https://github.com/dotnet/razor/issues/10103
> Remove unnecessary parameter

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/FilePathNormalizer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/FilePathNormalizingComparer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectKey.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteProjectSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/SemanticTokens/RemoteCSharpSemanticTokensProvider.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/DynamicFiles/RazorDynamicFileInfoProvider.cs
- src/Razor/src/Microsoft.VisualStudio.Editor.Razor/ProjectSystem/FallbackProjectManager.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/WorkspaceProjectStateChangeDetector.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/FilePathNormalizerTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/PathUtilities.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackProjectManagerTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/StringExtensions.cs
@toddgrun pointed me to a fair amount of string allocation due `ProjectKey.From(Project)` being called repeatedly on a hot path. To address this, I've added `ProjectKey.Matches(Project)`, which simply compares the current key's `Id` with the project's intermediate output path. This uses a new `FilePathNormalizer.AreDirectoryPathsEquivalent(...)` helper to avoid allocating a new string.
> Fix hot path string allocations from ProjectKey

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
Part of #10127
Now that all `[Export]`s have been removed from Workspaces, we can stop registering it for VS MEF.
> Stop exporting MS.CA.Razor.Workspaces as MEF component

- eng/Versions.props
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/TokenizerLookaheadTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/CSharpCodeParser.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/HtmlMarkupParser.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/TokenizerBackedParser.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ListExtensions.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PooledObjects/PooledArrayBuilder`1.cs
@ToddGrun shared a couple PerfView stacks with me where the Razor compiler was allocating `List<SyntaxToken>` instances in the tokenizer. To remove those allocation, this change replaces `List<SyntaxToken>s` throughout the parsers and tokenizer, and uses `PooledArrayBuilder<SyntaxToken>` instead. In addition, I removed a couple of `Concat` calls and replaced them with pooled `StringBuilders`.
> Use PooledArrayBuilder<SyntaxToken> throughout parsers and tokenizer

- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/DocumentMapping/RemoteDocumentMappingService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Logging/RemoteLoggerFactory.Logger.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Logging/RemoteLoggerFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorServiceFactoryBase.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/SemanticTokens/RazorSemanticTokensInfoService.cs
One of the follow up items in https://github.com/dotnet/razor/issues/10103
I would like to improve this in future a bit, but for now just doing this simple logger will at least get us logs attached to feedback issues, and on our hard drives during development.
> Simple logging in OOP to TraceSource

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Serialization/MessagePack/Formatters/RazorConfigurationFormatter.cs
The recent FUSE changes updated the `RazorConfigurationFormatter` to write serialize/deserialize a new boolean. However, `SerializationFormat.Version` for MessagePack wasn't updated, so it just fails during deserialization when older `project.razor.bin` files are initially read off disk. This tweaks the deserializer to be more forgiving and handle the case that the boolean isn't present.
A similar change is not needed in the JSON serialization because that deserializer was written to be a bit more forgiving and the JSON `SerializationFormat.Version` was updated.
I ran into this when opening an old clone of OrchardCore that I'd opened previously, and started hitting exceptions during message pack deserialization.
> Tweak RazorConfigurationFormatter to account for serialization format change

- build.sh
- eng/Version.Details.xml
- eng/Versions.props
- eng/cibuild.sh
- eng/nuget-workaround.sh
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorRequestExecutionQueue.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/AssemblyCodeBases.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/source.extension.vsixmanifest
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/WebTools.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Microsoft.AspNetCore.Razor.LanguageServer.Test.csproj
Now that https://github.com/dotnet/roslyn/pull/72237 has merged on the Roslyn side, we need to update Razor to consume the source package version.  This will allow us to delete the nuget package version
-
Fixes:
> Switch Razor to using clasp as a source package

- src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/Cohost/CohostSemanticTokensRangeEndpoint.cs
This totally wasn't a problem when CLaSP was a binary dependency, but in newer VS builds cohosting stopped working.
It took me so long to find this, I don't want to talk about it :(
> Fix cohosting

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/FilePathNormalizer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/FilePathNormalizerTest.cs
Fixes https://github.com/dotnet/razor/issues/10192
Seems we were normalizing `\\computername\path` to `//computername/path` which meant it wasn't a network path any more. Now we normalize to `\\computername/path` which seems to work fine 🤷‍♂️
> Make network paths be network paths

- Razor.sln
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Initialization/RemoteClientInitializationService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/TagHelpers/RemoteTagHelperProviderService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/TagHelpers/RemoteTagHelperProviderServiceFactory.cs
Just a couple of tiny little inconsistencies in our OOP services. I think confining ExportProvider usage to the factories makes things much nicer in the services.
The other services already follow this pattern.
> Minor OOP service cleanup

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/FilePathNormalizer.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/WorkspaceProjectStateChangeDetector.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/FilePathNormalizerTest.cs
Not sure whether me or @DustinCampbell broke this, but hit this assert during debugging today. What was happening was:
* WorkspaceProjectStateChangeDetector tried to create a ProjectKey for a Project that had no compilation output assembly path
* `ProjectKey` calls `FilePathNormalizer.GetNormalizedDirectoryName`, passes in `null`, and gets back `/`
* `ProjectKey` then calls `FilePathNormalizer.NormalizeDirectory` on that `/`, which exploded
This fixes the first bullet point, by checking if Roslyn knows about the intermediate output path before continuing. Since this is only checking for project existence, we don't actually need to go further.
This fixes the third point by protecting against a single `/` being written for an input that is only a single `/`
This ignores the second point …
> Fix project load when intermediate output path isn't known

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Properties/launchSettings.json
Who wants to wait for the native debugger on F5 every time? Not me!
> Add launch profiles that don't have native debugging enabled

- Directory.Build.props
- src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace.csproj
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor.CoreComponents/Microsoft.CodeAnalysis.Remote.Razor.CoreComponents.csproj
- src/Razor/src/Microsoft.VisualStudio.DevKit.Razor/Microsoft.VisualStudio.DevKit.Razor.csproj
With the move for rzls to publish net8 binaries, we no longer use our net7 build.  Remove the TFM from our builds (should speed CI builds)
> Stop building no longer shipping net7 build

- .gitignore
- Directory.Build.targets
- eng/cibuild.sh
Issue a warning when `%NUGET_PACKAGES%` doesn't have a trailing slash until the associatede issue is fixed.
https://github.com/dotnet/roslyn/issues/72657
> Warn on invalid NuGet configuration

- Directory.Packages.props
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Microsoft.VisualStudio.Razor.IntegrationTests.csproj
Add direct reference to xunit.runner.utility
On at least some machines, it appears that running integration tests fails near startup because xunit.runner.utility.*.dll cannot be found.  Adding the direct reference fixes the issue.
> Add direct reference to xunit.runner.utility

- SpellingExclusions.dic
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Logging/ILoggerExtensions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/IProjectWorkspaceStateGenerator.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectWorkspaceStateGenerator.TestAccessor.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectWorkspaceStateGenerator.UpdateItem.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectWorkspaceStateGenerator.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VsSolutionUpdatesProjectSnapshotChangeTrigger.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/WorkspaceProjectStateChangeDetector.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/TestProjectWorkspaceStateGenerator.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectWorkspaceStateGeneratorTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/VsSolutionUpdatesProjectSnapshotChangeTriggerTest.cs
The primary goal of this change is to remove the `ProjectSnapshotManagerDispatcher` from `ProjectWorkspaceStateGenerator`, which was only used to synchronize access to the dictionary it uses to track updates. While doing this, I've significantly refactored the code with the following goals:
1. Don't create linked `CancellationTokenSources` to an external `CancellationToken`. This was used by `VsSolutionUpdatesProjectSnapshotChangeTrigger` to cancel all updates when the solution is closed. However, that's a pretty subtle mechanism and it's easy enough to just add a `CancelUpdates` method.
2. Ensure that the dictionary of updates is cleared when updates are cancelled. Otherwise, we risk holding onto Roslyn solution snapshots that are no longer valid.
3. Use the test accessor pattern to …
> Remove ProjectSnapshotManagerDispatcher from ProjectWorkspaceStateGenerator

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.json
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/html.tmLanguage.json
Update razor textmate grammar so that razor expressions inside html tags are classified correctly
- copied over the textmate grammar from the vscode-csharp repo. For testing and justification see dotnet/vscode-csharp#7051 and dotnet/vscode-csharp#7055
> update razor textmate grammar

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointDelegationTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs
RenameEndpoint takes a `ProjectSnapshotManagerDispatcher` in order to call `IProjectSnapshotManager.GetProjects()`. However, that method is thread-safe, thanks to @ryzngard's work in #8943. So, this use of `ProjectSnapshotManagerDispatcher` can be removed.
> Remove ProjectSnapshotManagerDispatcher from RenameEndpoint

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultRazorComponentSearchEngine.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentPresentation/TextDocumentUriPresentationEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorComponentSearchEngine.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/IDocumentSnapshotExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RazorCodeDocumentExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/TagHelperDescriptorExtensions.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentPresentation/TextDocumentUriPresentationEndpointTests.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/LanguageServerTestBase.cs
As part of moving the Uri presentation endpoint to cohosting, I needed to do this, and thought it would be easier to review separately.
> Extract component search engine method to extension

- src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Test.csproj
This made it so devkit in vscode at least had no errors. Command line builds are still failing but this unblocks me
> Include arm64 for source gen test

- Directory.Packages.props
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Microsoft.VisualStudio.Razor.IntegrationTests.csproj
Restores the reference to `xunit.runners.visualstudio` that was inadvertently lost when moving to CPM.
Run is happening now, but signs are positive:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9450237
> Get integration tests running again

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeDocumentReferenceHolder.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsPublisher.Comparer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsPublisher.TestAccessor.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsPublisher.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/GeneratedDocumentPublisher.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/GeneratedDocumentSynchronizer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IDocumentProcessedListener.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/OpenDocumentGenerator.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeDocumentReferenceHolderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsPublisherTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/GeneratedDocumentPublisherTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/GeneratedDocumentSynchronizerTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/OpenDocumentGeneratorTest.cs
This is a more significant change that removes usage of `ProjectSnapshotManagerDispatcher` from all "document processed listeners". As part of this work, I've re-worked the `RazorDiagnosticsPublisher` to use an `AsyncBatchingWorkQueue` and `Task.Delay` rather than a pair of timers. The result is a much simpler for implementation of `RazorDiagnosticsPublisher`.
> Remove ProjectSnapshotManagerDispatcher from all "document processed listeners"

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/IRazorFileChangeListener.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.TestAccessor.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetectorManager.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileSynchronizer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorInitializedEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileChangeDetectorManagerTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileChangeDetectorTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileSynchronizerTest.cs
This change removes usage of `ProjectSnapshotManagerDispatcher` from `RazorFileChangeDetector`. In order to achieve that, I've refactored `RazorFileChangeDetector` to use an `AsyncBatchingWorkQueue` rather than the existing complex strategy of tracking a dictionary of "pending notifications" with delayed tasks. However, the `ProcessBatchAsync` is a bit trickier than others I've implemented.
To reduce churn on the `RazorProjectService`, `RazorFileChangeDetector` does extra work to try and avoid elide adds/remove pairs for the same file. This makes the `ProcessBatchAsync` more complex because we need to pass through the items in the batch once to find add/remove pairs and make note of the changes we should skip. Then, we make a second pass and notify the listeners of changes, taking care to …
> Remove ProjectSnapshotManagerDispatcher from RazorFileChangeDetector

- SpellingExclusions.dic
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeEventArgs.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.Comparer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.TestAccessor.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/MonitorProjectConfigurationFilePathEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MonitorProjectConfigurationFilePathEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationFileChangeDetectorTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationFileChangeEventArgsTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationStateSynchronizerTest.cs
This change removes `ProjectSnapshotManagerDispatcher` usage from `ProjectConfigurationStateSynchronizer` and `ProjectConfigurationFileChangeDetector`. Ultimately, a lot of this code will go away once #10173 is the default behavior.
As part of this change, I updated `ProjectConfigurationStateSynchronizer` to use an `AsyncBatchingWorkQueue`. In my opinion, this is a huge improvement over the previous implementation.
> Remove ProjectSnapshotManagerDispatcher from ProjectConfigurationStateSynchronizer

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/RazorConstants.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs
Register the UI context for Razor, so it can be used in Roslyn (see https://github.com/dotnet/roslyn/pull/73172)
Will eventual fix https://github.com/dotnet/razor/issues/10279 once the Roslyn side is in
> Register UI context for cohost activation

- azure-pipelines-official.yml
Fixes a warning in official builds:
<samp>
##[warning]DropRetentionDays not set. Defaulting to 10 years (3650 days). Please reduce drop retention period to 30 days if possible.
</samp>
<p>
I'm not sure what value to replace 10 years with - the drop is inserted into VS (and if it ends up in VS release branch I presume it's still used for releasing) so probably shouldn't live too shortly. I chose 90 days as that's the example in https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/outputs/microbuild-vsts-drop?tabs=inlinetask.
Official build run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2435732&view=results
> Lower drop retention from 10 years to 3 months

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_MapCode.cs
This causes the mapcode edits returned from C# and Razor to no longer be empty.
But still the resulting edit is wrong.
So there is more work to do.
Contributes to #10040
> Fixes broken mapcode LSP flow from razor to c#

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectWorkspaceStateGenerator.cs
This reverts commit d76f5c59d9892b4c05e8291bb72578a869ecdf5d, humorously entitled "Check correct CancellationToken". Sorry @DustinCampbell 😁
What was happening was that when a project change was queued up, we cancelled any previous work that was in play. This used to check the disposal cancellation token, so we didn't try to release a semaphore that was disposed. The change to use the passed in cancellation token meant we never released the semaphore.
> Fix integration tests, and razor, by using the correct cancellation token

- eng/pipelines/test-integration-job.yml
- eng/scripts/CreateVSHive.ps1
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectWorkspaceStateGenerator.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Logging/TestOutputLogger.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Logging/TestOutputLoggerProvider.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/OutputInProcess.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/LogIntegrationTestAttribute.cs
This PR:
* Re-enables logging to test output for integration tests
* Increases the log level of all logging during integration tests
* Actually deploys Razor to the experimental hive so we're testing Razor main on VS main
* Previously, without that change, we were testing using the integration test source from main, against whatever bits were inserted in VS main. This seemed odd to me, but if anyone thinks that is a desired test scenario let me know. It does explain a couple of failures I remember seeing ages ago, which was the reason I had backed out the logging in the first place
* Output VS version info to the pipeline logs
> More integration test work

- eng/scripts/featureflag.ps1
It was tedious to get the actual argument right, so this checks for multiple forms and tries to correct them. 
The following should be supported now: 
`eng\scripts\featureflag.ps1 -set -flag Razor.LSP.ForceRuntimeCodeGeneration -enable`
`eng\scripts\featureflag.ps1 -set -flag Razor\LSP\ForceRuntimeCodeGeneration -enable`
`eng\scripts\featureflag.ps1 -set -flag FeatureFlags.Razor.LSP.ForceRuntimeCodeGeneration -enable`
`eng\scripts\featureflag.ps1 -set -flag FeatureFlags\Razor\LSP\ForceRuntimeCodeGeneration -enable`
This should make copying the value from code easier to figure out. We could also just assume feature flags start with `FeatureFlags\LSP\Razor\<flagname>` but that's not inherantly true, just happens to be for now.
> Allow multiple forms for the featureflag script

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/ProjectInfoEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Serialization/IRazorProjectInfoDeserializer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Serialization/RazorProjectInfoDeserializer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/IProjectSnapshotExtensions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/ProjectSystem/RazorProjectInfoEndpointPublisher.TestAccessor.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/ProjectSystem/RazorProjectInfoEndpointPublisher.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/ProjectSystem/RazorProjectInfoEndpointPublisherTest.cs
Unit tests for RazorProjectInfoEndpointPublisher
- Based on tests for RazorProjectInfoPublisher
- Excludes tests that didn't make sense for the endpoint-based code (e.g. filename scenarios, etc.)
> Unit tests for RazorProjectInfoEndpointPublisher

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/WorkspaceProjectStateChangeDetector.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/WorkspaceProjectStateChangeDetectorTest.cs
Fixes #10295
`WorkspaceProjectStateChangeDetector` tests were taking an extra long time to run because they didn't specify a faster delay `TimeSpan` to the detector's `AsyncBatchingWorkQueue`.
> Allow tests to specify delay for WorkspaceProjectStateChangeDetector

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractIntegrationTest.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/OutputInProcess.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Microsoft.VisualStudio.Razor.IntegrationTests.csproj
* Reference the razor extension from the integration test project, so that making a code change and running a test from Test Explorer actually causes the new code to be tested
* Manually initialize the `ThrowingTraceListener` because it seems the module initializer doesn't work with our wacky test infra (and I choose not to try to understand the latter :P)
* Up the log level of the test logger, so the Text Explorer output includes the full logs of the test run
> Minor improvements to integration tests

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_UpdateCSharpBuffer.cs
Seems like timing changes in the system have resulted in us recieving generated C# for miscellaneous project files, so we're hitting this assert more often now. Removing it doesn't seem to have any noticable effects, we get the right C# content for the right projects soon after, as the server loads information.
> Convert assert to a log message

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/CodeGeneration/DesignTimeNodeWriterTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/CodeWriterExtensions.cs
Move windows path remapping later in the process so that path comparisons for source mappings are unaffected
Fixes https://github.com/dotnet/razor/issues/10263
> Fix source mappings not appearing in fuse:

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/IRazorProjectService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileSynchronizer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultRazorComponentSearchEngineTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileSynchronizerTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorProjectServiceTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestRazorProjectService.cs
Fixes https://github.com/dotnet/razor/issues/9986
The issue at heart here is a race condition between our two project systems (one in the server, one in VS) and how they deal with/find new Razor files. What was happening was that the LSP server was discovering the newly named file, finding a project that it could fit in (based on path) and adding it to that project. It then starts generating C# code for that file, and sending it to VS. Meanwhile VS is discovering that same new file at its own pace, via CPS events etc., and adding the file to the project. VS then tells the LSP server about the new file, via project.razor.vs.bin, and all is right with the world. The problem comes when the LSP server sends generated C# to VS, before VS knows about the new file, but the server doesn't know …
> Don't try to find "potential" projects for newly created .razor files

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/ProjectSystem/RazorProjectInfo.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.Test/ArgHelperTests.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.Test/Microsoft.AspNetCore.Razor.Utilities.Shared.Test.csproj
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.Test/PooledArrayBufferWriterTests.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ArgHelper.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PooledArrayBufferWriter`1.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/SR.resx
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.cs.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.de.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.es.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.fr.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.it.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.ja.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.ko.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.pl.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.pt-BR.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.ru.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.tr.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.zh-Hans.xlf
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Resources/xlf/SR.zh-Hant.xlf
This change introduces a couple of helper utilities into MS.ANC.Razor.Utilities.Shared. Most notably, I've introduced an `ArgHelper` type that can be used for argument validation. This is analogous to the various `ArgumentNullException.Throw*`, `ArgumentException.Throw*`, and `ArgumentOutOfRangeException.Throw*` APIs that were added in .NET 8+. In addition, I've included `PooledArrayBufferWriter<T>`, which is a use implementation of `IBufferWriter<T>` that uses shared array pools.
> Add some helper utilities

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorLanguageServerBenchmarkBase.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.LoggerFactoryWrapper.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Logging/AbstractLoggerFactory.AggregateLogger.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Logging/AbstractLoggerFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Logging/LoggerProviderMetadata.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Logging/RazorLogHubLogger.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Logging/RazorLogHubLoggerProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/ActivityLogLoggerProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/ExportLoggerProviderAttribute.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/MemoryLoggerProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/OutputWindowLoggerProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/VisualStudioLoggerFactory.cs
- src/Razor/src/rzls/LoggerFactory.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Logging/TestOutputLoggerFactory.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/DictionaryExtensions.cs
Fixes #10326
This change makes our `AbstractLoggerFactory` take a set of `Lazy<ILoggerProvider>` instances and only realize them the first time a message is logged.
🤔 _I wonder if it would be possible to change our `ILoggerProvider` instances to declare their minimum `LogLevel` via MEF and import that as metadata? That would allow us to avoid instantiating all the logger providers just to call `IsEnabled`._
> Lazily import ILoggerProviders

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Debugging/DefaultLSPBreakpointSpanProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Debugging/DefaultLSPProximityExpressionsProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/VSTelemetryReporter.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Editor_NetFx/TestTelemetryReporter.cs
Awhile back, a few MEF components were changed to import ILoggerFactory lazily in order to avoid extra image loads for MS.Ext.Logging. However, that shouldn't be an issue anymore for two reasons:
1. We don't rely on that logging implementation anymore.
2. Our logging implementation is already lazy and does not force MEF components to be created until the first time a message is logged.
> Stop importing ILoggerFactory lazily

- eng/targets/Services.props
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentPresentation/TextDocumentUriPresentationEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentPresentation/UriPresentationHelper.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteUriPresentationService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RazorServices.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/SemanticTokens/RemoteSemanticTokensService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/UriPresentation/RemoteUriPresentationService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/UriPresentation/RemoteUriPresentationServiceFactory.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostUriPresentationEndpoint.cs
This enables the Uri Presentation endpoint in cohosting, which is used when draging and dropping a file only a Razor document, and handles placing a Razor component tag in the document. It's part 1 because part 2 involves calling out to Web Tools to allow the Html language server to do the same, but I haven't done that bit yet. No point reviewing it all in one huge lump though.
This is also a reasonable "bare minimum" changes necessary to create a new cohost endpoint and service.
> UriPresentation to Cohost/OOP, Part 1

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/OpenDocumentGenerator.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeEventArgs.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.Comparer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationStateSynchronizer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/IRazorProjectService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectKey.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/OpenDocumentGeneratorTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/ProjectConfigurationStateSynchronizerTest.cs
Fixes https://github.com/dotnet/razor/issues/10306
This change takes a different approach than https://github.com/dotnet/razor/pull/10308 and https://github.com/dotnet/razor/pull/10330 and https://github.com/dotnet/razor/pull/10332 because life was meant to be interesting.
The original problem we were trying to solve is that when a Reset then Add came in, we would migrate all of the documents out of the project, then migrate them all back in again. The various solutions in the other PRs you can read about at your leisure, this one takes a rather simple approach:
1. Ignore everything but the most recent update for a specific project
2. If we need to update a project, but it doesn't exist, add it
In the long run we should remove `IRazorProjectService.AddProjectAsync` entirely, and rename …
> YAPCSSF: Automatically add projects if they don't exist when updating

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/OpenDocumentGeneratorTest.cs
With recent changes, this is unnecessary because a document add event will do the same job, but better.
> Minor RazorProjectService cleanup

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectWorkspaceStateGenerator.UpdateItem.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectWorkspaceStateGenerator.cs
This change should address issues in ProjectWorkspaceStateGenerator where update cancellation was tied to the base IDisposable implementation in a complex way. This could cause exceptions to be thrown unnecessarily if the generator is disposed while an update is in flight. Now we just track a boolean field as we did in the past.
Validation PR to determine impact: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/549802
> Don't use CancellationTokenSource for disposal

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorProjectServiceTest.cs
Fixes an issue Andrew found in speedometer tests. When opening files and modifying them, before we migrate the document to the "real" project, things get out of sync.
Also matches some stacks on PRISM, but I think this bug was only introduced in the last two weeks, so I don't think its the only cause thats for sure.
> Fix disco colors when modifying documents during project load

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostUriPresentationEndpoint.cs
There's a long discussion about this, but it turns out that CLaSP relies on MEF metadata that exposes System.Types. This means that MEF must load assemblies in order to produce metadata. Recently, one of our co-hosting endpoints unintentionally pulled in Microsoft.CodeAnalysis.Razor.Workspaces by using a protocol type from MS.CA.Razor.Workspaces as generic type argument. Since, CLaSP loads the type, it had to additionally load MS.CA.Razor.Workspaces to satisfy the generic argument.
The fix is easy -- just don't use that protocol type. However, that's not sustainable and this change has started a conversation about potential re-architecture to CLaSP to avoid eagerly loading assemblies.
> Avoid image load due to co-hosting and CLaSP

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/DirectiveVerifier.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveCompletionItemProviderTest.cs
- using directive was erroneously excluded from Razor components
- this PR makes it available
Fixes:
Internally filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1992434?src=WorkItemMention&src-action=artifact_link
> using directive should be available in Razor components

- .github/CODEOWNERS
- eng/Version.Details.xml
- eng/Versions.props
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentPresentation/TextDocumentUriPresentationEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentPresentation/UriPresentationHelper.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/HtmlDocuments/RemoteHtmlDocumentService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/UriPresentation/RemoteUriPresentationService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostUriPresentationEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentPublisher.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentResult.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentSynchronizer.RazorDocumentVersion.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentSynchronizer.SynchronizationRequest.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentSynchronizer.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/IHtmlDocumentPublisher.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/IHtmlDocumentSynchronizer.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/HtmlDocumentSynchronizerTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/RazorCustomMessageTargetTest.cs
Commit at a time might be easier. Not really sure.
This PR finished off Uri Presentation in cohosting, but more importantly it brings html document generation to cohosting. The generation is done completely on-demand as we get a request for a document, and in general is much simpler than the current system, because whilst we still need to push the document to a VS buffer, we don't have to wait for the document to be pushed to VS from the LSP server, and synchronize those two pushes. This isn't doing any buffer management specifically for cohosting yet, but all of that is still needed for C# anyway, at the moment.
> Uri Presentation Part 2, aka Cohost Html on-demand generation

- src/Razor/src/rzls/Targets/Microsoft.NET.Sdk.Razor.DesignTime.targets
- src/Razor/src/rzls/Targets/Readme.md
- src/Razor/src/rzls/Targets/Rules/RazorComponentWithTargetPath.xaml
- src/Razor/src/rzls/Targets/Rules/RazorConfiguration.xaml
- src/Razor/src/rzls/Targets/Rules/RazorExtension.xaml
- src/Razor/src/rzls/Targets/Rules/RazorGeneral.xaml
- src/Razor/src/rzls/Targets/Rules/RazorGenerateWithTargetPath.xaml
- src/Razor/src/rzls/rzls.csproj
Part of fixing https://github.com/dotnet/razor/issues/10351 
Copied build targets to the razor repo so they can be shipped by us and used in vs code
> Add design time targets to the razor repo

- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Logging/RemoteLoggerFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/MEFComposition.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorServiceFactoryBase.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteMefComposition.cs
Remember when I said things like "ServiceHub and ALCs are weird!"? Well it turns out I just forgot how .NET worked for a minute, and accidentally created a static field in a generic type, which of course meant we were creating a MEF composition per service.
Hopefully my shame is punishment enough.
Also made everything log to the same trace source, like I originally intended, and did a minor bit of cleanup.
> Fix OOP service lifetimes

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteClientProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteServiceProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostLinkedEditingRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostSemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostUriPresentationEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentPublisher.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/OutOfProcTagHelperResolver.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteClientProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteServiceProvider.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Remote/OutOfProcTagHelperResolverTest.TestResolver.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Remote/OutOfProcTagHelperResolverTest.cs
This makes our OOP services a bit easier to call, removes a bit of boiler plate, and fixes a bug where we could be overly chatty and send multiple initialization calls if a .razor document is restored from a previous VS session.
> Simplify OOP service call API

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/VSPackage.resx
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.cs.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.de.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.es.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.fr.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.it.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ja.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ko.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.pl.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.pt-BR.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.ru.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.tr.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.zh-Hans.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/VSPackage.zh-Hant.xlf
This fixes VS bug 2057011 ([Internal Link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2057011)). Changing the setting text for advanced razor setting from title case to sentence case to adhere to the DevDiv guidlines ([Internal Link](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/38111/Guide-for-setting-owners?anchor=titles)).
> Razor advanced setting text: title case to sentence case

- src/Razor/src/.editorconfig
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LiveShare/Host/ProjectSnapshotManagerProxy.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/VisualStudioWindowsLogHubTraceProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectWorkspaceStateGenerator.cs
Yesterday when I hit the `SemaphoreSlim` et al banning, I suppressed in an editorconfig file, without thinking too much. That was a mistake though, as it bans the entire BannedApiAnalyzer. This PR just suppresses the few spots we use SemaphoreSlim. Still not ideal to do it for the whole file, but I thought it was better than suppressing at every individual call site. If you disagree, let me know.
I did puth the suppression below the class definition at least, so our MEF related bannings still work.
> Suppress less

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/EditorDocumentManagerListener.TestAccessor.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/EditorDocumentManagerListener.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Documents/EditorDocumentManagerListenerTest.cs
Fixes https://github.com/dotnet/razor/issues/10395
Before this change, loading OrchardCode on my machine does 1479 switches to the main thread, after this change it does 2 or 3, depending on timing. Batching updates to the project manager, or notifications for multiple documents at a time, could not have solved this scenario per se, as we get the initial notifications through Roslyn, one file at a time. That means we could either batch them in the `IDynamicFileInfoProvider` and do the work to rearchitect the project snapshot manager, so batching them in the listener instead made the most sense.
I've kicked off a validation insertion to get Speedometer numbers, should be ready in the morning (my time)
> Switch `EditorDocumentManagerListener` to an async batching work queue

- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/HtmlDocuments/RemoteHtmlDocumentService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Initialization/RemoteClientInitializationService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/LinkedEditingRange/RemoteLinkedEditingRangeService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/DocumentSnapshotFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteDocumentContext.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorDocumentServiceBase.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorServiceBase.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/SemanticTokens/RemoteSemanticTokensService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/TagHelpers/RemoteTagHelperProviderService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/UriPresentation/RemoteUriPresentationService.cs
Previously @alexgav created some helper methods to get document info in OOP services, but it ended up being a little bit of an odd API to use if you needed to access multiple things. You'd either have to make multiple calls to get things, and end up looking up things in the solution multiple times etc., or have single methods that returned an arbitrary tuple of multiple things.
It occurred to me while doing the folding range work that `DocumentContext` was designed to hold all of these concepts together, so we could just use that, and use the single `CreateDocumentContext` method that Alex had already added. It then further occured to me that if we did that by wrapping `RazorBrokeredServiceImplementation.RunServiceAsync` then each service could just have a method that takes a document …
> Simplify OOP services

- azure-pipelines-official.yml
The new version of the powershell script will not place the creds in the nuget.config file, instead it will use standard environment variables. Update the YAML file to use NuGetAuthenticate to avoid a build break that may happen if the credential provider is not available.
> Call NuGetAuthenticate after SetupNuGetSources

- azure-pipelines-official.yml
I've heard in https://github.com/dotnet/fsharp/issues/17265 that this will be required.
Official build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2466301&view=results
> Enable 1ES's SBOM generation

- src/Razor/src/Microsoft.VisualStudio.DevKit.Razor/Microsoft.VisualStudio.DevKit.Razor.csproj
The way we use the nupkg is to restore _all_ required bits in a single package to unpack in the repo. This fixes our devkit package to include the telemetry dll so it will work when restored and unpacked.
> Fix DevKit nupkg to include all dlls needed

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/RazorVSInternalCodeAction.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/CompletionListMerger.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/CodeActions/FormatNewFileParams.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/CodeActions/SimplifyMethodParams.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/CodeActions/VSCodeActionParams.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/JsonHelpers.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_CodeActions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_Completion.cs
Due to our custom message target stuff, which lives in the LSP client, there are a couple of places where we rely on knowing exactly what serializer our delegated servers (ie, Roslyn and Web Tools) are using in order to process their responses. This effectively blocks them from moving to System.Text.Json, as they'd break us. This PR is an attempt for us to be resilient to one of them moving to System.Text.Json, so that hopefully we can all do it without dual or triple insertions.
Testing is sadly manual (chicken and egg, Roslyn hasn't moved to STJ so can't test in CI, but Roslyn can't move until this is done) but basic functionality works, and code actions and completion are the only two things I can think of where we need to inspect json objects directly, so I'm hoping that anything else …
> Allow delegated servers to use either System.Text.Json or Newtonsoft.Json

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/RazorCSharpStatementKeywordFoldingProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Folding/FoldingEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/10443
> Fold C# statement keyword blocks

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/MiscFilesHostProject.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Tooltip/TagHelperTooltipFactoryBase.cs
Fixes the integration tests. I guess this was always a bit broken, but we got lucky because misc files project wasn't added up front? But I would have thought we would have noticed earlier.... 🤷‍♂️
> Don't show misc files project in hover info

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Folding/FoldingRangeEndpoint.cs
Part of fixing https://github.com/dotnet/razor/issues/9492 along with https://github.com/dotnet/roslyn/pull/74069
The change here is to just change the properties we want to change, and let everything else flow through from Roslyn, rather than being so opinionated.
> Preserve properties on the folding ranges we return

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.cs
I thought tackling https://github.com/dotnet/razor/issues/6955 might be a good use of a Thursday night, and help paint a clearer picture for cohosting, and then I found that OnAutoInsert was really the only offender that would actually impact cohosting, so I just cleaned it up a bit instead.
> Don't use GetRequiredService in the OnAutoInsert endpoint

- azure-pipelines-official.yml
There is no flow from runtime to this repo, and the SAS variables are going away.
> Remove support for internal runtime downloads

- azure-pipelines-official.yml
There is no flow from runtime to this repo, and the SAS variables are going away.
> [release/dev17.9] Remove support for internal runtime downloads

- azure-pipelines-official.yml
There is no flow from runtime to this repo, and the SAS variables are going away.
> [release/dev17.10] Remove support for internal runtime downloads

- azure-pipelines-official.yml
There is no flow from runtime to this repo, and the SAS variables are going away.
> [release/dev17.11] Remove support for internal runtime downloads

- src/Razor/src/rzls/rzls.csproj
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2088486
Seems this was inadvertently removed in https://github.com/dotnet/razor/pull/10453
@ryzngard I'm pretty out of my depth here about what is required, but a local build of rzls with this change does fix the problem. Are there any other project properties that might be important, that I should bring back?
> Add back roll forward to rzls

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
We don't need to (and shouldn't) specify AllCommitCharacters in capabilities for our completion endpoint. Doing so causes them to always be added to all completion items.
-
Since we are using our completion endoint for VSCode now, it was causing undesirable behavior there. VSCode HTML doesn't use ">"  as the commit character, and having it specified in server capabilities was causing us to always use ":", ">", " ", and "=" as the commit characters for all items.
Fixes:
https://github.com/microsoft/vscode/issues/217772
> Fixing completion commit chars

- src/Razor/src/rzls/rzls.csproj
Should fix sourcebuild for sdk insertion I think???
> Don't use runtime identifiers in sourcebuild

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/DefaultRazorTagHelperContextDiscoveryPhase.cs
Noticed in customer trace, ~35% of allocations over a nearly two minute period are in razor's sourcegenerator's call to the TagHelperDirectiveVisitor.
As the DirectiveVisitor construction and usage are scoped to the calling method (DefaultRazorTagHelperContextDiscoveryPhase.ExecuteCore), it's easy enough to make the DirectiveVisitor disposable and to make the DirectiveVisitor use a pooled array for it's TagHelperDescriptor array.
*** from the customer trace ***
> Reduce allocations in Razor's DirectiveVisitor

- azure-pipelines-official.yml
- eng/TSAConfig.gdntsa
Should unblock official builds broken with BinSkim errors.
Official build of this PR: https://dev.azure.com/dnceng/internal/_build/results?buildId=2482768&view=results
> Enable TSA

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentSymbols/DocumentSymbolEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentHighlighting/DocumentHighlightEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentSymbols/DocumentSymbolEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/HoverServiceTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/MapCode/MapCodeTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Semantic/SemanticTokensTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.TestLanguageServer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/CSharpTestLspServerHelpers.cs
Our custom message target currently returns `SumType<DocumentSymbol[], SymbolInformation[]>?` but our endpoint blindly assumes `SymbolInformation[]?` is the return type. This is a bad thing because Roslyn can return either type, based on a client capability, and even the spec notes:
> Servers should whenever possible return [DocumentSymbol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentSymbol) since it is the richer data structure.
This PR adds support for `DocumentSymbol` to our langauge server, and tests that cover both possible result types.
> Support `DocumentSymbol` results from Roslyn

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentPresentation/AbstractTextDocumentPresentationEndpointBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentPresentation/TextDocumentTextPresentationEndpointTests.cs
As discussed offline, Roslyn doesn't support the Uri or Text presentation endpoints, and recent LSP client changes have caused erroneous failure telemetry to be logged as a result. This PR fixes that by just not calling Roslyn.
> Don't call C# for Uri or Text presentation

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LspEditorFeatureDetector.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/WellKnownFeatureFlagNames.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LspEditorFeatureDetectorTest.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
AFAIK it was introduced for new LSP editor rollout several years ago before we had Tools/Options/HTML Editor/Advanced/Use legacy Razor Editor option. Now that rollout is over, and there is a public non-preview mechanism for users to switch to the old editor if needed, the feature flag is no longer necessary and creates confusion (and extra code to test/maintain).
-Removing unnecessary Razor Legacy Editor feature flag
Fixes:
Removes redundant way to (internally only) enable legacy Razor editor
> Removing unnecessary Razor Legacy Editor feature flag

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/AddUsingsCodeActionProviderHelper.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/CSharpCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/TypeAccessibilityCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/UnformattedRemappingCSharpCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionResolveEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Html/DefaultHtmlCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Html/DefaultHtmlCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Html/HtmlCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/AddUsingsCodeActionParams.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/CodeActionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/CreateComponentCodeActionParams.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/GenerateMethodCodeActionParams.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/RazorCodeActionResolutionParams.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/RazorVSInternalCodeAction.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/AddUsingsCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/CodeBlockService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/CreateComponentCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/GenerateMethodCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/GenerateMethodCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/RazorCodeActionContext.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingUtilities.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/TypeAccessibilityCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ComponentAccessibilityCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionProviderTest.cs
This PR is a style-only clean up of our code actions handlers and related code. Definitely could have gone further (more collection pooling, returning concrete types etc.) but I wanted to try to have it serve as an indication for what we consider our current idiomatic coding style* and to avoid conflicts with the extract to component work.
<sub>* Current style is subject to change at any time, and are not well documented. To quote a great Australian film, [it's just the vibe](https://www.youtube.com/watch?v=nMuh33BMZYY).</sub>
> Clean up code actions code

- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/IBrokeredServiceInterceptor.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorServiceBase.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostLinkedEditingRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteServiceProvider.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/ToolingTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostLinkedEditingRangeTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/InterceptingServiceBroker.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/ShortCircuitingRemoteServiceProvider.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/TestTraceSourceProvider.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Microsoft.VisualStudio.LanguageServices.Razor.Test.csproj
Finally some cohosting tests! Some people would say that I'm being lazy in adding tests for the simplest endpoint we have. Those people have a point.
The test infra here almost entirely avoids ServiceHub, and certainly avoids the Roslyn solution sync mechanism, but it _does_ use our real services and service factories, including the OOP services' separate MEF composition, so the services themselves are partying on a real Roslyn (test) solution and are using real implementations of all of their dependencies.
Things not covered by this test infra yet:
* OOP initialization
* Adding generated C# files to the Roslyn solution (IDynamicFile does this in real life)
* Dealing with Html documents in any way
Future PRs to add tests for more …
> Add tests for the cohost linked editing range endpoint

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/RazorPackage.cs
While self-hosting I noticed unified settings were no longer available and were defaulting back to the classic experience. Looks like they updated how some of the registration works and added a fix for f5 debugging them. Worked locally on my machine but I will not claim any expertise here.
> Fix unified settings

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/RazorLSPTextViewConnectionListener.cs
- The constructors of MEF parts must be free threaded
- Get `IVsTextManager4` on demand, rather than in the constructor of `RazorLSPTextViewConnectionListener`
- This removes UI thread dependency, and allows Razor to be loaded asynchronously on solution restore, reducing UI delay on startup.
Fixes:
#10592
> Avoid UI thread dependency in the constructor

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/TagHelperCompletionProvider.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperCompletionProviderTest.cs
In empty document completion context will have RazorDocumentSyntax as Owner. RazorDoucmentSyntax has null as the parent, which makes sense. However compiler thinks we can't have a null here, while obviously we do.
I'm adding a null check and a test for this case. We would probably further discuss the implications here. I tried to track down how we get null in a non-nullable field, but it's a bit confusing since the class gets generated.
- Fix NRE thrown if completion is invoked in an empty razor document
> Fix NRE when invoking completion in empty document

- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostLinkedEditingRangeEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/ServiceFactoryMap.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/TestRemoteServiceProvider.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/TestServiceBroker.cs
> Add tests for cohosting linked editing range that use real components

- src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/RazorWorkspaceListenerBase.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/StreamExtensions.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.ProjectEngineHost.Test/StreamExtensionTests.cs
When reading RazorProjectInfo from a stream the array being used was a pooled array. The code was not correctly trimming that array for the deserializer which meant that unknown bytes were being attempted to be read and were likely wrong. This fixes the code to make sure and trim before deserializing and adds tests. 
Fixes [AB#2137098](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2137098)
> Fix project info reading

- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.Test/ImmutableArrayExtensionsTests.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ImmutableArrayExtensions.cs
This change introduces four sets of extension methods with overloads:
- OrderAsArray(...)
- OrderDescendingAsArray(...)
- OrderByAsArray(...)
- OrderByDescendingAsArray(...)
Each of these operates on an `ImmutableArray<T>` and returns an `ImmutableArray<T>`.
> Add ImmutableArray extension methods for ordering

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/CodeGeneration/CSharpCodeWriterTest.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/CodeGeneration/DesignTimeNodeWriterTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/CodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/DefaultCodeRenderingContext.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/DefaultDocumentWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/RazorHtmlWriter.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Language/CodeGeneration/TestCodeRenderingContext.cs
These allocations are present in a customer trace I'm looking at, accounting for 1.4% of allocations in the VS process (around 100 MB).
The owner of the CodeWriter is already disposable, so making the CodeWriter disposable is trivial, and allows for all ReadOnlyMemory<char> pages added to _pages to be released back to a pool.
*** Customer trace ***
*** local trace WITHOUT changes opening OrchardCore ***
*** local trace WITH changes opening OrchardCore ***
> Pool CodeWriter ReadOnlyMemory<char> pages

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/AsyncBatchingWorkQueue`2.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/RazorActivityLog.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/VisualStudio_NetFx/VsMocks.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LspEditorFeatureDetectorTest.cs
It turns out that an old bug and some recent changes were causing `MS.VS.LanguageService.Razor.Test` unit tests to fail intermittently.
1. I made a mistake when porting `AsyncBatchingWorkQueue` from Roslyn that would cause an exception to be thrown if an `OperationCanceledException` was thrown during batch processing.
2. `RazorActivityLog` would switch to the main thread when processing a batch of messages. However, this is unnecessary, since `IVsActivityLog` is supposed to a be a thread-safe VS service.
3. `RazorActivityLog` didn't check its cancellation token while processing a batch of messages. This is problematic because it would continue logging messages after `RazorActivityLog` was disposed.
4. The `IAsyncServiceProvider` mock passed to `RazorActivityLog` didn't implement …
> Fix Visual Studio unit tests

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostFoldingRangeEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Workspaces/WorkspaceTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostFoldingRangeEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostLinkedEditingRangeEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostSemanticTokensRangeEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/TestHtmlDocumentSynchronizer.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/TestLSPRequestInvoker.cs
Part of https://github.com/dotnet/razor/issues/9519 and https://github.com/dotnet/razor/issues/10603
This time I did copy the existing tests, because everything was inline so it was easier.
> Cohosting folding range tests

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentCodeGenerationTestBase.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentLoweringPass.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/DiagnosticExtensions.cs
Fixes https://github.com/dotnet/razor/issues/10553.
> Handle `:get`/`:set` in `EditorRequired` checking

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/FilePathNormalizer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/TagHelperTooltipFactoryBaseTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentContextFactoryTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/LanguageServerTestBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Logging/TestOutputLogger.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/TestMocks.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/DocumentGenerator/BackgroundDocumentGeneratorTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Documents/VisualStudioFileChangeTrackerTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/ProjectSystem/RazorProjectInfoDriverTest.cs
It's probably easiest to go through this commit-by-commit.
The main fix here is the `IndexOutOfRangeException` in the `FilePathNormalizer`. The problem occurs when the array rented from the pool already contains a `\` or `/` immediately after the span that we care about. It was possible for `FilePathNormalizer.NormalizeAndDedupeSlashes(...)` to read past the end of the span, and if it found a `\` or `/` there, it would cause the incorrect length to be used later, causing an `IndexOutOfRangeException`. The reason the failure was intermittent is because it's dependent on the contents of the array pool.
> Fix handful of unit test issues and the intermittent IndexOutOfRangeException failures

- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ArrayExtensions.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ImmutableArrayExtensions.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/StringExtensions.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Utilities/ThrowHelper.cs
This change covers several pieces of work on shared extension methods:
1. Augment and document `AsSpan()`, `AsSpanOrDefault()`, `AsMemory()`, and `AsMemoryOrDefault()` extension methods targeting string.
2. Augment and document `Contains()`, `IndexOf()`, `StartsWith()`, and `EndsWith()` extension methods targeting string.
3. Add `AsSpan()` and `AsMemory()` extensions methods targeting array and Razor's polyfill `Index` and `Range` types.
> Expand string and span extension methods

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/FilePathNormalizer.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/BufferExtensions.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PooledObjects/PooledArray`1.cs
This change adds a new `GetPooledArraySpan(...)` extension method that returns a pooled array as a `Span<T>` with the expected length. This can help avoid bugs that can occur if a pooled array's `Length` is accidental used.
> Add GetPooledArraySpan(...) extension method

- .vscode/settings.json
We have tests with baselines that have trailing whitespaces. Our `trimTrailingWhitespace` setting means that those will get modified automatically, breaking those tests. To fix that, I implemented a vscode feature to avoid triming inside regex and strings, so let's use that.
> Turn off trailing whitespace triming in strings

- eng/Build.props
- eng/BuildAnalyzers.sln
Having two sln files in the root directory means that `dotnet` CLI commands get confused about what sln to use and need to have it specified. To fix, we just move this solution file into eng, since it's only used for full builds anyways.
> Move BuildAnalyzers.sln to eng

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteUriPresentationService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/UriPresentation/RemoteUriPresentationService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostUriPresentationEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/TestProjectData.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostUriPresentationEndpointTest.cs
Part of https://github.com/dotnet/razor/issues/9519 and https://github.com/dotnet/razor/issues/10603
After this, all cohost endpoints have test coverage 😁
> Cohosting tests for Uri presentation

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/ActivityLogLoggerProvider.Logger.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/ActivityLogLoggerProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj
- src/Shared/Microsoft.AspNetCore.Razor.Serialization.Json/JsonDataReader.cs
- src/Shared/Microsoft.AspNetCore.Razor.Serialization.Json/JsonReaderExtensions.cs
- src/Shared/Microsoft.AspNetCore.Razor.Serialization.Json/Microsoft.AspNetCore.Razor.Serialization.Json.projitems
- src/Shared/Microsoft.AspNetCore.Razor.Serialization.Json/ObjectReaders.cs
All of the types MS.VS.LanguageServices.Razor elide "LanguageServices" from their namespaces. So, each type has `Microsoft.VisualStudio.Razor` its root namespace. These have been kept in sync by pure discipline until this change.
This change updates the `<RootNamespace>` for MS.VS.LanguageServices.Razor to not include "LanguageServices". That way, new files in this project will be created with a root namespace of `Microsoft.VisualStudio.Razor`. Normally, changing the `<RootNamespace>` should be a painless process. However, it was blocked due to issues caused by the MS.ANC.Razor.Serialization.Json shared project's embedded string resources. I've gone ahead and sorted that so that updating the `<RootNamespace>` is now possible.
> Set RootNamespace for MS.VS.LanguageServices.Razor

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/RazorProjectEngine.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/FormattingContext.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/RazorFormattingService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/IDocumentSnapshotExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.ComputedStateTracker.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.ImportItem.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteDocumentSnapshot.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingTestBase.cs
Separated commits to functional change and code moving. This moves the feature flag check into tooling instead of relying on the compiler to know and generate documents differently.
That also allows for correctly doing document generation of designtime/runtime from the tooling side. If FUSE is enabled tooling will use runtime in all places except formatting. This is to keep formatting working as it does today without FUSE and start A/B testing faster.
> Always use designtime document for formatting with FUSE

- azure-pipelines.yml
- global.json
Since we updated to a .NET 9 SDK, the
MS.ANC.Razor.Microbenchmarks.Generator unit tests have failed to run locally. This is because these test use Benchmark.NET, which performs a builder at runtime targeting .NET 8. This works fine in CI because it uses a .NET 8 SDK.
This change just adds the most recent .NET 8 runtime version to the list of runtimes in Razor's global.json. So, it'll get installed into the .dotnet folder and the Microbenchmarks.Generator will run and stop reporting a spurious error.
> Add latest .NET 8 runtime to global.json

- eng/targets/Services.props
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/LinePositionExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/LinePositionSpanExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/PositionExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RangeExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/DocumentHighlight/RemoteDocumentHighlight.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteDocumentHighlightService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteUriPresentationService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RazorServices.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RemoteResponse.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/DocumentHighlight/RemoteDocumentHighlightService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/UriPresentation/RemoteUriPresentationService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentHighlightPresentationEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostUriPresentationEndpoint.cs
- src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/RazorServicesTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentHighlightEndpointTest.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Language/TestProject.cs
Brings document highlight to cohosting, including tests. Also added some basic tests for `RazorServices` and `Services.props`.
> Cohost document highlighting

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Microsoft.VisualStudio.Razor.IntegrationTests.csproj
Uses `UseVSTestRunner` instead of `TestRunneName`.
Fixes #10660
> Fix arcade property for Microsoft.VisualStudio.Razor.IntegrationTests.csproj

- Directory.Build.targets
Those platforms do not have nullable-annotated BCLs, so things like `Debug.Assert` do not work as expected and cause spurious warnings. This is the same approach that Roslyn takes: https://github.com/dotnet/roslyn/blob/main/eng/targets/Imports.targets#L35-L42.
> Disable nullable warnings on .NET Standard and Framework

- Directory.Build.targets
Merge main into the feature branch
> Merge main

- eng/config/PublishData.json
Official build containing this change: https://dev.azure.com/dnceng/internal/_build/results?buildId=2505642&view=results
Recent official builds are failing since snap: https://dev.azure.com/dnceng/internal/_build/results?buildId=2505159&view=logs&j=7ae71e7c-d4fe-51ea-64cd-240849b77ab1&t=4f9c0653-2f18-500e-227d-19e80298b3dc
```log
No PublishData found for branch 'main'. Using PublishData for branch 'main' with draft PR status.
The property 'insertionCreateDraftPR' cannot be found on this object. Verify that the property exists and can be set.
At D:\a\_work\_temp\548307e3-ff7c-45ff-9ccc-be3ab4e0bf53.ps1:12 char:3
+   $branchData.insertionCreateDraftPR = 'true'
```
The failure doesn't really make sense to me. Inspecting the diff from #10681, the most likely thing I can blame is the trailing …
> Fix trailing comma in PublishData

- eng/config/PublishData.json
17.5 is not LTS so removing the PublishData entry for it. @phil-allen-msft
> Remove 17.5 from servicing

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/DynamicFiles/RazorDocumentExcerptService.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/DynamicFiles/RazorDocumentExcerptServiceTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2112012
> Fix excerpt service to allow for multi line verbatim strings

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/DefinitionEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/LspProjectSnapshotManager.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Refactoring/RenameEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/IProjectCollectionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/IRazorComponentSearchEngine.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorComponentSearchEngine.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteProjectCollectionResolver.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Definition/DefinitionEndpointDelegationTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorComponentSearchEngineTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointDelegationTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/ProjectSystem/TestProjectSnapshotManager.cs
Started this for https://github.com/dotnet/razor/issues/10688 but saw that Go To Def used the same service, so figured @DustinCampbell would need to do the same thing, and thought it would be easier to put it up separately.
(Unless of course you've already done this, or similar, Dustin in which case I can just abandon this, nbd)
> Move down and interface-ize component search engine, and introduce IProjectCollectionResolver

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorInitializeEndpoint.cs
Adds a single telemetry point so that we if we receive feedback that something unusual behavior occurs, we can determine if Fuse was engaged or not engaged.
> Add simple telemetry to initialize endpoint

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorTranslateDiagnosticsService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentMapping/IDocumentMappingServiceExtensions.cs
because it's really easy to get one from the other.
While working on rename in cohosting, I noticed this unnecessary extra bit of work while calling `GetPositionInfo`, so I fixed it. Then I thought I'd see where else `GetSourceTextAsync` was used in an non-ideal way, and that was clearly going to be too big for the rename PR so I separated it out into it's own PR. Then I heard Dustin say he was changing `DocumentSnapshot` so the unnecessary work will end up being much less wasteful anyway, plus we'd probably just have conflicts, so I pared the whole thing right back to just this minor removal of a couple of unnecessary parameters. Enjoy.
> Don't pass `RazorCodeDocument` and `SourceText` around together

- Directory.Build.props
- Directory.Packages.props
- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/Microsoft.AspNetCore.Razor.Language.Legacy.Test.csproj
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Microsoft.AspNetCore.Razor.Language.Test.csproj
- src/Compiler/perf/Microsoft.AspNetCore.Razor.Microbenchmarks.Generator/Microsoft.AspNetCore.Razor.Microbenchmarks.Generator.csproj
- src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Test.csproj
This should make it much easier for us to respond to CG alerts in the future. All that will need to be done is add an entry in Directory.Packages.props and it will automatically impact all consumers of it.
Consider this example in Roslyn for how to respond to a CG issue
https://github.com/dotnet/roslyn/pull/74653
-
Fixes:
> Move to central package pinning

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/CSharpTokenizerTestBase.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/DirectiveCSharpTokenizerTest.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/DirectiveHtmlTokenizerTest.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/HtmlTokenizerTestBase.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Legacy/TokenizerTestBase.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/CSharpCodeParser.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/ParserContext.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/RoslynCSharpLanguageCharacteristics.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/RoslynCSharpTokenizer.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/RazorParserOptions.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/RazorParserOptionsBuilder.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/ConfigureRazorParserOptions.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorSourceGenerationOptions.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorSourceGenerator.Helpers.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorSourceGenerator.RazorProviders.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Language/Legacy/ToolingParserTestBase.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/IntegrationTestBase.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Language/Legacy/ParserTestBase.cs
Does as the tin says. Prerequisite to handling directives, as we'll need the parse options to know what preprocessor symbols are enabled.
> Plumb CSharpParseOptions to the tokenizer

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/ParserContext.cs
The debugger display of ParserContext was modifying state, this should fix it. There was also one unused method (it's weird we don't get an analyzer warning for that, but I wasn't able to make that work, so I've removed just that one method manually for now).
> Fix parser debug helpers

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorProjectServiceTest.cs
Noticed in the logs that we were double-compiling files, and it was causing issues in my "self versioned documents" branch. Separated out of that to make it easier to review.
RCA is because we now share a project manager across VS and LSP server, so we get real project information much sooner than before, which beats file watchers etc.
> Don't add already known documents to the misc files project

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/settings.json
- .vscode/tasks.json
Simple dev container for use when working in Razor
> Initial DevContainer for Razor

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Rename/RenameService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostRenameEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/10717
> Support component rename from an end tag

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_Completion.cs
Fixes https://github.com/dotnet/razor/issues/10759
Initially when investigating this I was digging into buffer versions and race conditions, but now that the editor fix is in, and we are self versioned, the bug stood out much more obviously: A character offset was being passed in to a parameter that expected a length 🤦‍♂️
Sadly none of the `RazorCustomMessageTarget` code is testable. Cohosting will make this trivial though, as we would simply create a new `Document` with the provisional change, and drop it on the floor when we're finished.
> Fix provisional completion corrupting generated C# documents

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_FindAllReferences.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_TextDocumentPosition.cs
Fixes integration test failures in Find All References.
Roslyns LSP types got much more spec compliant in https://github.com/dotnet/roslyn/pull/73911 and we were never sending the `Context` property in our request, so deserialization failed on their end.
> Fix find all references calls to Roslyn

- Directory.Packages.props
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingLanguageServerClient.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/WebTools.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Microsoft.AspNetCore.Razor.LanguageServer.Test.csproj
Fixes https://github.com/dotnet/razor/issues/10160
> Bump WebTools and remove legacy CLaSP package

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/RenameTests.cs
Skipping this should show some green ticks in the pipeline, which will make us all feel better
> Skip flaky test

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/CSharp/EventHandlerTagHelperDescriptorProvider.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/test/EventHandlerTagHelperDescriptorProviderTest.cs
This fixes an issue that @tmat pointed out to me over email. In a recent change (#10720), I added a call to `Assumed.Unreachable()` when `[EventHandler]` tag helper discovery encounters an attribute with invalid constructor attributes. However, throwing an exception during tag helper discovery is usually the wrong approach. Normally, if Roslyn symbols aren't in the proper shape during tag helper discovery, Razor will simply not produce a tag helper. (We _do_ support diagnostics for tag helpers, but those are usually reserved for warnings and errors that are related to a tag helper's data that would make it unusable, such as a name containing whitespace.)
It turns out that the "unreachable" condition wasn't actually all that unreachable and @tmat was hitting it while working on hot reload …
> Clarify [EventHandler] tag helper discovery logic and avoid exception

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostGoToDefinitionEndpoint.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostGoToDefinitionEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/10823
> Remap Html uris in cohost Go To Def

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/RazorFormattingOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteAutoInsertService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RemoteAutoInsertOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/AutoInsert/RemoteAutoInsertService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostOnAutoInsertEndpoint.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostOnAutoInsertEndpointTest.cs
- Tests for cohost OnAutoInsert endpoing
> OnAutoInsert Cohosting Tests

- .editorconfig
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/AutoInsert/OnAutoInsertEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/DocumentSymbols/RemoteDocumentSymbolService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostOnAutoInsertEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostSignatureHelpEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostWorkspaceSpellCheckEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Snippets/SnippetService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/OnAutoInsertEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostSignatureHelpEndpointTest.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PooledObjects/PooledHashSet`1.cs
A clean error list is a good error list.
> Remove unused private members

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RemoteAutoInsertOptions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostOnAutoInsertEndpoint.cs
Use default RazorFormattingOptions constructor in init of RemoteAutoInsertOptions to avoid having potentially two sets of defaults.
> Cleanup default RemoteAutoInsertOptions

- docs/CollectionBestPractices.md
This change adds a new document covering some "collection best practices" for the Razor repo. This can be expanded, but I think/hope it's a good start.
> Add Collection Best Practices in Razor document

- Directory.Build.props
It should not be needed with .NET SDK 9 preview 7.
> Remove toolset compiler workaround

- src/Compiler/Microsoft.CodeAnalysis.Razor/test/BaseTagHelperDescriptorProviderTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/test/CompilationTagHelperFeatureTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/test/ComponentTagHelperDescriptorProviderTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/test/DefaultTagHelperDescriptorFactoryTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/test/DefaultTagHelperDescriptorProviderTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/test/Microsoft.CodeAnalysis.Razor.Test.csproj
- src/Compiler/Microsoft.CodeAnalysis.Razor/test/TagHelperDescriptorFactoryTagHelpers.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/test/TagHelperTypeVisitorTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Microsoft.CodeAnalysis.Razor.Workspaces.Test.csproj
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/ReferenceUtil.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/TestCompilation.cs
Part of https://github.com/dotnet/razor/issues/10343.
> Use Basic.Reference.Assemblies in MS.CA.Razor.Test

- Directory.Build.props
- eng/AfterSigning.targets
- eng/Publishing.props
- eng/configure-toolset.sh
- eng/scripts/ci-source-build.sh
- src/Compiler/Directory.Build.props
- src/Compiler/Directory.Packages.props
- src/Shared/Directory.Build.props
Now that razor is on .NET 9 arcade, it can switch over to the new control schema. For this repo, this is roughly:
- DotNetBuildFromSource -> DotNetBuildSourceOnly - Building a source-only build.
- DotnetBuildFromSourceFlavor == Product -> DotNetBuildOrchestrator == true - Building in the VMR, could be source-only or MS's build.
- ArcadeBuildFromSource -> DotNetBuildRepo == true -> Indicates an outer repo build.
> Switch to new VMR control schema.

- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Microsoft.VisualStudio.LanguageServices.Razor.Test.csproj
Fixes https://github.com/dotnet/razor/issues/10874
This project uses the `ExportProviderFactory` which has static state, and running tests in parallel is therefore racey. https://github.com/dotnet/razor/pull/10882 is removing that system, but that has to wait for a Roslyn insertion etc. so this is a short term workaround
> Disable test parallelisation in language services

- Directory.Build.props
- src/Analyzers/Razor.Diagnostics.Analyzers/Razor.Diagnostics.Analyzers.csproj
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Microsoft.CodeAnalysis.Razor.Compiler.csproj
- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport.csproj
- src/Compiler/Microsoft.Net.Compilers.Razor.Toolset/Microsoft.Net.Compilers.Razor.Toolset.csproj
- src/Compiler/perf/Microbenchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks.Compiler.csproj
- src/Compiler/test/Directory.Build.props
- src/Compiler/tools/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal/Microsoft.AspNetCore.Mvc.Razor.Extensions.Tooling.Internal.csproj
- src/Compiler/tools/Microsoft.CodeAnalysis.Razor.Tooling.Internal/Microsoft.CodeAnalysis.Razor.Tooling.Internal.csproj
- src/Compiler/tools/RazorSyntaxGenerator/RazorSyntaxGenerator.csproj
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks.csproj
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Microsoft.AspNetCore.Razor.ProjectEngineHost.csproj
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj
- src/Razor/src/Microsoft.VisualStudio.LanguageServer.ContainedLanguage/Microsoft.VisualStudio.LanguageServer.ContainedLanguage.csproj
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Microsoft.VisualStudio.LanguageServices.Razor.csproj
- src/Razor/src/Microsoft.VisualStudio.LegacyEditor.Razor/Microsoft.VisualStudio.LegacyEditor.Razor.csproj
- src/Razor/src/Microsoft.VisualStudio.RazorExtension.Dependencies/Microsoft.VisualStudio.RazorExtension.Dependencies.csproj
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- src/Razor/test/Directory.Build.props
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.csproj
Missed this in my first pass of control updates. This is a direct replacement with no change in meaning from the original control.
Fixes:
> ExcludeFromSourceBuild->ExcludeFromSourceOnlyBuild

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/HtmlFormattingPassBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/RazorFormattingTest.cs
Altered `HtmlFormattingPassBase` to discard any `TextChange`s that start within a `RazorCommentBlockSyntax` and added a test to catch any regressions in the future.
Fixes https://github.com/dotnet/razor/issues/10891
> Fix #10891 - Formatting does not respect indentation within Razor comment blocks

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs
-VS Platform (languageserver.client code) uses various characters specified by completion capabilities, including commit characters, to figure out which text span a completion item should replace when committed. It's known as "applicable-to" span. If we don't specify commit characters HTML uses in Razor commit character set in our completion endpoint capabilities, we end up eating some of those characters if they happen to be in the document text following (or preceding) item being commited.
Fixes: https://github.com/dotnet/razor/issues/10787
> Fixing HTML attribute commit

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs
-Switching to using IAsyncCompletionSession call to commit using specific character instead of commit just by typing. It appears to be more reliable.
> Harden completion test

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RoslynLspExtensions_SourceText.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/VsLspExtensions_SourceText.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotManager.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorProjectServiceTest.cs
Fixes most of the hits on https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2223687 in 17.12 P2 and above
> Fix some `AssumeNotNull` assumptions

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/DocumentPullDiagnosticsEndpoint.cs
Helps add telemetry for cases like [AB#2255138](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2255138/)
> Add telemetry for 'bad' experiences based on tag helpers

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/EditorInProcess_Completion.cs
We now wait for a specific item in the actual shown completion UI, and also wait for the correct text in the editor post-commit to account for actions such as OnAutoInsert
1. We now actually open completion UI. Previously we may or may not have had the UI open, because IAsyncCompletionBroker.TriggerCompletion doesn't actually cause completion pop-up window UI to show (at least per doc comments). IAsyncCompletionSession.OpenOrUpdate actually shows completion window UI.
2. We now wait for a specified item to be present and selected prior to trying to commit. We will re-update (re-calculate) completion items while waiting.
3. We now wait for the correct text to be in the editor. After completion commit, there may be another action, such as OnAutoInsert that may modify the text further. We …
> More hardening of the completion test

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/TelemetryReporter.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Telemetry/TelemetryReporterTests.cs
Helps remove `AssumeNotNull` from the fault parameters and blame something in our code stack instead
> Add a filter for faults to avoid bucketing

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DocumentOnTypeFormattingEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Formatting/RemoteFormattingService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/CSharpStatementBlockOnTypeFormattingTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentOnTypeFormattingEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingLanguageServerTestBase.cs
Oops! I broke on type formatting, by missing a `!`, in https://github.com/dotnet/razor/pull/10822
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2264292
FYI @phil-allen-msft as I'm targetting 17.12 P3 with the fix.
> Fix on type formatting

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentSynchronization/DocumentDidChangeEndpoint.cs
FIxes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2046969
Rather than reporting telemtery, this PR just doesn't. I think we tried in the past to collect cabs for this, and didn't get any, and we haven't had any obvious reports from users of issues this causes.
Left the debug assert and the log message, because one of us might get lucky and run into it, or maybe a user will report something.
> Stop reporting telemetry for bad requests

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentColorEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentFormattingEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentHighlightEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentPullDiagnosticsEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentSpellCheckEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentSymbolEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostEndpointRegistration.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostFoldingRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostGoToDefinitionEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostGoToImplementationEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostInlayHintEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostInlayHintResolveEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostLinkedEditingRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostOnAutoInsertEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostOnTypeFormattingEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostRangeFormattingEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostRenameEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostSemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostSignatureHelpEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostTextPresentationEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostUriPresentationEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/IDynamicRegistrationProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/RazorCohostDynamicRegistrationService.cs
Recently the editor fixed a bug where they were sending `didOpen` etc. requests for things not explicitly registered: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2003716/
This is great, and I even logged the bug, but we do actually want those messages in cohosting, so now we need to register for them :)
Most of the changes are just allowing our registration providers to provide multiple registrations.
> Register for endpoints provided by Roslyn in cohosting

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/AutoInsert/AutoClosingTagOnAutoInsertProvider.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/AutoInsert/AutoClosingTagOnAutoInsertProviderTest.cs
Current code was defining allowed auto-insert scenario too narrowly, with the main issue being that at the moment of the auto-insert the end tag for the newly typed tag is missing and if there is an enclosing/parent tag with the same name, the inner tag ends up "stealing" the end tag from that. We need to walk up the tree looking for the unclosed parent tag with the same name.
- If our current tag (the one where we just completed the start tag by typing ```>```) appears to contain end tag, it might be stealing end tag from the enclosing tag with the same name, e.g.
```
<div>
<div>|
</div>
```
we currently handle that case, but not completely. 
- Now we walk up the tree, and we don't stop if current tag is inside of something other than a tag, because when a tag …
> Fixing auto-insert inside of a C# statement.

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs
Seeing intermittent failures in other completion commit tests. This switches them all to the new commit method where we wait for the specific completion item to be present.
> Hardening the rest of the completion commit tests

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/InlayHints/InlayHintService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/InlayHints/RemoteInlayHintService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/InlayHints/InlayHintEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostInlayHintEndpointTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2253190
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2225341
> Don't throw if we get an old/bad Inlay Hint request

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WorkspaceDiagnosticsRefresh.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WorkspaceDiagnosticsRefresher.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WorkspaceSemanticTokensRefreshNotifier.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/WorkspaceDiagnosticRefreshTest.cs
This notifies a client to refresh diagnostics when we experience project snapshot changes (except for document changed). This should help for cases where the project engine is updating but doesn't have all taghelper information yet.
> Refresh diagnostics on project changes

- eng/TSAConfig.gdntsa
Move to reporting TSA data for all the tools. The previous configuration was causing us to miss Polichcek, PSScriptAnalyzer, CredScan, etc ...
> Enable TSA reporting

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DocumentContextFactory.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/IProjectSnapshotManagerExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/IProjectSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/IProjectSnapshotExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorComponentSearchEngine.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Rename/RenameService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteProjectSnapshot.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Documents/RazorCodeDocumentProvidingSnapshotChangeTrigger.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/DynamicFiles/RazorDocumentExcerptService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/CSharpVirtualDocumentFactory.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_ProjectContexts.cs
- src/Razor/src/Microsoft.VisualStudio.LegacyEditor.Razor/EphemeralProjectSnapshot.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/ProjectSystem/TestProjectSnapshot.cs
There's a fair amount of code in Razor that uses `IProjectSnapshot.GetDocument(...)` to test for the presence of a document with a given file path in a project. However, `GetDocument` has the side effect of creating a document snapshot which ultimately may be thrown away.
This change adds an `IProjectSnapshot.ContainsDocument(...)` method that tests for the presence of a document by file path and returns true or false without creating a new document snapshot. In addition, I've cleaned up the `IProjectSnapshot` implementations a bit.
> Add IProjectSnapshot.ContainsDocument to test document paths cheaply

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/GenerateMethodCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/RazorFormattingService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/TelemetryReporter.cs
Cherry pick of the commit from https://github.com/dotnet/razor/pull/10959 that fixes code actions in FUSE, **and fixing the generate event handler code action which is unrelated to FUSE**, in case we decide we want to take it for 17.12 P3
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2268945
> Fix Generate Event Handler code action

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/GeneratedDocumentPublisher.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/GeneratedDocumentSynchronizer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/OpenDocumentGenerator.Comparer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/OpenDocumentGenerator.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/CSharpVirtualDocumentManager.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/GeneratedDocumentPublisherTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/GeneratedDocumentSynchronizerTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorProjectServiceTest.cs
Fixes https://github.com/dotnet/razor/issues/10970
Each commit in this PR essentially hardens the project system a little bit more. Together they fix the publish issue, which is a particularly difficult scenario, as it essentially removes and quickly re-adds a project, but I think the changes are pretty good overall. No one commit fixes the publish issue, and I wouldn't say there is no more work to do, but forward progress is forward progress.
Each commit is isolated to a particular service and has a brief description of what the change is and why, but I think it's perfectly understood when looked at as a whole too. Review however you prefer :)
> Fix project publish (or: Various project system fixes)

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/IRazorProjectService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.TestAccessor.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorComponentSearchEngineTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorProjectServiceTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestRazorProjectService.cs
Noticed while working on my previous PR. There were a few methods in RazorProjectService that were only used by tests, and also resulted in some tests validating things that could never happen in the product (like passing `null` for a project file path in an update). This PR removes one unused method, moves one to a test accessor where it rightly should be, and updates the tests that were calling `UpdateProjectAsync` to instead call through `IRazorProjectServiceListener.UpdatedAsync`.
I don't love that these tests have to call through that interface, but I didn't change the method to be implicitly implemented because I don't think the name makes sense when written that way.
There are, or at least should be, no functionality changes in this PR.
> RazorProjectService cleanup

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Definition/DefinitionEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/FindAllReferences/FindAllReferencesEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Implementation/ImplementationEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Implementation/ImplementationEndpointTest.cs
Using SumType doesn't directly allow CLaSP to correctly do a null check via `is null`. This fixes it so that places that allow null use `Nullable<T>` or specificy that the non-value type can be null. Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2136054/
> Fix nullability to match specification

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/CodeGenerationIntegrationTest.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/TestTagHelperDescriptors.cs
- Related to https://github.com/dotnet/razor/issues/10343.
- Extracted out of https://github.com/dotnet/razor/pull/11000.
> Avoid referencing a test assembly in compilation

- Directory.Packages.props
- NuGet.config
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/IRazorGeneratedDocumentExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/NonCapturingTimer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RemoteAutoInsertOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TextDifferencing/TextDiffer.IntArray.cs
Extracted out of https://github.com/dotnet/razor/pull/11000.
> Remove source-only package

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/DefaultCSharpCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CSharp/TypeAccessibilityCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Models/ExtractToComponentCodeActionParams.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ComponentAccessibilityCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToCodeBehindCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToComponentCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToComponentCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/GenerateMethodCodeActionProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/RazorCodeActionContext.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/DefaultCSharpCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/TypeAccessibilityCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Html/DefaultHtmlCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ComponentAccessibilityCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToComponentCodeActionProviderTest.cs
Clean up some of the extract to component code. Move more work to the resolver, use pooled objects where applicable, and try to make the provider cleaner when creating the ExtractToComponentCodeActionParams
> Some Cleanup For ExtractToComponent

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorRequestExecutionQueue.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorLanguageServerTest.cs
Mirrors https://github.com/dotnet/roslyn/pull/74300 for razor
fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2286513?src=WorkItemMention&src-action=artifact_link
> Move culture info check

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentCodeGenerationTestBase.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/CascadingGenericInference_NotCascaded_CreatesError/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/CascadingGenericInference_NotCascaded_Explicit/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/CascadingGenericInference_WithUnrelatedType_CreatesError/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/EventCallbackOfT_GenericComponent_MissingTypeParameterBinding_01/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/EventCallbackOfT_GenericComponent_MissingTypeParameterBinding_02/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/CascadingGenericInference_NotCascaded_CreatesError/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/CascadingGenericInference_NotCascaded_Explicit/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/CascadingGenericInference_WithUnrelatedType_CreatesError/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/EventCallbackOfT_GenericComponent_MissingTypeParameterBinding_01/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/EventCallbackOfT_GenericComponent_MissingTypeParameterBinding_01/TestComponent.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/EventCallbackOfT_GenericComponent_MissingTypeParameterBinding_02/TestComponent.codegen.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/CSharp/GenericTypeNameRewriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor/test/GenericTypeNameRewriterTest.cs
Similar to https://github.com/dotnet/razor/pull/10999, this time just an error-recovery scenario.
> Avoid ambiguous `object` reference in generic component recovery

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentCodeGenerationTestBase.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentLoweringPass.cs
Fixes part of https://github.com/dotnet/razor/issues/10553 missed previously - when the `ValueChanged` or `ValueExpression` property is `[EditorRequired]`.
> Handle EditorRequired *Changed/*Expression parameters

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/UnifiedSettings/razor.registration.json
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Microsoft.VisualStudio.Razor.IntegrationTests.csproj
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/UnifiedSettingsTest.cs
> Fix invalid setttings json

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/Razor/ExtractToComponentCodeActionProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/RazorSyntaxFacts.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToComponentCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToComponentCodeActionResolverTest.NetFx.cs
Fixes https://github.com/dotnet/razor/issues/11050 
Commit by commit will show moving things around to clean up. Decided for now that the extraction should not be offered until we find a need/use case for it.
> Do not extract component into code block

- docs/Compiler Breaking Changes - DotNet 8.md
Adds a new breaking changes document in the style of roslyn to document breaking changes in the razor compiler.
> Add breaking changes document

- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/TestFiles/ParserTests/CSharpSectionTest/ParserDoesNotOutputErrorOtherNestedDirectives.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/TestFiles/ParserTests/CSharpSectionTest/ParserOutputsErrorOnMultipleNestedSections.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/TestFiles/ParserTests/CSharpSectionTest/ParserOutputsErrorOnNestedSections.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/TestFiles/ParserTests/HtmlToCodeSwitchTest/SectionContextGivesWhitespacePreceedingToCodeIfThereIsNoMarkupOnThatLine.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/TestFiles/ParserTests/RazorDirectivesTest/ExtensibleDirectiveErrorsIfNotAtStartOfLine.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/CSharpSectionTest/ParserDoesNotOutputErrorOtherNestedDirectives.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/CSharpSectionTest/ParserOutputsErrorOnMultipleNestedSections.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/CSharpSectionTest/ParserOutputsErrorOnNestedSections.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/HtmlToCodeSwitchTest/SectionContextGivesWhitespacePreceedingToCodeIfThereIsNoMarkupOnThatLine.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/RazorDirectivesTest/ExtensibleDirectiveErrorsIfNotAtStartOfLine.diag.txt
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Resources.resx
Replace a `` ` ``   with a `'` in the error message.
> Fix resource string

- Directory.Packages.props
- src/Analyzers/Directory.Build.props
- src/Compiler/Directory.Build.props
- src/Razor/Directory.Build.props
- src/Shared/Directory.Build.props
I noticed some painful NuGet analyzer package upgrades in PR #11048 and decided to take a look at the issue. I've made the following changes:
- `Roslyn.Diagnostics.Analyzers` is now versioned separately from `Microsoft.CodeAnalysis.Analyzers`, as they are in [`dotnet/roslyn`](https://github.com/dotnet/roslyn/blob/08243d3826b8ebbc38350d0d74796bb8176f55b1/eng/Directory.Packages.props#L4).
- I've removed direct references to `MS.CA.BannedApiAnalyzers` since that reference should flow from `Roslyn.Diagnostics.Analyzers`.
- I've updated the versions of `Microsoft.CodeAnalysis.Analyzers` and `Roslyn.Diagnostics.Analyzers`
> Update analyzer package versions

- Directory.Packages.props
- src/Analyzers/Directory.Build.props
- src/Compiler/Directory.Build.props
- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/TestFiles/ParserTests/CSharpSectionTest/ParserDoesNotOutputErrorOtherNestedDirectives.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/TestFiles/ParserTests/CSharpSectionTest/ParserOutputsErrorOnMultipleNestedSections.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/TestFiles/ParserTests/CSharpSectionTest/ParserOutputsErrorOnNestedSections.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/TestFiles/ParserTests/HtmlToCodeSwitchTest/SectionContextGivesWhitespacePreceedingToCodeIfThereIsNoMarkupOnThatLine.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/legacyTest/TestFiles/ParserTests/RazorDirectivesTest/ExtensibleDirectiveErrorsIfNotAtStartOfLine.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/CSharpSectionTest/ParserDoesNotOutputErrorOtherNestedDirectives.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/CSharpSectionTest/ParserOutputsErrorOnMultipleNestedSections.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/CSharpSectionTest/ParserOutputsErrorOnNestedSections.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/HtmlToCodeSwitchTest/SectionContextGivesWhitespacePreceedingToCodeIfThereIsNoMarkupOnThatLine.diag.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/ParserTests/RazorDirectivesTest/ExtensibleDirectiveErrorsIfNotAtStartOfLine.diag.txt
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Resources.resx
- src/Razor/Directory.Build.props
- src/Shared/Directory.Build.props
Trivial conflict resolutions only.
> Merge main to tokenizer branch

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/ITelemetryReporter.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/NoOpTelemetryReporter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Telemetry/OutOfProcessTelemetryReporter.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/TelemetryReporter.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/VSTelemetryReporter.cs
- src/Razor/src/rzls/Program.cs
rzls imports telemetry by creating an ExportProvider with the path to devkit telemetry if it's installed and enabled. Unfortunately that means that dispose is being prematurely called when that provider is torn down. To help with this two things are done:
1. Make a flush method on ITelemetryReporter
2. Make when flush happens an implementation detail on the specific providers.
In this case, rzls will flush after the language server host exits. In other cases IDisposable will be used to flush telemetry (VS and OOP)
> Add flush method and make it implementation detail on how that happens

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/DocumentPullDiagnosticsEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/MapCode/MapCodeEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/SemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/ITelemetryReporter.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/ITelemetryReporterExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/NoOpTelemetryReporter.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/TelemetryScope.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Telemetry/TelemetryThresholds.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/SemanticTokens/RemoteCSharpSemanticTokensProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostSemanticTokensRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_CodeActions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_Completion.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_Diagnostics.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_MapCode.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_SemanticTokens.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/TelemetryReporter.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/VSTelemetryReporter.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/RazorCustomMessageTargetTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Telemetry/TelemetryReporterTests.cs
Reduce the amount of telemetry emitted
The beginLspRequest event is removed, and the trackLspRequest event is only emitted if the amount of time is over a certain threshold.  This allows analysis of cases in which the amount of taken is significantly over expectations while reducing the total telemetry significantly.
> Reduce the amount of telemetry emitted

- Directory.Packages.props
- eng/Version.Details.xml
- eng/Versions.props
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/MetadataCollectionTests.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/DocumentSymbols/RemoteDocumentSymbolService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/TestRazorDocumentServiceProvider.cs
- Update Roslyn package references to the latest in VS main
- Minor fixup due to ambiguous extension method Reverse() - there is now one in System.MemoryExtensions, so we need to force type we are invoking the method on to be IEnumerable to get the Linq reverse method we want.
- Roslyn GetDocumentSymbolAsync method now requires supportsVSExtensions parameter. Hardcoding to true for now until we plumb VSInternalClientCapabilities through init of the remote client (see https://github.com/dotnet/razor/issues/11102)
> Update Roslyn package references to latest available and do minor fixup

- docs/contributing/BuildFromSource.md
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveCompletionItemProvider.cs
- optimize docs for first-time pull-experience
Fixes:
Some initial confusion when starting to work with the repo
> docs: better bootstrapping xp

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/RazorCodeActionFactory.cs
Fixes https://github.com/dotnet/razor/issues/11049
Turns out https://github.com/dotnet/razor/pull/11069 meant the ordering of Razor and C# code actions is no longer a problem, so all we need to do is make sure the code actions that introduce new `@using` directives comes first.
> Make "add using" code actions high priority

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/ITelemetryReporter.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/NoOpTelemetryReporter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Telemetry/OutOfProcessTelemetryReporter.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/TelemetryReporter.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/VSTelemetryReporter.cs
- src/Razor/src/rzls/Program.cs
Currently telemetry is flushed after the language server host exits in VS Code. This is correctly flushing to the telemetry session, but can miss actually reporting the telemetry. In VS the lifetime of the TelemetrySession is managed centrally, but in VS Code it is up to each process to make sure it gets disposed properly. Without this telemetry that is fired could be dropped. This change addresses this by doing the following: 
1. Removing the flush method on ITelemetryReporter
2. Making TelemetryReporter IDisposable (again). This will be disposed by the DI container.
3. Keep the DI container (ExportProvider) alive in rzls until the language server host exits.
This should fix the reliability of some telemetry getting dropped. It still won't fix the scenario where the user force closes the …
> Fix aggregate telemetry reliability

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/HoverEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Hover/HoverFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Tooltip/ClassifiedTagHelperTooltipFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Tooltip/MarkupTagHelperTooltipFactory.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/HoverEndpointTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Hover/HoverFactoryTest.cs
This pull request makes a couple of changes to `HoverFactory.GetHoverAsync(...)` to prepare for co-hosting:
1. `HoverFactory.GetHoverAsync(...)` returns an LSP `Hover` rather than `VSInternalHover`.
2. `HoverFactory.GetHoverAsync(...)` no longer takes a document file path. It already takes a `RazorCodeDocument`, and the file path can be retrieved from that.
> Pre co-hosting Hover tweaks

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorCodeActionsBenchmark.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionResolveEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/IDelegatedCodeActionResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/IDelegatedCodeActionsProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hosting/LspInitializationHelpers.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/CSharp/CSharpCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/CSharp/UnformattedRemappingCSharpCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/CodeActionResolveService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/CodeActionsService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Html/HtmlCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/ICodeActionResolveService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/ICodeActionsService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/RazorCodeActionContext.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/CSharpCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/CSharpCodeActionResolverTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CSharp/TypeAccessibilityCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionResolutionEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Html/HtmlCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Html/HtmlCodeActionResolverTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ComponentAccessibilityCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToCodeBehindCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToComponentCodeActionProviderTest.cs
Okay, I was wrong when I said the last PR was the final piece before cohosting actually gets implemented, but this one is, I swear!
Code actions have to run in devenv for Roslyn, so the main thing here is re-architecting so that the endpoints call the delegated servers, because calling into the service. Each commit is an isolated step on the way.
> More CodeAction moves in preparation for cohosting

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/ExtractToComponentCodeActionProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/RazorCodeActionContext.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToComponentCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToComponentCodeActionResolverTest.NetFx.cs
Extract component had some odd behavior around MarkupTextLiteralSyntax selection.
Previously it would not allow a user to have a text literal as the start or end of the selection, it would always try to get the parent block. That works as intended for most cases where a user is highlighting inside a tag and the tag shouldn't be split. However, if the text is top level in the document it won't have a parent tag and thus would not have been considered a valid selection. This allows for that scenario.
There was also an issue if the selection was following a tag with a sibling text literal. If the selection ended after the brace but the text literal was not empty the selection would fail. For example:
```razor
[|<h1>Hello</h1>|]
Welcome to your new app
```
In the above the end of the …
> Fix some things for extract component

- src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/RazorWorkspaceListenerBase.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/RazorProjectInfoFactory.cs
- src/Razor/src/rzls/NamedPipeBasedRazorProjectInfoDriver.cs
Add logging on the server side for why a project isn't being serialized.
Reduce some of the logging on the client side if it gets into a bad state. Log once for first bad read and once when it gets to a point where we think we returned to a good state.
> Better logging for named pipe

- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Assumed.cs
This change is a follow-up to https://github.com/dotnet/razor/pull/11144#discussion_r1828602406 that addresses two issues that may help with diagnosis:
1. `Assumed.Unreachable(...)`captures the `[CallerFilePath]` and `[CallerLineNumber]` but didn't do anything with them. Now, those values are appended to the exception message.
2. Two `Assumed.Unreachable(...)` overloads have been added to allow a custom exception message to be provided that can be used to add more detail about a failure.
> Improvements for Assumed.Unreachable(...)

- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostHoverEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/HoverAssertions.cs
Even though component attributes look like HTML they map to generated C#. In this case, Hover prefers C# over HTML and requests hover data from Roslyn. This adds a test for that scenario.
> Add cohosting Hover test for component attribute

- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingTestBase.cs
Turns out the boolean parameter passed in here is read in exactly one spot in our code, and that line of code is never hit in these tests because they use mocks.
Yes, this is the equivalent of removing a `Thread.Sleep` that was put in previously, but I'm taking it regardless :)
> Halve the time it takes to run formatting unit tests

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DocumentRangeFormattingEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentRangeFormattingEndpointTest.cs
It turns out the value comes back as a JsonElement instead of the underlying type 🤷
> Fix format on paste data readon from request

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hosting/ConfigurableLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RemoteClientInitializationOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Initialization/RemoteLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteProjectSnapshot.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteServiceInvoker.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/WellKnownFeatureFlagNames.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Workspaces/TestLanguageServerFeatureOptions.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTestBase.cs
This makes the feature work in VS and VS Code (with corresponding VS Code change to pass the right flag, coming once this is merged)
VS Code PR: https://github.com/dotnet/vscode-csharp/pull/7748
/cc @danroth27, @leslierichardson95, @333fred, @chsienki and anyone else who wants, for wording:
VS Code:
https://github.com/dotnet/vscode-csharp/pull/7748/files#diff-9b29d8b47a74097a04da353b72a8632d485d658282457b97b4caf26575a42dd0R131
VS:
https://github.com/dotnet/razor/pull/11185/files#diff-18b9b146f4d27a6a5b6248ece31b30570d84c2a409b25bf5b660de86e608fa4cR80
> Add feature flag to turn on the new Roslyn tokenizer

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/AggregatingTelemetryLog.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/TelemetryReporter.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Telemetry/TelemetryReporterTests.cs
When first introduced there was an error in assumption of how histogram telemetry worked. This fixes this by correctly reporting a unique histogram even per lsp method name rather than the first one that comes in (which, as it turns out, was always initialize)
Also cleaned up the wording so it was a little easier to understand.
> Fix request duration logging

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/IProjectSnapshotExtensions.cs
- src/Razor/src/Microsoft.VisualStudio.LegacyEditor.Razor/VisualStudioDocumentTracker.cs
Fixes #9878
It turns out that this extension method isn't necessary. It's only used by the legacy editor, which can just access `IProjectSnaphshot.ProjectWorkspaceState.TagHelpers`. That property is always implemented by any project snapshot that the legacy editor encounters, namely `ProjectSnapshot` or `EphemeralProjectSnapshot`.
> Remove GetTagHelpersSynchronously extension method

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DocumentStateTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateTest.cs
Follow up to https://github.com/dotnet/razor/pull/11191 which caused RPS regressions.
There were some edge-y things I papered over in that PR, assuming they were unnecessary over-complications, but given the RPS regression I had a closer look, and they could have caused re-compilation of closed documents when only tag helpers changed, which would be new behaviour. Not _entirely_ convinced the re-compilation is all unnecessary (if a document used a Tag Helper that has only just been discovered, then its code gen would legitimately change) but it's hard to justify when I can't point to any tooling for the closed files that would actually benefit from the extra work.
The key thing is not changing `DocumentCollectionVersion` when only `ProjectWorkspaceState` changes. Not re-calculating import …
> Fine tuning of what types of project update affect what state

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorLanguageServerBenchmarkBase.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/RazorProjectService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentState.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectDifference.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotManager.Updater.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotManager.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectState.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/UpdateProjectAction.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LiveShare/Guest/ProjectSnapshotSynchronizationService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectWorkspaceStateGenerator.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeDocumentReferenceHolderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DocumentPresentation/TextDocumentUriPresentationEndpointTests.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/OpenDocumentGeneratorTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Refactoring/RenameEndpointTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/DocumentStateTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateGeneratedOutputTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/ProjectSystem/ProjectStateTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Tooltip/ProjectAvailabilityTests.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LiveShare/Guest/ProjectSnapshotSynchronizationServiceTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LiveShare/Host/ProjectSnapshotManagerProxyTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackProjectManagerTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/ProjectSnapshotManagerTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectWorkspaceStateGeneratorTest.cs
- src/Razor/test/Microsoft.VisualStudio.LegacyEditor.Razor.Test/VisualStudioDocumentTrackerTest.cs
Reverts https://github.com/dotnet/razor/pull/11213 and https://github.com/dotnet/razor/pull/11191
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2302189
> Revert changes to how projects are updated

- azure-pipelines.yml
This will allow https://lab.razor.fyi to be used on PR builds of the compiler. Including Debug configurations (useful for seeing asserts). Note that Roslyn also publishes packages and DLLs on PR builds (both Debug and Release configurations).
> Publish package artifacts on PR builds

- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/RazorEventSource.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/AsyncBatchingWorkQueue`1.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Utilities/AsyncBatchingWorkQueue`2.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/DynamicFiles/BackgroundDocumentGenerator.cs
I was musing the other day about ETW events possibly being useful in tracking down the Speedometer regression I was looking in to, and then along comes https://github.com/dotnet/razor/issues/11232 which is a great excuse to add some ETW event infrastructure to our lives.
The idea here is that RPS/Speedometer tests can wait for Razor to be "ready" by looking for this event, rather than `Thread.Sleep`ing. Anecdotally on my machine, when loading OrchardCore, this event fires once a couple of minutes after solution load, so seems like a reasonable candidate.
Once this is in @WardenGnaw will try it out and if it's not good, we'll pop some more events somewhere.
Will need to follow up with PR(s?) to add this event source name to the list, but I need to work out where to do that first :)
> Fire an ETW event when the background document generator queue is empty

- src/Razor/src/.editorconfig
- src/Razor/src/Microsoft.AspNetCore.Razor.ExternalAccess.RoslynWorkspace/RazorWorkspaceListener.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionResolveEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hosting/FormattingFlags.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.ProjectEngineHost/Telemetry/TelemetryScope.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Models/RazorCodeActionResolutionParams.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/SnippetResponseRewriter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Logging/LogLevel.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/AutoInsert/RemoteAutoInsertTextEdit.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/Competion/CompletionPositionInfo.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/TextDocumentIdentifierAndVersion.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentCompletionEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LiveShare/Guest/RazorGuestInitializationService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/TelemetryReporter.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Telemetry/VSTelemetryReporter.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/IntraTextAdornmentTagger.cs
- Adding .editorconfig setting to flag formatting issues as warnings during build
Fixes: https://github.com/orgs/dotnet/projects/197?pane=issue&itemId=88054220
> Adding a setting to .editorconfig to enforce formatting

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectCapabilityResolver.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2302211
This change adds a null check to ProjectCapabilityResolver.ContainingProjectHasCapability(...) that was incorrectly removed by 6cd5bd4ba6fe57dee7454e8b4d6a33ddaea5514b. Without this null check, it is impossible to open a merge editor for a razor or cshtml file. The merge editor has a few editors within it, and some of them are not included in a project, so they have a null IVsHIerarchy.
> [17.12] Add back null check to allow merge editor to load

- src/Razor/.editorconfig
- src/Razor/src/.editorconfig
Got sick of seeing messages about namespaces not matching folder names, so thought I'd suppress it. Then Alex mentioned the formatting rule in standup, and I thought tests deserve the same treatment.
> Editor config tweaks

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/ExtractToComponentCodeActionProvider.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToComponentCodeActionProviderTest.cs
fixes https://github.com/dotnet/razor/issues/11261
> Fix extract component whitespace handling

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Mvc/MvcImportProjectFeature.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Models/PromoteToUsingCodeActionParams.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/PromoteUsingCodeActionProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/PromoteUsingCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/RazorCodeActionFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/LanguageServerConstants.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/SR.resx
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.cs.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.de.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.es.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.fr.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.it.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.ja.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.ko.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.pl.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.pt-BR.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.ru.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.tr.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.zh-Hans.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.zh-Hant.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/CodeActions/RemoteServices.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostCodeActionsEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTestBase.cs
Fixes https://github.com/dotnet/razor/issues/6155
Me: I really like the cohosting code action tests, it must be really easy to add a new code action now!
Me: Oh really? Well, try it and find out, I dare you!!
Me: &lt;this PR&gt;
(Also me: That wasn't as much fun as I expected. I have thoughts.)
> Add a code action to promote a using directive

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hosting/RazorLanguageServerHost.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/JsonHelpers.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/CodeActions/RoslynCodeActionHelpers.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Completion/RemoteCompletionService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/DocumentSymbols/RemoteDocumentSymbolService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostCodeActionsEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostCodeActionsResolveEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentCompletionEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentPullDiagnosticsEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/RazorCohostDynamicRegistrationService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/LanguageServerTestBase.cs
We weren't always using correct serializer options when serializing and deserializing in cohosting. E.g. deserializing to VS LSP types should use VS LSP converters, and deserializing to Roslyn LSP types should use Roslyn LSP converters. Otherwise, things mostly work, but you can end up with base versions of the types instead of VSInternal subtypes.
I found this issue when I realized that VSInternalClientCapabilities wasn't getting deserialized quite right - top level was VSInternal version, but all fields (and their fields) were not properly deserialized to their VSInternal versions. 
Also adding a couple of common helper methods to make serialization/deserializion code easier to keep consistent. 
-Common helpers for serialization and deserialization
-Make sure …
> Use correct serializer options when serializing and deserializing

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/SnippetResponseRewriter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/SR.resx
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.cs.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.de.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.es.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.fr.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.it.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.ja.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.ko.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.pl.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.pt-BR.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.ru.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.tr.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.zh-Hans.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.zh-Hant.xlf
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/SnippetResponseRewriterTest.cs
Fixes https://github.com/dotnet/razor/issues/11189
Previously we would change "using" to "using statement" in completion. Completing this item would insert "using statement" into the document, which not valid Razor or C#. Inline completion also wouldn't work because "statement" is not a valid C# snippet. Removing it means we leave our using keyword and using directive snippet completion items in place, and our using keyword works fine with inline completion, because completion item type doesn't matter at that point.
> Remove C#s using snippet from completion

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/GeneratedDocumentPublisher.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/UpdateBufferRequest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/RazorCustomMessageTargetTest.cs
Razor side of https://github.com/dotnet/roslyn/pull/76050
> Add more information to dynamic file publish

- eng/pipelines/test-integration-job.yml
Seems to work:
https://devdiv.visualstudio.com/DevDiv/_build?definitionId=15591&_a=summary
> Enable long paths before building on test machines

- Directory.Packages.props
- eng/Versions.props
Tracking issue: https://github.com/dotnet/sdk/issues/45155
Unblocks: https://github.com/dotnet/sdk/pull/45042
@ViktorHofer @ericstj @MichaelSimons @akoeplinger
> Only update razor dependencies coming from maintenance-packages when source build is true

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/FindAllReferences/FindAllReferencesEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/FindAllReferences/FindAllReferencesHelper.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/FindAllReferences/RemoteFindAllReferencesService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/FindReferences/FindAllReferencesEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostFindAllReferencesEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/11278
Fixes https://github.com/dotnet/razor/issues/4611
We lose classification, but get more context. Worthy trade off I think
Before:
After:
> Improve Find All Refs results

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Diagnostics/CSSErrorCodes.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Diagnostics/RazorTranslateDiagnosticsService.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentPullDiagnosticsTest.cs
Filters out the main user frustration arising from https://github.com/dotnet/razor/issues/7349
> Filter out CSS002 when it appears in an "@@"

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RazorSyntaxNodeExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/CSharpFormatter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/FormattingVisitor.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/CSharpFormattingPass.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/CSharpFormattingPassBase.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/CSharpOnTypeFormattingPass.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/RazorFormattingPass.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/RazorFormattingService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentFormattingTest.cs
Part of https://github.com/dotnet/razor/issues/10402
This PR makes various updates to our formatting engine to allow it to run on runtime code-gen. After this PR there are still 5 formatting tests that fail, representing two different bugs (the one in the issue, and a cascading value parameter issue), but those are proving very stubborn, so thought I'd put this up first. Plus it's Friday afternoon :)
Comments in the code hopefully explain what is going on, but honestly, it doesn't matter if anyone understands the formatting engine, as long as the tests pass :D
Each commit is a self-contained change for those who are extra curious about which bit fixes which failure.
> Formatting engine changes to allow it to (mostly) run on runtime code-gen

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/CSharpFormatter.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/11325
> Don't format collection expressions, because Roslyn doesn't either

- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentFormattingTest.cs
Follow up to address https://github.com/dotnet/razor/pull/11326#issuecomment-2557214532
> Add a test to ensure collection expressions format, even if they don't indent

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Hover/HoverFactory.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostHoverEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/11335
Event callbacks on components use the tag helper infrastructure internally in the compiler, but it makes sense to me to have different rules applied to them when it comes to showing hover info. Leaving the existing code as is for `.cshtml` files is entirely deliberate.
Before:
After:
> Only show element hover information when hovering over an element in a `.razor` file

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentMapping/IDocumentMappingServiceExtensions.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentCompletionEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/10613
Fixes https://github.com/dotnet/razor/issues/10614
> Fix completion in an empty document

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Diagnostics/RazorDiagnosticsPublisher.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/CreateComponentCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/ExtractToCodeBehindCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/ExtractToComponentCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/GenerateMethodCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/PromoteUsingCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Rename/RenameService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/DefaultWorkspaceDirectoryPathResolverTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/RazorFileChangeDetectorManagerTest.cs
Fixes https://github.com/dotnet/razor/issues/10662
> Use a helper method instead of doing lots of Uri building

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/DelegatedCompletionHelper.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentCompletionEndpointTest.cs
Fixes element completion at the end of a document.
Also closes https://github.com/dotnet/razor/issues/4622 by adding a test to prove it doesn't repro.
> Fix completion at end of document

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Models/GenerateMethodCodeActionParams.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/GenerateMethodCodeActionProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/GenerateMethodCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/RazorCodeActionFactory.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostCodeActionsEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/9730
Fixes https://github.com/dotnet/razor/issues/10704
Commit at a time might be easier, depending on how well GitHub handlers the diff
> Support "Generate Event Handler" on event callbacks (ie `ValueChanged` and friends)

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/CSharpFormattingPass.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/CSharpFormattingPassBase.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/CSharpOnTypeFormattingPass.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Microsoft.CodeAnalysis.Razor.Workspaces.csproj
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/DocumentSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Microsoft.CodeAnalysis.Remote.Razor.csproj
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteDocumentSnapshot.cs
There was only one slight tweak that needed to be made to on type formatting in order for all of our tests to pass on runtime code-gen, so this is that.
Extracted out of the new formatting engine PR.
> Allow on-type formatting to run on runtime code-gen

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LspServices.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/AutoInsert/RemoteAutoInsertService.cs
When using the latest daily build of the .NET 10 SDK to build this repo, it results in the following errors:
```
/__w/1/vmr/src/razor/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/LspServices.cs(17,56): error IDE0052: Private member 'LspServices._startupServices' can be removed as the value assigned to it is never read (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0052) [/__w/1/vmr/src/razor/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj]
/__w/1/vmr/src/razor/src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/AutoInsert/RemoteAutoInsertService.cs(35,39): error IDE0052: Private member 'RemoteAutoInsertService._filePathService' can be removed as the value assigned to it is never read …
```
> Remove unused field in LspServices

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/RazorContentTypeChangeListener.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/RazorContentTypeChangeListenerTest.cs
Related to https://github.com/dotnet/razor/pull/11358
Discovered another unused field to be removed.
> Remove unused field in RazorContentTypeChangeListener

- eng/config/globalconfigs/Common.globalconfig
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentMarkupBlockPass.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/DocumentClassifierPassBase.cs
Fixes https://github.com/dotnet/razor/issues/11359
IDE0052 wasn't being enforced in CI which means we broke the VMR build (see https://github.com/dotnet/razor/pull/11358 and https://github.com/dotnet/razor/pull/11361). This change makes sure this rule is turned on and enforced in command line builds, and fixes a couple of violations in the compiler. Should prevent future breakages too.
Not sure why out existing .editorconfig for this diagnostic didn't work, but I suspect its because the compiler has its own .editorconfig marked as root.
> Enforce IDE0052 across the repo

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionItemResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionResolveEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/ComponentAvailabilityService.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hover/HoverEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/AggregateCompletionItemResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/CompletionItemResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItemResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/FindAllReferences/FindAllReferencesHelper.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Hover/HoverFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Tooltip/AbstractComponentAvailabilityService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Tooltip/ClassifiedTagHelperTooltipFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Tooltip/Extensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Tooltip/IComponentAvailabilityService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Tooltip/MarkupTagHelperTooltipFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Hover/ComponentAvailabilityService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Hover/RemoteHoverService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionItemResolverTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionResolveEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/HoverEndpointTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Hover/HoverFactoryTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Tooltip/ClassifiedTagHelperTooltipFactoryTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Tooltip/MarkupTagHelperTooltipFactoryTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Tooltip/ProjectAvailabilityTests.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Tooltip/TestComponentAvailabilityService.cs
When determining what projects a component or tag helper is available within, there is slightly different behavior in the Razor language server vs. co-hosting. In the language server, there is a special case to skip the misc-files project, but that case isn't bothered with in co-hosting. The special case is manifested via different implementations of `ISolutionQueryOperations.GetProjectsContainingDocument(...)` in the language server and co-hosting.
This change (which is largely mechanical) introduces a new service, `IComponentAvailabilityService`, that is used to determine what projects a component or tag helper is available within. The intention is that this service contains the behavior difference between the language server and co-hosting rather than relying on …
> Replace ISolutionQueryOperations in hover with a dedicated service

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RazorSyntaxNodeExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/CSharpFormatter.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/HtmlFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/11372
When you assume, you make a fool out of people who use the `.Single()` method and expect a good time.
> Fix a couple of exceptions encountered when formatting documents with preprocessor directives

- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentFormattingTest.cs
Some formatting issues fixed by the new engine (and one that seems to work in both, so I just added a test to prove it)
Fixes https://github.com/dotnet/razor/issues/9254
Fixes https://github.com/dotnet/razor/issues/6150
Fixes https://github.com/dotnet/razor/issues/9119
Fixes https://github.com/dotnet/razor/issues/9711
> Create some more formatting tests

- src/Shared/Microsoft.AspNetCore.Razor.Serialization.Json/JsonDataWriter.cs
- src/Shared/Microsoft.AspNetCore.Razor.Serialization.Json/ObjectWriters.cs
- src/Shared/Microsoft.AspNetCore.Razor.Serialization.Json/ObjectWriters_TagHelpers.cs
Noticed this while doing the preprocessor symbols, and was reminded of it in the working group meeting.
These are all immutable arrays, but were calling a serialize method that took an `IReadOnlyList`, so would have boxed an enumerator and not handled default.
> Use the overload that takes an immutable array in serailization

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/EmbeddedGrammars/aspnetcorerazor.tmLanguage.json
This fixes https://github.com/dotnet/razor/issues/11249.
The problem here is that curly braces are not required within the `case` clause. I added one line in the TextMate syntax to account for this potential usage.
The code change and testing is done on the vscode-csharp repo where Razor TextMate source code is hosted. See original PR: https://github.com/dotnet/vscode-csharp/pull/7929.
Before:
After:
> TextMate bug: recognize codeblocks with curly braces in switch statements

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hosting/ConfigurableLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeTransitionCompletionItemProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionListProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RemoteClientInitializationOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Completion/OOPRazorCompletionItemProviders.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Initialization/RemoteLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteServiceInvoker.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioLanguageServerFeatureOptions.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Workspaces/TestLanguageServerFeatureOptions.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeTransitionCompletionItemProviderTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/RazorCompletionListProviderTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTestBase.cs
We need to avoid specifying explicit commit characters in VS Code as there is no soft selection and typing when completion list is up is much more likely to commit wrong items. This is especially true when commit characters are specified explicitly in some Razor completion items to work around some of the VS completion quirks. We can do so by defining a new flag and passing it from VS Code to rzls to specify the desired commit character set.
There will be a corresponding PR in VS Code to actually pass the new flag.
-
Fixes:
https://github.com/dotnet/razor/issues/10601
> Fix bad completion commit in vs code

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/Formatting/TestFiles/Expected/FormatOnPaste.cshtml
I realised we could be waiting a while before the integration test machines are updated and get the new formatting engine, so lets see some green for a while. Easy enough to revert this PR once the test starts failing again.
> Fix test output

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/RazorFormattingPass.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentFormattingTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2347107
First commit fixes the bug in the new formatting engine where we sometimes create overlapping edits, and instead now we drop those edits on the floor, so at least most of the file will format correctly.
Second commit then fixes the actual formatting issue with the code in hand, which means we no longer have overlapping edits in the first place.
> Don't create overlapping changes when doing additional formatting

- .vscode/extensions.json
When I opened razor using VSCode for a quick change, I noticed that we recommending a depcricated extention (TSLink). So I am changing to the the recommended Microsoft Repalcement (ESLint). Both owned by Microsoft.
> Change recommended VS extension to ESLint

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
targeting dev17.14 cherry picked from https://github.com/dotnet/razor/pull/11416
> [Dev17.14] fuse on by default

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/CompilationHelpers.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteServiceInvoker.cs
This fixes a bug in `RemoteServiceInvoker` that can cause its initialization step to be cancelled incorrectly, leaving it in a bad state. In this state, tag helpers/components never compute in Roslyn OOP for the lifetime of Visual Studio.
I recommend reviewing this change commit-by-commit. The description of the bug and the fix is in the first commit.
CI Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2631845&view=results
Test Insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/607258
> Fix remote service invoker

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/CSharpOnTypeFormattingPass.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/OnTypeFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/11117
Looks like I broke this in https://github.com/dotnet/razor/pull/10855
We were accidentally formatting everything from line 0 to the actual line we cared about, in on type formatting.
> Fix on type formatting line delta calculations

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/SourceTextExtensions.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Mapping/RazorLanguageQueryEndpointTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2347349
This is a bit speculative, but its legal in LSP to send a postion of `(LineCount, 0)` to represent the end of the document, but Roslyn will throw on that. Our `[Try]GetAbsoluteIndex` method handle this edge, so we just need to use it as much as possible.
Some of the errors on this bug fit this scenario, eg "The requested line number 23 must be less than the number of lines 23. (Parameter 'Line')"
> Make sure we go through GetAbsolutePosition to handle LSP edge cases

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Models/WrapAttributesCodeActionParams.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/RazorCodeActionFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/WrapAttributesCodeActionProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/WrapAttributesCodeActionResolver.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/LanguageServerConstants.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/SR.resx
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.cs.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.de.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.es.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.fr.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.it.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.ja.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.ko.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.pl.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.pt-BR.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.ru.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.tr.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.zh-Hans.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Resources/xlf/SR.zh-Hant.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/CodeActions/RemoteServices.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostCodeActionsEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/4296
> Code action to offer to wrap Html attributes

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.CSharpDocumentGenerator.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentFormattingTest.cs
Just noticed this while mucking around in OrchardCode
> Fix formatting of escaped at signs

- src/Razor/.editorconfig
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Snippets/SnippetInfo.cs
Adding IDE rule 0040 to Razor tooling .editorconfig to enforce the use of accessibility modifiers for all types.
> Enforcing accessibility modifiers

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerControl.xaml.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizer/SyntaxVisualizerToolWindow.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/SyntaxVisualizerMenu.vsct
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.cs.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.de.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.es.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.fr.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.it.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.ja.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.ko.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.pl.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.pt-BR.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.ru.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.tr.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.zh-Hans.xlf
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/xlf/SyntaxVisualizerMenu.vsct.zh-Hant.xlf
Figured this might come in handy, possibly for some specific date in the next 2 weeks.
I tried to make a drop down button instead of just adding a new button, and I couldn't work out how to do it :(
> Add button to view the formatting document to the syntax visualizer

- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.csproj
Contributes to https://github.com/dotnet/sdk/pull/46642
NuGet added a new feature that automatically prunes package and project references that are provided by the shared framework that is targeted.
Resolve the one warning that got emitted when source-building the repository.
> React to NuGet package pruning warnings

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/AutoInsert/IOnAutoInsertProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/IDelegatedCSharpCompletionResponseRewriter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/IFileSystem.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/IDelegatedParams.cs
Fixes build errors in https://github.com/dotnet/sdk/pull/46633
> Remove accessibility modifiers from interface members

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.TestAccessor.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultWindowsRazorProjectHostTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackWindowsRazorProjectHostTest.cs
Fixes https://github.com/dotnet/razor/issues/11482
Explanation, copied from the issue: RCLs don't have an absolute `BaseIntermediateOutputPath`, so we end up seeing `<current directory>\obj` as the obj path, and we have a `Directory.Exists` check that catches if that happens, and falls back to different logic for an RCL. Turns out current directory is the solution folder, and so sometimes that obj path does exist, but it exists for a different project, and then all sorts of fun shenanigans ensue.
> Don't use Directory.Exists to check if a path is relative

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Options/AdvancedOptionPage.cs
Fixes https://github.com/dotnet/razor/issues/7025
Turns out in the old options screen we weren't setting two of the options to honour user choices, and we were also clobbering their choice for one of them every time the screen opened.
> Fix a couple of options in the old options screen

- Directory.Packages.props
- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks.csproj
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Microsoft.AspNetCore.Razor.LanguageServer.csproj
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Microsoft.AspNetCore.Razor.LanguageServer.Test.csproj
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Microsoft.AspNetCore.Razor.Test.Common.Tooling.csproj
Response to https://github.com/dotnet/roslyn/pull/74597 to pave the way for https://github.com/dotnet/razor/pull/10682 once Web Tools inserts.
The break from the Roslyn change is not binary breaking, so no need for dual insertion, and since this change doesn't break anything, we can get this in now, and whenever we happen to bump Roslyn next, there should be no build issues.
> Prevent warnings from new IVTs from Roslyn

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorCompletionBenchmark.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionListProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/DefaultLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Hosting/ConfigurableLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/CompletionTriggerCharacters.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/DelegatedCompletionHelper.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionListProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/LanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RemoteClientInitializationOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Initialization/RemoteLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostCompletionTriggerAndCommitCharacters.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentCompletionEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteServiceInvoker.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/VisualStudioLanguageServerFeatureOptions.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/CompletionListProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/TestDelegatedCompletionListProvider.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/Workspaces/TestLanguageServerFeatureOptions.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentCompletionEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTestBase.cs
VS Code HTML language service is a lot more aggressive with showing low quality matches than VS HTML language service. We cannot use the same completion trigger characters in VS Code as in VS because it causes unwanted completion list with bad completion non-matches to pop up while user types in plain text.
-
Fixes:
https://github.com/dotnet/vscode-csharp/issues/7678
https://github.com/dotnet/vscode-csharp/issues/7871
> Use different comletion trigger character set for VSCode

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/AbstractFilePathService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/ProjectExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RemoteClientInitializationOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Initialization/RemoteLanguageServerFeatureOptions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteProjectSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteFilePathService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Extensions/TextDocumentExtensions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentPullDiagnosticsEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteServiceInvoker.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentPullDiagnosticsTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTestBase.cs
Step one of The Great Unskippening!™
Part of https://github.com/dotnet/razor/issues/10693
It is no longer simply possible to use string manipulation to get a generated C# document path from a Razor document path. The alternative options for what is available differ depending on which process code is running in. Yay! :)
> Unskip cohosting diagnostics tests

- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/RemoteDebugInfoServiceTest.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/DiagnosticTests.cs
Fixes https://github.com/dotnet/razor/issues/8150
Noticed these happened to pass for me today.
> Unskip diagnostic integration tests

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Diagnostics/RazorTranslateDiagnosticsService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Diagnostics/RazorDiagnosticsPublisherTest.cs
TLDR: This was always wrong. The spec doesn't say anything, but VS Code always threw in converting these diagnostics (silently) and VS seems to do the same. 
VS Code had a lot of version bumps in this change https://github.com/dotnet/vscode-csharp/pull/7984
Unfortunately, that changed `vscode-languageclient` from `8.2.0-next.1` to `10.0.0-next.14`. Functionally this wasn't a problem, but it did add a sneaky line here to helpfully let extension developers know they are doing something wrong very loudly [microsoft/vscode-languageserver-node@`release/client/8.2.0-next.1...release/client/10.0.0-next.14`#diff-1442f78812](https://github.com/microsoft/vscode-languageserver-node/compare/release/client/8.2.0-next.1...release/client/10.0.0-next.14#diff-1442f78812d67be25f18d3b5d82e8b4191ae2f939a900ea …
> Don't send invalid ranges for diagnostics if they do not map

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/CodeActions/CodeActionEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/CodeActionsService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostCodeActionsEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTestBase.NetFx.cs
Fixes https://github.com/dotnet/razor/issues/11536
> Fix code actions appearing for the wrong context when invoked from light bulb

- Directory.Build.props
- src/Analyzers/Directory.Build.props
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Microsoft.CodeAnalysis.Razor.Compiler.csproj
- src/Razor/src/Directory.Build.props
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
- src/Shared/Directory.Build.props
﻿Revert symbol related changes (for now)
> Revert symbol related changes (for now)

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorGeneratorResult.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorSourceGenerator.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/ProjectExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Completion/RemoteCompletionService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/DocumentMapping/RemoteDocumentMappingService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteDocumentSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteProjectSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteFilePathService.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/ExtractToCodeBehindTests.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostFindAllReferencesEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostGoToDefinitionEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostGoToImplementationEndpointTest.cs
Fixes a bunch of cohost functionality post source generator hookup
Part of https://github.com/dotnet/razor/issues/10693
> Update document mapping to work with the source generator

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Logging/Handlers/LogMessageInterpolatedStringHandler.cs
A bright eyed young developer recently added a log message to our code, because they wanted to be kind, helpful, and allow Razor tooling developers to help customers track down issues in future. Little did they know that our logging infrastructure was actually the PIT OF DESPAIR in disguise! To save this kind soul, and hopefully avoid their drive for success from being beaten down further that our regular baseline level of despair these days, I have decided to renovate the pit into a pit of success!
Before:
``[LSP][Diagnostics.RazorTranslateDiagnosticsService] [08:20:43.7052932] Dropping diagnostic Microsoft.VisualStudio.LanguageServer.Protocol.SumType`2[System.Int32,System.String]:; expected at csharp range Microsoft.VisualStudio.LanguageServer.Protocol.Range``
After: …
> Make logging fall into the pit of success

- eng/Version.Details.xml
- eng/Versions.props
Use the default from arcade instead.
> Remove references to old xliff-tasks repo from Version.Details.xml

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WrapWithTag/WrapWithTagParams.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/CompletionListMerger.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/JsonHelpers.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostCodeActionsEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_CodeActions.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_Completion.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/CSharpTestLspServer.cs
Now that Web Tools has moved to System.Text.Json we don't need these any more.
Part of https://github.com/dotnet/razor/issues/11588, extracted from https://github.com/dotnet/razor/pull/10682
> Remove some Newtonsoft.Json references and conversions

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/LanguageServer/RazorCompletionBenchmark.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/CompletionListProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionListProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/DelegatedCompletionHelper.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/DesignTimeHelperResponseRewriter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/IDelegatedCSharpCompletionResponseRewriter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/SnippetResponseRewriter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/TextEditResponseRewriter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionListProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/DocumentMapping/IDocumentMappingServiceExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RazorCodeDocumentExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Completion/RemoteCompletionService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/CompletionListProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionListProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/ResponseRewriterTestBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionEndpointTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/RazorCompletionListProviderTest.cs
A lot of the code to compute completion lists is asynchronous in order to call `DocumentContext.GetCodeDocumentAsync(...)`. However, many of these calls can be made synchronous if the `RazorCodeDocument` is computed up front and passed in. In addition, I've updated some methods that have both synchronous and asynchronous paths to return `ValueTask`.
I hope that I don't conflict too badly with @davidwengier's completion work.
CI Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2662887&view=results
Test Insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/619102
> Remove excess async state machines in completion

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.CSharpDocumentGenerator.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentFormattingTest.cs
Fixes https://github.com/dotnet/razor/issues/11622
I timeboxed trying to fix this in the old formatting engine, and failed. Looking forward to seeing the back of it.
> Fix text area formatting in the new formatting engine

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/ExtractToComponentCodeActionProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/GenerateMethodCodeActionProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/WrapAttributesCodeActionProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/RazorCodeActionContext.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/CohostCodeActionsEndpointTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/ExtractToComponentTests.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/WrapAttributeTests.cs
A two-for-one PR!
I noticed Wrap Attributes wasn't working for self-closing input tags when I was recording a video yesterday, and overnight @AdmiralSnyder reported an annoyance with Extract to Component, and they were both small fixes, so here they are.
> Couple of small code actions tweaks

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DocumentFormattingEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DocumentOnTypeFormattingEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/DocumentRangeFormattingEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/HtmlFormatter.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Formatting/IHtmlFormatter.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_HtmlFormatting.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingTestBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/TestHtmlFormatter.cs
Partial fix for the symptoms of https://github.com/dotnet/razor/issues/11643
Turns out there is a bug in our handling of Html documents in multi-target projects, and most likely everything has been quietly failing sometimes. Additionally it turns out that the new formatting engine doesn't format things nicely if we don't get a response from Html, so this PR fixes that, and stops things breaking users documents.
I'll follow up with a proper fix soon.
> Don't format if we didn't get a response from the Html formatter

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotManager.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Discovery/OutOfProcTagHelperResolver.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/ProjectSnapshotManagerTest.cs
I was debugging through `ProjectSnapshotManager` and noticed a couple of issues:
1. Documents won't be cleared from `ProjectSnapshotManager`'s open documents on solution close.
2. The algorithm to request tag helpers from OOP has some undesirable behavior. Essentially, any tag helpers that it had to fetch from OOP using checksums will be added to the end of the result. That can result in cases when the `ProjectWorkspaceState` is updated for a project with exactly the same tag helpers in a different order. This results in `SequenceEquals(...)` returning false when comparing old and new `ProjectWorkspaceState` and all of the documents being invalidated.
CI Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2668868&view=results
Test Insertion: …
> Fix a couple of Razor project issues

- azure-pipelines-official.yml
- eng/TSAConfig.gdntsa
> Update TSA settings main

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/CodeActionsService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Models/RazorVSInternalCodeAction.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/ExtractToCodeBehindCodeActionProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/CodeActions/Razor/RazorCodeActionFactory.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/LanguageServerConstants.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTest.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/CodeActionEndToEndTestBase.NetFx.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ComponentAccessibilityCodeActionProviderTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/CodeActions/Razor/ExtractToComponentCodeActionResolverTest.NetFx.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/CohostCodeActionsEndpointTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/CreateComponentFromTagTests.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/ExtractToCodeBehindTests.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/ExtractToComponentTests.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/GenerateEventHandlerTests.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CodeActions/TypeAccessibilityTests.cs
There was some feedback on Reddit this morning about code action ordering and Extract to Component being a little "in your face". See https://www.reddit.com/r/Blazor/comments/1jjg3bh/am_i_doing_something_wrong_or_is_intellisense_and/mjq7jp3/?context=3 and the rest of the thread in general.
This PR:
* Makes sure Extract to Component always last, since it is offered basically everywhere
* Makes sure Add Using and Fully Qualify are always first, since they're the most likely code actions people want
* Ensures Extract to Code Behind is offered at `$$@code` since previously there would be no light bulb in that situation, but now there is and muscle-memory makes people hit it, which extract the code block to a new component, which is not what they want.
Note that the ordering here is only among …
> Some code actions ordering and cleanup

- Directory.Packages.props
- src/Analyzers/Razor.Diagnostics.Analyzers.Test/Razor.Diagnostics.Analyzers.Test.csproj
- src/Analyzers/Razor.Diagnostics.Analyzers.Test/Verifiers/CSharpAnalyzerVerifier`1+Test.cs
- src/Analyzers/Razor.Diagnostics.Analyzers.Test/Verifiers/CSharpAnalyzerVerifier`1.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Analyzers/AnalyzerIDs.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Analyzers/AnalyzerResources.resx
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Analyzers/ComponentParameterNullableWarningSuppressor.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Microsoft.CodeAnalysis.Razor.Compiler.csproj
- src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/ComponentParameterNullableWarningSuppressorTests.cs
- src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/Microsoft.NET.Sdk.Razor.SourceGenerators.Test.csproj
Adds a suppressor for CS8618 when a component property has `EditorRequired` attached to it.
> Add a suppressor for CS8618

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Extensions/IServiceCollectionExtensions.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/GeneratedDocumentSynchronizer.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Hover/HoverEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LanguageClient/RazorCustomMessageTargetTest.cs
Just removing some code that is now dead, because the language server doesn't even start when cohosting is on.
> Minor cohosting cleanup

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/WrapWithTag/WrapWithTagEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/WrapWithTag/WrapWithTagEndpointTests.cs
Fixes https://github.com/dotnet/razor/issues/11686
> Skip past whitespace on the same line when wrapping with tag

- src/Razor/src/rzls/NamedPipeBasedRazorProjectInfoDriver.cs
Noticed in my VS Code logs that it was constantly reporting `Failed 0 times but things may be back on track`. I don't think they ever got off track :)
> Tweak a log message

- src/Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport/Microsoft.NET.Sdk.Razor.SourceGenerators.Transport.csproj
- src/Compiler/Microsoft.Net.Compilers.Razor.Toolset/Microsoft.Net.Compilers.Razor.Toolset.csproj
- src/Compiler/tools/Microsoft.CodeAnalysis.Razor.Tooling.Internal/Microsoft.CodeAnalysis.Razor.Tooling.Internal.csproj
This change removes SCI from the source-generators directory. This dependency is always resolved by the C# compiler that is loading the generator. Deploying it is just eating up disk space.
> Remove SCI from generators directory

- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/LspDynamicFileProvider.LspTextChangesTextLoader.cs
Helps mitigate https://github.com/dotnet/vscode-csharp/issues/8147
> Allow graceful handling of ArgumentException when trying to apply changes to SourceText in LspTextChangesLoader

- src/Razor/benchmarks/Microsoft.AspNetCore.Razor.Microbenchmarks/ProjectSystem/ProjectSnapshotManagerBenchmarkBase.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectSystem/LspProjectSnapshotManager.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotManager.Dispatcher.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/ProjectSnapshotManager.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/VisualStudioProjectSnapshotManager.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectSystem/WindowsRazorProjectHostBase.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/RazorLSPTextViewConnectionListener.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/RazorStartupInitializer.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/ProjectSystem/TestProjectSnapshotManager.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/DefaultWindowsRazorProjectHostTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackProjectManagerTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/FallbackWindowsRazorProjectHostTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/ProjectSystem/RazorDynamicFileInfoProviderTest.cs
- src/Razor/test/Microsoft.VisualStudio.LegacyEditor.Razor.Test/LegacyRazorTextViewConnectionListenerTest.cs
Dustin pointed out a couple of spots that were missed in the "disable things when cohosting is on" commit in https://github.com/dotnet/razor/pull/11412 and I noticed a slight tweak I could make to one I didn't miss :)
> Don't initialize or dispose if cohosting is on

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/SourceGeneratorProjectItem.cs
- src/Compiler/test/Microsoft.NET.Sdk.Razor.SourceGenerators.Tests/RazorSourceGeneratorTests.cs
When experimenting with CSS scopes in .net lab, I've noticed Razor source generator doesn't react to their updates (its incrementality is broken there). This PR should fix that.
> Check CSS scope when comparing source generator items

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Options/LocDescriptionAttribute.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Options/LocDisplayNameAttribute.cs
These get flagged when building with a recent compiler
> Fix two IDE0055 errors

- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Microsoft.VisualStudioCode.RazorExtension.csproj
- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/DynamicFileInfoProvider.cs
Getting a TextDocument from Roslyn uses ProtocolConversions.GetDocumentFilePathFromUri so we have to match with the file name when returning DynamicFileInfo
> Fix cases where there is a space in the URI

- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.csproj
Apparently this was the cause of restore failures in recent times. Seems to fix them 🤷‍♂️
> Don't set VSIXToolsPath

- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Microsoft.VisualStudioCode.RazorExtension.csproj
Razor side needed after https://github.com/dotnet/roslyn/pull/78286
.roslyn used to contain Microsoft.Extensions.ObjectPool.dll because of the transitive dependency and now it doesn't so it has to be packaged in the .razorExtension
> Add something previously published by Roslyn

- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/LanguageServer/CSharpTestLspServerHelpers.cs
Pre-emptive fix for when https://github.com/dotnet/roslyn/pull/78291 comes through
> Explicitly add test language server part

- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/InlayHints/CohostInlayHintEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/InlayHints/CohostInlayHintResolveEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Microsoft.CodeAnalysis.Razor.CohostingShared.projitems
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/InlayHints/RemoteInlayHintService.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostInlayHintEndpointTest.cs
Also fixes a bug that I noticed where we add a hint that would be invalid if inserted as an edit. Wasn't a problem in VS since VS doesn't support double clicking on hints.
> Support inlay hints in cohosting in VS Code

- .github/policies/resourceManagement.yml
Add 'resourceManagement' rules for breaking-change, just like https://github.com/dotnet/roslyn/pull/77948
> Add 'resourceManagement' rules for breaking-change

- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/MappingService.cs
Collision when implicit usings were removed
> Fix the build

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Debugging/ValidateBreakpointRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_ValidateBreakpoint.cs
Fixes https://github.com/dotnet/razor/issues/11789
When typing fast, sometimes we can't sync the document because the request is old, and in those cases we return null. Most of the time this is fine, but for breakpoints null means "please remove this breakpoint" which is bad.
> Don't return null if we couldn't sync the document for breakpoint validation

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Mapping/RazorMapToDocumentRangesEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Mapping/RazorMapToDocumentRangesEndpointTest.cs
It turns out when converting a range to a span you need to use the right SourceText...
> Fix span calculation on RazorMapToDocumentRangesEndpoint

- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Diagnostics/CohostDocumentPullDiagnosticsEndpointBase.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/GoToImplementation/RemoteGoToImplementationService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/SignatureHelp/RemoteSignatureHelpService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentPullDiagnosticsEndpoint.cs
- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Endpoints/DocumentPullDiagnosticsEndpoint.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentPullDiagnosticsTest.cs
> Fix some hardcoded values in cohosting

- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/FindAllReferences/CohostFindAllReferencesEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Formatting/CohostDocumentFormattingEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Formatting/CohostOnTypeFormattingEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Formatting/CohostRangeFormattingEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/LinkedEditingRange/CohostLinkedEditingRangeEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Microsoft.CodeAnalysis.Razor.CohostingShared.projitems
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Navigation/CohostGoToDefinitionEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Navigation/CohostGoToImplementationEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Rename/CohostRenameEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/SignatureHelp/CohostSignatureHelpEndpoint.cs
- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/VSCodeFilePathService.cs
This is the rest of them!
C# extension side: https://github.com/dotnet/vscode-csharp/pull/8249
> Port remaining cohosting endpoints to VS Code

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/ISnippetCompletionItemProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_Completion.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Snippets/SnippetCompletionItemProvider.cs
SnippetCompletionItemProvider was changed to export as ISnippetCompletionItemProvider but not updated in RazorCustomMessageTargets
> Fix MEF Composition Error

- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/HtmlDocumentServices/HtmlDocumentSynchronizer.SynchronizationRequest.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/HtmlDocumentServices/HtmlDocumentSynchronizer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/HtmlDocumentServices/IHtmlDocumentPublisher.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/HtmlDocumentServices/IHtmlDocumentSynchronizer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/HtmlDocumentServices/SynchronizationResult.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Microsoft.CodeAnalysis.Razor.CohostingShared.projitems
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentPublisher.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlRequestInvoker.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/HtmlVirtualDocument.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/HtmlVirtualDocumentSnapshot.cs
- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Endpoints/RazorDocumentClosedEndpoint.cs
- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/HtmlDocumentPublisher.cs
- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/HtmlRequestInvoker.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/HtmlDocumentSynchronizerTest.cs
Goes with https://github.com/dotnet/vscode-csharp/pull/8259
This adds a notification for VS Code to tell us that a Razor file has closed, so we can clear our cache, and also adds checksum matching to Html requests in VS and VS Code so we can ensure we're not out-of-sync.
> Improve document handling in VS Code and cohosting

- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/HtmlDocumentServices/HtmlDocumentSynchronizer.SynchronizationRequest.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/HtmlDocumentServices/HtmlDocumentSynchronizer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/HtmlDocumentServices/IHtmlDocumentSynchronizer.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/HtmlDocumentRemoveListener.cs
- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Endpoints/RazorDocumentClosedEndpoint.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/HtmlDocumentSynchronizerTest.cs
I'm not honestly sure what I was thinking in not passing on the cancellation token. The idea of "well we might need this work later, lets run it in the background" might have made some sense (though likely not, as Roslyn essentially does the same sort of thing with its compilation tracker) but since none of the tasks here are fire and forget, nor do we want them to be, there was never any real cancellation.
It's purely anecdotal, but this seems to have fixed (or at least reduced) the amount of cancellation happening (and erroneously logged errors due to cancellation), I think because new requests would come in (or things might have been timing out) after old requests were cancelled by the client, but of course we never honoured that.
> Allow html requests to be properly cancelled

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/CodeGeneration/CSharpCodeWriterTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/CodeWriter.cs
This is a particularly subtle bug that requires a chunk (or remaining bit of a chunk) and the destination buffer being _exactly_ the same size. When this happens, the following sequence occurs:
1. `source.Length` and `destination.Length` are exactly aligned. This means that we do not enter the `if` on line 450, and `endOfChunkWritten` will be true.
2. We slice `destination` by `source.Length`. This leaves us with a `destination` that has 0 elements, and `IsEmpty` is true.
3. Because `endOfChunkWritten` is true, we enter the `if` on line 466. This increments us to the next chunk.
4. On line 472 (in the before diff), `destination.IsEmpty` is true, so we enter the `if`, and break out of the loop, never reseting `charIndex` to 0.
5. 4 happens again, this time on line 480 (in the before diff). …
> Fix aligned buffer write

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/DefaultRazorProjectFileSystem.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/CompilationHelpers.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/IDocumentSnapshotExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/Legacy/ILegacyDocumentSnapshot.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Discovery/ProjectStateUpdater.cs
- src/Razor/src/Microsoft.VisualStudio.LegacyEditor.Razor/ImportDocumentManager.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestRazorProjectService.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/ConditionalFactAttribute.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.Test/PathUtilitiesTests.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PathUtilities.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/SpanExtensions.cs
Fixes [AzDO 2477693](https://devdiv.visualstudio.com/DevDiv/_queries/edit/2477693/?queryId=25fb5e55-8826-41b9-849a-30c1cf2d9f51)
It is a perfectly valid scenario to use a file rooted outside of the project containing it. For example, a NuGet package might add Razor files as content along with "TargetPath" metadata to a project. However, recent changes broke this scenario.
The incorrect change was to start calling `RazorProjectFileSystem.GetItem(...)` with the physical file path of a document. This is almost never correct because `DefaultRazorProjectFileSystem.GetItem(...)` will throw if the path passed in is rooted outside of the project root. Instead, it's more correct to pass in the document's target path, which is essentially a "logical path" to the file under the project root. When …
> Tooling: Don't throw exceptions when generating code for file rooted outside of project

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/DefaultRazorProjectFileSystem.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/CompilationHelpers.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/IDocumentSnapshotExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/ProjectSystem/Legacy/ILegacyDocumentSnapshot.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Discovery/ProjectStateUpdater.cs
- src/Razor/src/Microsoft.VisualStudio.LegacyEditor.Razor/ImportDocumentManager.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestRazorProjectService.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/ConditionalFactAttribute.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.Test/PathUtilitiesTests.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PathUtilities.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/SpanExtensions.cs
Backport of #11864 to release/dev17.14
- Manual testing of scenario with known repro project. The issue is present without the fix and resolved with the fix.
- Tested mainline scenarios, such as OrchardCore and MudBlazor. These continue working with the fix.
Medium. This affects how every Razor file is compiled in Visual Studio at design-time. However, this risk is mitigated by testing large solutions such as OrchardCore and MudBlazor.
> [release/dev17.14] Tooling: Don't throw exceptions when generating code for file rooted outside of project

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Debugging/DataTipRangeHandlerEndpoint.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/CustomMessageNames.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/DelegatedTypes.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Protocol/LspInitializationHelpers.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Endpoints/RazorCustomMessageTarget_DataTipRange.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Debugging/DataTipRangeHandlerEndpointTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/SingleServerDelegatingEndpointTestBase.TestLanguageServer.cs
Implement textdocument/_vs_dataTipRange lsp message which allows the vs debugger to better handle showing tooltips for the returned ranges.
This is my first PR into razor since joining the team, so I'm expecting/hoping for lots of feedback about these changes as I'm still just getting a feel for the codebase. This change is fairly simple, adding a new endpoint for _vs_dataTipRange, and forwarding the request to the csharp lsp implementation. AbstractRazorDelegatingEndpoint is extended to hook into the existing delegating infrastructure.
Fixes https://github.com/dotnet/razor/issues/6688, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2459195
> Improve debugging tooltip support

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/VisualStudioLogging.cs
Add a fallback to path detection in integration tests to handle the case where the hive path is not found.
> Add a fallback to hive detection in integration tests

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/DefaultRazorTagHelperBinderPhaseTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/DefaultRazorTagHelperContextDiscoveryPhase.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/ReadOnlyMemoryOfCharComparer.cs
Customer feedback ticket shows ~40% of CPU costs are in this method. Of the 33 seconds of CPU time in this method, 21 seconds are in it's calls to GetTypeNamespace and GetSpanWithoutGlobalPrefix.
VisitRazorDirective is called many times (we'll call that number 'l'), depending on the number of directives in the page. Each call costs O(m x n) where m is the number of import statements in the page and n is the number of directives that aren't fully qualified. Evidently, for this customer on this page, this O(l * m * n) is too much.
1) GetTypeNamespace -- Reduced to O(n) calls by storing it's result in _nonFullyQualifiedComponents 
2) GetSpanWithoutGlobalPrefix -- Reduced to O(l * m) by moving outside the innnermost loop
Fixes: https://developercommunity.visualstudio.com/t/Razor-Development:-3 …
> Reduce costs in ComponentDirectiveVisitor.VisitRazorDirective

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/AbstractRazorCompletionFactsService.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs
When we have @ symbol in front of existing = symbol in an attribute, we weren't getting directive attributes in the completion. We are adding one more case to check to AdjustSyntaxNodeForWordBoundary to fix this.
-This is another case where replacing Locate with FindInnermostNode caused an issue in one of the edge cases. If you already have an existing @="" attribute and you tried typing after @, you didn't get any of the directive attributes, e.g. @onclick. This PR adds anothe adjustment to account for this case.
Fixes:
https://github.com/dotnet/razor/issues/11890
> Fixes one of the cases in directive attribute completion

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/AbstractRazorEditorTest.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/RazorProjectSystemInProcess.cs
This doesn't necessarily make them all pass, but they at least get to the point of running the test. I did a quick check of a FAR test and it passes locally with these changes.
> Unblock integration tests from even starting if cohosting is on

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/TextLineExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.CSharpDocumentGenerator.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.LineInfo.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/Passes/New/CSharpFormattingPass.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/RazorFormattingService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/DocumentFormattingTest.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/FormattingTestBase.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Formatting_NetFx/TestRazorFormattingService.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/FormattingTestBase.cs
Fixes the other reported issue in [developercommunity.visualstudio.com/t/Format-Document-in-Razor-pages-no-longer/10903159](https://developercommunity.visualstudio.com/t/Format-Document-in-Razor-pages-no-longer/10903159)
Fixes [devdiv.visualstudio.com/DevDiv/_workitems/edit/2471065](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2471065)
Allows users to have Roslyn configured for K&R style braces (ie, on the same line), even though its ugly 😛
> Handle when Roslyn removes newlines while formatting

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/TagHelperParseTreeRewriter.cs
Tiny allocation improvement in TagHelperParseTreeRewriter.Rewriter.CurrentTagHelperTracker
The FirstOrDefault Linq usage was shown to be allocating about 9 MB (0.1%) in the typing scenario in the razor speedometer test. Small win for a small fix.
> Tiny allocation improvement in TagHelperParseTreeRewriter.Rewriter.CurrentTagHelperTracker

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/InternalSyntax/MarkupEndTagSyntax.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/InternalSyntax/MarkupStartTagSyntax.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/InternalSyntax/RazorDirectiveSyntax.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/MarkupMinimizedTagHelperAttributeSyntax.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/MarkupMinimizedTagHelperDirectiveAttributeSyntax.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/MarkupTagHelperAttributeSyntax.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/MarkupTagHelperDirectiveAttributeSyntax.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/RazorDirectiveSyntax.cs
Each caller changed was allocating more than necessary:
1) List object created
2) If GetAnnotations isn't empty, there was an array allocated in the list 
3) The Add calls would always allocate (even when constructed with a non-empty GetAnnotations result) 
4) ToArray allocation
Instead, there is just a single array allocation.
I don't expect this to have a huge effect, but there are 35 MB of List/array of SyntaxAnnotations allocated in the speedometer trace I'm looking at during the typing scenario (about 0.5% of allocations)
...
> Reduce allocations in calls to WithAnnotationsGreen

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/ChildSyntaxList.Enumerator.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/ChildSyntaxList.cs
This is a port of https://github.com/dotnet/roslyn/pull/73650 to Razor
The general idea behind this PR is that calls to getting items in a syntax list are typically done sequentially, and thus walking the full children of a node is often not necessary.
See the Roslyn PR for detailed performance analysis that was done upon the roslyn investigation.
In the roslyn speedometer test profile that I'm looking at, 0.8% of CPU is spent in ChildSyntaxList.ItemInternal (1.8 seconds of CPU), so this optimization is worth bringing over from Roslyn.
> ChildSyntaxList.ItemInternal optimization

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/DefaultRazorIntermediateNodeLoweringPhase.cs
Reduce allocations in LegacyFileKindVisitor.VisitMarkupTagHelperAttribute
This method shows up in the typing scenario in the razor lsp typing speedometer test as 1.8% (133MB) of allocations. This gets rid of about 1/6th of those allocations, so about a 0.3% reduction in total.
Changes are limited to a single method, but are roughly:
1) Get rid of Linq WhereArrayIterator allocations by manually walking the IAs
2) Get rid of the lambda closures that these methods were taking in
3) Get rid of the loop needing to call the First(...) method and it's lambda allocation
*** Highlighted allocations should be removed by this change ***
> Reduce allocations in LegacyFileKindVisitor.VisitMarkupTagHelperAttribute

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/HtmlTokenizer.cs
Razor only caches a limited number of green SyntaxTokens--specifically those that have different text, such as identifiers. However, it doesn't cache green SyntaxTokens will well-known text, even though those can always be shared if they don't have any diagnostics. This PR introduces a cache for SyntaxKind to SyntaxToken to the HTML tokenizer for tokens with well-known text.
Note: This only addresses the HTML tokenizer and C# will be handled separately. Because some SyntaxKind values are shared across HTML and C# but have different text (like SyntaxKind.Equals -- "=" in HTML and "==" in C#), it'll take a more significant change to solve this in a unified way.
----
CI Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2724900&view=results
Toolset Run: …
> HtmlTokenizer: Cache tokens with well-known text

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LspEditorFeatureDetector.cs
> Stop spamming the activity log

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/Syntax/SyntaxListTests.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/TagHelperBlockRewriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/GreenNode.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxFactory.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxList.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxListOfT.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxList`1.Enumerator.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxList`1.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxRewriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxTokenList.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxUtilities.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.Test/ImmutableArrayExtensionsTests.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.Test/PooledObjects/PooledArrayBuilderTests.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/ImmutableArrayExtensions.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/PooledObjects/PooledArrayBuilder`1.cs
I noticed that Razor's new `SyntaxTokenList` always creates a new array of `ArrayElement<GreenNode>` whenever a mutation method is called, even if there are few enough elements that an array is unnecessary. This pull request addresses that and brings the work done in `SyntaxTokenList` to `SyntaxList<TNode>`. Here is a summary of the changes:
- Introduce `ImmutableArray<T>.Builder.InsertRange(...)` extension method that takes a `ReadOnlySpan<T>`. For some reason, there's an `AddRange` overload for `ReadOnlySpan<T>` but no matching `InsertRange` overload.
- Add `PooledArrayBuilder<T>.InsertRange(...)` methods.
- Update `SyntaxTokenList` to use `PooledArrayBuilder<SyntaxToken>` for mutation operations. This should result in fewer `ArrayElement<GreenNode>[]` allocations.
- Bring …
> Compiler: Optimize SyntaxList<TNode>, SyntaxTokenList and PooledArrayBuilder<T> operations

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionItemResolver.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionListProvider.cs
- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/RazorCompletionEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Completion/CohostDocumentCompletionEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Completion/CohostDocumentCompletionResolveEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/CompletionListMerger.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/DelegatedCompletionHelper.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionListProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionResolveData.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/VSInternalCompletionItemExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/VSInternalCompletionListExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/VSInternalCompletionSettingExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/RazorFormattingService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Completion/RemoteCompletionService.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.NetFx.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/RazorCompletionListProviderTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentCompletionEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTestBase.cs
Fixes https://github.com/dotnet/razor/issues/11840
Two main bits to this change:
1. Roslyn uses a command to perform text edits in VS Code, so this extends our text edit mapping to support that
2. Roslyn uses the completion list `ItemDefaults.Data` for VS Code, and all of our data merging and wrapping didn't support it
I broke things up into lots of commits because it was lots of little changes in lots of places, so might be easier to review that way.
> Fix override completion in VS Code for Cohosting

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/GreenNode.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxNodeExtensions.cs
This method was creating a new StringWriter on every invocation. On net framework, each StringWriter incurs an additional char array allocation during construction. Instead, add a pool for stringwriters in GreenNode to avoid these allocations on every call. This reduced allocations spent under this method during the typing scenario in the razor lsp speedometer test from 3.5% to 1.9%.
Note that it would be nice to have GreenNode.ToString use this optimization too, however it differed (intentionally?) from the caller in SyntaxNodeExtensions.GetContent by passing in the invariant culture to the StringWriter during construction. I don't see ToString called near as often in the profile I'm looking at, so, it didn't seem to warrant creating a separate pool for that method. I would appreciate …
> Reduce allocations under SyntaxNodeExtensions.GetContent

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/CodeGeneration/RuntimeNodeWriterTest.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/RuntimeNodeWriter.cs
This method was creating a StringBuilder with unknown size allocating both a final string and char array along with resize allocations. Instead, calculate the result length and calculate a single char array. This reduced allocations in the typing scenario in the razor lsp speedometer test under this method from about 3.8% to 2.3%.
Speedometer run: https://dev.azure.com/devdiv/DevDiv/_apps/hub/ms-vseng.pit-vsengPerf.pit-hub?targetBuild=10711.132.dn-bot.250612.042302.643010&targetBranch=main&targetPerfBuildId=11746459&runGroup=Speedometer&baselineBuild=10711.80&baselineBranch=main
Allocations before change
Allocations with change
> Optimize allocations under RuntimeNodeWriter.WriteHtmlContent

- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/DocumentSymbol/CohostDocumentSymbolEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/LinkedEditingRange/CohostLinkedEditingRangeEndpoint.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ILspEditorFeatureDetector.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/CSHTMLFilePathToContentTypeProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/RazorFilePathToContentTypeProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/RazorFilePathToContentTypeProviderBase.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LspEditorFeatureDetector.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTest.cs
Fixes https://github.com/dotnet/razor/issues/11941
This change means that if cohosting is on, we'll always use LSP, except for .NET Framework projects which will fall back to the really really legacy legacy editor. That editor has no interaction with any of our code, except the VS editor does send us a couple of LSP methods (because dynamic registration is by file extension, not content type) so we have to be a tiny bit defensive.
> Make cohosting win over legacy editor

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/ClassifiedSpanVisitor.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/ClassifiedSpanVisitor.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/RazorSyntaxTreeExtensions.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Legacy/TagHelperSpanVisitor.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/SourceSpanComputer.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/SpanComputer.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxFactory.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/SyntaxUtilities.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RazorCodeDocumentExtensions.CachedData.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RazorCodeDocumentExtensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/RazorCodeDocumentExtensions_ClassifiedSpans.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/FormattingContext.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/FormattingVisitor.cs
This represents several changes to improve efficiency and reduce allocations in the `ClassifiedSpanVisitor`, `TagHelperSpanVisitor`, and `FormattingVisitor`.
- Pool `ClassifiedSpanVisitor` instances to reduce allocations.
- Move legacy code to the `Legacy` namespace, isolating it from current implementations.
- Avoid creating delegates in `ClassifiedSpanVisitor` and `FormattingVisitor`.
- Add `SpanComputer` helper to avoid creating syntax nodes just to visit them in `ClassifiedSpanVisitor` and `FormattingVisitor`.
- Use pooled array builder for formatting spans to reduce memory pressure.
- Add streamlined (i.e. non-Legacy) versions of `GetTagHelpers` and `GetClassifiedSpans` in tooling. These only produce the data needed to support tooling's GetLanguageKind.
- Other small tweaks
----
CI …
> Compiler + Tooling: Span visitor improvements

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TextDifferencing/TextDiffer.DiffEdit.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/TextDifferencing/TextDiffer.cs
Specifically, provide a factory method for offseting a DiffEdit instead of exposing the DiffEdit ctor
> Apply post-merge feedback from https://github.com/dotnet/razor/pull/11983

- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/Formatting/CSharpSyntaxFormattingOptionsTest_Generator.cs
Turns out there are a bunch of ways to "manually" run a test, and this one happens to break others. Since I don't expect it to be run very often at all, its easiest to just skip it.
> Don't run the test generator from a command line build

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionListProvider.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/RazorCompletionListProviderTest.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/CompletionIntegrationTests.cs
-We had old code that prevented us from even trying to return Razor completion items on deletion. It seems to work well now, so I removed that condition. 
Fixes:
https://github.com/dotnet/razor/issues/11565
> Allow Razor completion items on deletion

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/RazorCodeDocument.cs
I see about 40% of edits within an html scope generate the html document multiple times, primarily due to concurrent RazorCodeCode.GetHtmlDocument requests from the callstacks below (measured on release bits without a debugger attached). As these requests are on the same code document, they can be collapsed into a single request.
*** callstack 1 ***
RazorCodeDocument.GetHtmlDocument
RazorCodeDocumentExtensions.GetHtmlSourceText
GeneratedDocumentSynchronizer.DocumentProcessed
OpenDocumentGenerator.ProcessBatchAsync
*** callstack 2 ***
RazorCodeDocument.GetHtmlDocument
IDocumentMappingServiceExtensions.GetPositionInfo
DelegatedCompletionListProvider.GetCompletionListAsync CompletionListProvider.GetCompletionListCoreAsync
> Avoid concurrent generation of the html document within a razor code document.

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/CodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/RazorHtmlWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/SourceSpan.cs
This pull request is essentially a rewrite of `RazorHtmlWriter` with the following changes:
- Simply span tracking for source mappings.
- Avoid allocating strings when writing whitespace to the `CodeWriter` and reduce the number of writes.
- Avoid allocating strings when writing C# placeholder content (i.e. `~~~` and `/*~~~~~~~*/`).
- Avoid allocating delegates to base visitor methods.
- Fix a bug this change uncovered in the `CodeWriter.Reader.Read(char[], int, int)` implementation that can cause the `SourceText` produced to be one character shorter than expected.
I recommend reviewing commit-by-commit.
----
CI Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2736836&view=results
Test Insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/646317
Toolset …
> Compiler: Avoid allocating strings in the RazorHtmlWriter

- eng/Version.Details.xml
- eng/Versions.props
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Microsoft.CodeAnalysis.Razor.CohostingShared.projitems
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/RazorAnalyzerAssemblyRedirector.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Formatting/FormattingContext.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/AssemblyRedirectorTests.cs
This is the Razor half of https://github.com/dotnet/roslyn/pull/78852
It provides a redirector that will redirect the razor generator and its dependencies.
> Analyzer redirector

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorInitializeEndpoint.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/CohostInitializeReporter.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Microsoft.CodeAnalysis.Razor.CohostingShared.projitems
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/IncompatibleProjectNotifier.cs
- src/Razor/src/Microsoft.VisualStudio.RazorExtension/Microsoft.VisualStudio.RazorExtension.Custom.pkgdef
- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/IncompatibleProjectNotifier.cs
Fixes https://github.com/dotnet/razor/issues/11654
> Report cohost status in initialize telemetry

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/RazorCompletionItem.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/RazorCompletionItemResolverTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/RazorCompletionListProviderTest.cs
- Using snippet insert text will ensure that equals and quotes are added on attribute commit, and cursor is moved to the correct position between double quotes.
Fixes:
https://github.com/dotnet/razor/issues/11395
> Use snippet InsertText in directive attributes to insert equals and quotes

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/Delegation/DelegatedCompletionHelper.cs
-Existing code worked for the most part. The main issue was that parameters for the complex edit command come in as JsonElements in this case and need to be deserialized.
Fixes:
https://github.com/dotnet/vscode-csharp/issues/8310
> Fixing override completion in VSCode when LSP is enabled

- eng/targets/Services.props
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteMEFInitializationService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/RazorServices.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Initialization/RemoteMEFInitializationService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RazorBrokeredServiceBase.FactoryBase`1.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteMefComposition.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Remote/RemoteServiceInvoker.cs
- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Services/VSCodeRemoteServicesInitializer.cs
- src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/RazorServicesTest.cs
- src/Razor/test/Microsoft.CodeAnalysis.Remote.Razor.Test/RemoteMefCompositionTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/TestVsServiceProvider.cs
Fixes https://github.com/dotnet/razor/issues/11830
Code mostly stolen from Todd who stole it from Joey. Mistakes are all me though 😛
> Cache MEF composition in OOP and VS Code

- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestRazorProjectInfoDriver.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/TestRazorProjectService.cs
Going through our tests trying to find the source of the flakiness. This isn't it, but it does throw an exception during language server shut down (method not mocked) so its not exactly helping.
> Fix exception in tests

- src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Completion/Delegation/DelegatedCompletionItemResolver.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.LanguageServer.Test/Completion/Delegation/DelegatedCompletionItemResolverTest.NetFx.cs
Alex didn't get a chance to do this before he had to leave last week.
> Add override completion test for VS Code

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/WrapWithTag/VSInternalWrapWithTagParams.cs
Found via integration tests. The wrap with tag params is a custom type, and without implementing the interface, we weren't updating the Uri to be the Html virtual document correctly.
> Fix wrap with tag under cohosting

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/SourceGenerators/RazorSourceGenerator.Helpers.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Extensions/TextDocumentExtensions.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Tooling/XunitDisposeHook.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/TextDocumentExtensionsTest.cs
Got a new ARM laptop, thought I'd try a little item from my TODO list (https://github.com/dotnet/razor/pull/11788#discussion_r2064001002), ended up worse than I ever expected.
> Remove intermediate strings from hint name calculation

- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Diagnostics/CohostDocumentPullDiagnosticsEndpointBase.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentPullDiagnosticsEndpoint.cs
- src/Razor/src/Microsoft.VisualStudioCode.RazorExtension/Endpoints/DocumentPullDiagnosticsEndpoint.cs
Noticed diagnostics logging looks like this:
```
2025-08-08 10:55:38.751 [trace] [Razor.LanguageClient.Cohost.CohostDocumentPullDiagnosticsEndpointBase`2[[Roslyn.LanguageServer.Protocol.DocumentDiagnosticParams, Microsoft.CodeAnalysis.LanguageServer.Protocol, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35],[Roslyn.LanguageServer.Protocol.FullDocumentDiagnosticReport, Microsoft.CodeAnalysis.LanguageServer.Protocol, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]] Reporting 1 diagnostics back to the client
```
I think that category name is a little long :)
> Fix logging

- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentCodeGenerationTestBase.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Component_WithCssScope/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Component_WithCssScope/TestComponent.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef/TestComponent.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentDesignTimeCodeGenerationTest/Element_WithRef_AndOtherAttributes/TestComponent.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithCssScope/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithCssScope/TestComponent.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithRef/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithRef/TestComponent.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithRef_Nullable/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithRef_Nullable/TestComponent.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithRef_WithChildContent/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/Component_WithRef_WithChildContent/TestComponent.mappings.txt
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/GenericComponent_WithComponentRef_CreatesDiagnostic/TestComponent.codegen.cs
- src/Compiler/Microsoft.AspNetCore.Razor.Language/test/TestFiles/IntegrationTests/ComponentRuntimeCodeGenerationTest/GenericComponent_WithComponentRef_CreatesDiagnostic/TestComponent.mappings.txt
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentDesignTimeNodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentNodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentRuntimeNodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Intermediate/ReferenceCaptureIntermediateNode.cs
Fixes https://github.com/dotnet/razor/issues/12043.
> Add missing `global::` prefix in a `@ref` scenario

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/CodeWriter.WriteInterpolatedStringHandler.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/CodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/CodeWriterExtensions.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/CodeGeneration/IWriteableValue.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/BuilderName.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/BuilderVariableName.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentDesignTimeNodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentNodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentRuntimeNodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/FormNameVariableName.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/RenderModeVariableName.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ScopeStack.Entry.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ScopeStack.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Intermediate/CascadingGenericTypeParameter.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared.Test/Int32ExtensionsTests.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/Int32Extensions.cs
This change is targeted primarily at `ScopeStack` and `TypeInferenceMethodParameter`. Each of these holds onto strings that are created for variable names written during code generation. These variable names all take the form of some well-formed prefix and a suffix generated from int values, i.e. `"__seq0"`. We can avoid allocating these strings by providing lightweight abstractions to hold the bits that change (i.e. the suffix data) and write the data directly.
----
CI Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2771119&view=results
Test Insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/661321
Toolset Run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2771120&view=results
> Compiler: Avoid allocating strings for various variable and parameter names during code generation

- eng/Version.Details.xml
These builds are from the .NET 10.0.1xx channel, after main switched to .NET 11.0.1xx, so they need to be reverted
> Revert commits from bad channel

- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/TaskListTests.cs
As discussed this morning.
Unskipping tracked by https://github.com/dotnet/razor/issues/12142
> Skip test to hopefully get green runs

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/CapabilityCheckResult.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ILspEditorFeatureDetector.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/IProjectCapabilityResolver.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/RazorFilePathToContentTypeProviderBase.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LspEditorFeatureDetector.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/ProjectCapabilityResolver.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/LspEditorFeatureDetectorTest.cs
Makes misc files in VS open with cohosting, when it's on, including the left side of the diff window.
The key here is simply that we can only check for the ".NET Core" capability, but loose files have no capabilities at all, so we have to detect that case specifically.
> Allow cohosting to be used when files aren't in projects

- Directory.Packages.props
Fixes https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-razor/alert/11494973?typeId=6437374
We were getting this dependency transitively through the project system SDK, but I couldn't find which version of that referenced the patched MSBuild dll, and since we were already referencing other MSBuild packages which are new enough, this seemed like the easiest change.
> Reference a patched version of Microsoft.Build.Tasks.Core

- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Diagnostics/CohostDocumentPullDiagnosticsEndpointBase.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentPullDiagnosticsEndpoint.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentPullDiagnosticsTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2566865
If we don't return a report with no diagnostics, VS will assume the last report was correct, so the error list never cleared.
> Make sure we report no diagnostics where there are no diagnostics

- Directory.Packages.props
- eng/Version.Details.props
- eng/Version.Details.xml
- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/Diagnostics/CohostDocumentPullDiagnosticsEndpointBase.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Diagnostics/RazorTranslateDiagnosticsService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Remote/IRemoteDiagnosticsService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Diagnostics/RemoteDiagnosticsService.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/RemoteWorkspaceProvider.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostDocumentPullDiagnosticsEndpoint.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Cohosting/CohostTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/CohostDocumentPullDiagnosticsTest.cs
Fixes https://github.com/dotnet/razor/issues/12142 for cohosting
I just completely missed this when I did diagnostics originally, because we get them for free in the LSP editor.
> Support Task List in cohosting

- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteDocumentSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteProjectSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/SR.resx
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.cs.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.de.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.es.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.fr.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.it.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.ja.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.ko.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.pl.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.pt-BR.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.ru.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.tr.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.zh-Hans.xlf
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Resources/xlf/SR.zh-Hant.xlf
Part of https://github.com/dotnet/razor/issues/11522, but I'm not marking it fixed in case we want to do something more, like forcibly run the compiler and get a code document directly.
> Provide more specific information in cohosting failures

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/TagHelperObjectBuilderCollection`2.cs
Locally, I see about 2/3 of the non-empty ToImmutable calls be of size 1. This just handles that case directly without the need for the pooled data structures or adding to a hashset.
The ToImmutable call shows up as 2.7% of CPU samples during the html completion scenario in the razor cohosting completion speedometer test.
Test insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/668320
A sample old result is in the image below. Generally, the numbers vary a bit from run to run, so I looked at 5 runs with and without this change. As the Build call count did not change, I compared the Build call time vs the total TagHelperObjectBuilderCollection.ToImmutable execution time. If this % increased, then it should be safe to say that the total time spent in …
> Improve TagHelperObjectBuilderCollection.ToImmutable perf in a specific case

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Extensions/INamedTypeSymbolExtensions.Cache.IsViewComponentResult.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Extensions/INamedTypeSymbolExtensions.Cache.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Extensions/INamedTypeSymbolExtensions.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Mvc/ViewComponentTypeVisitor.cs
Cache calculation of whether an INamedTypeSymbol represents a view component. Over the 5 speedometer runs I looked at, the existing calculation averaged 2200 ms of total CPU in the Razor cohosting completion speedometer test. A speedometer run with a CWT cache around this calculation, cut the average cost down to 900 ms.
Test insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/668281
*** example old CPU ***
*** example new CPU ***
> Perf: Cache IsViewComponent results

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Syntax/GreenNode.cs
I see a lot of calls to this where the only non-null slot value is a token, which has a non-allocating ToString implementation.
The numbers from the test insertion were a little hard to decipher. The cohosting test has huge variances in general (which we should try to fix). Of the runs that didn't have the extremely high numbers, it looked like this change reduced allocations under GreenNode.ToString by about 50% while not adding any CPU cost (again, hard to read, but GetSingleSlotValueOrDefault looked like it was an insignificant CPU cost wrt the rest of the ToString impelementation).
Test insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/670195
> Optimize GreenNode.ToString to not potentially not allocate when it has only a single non-null slot value.

- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/Extensions.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/GeneratorRunResult.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteProjectSnapshot.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteSnapshotManager.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/ProjectSystem/RemoteSolutionSnapshot.cs
- src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common.Cohosting/CohostTestBase.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/RetryProjectTest.cs
Fixes the startup issue we have if Razor loses the race condition, and Roslyn caches the generator run result while it's in "cohosting off" mode.
Essentially our snapshot manager, which is our first port of call for "I would like to run this OOP service for this solution snapshot" will not sometimes redirect calls to a forked snapshot, that ensures the generator will have had a chance to re-run after it has seen the cohosting flag turn on. Some minor changes to solution and project snapshots because this could happen while code is in-flight, but after the first requests are done, subsequent requests flow through the system as normal (albeit being silently redirected to the fork) and once almost any change to the project or additional files has happened, the whole "retry project" notion …
> Retry running generators if the project config looks good, but the source generator doesn't produce host outputs

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentDesignTimeNodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentGenericTypePass.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentKeyLoweringPass.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentNodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentReferenceCaptureLoweringPass.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentRuntimeNodeWriter.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Components/ComponentSplatLoweringPass.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Intermediate/ReferenceCaptureIntermediateNode.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Intermediate/SetKeyIntermediateNode.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/Intermediate/SplatIntermediateNode.cs
- src/Shared/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/IntermediateNodeWriter.cs
- src/Shared/Microsoft.AspNetCore.Razor.Utilities.Shared/MemoryBuilderExtensions.cs
This is just a small amount of clean up around a few intermediate nodes.
> Compiler: Small bits of clean up

- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/RazorAnalyzerAssemblyRedirector.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/AssemblyRedirectorTests.cs
Fixes https://github.com/dotnet/vscode-csharp/issues/8621
Added a test and manually patched a repro-ing VS Code instance to confirm it fixes.
> Redirect the older named assembly too

- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/DefaultRazorParsingPhase.cs
- src/Compiler/Microsoft.CodeAnalysis.Razor.Compiler/src/Language/RazorParserOptions.cs
The same RazorSourceDocument for imports gets parsed many times during solution load. This simply holds onto those results so we don't need to reparse the same import document multiple times.
This is just the simplest way I could see to do this, but I don't know this area very well, so if anyone has a better suggestion to reduce these parses, I'm very willing to look into those approaches too. The other approaches I started to dig into other than a CWT ended up changing public apis, so I went this approach with the acknowledgement that I would call out my uncertainty in the PR and ask for other approaches.
This shows a pretty large reduction in both CPU and allocations under DefaultRazorParsingPhase.ExecurtCore. From the test insertion, I see CPU go from 2876 ms (3.9%) to 1412 ms (2.1%). …
> Reduce redundant import tree parsing

- src/Razor/src/Microsoft.CodeAnalysis.Razor.CohostingShared/CohostStartupService.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/CohostActivator.cs
- src/Razor/test/Microsoft.VisualStudio.Razor.IntegrationTests/InProcess/RazorProjectSystemInProcess.cs
Fixes https://github.com/dotnet/razor/issues/12243
Breakpoint placement was working fine, but our IVsLanguageDebugInfo implementation waits for the "LSP server" to activate, so figured we'd better let it know we have :)
> Fix breakpoint placement in cohosting

- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Cohost/SemanticTokensRefreshNotifier.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Options/OptionsStorage.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/LanguageClient/Options/SettingsNames.cs
Fixes https://github.com/dotnet/razor/issues/12260
Fixes https://github.com/dotnet/razor/issues/10200
First commit fixes a stupid bug I introduced which caused our settings to just not work. Sometimes it seems they would migrate from the legacy settings, but it was pretty hit and miss.
In manual testing, I then ran into #10200 which I'd forgotten that I'd logged a while ago, but with the benefit of time now that the old options screen is gone completely, the fix is really easy. Seems the legacy settings were just delayed as compared to UI events in the unified settings experience, but we can now just read directly from unified settings. Then I cleaned up a bit.
> Fix some issues with our options in the new experience

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Completion/DirectiveAttributeCompletionItemProvider.cs
- src/Razor/test/Microsoft.CodeAnalysis.Razor.Workspaces.Test/Completion/DirectiveAttributeCompletionItemProviderTest.cs
Better handle attribute snippet completion in components
This addresses a scenario where completion commit would insert an extra '=' inside the attribute value. For example, committing "@&#8203;ref" via typing '=' in this code 
```HTML+Razor
<p @re />
```
below would end up with the following document contents:
```HTML+Razor
<p @ref="=" />
```
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2581843
> Better handle attribute snippet completion in components

- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/Shared/CohostDocumentHighlightEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/Shared/CohostFoldingRangeEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/Shared/CohostGoToDefinitionEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/Shared/CohostGoToImplementationEndpointTest.cs
- src/Razor/test/Microsoft.VisualStudio.LanguageServices.Razor.Test/Cohost/Shared/CohostInlayHintEndpointTest.cs
Noticed the folding range test was invalid and wrong, and wondered how many other tests might be invalid due to mistakes so decided to fix them all. Turns out they were mostly fine. Of course a whole bunch need to not compile, so didn't put in permanent validation or anything.
> Fix syntax errors in test inputs

- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Logging/AbstractMemoryLoggerProvider.Buffer.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Logging/AbstractMemoryLoggerProvider.Logger.cs
- src/Razor/src/Microsoft.CodeAnalysis.Razor.Workspaces/Logging/AbstractMemoryLoggerProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Logging/MemoryLoggerProvider.cs
- src/Razor/src/Microsoft.CodeAnalysis.Remote.Razor/Logging/TraceSourceLoggerFactory.cs
- src/Razor/src/Microsoft.VisualStudio.LanguageServices.Razor/Logging/MemoryLoggerProvider.cs
The in-memory logger we have has been very useful in diagnosing what is actually going on when looking at a memory dump. Now that a lot of our work happens in the Roslyn OOP, we're missing out on a lot of those log messages.
> Bring our in-memory logger to OOP
